---
title: "집합"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---


{{< include ../../latexmacros.qmd >}}

우리는 여기서 일단 집합에 대해 잘 안다고 가정한다. 

</br>

## 기본 개념

::: {.callout-note appearance="simple" icon="false"}

::: {#def-FA_set_and_element}

#### 집합에의 포함관계

어떤 객체 $a$ 가 집합 $A$ 에 포함되면 $a$ 를 $A$ 의 원소라고 하고 $a\in A$ 라 쓴다. $a$ 가 $A$ 에 포함되지 않을 때는 $a\not\in A$ 라고 쓴다.

::: 
:::

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-FA_subset}

#### 부분 집합, 동일한 집합, 진부분 집합

집합 $A$ 의 모든 원소가 집합 $B$ 의 원소일 때 $A$ 를 $B$ 의 **부분집합(subset)**이라고 하고 $A \subset B$ 라고 쓴다. $A\subset B$ 일 때 $B$ 가 $A$ 를 포함한다고 한다. $A \subset B$ 이고 $B \subset A$ 일 때 $A$ 와 $B$ 를 같다고 하고 $A=B$ 라고 쓴다. $A$ 와 $B$ 가 같지 않을 때 $A \ne b$ 라고 쓴다. $A \subset B$ 이며 $A\ne B$ 일 때 어떤 $A$ 를 $B$ 의 **진부분집합(proper subset)** 이라고 하며 $A \subsetneq B$ 라고 쓴다.


::: 
:::


</br>

$A$ 의 원소들을 $\{\;\}$ 안에 나열하여 표현 할 수 있다. 즉 $A$ 가 $a,\,b,\,c$ 의 세 원소로만 이루어진 집합일 때 

$$
A = \{a,\,b,\,c\}
$$

와 같이 쓸 수 있다. 혹은 집합의 원소가 만족해야 할 성질을 아래와 같이 표현하여 집합을 정할 수 있다.

$$
B=\{x | x \text{ is an even integer}\}
$$


</br>


::: {.callout-note appearance="simple" icon="false"}

::: {#def-FA_union_and_intersection_of_sets}

#### 합집합과 교집합

집합 $A,\, B$ 에 대해 $A$ 와 $B$ 의 합집합 $A \cup B$ 는 다음과 같이 정의된다.

$$
A \cup B = \{x | x\in A \text{ or }x \in B\}
$$

그리고 $A$ 와 $B$ 의 교집합 $A \cap B$ 는 다음과 같이 정의된다.

$$
A \cup B = \{ x | x\in A \text{ and } x \in B\}
$$

::: 
:::

</br>

아래 두 명제는 정의로부터 자명하다. 

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-FA_associativity_of_union_and_intersection}

집합 $A,\,B$ 에 대해 $A \cup B = B \cup A$ 이고 $A \cap B = B \cap A$ 이다. 

:::


</div>

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-FA_commutativity_of_union_and_intersection}

집합 $A,\,B,\, C$ 에 대해 $A \cup (B \cup C) = (A \cup B) \cup C$ 이고 $A \cap (B\cap C) = (A \cap B) \cap C$ 이다. 

:::

</div>
</br>

세 집합의 합집합 혹은 교집합이 순서에 무관하므로 $A\cup B \cup C$ 나 $A \cap B \cap C$ 라 쓸 수 있다.




</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-FA_empty_set}

#### 공집합, 서로소

원소를 하나도 포함하지 않은 집합을 **공집합(empty set)** 이라고 하며 $\varnothing$ 이라 쓴다. 두 집합 $A,\,B$ 가 $A\cap B=\varnothing$ 이면 두 집합을 **서로소** 라고 한다.


::: 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-FA_union_intersection_with_empty_set}

집합 $A$ 에 대해 $A \cap \varnothing = \varnothing$ 이며 $A \cup \varnothing = A$ 이다.

:::

</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-FA_empty_set_is_subset_of_every_set}

공집합은 모든 집합의 부분집합이다.

:::

</div>

::: {.proof}

부분집합의 정의에 의해 $x\in \varnothing \implies x \in A$ 이면 $\varnothing \subset A$ 이다. 공집합의 정의에 의해 $x\in \varnothing$ 은 항상 거짓이므로 위의 명제는 항상 참이다. 따라서 공집합은 모든 집합의 부분집합이다. $\square$

:::

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-FA_diffeence_of_two_sets}

#### 차집합

두 집합 $A,\,B$ 에 대해 $A$ 에만 포함되고 $B$ 에는 포함되지 않는 원소의 집합을 차집합 이라 하며 $A-B$ 로 표현한다. 즉, 

$$
A-B =\{x | x\in A \text{ and }x\not\in B\}
$$

이다. 

::: 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-FA_distribution_law_for_sets}

#### 집합에서의 분배법칙

집합 $A,\,B,\,C$ 에 대해 다음이 성립하며 이를 집합에서의 분배법칙(distribution law) 라고 한다.

$$
\begin{aligned}
A \cap (B \cup C) &= (A \cap B) \cup (A \cap C), \\
A \cup (B \cap C) &= (A \cup B) \cap (A \cup C).
\end{aligned}
$$

:::

</div> 

::: {.proof}
$A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$ 는 다음과 같이 증명 할 수 있다.
$$
\begin{aligned}
x\in A \cap (B \cup C) &\iff x\in A \land x \in (B \cup C) \\
&\iff x \in A \land (x \in B \lor x \in C) \\
&\iff (x\in A \land x \in B) \lor (x\in A \land x \in C) \\
&\iff x\in (A \cap B) \cup (A \cap C)
\end{aligned}
$$

$A \cup (B \cap C) = (A \cup B) \cap (A \cup C)$ 도 같은 방법으로 증명 할 수 있다.

:::

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-FA_complement_of_set}

#### 여집합

어떤 전체집합 $X$ 의 부분집합 $A$ 에 대해 $X-A$ 를 $A$ 의 여집합이라 하고 $A^C$ 혹은 $X\backslash A$ 라 쓴다. 즉

$$
X\backslash A = A^C = X-A
$$

이다. 

::: 
:::

</br>


이제부터 별도로 언급하지 않아도 집합을 언급할 때는 어떤 전체집합의 부분집합임을 가정한다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-FA_difference_and_intersection}

$X$ 의 부분집합 $A,\,B$ 에 대해 $A-B = A \cap B^C$ 이다.

:::

</div>

::: {.proof}

$x\in (A-B) \iff x\in A \land x\not\in B \iff x\in A \cap B^C$ $\square$

:::

</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-FA_complement_of_union_and_intersection}

집합 $A,\,B$ 에 대해 $(A\cup B)^C = A^C \cap B^C$ 이며 $(A \cap B)^C = A^C \cup B^C$ 이다. 

:::
</div>

::: {.proof}

$$
\begin{aligned}
x\in (A\cup B)^C &\iff x\not\in (A \cup B) \iff x\not\in A \land x \not\in B \iff x\in (A^C \cap B^C)  \\
x\in (A \cap B)^C &\iff x\not\in (A \cap B) \iff x\not\in A \lor x\not\in B \iff x\in (A^C \cup B^C) 
\end{aligned}
$$

$\square$
:::

</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-FA_DeMorgrans_law}

#### 드 모르강의 법칙

집합 $A,\,B,\,C$ 에 대해 다음이 성립한다.

$$
\begin{aligned}
A-(B\cup C) &=  (A-B)\cap (A-C),\\
A-(B \cap C) & = (A-B)\cup (A-C).
\end{aligned}
$$

:::
</div>

::: {.proof}

$$
\begin{aligned}
A-(B\cup C) &=  A \cap (B \cup C)^C = A \cap (B^C \cap C^C) = (A\cap B^C)\cap (A\cap C^C) \\
&=  (A-B)\cap (A-C) \\
A-(B\cap C) &= A \cap (B \cap C)^C = A \cap (B^C \cup C^C) =  (A \cap B^C) \cup (A \cap C^C) \\
&= (A-B) \cup (A-C) \qquad \square
\end{aligned}
$$

:::


</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-FA_collection}

#### 집합족(collection, family)과 멱집합 (power set)

집합의 원소가 모두 집합인 집합을 **집합족**이라 한다. 특히 집합 $A$ 의 부분집합의 집합은 집합족으로 $A$ 의 **멱집합** 이라 하며 $\mathcal{P}(A)$ 라 쓴다. 


::: 
:::

집합족 $\Gamma$ 에 대한 합집합과 교집합을 다음과 같이 정의한다. 

$$
\begin{aligned}
\bigcup_{A\in \Gamma} A &= \{x|x \text{ 는 최소한 하나의 } A\in \Gamma \text{ 에 포함된다.}\}, \\
\bigcap_{A \in \Gamma} A &= \{x|x \text{ 는 모든 } A\in \Gamma \text{ 에 포함된다.}\},
\end{aligned}
$$

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-FA_ordered_pair}

#### 순서쌍(ordered pair) 과 좌표(coordinate)

집합 $A,\,B$ 에 대해 $a\in A,\, b\in B$ 일 때 $(a,\,b) = \{ \{a\}, \, \{a, b\}\}$ 를 순서쌍 이라 한다. 이 때 $(a,\,b)$ 에서 $a$ 를 첫번째 **좌표**, $b$ 를 두번째 좌표라고 한다.


::: 
:::

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-FA_ordered_pair}

$a \ne b$ 이면 $(a,\,b) \ne (b,\,a)$ 이다. 
:::

</div></br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-FA_cartesian_product}

#### 데카르트 곱

집합 $A,\,B$ 에 대해 아래와 같이 정의되는 $A\times B$ 를 $A$ 와 $B$ 에 의한 데카르트 곱이라 한다.

$$
A \times B = \{(a,b)| a\in A,\, b\in B\}.
$$

::: 
:::

</br>