---
title: "수열과 급수"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

## 수열(Sequence) 과 급수 (Series)

### 수열의 수렴

수열은 @def-part2_sequence 에서 정의하였다. 급수(series) 는 다음과 같이 정의된다.

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_series}

#### 부분합, 급수, 무한급수

수열 $\langle a_k\rangle$ 에 대해 

$$
s_n = \sum_{k=1}^n a_k
$$

일 때 $s_n$ 을 $\langle a_k\rangle$ 에 대한 **부분합 (partial sum)** 이라고 하며, 부분합으로 정의된 수열 $\langle s_n \rangle$ 을 **급수(series)** 라고 한다. $n \to \infty$ 에서의 $\langle s_n \rangle$ 을 **무한급수 (infinite sereis)** 라고 한다.

::: 
:::

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_convergence_of_series}

#### 수열의 수렴과 발산

거리공간 $X$ 에서 정의된 수열 $\langle a_k \rangle$ 과 어떤 $a\in X$ 를 생각하자. 

$$
\forall \varepsilon>0,\, \exists N\in \mathbb{Z}_+, \text{ s.t. } k \ge N \implies d(a_k,\, a)<\varepsilon
$$

일 때 수열 $\langle a_k \rangle$ 은 $a$ 로 수렴한다고 하며 $\displaystyle \lim_{k \to \infty} a_k = a$ 혹은 $\langle a_k\rangle \to a$ 라고 쓴다. $\langle a_k \rangle$ 이 수렴하지 않으면 발산한다고 한다. 

::: 
:::

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part2_convergence_and_space}

수렴 여부는 거리공간에 의존한다. 예를 들어 $\langle 1/n \rangle$ 은 $[0,\,1]$ 에서 수렴하지만 $(0,\,1]$ 에서는 수렴하지 않는다.

:::

</div>

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_properties_of_convergence_1}

거리공간 $X$ 에서 정의된 수열 $\langle a_k \rangle$ 에 대해 다음이 성립한다.

&emsp;($1$) $\displaystyle \lim_{k \to \infty} a_k = a \iff$ 모든 $a$ 의 근방은 유한개의 $\langle a_k \rangle$ 을 제외한 $\langle a_n\rangle$ 을 포함한다.

&emsp;($2$) 수열의 극한은 유일하다.

&emsp;($3$) 수렴하는 수열은 유계이다.
:::

</div></br>

::: {.proof}

($1$) $\implies$ 는 정의에 의해 자명하다. $a$ 의 임의의 근방 $N_X(a,\,\varepsilon)$ 에 대해 유한개 성분을 제외한 $a_k$ 의 모든 성분이 포함된다고 하자. 유한개의 포함되지 않는 수열 성분 가운데 인덱스가 최대인 것을 $N$ 이라고 하면 $k\ge N \implies a_k \in N_X(a,\,\varepsilon)$ 이므로 $\langle a_k \rangle \to a$ 이다. 


($2$) $a_1,\,a_2$ 로 수렴한다고 하자. 고정된 $\varepsilon>0$ 에 대해 $k \ge N_1 \implies d(a_k,\,a_1)<\varepsilon$ 이며 $k \ge N_2 \implies d(a_k,\, a_2)<\varepsilon$ 이라 하자. $k \ge \max (N_1,\, N_2)$ 이면 $d(a_1,\,a_2)  \le d(a_k,\,a_1)+d(a_k,\, a_2) < \varepsilon$ 이다. 임의의 $\varepsilon>0$ 에 대해 성립해야 하므로 $a_1=a_2$ 이다.

($3$) 고정된 $\varepsilon >0$ 에 대해 $k\ge N \implies d(a_k,\, a)<\varepsilon$ 이다. $m = \min \{a_1,\ldots,\,a_{N-1}\}$ $M = \max \{a_1,\ldots,\, a_{N-1}\}$ 이라 하면

$$
\min (m, a-\varepsilon) \le a_k \le \max (M, a+\varepsilon)
$$

이므로 $\langle a_k\rangle$ 은 유계이다. $\square$

:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_properties_of_convergence_2}

#### 수열과 극한점

거리공간 $X$ 와 $E \subset X$ 를 생각 할 때 다음 두 명제는 동치이다.

&emsp;($1$) $a\in E'$ 이다.

&emsp;($2$) $E\backslash\{a\}$ 에서 정의된 $a$ 로 수렴하는 수열 $\langle a_k\rangle$ 이 존재한다.

:::

</div></br>

::: {.proof}

($1 \implies 2$) $\delta_k = 1/k$ 에 대해 $N_X(a,\, \delta_k) \cap (E\backslash \{a\}) \ne \varnothing$ 이므로 여기서 하나를 선택하여 $a_k$ 로 놓으면 $k=1,\,2,\ldots,\,$ 에 대해 $a$ 로 수렴하는 수열 $\langle a_k\rangle$ 을 구성 할 수 있다.

($2 \implies 1$) 극한점과 수열의 정의를 생각해보면 쉽게 알 수 있다. $\square$


:::

</br>


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_properties_of_convergence_3}

$\mathbb{R}^n$ 에서 정의된 수열 $\langle a_k\rangle,\, \langle b_k \rangle$ 이 각각 $a,\,b$ 로 수렴할 때 다음이 성립한다.

&emsp;($1$) $\displaystyle \lim_{k \to \infty}(a_k+b_k) = a+b$.

&emsp;($2$) $c\in \mathbb{R}$ 에 대해 $\displaystyle \lim_{k \to \infty} (ca_k)= ca$.

&emsp;($3$) $\displaystyle \lim_{k \to \infty} a_k b_k = ab$.

&emsp;($4$) $a\ne 0$ 일 때 $\displaystyle \lim_{k \to \infty} \dfrac{1}{a_k}= \dfrac{1}{a}$.

&emsp;($5$) 어떤 $N \in \mathbb{N}$ 에 대해 $k\ge N \implies a_k \ge 0$ 이면 $a\ge 0$ 이다.

:::

</div></br>

::: {.proof}

($1$) 고정된 $\varepsilon>0$ 에 대해 $k\ge N_1 \implies |a_k - a|<\varepsilon/2$, $k \ge N_2 \implies |b_k- b|<\varepsilon/2$ 인 $N_1,\,N_2$ 가 존재한다. $k \ge \max(N_1,\,N_2)$ 이면

$$
|(a_k+b_k)-(a+b)| \le |a_k -a| + |b_k - b| < \varepsilon
$$

이므로 $\displaystyle \lim_{k \to \infty}(a_k+b_k) = a+b$ 이다.

($2$) $c=0$ 이면 자명하다. $c\ne 0$ 일 때 고정된 $\varepsilon>0$ 에 대해 $k \ge N \implies |a_k - a|<\dfrac{\varepsilon}{|c|}$ 인 $N$ 이 존재한다. 따라서 $k \ge N \implies |ca_k - ca| = |c||a_k -c| < \varepsilon$ 이다.

($3$) 주어진 $\varepsilon>0$ 에 대해 $k \ge N_1 \implies |a_k - a|<\sqrt{\varepsilon}$ 인 $N_1$ 과 $k \ge N_2 \implies |b_k - b|<\sqrt{\varepsilon}$ 인 $N_2$ 가 존재하며 $N = \max (N_1,\, N_2)$ 라 하자. 

$$
a_k b_k  - ab = (a_k-a)(b_k-b) + a(b_k-b)+ b(a_k-a)
$$

인데 $k \ge N \implies |(a_k-a)(b_k -b)|<\varepsilon$ 이며 ($1$) 과 ($2$) 에 의해 $a(b_k-b)$ 와 $b(a_k-a)$ 는 $0$ 으로 수렴하므로 $\displaystyle \lim_{k \to \infty} a_k b_k = ab$ 이다.

($4$) $a\ne 0$ 이므로 $k \ge M \implies |a_k - a|< \dfrac{1}{2}|a|$ 인 $M\in \mathbb{Z}_+$ 이 존재한다. $k > M$ 일 때

$$
|a|-|a_k| \le |a-a_k| = |a_k-a|<\dfrac{1}{2}|a| \implies |a_k|> \dfrac{1}{2}|a|
$$

이다. 또한 주어진 $\varepsilon>0$ 에 대해 $k \ge N_1 \implies |a_k -a| < \dfrac{1}{2}|a|^2 \varepsilon$ 인 $N_1 \in \mathbb{Z}_+$ 이 존재한다. $N = \max (M,\, N_1)$ 이라 하면, 

$$
\left| \dfrac{1}{a_k}- \dfrac{1}{a}\right| =\dfrac{|a_k - a|}{|a_k a|} < \dfrac{|a|^2\varepsilon}{2|a_k a|} < \varepsilon
$$

이므로 $\displaystyle \lim_{k \to \infty}\dfrac{1}{a_k} = \dfrac{1}{a}$ 이다. 

($5$) $a<0$ 이라면 $k \ge N' \implies |a_k- a|<\dfrac{1}{2}|a|$ 인 $N'$ 이 존재한다. $M = \max(N,\,N')$ 이라 하면

$$
k \ge M \implies a_k < \dfrac{1}{2}a < 0
$$

이므로 $k \ge N \implies a_k \ge 0$ 이라는 가정에 모순된다. 따라서 $a\ge 0$ 이다. $\square$

::: 

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_convergence_in_Euclidean_space}

$\mathbb{R}^k$ 에서의 수열 $\boldsymbol{x}_n = ( x_{1, n},\ldots,\, x_{k, n})$ 에 대해 $\boldsymbol{x}_n$ 이 $\boldsymbol{x} = (x_1,\ldots,\,x_k)$ 로 수렴할 필요충분조건은

$$
\lim_{n \to \infty} x_{j, n} = x_j \qquad (1 \le j \le k)
$$

이다.

:::

</div></br>

::: {.proof}

$\displaystyle \lim_{n \to \infty} \boldsymbol{x}_n = \boldsymbol{x}$ 이면 어떤 $\varepsilon>0$ 에 대해 $n \ge N \implies \|\boldsymbol{x}_n - \boldsymbol{x}\| < \varepsilon$ 을 만족하는 $N\in \mathbb{N}$ 이 존재한다. $|x_{j,\, n} -x_{j}| \le \|\boldsymbol{x}_n - \boldsymbol{x}\|$ 이므로 $\langle \boldsymbol{x}_n\rangle$ 이 $\boldsymbol{x}$ 로 수렴하면 $\langle x_{j, n}\rangle$ 은 $x_j$ 로 수렴한다.

역으로 $\displaystyle \lim_{n \to \infty} x_{j, n} = x_j \qquad (1 \le j \le k)$  이면 $\varepsilon>0$ 에 대해 $n \ge N_i \implies |x_{j, n}-x_j|<\varepsilon/k$ 인 $N_i$ 가 존재한다. $N = \max (N_1,\ldots,\, N_k)$ 라고 하면 $n\ge N$ 에 대해 

$$
\|\boldsymbol{x}_n -\boldsymbol{x}\| \le |x_{1, n}-x_1| + \cdots + |x_{k, n}-x_k| < \varepsilon
$$

이므로 $\langle \boldsymbol{x}_n\rangle$ 이 $\boldsymbol{x}$ 로 수렴한다. $\square$

:::

</br>

### 단조 수열과 부분 수열

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_monotonic_sequence}

#### 단조 수열

수열 $\langle a_n \rangle$ 이 $k\in \mathbb{Z}_+$ 에 대해 $a_k \le a_{k+1}$ 일 때 **단조 증가 수열** 이라고 하고 $a_{k} \ge a_{k+1}$ 일 때 **단조 감수 수열** 이라고 한다. 단조 증가 수열과 단조 감소 수열을 **단조 수열** 이라고 한다.

::: 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_bounded_monotonic_sequence}

유계인 단조수열은 수렴한다.

:::

</div></br>

::: {.proof}

$\langle a_n\rangle$ 이 단조 감소 수열이며 유계라고 하자. $a_1$ 은 이 수열의 상한이며 $a$ 를 이 수열의 하한이라고 하자. 즉 $a_n \ge a$ 이다. 임의의 $\varepsilon>0$ 에 대해 $a+ \varepsilon < a_k \le a$ 인 $a_k$ 가 존재한다. 그렇지 않으면 수열의 하한은 $a+\varepsilon$ 보다 크거나 같아야 한다. $a_n$ 이 단조감소 수열이므로 $n\ge k$ 에 대해 $a+\varepsilon < a_n \le a$ 이다. 즉 $\langle a_n \rangle$ 은 $a$ 로 수렴한다. 단조 증가 수열에 대해서도 같은 방법으로 보일 수 있다. $\square$

:::

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_subsequence}

#### 부분수열

수열 $\langle a_n \rangle$ 과 $1 \le n_1 < n_2 < \cdots$ 를 만족하는 자연수에서 정의된 수열 $\langle n_k \rangle$ 을 생각하자. 이 때 $\langle a_{n_k} \rangle$ 을 수열로 생각 할 수 있으며 이를 $\langle a_{n}\rangle$ 의 부분수열이라고 한다.

::: 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_properties_of_subsequence}

거리공간 $X$ 의 옹골집합 $K$ 에서 정의된 수열을 생각하자. 이 수열의 어떤 부분 수열은 $K$ 의 점으로 수렴한다.

:::

</div></br>

::: {.proof}
$\langle a_n \rangle \subset K$ 라고 하자. $\langle a_n \rangle$ 이 유한집합이면 최소한 하나의 $a\in \langle a_n \rangle$ 에 대해 $\{k: a_k = a\}$ 가 무한집합이므로 이 인덱스의 집합으로 부분수열을 만들면 $a$ 로 수렴하는 부분수열이다. 

이제 $\langle a_n \rangle$ 이 무한집합일 경우에 대해 생각하기로 하자. @prp-part2_infinite_subset_in_compact_set_has_limit_point_in_compact_set 의해 $\langle a_n \rangle$ 은 극한점을 가지며, 따라서 $k\in \mathbb{Z}_+$ 에 대해 $N(a,\, 1/k)\cap \langle a_n \rangle$ 은 무한개의 원소를 갖는다. $p_1=1$ 로 하고  $N(a,\, 1/k) \cap \left(\langle a_n \rangle \backslash \{a_1,\ldots,\, a_{p_k}\} \right)$  가운데 $a_m$ 을 골라 $p_{k+1}= m$ 이라고 하자. 그렇다면 $\langle a_{p_k}\rangle$ 은 $a$ 로 수렴하는 부분수열이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-part2_properties_of_subsequence}
$\mathbb{R}^n$ 에서 정의된 유계인 수열은 수렴하는 부분수열을 갖는다.
:::

</div></br>

::: {.proof}

유계인 수열을 포함하는 $n$-cell 은 옹골집합이므로 @prp-part2_properties_of_subsequence 에 의해 수렴하는 부분수열을 가진다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_ubsequential_limit_forms_closed_subset}

거리공간 $X$ 에서 정의된 수열 $\langle a_n \rangle$ 의 부분수열의 극한의 집합은 닫힌 집합이다.

:::

</div></br>

::: {.proof}

$E^\ast$ 를 $\langle a_n \rangle$ 의 부분수열의 극한의 집합이라고 하고 $q$ 가 $E^\ast$ 의 극한점이라고 하자.우선 $a_{n_1}\ne q$ 인 $a_{n_1}$ 을 선택한다. $a_{n_1} \ne q$ 인 $n_1$ 이 없다면 모든 $a_n=q$ 이므로 $E^\ast = \{q\}$ 는 닫힌 집합이다. 따라서 $a_{n_1} \ne q$ 인 $a_{n_1}$ 을 선택할 수 있을 경우만을 고려한다. $\delta = d(a_{n_1},\, q)$ 라 하자. $q$ 는 $E^\ast$ 에서의 극한점이므로 임의의 정수 $i$ 에 대해 $d(p,\,x)< 2^{-i}\delta$ 인 $x\in E^\ast$ 가 존재하며, $x$ 는 $\langle a_n \rangle$ 의 부분수열의 극한이므로 무한개의 $\langle a_n \rangle$ 의 원소를 포함한다. $n_1,\ldots,\, n_{i-1}$ 이 정해졌다고 할 때 $d(x,\, a_{n_i})<2^{-i}\delta$ 인 $a_{n_i}$ 를 정할 수 있다. 따라서 

$$
d(q,\, a_{n_i}) \le d(q,\, x) + d(x,\, a_{n_i}) < 2^{i-1}\delta
$$

이므로 $\langle a_{n_i}\rangle$ 은 $q$ 로 수렴한다. 즉 $q\in E^\ast$ 이므로 $E^\ast$ 는 닫힌 집합이다. $\square$

:::


</br>

### $e$ {#sec-part2_e}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_convergence_of_geometric_series}

#### 등비급수

$0 \le r < 1$ 일 때 $\displaystyle \sum_{k=0}^\infty r^k = \dfrac{1}{1-r}$ 로 수렴하며 $r\ge 1$ 이면 $\displaystyle \sum_{k=0}^\infty r^k$ 는 발산한다.

:::
</div></br>

::: {.proof}

$$
s_n = \sum_{k=1}^n r^k = \dfrac{1-r^{n+1}}{1-r}
$$

임을 안다. $\square$
:::


</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part2_e}

#### $e$

자연로그의 밑 $e$ 는 다음과 같이 정의된다.

$$
e := \sum_{k=0}^\infty \dfrac{1}{k!}
$$

여기서 $0! = 1$ 이다. 우선 $e$ 가 정의되려면 수열이 수렴해야 하므로 수렴함을 보이자. $k\ge 2$ 일 때 $k! \ge 2^{k-1}$ 임은 자명하다. 

$$
\sum_{k=1}^\infty = 1+1 + \dfrac{1}{2!}+ \dfrac{1}{3!} + \cdots \le 1+1 + \dfrac{1}{2} + \dfrac{1}{4} + \cdots = 2+ \sum_{j=1}\dfrac{1}{2^j} = 3
$$

로부터 $e$ 는 유계인 단조증가수열로 정의되었다는 것을 알 수 있으며 이 수열은 수렴하므로 $e$ 가 정의된다. 

이제 $e$ 에 대한 다른 정의가 성립한다는 것을 보이자. $e$ 는 다음과 같이 정의 될 수 있다.

$$
e:= \lim_{n \to \infty} \left(1+ \dfrac{1}{n}\right)^n
$$ 

이제 $a_n = \left(1+ \dfrac{1}{n}\right)^n$, $s_n = \displaystyle \sum_{k=0}^n \dfrac{1}{k!}$ 이라고 하자. $a_n>0$ 이며,

$$
\dfrac{a_{n+1}}{a_n}  =\dfrac{\left(1+\dfrac{1}{n+1}\right)^{n+1}}{\left(1+\dfrac{1}{n} \right)^n} > \dfrac{\left(1+\dfrac{1}{n+1}\right)^{n+1}}{\left(1+\dfrac{1}{n+1} \right)^n} =1+\dfrac{1}{n+1} > 1
$$

이므로 $a_n$ 은 단조 증가 수열이다. 이항정리를 이용하면

$$
\begin{aligned}
a_n &= \sum_{m=0}^n \begin{pmatrix} n \\ m \end{pmatrix} \left(\dfrac{1}{n}\right)^m = \sum_{m=0}^n \dfrac{n!}{m!(n-m)!}\dfrac{1}{n^m} \\
&= 1 + 1+ \sum_{m=2}^n \dfrac{1}{m!} \left(\dfrac{n(n-1)\cdots (n-m+1)}{n^m}\right)  \\
&= 1 + 1+ \sum_{m=2}^n \dfrac{1}{m!} \left(1-\dfrac{1}{n}\right) \cdots \left(1- \dfrac{m-1}{n}\right) \\
&\le 1+ 1+ \sum_{m=2}^n \dfrac{1}{m!} = s_n
\end{aligned}
$$

임을 보일 수 있다. $a_n \le s_n\le e$ 이며 $a_n$ 은 단조 증가 수열이므로 수렴한다.

고정된 $k<n$ 에 대해 $b_n = \displaystyle 1+1+ \sum_{m=2}^k \dfrac{1}{m!} \left(1-\dfrac{1}{n}\right) \cdots \left(1- \dfrac{m-1}{n}\right)$ 라고 하자. $b_n < a_n$ 이며 $\displaystyle \lim_{n \to \infty} b_n \ge s_k$ 이다. 즉, 

$$
e \ge \lim_{n \to \infty} a_n \ge \lim_{n \to \infty} b_n \ge s_k
$$

이며 이 부등식은 모든 $k$ 에 대해 성립하므로 $\displaystyle \lim_{n \to \infty} a_n = e$ 이다. $\square$

:::

</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_e_is_irrational}

$e$ 는 무리수이다.
:::

</div></br>

::: {.proof}


$e$ 가 유리수임을 가정한다. 우리는 일단 $e>2$ 라는 것을 알기 때문에 $e$ 가 유리수라면 $e=p/q$ 인 양의 정수 $p,\,q$ 가 존재한다고 할 수 있다. $s_k = \displaystyle \sum_{m=1}^k \dfrac{1}{m!}$ 라고 하면, 

$$
\begin{aligned}
e-s_q &= \dfrac{1}{(q+1)!}+ \dfrac{1}{(q+2)!} + \cdots \\
&= \dfrac{1}{(q+1)!}\left(1+ \dfrac{1}{q+2} + \dfrac{1}{(q+2)(q+3)} + \cdots \right) \\
&< \dfrac{1}{(q+1)!} \left(1+ \dfrac{1}{q+1} + \dfrac{1}{(q+1)^2} + \cdots \right) \\
&= \dfrac{1}{(q+1)!} \cdot \dfrac{1}{1-\dfrac{1}{q+1}} = \dfrac{1}{q!q}
\end{aligned}
$$


이므로 
$$
0 < q!(e-s_q) < \dfrac{1}{q}
$$
이다. $e=p/q$ 이므로 $q!(e-s_q)$ 는 자연수 이어야 하며 $1/q\le1$ 이므로 모순된다. $\square$
:::

</br>

## 코시 수열

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_series}

#### 코시 수열

거리공간 $X$ 에서 정의된 수열 $\langle a_n \rangle$ 이 임의의 $\varepsilon>0$ 에 대해 어떤 $N\in \mathbb{Z}_+$ 이 존재하여 

$$
m,\, n \ge N \implies d(a_m,\, a_n) < \varepsilon
$$ 

일 때 $\langle a_n \rangle$ 을 코시 수열 이라고 한다.

::: 
:::

</br>

코시 수열 뿐만 아니라 앞으로의 진행에 필요한 집합의 지름이라는 개념과 지름에 관련된 명제를 증명하고 넘어가기로 하자.

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_diameter}

#### 집합의 지름

거리공간 $X$ 의 공집합이 아닌 부분집합 $E$ 에 대해 아래와 같이 정의된 $\text{diam}(E)$ 를 $E$ 의 **지름 (diameter)** 라고 한다.

$$
\text{diam}(E):= \max \{\|x-y\|_X: x,\,y \in E\}. 
$$ {#eq-part2_definition_of_diameter}


::: 
:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_properties_of_diameter}

 거리공간 $X$ 를 생각하자. 

($1$) $E\subset X$ 일 때 $\text{diam}(\overline{E}) = \text{diam}(E)$ 이다.

($2$) $K_n$ 이 $X$ 에서 정의된 옹골집합이며 $n=1,\,2,\ldots,\,$ 에서 $K_{n}\supset K_{n+1}$ 이고 $\displaystyle \lim_{n \to \infty} \text{diam}(K_n)=0$ 이면 $\displaystyle \bigcap_{n=1}^\infty K_n$ 은 오직 하나의 원소로만 이루어졌다.

:::

</div></br>

::: {.proof}

($1$) $E \subset \overline{E}$ 이므로 $\text{diam}(E) \le \text{diam}(\overline{E})$ 이다. $p,\,q \in \overline{E}$ 라고 하자. $\overline{E}$ 의 정의에 의해 임의의 $\varepsilon>0$ 에 대해 $\|p-p'\|<\varepsilon,\, \|q-q'\|<\varepsilon$ 을 만족하는 $p'\,q'\in E$ 가 존재한다. 삼각부등식으로부터 

$$
\|p-q\| \le \|p - p'\| + \| q-q'\| + \|p'-q'\| \le 2\varepsilon + \|p'-q'\|
$$

이므로 $\text{diam}(\overline{E}) \le 2\varepsilon + \text{diam}(E)$ 이다. 임의의 $\varepsilon >0$ 에 대해

$$
\text{diam}(E) \le \text{diam}(\overline{E}) \le 2\varepsilon + \text{diam}(E)
$$

이므로 $\text{diam}(\overline{E}) = \text{diam}(E)$ 이다.

($2$) $K = \bigcap K_n$ 이라고 하자. @prp-part2_finite_intesection_of_compact_sets 에 의해 $K \ne \varnothing$ 이다. $K$ 가 두개 이상의 원소로 이루어졌다면 $\text{diam}(K) >0$ 이며, 따라서 $\displaystyle \lim_{n \to \infty} \text{diam}(K_n) >0$ 이므로 가정에 위배된다. 따라서 $K$ 는 오직 하나의 원소로만 이루어진다. $\square$

:::


</br>

수열의 수렴은 그 수열이 수렴하는 값에 대해 성립하지만 코시 수열은 정의상 수렴하는 값이 없어도 코시 수열인지 여부를 알 수 있다. 수열의 수렴과 코시 수열은 밀접한 관련이 있는데 이제 코시 수열에 대해 알아보기로 하자.

</br>


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-part2_cauchy_sequence}

#### 코시 수열의 성질 

코시 수열은 다음의 성질을 가진다.

&emsp;($1$) 거리공간에서 정의된 수렴하는 수열은 코시 수열이다.

&emsp;($2$) 코시수열은 유계이다.

&emsp;($3$) 코시수열의 어떤 부분수열이 수렴하면 코시수열은 수렴한다.

&emsp;($4$) 옹골집합인 거리공간 $X$ 에서 정의된 코시 수열은 $X$ 위의 한 점으로 수렴한다.



:::

</div></br>

::: {.proof}

($1$) $\langle a_n \rangle$ 이 거리공간 $X$ 에서 정의된 $a$ 로 수렴하는 수열이라고 하자. 임의의 $\varepsilon >0$ 에 대해 $n \ge N \implies d(a_n,\, a)<\varepsilon/2$ 을 만족하는 $N\in \mathbb{Z}_+$ 이 존재하므로 $m,\, n \ge N$ 일 때

$$
d(a_m,\, a_n) \le d(a_m,\, a)+ d(a_n,\, a)< \varepsilon
$$

이다. 즉 수렴하는 수열은 코시 수열이다.

($2$) $\varepsilon>0$ 에 대해 $m,\, n \ge N \implies d(a_m,\, a_n)< \varepsilon$ 인 $N\in \mathbb{Z}_+$ 이 존재하므로 $\{a_1,\ldots,\, a_{N-1}\}$ 과 $a_N-\varepsilon,\, a_N+\varepsilon$ 에 의해 코시수열 $a_n$ 의 한 상계와 하계가 정해진다. 따라서 코시수열은 유계이다.

($3$) 코시수열 $\langle a_n \rangle$ 의 부분수열 $\langle a_{n_k} \rangle$ 이 $a$ 로 수렴한다고 하자. 임의의 $\varepsilon>0$ 에 대헤 $m,\, n \ge N_1 \implies d(a_m,\, a_n)<\varepsilon/2$ 인 $N_1 \in \mathbb{Z}_+$ 이 존재한다. 부분수열이 수렴하므로 $k>K \implies d(a_{n_k},\, a)<\varepsilon/2$ 인 $K\in \mathbb{Z}_+$ 이 존재한다. $K$ 를 충분히 크게 잡아 $n_K \ge N_1$ 이 되게 할 수 있다. 그렇다면 $n \ge n_K$ 일 때

$$
d(a_n,\, a) \le d(a_n,\, a_{n_K})+ d(a,\, a_{n_K}) < \varepsilon
$$

이므로 $\langle a_n \rangle$ 은 $a$ 로 수렴한다. 

($4$) @prp-part2_properties_of_subsequence 과 ($3$) 에 의해 성립한다. $\square$ 

:::

</br>

이로부터 자연스럽게 다음의 결론을 얻는다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-part2_cauchy_sequence_in_Rn}

$\mathbb{R}^n$ 위에서의 코시수열은 수렴한다.
:::
</div> 

</br>

::: {.proof}

코시 수열은 유계이므로 코시 수열 전체를 포함하는 $n$-cell 을 잡을수 있다. $n$-cell 은 옹골집합이므로 수렴한다. $\square$

:::


</br>

앞으로 더 자세하게 다루겠지만 일단 다음을 정의하고 넘어가자.


::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_complete_metic_space}

#### 완비 거리 공간

거리공간 $X$ 에서 정의된 모든 코시 수열이 수렴할 때 이 거리공간을 **완비 거리 공간 (complete metric space)** 라고 한다.

::: 
:::


</br>

## 상극한과 하극한

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_diverge_to_infinite}

#### 무한대로 발산

수열 $\langle a_n \rangle$ 이 모든 양수 $M$ 에 대해 어떤 $N_M\in \mathbb{N}$ 이 존재하여 

$$
n \ge N_M \implies a_n > M
$$

이면 $a_n$ 은 양의 무한대로 발산한다고 하고 $\displaystyle \lim_{n\to\infty} a_n = + \infty$ 혹은 $a_n \to +\infty$ 라고 쓴다. $a_n$ 이 모든 양수 $M$ 에 대해 어떤 $N_M\in \mathbb{N}$ 이 존재하여

$$
n \ge N_M \implies a_n < -M
$$

일 때 $a_n$ 은 음의 무한대로 발산한다고 하고 $\displaystyle \lim_{n\to\infty} a_n = - \infty$ 혹은 $a_n \to -\infty$ 라고 쓴다. 
::: 
:::


</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_limsup_liminf}

#### 상극한과 하극한

위로 유계인 수열 $\langle a_n \rangle$ 의 상극한 $\displaystyle \limsup_{n \to \infty} a_n$ 를 다음과 같이 정의한다.

$$
\limsup_{n \to \infty} a_n := \lim_{n \to \infty} \sup \{a_n,\, a_{n+1},\,a_{n+2},\ldots\}
$$

역시 아래로 유계인 수열 $\langle b_n \rangle$ 의 하극한 $\displaystyle \liminf_{n \to \infty} b_n$ 를 다음과 같이 정의한다.

$$
\liminf_{n \to \infty} b_n  :=\lim_{n \to \infty} \inf \{b_n,\, b_{n+1},\, b_{n+2},\ldots \}
$$

::: 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_properties_of_limsup}

유계인 실수열 $\langle a_n \rangle$ 의 상극한이 $a$ 일 때 다음이 성립한다.

&emsp;($1$) 임의의 $\varepsilon>0$ 에 대해 $n \ge N \implies a_n < a+\varepsilon$ 을 만족하는 $N\in \mathbb{Z}_+$ 이 존재한다.

&emsp;($2$) 임의의 $\varepsilon>0$ 에 대해 $a-\varepsilon < a_n$ 을 만족하는 $n$ 이 무한히 많이 존재한다.

또한 어떤 실수열 $\langle a_n \rangle$ 이 실수 $a$ 에 대해 위의 두 성질을 만족하면 $\displaystyle \limsup_{n \to \infty} a_n = a$ 이다.

:::

</div></br>

::: {.proof}

우선 $\displaystyle a=\limsup_{n \to \infty} a_n$ 일 때 두 명제를 만족한다는 것을 보이자. $x_n = \sup \{a_n,\, a_{n+1},\ldots\}$ 라고 하자. $\langle x_n\rangle$ 은 단조 감소 수열 이다. $\displaystyle \limsup_{n \to \infty} a_n = \lim_{n \to \infty} x_n = a$ 이므로 $n\ge N \implies |x_n - a|<\varepsilon$ 인 $N \in \mathbb{Z}_+$ 이 존재한다.  $\langle x_n \rangle$ 이 단조감소수열이므로 $n \ge N \implies x_n < a+\varepsilon$ 이다. (($1$) 증명 끝) 

만약 유한개의 $n$ 에 대해서만 $a-\varepsilon < a_n$ 라면 어떤 $K\in \mathbb{Z}_+$ 에 대해 $n \ge K \implies a_n < a-\varepsilon$ 이므로 $n \ge K \implies x_n \le a-\varepsilon$ 이 성립한다. 이렇게 되면 $\displaystyle \limsup_{n \to \infty}a_n \le a-\varepsilon$ 이 되어 모순이다. (($2$) 증명 끝)

이제 수열 $\langle a_n \rangle$ 이 두 조건을 만족하면 $\displaystyle \limsup_{n \to \infty} a_n = a$ 임을 보이자. 임의의 $\varepsilon>0$ 에 대해 ($1$) 로 부터 $\displaystyle \limsup_{n \to \infty} a_n \le a+\varepsilon$ 임을 알 수 있다. 또한 ($2$) 로 부터 $\displaystyle a-\varepsilon \le \limsup_{n \to \infty}a_n$ 임을 알 수 있다. 따라서 $\displaystyle \limsup_{n \to \infty}a_n = a$ 이다. $\square$

:::

</br>

같은 방법으로 다음을 보일 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_properties_of_liminf}

유계인 실수열 $\langle b_n \rangle$ 의 하극한이 $b$ 일 때 다음이 성립한다.

&emsp;($1$) 임의의 $\varepsilon>0$ 에 대해 $n \ge N \implies b_n > a-\varepsilon$ 을 만족하는 $N\in \mathbb{N}$ 이 존재한다.

&emsp;($2$) 임의의 $\varepsilon>0$ 에 대해 $b_n< b + \varepsilon$ 을 만족하는 $n$ 이 무한히 많이 존재한다.

&emsp;($3$) 어떤 실수열 $\langle b_n \rangle$ 이 실수 $b$ 에 대해 ($1$), ($2$) 를 만족하면 $\displaystyle \liminf_{n \to \infty} b_n = b$ 이다.

:::

</div></br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-part2_limsup_liminf_limit}

실수열 $\langle a_n \rangle$ 에 대해 다음은 동치이다.

&emsp;($1$) $\displaystyle \lim_{n \to \infty} a_n = a$.

&emsp;($2$) $\displaystyle \limsup_{n \to \infty} a_n = \liminf_{n \to \infty} a_n = a$.

:::

</div></br>

::: {.proof}
(1 $\implies$ 2) 임의의 $\varepsilon>0$ 에 대해 $n \ge N \implies |a_n - a|<\varepsilon$ 이므로 @prp-part2_properties_of_limsup 과 @prp-part2_properties_of_liminf 를 만족한다.

(2 $\implies$ 1) @prp-part2_properties_of_limsup 과 @prp-part2_properties_of_liminf 각각의 1번 조건에 의해 $\displaystyle \lim_{n \to \infty}a_n = a$ 이다. $\square$

:::

</br>

## 중요한 수열들

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part2_sequences}

#### 중요한 수열들

아래의 수열은 많이 사용되는 수열이다.

&emsp;($1$) $\displaystyle p>0 \implies \lim_{n \to \infty} \dfrac{1}{n^p} = 0$.

&emsp;($2$) $\displaystyle p > 0 \implies \lim_{n \to \infty} \sqrt[n]{p}=1$.

&emsp;($3$) $\displaystyle \lim_{n \to \infty} \sqrt[n]{n}=1$.

&emsp;($4$) $\displaystyle p>0,\, a\in \mathbb{R} \implies \lim_{n \to \infty}\dfrac{n^a}{(1+p)^n} = 0$

이제 위 식을 증명해보자.

($1$) $N>(1/\varepsilon)^{1/p}$ 이라 하면 $n>N$ 에 대해 $\left| 1/n^p \right| < \varepsilon$ 이다.

($2$) $p>1$ 일 경우를 먼저 생각한다. $a_n = \sqrt[n]{p}-1$ 이라면 $1+n a_n \le (1+a_n)^n = p$ 이며 $0 < a_n \le \dfrac{p-1}{n}$ 이다. 따라서 $\displaystyle \lim_{n \to \infty}a_n = 0$ 이므로 $\displaystyle \lim_{n \to \infty} \sqrt[n]{p}=1$ 이다. $p=1$ 일 경우는 자명하며 $0<p<1$ 일 경우는 $1/p=q$ 에 대해 생각해보면 된다.

($3$) $a_n = \sqrt[n]{n}-1$ 이라 하자. $n > 2$ 일 경우만 생각해도 된다. $a_n \ge 0$ 이므로 이항정리에 의해 

$$
n = (1+a_n)^n \ge \dfrac{n(n-1)}{2}{a_n}^2
$$

이며 따라서

$$
0 \le a_n \le \sqrt{\dfrac{2}{n-1}}
$$

이므로 $\displaystyle \lim_{n \to \infty} a_n = 0$ 이다. 따라서 $\displaystyle \lim_{n \to \infty} \sqrt[n]{n}=1$ 이다. 

($4$) $k$ 가 $a$ 보다 큰 자연수라 하자. $n>2k$ 일 때

$$
\begin{aligned}
(1+p)^n = \sum_{m=0}^n \begin{pmatrix} n\\m \end{pmatrix} p^m > \begin{pmatrix} n\\k \end{pmatrix} p^k = \dfrac{n(n-1)\cdots (n-k+1)}{k!} p^k 
\end{aligned}
$$

이다. $n>2k$ 이므로 $n(n-1)\cdots (n-k+1)$ 의 각각의 term 은 $n/2$ 보다 크다. 따라서,
$$
(1+p)^n > \dfrac{n^kp^k}{2^k k!}
$$
 이므로 
$$
0<\dfrac{n^a}{(1+p)^n}< \dfrac{2^k k!}{p^k} n^{a-k}
$$
이다. $a-k<0$ 이므로 $\displaystyle \lim_{n \to \infty} \dfrac{n^a}{(1+p)^n} = 0$ 이다. $\square$


:::


</div></br>


## 급수의 수렴과 발산 {#sec-part2_convergence_of_series}

지금부터 다룰 수열과 급수는 $\mathbb{C}^1$ 에서 정의된 수열과 급수이다. $\mathbb{R}^n$ 에서의 급수에 대해서는 별도로 다루기로 한다.

### 코시 판정법 

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-part2_convergence_of_series_1}

#### 코시 판정법 {#sec-cauchy_criterion}

급수 $\sum a_n$ 이 수렴할 필요 충분 조건은 임의의 $\varepsilon > 0$ 에 대해 어떤 $N \in \mathbb{Z}_+$ 이 존재하여 

$$
m\ge n  \ge N \implies \left| \sum_{k=n}^m a_k\right| \le \varepsilon
$$

인 것이다.

:::

</div></br>

::: {.proof}
$s_n = \displaystyle \sum_{k=1}^n a_k$ 라고 하면 위의 조건은 $s_m - s_{n-1}$ 인 코시수열이 된다. @thm-part2_cauchy_sequence 을 보라. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-part2_convergence_of_series_2}

$\sum a_n$ 이 수렴하면 $\displaystyle \lim_{n \to \infty} a_n = 0$ 이다.

:::
</div></br>

::: {.proof}

@thm-part2_convergence_of_series_1 에서 $m=n$ 일 경우.

::: 

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_partial_sum_of_nonnegative_sequence}

음수가 아닌 항으로 이루어진 수열의 급수가 수렴할 필요충분조건은 수열의 부분합이 유계인 수열을 이루는 것이다.

:::

</div></br>

::: {.proof} 

음수가 아닌 항으로 이루어진 수열의 급수는 단조 증가 수열이다. 단조증가 수열이 유계이면 수렴하며(@prp-part2_bounded_monotonic_sequence), 수열이 수렴하면 유계이다. $\square$

:::

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_absolute_convergence}

#### 절대수렴 

수열 $\langle a_n \rangle$ 에 대한 급수 $\displaystyle s_n = \sum_{k=1}^\infty |a_k|$ 가 수렴하면 급수 $\displaystyle \sum_{k=1}^\infty a_k$ 가 절대수렴한다고 한다.

::: 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_convergence_of_series_3}

수열 $\langle a_k\rangle,\, \langle b_k\rangle$ 에 대해

($1$) 어떤 $N \in \mathbb{Z}_+$ 이 존재하여 $k \ge N \implies |a_k |\le b_k$ 이고 $\sum b_k$ 이 수렴하면, $\sum a_k$ 도 수렴한다.

($2$) 어떤 $N \in \mathbb{Z}_+$ 이 존재하여 $k \ge N \implies |a_k |\ge b_k \ge 0$ 이고 $\sum b_k$ 이 발산하면, $\sum a_k$ 도 발산한다.

:::

</div></br>

::: {.proof}

($1$) 코시 판정법(@thm-part2_convergence_of_series_1) 에 의해 $\sum_k b_k$ 이 수렴하면 임의의 $\varepsilon>0$ 에 대해 $N \in \mathbb{Z}_+$ 이 존재하여 $m\ge n \ge N$ 이면 $\displaystyle \sum_{k=n}^m b_k < \varepsilon$ 이며, 따라서 $\displaystyle\sum_{k=n}^m a_k <\varepsilon$ 이다.

($2$) $\sum_k a_k$ 이 수렴한다면 코시 판정법(@thm-part2_convergence_of_series_1) 에 의해 $\sum_k b_k$ 도 수렴해야 하는데 이는 조건에 위배된다. 따라서 $\sum a_k$ 은 발산한다. $\square$

:::

</br>


### 음수가 아닌 수로 이루어진 급수
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_series_of_power_of_2}
수열 $\langle a_k\rangle$ 에 대해 $a_1 \ge a_2 \ge \cdots \ge 0$ 일 때 다음은 동치이다.

&emsp;($1$) $\displaystyle \sum_{k=1}^\infty a_k$ 는 수렴한다.

&emsp;($2$) $\displaystyle \sum_{k=0}^\infty 2^k a_{2^k} = a_1 + 2a_2 + 4a_4 + 8a_8 + \cdots$ 는 수렴한다.

:::

</div></br>

::: {.proof}

$s_n,\,t_k$ 를 다음과 같이 정한다.

$$
\begin{aligned}
s_n &= a_1 + a_2 + \cdots + a_n,\\
t_k & = a_1 + 2a_2 + \cdots + 2^k a_{2^k}.
\end{aligned}
$$

$n<2^k$ 일 때

$$
\begin{aligned}
s_n & = a_1 + \cdots + a_n \\
&\le (a_1) + (a_2 + a_3) + \cdots + (a_{2^k}+ a_{2^k+1} + \cdots + a_{2^{k+1}-1}) \\
& \le a_1 +2a_2 + \cdots + 2^k a_{2^k} = t_k 
\end{aligned}
$$ 

이므로 $s_n \le t_k$ 이다.

$n > 2^k$ 일 때,

$$
\begin{aligned}
s_n &= a_1 + \cdots + a_n \\
&\ge (a_1) + (a_2) + (a_3+a_4) + \cdots + (a_{2^{k-1}+1}+ a_{2^{k-1}+2} + \cdots + a_{2^{k}}) \\
&\ge \dfrac{1}{2}a_1 + a_2 + 2a_4 + \cdots + 2^{k-1}a_{2^{k}} = \dfrac{1}{2}t_k
\end{aligned}
$$

이므로 $s_n \ge \dfrac{1}{2}t_k$ 이다. 이로부터 $\displaystyle \sum_{k=1}^\infty a_k$ 이 유계일 필요충분조건은 $\displaystyle \sum_{k=0}^\infty 2^k a_{2^k}$ 가 유계인 것임을 안다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_convergence_of_1_over_n_p}

$\displaystyle \sum_{k=1}^\infty \dfrac{1}{k^p}$ 는 $p>1$ 일 때 수렴하며 그 외에는 발산한다.
:::

</div></br>

::: {.proof}

$p \le 0$ 이면 $k^p\ge 1$ 이며, 따라서 $\displaystyle \lim_{k\to \infty}\dfrac{1}{k^p} \ne 0$ 이다. @cor-part2_convergence_of_series_2 에 의해 발산한다. $p>0$ 인 경우 @prp-part2_series_of_power_of_2 를 사용하여 증명 할 수 있다. 

$$
\sum_{k=0}^\infty 2^k \cdot \dfrac{1}{2^{kp}} = \sum_{k=0}^\infty 2^{(1-p)k}
$$

이며 $2^{(1-p)}<1 \iff p>1$ 이므로 @prp-part2_convergence_of_geometric_series 와 @prp-part2_series_of_power_of_2 에 의해 $p>1$ 일 때만 수렴하며 나머지 경우에는 발산한다. $\square$

:::

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part2_convergence_of_series_1}

급수 $\displaystyle \sum_{k=2}^\infty \dfrac{1}{k(\log k)^p}$ 는 $p>1$ 에서 수렴하며 나머지 경우에는 발산함을 보일 수 있다.

우리는 $k>1 \implies \log k > 0$ 이며 $\log (k)$ 이 단조증가함수라는 것을 안다. 따라서 $p>0$ 에 대해  $1/(k (\log (k)))^p$ 는 단조감소수열므로 @prp-part2_series_of_power_of_2 를 사용 할 수 있다.

$$
\sum_{k=1}^\infty 2^k \cdot \dfrac{1}{2^k (\log (2^k))^p} = \sum_{k=1}^\infty \dfrac{1}{(k \log 2)^p} = \dfrac{1}{(\log 2)^p} \sum_{k=1}^\infty \dfrac{1}{k^p}
$$

이므로 @prp-part2_convergence_of_1_over_n_p 에 의해 $p>1$ 일 때 수렴하고 $0<p\le 1$ 일 때 발산한다.

$p\le 0$ 인 경우는 $(\log k)^p <1$ 이므로 발산한다. $\square$

:::

</div></br>

### 근 판정법 {#sec-part2_root_criteria}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-part2_series_root_test}

급수 $\sum a_k$ 에 대해 $\displaystyle \alpha = \limsup_{k \to \infty} \sqrt[k]{|a_k|}$ 이라 할 때, 

&emsp;($1$) $\alpha<1$ 이면 $\sum_k a_k$ 은 수렴하며,

&emsp;($2$) $\alpha > 1$ 이면 $\sum_k a_k$ 은 발산하고,

&emsp;($3$) $\alpha=1$ 이면 이 조건만으로 수렴 여부를 정할 수 없다.

:::

</div></br>

::: {.proof}
($1$) $\alpha<1$ 이라 하자. $\alpha< \beta < 1$ 인 임의의 $\beta$ 를 생각하자. @prp-part2_properties_of_limsup 에 의해 $k\ge N \implies \sqrt[k]{|a_k|}<\beta$ 인 자연수 $N$ 이 존재한다. 즉 $k \ge N \implies |a_n|< \beta^n$ 이므로 $\sum_k a_k$ 는 절대수렴한다.

($2$) $\alpha>1$ 이라 하자. @prp-part2_properties_of_limsup 에 의해 $1<\beta<\alpha$ 일 때 무한히 많은 $k$ 에 대해 $|\alpha_k|> \beta^k > 1$ 이다. 따라서 $\sum_k a_k$ 는 발산한다.

($3$) @exm-part2_sequences 에서 $\displaystyle \lim_{k \to \infty} \sqrt[k]{k}=1$ 임을 보였다. 따라서 $\displaystyle \lim_{k \to \infty} \dfrac{1}{\sqrt[k]{k}} = \lim_{k \to \infty} \dfrac{1}{\sqrt[k]{k^2}}=1$ 이다. 그런데 $\alpha=1$ 인 두 수열 $\sum 1/k,\, \sum 1/k^2$ 은 각각 발산하고 수렴한다. (@prp-part2_convergence_of_1_over_n_p) $\square$

:::


</br>

### 비율 판정법 {#sec-part2_ratio_criteria}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-part2_series_ratio_test}

급수 $\sum_k a_k$ 에 대해 

&emsp;($1$) $\displaystyle \limsup_{k \to \infty} \left|\dfrac{a_{k+1}}{a_k}\right| <1$ 이면 수렴한다.

&emsp;($2$) 어떤 $N\in \mathbb{Z}_+$ 에 대해 $k\ge N \implies \left|\dfrac{a_{k+1}}{a_k}\right| \ge 1$ 이면 발산한다.

:::

</div></br>

::: {.proof}

($1$) $\displaystyle \limsup_{k \to \infty} \left|\dfrac{a_{k+1}}{a_k}\right| =\alpha$ 라고 하자. 임의의 $\alpha <\beta< 1$ 인 $\beta$ 에 대해 $k \ge N_0 \implies \left|\dfrac{a_{k+1}}{a_k}\right|<\beta$ 인 $N_0 \in \mathbb{Z}_+$ 이 존재한다(@prp-part2_properties_of_limsup). 임의의 $m\in \mathbb{Z}_+$ 에 대해 $|a_{N_0 + m}|< \beta^m |a_{N_0}|$ 이므로 $\sum_k a_k$ 는 수렴한다. 

($2$) $k \ge N \implies |a_{k+1}|\ge |a_k|$ 이면 $\displaystyle \lim_{k \to \infty}a_k \ne 0$ 이므로 $\sum_k a_k$ 은 발산한다 (@cor-part2_convergence_of_series_2). $\square$
:::

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part2_convergence_test_of_series}

근 판정법으로 판단할수 있지만 비율판정법으로는 판단 할 수 없는 경우를 보자.

&emsp;($1$) $\displaystyle \dfrac{1}{2}+ \dfrac{1}{3} + \dfrac{1}{2^2}+ \dfrac{1}{3^2} + \dfrac{1}{2^3}+ \dfrac{1}{3^3} + \cdots$

&emsp;($2$) $\displaystyle \dfrac{1}{2} + 1 + \dfrac{1}{8} + \dfrac{1}{4} + \dfrac{1}{32} + \dfrac{1}{16} + \dfrac{1}{128} + \dfrac{1}{64} + \cdots$ 



($1$) 의 경우를 보자. $a_{2k-1} = \dfrac{1}{2^k},\, a_{2k}= \dfrac{1}{3^k}$ 이므로,

$$
\begin{aligned}
\limsup_{k \to \infty}  \sqrt[k]{a_k} &= \lim_{k \to \infty} \sqrt[2k]{\dfrac{1}{2^k}} = \dfrac{1}{\sqrt{2}} < 1, \\
\limsup_{k \to \infty} \dfrac{a_{k+1}}{a_k} &=  \lim_{k \to \infty} \dfrac{1}{2}\left(\dfrac{3}{2}\right)^k = +\infty
\end{aligned}
$$

이다. 근 판정법에 따라 $\sum_k a_k$ 은 수렴하지만. 비율판정법으로는 수렴을 판단할 수 없으며 $k \ge N \implies |a_{k+1}|<|a_k|$ 인 $N\in \mathbb{Z}_+$ 도 존재하지 않기 때문에 발산도 판정할 수 없다.

($2$) 의 경우는 $a_{2k-1}= \dfrac{1}{2^{2k-1}}, a_{2n}= \dfrac{1}{2^{2k-2}}$ 이므로

$$
\begin{aligned}
\limsup_{k \to \infty} \sqrt[k]{a_k} &= \dfrac{1}{2},\\
\limsup_{k \to \infty} \dfrac{a_{k+1}}{a_k} &= 2
\end{aligned}
$$

이므로 근 판정법에 의해 수렴하며, 비율판정법으로는 수렴과 발산을 확인 할 수 없다. 

:::

</div></br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_root_test_and_ratio_test}

양수로 이루어진 수열 $\langle a_k \rangle$ 에 대해 다음이 성립한다.

$$
\liminf_{k \to \infty} \dfrac{a_{k+1}}{a_k} \le \liminf_{k \to \infty} {a_k}^{1/k} \le \limsup_{k \to \infty} {a_k}^{1/k} \le \limsup_{k \to \infty} \dfrac{a_{k+1}}{a_k}
$$

:::

</div><br>

::: {.proof}

$\displaystyle \liminf_{k \to \infty} a_k^{1/k} \le \limsup_{k \to \infty} a^{1/k}$ 임을 안다. 따라서 아래의 ($1$) 과 ($2$) 를 보이면 된다. 

&emsp;($1$) $\displaystyle \liminf_{k \to \infty} \dfrac{a_{k+1}}{a_k} \le \liminf_{k \to \infty} {a_k}^{1/k}$ 

&emsp;($2$) $\displaystyle \limsup_{k \to \infty} {a_k}^{1/k} \le \limsup_{k \to \infty} \dfrac{a_{k+1}}{a_k}$

우선 ($1$) 을 보이자. $\displaystyle \alpha = \liminf_{k \to \infty} \dfrac{a_{k+1}}{a_k}$ 라 하자. $\alpha =0$ 이면 trivial 하므로 $\alpha >0$ 인 경우만 생각한다. 임의의 $\varepsilon \in (0,\, \alpha)$ 에 대해 어떤 $N\in \mathbb{Z}_+$ 이 존재하여 

$$
k \ge N \implies \dfrac{a_{k+1}}{a_k} \ge \alpha - \varepsilon > 0
$$ 

이므로(@prp-part2_properties_of_limsup), $m\in \mathbb{Z}_+$ 에 대해 $a_{N+m} \ge a_N(\alpha - \varepsilon)^m$ 이며, 

$$
k \ge N \implies {a_k}^{1/k} \ge  \left(\dfrac{a_N}{(\alpha - \varepsilon)^{N}}\right)^{1/k} ( \alpha - \varepsilon)
$$

이므로, 

$$
\liminf_{k \to \infty} {a_k}^{1/k} \ge \alpha - \varepsilon 
$$

이다. 임의의 $\varepsilon>0$ 에 대해 성립하기 때문에 $\displaystyle \liminf_{k \to \infty} {a_k}^{1/k} \ge \alpha = \liminf_{k \to \infty} \dfrac{a_{k+1}}{a_k}$ 이다. 

($2$) 의 경우는 ($1$) 과 비슷한 방법으로 보일 수 있다. $\square$ 

:::

</br>

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part2_convergence_of_some_series}

다음 급수의 수렴 여부를 알아보자.

($1$) $\displaystyle \sum_{k=1}^\infty \dfrac{2^k}{k!}$.

이 경우 비율판정법을 통해 $k>1$ 인 경우 $\dfrac{a_{k+1}}{a_k} = \dfrac{2}{k+1}<1$ 이므로 수렴함을 알 수 있다. 

($2$) $\displaystyle \sum_{k=1}^\infty \dfrac{k^{1/k}}{k}$.

우리는 $k^{1/k}>1$ 임을 안다. 또한 $\sum_k 1/k$ 가 발산함을 안다. 따라서 발산한다.

($3$) $\displaystyle \sum_{k=1}^\infty a^k k^a,\, (a>0)$

$a>1$ 일 경우는 $a^kk^a > a^k > 1$ 이므로 발산한다. $a<1$ 일 경우 비율판정법을 사용하면

$$
\left(a^kk^a\right)^{1/k} = a \left(k^{1/k}\right)^a \to a <1
$$

이므로 수렴한다.

($4$) $\displaystyle \sum_{k=1}^\infty \left(k^{1/k}-1\right)^k$.

비율판정법으로 $\lim_{k\to \infty} (k^{1/k}-1)=0$ 이므로 수렴한다.


($5$) $\displaystyle \sum_{k=2}^\infty \dfrac{1}{k^p-k^q},\qquad (0<q<p)$.

$\dfrac{1}{k^p-k^q} = \dfrac{1}{k^p}\dfrac{1}{1-k^{q-p}}$ 이다. $\displaystyle \lim_{k \to \infty} k^{q-p}\to 0$ 이므로 충분히 큰 $k$ 에 대해 $k^{q-p}< 1/2$ 이며 

$$
\dfrac{1}{k^p-k^q} < \dfrac{1}{2k^p} < \dfrac{1}{k^p}
$$

이므로 수렴한다.

($6$) $\displaystyle \sum_{k=1}^\infty \dfrac{1}{1+a^k}, \, (a>-1)$.

$a>1$ 이면 $1/(1+a^k)< 1/a^k$ 이고 $\sum 1/a^k$ 가 수렴하므로 수렴한다. $-1< a \le 1$ 이면 모든 항이 모든 항이 $1/2$ 보다 크거나 같으므로 발산한다. 



:::
</div>

</br>

### 멱급수 {#sec-part2_power_series}

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_power_series}

#### 멱급수

수열 $\langle a_n\rangle$ 에 대해 $\displaystyle \sum_{n=0}^\infty a_n z^n$ 꼴로 주어진 급수를 **멱급수(power sereis)** 라고 한다.

::: 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_radius_of_convergence}

멱급수 $\sum a_n z^n$ 에 대해 

$$
\dfrac{1}{R} := \limsup_{n \to \infty} \sqrt[n]{|a_n|}
$$

이라 하자. $|z|<R$ 일 때 멱급수는 수렴하고 $|z|>R$ 이면 멱급수는 발산한다.
:::

</div></br>

::: {.proof}

$$
\sqrt[n]{|a_n z^{n}|} = |z|\sqrt[n]{|a_n|}
$$

이므로 근 판정법(@thm-part2_series_root_test) 을 사용하면 증명된다. $\square$
:::

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-radius_of_convergence}

#### 수렴반경

멱급수 $\sum a_n z^n$ 에 대해 @prp-part2_radius_of_convergence 에서의 $R$ 을 **수렴 반경(radius of convergence)** 이라고 한다.

::: 
:::

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part2_convergence_of_radius}

다음 멱급수에 대한 수렴반경 $R$ 은 다음과 같다.

&emsp;($1$) $\displaystyle \sum n^n z^n \longrightarrow R=0$, 

&emsp;($2$) $\displaystyle \sum \dfrac{z^n}{n!} \longrightarrow R=+\infty$, 

&emsp;($3$) $\displaystyle \sum z^n \longrightarrow R=1$,

&emsp;($4$) $\displaystyle \sum \dfrac{z^n}{n^2} \longrightarrow R=1$.


($1$) $\displaystyle \limsup_{n \to \infty} n = \infty$ 

($2$) 비율판정법을 사용한다. $c_n = \dfrac{z^n}{n!}$ 이라고 하면, $\displaystyle \limsup_{n \to \infty} \dfrac{c_{n+1}}{c_n} = \lim_{n \to \infty} \dfrac{|z|}{n+1} = 0$ 이므로 @prp-part2_root_test_and_ratio_test 에 의해 $R= +\infty$ 이다.

($3$), ($4$) 는 쉽게 보일 수 있기때문에 생략한다. 

:::

</div></br>

## 부분합과 재배열 급수


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_partial_summation_formula}

두 수열 $\langle a_n \rangle,\, \langle b_n \rangle$ 에 대해 $\displaystyle A_n = \sum_{k=0}^n a_k$ 라 하고 $A_{-1}=0$ 이라 하자. $0 \le p \le q$ 일 때

$$
\sum_{n=p}^q a_n b_n = \sum_{n=p}^{q-1} A_n(b_n - b_{n-1}) + A_qb_q - A_{p-1} b_p
$$

이다.
:::
</div></br>

::: {.proof}

$$
\begin{aligned}
\sum_{n=p}^q a_n b_n  &= \sum_{n=p}^q (A_n-A_{n-1}) b_n = \sum_{n=p}^q A_n b_n - \sum_{n=p-1}^{q-1} A_n b_{n+1}\\
&= \sum_{n=p}^{q-1} A_n b_n + A_qb_q - \sum_{n=p}^{q-1} A_n b_{n+1} -A_{p-1}b_p \\
&= \sum_{n=p}^{q-1} A_n (b_n - b_{n+1}) + A_qb_q - A_{p-1}b_p \qquad \square
\end{aligned}
$$

:::

</br>


[1번 조건에서 $\sum a_n$ 이 수렴한다면 $A_n$ 은 유계이다. 그러나 $A_n$ 이 유계라고 $\sum_n a_n$ 이 수렴하지는 않는다. $a_n = (-1)^n$ 을 생각해보라.]{.aside}

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_convergence_of_product_of_sequences}

수열 $\langle a_n \rangle,\, \langle b_n \rangle$ 이 아래의 두 조건을 만족하면 $\sum_n a_n b_n$ 은 수렴한다.

&emsp;($1$) $\displaystyle A_n=\sum_{k=1}^n a_k$ 이 유계인 수열을 이루며,

&emsp;($2$) $\langle b_n \rangle$ 은 $0$ 으로 수렴하는 단조감소 수열이다.

:::
</div></br>

::: {.proof}

$|A_n|<M$ 이라 하자. 임의의 $\varepsilon>0$ 에 대해 $b_N \le \varepsilon/(2M)$ 인 $N$ 이 존재한다. $N \le p \le q$ 일 때, 

$$
\begin{aligned}
\left| \sum_{n=p}^q a_n b_n \right| &= \left| \sum_{n=p}^{q-1} A_n (b_n - b_{n+1}) + A_qb_q - A_{p-1}b_p\right| \\
&\le M \left| \sum_{n=p}^{q-1} (b_n -b_{n+1}) + b_q - b_p\right|\\
&= 2Mb_p \le 2Mb_N \le \varepsilon
\end{aligned}
$$

이므로 @thm-part2_convergence_of_series_1 (코시 판정법) 에 의해 $\sum_n a_n b_n$ 은 수렴한다. $\square$


:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_summation_of_series}

$\sum a_n = A$, $\sum b_n = B$ 일 때 $\sum (a_n + b_n) = A + B$ 이다. 또한 상수 $c$ 에 대해 $\sum ca_n = cA$ 이다.

:::
</div></br>

::: {.proof}

수렴하는 수열아 합과 상수곱을 생각하면 쉽다.
:::

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_cauchy_product}

#### 코시 곱

급수 $\sum a_n,\, \sum b_n$ 에 대해 

$$
c_n = \sum_{k=0}^n a_k b_{n-k}
$$

로 정의된 급수 $\sum c_n$ 을 두 급수의 **코시 곱(Cauchy product)** 이라고 한다.


::: 
:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_convergence_of_cauchy_product}

급수 $\sum a_n,\, \sum b_n$ 이

&emsp; ($1$) $\displaystyle \sum_{n=0}^\infty a_n$ 이 절대수렴하며,

&emsp; ($2$) $\displaystyle A=\sum_{n=0}^{\infty} a_n,\, B = \sum_{n = 0}^\infty b_n$ 

일 때 코시 곱 $\displaystyle c_n = \sum_{k=0}^n a_k b_{n-k}$ 에 대해 

$$
\sum_{k=0}^\infty c_n = AB
$$

이다.

:::
</div></br>

::: {.proof}

$\displaystyle A_n = \sum_{k=0}^n a_k,\, B_n = \sum_{k=0}^n b_k,\, C_n = \sum_{k=0}^\infty c_k,\, \beta_n = B_n - B$ 라 하자.

$$
\begin{aligned}
C_n &= a_0 b_0 + (a_0b_1 + a_1b_0) + \cdots + (a_0b_n + a_1b_{n-1} + \cdots + a_n b_0) \\
&= a_0 B_n + a_1 B_{n-1} + \cdots + a_n B_0\\
&= a_0 (B+ \beta_n) + a_1 (B+ \beta_{n-1}) + \cdots + a_n (B+\beta_0) \\
&= A_nB + a_0\beta_n + a_1 \beta_{n-1} + \cdots + a_n \beta_0
\end{aligned}
$$

이다. $\gamma_n = a_0 \beta_n + a_1 \beta_{n-1}+ \cdots + a_n \beta_0$ 라고 하자. $C_n = A_n B + \gamma_n$ 이므로 $\langle \gamma_n \rangle \to 0$ 임을 보이면 된다. 임의의 $\varepsilon>0$ 을 생각하자. $\langle \beta_n \rangle \to 0$ 이므로 $n\ge N \implies |\beta_n|<\varepsilon$ 이 되도록 $N$ 을 선택한다. $n\ge N$ 이라면, 

$$
\begin{aligned}
|\gamma_n | &= | \beta_0 a_n + \cdots + \beta_N a_{n-N} + \beta_{N+1}a_{n-N-1} + \cdots + \beta_n a_0| \\
&\le | \beta_0 a_n + \cdots + \beta_N a_{n-N}| + |\beta_{N+1}a_{n-N-1} + \cdots + \beta_n a_0| \\
&\le | \beta_0 a_n + \cdots + \beta_N a_{n-N}| + \varepsilon \left(\sum |a_n|\right)
\end{aligned}
$$

여기에 $N$ 을 고정하고 $n \to \infty$ 극한을 취하면, 

$$
0 \le \limsup_{n \to \infty} |\gamma_n| \le \varepsilon \sum |a_n|
$$

이므로 $\displaystyle \lim_{n \to \infty} \gamma_n = 0$ 임을 알 수 있다. $\square$

:::



</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_rearangement_of_series}

#### 재배열 급수

급수 $\sum a_n$ 과 전단사 함수 $\sigma : \mathbb{N} \to \mathbb{N}$ 에 대해 $\sum a_{\sigma (n)}$ 을 $\sum a_n$ 의 **재배열 급수**라고 한다.

::: 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_convergence_of_rearanged_series}

양의 실수열 $\langle a_n \rangle$ 에 대해 $\sum a_n$ 이 $\alpha$ 로 수렴하면 재배열 급수도 $\alpha$ 로 수렴한다. $\sum a_n$ 이 발산하면 재배열 급수도 발산한다.

:::

</div></br>

::: {.proof}
$\sum a_n$ 에 대한 재배열 급수 $\sum a_{\sigma (n)}$ 을 생각한다. $\sum a_n = \alpha$ 라고 하자. $M(n) = \max \{\sigma(1), \ldots,\, \sigma(n)\}$ 이라 하면 

$$
\{ a_{\sigma (1)},\ldots,\, a_{\sigma (n)} \} \subset \{ a_{1},\ldots,\, a_{M(n)} \} 
$$

이며, 따라서 
$$
\sum_{i=1}^n a_{\sigma(i)} \le \sum_{i=1}^{M(n)} a_i \le \alpha
$$

이므로 $\sum a_{\sigma(n)} \le \alpha$ 이다. $\sigma$ 에 대한 역함수를 생각하면 $\sum a_{\sigma(n)}=\alpha$ 이다. $\sum a_i$ 는 $\sum a_{\sigma (n)}$ 의 재배열 급수이므로 둘의 발산 여부는 동등하다. $\square$
:::

</br>

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_alternating_series}

#### 교대 급수 판정법

실수열 $\langle a_n \rangle$ 에 대해 $a_1 \ge a_2 \ge \cdots \ge a_n \ge \cdots \ge 0$ 이며 $\displaystyle \lim_{n \to \infty} a_n = 0$ 이면 급수 $\sum (-1)^n a_n$ 은 수렴한다.

:::

</div></br>

::: {.proof}
$b_n = (-1)^n a_n$ 이라 하고 $b_n$ 의 부분합수열 $s_n = \displaystyle \sum_{i=1}^n b_i$ 이 코시 수열임을 보이자. 임의의 $\varepsilon >0$ 에 대해 $n \ge N \implies a_n < \varepsilon$ 인 $N\in \mathbb{N}$ 이 항상 존재한다.$n>m\ge N$ 에 대해

$$
\begin{aligned}
|s_n - s_m | = a_{m+1} - a_{m+2} + a_{m+3} - \cdots + (-1)^{n-m+1} a_{n} \le a_{m+1} < \varepsilon
\end{aligned}
$$

이므로 $\langle s_n \rangle$ 은 코시수열이다. $\square$
:::


## 연습문제


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_KKK_1_6_7}

#### 김김계 1.6.7

임의의 자연수 $n=1,\,2,\ldots$ 에 대하여 $\sqrt{n-1} + \sqrt{n+1}$ 이 무리수임을 증명하여라.

:::

</div></br>

::: {.solution}

우선 $(m+1)^2-(m)^2 = 2m+1$ 이므로 인접하는 $0$ 보다 큰 두 자연수의 제곱의 차이는 2보다 크다. 따라서 $\sqrt{n-1}$ 과 $\sqrt{n+1}$ 이 동시에 제곱수일 수는 없다. 

제곱수가 아닌 자연수 $n$ 에 대해 $\sqrt{n}$ 이 유리수라고 가정하면 서로소인 어떤 자연수 $p,\,q$ 에 대해 $\sqrt{n}=p/q$ 이며 $q^2 n = p^2$ 인데 이로부터 $q\mid p$ 라는 결론이 나오므로 모순이다. 따라서 제곱수가 아닌 자연수의 제곱근은 무리수이며 따라서 $\sqrt{n-1}+ \sqrt{n+1}$ 은 자연수 + 무리수 이거나, 무리수 + 무리수 이다. 자연수 + 무리수 인 경우는 무리수이므로, 무리수 + 무리수 인 경우만 살펴보면 된다.

서로소인 자연수 $p,\,q$ 에 대해 $\sqrt{n-1}+ \sqrt{n+1} = \dfrac{p}{q}$ 라 하자. 그렇다면 $\sqrt{n^2-1}=\dfrac{p^2}{2q^2} - \dfrac{2n+1}{2} \in \mathbb{Q}$ 이다. 그런데 ($1$) 에서 보였듯이 $n^2-1$ 은 완전제곱수가 아니며 따라서 $2$ 에 의해 무리수이다. 즉 $\sqrt{n-1}+ \sqrt{n+1}$ 은 무리수이다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_KKK_2_6_11_12}

#### 김김계 1.6.11, 1.6.12

각 양수 $a>0$ 과 자연수 $n=1,\,2,\ldots$ 에 대하여 부등식

$$
(1+a)^n \ge 1+ na
$$

가 성립함을 보여라 그리고 이를 이용하여 다음을 보여라.

&emsp;($1$) 만일 $|a|<1$ 이면 $\displaystyle \lim_{n\to \infty} a^n = 0$ 이고, $|a|>1$ 이면 $\langle a^n\rangle$ 은 발산한다.

&emsp;($2$) 임의의 양수 $a>0$ 에 대하여 $\displaystyle \lim_{n\to\infty} a^{1/n}=1$ 이다.

&emsp;($3$) $\lim_n n^{1/n}=1$ 이다.

:::

</div></br>

::: {.solution}

$(1+a)^n = \displaystyle \sum_{k=0}^n \begin{pmatrix}n \\ k\end{pmatrix}a^k$ 에 의해 $(1+a)^n \ge 1+ na$ 이다.

($1$) $0<a<1$ 이라면 어떤 $b>0$ 에 대해 $a=\dfrac{1}{1+b}$ 이다. $\dfrac{1}{a^n} = (1+b)^n \ge 1+nb$ 이므로, $a^n \le \dfrac{1}{1+nb}$ 이다. 따라서 $\displaystyle \lim_{n\to \infty} \dfrac{1}{1+nb}=0$ 이므로 $\displaystyle \lim_{n\to\infty} a^n = 0$ 이다. $-1<a<0$ 이라면 $\displaystyle \lim_{n\to\infty} (-a)^n = 0$ 이므로 $\displaystyle\lim_{n\to\infty} a^n = 0$ 이다. 따라서 $\displaystyle |a|<1 \implies \lim_{n\to\infty} a^n=0$ 이다. $|a|>1$ 일 경우 $d=1/a$ 에 대해 $\displaystyle \lim_{n\to\infty} |d|^n = 0$ 이므로 $\displaystyle\lim_{n\to \infty} |a|^n$ 은 발산한다.

($2$) $a>1$ 일 경우 임의의 자연수 $n$ 에 대해 $a^{1/n}>1$ 이다. 임의의 $n\in \mathbb{Z}_+$ 에 대해 $\alpha_n = \dfrac{a-1}{n}$ 이라고 하면 $1+n\alpha_n = a$ 이며, $(1+\alpha_n)^n \ge 1+n\alpha =a$ 이다.

$$
1 < a^{1/n} \le (1+\alpha_n)
$$

이므로 $\displaystyle \lim_{n\to\infty} a^{1/n}=1$ 이다. $0<a<1$ 일 경우에는 $b=1/a$ 에 대해 $\displaystyle \lim_{n\to\infty} b^{1/n} = 1$ 이므로 $\displaystyle \lim_{n\to\infty} a^{1/n}=1$ 이다. 


($3$) 자연수 $n$ 에 대해 $n^{1/n} \ge 1$ 이다. 주어진 부등식을 생각하자. 임의의 $a>0$ 에 대해

$$
(1+a)^n \ge 1+na \ge na
$$

이므로 $n^{1/n} \le \dfrac{1+a}{a^{1/n}}$ 이다. $\displaystyle \lim_{n\to\infty} a^{1/n}=1$ 이므로 $\displaystyle \lim_{n\to\infty} n^{1/n} \le 1+a$ 이며 임의의 양수 $a$ 에 대해 성립하므로 $\displaystyle \lim_{n \to \infty} n^{1/n}=1$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_KKK_2_7_9}

### 김김계 2.7.9

집합 $\{ \sin n : n\in \mathbb{Z}_+\}$ 이 구간 $[-1,\,1]$ 안에서 조밀함을 보여라. 또한 $\theta$ 가 무리수일 때 $\{e^{2\pi i n \theta}: n \in \mathbb{Z}_+\}$ 이 단위원 $\{e^{2\pi i t}:t\in [0,\,1]\}$ 안에서 조밀함을 보여라.

:::

</div></br>

::: {.solution}


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_3_3}

#### Rudin 3.3

$s_1 = \sqrt{2}$ 이고 $s_{n+1} = \sqrt{2+\sqrt{s_n}}$, $(n=1,\,2,\,3,\ldots)$ 일 때 $\langle s_n \rangle$ 이 수렴하며 $s_n<2,\, n=1,\,2,\,3,\ldots$ 임을 보여라.

:::

</div></br>

::: {.solution}
주어진 점화식에 의해 $s_n<2 \implies s_{n+1}<2$ 이다. 따라서 $\{s_n\}$ 은 유계이다. $s_n<2$ 이므로 $\sqrt{s_n}> \dfrac{s_n}{2}$ 이다.

$$
s_{n+1} = \sqrt{2+\sqrt{s_n}} \ge \sqrt{2+\dfrac{s_n}{2}} \ge \sqrt{s_n + \dfrac{s_n}{2}}=\sqrt{\dfrac{3}{2}} \sqrt{s_n} \ge \dfrac{\sqrt{3}}{2\sqrt{2}}s_n > s_n
$$


이므로 $\{s_n\}$ 은 유계인 단조증가수열이다. 따라서 수렴한다. 
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_3_4}

#### Rudin 3.4

다음과 같이 정의된 수열 $\langle s_n \rangle$ 의 상극한과 하극한을 구하시오.

$$
s_1=0,\qquad s_{2m} = \dfrac{s_{2m-1}}{2},\qquad s_{2m+1} = \dfrac{1}{2} + s_{2m}.
$$

:::
</div></br>

::: {.proof}

주어진 조건으로 부터 다음을 알 수 있다.
$$
s_1=0,\qquad s_2 = 0,\qquad s_{2m+2} = \dfrac{1}{4} + \dfrac{1}{2}s_{2m},\qquad s_{2m+1} =  \dfrac{1+s_{2m-1}}{2} 
$$

따라서,

$$
\begin{aligned}
s_{2m} &= \left(-\dfrac{1}{2}\right)\left(\dfrac{1}{2}\right)^{m-1} + \dfrac{1}{2}, \\
s_{2m+1} &= -\left(\dfrac{1}{2}\right)^{m-1}+1,
\end{aligned}
$$

이다. 이 수열의 상극한은 $1$, 하극한은 $1/2$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_3_5}

#### Rudin 3.5

실수열 $\langle a_n \rangle,\, \langle b_n \rangle$ 에 대해 아래 식의 우변이 $\infty - \infty$ 꼴이 아닐 때 성립함을 보여라.

$$
\limsup_{n \to \infty} (a_n + b_n) \le \limsup_{n \to \infty} a_n + \limsup_{n \to \infty} b_n.
$$

:::
</div></br>

::: {.solution}

$\displaystyle a=\limsup_{n \to \infty} a_n ,\, b=\limsup_{n \to \infty} b_n$ 라 하자. $a=b=+\infty$ 이거나 $a=b=-\infty$ 인 경우라면 자명하다. 이제 $a,\,b$ 가 실수일 때만 생각한다. 귀류법으로 증명한다. 이제

$$
c=\limsup_{n \to \infty} (a_n + b_n) > \limsup_{n \to \infty} a_n + \limsup_{n \to \infty} b_n = a+b
$$

임을 가정하자. $r= \dfrac{c-(a+b)}{2}$ 라 하면 $r>0$ 이다. @prp-part2_properties_of_limsup 에 의해 $\varepsilon < \dfrac{r}{2}$ 에 대해 어떤 $N\in \mathbb{Z}_+$ 이 존재하여,

$$
n \ge N \implies a_n< a+\varepsilon,\, b_n < b+\varepsilon
$$

이므로 

$$
n \ge N \implies a_n + b_n < a+b+2\varepsilon < a+b+r =c-r
$$

이다. 즉 $a_n + b_n$ 의 상극한은 $c$ 가 아닌데 이는 모순이다. 즉, 

$$
\limsup_{n \to \infty} (a_n + b_n) \le \limsup_{n \to \infty} a_n + \limsup_{n \to \infty} b_n
$$

이다. 

등호가 성립하지 않는 예를 블어보자. $a_n = (−1)^n +2$, $b_n = −(−1)^n +2$ 라 하면 $a=3,\, b=3$ 이지만 $a_n +b_n = 4$ 이므로 $a_n + b_n$ 의 상극한은 각각의 상극한보다 작다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_3_7}

#### Rudin 3.7

양의 실수열 $\langle a_n \rangle$ 에 대해 $\sum a_n$ 이 수렴하면 $\sum \dfrac{\sqrt{a_n}}{n}$ 도 수렴함을 보여라.

:::

</div></br>

::: {.solution}

Cauchy-Schwartz 부등식을 사용한다. 즉 수열 $a_n,\,b_n$ 에 대해 

$$
\sum_n a_n b_n \le \sqrt{\sum_n |a_n|^2}  \sqrt{\sum_n |b_n|^2}  
$$

이다. 

$$
\sum_n \dfrac{\sqrt{a_n}}{n} \le \sqrt{\sum_n a_n} \sqrt{\sum_n \dfrac{1}{n^2}}
$$

이다. $\sqrt{\sum_n a_n}$ 는 문제의 조건에 의해 수렴하며, $\sqrt{\sum_n \dfrac{1}{n^2}}$ 가 수렴함은 @prp-part2_convergence_of_1_over_n_p 로부터 안다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_3_8}

#### Rudin 3.8

$\sum a_n$ 이 수렴하며 $\langle b_n \rangle$ 이 유계인 단조수열일 때 $\sum a_n b_n$ 이 수렴함을 보이시오.

:::

</div></br>

::: {.solution}

$\langle b_n \rangle$ 이 유계인 단조수열이므로 수렴한다. $b=\lim b_n$ 라 하자. $b_n$ 이 단조증가수열이라면 $c_n=b-b_n$ 은 단조감소수열이며 $\lim c_n = 0$ 이다. 

$$
\sum_n a_n b_n = \sum_{n} a_n (b-c_n) = b\sum_n a_n - \sum_n a_n c_n 
$$

이며 @prp-part2_convergence_of_product_of_sequences 에 의해 $\sum_n a_n c_n$ 은 수렴하므로 위 식은 수렴하는 두 수열의 차이므로 수렴한다. $b_n$ 이 단조감소수열이라면 $c_n = b_n -b$ 는 $0$ 으로 수렴하는 단조감소수열이고 

$$
\sum_n a_n b_n = \sum_{n} a_n (c_n + b) = b\sum_n a_n + \sum_n a_n c_n 
$$

이므로 좌변은 수렴하는 두 수열의 합이되며, 따라서 수렴한다. $\square$

:::



</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_3_9}

#### Rudin 3.9

아래의 멱급수에 대한 수렴반경을 구하라.

($a$) $\displaystyle \sum n^3 z^n\qquad$ ($b$) $\displaystyle \sum\dfrac{2^n}{n!}z^n\qquad$ ($c$) $\displaystyle \sum \dfrac{2^n}{n^2} z^n\qquad$ ($d$) $\displaystyle \sum \dfrac{n^3}{3^n}z^n$.

:::

</div></br>

::: {.solution}

($a$) $\left|\dfrac{a_{n+1}}{a_n}\right| = \left(1+\dfrac{1}{n}\right)^3|z| <1$ 이어야 하므로 수렴반경 $R=1$ 이다.

($b$) $\left|\dfrac{a_{n+1}}{a_n} \right| = \dfrac{2}{n+1}|z| <1$ 이므로 수렴반경 $R=\infty$ 이다.

($c$) $\left|\dfrac{a_{n+1}}{a_n}\right| = \dfrac{2}{(1+1/n)^2}|z| <1$ 이므로 수렴반경 $R=\dfrac{1}{2}$ 이다.

($d$) $\left|\dfrac{a_{n+1}}{a_n}\right| =  \dfrac{1}{3}\left(1+\dfrac{1}{n}\right)^3 |z|<1$ 이므로 수렴반경 $R=3$ 이다. 
:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_3_11}

#### Rudin 3.11

양의 실수열 $\langle a_n \rangle$ 에 대해 $s_n = \displaystyle \sum_{k=1}^n a_k$ 이며 $\sum a_n$ 은 발산한다고 하자.

($1$) $\sum \dfrac{a_n}{1+a_n}$ 은 발산함을 보여라.

($2$) $\dfrac{a_{n+1}}{s_{N+1}} + \cdots + \dfrac{a_{N+k}}{s_{N+k}} \ge 1- \dfrac{s_N}{s_{N+k}}$ 임을 보이고 $\sum \dfrac{a_n}{s_n}$ 이 발산함을 보여라.

($3$) $\dfrac{a_n}{{s_{n}}^2} \le \dfrac{1}{s_{n-1}} - \dfrac{1}{s_n}$ 임을 보이고 $\sum \dfrac{a_n}{{s_n}^2}$ 가 수렴함을 보여라.

($4$) $\sum \dfrac{a_n}{1+a_n}$ 과 $\sum \dfrac{a_n}{1+n^2a_n}$ 에 대해 더 알 수 있는 것은 무엇인가?

:::

</div></br>

::: {.solution}

($1$) $\sum \dfrac{a_n}{1+a_n}$ 이 수렴함을 가정하자. 그렇다면 $\displaystyle \lim_{n \to \infty} \dfrac{a_n}{1+a_n}=0$ 이며 따라서 $a_n \to 0$ 이다. 그렇다면 어떤 $N\in \mathbb{Z}_+$ 에 대해 $n\ge N \implies a_n<1$ 이며

$$
a_n<1 \implies a_n^2 < a_n \implies a_n^2+a_n \le 2a_n \implies \dfrac{a_n}{2} \le \dfrac{a_n}{1+a_n}
$$

이므로 비교판정법에 의해 $\sum a_n$ 은 수렴해야 하는데 이는 가정에 모순된다. 따라서 $\sum \dfrac{a_n}{1+a_n}$ 은 발산한다.

($2$) 부등식은 다음과 같이 보인다.

$$
\dfrac{a_{n+1}}{s_{N+1}} + \cdots + \dfrac{a_{N+k}}{s_{N+k}} \ge \dfrac{a_{n+1}}{s_{N+k}} + \cdots + \dfrac{a_{N+k}}{s_{N+k}} = \dfrac{s_{N+k}-s_N}{s_{N+k}} = 1-\dfrac{s_N}{s_{N+k}}
$$

이제 $\sum \dfrac{a_n}{s_n}$ 이 발산함을 보이자. $s_n$ 이 $+\infty$ 로 발산하므로 충분히 큰 $k$ 에 대해 $s_{N+k}>2s_N$ 이며 따라서 $\dfrac{a_{n+1}}{s_{N+1}} + \cdots + \dfrac{a_{N+k}}{s_{N+k}} \ge \dfrac{1}{2}$ 이다. 즉 코시 판정법의 발산 조건이다. 

($3$) $s_n > s_{n-1}$ 이므로

$$
\dfrac{1}{s_{n-1}}-\dfrac{1}{s_n} = \dfrac{a_n}{s_n s_{n-1}} \ge \dfrac{a_n}{{s_n}^2}
$$

이다. 따라서, 

$$
\begin{aligned}
\sum_{k=1}^n \dfrac{a_n}{{s_n}^2} &= \dfrac{1}{a_1} + \sum_{k=2}^n \dfrac{a_n}{{s_n}^2} \\
&\le \dfrac{1}{a_1} + \left(\dfrac{1}{s_1}- \dfrac{1}{s_2}\right) + \cdots \left(\dfrac{1}{s_{n-1}}-\dfrac{1}{s_n}\right) \\
&= \dfrac{2}{a_1}-\dfrac{1}{s_n}
\end{aligned}
$$

이므로 $\sum \dfrac{a_n}{{s_n}^2} \le \dfrac{2}{a_1}$ 이다. 따라서 수렴한다.

($4$) $\langle na_n\rangle$ 이 위로 유계인 경우 즉 $na_n < M$ 인 경우 $\dfrac{a_n}{1+na_n} > \dfrac{a_n}{M+1}$ 이므로 발산한다. $\langle na_n \rangle$ 이 $0$ 이 양의 하한 $b$ 를 가지는 경우, 즉 $na_n > b > 0$ 인 경우

$$
\dfrac{a_n}{1+na_n} = \dfrac{1}{n} \dfrac{na_n}{1+na_n} > \dfrac{1}{n}\dfrac{b}{1+b}
$$

이므로 $\sum \dfrac{a_n}{1+na_n}$ 은 발산한다.

수렴하는 경우는 (위스컨신 대학의 solution site 에서 가져왔음) 

$$
a_n = \left\{ \begin{array}{ll} \dfrac{1}{\sqrt{n}} \qquad & n\text{ 이 자연수의 제곱일 때} \\ \dfrac{1}{n^2} &\text{otherwise}.\end{array} \right.
$$

이 있다. 이 $a_n$ 은 문제의 조건을 만족하며, 인덱스가 제곱수가 아닌 항의 합은 수렴하고($<\sum 1/n^2$), 제곱수 인 항의 합은 $\sum \dfrac{1}{m^2+m}$ 이 되므로 수렴한다. 따라서 $\dfrac{a_n}{1+na_n}$ 은 수렴한다.

$\dfrac{a_n}{1+n^2a_n}$ 의 경우

$$
\sum \dfrac{a_n}{1+n^2 a_n} = \sum \dfrac{1}{1/a_n + n^2} < \sum \dfrac{1}{n^2}
$$

이므로 수렴한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_3_12}

#### Rudin 3.12

$a_n>0$ 이며 $\sum a_n$ 이 수렴한다고 하자. $r_n$ 을 다음과 같이 정한다.


$$
r_n = \sum_{k=n}^\infty a_k.
$$


&emsp; ($1$) $m<n$ 일 때 $\dfrac{a_m}{r_m} + \cdots + \dfrac{a_n}{r_n} > 1- \dfrac{r_n}{r_m}$ 임을 보이고, $\sum \dfrac{a_n}{r_n}$ 이 발산함을 보여라.

&emsp; ($2$) $\dfrac{a_n}{\sqrt{r_n}} < 2(\sqrt{r_n}- \sqrt{r_{n+1}})$ 임을 보이고 $\sum \dfrac{a_n}{\sqrt{r_n}}$ 이 수렴함을 보여라.

:::

</div></br>

::: {.solution}

($1$) $m<n$ 일 때 $r_m > r_n$ 이다. 즉 $\langle r_n\rangle$ 은 단순 감소 수열(같은 값을 갖는 항이 없는 감소수열) 이다.

$$
\dfrac{a_m}{r_m} + \cdots + \dfrac{a_n}{r_n} > \dfrac{a_m + \cdots a_n}{r_m} = \dfrac{r_m-r_{n+1}}{r_m} > \dfrac{r_m - r_n}{r_m} = 1-\dfrac{r_n}{r_m}
$$


$\sum a_n$ 이 수렴하므로 $\langle r_n \rangle \to 0$ 이다. 아무리 큰 $m$ 을 잡더라도 더 큰 어떤 $n$ 에 대해 $r_n < \dfrac{1}{2} r_m$ 이므로

$$
\sum_{k=n}^m \dfrac{a_n}{r_n} > 1-\dfrac{r_n}{r_m} > \dfrac{1}{2}
$$

이다. 코시 판정법에 의해 발산한다.

($2$)  $a_n = r_n - r_{n+1} >0$ 을 이용한다.

$$
\sqrt{r_n}-\sqrt{r_{n+1}} = \dfrac{r_n -r_{n+1}}{\sqrt{r_n}+\sqrt{r_{n+1}}} = \dfrac{a_n}{\sqrt{r_n}+ \sqrt{r_{n+1}}}> \dfrac{a_n}{2 \sqrt{r_{n}}}.
$$

이로부터, 

$$
\sum_{k=1}^n \dfrac{a_n}{\sqrt{r_n}} < 2(\sqrt{r_1}- \sqrt{r_{n+1}}) 
$$


이므로 수렴한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_3_13}

#### Rudin 3.13

절대수렴하는 두 급수의 코시곱은 절대수렴함을 보이시오.

:::

</div></br>

::: {.solution}
$\displaystyle A'_n = \sum_{k=0}^n |a_k|,\, B'_n = \sum_{k=0}^n |b_k|$, $A' = \displaystyle \lim_{n \to \infty} A'_n$, $B' = \displaystyle \lim_{n \to \infty} B'_n$, $\beta'_n = B'_n - B'$ 이라 하자.

$$
\begin{aligned}
\sum_{k=0}^\infty |c_k| &= |a_0 b_0| + |a_0b_1 + a_1b_0| + \cdots + |a_0b_n + a_1b_{n-1} + \cdots + a_n b_0| \\
&\le |a_0|\left( |b_0|+|b_1|+ \cdots + |b_n| \right) + |a_1|\left( |b_0|+ \cdots + |b_{n-1}|\right)\\
&\qquad \qquad + \cdots + |a_n| \left(|b_0|\right) \\
&= |a_0|B'_n + |a_1| B'_{n-1} + \cdots + |a_n| B'_0\\
&= |a_0|(\beta'_n+B') + |a_1| (\beta'_{n-1}+B') + \cdots + |a_n| (\beta'_0 + B') \\
&= A'_n B' + |a_0| \beta'_n + \cdots + |a_n| \beta'_0
\end{aligned}
$$
이다. $\gamma'_n = |a_0|\beta'_n + \cdots + |a_n| \beta'_0$ 라 하고 $\displaystyle \lim_{n \to \infty} \gamma'_n \to 0$ 임을 보이자. 임의의 $\varepsilon >0$ 을 생각한다. $\displaystyle \lim_{n \to \infty}\beta'_n = 0$ 이므로 $n \ge N \implies |\beta'_n|<\varepsilon$ 이 되도록 $N$ 을 선택 할 수 있다. $n \ge N$ 이면, 
$$
\begin{aligned}
|\gamma'_n| &= \left| \beta'_0|a_n| + \cdots + \beta'_N |a_{n-N}| + \beta'_{N+1} |a_{n-N-1}| + \cdots + \beta'_n |a_0| \right|\\
&\le \left| \beta'_0|a_n| + \cdots + \beta'_N |a_{n-N}|\right| + \left|\beta'_{N+1} |a_{n-N-1}| + \cdots + \beta'_n |a_0| \right|\\
&\le \left| \beta'_0|a_n| + \cdots + \beta'_N |a_{n-N}|\right| + \varepsilon \left(\sum_{k=0}^{n-N-1} |a_k|\right)
\end{aligned}
$$
이다. 여기에 $N$ 을 고정하고 $n \to \infty$ 극한을 취하면, 
$$
0 \le \limsup_{n \to \infty} |\gamma'_n| \le \varepsilon \left( \sum |a_n|\right)
$$
이므로 $\displaystyle \lim_{n \to \infty} \gamma'_n = 0$ 임을 알 수 있다. 즉 $\displaystyle \sum_{k=0}^\infty |c_k| = A'B'$ 이다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_kkk_2_7_11}

#### 김김계 2.7.11

유계 실수열 $\langle x_n \rangle$ 이 다음 조건

$$
2x_n \le x_{n-1}+x_{n+1},\qquad n=1,\,2,\ldots
$$

를 만족할 때 $\lim_n (x_{n+1}-x_n)=0$ 임을 보여라.
:::

</div></br>

::: {.solution}
$y_n := x_{n+1}-x_n$ 이라 하자. $\langle x_n\rangle$ 이 유계이므로 $|x_n|<R$ 인 양의 실수 $R\in \mathbb{R}$ 이 존재하며 $|y_n|<2R$ 이므로 $\langle y_n\rangle$ 도 유계이다. 또한 주어진 조건으로 부터 $x_{n+1}-x_n \le x_n -x_{n-1}$ 이므로 $\langle y_{n} \rangle$ 은 단조감소수열이다. 따라서 $\langle y_n \rangle$ 은 수렴한다. 

$y:=\displaystyle \lim_{n \to \infty} y_n$ 이라 하자. 우리는 $y=0$ 임을 보이고자 한다. 

우선 $y>0$ 임을 가정하자. $y$ 가 감소수열이므로 $y_n\ge y$ 이다. 자연수 $N$ 에 대해 
$$
\begin{aligned}
x_{N+1}-x_1 &= (x_{N+1}-x_{N})+ (x_{N}-x_{N-1}) + (x_{N-1}-x_{N-2}) + \cdots + (x_2-x_1) \\
&= y_{N} + y_{N-1} + \cdots + y_{1} > Ny
\end{aligned}
$$

이므로 $x_{N+1} > x_1 + Ny$ 이다. $N > \dfrac{R-x_1}{y}$ 이면 $x_{N+1}>R$ 이므로 $|x_n|<R$ 이라는 가정에 위배된다. 

$y<0$ 이라면 어떤 $N\in \mathbb{N}$ 이 존재하여 $n\ge N \implies y_n < \dfrac{y}{2}$ 이며,

$$
\begin{aligned}
x_{N} - x_{N+M+1} &= x_{N}-x_{N+1}+ x_{N+1}-x_{N+2} + \cdots + x_{N+M}- x_{N+M+1}\\
&= - y_{N} - y_{N+1} - \cdots - y_{N+M} > -(M+1)\dfrac{y}{2}
\end{aligned}
$$

이므로 $x_{N+M+1} < x_N + (M+1)\dfrac{y}{2}$ 이다. $M > -(R+x_N) \dfrac{2}{y}-1$ 이면 $x_{N+M+1}<-R$ 이므로 $|x_n|<R$ 이라는 가정에 위배된다. 따라서 $y=0$ 이다. $\square$

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_kkk_2_7_12}

#### 김김계 2.7.12

실수열 $\langle a_n \rangle$ 에 대하여 새로운 수열 $\langle \sigma_n\rangle$ 을 다음

$$
\sigma_n = \dfrac{1}{n}(a_1+ \cdots + a_n),\qquad n=1,\,2,\ldots,
$$

과 같이 정의하자. 이 때 $\lim_n a_n = a$ 이면 $\lim_n \sigma_n = a$ 임을 보여라.

::: 
</div></br>

::: {.solution}

정해진 $\varepsilon>0$ 에 대해 $n \ge N \implies |a_n - a|<\varepsilon$ 을 만족하는 $N$ 이 존재한다. $n > N$ 이라 하자. 

$$
\begin{aligned}
|\sigma_n - a| & = \dfrac{1}{n} \left| (a_1-a)  + \cdots + (a_N -a ) + (a_{N+1}-a) + \cdots + (a_n - a) \right| \\
& \le \dfrac{|a_1-a| + \cdots + |a_N-a|}{n} + \dfrac{|a_{N+1}-a| + \cdots + |a_{n}-a|}{n} \\
&< \dfrac{|a_1-a| + \cdots + |a_N-a|}{n} + \varepsilon \dfrac{n-N}{n}
\end{aligned}
$$

이다. $N$ 을 고정하고 $n \to \infty$ 에서 생각하면, 

$$
0 \le \limsup_{n \to \infty} |\sigma_n - a| \le \varepsilon
$$

이다. 따라서 $\displaystyle \lim_{n \to \infty} \sigma_n = a$ 이다.

:::

</br>


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_kkk_2_7_13}

#### 김김계 2.7.13

좌표공간의 수얼 $\langle x_n\rangle$ 이 고정된 실수 $r\in 1$ 에 대해

$$
\|x_{n+2}-x_{n+1}\| \le r\|x_{n+1}-x_n\|,\qquad n=1,\,2,\ldots
$$

을 만족하면 $\langle x_n\rangle$ 이 코시수열임을 보여라. 위 조건이 

$$
\|x_{n+2}-x_{n+1} \| < \|x_{n+1}-x_n\|, \qquad n=1,\,2,\ldots
$$

으로 바뀌면 어떻게 되는지 살펴보아라.


::: 
</div></br>

::: {.solution}

주어진 조건에 의해 

$$
\|x_{n+2}-x_{n+1}\| \le r\| x_{n+1}-x_n\| \le \cdots \le r^{n}\|x_2-x_1\|
$$

이다. 이를 이용하면 

$$
\begin{aligned}
\|x_{n+k}-x_n\| &\le \|x_{n+k}-x_{n+k-1}\| + \|x_{n+k-1}-x_n\|  \\
& \qquad \qquad \vdots \\
&\le \|x_{n+k}-x_{n+k-1}\| + \|x_{n+k-1}-x_{n+k-2}\| + \cdots + \|x_{n+1}-x_n\| \\
&\le (r^{n+k-2} + r^{n+k-3} + \cdots + r^{n-1}) \|x_2-x_1\| \\
&= \dfrac{r^{n-1}(1-r^{k})}{1-r}\|x_2-x_1\| < \dfrac{r^{n}}{1-r}\|x_2-x_1\|
\end{aligned}
$$

임을 안다. $c=\dfrac{\|x_2-x_1\|}{1-r}$ 라 하면  $\|x_{n+k}-x_n\| \le cr^{n}$ 이므로 임의의 $\varepsilon>0$ 에 대해 $n>\ln_r(\varepsilon/c)$ 이면 $\|x_{n+k}-x_n\|<\varepsilon$ 이므로 $\langle x_n \rangle$ 은 코시수열이다. 

이제 $\|x_{n+2}-x_{n+1} \| < \|x_{n+1}-x_n\|$ 인 경우를 보자. $x_n := \displaystyle \sum_{k=1}^n \dfrac{1}{n}$ 이라 하면

$$
\|x_{n+2} - x_{n+1}\| = \dfrac{1}{n+2} < \dfrac{1}{n+1} = \|x_{n+1}-x_{n}\| 
$$

이지만 $\langle x_n\rangle$ 은 수렴하지 않으므로 코시수열이 아니다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_3_16}

#### Rudin 3.16

양수 $\alpha$ 를 고정시킨다. $x_1 > \sqrt{\alpha}$ 를 선택하고
$$
x_{n+1} = \dfrac{1}{2} \left(x_n + \dfrac{\alpha}{x_n}\right)
$$

이라 하자.

($1$) $\langle x_n \rangle$ 이 단조감소수열이며 $\lim_n x_n = \sqrt{\alpha}$ 임을 보여라

($2$) $\varepsilon_n = x_n -\sqrt{\alpha}$ 일 때 $\varepsilon_{n+1} = \dfrac{\varepsilon_n^2}{2x_n}  < \dfrac{\varepsilon_n^2}{2\sqrt{\alpha}}$ 임을 보여라. 또한 $\beta = 2\sqrt{\alpha}$ 라 하면

$$
\varepsilon_n < \beta \left(\dfrac{\varepsilon_1}{\beta}\right)^{2^n} \qquad (n=1,\,2,\,3,\ldots)
$$

임을 보여라

($3$) 이것은 제곱근을 계산하는 좋은 알고리즘이다. 예를 들어 $\alpha=3$ 이고 $x_1=2$ 일 때 $\varepsilon/\beta < \dfrac{1}{10}$ 이며 따라서, 

$$
\varepsilon_5 < 4 \cdot 10^{-16},\qquad \varepsilon_6 < 4 \cdot 10^{-32}
$$

이다.

:::

</div></br>

::: {.solution}

($1$) $a+b\ge 2 \sqrt{ab}$ 이므로 

$$
x_{n+1} = \dfrac{1}{2} \left(x_n + \dfrac{\alpha}{x_n}\right) \ge \sqrt{\alpha}
$$

이다. $x_n > \sqrt{\alpha}$ 이며 $\alpha/x_n <\sqrt{\alpha}$ 이다.

$$
x_n-x_{n+1} = \dfrac{1}{2}\left(x_n - \dfrac{\alpha}{x_n}\right) >0
$$

이므로 $\langle x_n \rangle$ 은 단조감소수열이다. $\langle x_n \rangle$ 이 유계인 단조감소수열이므로 수렴하며 $\lim_n x_n=x$ 라 놓으면 $x=\dfrac{1}{2} \left(x+\dfrac{\alpha}{x}\right)$ 이므로 $x=\sqrt{\alpha}$ 이다.

($2$) $\dfrac{\varepsilon_n^2}{2x_n} = \dfrac{1}{2x_n}\left(x_n^2 - 2\sqrt{\alpha}x_n + \alpha\right) = \dfrac{1}{2}\left(x_n + \dfrac{\alpha}{x_n}\right) - \sqrt{\alpha} = x_{n+1}-\sqrt{\alpha} = \varepsilon_{n+1}$

이며 $x_n> \sqrt{\alpha}$ 이므로 $\dfrac{\varepsilon_n^2}{2x_n}< \dfrac{\varepsilon_n^2}{2\sqrt{\alpha}}$ 이다. $\beta = 2\sqrt{\alpha}$ 라 하면 $\varepsilon_{n+1} < \dfrac{\varepsilon_{n}^2}{\beta}$ 이다.

$$
\varepsilon_{n+1} < \dfrac{\varepsilon_n^2}{\beta} < \dfrac{1}{\beta}\left(\dfrac{\varepsilon_{n-1}^2}{\beta}\right)^2 = \dfrac{\varepsilon_{n-1}^4}{\beta^3} < \cdots < \beta \left(\dfrac{\varepsilon_1}{\beta}\right)^{2^n}
$$

:::


</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_3_17}

#### Rudin 3.17

$\alpha>1$ 을 고정시키고 $x_1>\sqrt{\alpha}$ 로 잡고 다음과 같이 수열 $\langle x_n\rangle$ 을 정의하자.

$$
x_{n+1}= \dfrac{\alpha+x_n}{1+x_n} = x_n + \dfrac{\alpha-x_n^2}{1+x_n}.
$$

&emsp;($a$) $x_1>x_3>x_5>\cdots$ 임을 보여라.

&emsp;($b$) $x_2<x_4<x_6<\cdots$ 임을 보여라.

&emsp;($c$) $\displaystyle \lim_{n \to \infty} x_n = \sqrt{\alpha}$ 임을 보여라.

&emsp;($d$) 수렴 속도를 @exr-part2_rudin_3_16 과 비교하라.

:::

</div></br>

::: {.solution}

$x_n>0$ 이면 $x_{n+1}>0$ 임은 주어진 식으로부터 자명하다. 또한

$$
x_{n+1} = 1+ \dfrac{\alpha-1}{1+x_n}
$$

이다. $x_1>1$ 이므로 $x_n>1$ 이다. 

$x_n>\sqrt{\alpha}$ 이면

$$
x_{n+1}= 1+ \dfrac{\alpha-1}{1+x_n} < 1+ \dfrac{\alpha -1}{\sqrt{\alpha}+1}= \sqrt{\alpha}
$$

이며,

$x_n<\sqrt{\alpha}$ 이면 

$$
x_{n+1} = 1+\dfrac{\alpha-1}{1+x_n} > 1+ \dfrac{\alpha-1}{\sqrt{\alpha}+1} = \sqrt{\alpha}
$$

이다. 

($a$) 위의 결과로부터 $x_1>\sqrt{\alpha}$ 이므로 $x_{2n+1}>\sqrt{\alpha}$ 임을 안다. 또한

$$
x_{n+2} = \dfrac{\alpha+x_{n+1}}{1+x_{n+1}}= \dfrac{\alpha + (\alpha+x_n)/(1+x_n)}{1+ (\alpha+x_n)/(1+x_n)} = x_n + \dfrac{\alpha-x_n^2}{x_n + (\alpha+1)/2}
$$ {#eq-part2_rudin_3_17}

로부터 $x_n>\sqrt{\alpha}$ 이면 $x_{n+2}<x_n$ 임을 안다. 즉

$$
x_{1}>x_3 > x_5 > \cdots >\sqrt{\alpha}
$$

이다.

($b$) $x_2<\sqrt{\alpha}$ 이므로 $x_{2n}<\sqrt{\alpha}$ 임을 안다. @eq-part2_rudin_3_17 로부터 $x_{n+2}> x_n$ 임을 안다. 즉

$$
x_2 < x_4 < x_6 <\cdots < \sqrt{\alpha}
$$

이다. 

($c$) $\langle x_{2n}\rangle$ 과 $\langle x_{2n-1}\rangle$ 이 모두 유계인 단조수열이므로 수렴한다. 수렴하는 지점에서 @eq-part2_rudin_3_17 로부터

$$
x= x + \dfrac{\alpha-x^2}{x+ (\alpha+1)/2}
$$

이므로 $x=\sqrt{\alpha}$ 이다. 앞서 $x_n>1$ 인 조건을 얻었으므로 $x=-\sqrt{\alpha}$ 일 수 없다.

($d$) $\varepsilon_n = x_n-\sqrt{\alpha}$ 라고 하자.

$$
\begin{aligned}
\varepsilon_{n+1} &= \dfrac{\alpha+x_n}{1+x_n}-\sqrt{\alpha} = \dfrac{(\alpha-\sqrt{\alpha}) + (1-\sqrt{\alpha})x_n}{1+x_n} \\
&= \dfrac{(\sqrt{\alpha}-1)(\sqrt{\alpha}-x_n) }{1+x_n} = -\dfrac{\sqrt{\alpha}-1}{1+x_n}\varepsilon_n
\end{aligned}
$$

이며 $x_n>1$ 을 이용하면

$$
|\varepsilon_{n+1}| = \dfrac{\sqrt{\alpha}-1}{1+x_n}|\varepsilon_n| < \dfrac{\sqrt{\alpha}-1}{2}|\varepsilon_n|
$$

이다. $\alpha=3,\,x_1=2$ 인 경우 $|\varepsilon_{n+1}|<0.74 |\varepsilon_n| < \cdots (0.74)^n |\varepsilon_1|<(0.74)^n \times 0.27$ 이므로

$$
\varepsilon_5 < 0.060,\qquad \varepsilon_6 < 0.044
$$

이다. @exr-part2_rudin_3_16 보다 수렴 속도가 매우 느림을 알 수 있다.

:::