---
# title: "수열과 급수"
number-sections: true
number-depth : 2
crossref:
  chapters: true
---

## 연습문제 {.unnumbered}


::: {#exr-KKK_1_6_7}

#### 김김계 1.6.7

임의의 자연수 $n=1,\,2,\ldots$ 에 대하여 $\sqrt{n-1} + \sqrt{n+1}$ 이 무리수임을 증명하여라.

:::

::: {.solution}

$1$. $(m+1)^2-(m)^2 = 2m+1$ 이므로 인접하는 두 제곱수의 차이는 2보다 크다. 따라서 $\sqrt{n-1}$ 과 $\sqrt{n+1}$ 이 동시에 제곱수일 수는 없다. 

$2$. 제곱수가 아닌 자연수 $n$ 에 대해 $\sqrt{n}$ 이 유리수라고 가정하면 서로소인 어떤 자연수 $p,\,q$ 에 대해 $\sqrt{n}=p/q$ 이며 $q^2 n = p^2$ 인데 이로부터 $q\mid p$ 라는 결론이 나오므로 모순이다. 따라서 제곱수가 아닌 자연수의 제곱근은 무리수이다.

$3$. $1$ 과 $2$ 에 의해 $\sqrt{n-1}+ \sqrt{n+1}$ 은 자연수 + 무리수 이거나, 무리수 + 무리수 이다. 자연수 + 무리수 인 경우는 무리수이므로, 무리수 + 무리수 인 경우만 살펴보면 된다.

$4$. 서로소인 자연수 $p,\,q$ 에 대해 $\sqrt{n-1}+ \sqrt{n+1} = \dfrac{p}{q}$ 라 하자. $\sqrt{n^2-1}=\dfrac{p^2}{2q^2} - \dfrac{2n+1}{2} \in \mathbb{Q}$ 이다. 그런데 $1$ 에 의해 $n^2-1$ 은 완전제곱수가 아니며 따라서 $2$ 에 의해 무리수이다. 즉 $\sqrt{n-1}+ \sqrt{n+1}$ 은 무리수이다.
:::

</br>

::: {#exr-KKK_2_6_11_12}

#### 김김계 1.6.11, 1.6.12

각 양수 $a>0$ 과 자연수 $n=1,\,2,\ldots$ 에 대하여 부등식

$$
(1+a)^n \ge 1+ na
$$

가 성립함을 보여라 그리고 이를 이용하여 다음을 보여라.

&emsp; (1) 만일 $|a|<1$ 이면 $\lim_n a^n = 0$ 이고, $|a|>1$ 이면 $\langle a^n\rangle$ 은 발산한다.

&emsp; (2) 임의의 양수 $a>0$ 에 대하여 $\lim_n a^{1/n}=1$ 이다.

&emsp; (3) $\lim_n n^{1/n}=1$ 이다.

:::

::: {.solution}

$(1+a)^n = \displaystyle \sum_{k=0}^n \begin{pmatrix}n \\ k\end{pmatrix}a^k$ 에 의해 $(1+a)^n \ge 1+ na$ 이다.

($1$) $0<a<1$ 이라면 어떤 $b>0$ 에 대해 $a=\dfrac{1}{1+b}$ 이다. $\dfrac{1}{a^n} = (1+b)^n \ge 1+nb$ 이므로, $a^n \le \dfrac{1}{1+nb}$ 이다. 따라서 $\lim_n \dfrac{1}{1+nb}=0$ 이므로 $\lim_n a^n = 0$ 이다. $-1<a<0$ 이라면 $\lim_n (-a)^n = 0$ 이므로 $\lim_n a^n = 0$ 이다. 따라서 $|a|<1 \implies \lim_n a^n=0$ 이다. $|a|>1$ 일 경우 $d=1/a$ 에 대해 $\lim_n |d|^n = 0$ 이므로 $\lim_n |a|^n$ 은 발산한다.

($2$) $a>1$ 일 경우 임의의 자연수 $n$ 에 대해 $a^1/n>1$ 이다. 고정된 $n\in \mathbb{N}$ 에 대해 $\alpha_n = \dfrac{a-1}{n}$ 이라고 하면 $1+n\alpha_n = a$ 이며, $(1+\alpha_n)^n \ge 1+n\alpha =a$ 이다.

$$
1 < a^{1/n} \le (1+\alpha_n)
$$

이므로 $n \to \infty$ 극한을 생각하면 $\lim_n a^{1/n}=1$ 이다. $0<a<1$ 일 경우에는 $b=1/a$ 에 대해 $\lim_n b^{1/n} = 1$ 이므로 $\lim_n a^{1/n}=1$ 이다. 


($3$) 자연수 $n$ 에 대해 $n^{1/n} \ge 1$ 이다. 주어진 부등식을 생각하자. 임의의 $a>0$ 에 대해

$$
(1+a)^n \ge 1+na \ge na
$$

이므로 $n^{1/n} \le \dfrac{1+a}{a^{1/n}}$ 이다. $\lim_n a^{1/n}=1$ 이므로 $\lim_n n^{1/n} \le 1+a$ 이며 임의의 양수 $a$ 에 대해 성립하므로 $\lim_n n^{1/n}=1$ 이다.

:::

</br>

::: {#exr-KKK_2_7_9}

### 김김계 2.7.9

집합 $\{ \sin n : n\in \mathbb{N}\}$ 이 구간 $[-1,\,1]$ 안에서 조밀함을 보여라. 또한 $\theta$ 가 무리수일 때 $\{e^{2\pi i n \theta}: n \in \mathbb{N}\}$ 이 단위원 $\{e^{2\pi i t}:t\in [0,\,1]\}$ 안에서 조밀함을 보여라.

:::

::: {.solution}


:::

</br>

::: {#exr-rudin_3_3}

#### Rudin 3.3

$s_1 = \sqrt{2}$ 이고 $s_{n+1} = \sqrt{2+\sqrt{s_n}}$, $(n=1,\,2,\,3,\ldots)$ 일 때 $\langle s_n \rangle$ 이 수렴하며 $s_n<2,\, n=1,\,2,\,3,\ldots$ 임을 보여라.

:::

::: {.solution}
주어진 점화식에 의해 $s_n<2 \implies s_{n+1}<2$ 이다. 따라서 $\{s_n\}$ 은 유계이다. $s_n<2$ 이므로 $\sqrt{s_n}> \dfrac{s_n}{2}$ 이다.

$$
s_{n+1} = \sqrt{2+\sqrt{s_n}} \ge \sqrt{2+\dfrac{s_n}{2}} \ge \sqrt{s_n + \dfrac{s_n}{2}}=\sqrt{\dfrac{3}{2}} \sqrt{s_n} \ge \dfrac{\sqrt{3}}{2\sqrt{2}}s_n > s_n
$$


이므로 $\{s_n\}$ 은 유계인 단조증가수열이다. 따라서 수렴한다. 
:::

</br>

::: {#exr-rudin_3_4}

#### Rudin 3.4

다음과 같이 정의된 수열 $\langle s_n \rangle$ 의 상극한과 하극한을 구하시오.

$$
s_1=0,\qquad s_{2m} = \dfrac{s_{2m-1}}{2},\qquad s_{2m+1} = \dfrac{1}{2} + s_{2m}.
$$

:::

::: {.proof}

주어진 조건으로 부터 다음을 알 수 있다.
$$
s_1=0,\qquad s_2 = 0,\qquad s_{2m+2} = \dfrac{1}{4} + \dfrac{1}{2}s_{2m},\qquad s_{2m+1} =  \dfrac{1+s_{2m-1}}{2} 
$$

따라서,

$$
\begin{aligned}
s_{2m} &= \left(-\dfrac{1}{2}\right)\left(\dfrac{1}{2}\right)^{m-1} + \dfrac{1}{2}, \\
s_{2m+1} &= -\left(\dfrac{1}{2}\right)^{m-1}+1,
\end{aligned}
$$

이다. 이 수열의 상극한은 $1$, 하극한은 $1/2$ 이다.

:::

</br>

::: {#exr-rudin_3_5}

#### Rudin 3.5

실수열 $\langle a_n \rangle,\, \langle b_n \rangle$ 에 대해 동시에 $\displaystyle \limsup_{n \to \infty} a_n = +\infty$, $\displaystyle \limsup_{n \to \infty} b_n = -\infty$ 인 경우가 아닐 때에는 다음이 성립함을 보이시오.

$$
\limsup_{n \to \infty} (a_n + b_n) \le \limsup_{n \to \infty} a_n + \limsup_{n \to \infty} b_n
$$

:::

::: {.solution}

$\displaystyle a=\limsup_{n \to \infty} a_n ,\, b=\limsup_{n \to \infty} b_n$ 라 하자. $a=b=+\infty$ 이거나 $a=b=-\infty$ 인 경우라면 자명하다. 이제 $a,\,b$ 가 실수일 때만 생각한다. 귀류법으로 증명한다. 이제

$$
c=\limsup_{n \to \infty} (a_n + b_n) > \limsup_{n \to \infty} a_n + \limsup_{n \to \infty} b_n = a+b
$$

임을 가정하자. $r= \dfrac{c-(a+b)}{2}$ 라 하면 $r>0$ 이다. @prp-properties_of_limsup 에 의해 $\varepsilon < \dfrac{r}{2}$ 에 대해 어떤 $N\in \mathbb{N}$ 이 존재하여,

$$
n \ge N \implies a_n< a+\varepsilon,\, b_n < b+\varepsilon
$$

이므로 

$$
n \ge N \implies a_n + b_n < a+b+2\varepsilon < a+b+r =c-r
$$

이다. 즉 $a_n + b_n$ 의 상극한은 $c$ 가 아닌데 이는 모순이다. 즉, 

$$
\limsup_{n \to \infty} (a_n + b_n) \le \limsup_{n \to \infty} a_n + \limsup_{n \to \infty} b_n
$$

이다. 

등호가 성립하지 않는 예를 블어보자. $a_n = (−1)^n +2$, $b_n = −(−1)^n +2$ 라 하면 $a=3,\, b=3$ 이지만 $a_n +b_n = 4$ 이므로 $a_n + b_n$ 의 상극한은 각각의 상극한보다 작다.
:::

</br>

::: {#exr-rudin_3_7}

#### Rudin 3.7

양의 실수열 $\langle a_n \rangle$ 에 대해 $\sum a_n$ 이 수렴하면 $\sum \dfrac{\sqrt{a_n}}{n}$ 도 수렴함을 보여라.

:::

::: {.solution}

Cauchy-Schwartz 부등식을 사용한다. 즉 수열 $a_n,\,b_n$ 에 대해 

$$
\sum_n a_n b_n \le \sqrt{\sum_n |a_n|^2}  \sqrt{\sum_n |b_n|^2}  
$$

이다. 

$$
\sum_n \dfrac{\sqrt{a_n}}{n} \le \sqrt{\sum_n a_n} \sqrt{\sum_n \dfrac{1}{n^2}}
$$

이다. $\sqrt{\sum_n a_n}$ 는 문제의 조건에 의해 수렴하며, $\sqrt{\sum_n \dfrac{1}{n^2}}$ 가 수렴함은 @prp-convergence_of_1_over_n_p 로부터 안다.

:::

</br>

::: {#exr-rudin_3_8}

#### Rudin 3.8

$\sum a_n$ 이 수렴하며 $\langle b_n \rangle$ 이 유계인 단조수열일 때 $\sum a_n b_n$ 이 수렴함을 보이시오.

:::

::: {.solution}

$\langle b_n \rangle$ 이 유계인 단조수열이므로 수렴한다. $b=\lim b_n$ 라 하자. $b_n$ 이 단조증가수열이라면 $c_n=b-b_n$ 은 단조감소수열이며 $\lim c_n = 0$ 이다. 

$$
\sum_n a_n b_n = \sum_{n} a_n (b-c_n) = b\sum_n a_n - \sum_n a_n c_n 
$$

이며 @prp-convergence_of_product_of_sequences 에 의해 $\sum_n a_n c_n$ 은 수렴하므로 위 식은 수렴하는 두 수열의 차이므로 수렴한다. $b_n$ 이 단조감소수열이라면 $c_n = b_n -b$ 는 $0$ 으로 수렴하는 단조감소수열이고 

$$
\sum_n a_n b_n = \sum_{n} a_n (c_n + b) = b\sum_n a_n + \sum_n a_n c_n 
$$

이므로 좌변은 수렴하는 두 수열의 합이되며, 따라서 수렴한다. $\square$

:::

</br>

::: {#exr-rudin_3_11}

#### Rudin 3.11

양의 실수열 $\langle a_n \rangle$ 에 대해 $s_n = \displaystyle \sum_{k=1}^n a_k$ 이며 $\sum a_n$ 은 발산한다고 하자.

&emsp; ($1$) $\sum \dfrac{a_n}{1+a_n}$ 은 발산함을 보여라.

&emsp; ($2$) $\dfrac{a_{n+1}}{s_{N+1}} + \cdots + \dfrac{a_{N+k}}{s_{N+k}} \ge 1- \dfrac{s_N}{s_{N+k}}$ 임을 보이고 $\sum \dfrac{a_n}{s_n}$ 이 발산함을 보여라.

&emsp; ($3$) $\dfrac{a_n}{{s_{n}}^2} \le \dfrac{1}{s_{n-1}} - \dfrac{1}{s_n}$ 임을 보이고 $\sum \dfrac{a_n}{{s_n}^2}$ 가 수렴함을 보여라.

&emsp; ($4$) $\sum \dfrac{a_n}{1+a_n}$ 과 $\sum \dfrac{a_n}{1+n^2a_n}$ 에 대해 더 알 수 있는 것은 무엇인가?

:::

::: {.solution}

($1$) $\sum \dfrac{a_n}{1+a_n}$ 이 수렴함을 가정하자. 그렇다면 $\displaystyle \lim_{n \to \infty} \dfrac{a_n}{1+a_n}=0$ 이며 따라서 $a_n \to 0$ 이다. 그렇다면 어떤 $N\in \mathbb{N}$ 에 대해 $n\ge N \implies a_n<1$ 이며

$$
a_n<1 \implies a_n^2 < a_n \implies a_n^2+a_n \le 2a_n \implies \dfrac{a_n}{2} \le \dfrac{a_n}{1+a_n}
$$

이므로 비교판정법에 의해 $\sum a_n$ 은 수렴해야 하는데 이는 가정에 모순된다. 따라서 $\sum \dfrac{a_n}{1+a_n}$ 은 발산한다.

($2$) 부등식은 다음과 같이 보인다.

$$
\dfrac{a_{n+1}}{s_{N+1}} + \cdots + \dfrac{a_{N+k}}{s_{N+k}} \ge \dfrac{a_{n+1}}{s_{N+k}} + \cdots + \dfrac{a_{N+k}}{s_{N+k}} = \dfrac{s_{N+k}-s_N}{s_{N+k}} = 1-\dfrac{s_N}{s_{N+k}}
$$

이제 $\sum \dfrac{a_n}{s_n}$ 이 발산함을 보이자. $s_n$ 이 $+\infty$ 로 발산하므로 충분히 큰 $k$ 에 대해 $s_{N+k}>2s_N$ 이며 따라서 $\dfrac{a_{n+1}}{s_{N+1}} + \cdots + \dfrac{a_{N+k}}{s_{N+k}} \ge \dfrac{1}{2}$ 이다. 즉 코시 판정법의 발산 조건이다. 

($3$) $s_n > s_{n-1}$ 이므로

$$
\dfrac{1}{s_{n-1}}-\dfrac{1}{s_n} = \dfrac{a_n}{s_n s_{n-1}} \ge \dfrac{a_n}{{s_n}^2}
$$

이다. 따라서, 

$$
\begin{aligned}
\sum_{k=1}^n \dfrac{a_n}{{s_n}^2} &= \dfrac{1}{a_1} + \sum_{k=2}^n \dfrac{a_n}{{s_n}^2} \\
&\le \dfrac{1}{a_1} + \left(\dfrac{1}{s_1}- \dfrac{1}{s_2}\right) + \cdots \left(\dfrac{1}{s_{n-1}}-\dfrac{1}{s_n}\right) \\
&= \dfrac{2}{a_1}-\dfrac{1}{s_n}
\end{aligned}
$$

이므로 $\sum \dfrac{a_n}{{s_n}^2} \le \dfrac{2}{a_1}$ 이다. 따라서 수렴한다.

($4$) $\langle na_n\rangle$ 이 위로 유계인 경우 즉 $na_n < M$ 인 경우 $\dfrac{a_n}{1+na_n} > \dfrac{a_n}{M+1}$ 이므로 발산한다. $\langle na_n \rangle$ 이 $0$ 이 양의 하한 $b$ 를 가지는 경우, 즉 $na_n > b > 0$ 인 경우

$$
\dfrac{a_n}{1+na_n} = \dfrac{1}{n} \dfrac{na_n}{1+na_n} > \dfrac{1}{n}\dfrac{b}{1+b}
$$

이므로 $\sum \dfrac{a_n}{1+na_n}$ 은 발산한다.

수렴하는 경우는 (위스컨신 대학의 solution site 에서 가져왔음) 

$$
a_n = \left\{ \begin{array}{ll} \dfrac{1}{\sqrt{n}} \qquad & n\text{ 이 자연수의 제곱일 때} \\ \dfrac{1}{n^2} &\text{otherwise}.\end{array} \right.
$$

이 있다. 이 $a_n$ 은 문제의 조건을 만족하며, 인덱스가 제곱수가 아닌 항의 합은 수렴하고($<\sum 1/n^2$), 제곱수 인 항의 합은 $\sum \dfrac{1}{m^2+m}$ 이 되므로 수렴한다. 따라서 $\dfrac{a_n}{1+na_n}$ 은 수렴한다.

$\dfrac{a_n}{1+n^2a_n}$ 의 경우

$$
\sum \dfrac{a_n}{1+n^2 a_n} = \sum \dfrac{1}{1/a_n + n^2} < \sum \dfrac{1}{n^2}
$$

이므로 수렴한다.

:::

</br>

::: {#exr-rudin_3_12}

#### Rudin 3.12

$a_n>0$ 이며 $\sum a_n$ 이 수렴한다고 하자. $r_n$ 을 다음과 같이 정한다.


$$
r_n = \sum_{k=n}^\infty a_k.
$$


&emsp; ($1$) $m<n$ 일 때 $\dfrac{a_m}{r_m} + \cdots + \dfrac{a_n}{r_n} > 1- \dfrac{r_n}{r_m}$ 임을 보이고, $\sum \dfrac{a_n}{r_n}$ 이 발산함을 보여라.

&emsp; ($2$) $\dfrac{a_n}{\sqrt{r_n}} < 2(\sqrt{r_n}- \sqrt{r_{n+1}})$ 임을 보이고 $\sum \dfrac{a_n}{\sqrt{r_n}}$ 이 수렴함을 보여라.

:::


::: {.solution}

($1$) $m<n$ 일 때 $r_m > r_n$ 이다. 즉 $\langle r_n\rangle$ 은 단순 감소 수열(같은 값을 갖는 항이 없는 감소수열) 이다.

$$
\dfrac{a_m}{r_m} + \cdots + \dfrac{a_n}{r_n} > \dfrac{a_m + \cdots a_n}{r_m} = \dfrac{r_m-r_{n+1}}{r_m} > \dfrac{r_m - r_n}{r_m} = 1-\dfrac{r_n}{r_m}
$$


$\sum a_n$ 이 수렴하므로 $\langle r_n \rangle \to 0$ 이다. 아무리 큰 $m$ 을 잡더라도 더 큰 어떤 $n$ 에 대해 $r_n < \dfrac{1}{2} r_m$ 이므로

$$
\sum_{k=n}^m \dfrac{a_n}{r_n} > 1-\dfrac{r_n}{r_m} > \dfrac{1}{2}
$$

이다. 코시 판정법에 의해 발산한다.

($2$)  $a_n = r_n - r_{n+1} >0$ 을 이용한다.

$$
\sqrt{r_n}-\sqrt{r_{n+1}} = \dfrac{r_n -r_{n+1}}{\sqrt{r_n}+\sqrt{r_{n+1}}} = \dfrac{a_n}{\sqrt{r_n}+ \sqrt{r_{n+1}}}> \dfrac{a_n}{2 \sqrt{r_{n}}}.
$$

이로부터, 

$$
\sum_{k=1}^n \dfrac{a_n}{\sqrt{r_n}} < 2(\sqrt{r_1}- \sqrt{r_{n+1}}) 
$$


이므로 수렴한다.

:::

</br>

::: {#exr-rudin_3_13}

#### Rudin 3.13

절대수렴하는 두 급수의 코시곱은 절대수렴함을 보이시오.

:::


::: {.solution}
$\displaystyle A'_n = \sum_{k=0}^n |a_k|,\, B'_n = \sum_{k=0}^n |b_k|$, $A' = \displaystyle \lim_{n \to \infty} A'_n$, $B' = \displaystyle \lim_{n \to \infty} B'_n$, $\beta'_n = B'_n - B'$ 이라 하자.

$$
\begin{aligned}
\sum_{k=0}^\infty |c_k| &= |a_0 b_0| + |a_0b_1 + a_1b_0| + \cdots + |a_0b_n + a_1b_{n-1} + \cdots + a_n b_0| \\
&\le |a_0|\left( |b_0|+|b_1|+ \cdots + |b_n| \right) + |a_1|\left( |b_0|+ \cdots + |b_{n-1}|\right)\\
&\qquad \qquad + \cdots + |a_n| \left(|b_0|\right) \\
&= |a_0|B'_n + |a_1| B'_{n-1} + \cdots + |a_n| B'_0\\
&= |a_0|(\beta'_n+B') + |a_1| (\beta'_{n-1}+B') + \cdots + |a_n| (\beta'_0 + B') \\
&= A'_n B' + |a_0| \beta'_n + \cdots + |a_n| \beta'_0
\end{aligned}
$$
이다. $\gamma'_n = |a_0|\beta'_n + \cdots + |a_n| \beta'_0$ 라 하고 $\displaystyle \lim_{n \to \infty} \gamma'_n \to 0$ 임을 보이자. 임의의 $\varepsilon >0$ 을 생각한다. $\displaystyle \lim_{n \to \infty}\beta'_n = 0$ 이므로 $n \ge N \implies |\beta'_n|<\varepsilon$ 이 되도록 $N$ 을 선택 할 수 있다. $n \ge N$ 이면, 
$$
\begin{aligned}
|\gamma'_n| &= \left| \beta'_0|a_n| + \cdots + \beta'_N |a_{n-N}| + \beta'_{N+1} |a_{n-N-1}| + \cdots + \beta'_n |a_0| \right|\\
&\le \left| \beta'_0|a_n| + \cdots + \beta'_N |a_{n-N}|\right| + \left|\beta'_{N+1} |a_{n-N-1}| + \cdots + \beta'_n |a_0| \right|\\
&\le \left| \beta'_0|a_n| + \cdots + \beta'_N |a_{n-N}|\right| + \varepsilon \left(\sum_{k=0}^{n-N-1} |a_k|\right)
\end{aligned}
$$
이다. 여기에 $N$ 을 고정하고 $n \to \infty$ 극한을 취하면, 
$$
0 \le \limsup_{n \to \infty} |\gamma'_n| \le \varepsilon \left( \sum |a_n|\right)
$$
이므로 $\displaystyle \lim_{n \to \infty} \gamma'_n = 0$ 임을 알 수 있다. 즉 $\displaystyle \sum_{k=0}^\infty |c_k| = A'B'$ 이다.
:::



</br>

::: {#exr-kkk_2_7_11}

#### 김김계 2.7.11

유계 실수열 $\langle x_n \rangle$ 이 다음 조건

$$
2x_n \le x_{n-1}+x_{n+1},\qquad n=1,\,2,\ldots
$$

를 만족할 때 $\lim_n (x_{n+1}-x_n)=0$ 임을 보여라.
:::

::: {.solution}
$y_n := x_{n+1}-x_n$ 이라 하자. $\langle x_n\rangle$ 이 유계이므로 $|x_n|<R$ 인 양의 실수 $R\in \mathbb{R}$ 이 존재하며 $|y_n|<2R$ 이므로 $\langle y_n\rangle$ 도 유계이다. 또한 주어진 조건으로 부터 $x_{n+1}-x_n \le x_n -x_{n-1}$ 이므로 $\langle y_{n} \rangle$ 은 단조감소수열이다. 따라서 $\langle y_n \rangle$ 은 수렴한다. 

$y:=\displaystyle \lim_{n \to \infty} y_n$ 이라 하자. 우리는 $y=0$ 임을 보이고자 한다. 

우선 $y>0$ 임을 가정하자. $y$ 가 감소수열이므로 $y_n\ge y$ 이다. 자연수 $N$ 에 대해 
$$
\begin{aligned}
x_{N+1}-x_1 &= (x_{N+1}-x_{N})+ (x_{N}-x_{N-1}) + (x_{N-1}-x_{N-2}) + \cdots + (x_2-x_1) \\
&= y_{N} + y_{N-1} + \cdots + y_{1} > Ny
\end{aligned}
$$

이므로 $x_{N+1} > x_1 + Ny$ 이다. $N > \dfrac{R-x_1}{y}$ 이면 $x_{N+1}>R$ 이므로 $|x_n|<R$ 이라는 가정에 위배된다. 

$y<0$ 이라면 어떤 $N\in \mathbb{N}$ 이 존재하여 $n\ge N \implies y_n < \dfrac{y}{2}$ 이며,

$$
\begin{aligned}
x_{N} - x_{N+M+1} &= x_{N}-x_{N+1}+ x_{N+1}-x_{N+2} + \cdots + x_{N+M}- x_{N+M+1}\\
&= - y_{N} - y_{N+1} - \cdots - y_{N+M} > -(M+1)\dfrac{y}{2}
\end{aligned}
$$

이므로 $x_{N+M+1} < x_N + (M+1)\dfrac{y}{2}$ 이다. $M > -(R+x_N) \dfrac{2}{y}-1$ 이면 $x_{N+M+1}<-R$ 이므로 $|x_n|<R$ 이라는 가정에 위배된다. 따라서 $y=0$ 이다. $\square$

:::

</br>

::: {#exr-kkk_2_7_12}

#### 김김계 2.7.12

실수열 $\langle a_n \rangle$ 에 대하여 새로운 수열 $\langle \sigma_n\rangle$ 을 다음

$$
\sigma_n = \dfrac{1}{n}(a_1+ \cdots + a_n),\qquad n=1,\,2,\ldots,
$$

과 같이 정의하자. 이 때 $\lim_n a_n = a$ 이면 $\lim_n \sigma_n = a$ 임을 보여라.

::: 

::: {.solution}

정해진 $\varepsilon>0$ 에 대해 $n \ge N \implies |a_n - a|<\varepsilon$ 을 만족하는 $N$ 이 존재한다. $n > N$ 이라 하자. 

$$
\begin{aligned}
|\sigma_n - a| & = \dfrac{1}{n} \left| (a_1-a)  + \cdots + (a_N -a ) + (a_{N+1}-a) + \cdots + (a_n - a) \right| \\
& \le \dfrac{|a_1-a| + \cdots + |a_N-a|}{n} + \dfrac{|a_{N+1}-a| + \cdots + |a_{n}-a|}{n} \\
&< \dfrac{|a_1-a| + \cdots + |a_N-a|}{n} + \varepsilon \dfrac{n-N}{n}
\end{aligned}
$$

이다. $N$ 을 고정하고 $n \to \infty$ 에서 생각하면, 

$$
0 \le \limsup_{n \to \infty} |\sigma_n - a| \le \varepsilon
$$

이다. 따라서 $\displaystyle \lim_{n \to \infty} \sigma_n = a$ 이다.

:::

</br>

::: {#exr-rudin_3_16}

#### Rudin 3.16

양수 $\alpha$ 를 고정시킨다. $x_1 > \sqrt{\alpha}$ 를 선택하고
$$
x_{n+1} = \dfrac{1}{2} \left(x_n + \dfrac{\alpha}{x_n}\right)
$$

이라 하자.

($1$) $\langle x_n \rangle$ 이 단조감소수열이며 $\lim_n x_n = \sqrt{\alpha}$ 임을 보여라

($2$) $\varepsilon_n = x_n -\sqrt{\alpha}$ 일 때 $\varepsilon_{n+1} = \dfrac{\varepsilon_n^2}{2x_n}  < \dfrac{\varepsilon_n^2}{2\sqrt{\alpha}}$ 임을 보여라. 또한 $\beta = 2\sqrt{\alpha}$ 라 하면

$$
\varepsilon_n < \beta \left(\dfrac{\varepsilon_1}{\beta}\right)^{2^n} \qquad (n=1,\,2,\,3,\ldots)
$$

임을 보여라

($3$) 이것은 제곱근을 계산하는 좋은 알고리즘이다. 예를 들어 $\alpha=3$ 이고 $x_1=2$ 일 때 $\varepsilon/\beta < \dfrac{1}{10}$ 이며 따라서, 

$$
\varepsilon_5 < 4 \cdot 10^{-16},\qquad \varepsilon_6 < 4 \cdot 10^{-32}
$$

이다.

::: {.solution}

($1$) $a+b\ge 2 \sqrt{ab}$ 이므로 

$$
x_{n+1} = \dfrac{1}{2} \left(x_n + \dfrac{\alpha}{x_n}\right) \ge \sqrt{\alpha}
$$

이다. $x_n > \sqrt{\alpha}$ 이며 $\alpha/x_n <\sqrt{\alpha}$ 이다.

$$
x_n-x_{n+1} = \dfrac{1}{2}\left(x_n - \dfrac{\alpha}{x_n}\right) >0
$$

이므로 $\langle x_n \rangle$ 은 단조감소수열이다. $\langle x_n \rangle$ 이 유계인 단조감소수열이므로 수렴하며 $\lim_n x_n=x$ 라 놓으면 $x=\dfrac{1}{2} \left(x+\dfrac{\alpha}{x}\right)$ 이므로 $x=\sqrt{\alpha}$ 이다.

($2$) $\dfrac{\varepsilon_n^2}{2x_n} = \dfrac{1}{2x_n}\left(x_n^2 - 2\sqrt{\alpha}x_n + \alpha\right) = \dfrac{1}{2}\left(x_n + \dfrac{\alpha}{x_n}\right) - \sqrt{\alpha} = x_{n+1}-\sqrt{\alpha} = \varepsilon_{n+1}$

이며 $x_n> \sqrt{\alpha}$ 이므로 $\dfrac{\varepsilon_n^2}{2x_n}< \dfrac{\varepsilon_n^2}{2\sqrt{\alpha}}$ 이다. $\beta = 2\sqrt{\alpha}$ 라 하면 $\varepsilon_{n+1} < \dfrac{\varepsilon_{n}^2}{\beta}$ 이다.

$$
\varepsilon_{n+1} < \dfrac{\varepsilon_n^2}{\beta} < \dfrac{1}{\beta}\left(\dfrac{\varepsilon_{n-1}^2}{\beta}\right)^2 = \dfrac{\varepsilon_{n-1}^4}{\beta^3} < \cdots < \beta \left(\dfrac{\varepsilon_1}{\beta}\right)^{2^n}
$$


:::