---
title: "미분"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

## 실함수의 미분

### 미분가능성과 도함수 {#sec-part2_differentiability}

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_differentiable}

#### 미분가능과 도함수

$f:[a,\,b] \subset \R \to \R$ 과 $x\in [a,\,b]$ 에 대해 

$$
\lim_{h \to 0} \dfrac{f(x+h)-f(x)}{h}
$$ {#eq-part2_differentiability}

가 존재할 때 $f$ 가 $x$ 에서 **미분 가능하다(be differentiable)** 고 하며 @eq-part2_differentiability 의 극한값을 $f'(x)$ 라고 표기한다. $f$ 가 $[a,\,b]$ 의 모든 값에서 미분가능할 할 때 $f'$ 값을 $[a,\,b]$ 에서 정의된 함수로 생각 할 수 있으며 $f'(x)$ 를 $f(x)$ 의 **도함수 (derivative)** 라고 한다.

::: 
:::

</br>


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_continuity_and_differentiability}

$f:[a,\,b]\to \R$ 이 $x\in [a,\,b]$ 에서 미분가능하면 $f$ 는 $x$ 에서 연속이다.

:::

</div></br>

::: {.proof}

$\lim_{h \to 0} f(x+h)-f(x) \ne 0$ 이면 $x$ 에서 미분가능하지 않으므로 $x$ 에서 미분가능하면 $\lim_{h \to 0} f(x+h)-f(x) = 0$ 이다. 즉 $f$ 는 $x$ 에서 연속이다. $\square$
:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_continuity_and_differentiability}

$[a,\,b]$ 구간에서 정의된 함수 $f,\,g$ 가 $x \in [a,\,b]$ 에서 미분가능하면 $f+g,\, fg,\, f/g$ 가 $x$ 에서 미분가능하며, 

&emsp;($1$) $(f+g)'(x) = f'(x)+g'(x)$, 

&emsp;($2$) $(fg)'(x) = f'(x) g(x) + f(x) g'(x)$, 

&emsp;($3$) $\left(\dfrac{f}{g}\right)'(x) = \dfrac{f'(x)g(x) - f(x) g'(x)}{(g(x))^2}$

이다. 단 ($3$) 의 경우 $g(x)\ne 0$ 일 때 성립한다. 

:::

</div></br>

::: {.proof}

($1$) $\displaystyle \lim_{t\to x} (f+g)(t)= \lim_{t\to x} f(t) + \lim_{t \to x} g(t)$ 임을 이용한다.

($2$) 아래 식을 이용한다.

$$
\begin{aligned}
&\dfrac{f(x+h)g(x+h)-f(x)g(x)}{h} \qquad \\
&= \dfrac{f(x+h)g(x+h) - f(x) g(x+h) + f(x)g(x+h) - f(x)g(x)}{h} \\
&= g(x+h)\dfrac{f(x+h)-f(x)}{h} + f(x) \dfrac{g(x+h)-g(x)}{h}
\end{aligned}
$$

($3$) $g(x) \ne 0$ 일 때 

$$
\begin{aligned}
\left(\dfrac{1}{g}\right)'(x) &= \lim_{h \to 0}\dfrac{1/g(x+h) - 1/g(x)}{h} \\
&= -\lim_{h \to 0}\dfrac{1}{g(x+h)g(x)}\dfrac{g(x+h) - g(x)}{h} \\
&= - \dfrac{g'(x)}{(g(x))^2}
\end{aligned}
$$

이므로 ($2$) 와 함께 사용하면 ($3$) 의 결과를 얻는다. $\square$

:::

</br>

미분 가능성에 대한 다른 정의가 가능하며, 이 정의는 앞으로 자주 사용된다. 

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part2_other_form_of_differentiability}

$f:(a,\,b) \to \R$ 과 $x\in (a,\,b)$ 에 대해 다음은 동치이다.

($1$) $f$ 는 미분 가능하다.

($2$) 어떤 상수 $a$ 와 $0$ 으로의 극한이 $0$ 인 어떤 함수 $\eta:N(0,\,\delta)\backslash\{0\} \to \R$ 에 대해

$$
f(x +h) -f(x) = ah + |h| \eta (h)
$$ {#eq-part2_other_form_of_differentiability}

이다. 
:::

</div></br>

::: {.proof}

($1 \implies 2$) $\eta(h)$ 를 다음과 같이 정의한다.

$$
\eta(h) = \left\{\begin{array}{ll} \dfrac{f(x+h)-f(x)}{h} - f'(x), \qquad &h>0, \\ -\dfrac{f(x+h)-f(x)}{h} + f'(x), \qquad &h<0 \end{array}\right.
$$

그렇다면 $\displaystyle \lim_{h \to 0}\eta(h) = 0$ 이며 @eq-part2_other_form_of_differentiability 를 만족한다. 그리고 $a=f'(x)$ 이다. 


($2\implies 1$) 미분가능의 정의에 의해

$$
\lim_{h \to 0}\dfrac{f(x+h)-f(x)}{h} = \lim_{h \to 0} \left(a + \dfrac{|h|}{h}\eta (h)\right) = a
$$

이다. $\square$

:::

</br>


<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part2_derivatives_of_simplie_functions}

다음은 쉽게 보일 수 있다. 

($1$) $f(x)$ 가 상수함수일 경우 $f'(x) = 0$ 이다.

($2$) $n\in \mathbb{Z}_+$ 에 대해 $f(x)=x^n$ 일 경우 $f'(x) = nx^{n-1}$ 이다. 


:::

</div>

<br>

### 연쇄 규칙 {#sec-part2_chain_rule}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-part2_chain_rule}

#### 연쇄 규칙


$f:[a,\,b]\to \R$ 이 $x\in [a,\,b]$ 에서 미분가능하며 $f(x)$ 를 포함하는 구간 $I$ 에서 정의된 함수 $g$ 가 $f(x)$ 에서 미분가능하다고 하자. 이 때 $g\circ f$ 는 $x$ 에서 미분 가능하며 그 미분값은 다음과 같다.

$$
(g\circ f)'(x) = g'(f(x))f'(x).
$$ {#eq-part2_chain_rule}

:::

</div></br>

::: {.proof}

$h=g \circ f,\, y=f(x)$ 라고 하자. @prp-part2_other_form_of_differentiability 에 의해 

$$
\begin{aligned}
f(x+h) - f(x) &= hf'(x) + |h|\eta(h), \\
g(y+s) - g(y) & = sg'(y) + |s|\zeta(s)
\end{aligned}
$$

인 $\eta(h),\, \zeta(s)$ 가 존재하며 $0$ 으로의 극한은 $0$ 이다. 

$$
\begin{aligned}
h(x+h)-h(x) &= g(f(x+h)) - g(f(x)) \\
&= g(y + hf'(x) +|h|\eta(h)) - g(y) &;s=hf'(x) +|h|\eta(h)\\
& = (hf'(x)+|h|\eta (h))g'(y) + |s| \zeta (s) \\
& = hf'(x) g'(y) + |h| \left[\eta (h) g'(y) + \dfrac{s}{|h|}\zeta (s) \right]
\end{aligned}
$$

이며 마지막 줄 두번째 항의 $[\cdots]$ 부분은 $h \to 0$ 극한에서 $s\to 0$ 이므로 $\to 0$ 이다. 따라서,  @eq-part2_chain_rule 가 성립한다. $\square$

:::

</br>

### 도함수의 연속성과 계층 {#sec-continuity_of_derivatives}

우리는 앞서 @prp-part2_continuity_and_differentiability 에서 $f:[a,\,b] \to \R$ 이 $x_0\in [a,\,b]$ 에서 미분가능하면 $x_0$ 에서 연속이라는 것을 보였다. $f$ 의 도함수 $f'(x)$ 의 경우는 연속함수가 아닐 수 있다.


<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part2_case_of_derivative_without_continuity}

$f:\R \to \R$ 이 다음과 같이 정의되어 있다고 하자. 

$$
f(x) = \left\{\begin{array}{ll} 0, & x=0, \\ x^2 \sin \dfrac{1}{x},\,&x\ne 0\end{array}\right.
$$

$f(x)$ 는 $\R$ 에서 미분가능하며 그 도함수는 

$$
f'(x) = \left\{\begin{array}{ll} 0, & x=0, \\ 2x \sin \dfrac{1}{x}- \cos \dfrac{1}{x},\,&x\ne 0\end{array}\right.
$$

이다. 그러나 $f'(x)$ 는 $x=0$ 에서 연속이 아니다. 

:::

</div>

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_differentiable}

#### 도함수의 차수

구간에서 정의된 함수 $f:I \to \mathbb{R}$ 의 도함수 $f'(x)$ 를 생각 할 수 있다. $f'(x)$ 가 $I$ 에서 미분가능하면 $f'(x)$ 의 도함수를 $f''(x)$ 혹은 $f^{(2)}(x)$ 라고 쓰고 이차 도함수라고 한다. 이것을 계속하면 $n$ 차 도함수 $f^{(n)}(x)$ 를 생각 할 수 있다. 

::: 
:::

</br>

@exm-part2_case_of_derivative_without_continuity 에서 보았듯이 $n$-차 도함수가 연속일 수도 있고 아닐 수도 있다. $n$ 차 도함수가 연속인 것은 매우 중요한 성질이므로 여기에 특별한 이름을 붙인다.

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_class_of_derivatives}

#### 도함수의 계층

구간 $I$ 에서 정의된 함수 $f:I \to \mathbb{R}$ 이 $n$ 번 미분가능하며 $n$ 번째 도함수가 연속일 때 이 함수를 $C^k$-함수라고 한다. 연속인 함수는 $C^0$-함수이며 도함수가 연속이면 $C^1$-함수 라고 한다. 다항함수나 지수함수와 같이 무한번 미분 가능하며 연속인 함수는 $C^\infty$ 라고 표기한다.

::: 
:::



## 평균값 정리와 로피탈 정리

### 평균값 정리 {#sec-mean_value_theorem}

::: {.callout-note appearance="simple" icon="false"}

::: {#def-part2_extreme_value}

#### 극대값과 극소값

거리공간에서 $X$ 에서 정의된 실함수 $f:X\to\R$ 을 생각하자. $x\in X$ 일 때 어떤 $x$ 의 근방 $N=N(x,\,\delta)$ 에서 $p\in N \implies f(p) \le f(x)$ 일 때 $f$ 가 $x$ 에서 **극대값(local maximum)** 을 갖는다고 한다. 반대로 $p\in N \implies f(p) \ge f(x)$ 일 때 $f$ 가 $x$ 에서 **극소값(local minimum)** 을 갖는다고 한다. 극대값과 극소값을 **극값 (local extrema)** 라고 한다.
::: 
:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-part2_derivative_of_extreme_value}

함수 $f:[a,\,b] \to \R$ 이 미분가능하며 $p\in (a,\,b)$ 가 극값일 경우 $f'(p)=0$ 이다.

:::

</div></br>

::: {.proof}

$p$ 가 극대값이라고 하자. 어떤 $I_p=(p-\delta,\, p+\delta)$ 에서 $x\in I_p \implies f(x) \le f(p)$ 이다. 이 때 $h>0$ 이면 $\phi_1(h) := \dfrac{f(p+h)-f(p)}{h} <0$ 이며 $h<0$ 이면 $\phi_2(h) := \dfrac{f(p+h)-f(p)}{h} >0$ 이다. $h\to 0$ 극한에서 $\phi_1(h) \le 0$ 이며 $\phi_2(h) \ge 0$ 인데 두 극한이 같아야 하므로 $f'(p) = 0$ 이다. $p$ 가 극소값인 경우도 같은 방법으로 보일 수 있다. $\square$ 

:::

</br>


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-part2_generalized_mean_value_theorem}

$f:[a,\,b]\to \R$ 가 미분가능함수일 때 $f(a)=f(b)$ 이면 어떤 $c\in (a,\,b)$ 에서 $f'(c) = 0$ 이다.

:::

</div></br>

::: {.proof}

$f$ 가 상수함수이면 자명하므로 $f$ 가 상수함수가 아니라고 하자. $[a,\,b]$ 는 옹골집합이므로 @thm-part2_extreme_value_theorem 에 의해 최소값과 최대값을 가지며 최소한 둘 중 하나는 $f(a)$ 값과 (그리고 $f(b)$ 값과) 다르다. $c\in (a,\,b)$ 에서 최대값 혹은 최소값을 가진다면 당연히 $c$ 에서 극값을 가지므로 $f'(c) = 0$ 이다. $\square$

:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-part2_generalized_mean_value_theorem}

#### 일반화된 평균값 정리

$f,\,g:[a,\,b] \to \R$ 이 $(a,\,b)$ 에서 미분가능하면 다음을 만족하는 $c\in (a,\,b)$ 가 존재한다.

$$
[f(b)-f(a)] g'(c) = [g(b)-g(a)] f'(c).
$$

:::

</div></br>

::: {.proof}

함수 $h:[a,\,b] \to \R$ 을 다음과 같이 정의한다.

$$
h(t) := [f(b) -f(a)] g(t) - [g(b)-g(a)] f(t).
$$ 

$h(a) = h(b)=f(b)g(a) - f(a)g(b)$ 이다. @lem-part2_generalized_mean_value_theorem 의해 $h'(c)=0$ 인 $c\in (a,\,b)$ 가 존재한다. $\square$ 

:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-part2_mean_value_theorem}

#### 평균값 정리

$f:[a,\,b] \to \R$ 이 $(a,\,b)$ 에서 미분가능하면 다음을 만족하는 $c\in (a,\,b)$ 가 존재한다.

$$
f(b)-f(a) = (b-a)f'(c)
$$ {#eq-part2_mean_value_theorem}

:::

</div></br>

::: {.proof}
@thm-part2_generalized_mean_value_theorem 에서 $g(x) = x$ 로 놓으면 된다. $\square$ 

:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-part2_mean_value_theorem}

$f:[a,\,b]\to \R$ 이 $I=(a,\,b)$ 에서 미분가능하면 다음이 성립한다.

&emsp;($1$) $x\in I \implies f'(x)\ge 0$ 이면 $f$ 는 단조증가함수이다.

&emsp;($2$) $x\in I \implies f'(x) = 0$ 이면 $f$ 는 상수함수이다.

&emsp;($3$) $x\in I \implies f'(x) \le 0$ 이면 $f$ 는 단조감소함수이다.

:::

</div></br>

::: {.proof}

평균값정리(@thm-part2_mean_value_theorem) 에 따라 임의의 $x_1,\,x\in \in I$ 에 대해 

$$
f(x_2)-f(x_1)= (x_2-x_1)f'(x)
$$

를 만족하는 $x\in (x_1,\,x_2)$ 가 존재한다. $x_2>x_1$ 이라면 $f(x_2)-f(x_1)=(x_2-x_1)f'(x) >0$ 이므로 단조증가함수이다. 나머지 경우에 대해서도 쉽게 보일 수 있다. $\square$

:::

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part2_mean_value_theorem_is_not_valid_for_complex_function}

#### $\R \mapsto \mathbb{C}$ 함수와 평균값 정리

$f:\R \to \mathbb{C}$ 가 $f(x) = e^{ix}= \cos x + i \sin x$ 라고 하자. $f(2\pi) = f(0) = 0$ 이며 $f'(x) = ie^{ix}$ 이지만 $|f'(x) | = 1$ 이므로 중간값 정리가 성립하지 않는다. 즉 $\R \mapsto \mathbb{C}$ 함수의 경우 중간값 정리가 성립함을 보장 할 수 없다.

:::

</div>
</br>


### 로피탈 정리 {#sec-part2_Lhopital_theorem}


로피탈 정리는 실제 극한값을 계산할 때 아주 유용한 정리이다. 

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-part2_Lhopital_theorem}

#### 로피탈 정리

$x_0$ 를 포함하는 어떤 열린 구간 $I$ 에서 미분가능한 함수 $f,\,g :I \to \mathbb{R}$ 를 생각하자. $g'(x_0)\ne 0$ 이라고 하자. 이 때  

&emsp; ($1$) $\displaystyle \lim_{x\to x_0} f(x) = \lim_{x\to x_0} g(x) = 0$ 이거나

&emsp; ($2$) $\displaystyle \lim_{x\to x_0} g(x) = \pm \infty$ 

의 두가지 경우 가운데 하나이면서

$$
\lim_{x\to x_0}\dfrac{f'(x)}{g'(x)} = l
$$ {#eq-part2_lhopital_1}

라면

$$
\lim_{x\to x_0}\dfrac{f(x)}{g(x)} = l
$${#eq-part2_lhopital_2}

이다.


:::

</div></br>

::: {.proof}

임의의 $\varepsilon >0$ 에 대해

$$
|x-x_0|<\delta \implies \left|\dfrac{f'(x)}{g'(x)}-l\right|<\varepsilon
$$

인 $\delta > 0$ 이 존재한다. 구간 $N:=\left(x_0-\frac{\delta}{2},\,x_0+\frac{\delta}{2}\right) \cap I$ 라고 정하자. $x,\,t\in N,\, t>x$ 이면 @thm-part2_generalized_mean_value_theorem 에 따라

$$
\dfrac{f(t)-f(x)}{g(t)-g(x)} = \dfrac{f'(y)}{g'(y)}
$${#eq-part2_lhopital_3}

인 $y\in (x,\,t) \subset N$ 가 존재하며, 따라서,

$$
\left|\dfrac{f(t)-f(x)}{g(t)-g(x)} - l\right|<\varepsilon
$${#eq-part2_lhopital_4}

이다. ($1$) 의 경우 즉, $\displaystyle \lim_{x\to x_0} f(x) = \lim_{x\to x_0} g(x) = 0$ 라면 

$$
\left| \dfrac{f(t)}{g(t)} - l \right | <\varepsilon
$${#eq-part2_lhopital_6}

이다. 즉 $\displaystyle \lim_{x\to x_0} \dfrac{f(x)}{g(x)} = l$ 이다.

이제 ($2$) 의 경우를 생각하자. 우선 $\displaystyle \lim_{x \to x_0}g(x) = \infty$ 라고 하자. 
@eq-part2_lhopital_3 로부터

$$
l-\varepsilon < \dfrac{f(t)-f(x)}{g(t)-g(x)} < l+\varepsilon
$${#eq-part2_lhopital_7}

에서 $x \in N,\, x > x_0$ 로 고정하면 $t \in (x_0,\,c) \implies g(t)>g(x)$ 인 $c<x$ 가 존재한다. @eq-part2_lhopital_7 에 $(g(t)-g(x))/g(t)$ 를 곱하면 

$$
\dfrac{f(x)}{g(t)} + (l-\varepsilon)\dfrac{g(t)-g(x)}{g(t)} < \dfrac{f(t)}{g(t)} <\dfrac{f(x)}{g(t)} + (l+\varepsilon)\dfrac{g(t)-g(x)}{g(t)}
$$

이며 $t\to x_0$ 극한에서, $f(t)/g(t) \to l$ 임을 알 수 있다. 또한 같은 방법으로 $\displaystyle \lim_{x\to x_0} g(x) = -\infty$ 의 경우에도 성립함을 알 수 있다. 


:::

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part2_Lhopital_theorem_for_complex_function}

#### $\R \mapsto \mathbb{C}$ 함수와 로피탈 정리

$f,\,g:(0,\,1) \to \mathbb{C}$ 가 $f(x) := x$, $g(x) := x+x^2e^{i/x^2}$ 으로 정의되었다고 하자. $x\to 0$ 에 대해 $f(x) \to 0,\, g(x) \to 0$ 이다. 또한

$$
\lim_{x \to 0}\dfrac{f(x)}{g(x)} = 1
$$

이다. 여기서 

$$
g'(x) = 1+ \left(2x - \dfrac{2i}{x}\right)e^{i/x^2}
$$

이므로

$$
|g'(x)| \ge \left| 2x - \dfrac{2i}{x} \right| -1 \ge \dfrac{2}{x}-1
$$

이다. 이로부터

$$
\left|\dfrac{f'(x)}{g'(x)}\right| = \dfrac{1}{|g'(x)|} \le \dfrac{x}{2-x}
$$

이므로

$$
\lim_{x \to 0} \dfrac{f'(x)}{g'(x)} = 0
$$

이다. 즉 $\R\mapsto \mathbb{C}$ 함수의 경우 로피탈의 정리가 성립하지 않는다.

:::

</div>
</br>


## 테일러 정리


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-part2_tayler_theorem}

#### 테일러 정리

$f:[a,\,b]\to \R$ 이 $C^{n-1}$ 급 함수이며 $(a,\,b)$ 구간에서 $n$ 번 미분 가능하다고 하자. $x,\,t\in (a,\,b)$ 에 대해 
$$
f(x) = \sum_{k=0}^{n-1}\dfrac{f^{(k)}(t)}{k!}(x-t)^{k} + \dfrac{f^{(n)}(c)}{n!}(x-t)^n 
$$ {#eq-part2_tayler_theorem}

을 만족하는 $\xi$ 가 $x,\,t$ 사이에 반드시 존재한다. 

:::

</div></br>

::: {.proof}

$n=1$ 일 경우는 평균값 정리이다.

$$
f(x) = \sum_{k=0}^{n-1} \dfrac{f^{(k)}(t)}{k!}(x-t)^k + M(x-t)^n
$$ {#eq-part2_tayler_theorem_1}

를 만족하는 $M$ 을 생각하자. $y\in [a,\,b]$ 에 대해

$$
g(y) := f(y) - \sum_{k=0}^{n-1} \dfrac{f^{(k)}(t)}{k!}(y-t)^k - M(y-t)^n
$$ {#eq-part2_tayler_theorem_2}

라고 하면

$$
g^{(n)}(y) = f^{(n)}(y) - n!M
$$

이다. 이제 $g^{(n)}(y)=0$ 인 $y$ 가 반드시 존재한다는 것을 보이면 된다. @eq-part2_tayler_theorem_2 를 생각하면

$$
g(t) = g'(t) = \cdots = g^{(n-1)}(t) = 0
$$

임을 안다. @eq-part2_tayler_theorem_1 로부터 $g(x) = 0$ 이므로 $g'(x_1) = 0$ 인 $x_1$ 이 $t$ 와 $x$ 사이에 존재하며 $g''(x_2)$ 인 $x_2$ 가 $x_1$ 과 $t$ 사이에 존재한다. 이것을 계속하면 $g^{(n-1)}(x_{n-1}) = 0$ 인 $x_{n-1}$ 이 $t$ 와 $x_{n-2}$ 사이에 존재하므로 $g^{(n)}(x_n)=0$ 인 $x_n$ 도 $t$ 와 $x_{n-1}$ 사이에 존재한다. $g^{(n)}(x_n) = f^{(n)}(x_n)-n!M = 0$ 이므로 $M=f^{(n)}(x_n)/n!$ 이다. $\square$


:::

</br>

## 연습문제 {.unnumbered}


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_1}

#### Rudin 5.1

$f:\R \to \R$ 이 모든 $x,\,y\in \R$ 에 대해 

$$
|f(x)-f(y)| \le (x-y)^2
$$

일 때 $f$ 는 상수함수임을 보여라.

:::

</div>

</br>

::: {.solution}

$$
\left|\dfrac{f(x+h)-f(x)}{h}\right| \le |h|
$$

이므로 $h \to 0$ 극한을 생각하면 모든 $x\in \R$ 에 대해 $f$ 는 미분가능하며 $f'(x) = 0$ 이다. $f$ 가 미분가능하므로 임의의 $x,\,y\in R$ 에 대해

$$
f(x)-f(y)=(x-y)f'(c) = 0
$$

이므로 $f(x)$ 는 상수함수이다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_2}

#### Rudin 5.2

$(a,\,b)$ 구간에서 $f'(x)>0$ 이다. $f$ 가 $(a,\,b)$ 구간에서 strictily increasing 임을 보여라. $g=f^{-1}$ 에 대해 $g$ 가 미분가능하며, 

$$
g'(f(x)) = \dfrac{1}{f'(x)},\qquad (a<x<b)
$$

임을 보여라.

:::

</div>

</br>

::: {.solution}

임의의 $a<x<y<b$ 에 대해 $f(y)-f(x) = (y-x)f'(c)$ 를 만족하는 $c\in(x,\,y)$ 가 존재하는데 $f'(c)>0$ 이므로 $f(y)-f(x) >0$ 이다. 즉 $f$ 는 $(a,\,b)$ 구간에서 strictily increasing 하다. $f$ 가 $(a,\,b)$ 구간에서 strictily increasing 이므로 전단사이며, 따라서 역함수가 존재한다. 즉 $g$ 는 $(f(a),\, f(b))$ 구간에서 strictly increasing 이다. $y,\,s$ 에 대해 $g(y)=x,\, g(s)=t$ 라고 하자. 

$$
g'(f(t)) = g'(s)=\lim_{y \to s} \dfrac{g(y)- g(s)}{y-s} = \lim_{x \to t} \dfrac{x-t}{f(x)-f(t)} = \dfrac{1}{f'(t)}
$$

이다.
:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_3}

#### Rudin 5.3

$g:\R \to \R$ 의 도함수는 유계이다 (즉 $|g'|<M$). 고정된 $\varepsilon>0$ 에 대해 $f(x) = x+\varepsilon g(x)$ 라고 하자. $\varepsilon$ 이 충분히 작다면 $f$ 는 전단사 임을 보여라.


:::

</div>

</br>

::: {.solution}

$f'(x) = 1+\varepsilon g'(x)$ 이므로 $\varepsilon < 1/M$ 이라면 $f'(x)>0$ 이다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_4}

#### Rudin 5.4

$C_0,\ldots,\,C_n$ 이 실수 이며

$$
C_0 + \dfrac{C_1}{2} + \cdots + \dfrac{C_{n-1}}{n} + \dfrac{C_n}{n+1}=0
$$

이라고 하자. 하자 이 때 방정식

$$
C_0 + C_1x + \cdots + C_{n-1}x^{n-1} + C_n x^n=0
$$

은 $0$ 과 $1$ 사이에서 최소한 하나의 근을 가짐을 보여라.


:::

</div>

</br>

::: {.solution}

$g(x) = C_0 x + \dfrac{C_2}{2}x^2 + \cdots + \dfrac{C_n}{n+1}x^{n+1}$ 라고 하자. $g(0) = g(1) = 0$ 이다. 중간값 정리(@thm-part2_mean_value_theorem) 에 따라 $g'(x)=0$ 의 해가 $(0,\,1)$ 사이에 존재한다.  

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_5}

#### Rudin 5.5

$f$ 가 모든 $x>0$ 에서 미분가능하며 $\displaystyle \lim_{x \to \infty} f'(x) = 0$ 이라고 하자. $g(x) := f(x+1)-f(x)$ 에 대해 $\displaystyle \lim_{x \to \infty} g(x) = 0$ 임을 보여라.

:::

</div>

</br>

::: {.solution}

$g(x) = f(x+1)-f(x) = f'(c)$ 인 $c\in (x,\, x+1)$ 이 존재한다. 

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_6}

#### Rudin 5.6

$f:[0,\,\infty) \to \R$ 에 대해

($1$) $x\ge 0$ 에 대해 연속이며,

($2$) $x>0$ 에서 미분가능하고,

($3$) $f(0)= 0$ 이며,

($4$) $f'$ 이 단조증가함수이다.

이 때 $g(x):= \dfrac{f(x)}{x}$ 가 $x>0$ 에서 단조증가함수임을 보여라.

:::

</div>

</br>

::: {.solution}

$$
g'(x) = \dfrac{xf'(x) - f(x)}{x^2}
$$

이며 중간값 정리에 의해 $f(x)-f(0) = xf'(t)$ 인 $t\in (0,\,x)$ 가 존재한다. $f'$ 이 단조증가함수이므로 $f'(x)\ge f'(t)$ 이며 따라서 

$$
g'(x) = \dfrac{x(f'(x)-f'(t))}{x^2}\ge 0
$$

이다. 즉 $g$ 도 단조증가함수이다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_7}

#### Rudin 5.7

$f,\,g$ 가 $x$ 에서 미분가능하며 $g'(x) \ne 0$ 이고 $f(x) = g(x) = 0$ 이라고 하자. 이 때

$$
\lim_{t \to x} \dfrac{f(t)}{g(t)} = \dfrac{f'(x)}{g'(x)}
$$

임을 보여라. 

:::

</div>

</br>

::: {.solution}

$t \ne x$ 에 대해
$$
\dfrac{f(t)}{g(t)} = \dfrac{f(t)-f(x)}{g(t)-g(x)} = \dfrac{f'(c)(t-x)}{g'(d)(t-x)}= \dfrac{f'(c)}{g'(d)}
$$

인 $c,\,d \in (t,\,x)$ 에서 존재한다. $\lim t\to x$ 극한에서 생각하면 성립함을 알 수 있다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_8}

#### Rudin 5.8

$f'(x)$ 가 $[a,\,b]$ 구간에서 연속이며 $\varepsilon>0$ 이다. 이 때 다음이 성립하는 $\delta >0$ 이 존재함을 보여라.

$$
0<|t-x|<\delta ,\, a\le x,\,t \le b \implies \left|\dfrac{f(t)-f(x)}{t-x} - f'(x)\right|<\varepsilon.
$$

:::

</div>

</br>

::: {.solution}

$a,\,b\in R$ 에 대해 큰 값과 작은 값 사이의 열린 구간을 $I_{ab}$ 라고 하자. $a<b$ 이면 $I_{a,b}=(a,\,b)$ 이고 $a>b$ 이면 $I_{ab}=(b,\,a)$ 이다. $x \in (a,\,b)$ 를 고정시키자. 중간값 정리에 의해 $f(t)-f(x) = (t-x)f'(y)$ 인 $y\in I_{tx}$  가 존재한다. $f'$ 이 연속이므로 임의의 $\varepsilon>0$ 에 대해

$$
|y-x|<\delta_x \implies |f'(y)-f'(x)|<\varepsilon
$$

인 $\delta_x>0$ 이 존재한다. 이 $\{\delta_x | x\in [a,\,b]\}$ 는 $[a,\,b]$ 에 대한 열린 덮개이며 $[a,\,b]$ 가 옹골집합이므로 유한개만으로 $[a,\,b]$ 를 덮을 수 있다. 이 유한개중 가장 작은 값을 $\delta$ 라고 잡자. $0<|t-x|<\delta$ 이면 $f(t)-f(x)=(t-x)f'(y)$ 인 $y\in I_{tx}$ 가 존재하며 $\delta \le \delta_x$ 이므로

$$
\left|\dfrac{f(t)-f(x)}{t-x} - f'(x)\right|<\varepsilon
$$

이다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_9}

#### Rudin 5.9

$f:\R \to \R$ 이 연속이며, $x\ne 0$ 에 대해 도함수가 존재하고 $\lim_{x \to 0} f'(x) = 3$ 이라고 하자. $f'(0)$ 이 존재하는가?

:::

</div>

</br>

::: {.solution}

로피탈의 정리에 의해

$$
f'(0) = \lim_{t \to 0} \dfrac{f(t)-f(0)}{t-0} = \lim_{t \to 0}\dfrac{f'(t)}{1} = 3
$$


이다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_10}

#### Rudin 5.10

$f,\,g : (0,\,1) \to \mathbb{C}$ 이며 $x\to 0$ 에 대해 $f(x) \to 0$, $g(x) \to 0$, $f'(x) \to A$, $g'(x) \to B$ 이다. 이 때 $B\ne 0$ 이라고 하자. 다음을 보여라.

$$
\lim_{x \to 0} \dfrac{f(x)}{g(x)} = \dfrac{A}{B}.
$$

그리고 @exm-part2_Lhopital_theorem_for_complex_function 과 비교하라.


:::

</div>

</br>

::: {.solution}

$f(x) = f_r (x) + if_i (x)$, $g(x) = g_r(x) + ig(x)$ 이며 $f_r,\,f_i,\,g_r,\,g_i$ 가 모두 $\R\mapsto \mathbb{C}$ 함수라고 하자. $A=A_r+iA_i,\, B=B_r+iB_i$ 이며 $A_r,\,A_i,\,B_r,\,B_i$ 가 모두 실수라고 하자. 

$$
\begin{aligned}
\dfrac{f(x)}{g(x)} &= \left(\dfrac{f(x)}{x}-A\right) \cdot \dfrac{x}{g(x)} + A \cdot \dfrac{x}{g(x)} \\
&= \left[\left(\dfrac{f_r(x)}{x} - A_r\right) + i \left(\dfrac{f_i(x)}{x} - A_i\right)\right] \left(\dfrac{g_r(x)}{x} + i \dfrac{g_i(x)}{x}\right)^{-1} \\
&\qquad + A \left(\dfrac{g_r(x)}{x} + i \dfrac{g_i(x)}{x}\right)^{-1}
\end{aligned}
$$

이며 $x\to 0$ 극한을 취하자. 

$$
\begin{aligned}
\lim_{x \to 0}\dfrac{f_r(x)}{x} &= \lim_{x\to 0}\dfrac{f'_r(x)}{1} = A_r, \\
\lim_{x \to 0}\dfrac{f_i(x)}{x} &= \lim_{x\to 0}\dfrac{f'_i(x)}{1} = A_i, \\
\lim_{x \to 0}\dfrac{g_r(x)}{x} &= \lim_{x\to 0}\dfrac{g'_r(x)}{1} = B_r, \\
\lim_{x \to 0}\dfrac{g_i(x)}{x} &= \lim_{x\to 0}\dfrac{g'_i(x)}{1} = B_i,
\end{aligned}
$$

이므로

$$
\lim_{x\to 0} \dfrac{f(x)}{g(x)} = A(B_r+iB_i)^{-1} = \dfrac{A}{B}
$$

이다. @exm-part2_Lhopital_theorem_for_complex_function 의 경우 $\lim_{x \to 0} g'(x)$ 가 발산하는 차이가 있다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_11}

#### Rudin 5.11

$f$ 가 $x$ 의 근방에서 정의되어 있고 $f''(x)$ 가 존재한다. 이 때 

$$
\lim_{h \to 0}\dfrac{f(x+h) + f(x-h) -2f(x)}{h^2} = f''(x)
$$

임을 보여라. $f''(x)$ 가 존재하지 않더라도 위의 극한이 존재할 수 있음을 예를 들어 보여라.
:::

</div>

</br>

::: {.solution}

$x$ 를 고정하고 $h$ 에 대해 로피탈의 정리를 적용하면
$$
\begin{aligned}
\lim_{h \to 0}\dfrac{f(x+h) + f(x-h) -2f(x)}{h^2} &= \lim_{h \to 0} \dfrac{f'(x+h) - f'(x-h)}{2h} \\
&= \lim_{h \to 0}\dfrac{f''(x+h) + f''(x-h)}{2} \\
&= f''(x)
\end{aligned}
$$

이다. 

신호처리등에서 많이 사용되는 $\text{sgn}: \R \to \{0,\,1, -1\}$ 은 다음과 같이 정의된다.

$$
\text{sgn}(x) = \left\{\begin{array}{ll}1, \qquad & x>0,\\ 0, & x=0, \\ -1, & x<0. \end{array}\right.
$$

$x=0$ 에서 연속이 아니므로 도함수 및 이차도함수는 존재하지 않지만 위의 극한은 $0$ 으로 존재한다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_12}

#### Rudin 5.12

$f(x)=|x|^3$ 일 때 $f'(x),\, f''(x)$ 를 계산하라. $f^{(3)}(0)$ 이 존재하지 않음을 보여라.

:::

</div>

</br>

::: {.solution}

$$
f'(x) = \left\{\begin{array}{ll} 3x^2, \qquad &x\ge 0\\ -3x^2 & x<0\end{array}\right. \qquad f''(x) = \left\{\begin{array}{ll} 6x, \qquad &x\ge 0\\ -6x & x<0\end{array}\right. 
$$ 

이지만 $f^{(3)}(0^+) = 6$, $f^{(3)}(0^-)=-6$ 이므로 $f^{(3)}(0)$ 은 존재하지 않는다. 
:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_14}

#### Rudin 5.14

$f:(a,\,b)\to \R$ 이 미분가능하다. 이 때 $f$ 가 볼록함수(@exr-part2_rudin_4_23) 일 필요충분조건이 $f'$ 이 단조증가함수인 것임을 보여라. 또한 $f''(x)$ 가 모든 $x\in (a,\,b)$ 에서 존재한다면 $f$ 가 볼록함수일 필요충분조건은 $\forall x\in (a,\,b), f''(x)\ge 0$ 인 것임을 보여라.

:::

</div>

</br>

::: {.solution}

$f$ 가 볼록함수 임을 가정한다. @exr-part2_rudin_4_23 의 @eq-part2_convex_function_2 을 이용한다. $a<s<t<u<b$ 에 대해

$$
\dfrac{f(t)-f(s)}{t-s} \le \dfrac{f(u)-f(t)}{u-t}
$$

이다. 좌변에 $t \to s$ 극한을 취하면 $f'(s) \le \dfrac{f(u)-f(t)}{u-t}$ 이며 우변에 $t\to u$ 극한을 취하면 $f'(s) \le f(u)$ 이다. 즉 $s<u \implies f'(s) \le f'(u)$ 이므로 $f'$ 은 단조증가함수이다. 

이제 $f'$ 이 단조증가함수임을 가정하자. 여기서 $\lambda \in (0,\,1)$ 에 대해 

$$
f(\lambda x+ (1-\lambda)y) \le \lambda f(x) + (1-\lambda)f(y)
$$

임을 보이고자 한다. $z=\lambda x+ (1-\lambda)y$ 이며, $x<y$ 라고 하면 $x<z<y$ 이다. $\lambda = \dfrac{y-z}{y-x}$ 이며

$$
\begin{aligned}
f(z)-\lambda f(x) - (1-\lambda)f(y) &= f(z) - \dfrac{y-z}{y-x}f(x) - \dfrac{z-x}{y-x}f(y) \\
&= \dfrac{y-z}{y-x}(f(z)-f(x)) - \dfrac{z-x}{y-x}(f(y)-f(z))
\end{aligned}
$$

이다. 중간값 정리에 의해 $f(z)-f(x) = (z-x)f'(c)$ 인 $c\in (x,\,z)$ 가 존재하며 $f(y)-f(z) = (z-y)f'(d)$ 인 $d\in (z,\,y)$ 가 존재한다. 즉 $c<d$ 이다. 그렇다면

$$
\begin{aligned}
f(z)-\lambda f(x) + (1-\lambda)f(y) &= \dfrac{(y-z)(z-x)}{y-x}(f'(c)-f'(d) ) 
\end{aligned}
$$

이다. $x<y<z$ 이므로 $\dfrac{(y-z)(z-x)}{y-x}>0$ 이며 $f'$ 이 단조증가이므로 $f'(c)-f'(d)\le 0$ 이다. 즉

$$
f(\lambda x + (1-\lambda)y) = f(z) \le \lambda f(x) + (1-\lambda) 
$$

이므로 $f$ 는 볼록함수이다. 

이제 $f''(x)$ 가 모든 $x\in (a,\,b)$ 에서 존재함을 가정하자. $f'$ 이 단조증가인 것과 $f''(x)>0$ 인 것은 동치임을 쉽게 보일 수 있다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_15}

#### Rudin 5.15

$a\in \R$ 이며 $f$ 가 $(a,\,\infty)$ 에서 두번 미분 가능한 함수이고 $M_0,\,M_1,\,M_2$ 는 각각 $|f(x)|,\, |f'(x)|,\, |f''(x)|$ 의 $(a,\,\infty)$ 구간에서의 상한이라고 하자. 다음이 성립함을 보여라.

$$
{M_1}^2 \le 4M_0 M_2.
$$


:::

</div>

</br>

::: {.solution}

테일러 전개에 의해 $h>0,\, x>a$ 에 대해

$$
f'(x) = \dfrac{1}{2h}[f(x+2h)-f(x)] - hf''(\xi)
$$

인 $\xi \in (x,\, x+2h)$ 가 존재한다. 따라서

$$
|f'(x)| \le  \dfrac{1}{2h}|f(x+2h)-f(x)| + h|f''(\xi)| \le hM_2 + \dfrac{M_0}{h} \le 2\sqrt{M_0M_2}
$$

가 성립한다. 즉 ${M_1}^2 \le 4M_0M_2$ 이다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_16}

#### Rudin 5.16

$f$ 가 $(0,\,\infty)$ 구간에서 두번 미분 가능하며 $f''$ 은 유계이고 $\displaystyle \lim_{x\to \infty}f(x) = 0$ 이다. $\displaystyle \lim_{x\to \infty} f'(x) = 0$ 임을 보여라.

:::

</div>

</br>

::: {.solution}

@exr-part2_rudin_5_15 를 이용한다. $\displaystyle \lim_{x\to \infty}f(x) = 0$ 이므로 정해진 $\varepsilon >0$ 에 대해 $x>x_0 \implies |f(x)|<\varepsilon$ 인 $x_0$ 가 존재한다. 그렇다면 $x>x_0$ 이면 $(x_0,\, \infty)$ 구간에서 $|f'(x)|< 2 \sqrt{\varepsilon M}$ 이 성립하므로 $\displaystyle \lim_{x\to \infty} f'(x) = 0$ 이다. 

:::


</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part2_rudin_5_18}

#### Rudin 5.18

$f:[a,\,b]\to \R$ 이 $n-1$ 번 미분 가능한 함수이다. $\alpha,\,\beta\in (a,\,b)$ 에 대해 $Q:[a,\,b] \to \R$ 을 $t\ne \beta$ 에 대해

$$
Q(t) := \dfrac{f(t)-f(\beta)}{t-\beta}
$$

라고 하자. $f(t) - f(\beta) = (t-\beta) Q(t)$ 를 $t=\alpha$ 에서 $n-1$ 번 미분하여 아래 식을 구하라.

$$
f(\beta) = \sum_{k=0}^{n-1}\dfrac{f^{(k)}(\beta)}{k!} + \dfrac{Q^{(n-1)}(\alpha)}{(n-1)!}(\beta-\alpha)^n.
$$



@thm-part2_tayler_theorem 의 

:::

</div>

</br>

::: {.solution}

$f(t) - f(\beta) = (t-\beta) Q(t)$ 를 $n-1$ 번 미분하면 

$$
f^{(n-1)}(t) = (n-1)Q^{(n-2)} + (t-\beta) Q^{(n-1)}(t)
$$

를 얻는다. 

:::

