---
title: "함수열"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

::: {.callout-warning icon="false"}

#### 함수열의 정의역에 대해 
아무리 찾아봐도 Rudin 에 명시적으로 지정되지 않았지만 함수열에서 다루는 함수의 정의역은 좌표공간, 혹은 유클리드 공간으로 한정되어 있다. 예를 들어 고른수렴에 대한 코시 판별법(@thm-MA_cauchy_criteria_for_uniform_convergence) 의 경우 코시 수열이 수렴하는 것이 필요한데 일반적인 거리공간에서는 코시수열이 수렴하지 않는다. 따라서 특별한 언급이 없다면 함수열의 정의역은 좌표공간의 부분집합이다.

:::

</br>

## 함수열과 고른 수렴
### 함수열 {#sec-MA_sequence_of_functions}

::: {.callout-note icon="false"}

#### **함수열의 수렴**

::: {#def-MA_convergence_of_sequences_of_functions}

$f_n:E \to \C,\, n=1,\,2,\ldots$ 로 이루어진 수열 $\langle f_n \rangle$ 을 **함수열 (sequence of functions)** 라고 한다. 각각의 $x\in E$ 에 대해 $\langle f_n(x)\rangle$ 이 수렴할 때 함수 $f:E \to \C$ 를 다음과 같이 정의 할 수 있다.

$$
f(x) = \lim_{n \to \infty} f_n(x)
$$

이 때 함수열 $\langle f_n \rangle$ 이 정의역 $E$ 에서 함수 $f$ 로 **수렴한다**, 혹은 **점별 수렴한다(pointwisely converge)** 고 한다. 각각의 $f_n$ 이 $E$ 에서 연속함수일 때 $\langle f_n \rangle$ 을 **연속함수열** 이라고 한다.

비슷한 방법으로 함수열 $\langle f_n \rangle$ 의 급수 $\sum f_n$ 이 $F$ 로 수렴할 때 $F$ 를 $\langle \sum f_n\rangle$ 의 **합(sum)** 이라고 한다.


::: 
:::

</br>

함수열을 다루는 목적은 개별 $f_n$ 의 성질이 극한함수 $f$ 에서 보존되는지 여부이다. 예를 들어 연속함수열 $\langle f_n\rangle$ 이 $f$ 로 수렴할 때 $f$ 는 연속함수임을 보장하는가? 더 나아기 $f_n$ 각각이 미분 혹은 적분 가능일 때 그 수렴함수 $f$ 는 그 미분 혹은 적분가능성이 보장되는가? 각각의 $f_n$ 의 도함수 $f_n'$ 에 대해 $f_n'$ 은 $f'$ 으로 수렴하는가? 등의 문제가 있을 수 있다. 

연속함수열에서 극한의 순서를 바꾸어도 그 값이 유지되는가 하는 문제도 있다. 즉

$$
\lim_{x \to x_0} \lim_{n \to \infty} f_n(x) = \lim_{n \to \infty} \lim_{x \to x_0} f_n(x)
$$ 

가 항상 보장되는가 하는 문제이다. 

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_double_sequence}

$m,\,n\in \Z_+$ 에 대해 이중 수열 $s_{m,n}$ 을 다음과 같이 정의하자.

$$
s_{m,n} = \dfrac{m}{m+n}
$$

여기서

$$
\lim_{m \to \infty} \lim_{n \to \infty}s_{m,n} =0,\qquad \lim_{n \to \infty}\lim_{m \to \infty} s_{m,n} = 1
$$

임을 안다. 즉 이중수열의 수렴은 그 인덱스 변수의 순서에 따라 달라 질 수 있다.

:::

</div></br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_non_converging_continuous_sequence}

$\R$ 에서 정의된 실함수열 $\displaystyle f_n (x) = \dfrac{x^2}{(1+x^2)^n},\;(n=0,\,1,\ldots)$ 을 생각하자. 이 때

$$
f(x) = \sum_{n=0}^\infty f_n(x) = \sum_{n=0}^\infty \dfrac{x^2}{(1+x^2)^n}
$$

라 놓자. 각각의 $n$ 에 대해 $f_n(0)=0$ 이므로 $f(0)=0$ 이며 $x\ne 0$ 에 대해 $f(x) = 1+x^2$ 이다. $f_n(x)$ 는 모두 $\R$ 전체에서 연속이지만 $f(x)$ 는 $x=0$ 에서 연속이 아니다.


:::

</div></br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_non_riemann_integrable_function_sequence}

$m\in \Z_+$ 에 대해 함수열 $\langle f_m\rangle$ 을 아래와 같이 정의한다.

$$
f_m(x) := \lim_{n \to \infty} \left(\cos m!\pi x\right)^{2n}.
$$

$m!x$ 가 정수일 때 $f_m(x) = 1$ 이며 다른 $x$ 에 대해 $f_m(x) = 0$ 이다. 이제 

$$
f(x) := \lim_{m \to \infty} f_m(x)
$$

라고 하자. $x\in \R-\Q$ 에 대해 $f(x) = 0$ 이다. $x\in \Q$ 에 대해 $x=p/q$ 일 때 $m\ge q$ 이면 $m!x \in \Z$ 이며 따라서 $f(x) =1$ 이다. 따라서

$$
\lim_{m \to \infty} \lim_{n \to \infty} \left(\cos m! \pi x\right)^{2n} = \left\{\begin{array}{ll} 0, \qquad &x\in \R-\Q,\\ 1,k&x\in \Q\end{array}\right.
$$

이다. 따라서 우리는 모든 곳에서 불연속인 함수를 얻었으며, 이 함수는 리만 적분 가능하지 않다(@exr-MA_rudin_6_4). 


:::

</div></br>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_non_convergent_derivative_of_function_sequence}

$n\in \Z_+$ 에 대해 $f_n :\R \to \R$ 이 아래와 같다고 하자.

$$
f_n(x) = \dfrac{\sin n x}{\sqrt{n}},\qquad f(x) = \lim_{n \to \infty} f_n(x) = 0.
$$

$f'(x) = 0$ 이고 $f'_n(x) = \sqrt{n}\cos n x$ 이므로 $\langle f'_n \rangle$ 은 $f'$ 으로 수렴하지 않는다. 

:::

</div></br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_double_sequence}

$n\in \Z_+$ 에 대해 $f_n : [0,\,1] \to \R$ 이 아래와 같다고 하자.

$$
f_n (x) = n^2 x(1-x^2)^n.
$$

$0<x\le 1$ 일 때 

$$
\lim_{n \to \infty} f_n(x) = 0
$$

이며 $f_n(0)=0$ 이므로 $x\in [0,\,1]$ 에 대해 

$$
\lim_{n \to \infty} f_n(x) = 0
$$

임을 안다. 여기서

$$
\int_0^1 x(1-x^2)^n\, dx = \dfrac{1}{2n+2}
$$

이므로

$$
\lim_{n \to \infty} \int_0^1 f_n (x)\,dx = \lim_{n \to \infty} \dfrac{n^2}{2n+1} \to +\infty
$$

이다. 

이제 $g_n:[0,\,1]\to \R$ 이 아래와 같다고 하자.

$$
g_n(x) = nx(1-x^2)^n.
$$

즉 $f_n(x)$ 의 $x^2$ 이 $x$ 로 바뀐 것 뿐이다. 여기서 $g(0)=0$ 이며 $x\in (0,\,1]$ 에 대해

$$
\lim_{n \to \infty} g_n(x) = 0,\, 
$$

이다. 즉 $f_n(x)$ 에 대해서와 마찬가지로

$$
\lim_{n \to \infty} g_n(x) = 0
$$

이다. 그러나

$$
\lim_{n \to \infty} \int_0^1 g_n(x) = \lim_{n \to \infty} \dfrac{n}{2n+1}= \dfrac{1}{2}
$$


이다. 즉 각각의 함수열에 대한 적분의 극한값은 극한값의 적분과 같지 않을 수 있다. 심지어 두 값이 모두 유한한 값일지라도 말이다. 

:::

</div></br>

</br>

### 함수열의 고른 수렴 {#sec-MA_uniform_convergence_of_sequences_of_functions}

::: {.callout-note icon="false"}

#### **고른 수렴**

::: {#def-MA_uniform_convergence}

$E$ 에서 정의된 함수열 $\langle f_n \rangle$ 이 $f$ 로 점별 수렴한다고 하자. 각각의 $\varepsilon > 0$ 에 대해 어떤 양의 정수 $N$ 이 존재하여 각각의 $x\in E$ 에 대해

$$
n \ge N \implies |f_n(x) - f(x)| \le \varepsilon
$$ {#eq-MA_uniform_convergence}

일 때 함수열 $\langle f_n\rangle$ 은 함수 $f$ 로 **고르게 수렴한다(congerge uniformly)** 라고 한다.

::: 
:::

</br>


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_cauchy_criteria_for_uniform_convergence}

#### 고른 연속에 대한 코시 판별법

$E$ 에서 정의된 함수열 $\langle f_n \rangle$ 이 $E$ 에서 고르게 수렴할 필요충분조건은 각각의 $\varepsilon >0$ 에 대해 어떤 $N\in \Z_+$ 가 존재하여

$$
m,\,n \ge N \implies |f_m(x) - f_n(x) | \le \varepsilon
$$ {#eq-MA_cauchy_criterial_for_uniform_convergence}

이니 것이다.

:::

</div>

::: {.proof}

$f_n$ 이 $f$ 로 고르게 수렴한다고 하자. 어떤 $N\in \Z_+$ 가 존재하여 $n\ge N$ 일 때 $|f_n(x) - f(x)|<\varepsilon/2$ 이다. $m>N$ 에 대해서도 마찬가지. 이 때

$$
|f_n(x) - f_m(x)| \le |f_n(x) - f(x)| + |f_m (x) - f(x) | \le \varepsilon
$$

이다. 역으로 임의의 정해진 $\varepsilon > 0$ 에 대해 어떤 $N\in \Z_+$ 에 대해 @eq-MA_cauchy_criterial_for_uniform_convergence 가 성립한다고 하자. 각각의 $x$ 에 대해 코시수열이며 따라서 수렴한다. 각각의 $x$ 에 대해 수렴하는 값을 모아 함수 $f(x)$ 를 구성 할 수 있다. @eq-MA_cauchy_criterial_for_uniform_convergence 로 부터 $n \to \infty$ 를 취하면

$$
|f_m(x) - f(x)| \le \varepsilon
$$

를 얻는다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_weierstrass_criteria_for_uniform_convergence_1}

$E$ 에서 정의된 함수열 $\langle f_n \rangle$ 이 $f$ 로 점별수렴한다고 하자. 

$$
M_n := \sup_{x\in E} |f_n(x) - f(x)|
$$

이라 할 때 $\langle f_n \rangle$ 이 $f$ 로 고르게 수렴할 필요충분조건은 $\displaystyle \lim_{n \to \infty} M_n = 0$ 인 것이다.

:::

</div>

::: {.proof}

@def-MA_uniform_convergence 에 의해 쉽게 보일 수 있다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_weierstrass_criteria_for_uniform_convergence_2}

#### 급수의 바이어슈트라스 판정법

$E$ 에서 정의된 함수열 $\langle f_n \rangle$ 과 양의 실수열 $\langle M_n \rangle$ 에 대해

$$
|f_n (x)|\le M_n
$$

이라고 하자. $\sum M_n$ 이 수렴하면 $\sum f_n$ 은 고르게 수렴한다.

:::

</div>

::: {.proof}

$\sum_n M_n$ 이 수렴한다고 하자. 그렇다면 임의의 $\varepsilon >0$ 에 대해 

$$
m>n>N \implies \sum_{i=n}^m M_n < \varepsilon
$$

인 $N\in \Z_+$ 이 존재한다. 
$$
\left|\sum_{i=n}^m f_n (x)\right| \le \sum_{i=n}^m M_n <\varepsilon
$$

이므로 $\sum_n f_n$ 은 고르게 수렴한다.

:::

</br>

## 함수열의 연속, 미분, 적분

### 함수열과 연속 {#sec-MA_funcion_sequence_and_continuity}

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_uniform_convergence_and_continuity}

$E$ 에서 정의된 함수열 $\langle f_n \rangle$ 이 $f$ 로 고르게 수렴한다고 하자. $x$ 가 $E$ 의 극한점이며 $a_n = \displaystyle \lim_{t \to x} f_n (t)$ 으로 정의된 수열 $\langle a_n \rangle$ 은 수렴하며 

$$
\lim_{t \to x} f(t) = \lim_{n \to \infty} a_n
$$ {#eq-thm-MA_uniform_convergence_and_continuity_1}

이다. 즉 

$$
\lim_{t \to x} \lim_{n \to \infty} f_n (t) = \lim_{n \to \infty} \lim_{t \to x} f_n(t)
$${#eq-thm-MA_uniform_convergence_and_continuity_2}

이다.

:::

</div>

::: {.proof}

$\varepsilon >0$ 을 정한다. $\langle f_n \rangle$ 이 $f$ 로 고르게 수렴하므로 코시 판별법에 따라 어떤 $N\in \Z_+$ 에 대해

$$
m,\, n \ge N \implies |f_m(t) - f_n (t) | \le \varepsilon
$$

이다. $t\to x$ 극한에서 $|a_m - a_n | <\varepsilon$ 이며 이는 $\langle a_n \rangle$ 이 코시 수열임을 말한다. 따라서 $\langle a_n \rangle$ 은 수렴한다.

이제 $\langle a_n \rangle \to a$ 라고 하자.

$$
|f(t)-a| \le |f(t) - f_n(t) | + |f_n(t) - a_n| + |a_n -a|
$$

이다. $\langle f_n \rangle$ 이 $f$ 로 균등수렴하므로 $n\ge N_1 \implies |f(t)-f_n(t)|\le \varepsilon/3$ 인 $N_1\in \Z_+$ 가 존재하고 $a_n$ 의 정의애 의해 $|t-x|<\delta \implies |f_n(t) - a_n|\le \varepsilon/3$ 인 $\delta >0$ 이 존재하며 $\langle a_n \langle \to a$ 이므로 $n\ge N_2 \implies |a_n-a|\le \varepsilon/3$ 인 $N_2\in \Z_+$ 가 존재한다. $N=\max \{N_1,\,N_2\}$ 라고 하면 $|t-x|<\delta,\, n\ge N$ 일 때

$$
|f(t)-a|\le \varepsilon
$$

이며 이는 @eq-thm-MA_uniform_convergence_and_continuity_1 가 성립함을 말한다. $\square$

:::

</br>

아래의 정리는 @prp-MA_uniform_convergence_and_continuity 의 직접적인 결론이다.
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_uniform_convergence_and_continuity}

$\langle f_n \rangle$ 이 $E$ 에서 정의된 연속 함수열이고 $f$ 로 고르게 수렴한다면 $f$ 는 $E$ 에서 연속함수이다.

:::

</div>

::: {.proof}

@prp-MA_uniform_convergence_and_continuity 의 용어를 그대로 사용하면 결국은 각각의 $x\in E$ 에 대해 $\displaystyle f(x) = \lim_{t\to x} \lim_{n \to \infty} f_n(t)$ 를 보이는 문제이다. 그런데 정의상 $f(x) = \lim_{n \to \infty} f_n(x)$ 이며 $f_n$ 은 연속함수이므로 $f_n (x) = \lim_{t \to \infty} f_n (t)$ 이므로 결국은 @eq-thm-MA_uniform_convergence_and_continuity_1 를 보이는 문제이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_uniform_convergence_and_continuity_and_compact_set}

옹골집합 $K$ 와 $K$ 에서 정의된 함수열 $\langle f_n\rangle$ 에 대해 

&emsp;($1$) 각각의 $f_n$ 이 $K$ 에서 연속이며,

&emsp;($2$) $\langle f_n \rangle$ 이 $f$ 로 점별 수렴하고,

&emsp;($3$) 모든 $x\in K,\, n\in \Z_+$ 에 대해 $f_n(x) \ge f_{n+1}(x)$ 이면

$\langle f_n \rangle$ 은 $f$ 로 고르게 수렴한다.

:::

</div>

::: {.proof}

함수열 $\langle g_n \rangle$ 을 $g_n := f_n-f$ 로 정의하자. 그렇다면 $g_n$ 은 연속이며 $\langle g_n \rangle$ 은 $0$ 으로 점별 수렴하며, $g_n \ge g_{n+1}$ 이다. 이제 우리는 $\langle g_n \rangle$ 이 $0$ 으로 고르게 수렴한다는 것을 보이면 된다.

정해진 $\varepsilon > 0$ 에 대해 $K_n := \{x\in K : g_n(x) \ge \varepsilon\}$ 이라고 하자. $K$ 가 옹골집합이므로 $K_n$ 은 닫힌 집합이며(@thm-MA_continuity_and_inverse_of_map) 따라서 옹골집합이다(@prp-MA_closed_subset_of_compact_set_is_compact). $g_{n} \ge g_{n+1}$ 이므로 $K_n \supset K_{n+1}$ 이다.

$x\in K$ 를 선택한다. $\langle g_n \rangle \to 0$ 이므로 $x\notin \bigcap_n K_n$ 이며, 따라서 $\bigcap_n K_n = \varnothing$ 이다. @prp-MA_finite_intesection_of_compact_sets 에 따라 어떤 $K_N=\varnothing$ 이며 $n \ge N$ 일 때 모든 $x\in K$ 에서 $0\le g_n(x)< \varepsilon$ 이다. 즉 $\langle g_n \rangle$ 은 $0$ 으로 고르게 수렴하며 따라서 $\langle f_n\rangle$ 은 $f$ 로 고르게 수렴한다. $\square$

:::


</br>

위의 정리 에서 옹골집합이라는 조건이 없을 경우 어떻게 되는지 예를 들어보자

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_non_compact_set_and_uniform_convergence}

#### 옹골집합이 아닌 집합에서 정의된 점별수렴하는 함수열

옹골집합이 아닌 집합 $(0,\,1)$ 에서 정의된 함수열 $\langle f_n \rangle$ 이 $f_n (x) := \dfrac{1}{nx+1}$ 이라고 하자. $\langle f_n\rangle$ 은 $0$ 으로 점별 수렴하며 @thm-MA_uniform_convergence_and_continuity_and_compact_set 의 세 조건을 모두 만족한다. $\varepsilon > 0$ 을 정하자. 아무리 큰 $n$ 이라도 $nx+1 > 1/\varepsilon$ 이 되도록 $x$ 값을 정할 수 있으며, 따라서 $\langle f_n \rangle$ 은 $0$ 으로 고르게 수렴하지 않는다.

:::

</div></br>

### 완비 거리 공간 {#sec-MA_complete_metric_space}

::: {.callout-note icon="false"}

#### **유계 연속 복소함수공간**

::: {#def-MA_complex_function_space}



거리공간 $X$ 에서 정의된 연속이며 유계인 복소함수들의 집합을 $\mathscr{C}(X)$ 라고 하자. $\mathscr{C}(X)$ 는 벡터공간을 이루며 아래와 같은 **상한 노름(supremum norm)** 을 정의하면 거리공간이 된다.(@prp-MA_trivials_in_supremum_norm_space)

$$
\|f\| := \sup_{x\in X} |f(x)|.
$$ {#eq-MA_supremum_norm}

::: 
:::

</br>

아래는 쉽게 보일 수 있으며 따라서 $\mathscr{X}$ 는 거리공간이다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_trivials_in_supremum_norm_space}

$f,\, g\in \mathcal{C}(X)$ 일 때 다음이 성립한다. 

&emsp;($1$) $\|f\|=0 \iff \forall x\in X,\, f(x) = 0$,

&emsp;($2$) $\|f+g\| \le \|f\|+\|g\|$, 

:::

</div></br>

@thm-MA_weierstrass_criteria_for_uniform_convergence_1 는 이제 다음과 같이 쓸 수 있다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_weierstrass_criteria_for_uniform_convergence_3}

함수열 $\langle f_n \rangle$ 이 $\mathscr{C}(X)$ 의 거리함수에 대해 $f$ 로 수렴할 필요충분조건은 $\langle f_n \rangle$ 이 $f$ 로 고르게 수렴하는 것이다.

:::

</div>

</br>

완비 거리공간(@def-MA_complete_metic_space) 은 코시수열이 수렴하는 거리공간이다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_complete_metric_space}

상한노름이 부여된 $X$ 에서의 유계연속복소함수공간 $\mathcal{C}(X)$ 는 완비 거리 공간이다.
:::

</div>

::: {.proof}

$\langle f_n \rangle$ 을 $\mathcal{C}(X)$ 에서의 코시수열이라고 하자. 즉 임의의 $\varepsilon >0$ 에 대해 어떤 $N\in \Z_+$ 가 존재하여

$$
n,\,m\ge N \implies \|f_n - f_m\| <\varepsilon
$$

이다. @thm-MA_cauchy_criteria_for_uniform_convergence 에서 보았듯이 $\langle f_n \rangle$ 은 어떤 함수 $f$ 로 고르게 수렴하며 @thm-MA_uniform_convergence_and_continuity 에서 보았듯이 $f$ 는 연속함수이다. $f_n$ 이 유계이며 모든 $x\in X$ 에 대해 $n \ge N \implies |f_n(x)-f(x)|<1$ 이 되는 $N\in\Z_+$ 을 잡을 수 있으므로 $f$ 도 유계이다. 즉 $f\in \mathscr{C}(X)$ 이므로 $\mathscr{C}(X)$ 는 완비거리공간이다.

:::

</br>

### 함수열과 적분 {#sec-MA_function_sequence_and_integration}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_function_sequence_and_integration}

$\alpha$ 가 $[a,\,b]$ 에서 단조증가함수이며 함수열 $\langle f_n \rangle$ 이 각각의 $n=1,\ldots$ 에 대해 $f_n \in \mathcal{R}(\alpha)[a,\,b]$ 이고 $f$ 로 고르게 수렴한다고 하자. 그렇다면 $f\in \mathcal{R}(\alpha)[a,\,b]$ 이며 그 값은 다음과 같다.

$$
\int_a^b f\,d\alpha = \lim_{n \to \infty} \int_a^b f_n\, d\alpha.
$$ {#eq-MA_integration_of_sequence_of_function}

:::

</div>

::: {.proof}

$\varepsilon_n := \sup \{|f_n(x)- f(x)|: x\in [a,\,b]\}$ 라고 하자. 그렇다면 

$$
f_n - \varepsilon_n \le f \le f_n + \varepsilon_n
$$

이며 

$$
\int_a^b (f_n - \varepsilon_n)\,d\alpha \le \underline{\int_a^b} f\,d\alpha \le \overline{\int_a^b}f\,d\alpha \le \int_a^b (f_n + \varepsilon_n)\,d\alpha
$$

이므로

$$
0 \le \overline{\int_a^b}f\,d\alpha -  \underline{\int_a^b} f\,d\alpha \le 2\varepsilon_n [\alpha(b)-\alpha(a)]
$$

이다. $N \to \infty$ 에서 $\varepsilon_n \to 0$ 이므로 상적분과 하적분의 값이 같아진다. 즉 $f\in \mathcal{R}(\alpha)[a,\,b]$ 이다. $\square$

:::

</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-MA_function_series_and_integration}

$f_n \in \mathcal{R}(\alpha)[a,\,b]$ 이고 $f(x) = \sum_{n=1}^\infty f_n(x)$ 가 $[a,\,b]$ 에서 고르게 수렴한다면 그 적분값은 다음과 같다.

$$
\int_a^b f\,d\alpha = \sum_{n=1}^\infty \int_a^b f_n\,d\alpha.
$${#eq-MA_integration_of_series_of_function}

:::

</div></br>

### 함수열과 미분 {#sec-MA_function_sequence_and_derivative}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_function_sequence_and_derivative}

함수열 $\langle f_n \rangle$ 이 $[a,\,b]$ 에서 미분가능하며 어떤 $x_0\in (a,\,b)$ 에 대해 $\langle f(x_0)\rangle$ 가 수렴한다고 하자. $\langle f'_n\rangle$ 이 $[a,\,b]$ 에서 고르게 수렴하면 $\langle f_n \rangle$ 이 $[a,\,b]$ 에서 어떤 미분가능 함수 $f$ 로 고르게 수렴하며 다음이 성립한다.

$$
f'(x) = \lim_{n \to \infty} f_n'(x).
$${#eq-MA_derivative_of_sequence_of_function}

:::

</div>

::: {.proof}

$\varepsilon > 0$ 을 정하자. $\langle f_n(x_0)\rangle$ 이 수렴하므로 $x_0$ 에 대해 $N_1\in \Z_+$ 을 다음을 만족하도록 정할 수 있다.

$$
m,\,n \ge N_1 \implies |f_n(x_0) - f_m(x_0)|<\dfrac{\varepsilon}{2}. 
$$ {#eq-thm-MA_function_sequence_and_derivative_1}

또한 $\langle f'_n \rangle$ 이 고르게 수렴하므로 모든 $t\in [a,\,b]$ 에 대해 $N_2\in \Z_+2$ 을 다음을 만족하도록 정한다.

$$
m,\,n \ge N_2 \implies \left|f'_n(t) - f'_m(t)\right| < \dfrac{\varepsilon}{2(b-a)}. 
$$ {#eq-thm-MA_function_sequence_and_derivative_2}

이제 $N=\max \{N_1,\,N_2\}$ 라고 하면 @eq-thm-MA_function_sequence_and_derivative_1 과 @eq-thm-MA_function_sequence_and_derivative_1 가 $N$ 에 대해 동시에 성립한다. $g=f_n-f_m$ 이라고 하면 평균값 정리(@thm-MA_mean_value_theorem) 에 따라 아래를 만족하는 $s\in (a,\,b)$ 가 존재한다.

$$
|g(x)-g(y)| = |g'(s)||x-y|
$$

@eq-thm-MA_function_sequence_and_derivative_2 에 따라 임의의 $x,\,y\in [a,\,b],\, m,\,n > N$ 에 대해 

$$
|f_n(x) - f_m(x) - f_n(y) + f_m(y)| = |g(x)-g(y)|< \dfrac{\varepsilon |x-y|}{2(b-a)} \le \dfrac{\varepsilon}{2}
$$ {#eq-thm-MA_function_sequence_and_derivative_3}

이다. @eq-thm-MA_function_sequence_and_derivative_1 과 @eq-thm-MA_function_sequence_and_derivative_3 을 이용하여 
$$
|f_n(x)-f_m(x) | \le |f_n(x)-f_m(x) - f_n(x_0) + f_m(x_0)| + |f_n(x_0) -f_m(x_0)| < \varepsilon
$$

임을 안다. 즉 $\langle f_n \rangle$ 은 $f$ 로 고르게 수렴한다. 이제 

$$
f(x) := \lim_{n \to \infty} f_n(x)
$$

라고 하자. 고정된 $x\in [a,\,b]$ 에 대해 $\phi_n,\, \phi_t$ 를 $[a,\,b]-\{x\}$ 에서 아래와 같이 정의한다.

$$
\phi_n(t) = \dfrac{f_n(t) - f_n(x)}{t-x},\qquad \phi(t) = \dfrac{f(t) - f(x)}{t-x}.
$$

그렇다면 $\displaystyle \lim_{t \to x} \phi_n(t) = f'_n(t)$ 이며 @eq-thm-MA_function_sequence_and_derivative_3 로부터 $n,\,m \ge N$ 일 때

$$
|\phi_n(t) - \phi_m(t) | \le \dfrac{\varepsilon}{2(b-a)}
$$

임을 안다. 즉 $\langle \phi_n\rangle$ 은 $t\ne x$ 에서 고르게 수렴한다. $\langle f_n \rangle$ 이 $f$ 로 수렴하므로 $\langle \phi_n\rangle$ 은 $t\ne x$ 에서 $\phi$ 로 고르게 수렴한다. @prp-MA_uniform_convergence_and_continuity 에 의해 $\lim_{t \to x} \phi (t) = \lim_{n \to \infty} f'_n(x)$ 이므로 @eq-MA_derivative_of_sequence_of_function 이 성립한다. $\square$

:::

</br>

@thm-MA_function_sequence_and_derivative 에서 에 만약 $f'_n$ 이 연속이라는 조건이 붙는다면 $f'_n \in \mathcal{R}[a,\,b]$ 이며 임의의 $x\in [a,\,b]$ 에 대해

$$
\int_a^x f'\, d\alpha = \lim_{n \to \infty} \int_a^x f'_n\,d\alpha
$$

이 성립하므로 $f(x) = \lim_{n \to \infty} f_
