---
title: "그림 1"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

```{r, engine = 'tikz'}
#| label: fig-continuity_of_inverse
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 6
#| fig-align: center
#| fig-cap: "양자 상태"


\begin{tikzpicture}[scale=1]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw[thick, -{Stealth[length=2mm]}] (-0.5, 0) -- (3, 0) node [right] {$x$} ;
\draw[thick, -{Stealth[length=2mm]}] (0, -0.5) -- (0, 3) node [above] {$f(x)$};

\filldraw[black] (0, 0) circle (2pt);
\draw[black, very thick] (1, 0) -- (3, 2);
\fill[draw=black, fill = white] (1, 0) circle (2pt);

\begin{scope}[shift={(5,0)}]
\draw[thick, -{Stealth[length=2mm]}] (-0.5, 0) -- (3, 0) node [right] {$x$} ;
\draw[thick, -{Stealth[length=2mm]}] (0, -0.5) -- (0, 3) node [above] {$f^{-1}(x)$};

\filldraw[black] (0, 0) circle (2pt);
\draw[black, very thick] (0, 1) -- (2, 3);
\fill[draw=black, fill = white] (0, 1) circle (2pt);

\end{scope}
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-part2_continuity_and_differentiability
#| code-fold: true
#| output: asis
#| fig-width: 8
#| fig-align: center
#| fig-cap: "연속과 미분 가능"


\begin{tikzpicture}[scale=6.0]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw[, -{Stealth[length=2mm]}] (-0.5, 0) -- (1, 0) node[right] {$x$} ;
\draw[, -{Stealth[length=2mm]}] (0, -0.5) -- (0, 0.5) ;


\draw[teal, thick] plot[variable=\t, domain=0.011:0.08, samples=600, thick] ({10*\t}, {60*\t*\t* sin(180/3.141592/\t)});
\draw[red, thick] plot[variable=\t, domain=0:0.08, samples=600, thick] ({10*\t}, {60*\t*\t});
\draw[red, thick] plot[variable=\t, domain=0:0.08, samples=600, thick] ({10*\t}, {-60*\t*\t});
\end{tikzpicture}
```


```{r, engine = 'tikz'}
#| label: fig-part2_fixed_point
#| code-fold: true
#| output: asis
#| fig-width: 6
#| fig-align: center
#| fig-cap: "연속과 미분 가능"


\begin{tikzpicture}[scale=2]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\coordinate (P1) at (3, 0.5);
\coordinate (P2) at (0.5, 0.5);
\draw[thick, -{Stealth[length=2mm]}] (-1, 0) -- (4, 0) node[right] {$x$} ;
\draw[thick, -{Stealth[length=2mm]}] (0, -1) -- (0, 4) node[above] {$y$};

\draw[thick, teal] (-0.5, -0.5) -- (3.5, 3.5) node [above] {$y=x$};
\draw[thick, red] (-0.5, 2.25) -- (3.5, 0.25);

\node[above right] at (P1) {$(x_1,\,x_1)$} ;
\draw[blue] (P1) -- (P2);

\draw[teal, thick] plot[variable=\t, domain=0.011:0.08, samples=600, thick] ({\t}, {\t})  ;
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-part3_integrability
#| code-fold: true
#| output: asis
#| fig-width: 6
#| fig-align: center
#| fig-cap: "적분가능"


\begin{tikzpicture}[scale=2]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}


\filldraw [fill=yellow,opacity=0.7] (1.9,1.5) rectangle (4.0,2.8);
\filldraw [fill=yellow,opacity=0.7] (1.9,2.8) rectangle (4.6,3.4);
\filldraw [fill=yellow,opacity=0.7] (3.0,3.4) rectangle (4.6,4.6);
\draw[thick] (0, 0) -- (5, 0);
\draw[thick] (0, 1.5) -- (5, 1.5);
\draw[thick] (0, 2.8) -- (5, 2.8);
\draw[thick] (0, 3.4) -- (5, 3.4);
\draw[thick] (0, 4.6) -- (5, 4.6);
\draw[thick] (0, 5) -- (5, 5);
\draw[thick] (0, 0) -- (0, 5);
\draw[thick] (1.9, 0) -- (1.9, 5);
\draw[thick] (3.0, 0) -- (3.0, 5);
\draw[thick] (4.0, 0) -- (4.0, 5);
\draw[thick] (4.6, 0) -- (4.6, 5);
\draw[thick] (5, 0) -- (5, 5);
\draw [very thick, teal,] plot [smooth, tension=1] coordinates { (2.5, 2.1) (3.0, 2.6) (3.8,3.7) (4.3,4.0)};
\node[above,yshift=0.1cm] at(2.5, 2.1) {$B_\varepsilon$};
\node[] at (3.5, 2.0) {$U_2$};
\node[] at (3.6, 4.0) {$U_1$};
\end{tikzpicture}
```