---
title: "테일러 전개"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---


{{< include ../../latexmacros.qmd >}}

## 코시의 평균값 정리

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_mean_value_theorem}  

($1$) 평균값 정리를 이용하여 미분계수가 항등적으로 $0$ 인 함수는 상수함수임을 증명하라.

($2$) 미분가능한 함수 $f:[a,\,b]\to \mathbb{R}$ 에 대하여 점 $(a,\,f(a))$ 와 점 $(b,\,f(b))$ 를 지나는 직선의 방정식을 $y=l(x)$ 라 하자. 이 때 $|l(x)-f(x)|$ 가 최대가 되는 점 $c$ 에서 $f'(c)=\dfrac{f(b)-f(a)}{b-a}$ 임을 보이라. 만약 $f$ 가 이차함수이면 $c=\dfrac{a+b}{2}$ 임을 보이라.

($3$) 미분가능한 함수 $f:\mathbb{R}\to \mathbb{R}$ 이 $f(0)=1$ 이고, 임의의 $x$ 에 대하여 $f'(x)\le 0.2$ 이면 $f(5)\le 2$ 임을 보이라.

($4$) 현재 어떤 집값이 1억원이고, 앞으로 순간 물가 증가율이 $0.2$ (억원/년) 을 넘지 않는다면 5년 후에 이 집값은 2억원을 넘지 않음을 보이라.

:::

</div>

::: {.solution}

($1$) 임의의 구간 $(a,\,b)$ 에 대해서 $f(b)\ne f(a)$ 라면 $0 \ne \dfrac{f(b)-f(a)}{b-a}=f'(c)$ 인 $c\in (a,\,b)$ 가 존재해야 한다. 이는 미분계수가 항등적으로 $0$ 이라는 가정에 위배된다. 따라서 $f$ 는 상수함수이다.

($2$) $l(x) = \dfrac{f(b)-f(a)}{b-a} (x-a)+f(a)$ 이다. $s(x)=|l(x)-f(x)|^2$ 라 하자.  $f$ 가 상수함수이면 자명하므로 $f$ 가 상수함수가 아닐 경우만 생각하자. $s(a)=s(b)=0$ 이며 $s(x)\ge 0$ 이므로,  $s (x)$ 가 최대가 되는 $c$ 에서 $s'(x)=0 \implies l(c)=f(c)$ or $l'(x)=f'(x)$ 이다. $l(c)=f(c)$ 이면 $s(c)=0$ 이므로 최대값이 아니다. $f'(c)=l'(c) = \dfrac{f(b)-f(a)}{b-a}$ 일 때 이다.

($3$) $f(x)-f(0)=f'(c) (x-0) \le 0.2 x$ 이므로 $f(5)\le 2$ 이다.

($4$) ($3$) 에 의해 자명.

:::


</br>

## 연습문제 : 제 3장 2절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_2_1}  

다음 극한을 구하라.

:::

</div>

::: {.solution}

($1$)  $ \displaystyle \lim_{x \to 0}\dfrac{1-\cos x}{x^2}=\lim_{x \to 0}\dfrac{\sin x}{2x} = \lim_{x \to 0}\dfrac{\cos x}{2}=\dfrac{1}{2}$

($2$) $\displaystyle \lim_{x \to 0}\dfrac{e^x-1-x}{x^2}=\lim_{x \to 0}\dfrac{e^x-1}{2x}=\lim_{x\to 0}\dfrac{e^x}{2}=\dfrac{1}{2}$

($3$)  $\displaystyle \lim_{x\to 0} \dfrac{x-\tan x}{x-\sin x} = \lim_{x \to 0}\dfrac{1-\dfrac{1}{\cos^2 x}}{1-\cos x}= \lim_{x \to 0} \dfrac{-\dfrac{2 \sin x}{\cos^3 x}}{ \sin x}=-2$

($4$) $\displaystyle \lim_{x \to 0} \dfrac{e^x-e^{-x}}{\sin x}=\lim_{x \to 0}\dfrac{e^x+e^{-x}}{\cos x}=2$

($5$) $\displaystyle \lim_{x \to 0} \dfrac{e^x-1}{\ln (1+x)} = \lim_{x \to 0} e^x (1+x)=1$

($6$) $\displaystyle \lim_{x \to 0} (e^x+x)^{1/x}=\lim_{x \to 0} e^{\frac{1}{x}{\ln (e^x+x)}}=\lim_{x \to 0} \exp \left(\dfrac{e^x+1}{e^x+x}\right)=e^2$

($7$) 

$$
\begin{aligned}
\lim_{x \to 0} \left(\dfrac{1}{\sin x}-\dfrac{1}{x}\right) &= \lim_{x \to 0} \dfrac{x-\sin x}{x\sin x} \\[0.3em]
&= \lim_{x \to 0}\dfrac{1-\cos x}{\sin x +x\cos x} \\[0.3em]
&= \lim_{x \to 0}\dfrac{\sin x}{\cos x -x\sin x+\cos x}=0
\end{aligned}
$$

($8$) 

$$
\begin{aligned}
\lim_{x \to 0} \dfrac{\tan x-\sin x}{x^3} &= \lim_{x \to 0}\dfrac{\sin x - \sin x \cos x}{x^3 \cos x} \\[0.3em] 
&= \lim_{x\to 0}\dfrac{\cos x-\cos^2 x+ \sin ^2 x}{3x^2 \cos x - x^3 \sin x}\\[0.3em]
&= \cdots =\lim_{x \to 0} \dfrac{-\sin x + 4 \sin x \cos x}{6 \cos x + x(\cdots)}=\dfrac{1}{2}
\end{aligned}
$$

($9$) 

$$
\begin{aligned} 
\lim_{x \searrow 0} \sin x \ln x &= \lim_{x \searrow 0 } \dfrac{\ln x}{1/\sin x} = \lim_{x \searrow 0}\dfrac{1/x}{\cos x/\sin^2 x} \\[0.3em]
&= \lim_{x \searrow 0}\dfrac{\sin ^2 x}{x\cos x}= \lim_{x \searrow 0 }\dfrac{2\sin x \cos x}{\cos x+x\sin x}=0
\end{aligned}
$$


($10$) $\displaystyle \lim_{x \searrow 0} \sqrt{x}\ln x = \lim_{x \searrow 0}\dfrac{\ln x}{1/\sqrt{x}}=\lim_{x \searrow 0} \dfrac{1/x}{-1/2x^{3/2}} = \lim_{x \searrow 0}\left[-2\sqrt{x}\right]=0$

($11$)  $\displaystyle \lim_{x \searrow 0} x^a \ln x\;(a>0)= \lim_{x \searrow 0}\dfrac{\ln x}{x^{-a}}=\lim_{x \searrow 0} \dfrac{x^{-1}}{-ax^{-a-1}}=\lim_{x\searrow 0}\dfrac{1}{-a} x^a=0$

($12$) $\displaystyle \lim_{x \searrow 0} x^x = \lim_{x \searrow 0} e^{x \ln x} = \lim_{x \searrow 0} \exp \left(\dfrac{1/x}{-1/x^2}\right) = \lim_{x \searrow 0}e^{-x}=1$  

($13$) $\displaystyle \lim_{x \searrow 0} x^{\sin x}= \lim_{x \searrow 0 } \exp \left(\sin x \ln x\right)=1$ (see (9))

($14$) $\displaystyle \lim_{x \searrow 0} \dfrac{\sqrt{x}}{\sqrt{x} + \sin \sqrt{x}}= \lim_{x \searrow 0} =\dfrac{1/\sqrt{x}}{1/\sqrt{x} +1/\sqrt{x} \cos \sqrt{x}}=\dfrac{1}{2}$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_2_2}   

구간 $I$ 에서 두번 미분 가능한 함수 $f$ 에 대하여

$$
f''(x) = 2\lim_{h \to 0} \dfrac{f(x+h) -f(x) - f'(x)h}{h^2}\,,\qquad x\in I
$$

이 성립함을 보이라.

:::

</div>

::: {.solution}

$\lim_{h \to 0} \dfrac{f(x+h) -f(x) - f'(x)h}{h^2} =\lim_{h \to 0}\dfrac{f'(x+h)-f'(x)}{2h}=\dfrac{f''(x)}{2}$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_2_3}   

열린 구간 $I$ 에서 두 번 미분가능한 함수 $f(x)$ 를 생각하자. 이 때 $x=a\in I$ 가 $f(x)$ 의 임계점(critical point), 즉 $f'(a)=0$ 이라고 하자.

($1$) 만약 $f''(a)>0$ 이면 $x=a$ 는 $f(x)$ 의 극소점 임을 보여라.

($2$) 만약 $f''(a)<0$ 이면 $x=a$ 는 $f(x)$ 의 극대점 임을 보여라.

:::

</div>

::: {.solution}

($1$) $f''(a)>0$ 이면 $a$ 를 포함하는 어떤 열린 구간 $I_a$ 에 대해 $x\in I_a \implies f''(x)>0$ 임을 생각 할 수 있다. $x_1,\,x_2 \in I_a$ 이고 $x_1<x_2$ 이면 $f'(x_1) < f'(x_2)$ 이다. $x\in I_a$ 에 대해 $x>a$ 라 하자.  평균값정리에 의해 다음을 만족하는 $y\in (a,\,x)$ 가 존재한다.

$$
f(x)-f(a)=(x-a)f'(y)
$$

여기서 $f'(y)-f'(a)=f'(y)=(y-a)f''(z)$ 를 만족하는 $z\in (a,\,y)$ 가 존재하므로 $f'(y) = (y-a)f''(z)>0$ 이며 $(x-a)>0$ 이므로 이 구간 $I_a$  에서의 임의의 $x>a$ 에 대해 $f(x)-f(a)>0$ 이다.

$x<a$ 일 경우도 마찬가지로 $f(x)-f(a)>0$ 임을 보일 수 있다. 따라서 $x=a$ 는 $f(x)$ 의 극소점이다.

($2$) ($1$) 의 방법대로 하면 쉽게 보일 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_2_4}   

#### 로피탈의 정리

구간 $(a,\,\infty)$ 에서 정의된 두 미분가능한 함수 $f,\,g$ 에 대하여 극한값 $l:=\displaystyle \lim_{x \to \infty} \dfrac{f'(x)}{g'(x)}$ 이 존재한다고 하자. 이제

($i$) $\displaystyle \lim_{x \to \infty} f(x) = \lim_{x \to \infty} g(x) =0$

이거나, 또는

($ii$) $\displaystyle \lim_{x \to \infty} f(x) = \lim_{x \to \infty} g(x) = \infty$

이면,

$$
\lim_{x \to \infty} \dfrac{f(x)}{g(x)}= \lim_{x \to \infty} \dfrac{f'(x)}{g'(x)}
$$

임을 보이라.

:::

</div>

::: {.solution}

$y=1/x$ 라 놓으면 $\displaystyle \lim_{x \to \infty}f(x)=\lim_{y \searrow 0}f(1/y)$ 임을 안다.

$$
\lim_{x \to \infty} \dfrac{f(x)}{g(x)}= \lim_{y\searrow 0} \dfrac{f(1/y)}{g(1/y)} = \lim_{y\searrow 0} \dfrac{(-1/y^2)f'(1/y)}{(-1/y^2)g'(1/y)}=\lim_{y \searrow 0} \dfrac{f'(1/y)}{g'(1/y)}=l
$$
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_2_5}

로피탈의 정리를 이용하여 $\displaystyle \lim_{n \to \infty} n^{1/n}=1$ 임을 보이라.

:::

</div>

::: {.solution}
$\displaystyle \lim_{n \to \infty} n ^{1/n}=\lim_{n \to \infty} e^{\frac{1}{n} \ln n}=\lim_{n \to \infty}e^{1/n}=1$
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_2_6} 

로피탈의 정리를 이용하여 다음을 보이라.

$$
\lim_{x \to \infty} \dfrac{x}{e^x}=0\,,\qquad \lim_{x \to \infty}\dfrac{x^2}{e^x}=0\;.
$$

일반적으로 임의의 다항식 $p(x)$ 에 대하여

$$
\lim_{x \to \infty} \dfrac{p(x)}{e^x}=0
$$

임을 보이라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
\lim_{x \to \infty} \dfrac{x}{e^x} = \lim_{x \to \infty} \dfrac{1}{e^x}=0\,,\\
\lim_{x \to \infty} \dfrac{x^2}{e^x} = \lim_{x \to \infty}\dfrac{2x}{e^x }=0\,.
\end{aligned}
$$

$p(x)$ 가 $n$ 차 다항식일 때 분자 분모를 각각 $n+1$ 번 미분하면 $\lim_{x \to \infty} \dfrac{0}{e^x}$ 꼴이 되므로 그 극한이 $0$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_2_7} 

다음을 보이라.

$$
\lim_{x \to \infty} \dfrac{\ln x}{x}=0,\qquad \lim_{x \to\infty}\dfrac{\ln x}{\sqrt{x}}=0\;.
$$

일반적으로 임의의 자연수 $n$ 에 대하여 $\displaystyle \lim_{x \to \infty} \dfrac{\ln x}{\sqrt[n]{x}} =0$ 임을 보이라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
\lim_{x \to \infty}\dfrac{\ln x}{x} &= \lim_{x \to \infty}\dfrac{1/x}{1}=0\;.\\
\lim_{x \to \infty}\dfrac{\ln x}{\sqrt{x}} &= \lim_{x \to \infty} \dfrac{1/x}{(1/2)x^{-1/2}}=\lim_{x \to \infty}\dfrac{2}{\sqrt{x}}=0\;,\\
\lim_{x \to \infty}\dfrac{\ln x}{x^{1/n}} &= \lim_{x\to \infty}\dfrac{1/x}{(1/n)x^{(1/n-1)}} = \lim_{x \to \infty} \dfrac{n}{x^{1/n}}=0\;.
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_2_9} 

$0$ 이상인 임의의 실수 $a,\,b,\,c$ 에 대하여

($1$) $\displaystyle \lim_{n \to \infty} \left( \dfrac{a^{1/n}+b^{1/n}}2{}\right)^{n}=\sqrt{ab}$

($2$) $\displaystyle \lim_{n\to \infty} \left(\dfrac{a^{1/n}+b^{1/n}+c^{1/n}}{3}\right)^n = \sqrt[3]{abc}$

이 성립함을 보이라.

:::

</div>

::: {.solution}

($1$) 좌변에 log를 취하면, 

$$
\displaystyle \ln \left[\left(\dfrac{a^{1/n}+b^{1/n}}{2}\right)^n\right] =n  \ln\left(\dfrac{a^{1/n}+b^{1/n}}{2}\right)= \dfrac{\ln(a^{1/n}+b^{1/n})-\ln{2}}{1/n}
$$

이며,
$$
\lim_{n \to \infty}\dfrac{\ln(a^{1/n}+b^{1/n})-\ln{2}}{1/n}= \lim_{n \to \infty}  \dfrac{1/n^2 (\ln a+\ln b) \dfrac{1}{a^{1/n}+b^{1/n}}}{1/n^2} = \dfrac{\ln (ab)}{2}=\ln \sqrt{ab}
$$

($2$) 역시 좌변에 log 를 취하면 (1) 과 같은 방법으로 쉽게 구할 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_2_10} 

자연수 $n$ 에 대하여, 구간 $I$ 에서 정의된 $n$ 번 미분 가능한 함수 $f(x)$ 에 대하여
$$
\dfrac{f^{(n)}(x)}{n!}=\lim_{h \to 0}\dfrac{\displaystyle f(x+h)-\sum_{k=0}^{n-1}\dfrac{f^{(k)}(x)}{k!} h^k}{h^n}\,,\qquad \forall x \in I
$$

을 보이라.

:::

</div>

::: {.solution}

좌번의 $h \to 0$ 극한에서 분자와 분모가 모두 $0$ 으로 수렴한다. 분자 분모를 모두 $h$ 에 대하여 $n$ 번 미분하면, 분모의 $\displaystyle \sum_{k=0} ^{n-1}\cdots$ 은 $h$ 의 $n-1$ 차 다항식이므로 $n$ 번 미분에 사라진다. 따라서,  

$$
\lim_{h \to 0}\dfrac{\displaystyle f(x+h)-\sum_{k=0}^{n-1}\dfrac{f^{(k)}(x)}{k!} h^k}{h^n} = \lim_{h \to 0} \dfrac{f^{(n)}(x+h)}{n!} = \dfrac{f^{(n)}(x)}{n!}
$$

이다.

:::

</br>

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_2_11}

다음 극한을 구하라.

:::

</div>

::: {.solution}

($1$) $\displaystyle \lim_{n \to \infty} \dfrac{1}{\sqrt{n}} \left(1+\dfrac{1}{2}+ \cdots +\dfrac{1}{2n-1}+\dfrac{1}{2n}\right)$

우리는 $\dfrac{1}{2}+\dfrac{1}{3} + \cdots+ \dfrac{1}{n} <\ln n < 1+\dfrac{1}{2}+ \cdots + \dfrac{1}{n}$ 임을 알고 있다. 따라서 $\left(1+\dfrac{1}{2}+ \cdots +\dfrac{1}{2n-1}+\dfrac{1}{2n}\right) > \ln (2n+1)$ 이다.

$$
\begin{aligned}
0 &\le  \lim_{n \to \infty} \dfrac{1}{\sqrt{n}} \left(1+\dfrac{1}{2}+ \cdots +\dfrac{1}{2n-1}+\dfrac{1}{2n}\right) \le \lim _{n \to \infty}\dfrac{\ln (2n+1)}{\sqrt{n}} \\[0.3em]
&= \lim_{n \to \infty} \dfrac{2/(2n+1)}{\dfrac{1}{2\sqrt{n}} }=\lim_{n \to \infty} \dfrac{4\sqrt{n}}{2n+1}=0\;.
\end{aligned}
$$

이므로 극한값은 $0$ 이다.

($2$) $\displaystyle \lim_{n \to \infty} \dfrac{1}{n} \left(1+\dfrac{1}{2} + \cdots + \dfrac{1}{3n-1}+\dfrac{1}{3n}\right)^2$

역시 $\left(1+\dfrac{1}{2} + \cdots + \dfrac{1}{3n-1}+\dfrac{1}{3n}\right) > \ln (3n+1)$ 이므로,

$$
\begin{aligned}
\lim_{n \to \infty} \dfrac{1}{n} \left(1+\dfrac{1}{2} + \cdots + \dfrac{1}{3n-1}+\dfrac{1}{3n}\right)^2 &\le \lim_{n \to \infty}\dfrac{(\ln (3n+1))^2}{n} \\[0.3em]
&= \lim_{n \to \infty} \dfrac{6 \cdot \ln (3n+1)}{3n+1}=0
\end{aligned}
$$

($3$) $\displaystyle \lim_{n \to \infty} \dfrac{1}{n}\left(1+\dfrac{1}{2} + \cdots + \dfrac{1}{4n-1}+\dfrac{1}{4n}\right)^5$

역시 $\left(1+\dfrac{1}{2} + \cdots + \dfrac{1}{4n-1}+\dfrac{1}{4n}\right) > \ln (4n+1)$ 이므로,

$$
\begin{aligned}
\lim_{n \to \infty} \dfrac{1}{n} &\left(1+\dfrac{1}{2} + \cdots + \dfrac{1}{4n-1}+\dfrac{1}{4n}\right)^5   \\[0.3em]
&\le \lim_{n \to \infty}\dfrac{(\ln (4n+1))^5}{n}  \\
&= \lim_{n \to \infty} \dfrac{20 \cdot (\ln (4n+1))^4}{4n+1} \\
&=\lim_{n \to\infty} \dfrac{20 \cdot 4 \cdot 4 (\ln (4n+1))^3}{4(4n+1)}=\lim_{n\to \infty} \dfrac{80 (\ln (4n+1))^3}{4n+1} \\
&=\lim_{n \to\infty} \dfrac{80 \cdot 4 \cdot 3 (\ln (4n+1))^2}{4\cdot (4n+1)}= \lim_{n \to \infty} \dfrac{240 \cdot (\ln (4n+1))^2}{4n+1} \\
&= \lim_{n \to \infty} \dfrac{240 \cdot 4 \cdot 2 (\ln (4n+1))}{4\cdot(4n+1)} = \lim_{n \to \infty}\dfrac{ 480 \cdot \ln (4n+1)}{4n+1}=0\;.
\end{aligned}
$$

:::

</br>

## 연습문제 : 제 3 장 3 절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_3_1}

 원점 근방에서 정의된 함수 $f(x)$ 와 $g(x)$ 가 모두 $o(x^k)$ 이면 $f(x)+g(x)$ 도 $o(x^k)$ 임을 보이라. 또 임의의 실수 $c$ 에 대하여 $cf(x)$ 오 $o(x^k)$ 임을 보이라.

:::

</div>

::: {.solution}

$f^{(n)}(0)=g^{(n)}(0)=0$ for $n=0,\ldots,\,n$ 이므로 $(cf+g)^{(n)}(0)=0$ for any constant $c$.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_3_2} 

두 일차 다항삼수 $l_1(x)$ 와 $l_2(x)$ 의 차가 $o(x)$ 이면 $l_1(x)=l_2(x)$ 임을 보이라.

:::

</div>

::: {.solution}

let $l_1(x) = a_1 x +b_1,\, l_2(x) = a_2 x+b_2$. $l_1(x)-l_2 (x)=o(x)$ 이므로 $l_1 (0)=l_2 (0)\implies b_1=b_2$, ${l_1}'(0)={l_2}'(0)=0 \implies a_1=a_2$.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_3_3} 

두 $n$ 차 다항함수 $p_1(x)$ 와 $p_2(x)$ 의 차가 $o(x^n)$ 이면 $p_1(x)=p_2(x)$ 임을 보이라.

:::

</div>

::: {.solution}

Let $p_1 (x) =a_0 + a_1x + \cdots + a_n x^n$ and $p_2(x) =b_0+b_1 x+ \cdots + b_n x^n$. Then,
$$
p_1(x)-p_2(x) = (a_0-b_0)+(a_1-b_1)x +\cdots + (a_n-b_n)x^n= o(x^n)
$$

$(p_1-p_2)^{(k)}(0)=0 \implies a_k = b_k$ for $k=0,\ldots,\,n$ 따라서 $p_1=p_2$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_3_4}

다음 함수의 원점에서의 3차 근사 다항식을 구하라.

:::

</div>

::: {.solution}

($1$) $f(x) = e^x \sin x$

$$
\begin{aligned}
f(0)&=0\,,\\
f'(0) &=(e^x\sin x + e^x \cos x)(0)=1\,,\\
f''(x) &= (e^x \sin x + e^x \cos x + e^x  \cos x -e^x \sin x)(0)=(2e^x \cos x)(0)=2\,,\\
f^{(3)}(x) &= (2e^x \cos x - 2e^x\sin x )(0)=2\,,\\
f(x)&\approx 0+x+x^2 + \dfrac{1}{3} x^3
\end{aligned}
$$

($2$) $f(x) = x\ln (1+x)$

$$
\begin{aligned}
f(0)&=0\,,\\
f'(0) &= \left( \ln (1+x) + \dfrac{x}{1+x} \right) (0)=0\,,\\
f''(0) &=\left(\dfrac{2}{1+x}-\dfrac{x}{(1+x)^2}\right)(0)=2\,,\\
f^{(3)}(0) &= \left(\dfrac{-2}{(1+x)^2} -\dfrac{1}{(1+x)^2}+ \dfrac{2x}{(1+x)^3}\right)(0)=-3\;. \\
f(x) &\approx x^2-\dfrac{1}{2}x^3\;.
\end{aligned}
$$

($3$) $f(x) = e^{-x^2}$

$$
\begin{aligned}
f(0)&=1\,, \\
f'(0) &= \left(-2xe^{-x^2}\right)(0)=0\,,\\
f''(0) &=\left(-2e^{-x^2} +4x^2e^{-x^2}\right)(0)=-2\,,\\
f^{(3)}(0) &= \left(4xe^{-x^2} + 8xe^{-x^2} -8x^3e^{-x^2}\right)(0)=0\,.\\
f(x) &\approx 1-x^2
\end{aligned}
$$

($4$) $f(x) = \sin \exp(x)$

$$
\begin{aligned}
f(0)&=\sin 1\,,\\
f'(0) & = (e^x \cos e^x)(0)=\cos 1\,,\\
f''(0)&= (e^x \cos e^x -e^{2x } \sin e^x)(0)=\cos 1-\sin 1\\
f'''(0) &=(e^x \cos e^x -e^x \sin e^x-2e^{2x}\sin e^x-e^{3x}\cos e^x)(0)=\cos 1-\sin 1-\sin 1 -\cos 1=-2\sin 1\,,\\
f(x)&\approx (\sin 1)+ (\cos 1) x + \dfrac{\cos 1-\sin 1}{2}x^2 -\dfrac{2\sin 1}{6} x^3\;
\end{aligned}
$$

($5$) $f(x) = x-\cos x$
$$
\begin{aligned}
f(0)&=-1\,,\\
f'(0)&=(1+\sin x)(0)=1\,,\\
f''(0) &=(\cos x)(0)=1\,,\\
f^{(3)}(0) &=(-\sin x)(0)=0\,,\\
f(x)&\approx  -1+x+\dfrac{1}{2}x^2\,.
\end{aligned}
$$

($6$) $f(x)=2^x = e^{x \ln 2}$
$$
\begin{aligned}
f(0)&=1\,,\\
f'(0)& = (\ln 2 e^{x\ln 2})(0)=\ln 2\,,\\
f''(0) &= ((\ln 2)^2 e^{x\ln 2})(0)=(\ln 2)^2\,,\\
f^{(3)}(0) &= ((\ln 2)^3 e^{x \ln 2})(0)= (\ln 2)^3\,,\\
f(x)&\approx 1 + \ln 2 x + \dfrac{(\ln 2)^2}{2}x^2 + \dfrac{(\ln 2)^3}{3!}x^3\,.
\end{aligned}
$$

($7$) $f(x) = \sqrt{1+x}$

$$
\begin{aligned}
f(0)&=1\,,\\
f'(0)&= \left( \dfrac{1}{2\sqrt{1+x}}\right)(0)=\dfrac{1}{2}\,,\\
f''(0)&=\left(-\dfrac{1}{4} \dfrac{1}{(1+x)^{3/2}}\right)(0)=-\dfrac{1}{4}\,,\\
f^{(3)}(0)&=\left(\dfrac{3}{8} \dfrac{1}{(1+x)^{5/2}}\right)(0) =\dfrac{3}{8}\,,\\
f(x) &\approx 1+\dfrac{1}{2}x -\dfrac{1}{8}x^2 + \dfrac{1}{16}x^3\,.
\end{aligned}
$$

($8$) $f(x) = (1+x)^{-1}$

$$
\begin{aligned}
f(0)&=1\,,\\
f'(0) &= \left(-(1+x)^{-2}\right)(0)=-1\,,\\
f''(0) &=\left(2(x+1)^{-3}\right)(0)=2\,,\\
f^{(3)}(0) &= (-6(x+1)^{-4})(0)=-6\,,\\
f(x) &\approx 1-x+x^2 -x^3\,.
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_3_5} 

다음을 보이라.

:::

</div>

::: {.solution}

($1$) $\cosh x = \cos x + o(x)$

$f(x)=\cosh x - \cos x$ 라 놓으면 $f(0)=(\cosh x -\cos x)(0)=0$, $f'(0)= (\sinh x + \sin x)(0)=0$ 이므로 $f(x)=o(x)$ .

($2$) $\sinh x = \sin x +o(x^2)$

$f(x) = \sinh x - \sin x$ 라 놓으면 $f(0)=0$, $f'(x) = (\cosh x - \cos x)(0)=0$, $f''(x) = (\sin h x + \sin x)(0)=0$ 이므로 $f(x) = o(x^2)$ 이다.

($3$) $\tanh x = \arctan x + o(x^4)$

멱급수 전개를 보면,
$$
\begin{aligned}
\tanh x &=  x-\dfrac{1}{3}x^3 + O(x^4)\,,\\
\arctan x &= x-\dfrac{1}{3}x^3 +O(x^4)\,,\\
\tanh x-\arctan x &=O(x^4)
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_3_6} 

원점 근방에서 정의된 연속 함수 $f(x)$ 가 $o(x^n)$ 이면 적분함수 $\displaystyle F(x):= \int_0^x f(t)\, dt$ 는 $o(x^{n+1})$ 임을 보여라.

:::

</div>

::: {.solution}

$F'(x) = f(x),\, F^{(n)}(x)=f^{(n-1)}(x)$ 이므로 trivial 하다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_3_7} 

원점 근방에서 정의된 $n$ 번 미분가능 함수 $f(x)$ 가 $o(x^n)$ 이면 도함수 $f'(x)$ 는 $o(x^{n-1})$ 임을 보여라.

:::

</div>

::: {.solution}

trivial

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_3_8} 

정육면체의 모서리의 길이를 각각 1% 씩 증가시키면 부피는 3% 정도 증가함을 보여라.

:::

</div>

::: {.solution}

$f(x) =V(L+x)=(L+x)^3=L^3 +3L^2x +3Lx^2 +x^3$.   $x=\dfrac{1}{100}L$ 라 하면,

$$
\dfrac{f(x)-f(0)}{f(0)}=\dfrac{1}{L^3} \left(\dfrac{3}{100}L^3 +\dfrac{3L^3}{10,000}+ \dfrac{L^3}{1,000,000} \right) \approx 0.03
$$

나머지는 생략..

:::


</br>

## 연습문제 : 제 3장 4절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_4_1} 

지수함수 $\exp x$ 의 테일러 전개에서 $n$ 차 잉여항 $R_n (x)$ 가

$$
\left| R_n (x)\right| \le \dfrac{|x|^{n+1}}{(n+1)!} \max\{e^x,\,1\}
$$
임을 보이고, 이로부터 $e$ 의 값을 오차의 범위가 0.001 이하가 되도록 구하라.

::: 

</div>

::: {.solution}
$$
|R_n(x) | = |e^x-T_n(x)|=\left| \dfrac{e^y x^n}{(n+1)!} \right|
$$

여기서 $y$ 는 $0$ 과 $x$ 사이에서 $e^x-T_n (x) = e^yx^n/(n+1)!$ 을 만족하는 값이다. $x<0$ 이면 $-\infty < y < 0$ 이므로 $e^y<1$ 이며 $x>0$ 이면 $0<y<x$ 이므로 $e^y < e^x$ 이다. 따라서 $0<e^y \le \max\{e^x,\,1\}$ 이며, 주어진 식이 증명되었다. 그런데 우리는 $e^1$ 의 정확한 값을 모른다고 가정해야 한다. 다만 $0<e<3$ 임을 안다(고 가정하자).

$e=e^1$ 이므로 $\left| R_n (1)\right| < \dfrac{3}{(n+1)!} $ 이다. $R_5(1)<0.0042, R_6(1)<0.0006$ 이므로 6차항 까지 계산하면 된다.

$$
e^1 \approx 1+1+\dfrac{1}{2} + \dfrac{1}{3!} + \dfrac{1}{4!}+\dfrac{1}{5!}+\dfrac{1}{6}=2.7180\dot5
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_4_2} 

$e^{0.1}$ 의 근사값을 오차가 $10^{-3}$ 이내가 되도록 구하라.

:::

</div>

::: {.solution}

$1<e^{0.1}<2$ 이므로$R_n (0.1) \le  \left|\dfrac{(0.2)^n}{(n+1)!}\right|$ $R_1(0.1)\le 0.1,\, R_2(0.1)= 0.00\dot{6},\, R_3(0.1)\le 0.000\dot{3}$ 이므로 $3$ 차항 까지만 구하면 된다.

$$
e^{0.1}\approx 1+0.1+ \dfrac{(0.1)^2}{2}+ \dfrac{(0.1)^3}{3!}=1.105\;.
$$

:::

</br>

**3.** 생략

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_4_4} 

원점을 포함하는 구간에서 정의된 $n$ 번 미분 가능한 함수 $f(x)$ 의 $n-1$ 차 나머지항 $R_{n-1}(x)$ 에 대하여

$$
\lim_{x \to 0} \dfrac{R_{n-1}(x)}{x^n} = \dfrac{f^{(n)}(0)}{n!}
$$

임을 보이라.

:::

</div>

::: {.solution}

$\displaystyle F_n (x) = \sum_{k=0}^n \dfrac{f^{(k)}(0)}{k!} x^n$ 은 $f(x)$ 의 $n$ 차항 까지의 테일러 전개이다. $R_{n-1}(x) = f(x) - F_{n-1} (x)$ 이므로,

$$
\begin{aligned}
\lim_{x \to 0}\dfrac{R_{n-1}(x)}{x^n} &= \lim_{x \to 0}\dfrac{f(x)-F_{n-1}(x)}{x^n} \\
&=\lim_{x\to 0}\dfrac{f'(x)-F'_{n-1}(x)}{nx^{n-1}} \\
&\vdots \\
&= \lim_{x\to 0}\dfrac{f^{(n-1)}(x)-f^{(n-1)}(0)}{n!x} \\
&=\lim_{x \to 0}\dfrac{f^{(n)} (x)}{n!} \\
&=\dfrac{f^{n}(0)}{n!}
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_4_5} 

무한급함수 $f(x)$ 의 한 임계점 $x_0$ 에서 $f''(x_0)=0$ 일 때 $f'''(x_0)\ne 0$ 이면 $x_0$ 는 극소점도 아니고 극대점도 아님을 보이라.

:::

</div>

::: {.solution}

$x_0=0$ 으로 놓아도 no loss of generality.

$f(x)=f(0)+\dfrac{f'''(0)}{6}x^3 +R_{3}(x)$. $0$ 을 포함하는 어떤 열린구간 $I_0$ 에서 $f(x)-f(0) \approx ax^3$ for some constant $a$ 인데 $(f(x)-f(0))(f(-x)-f(0))<0$ 이므로 $0$ 은 극소점도 극대점도 아니다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_4_6} 

원점을 포함하는 구간에서 정의된 $n$ 급 함수 $f(x)$ 에 대하여,

$$
B_n f(x) : = \max\{|f^{(n)}(t)-f^{(n)}(0)|: t\in [0,\,x]\}
$$

로 두면, $f(x)$ 의 $n$ 차 테일러 나머지항 $R_n f(x)$ 는 부등식

$$
|R_n f(x)|\le B_n f(x) \dfrac{|x|^n}{n!}
$$

을 만족시킴을 보여라.

:::

</div>

::: {.solution}

$f(x) = \displaystyle \sum_{k=0}^{n-1}\dfrac{f^{(k)}(0)}{k!}x^k + R_{n-1}f(x) = \sum_{k=0}^{k-1} \dfrac{f^{(k)}(0)}{k!}x^k+ \dfrac{f^{(n)}(0)}{n!} x^n+R_{n}f(x)$ 이므로,

$$
R_n f(x) = R_{n-1}f(x)-\dfrac{f^{(n)}(0)}{n!}x^n=\dfrac{f^{(n)}(x_*)-f^{(n)}(0)}{n!}x^n
$$

이다. 여기서 $x_*\in (0,\,x)$ 는 테일러 전개의 나며지 항을 만족하는 실수이다. 따라서,

$$
|R_n f(x) | = \left|f^{(n)}(x_*)-f^{(n)}(0) \right|\dfrac{|x|^n}{n!} \le B_{n}f(x) \dfrac{|x|^n}{n!}
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_4_7} 

$\sqrt[3]{28}$ 의 근사값을 오차의 범위 $10^{-3}$ 이내로 구하라.

:::

</div>

::: {.solution}

28에 가까운 27 은 $3^3$ 이다. 따라서 $\sqrt[3]{28}= \sqrt[3]{27+1}=3\sqrt[3]{1+1/27}$ 이다. $f(x)=\sqrt[3]{1+x}$ 라 하면,

$$
\begin{aligned}
f(0) &= 1\,,\\
f'(0) &=\left(\dfrac{1}{3}(1+x)^{-2/3}\right)(0)=\dfrac{1}{3}\,,\\
f''(0) &= \left(-\dfrac{2}{9}(1+x)^{-4/3}\right)(0)= -\dfrac{2}{9}\,,\\
\left|R_1 (x)\right| &= \left| \dfrac{f''(x)}{2} x^2\right| \le  \dfrac{1}{6}\cdot \left(\dfrac{1}{27}\right)^2 =2.29\times 10^{-4}
\end{aligned}
$$

이므로 근사값은 $3\left( 1+\dfrac{1}{3}\dfrac{1}{27} \right)\approx 3.037$ 이다.  

:::

</br>

## 연습문제 : 제 3장 5절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_5_1} 

다음 함수의 테일러 급수를 구하라.

:::

</div>

::: {.solution}

($1$) $\cosh x$

$$
\cosh x=\dfrac{e^x+e^{-x}}{2},\qquad (\cosh x)'= \sinh x,\, \qquad (\cosh x )''=\cosh x
$$

이며 $\cosh 0=1$, $\sinh x=0$ 이므로,

$$
\cosh x = \sum_{n=0}^\infty\dfrac{1}{(2n)!}x^{2n}
$$

($2$) $\sinh x$

($1$) 의 결과로,

$$
 \sinh x = \sum_{n=0}^\infty \dfrac{1}{(2n+1)!}x^{2n+1}
$$

($3$) $f(x) = \sin x^2$

$$
\sin x^2 = \sum_{k=0}^\infty \dfrac{(-1)^k}{(2k+1)!}x^{4k+2}
$$

($4$) $f(x) = \dfrac{1}{1+x^3}$

$$
\dfrac{1}{1+x^3}= \sum_{k=0}^{\infty} (-1)^{k} x^{3k}
$$

::: 

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_5_2} 

원점에서 함수

$$
f(x)=\dfrac{1}{1+x^2}
$$

의 테일러 급수를 구하고, 수렴반경을 구하라. 이 때 점 $x=1$ 에서 $f(x)$ 의 테일러 급수가 수렴하는가? 또 함수

$$
g(x)=\dfrac{x}{1+3x^2}
$$

의 테일러 급수의 수렴반경을 구하라.

:::

</div>

::: {.solution}

$$
f(x) = \dfrac{1}{1+x^2}=\sum_{n=0}^\infty (-1)^n x^{2n}
$$

이며 $x=1$ 일 때 $ 1+(-1)+1 +(-1)+\cdots$ 이므로 수렴하지 않는다.

$$
g(x) = \dfrac{x}{1+3x^2}=\sum_{n=0}^{\infty} (-3)^n x^{2n+1}
$$

이므로 수렴반경은 $\dfrac{1}{\sqrt{3}}$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_5_3} 

함수

$$
f(x) = \left\{\begin{array}{ll} e^{-1/x^2} \qquad & (x\ne 0) \\ 0 &(x=0)\end{array} \right.
$$

는 무한급함수 임을 살펴보고, 원점에서 이 함수의 테일러 급수를 구하라.

:::

</div>

::: {.solution}

$e^x$ 와 $-1/x^2$  은 $x\ne 0$ 에서 무한급함수이므로 그 합성함수인 $f(x)$ 는 $x\ne 0$ 에서 무한급함수이다.

$f'(x) = -\dfrac{2}{x^3} e^{-1/x^2}$ , $f''(x) = \dfrac{6}{x^4}e^{-1/x^2} + \dfrac{4}{x^6} e^{-1/x^2}$ 이므로 $f^{(n)}(x) = \text{finite sum of } \dfrac{c}{x^m} e^{-1/x^2}$ where $m\ge 3$ 임을 알 수 있다.  

$m\ge 3$ 에 대해 $\displaystyle \lim_{x \to 0} \dfrac{e^{-1/x^2}}{x^m}=\lim_{t \to \infty} \dfrac{t^m}{e^{t^2}}=0$ 이므로 $f(x)$ 는 실수 전체 구간에서 무한급함수이며,  테일러 급수는 $0$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_5_4} 

함수

$$
f(x) =\left\{\begin{array}{ll} e^{-1/\sin x} \qquad &(0<x<\pi) \\ 0 &  (x\le 0 \;\text{ or }\;x\ge \pi)\end{array}\right.
$$

는 무한급함수이지만 원점 근방에서 해석함수가 아님을 보여라.

:::

</div>

::: {.solution}

$x\ne 0$ 에서 $f$ 가 무한번 미분 가능함은 쉽게 예상 할 수 있다. $f'(x) = - \dfrac{\cos x}{\sin ^2 x} e^{-1/\sin x}$ 이므로 $f^{(n)}(x)$ 는 $\sin^k x$ 와 $\cos^k x$ for $k\in \mathbb{N}$ 의 선형결합 과  $\dfrac{e^{-1/\sin x}}{\sin^m x}$ 의 곱의 선형결합으로 이루어짐을 알 수 있다.

이 때, $\sin^k x$ 와 $\cos^k x$ 의 선형결함의 $x\to 0$ 극한은 유한하므로 $\displaystyle \lim_{x \to 0} \dfrac{e^{-1/\sin x}}{\sin^m x}$ 을 계산하면 된다. $t=1/\sin x$ 라 치환하면, $t\to +\infty$ 를생각해야 한다.

$$
\lim_{x \searrow 0} \dfrac{e^{-1/\sin x}}{\sin^m x}= \lim_{t \to \infty} \dfrac{t^m}{e^{t}}=0\,,\\
$$

즉 $f^{(n)}(0)$ for $n=1,\,2,\,3,\,\ldots$ 이므로 무한급함수이다. 그러나 $f(x)$ 의 테일러전개는 $0$ 이므로 해석함수는 아니다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_5_5} 

원점에서 함수 $f(x) = \left\{\begin{array}{ll} \dfrac{e^{x}-1}{x} \,,\qquad &\text{if } x\ne 0 \\ 1 \;. &\text{if } x=0\;.\end{array}\right.$ 의 테일러 급수를 구하고 그 급수의 수렴반경을 구하라. 또,

$$
\sum_{n=1}^\infty \dfrac{n}{(n+1)!}=1
$$

임을 보이라.

:::

</div>

::: {.solution}

$e^x$ 의 테일러 전개는 잘 알고 있으므로,

$$
\dfrac{e^x-1}{x} = \sum_{n=1}^\infty \dfrac{x^{n-1}}{n!}
$$

임을 알고 있다. 또한 $\displaystyle \lim_{n \to \infty} \dfrac{(n)!}{(n+1)!}=\lim_{n\to \infty} \dfrac{1}{(n+1)}=0$ 이므로 수렴반경은 실수 전체이다.

이 함수를 미분하면,

$$
\begin{aligned}
\dfrac{d}{dx}\left(\dfrac{e^x-1}{x}\right) &=  \dfrac{xe^x-(e^x-1)}{x^2}=\dfrac{xe^x-e^x+1}{x^2}\,,\\
\dfrac{d}{dx} \left(\sum_{n=1}^\infty \dfrac{x^{n-1}}{n!}\right) &= \sum_{n=1}^\infty\dfrac{(n-1)x^{n-2}}{n!}=\sum_{n=1}^\infty \dfrac{nx^{n-1}}{(n+1)!}
\end{aligned}
$$

이므로 두 식에 $x=1$ 을 대입하면,

$$
\sum_{n=1}^\infty \dfrac{n}{(n+1)!}= 1
$$

이다.

:::

</br>

## 연습문제 : 제 3장 6절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_6_1} 

$x=1$ 에서 다음 함수의 3차 근사 다항식을 구하라.

:::

</div>

::: {.solution}

($1$) $x^2+x+1$

$$
\begin{aligned}
f(1) &= 3\,,\\
f'(1) &=(2x+1)(1)=3\,,\\
f''(1) &=(2)(1)=2\,,\\
f'''(1)&=0\,,\\
f(x) &\approx 3+3(x-1)+(x-1)^2\;.
\end{aligned}
$$

($2$) $\sin (\pi x)$

$$
\begin{aligned}
f(1) &= 0\,,\\
f'(1) &=(\pi \cos (\pi x))(0)=\pi\,,\\
f''(1) &= (-\pi^2 \sin (\pi x))(0)=0\,,\\
f'''(1)&= (-\pi^3 \cos (\pi x))(0)=-\pi^3\;.\\
f(x)&\approx\pi x -\dfrac{\pi^3}{6}x^3
\end{aligned}
$$

:::


</br>

**2.** 생략

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_6_3} 

두 번 미분가능한 함수 $f(x)$ 에 대하여

$$
f''(x) = \lim_{\Delta x \to 0} \dfrac{f(x+\Delta x) + f(x-\Delta x) -2f(x)}{(\Delta x)^2}
$$

임을 보이라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
\lim_{\Delta x\to 0} & \dfrac{f(x+\Delta x) + f(x-\Delta x) -2f(x)}{(\Delta x)^2} \\[0.3em]
&= \lim_{\Delta x \to 0} \dfrac{f'(x+\Delta x)- f'(x-\Delta x) }{2(\Delta x)} \qquad&\text{by l'Hopital's theorem} \\
&=\lim_{\Delta x \to 0} \dfrac{f''(x+\Delta x)+f''(x-\Delta x)}{2} \\
&=f''(x)
\end{aligned}
$$

:::

</br>

## 로피탈의 정리

구간 $(a,\,b)$ 에서 정의된 미분가능한 함수 $f(x),\, g(x)$ 에 대하여 극한값

$$
l :=\lim_{x \searrow a} \dfrac{f'(x)}{g'(x)}
$$

가 존재한다고 하자. 이 때, $\displaystyle \lim_{x \searrow a} f(x)=0,\, \lim_{x \searrow a} g(x)=0$ 이거나 $\lim_{x \searrow a} f(x) = \infty,\,m \lim_{x \searrow a} g(x) = \infty$ 이면,

$$
\lim_{x \searrow a} \dfrac{f(x)}{g(x)}=l
$$

이다.


::: {.proof} 

코시의 평균값정리에 의하여, $x,\,y \in (a,\,b)$ 가 $a$ 에 가까우면,

$$
f(x)-f(y) = (g(x)-g(y))\dfrac{f'(c)}{g'(c)}
$$

가 되는 $c$ 가 $x,\,y$ 사이에 존재한다. 이 식을 $g(x)$ 로 나눈 다음 정리하면,

$$
\begin{aligned}
\dfrac{f(x)}{g(x)} &= \dfrac{f(y)}{g(x)} + \left(1-\dfrac{g(y)}{g(x)}\right) \dfrac{f'(c)}{g'(c)}
\dfrac{f(x)}{g(x)}-l \\[0.3em]
&= \dfrac{f(y)}{g(x)} + \left(1-\dfrac{g(y)}{g(x)}\right) \left(\dfrac{f'(c)}{g'(c)}-l\right)+ l \dfrac{g(y)}{g(x)}
\end{aligned}
$$

을 얻는다. $\displaystyle l :=\lim_{x \searrow a} \dfrac{f'(x)}{g'(x)}$ 이므로 임의의 $\varepsilon>0$ 에 대하여,

$$
\begin{gather}
|x-a|<{\delta_1} \implies  \left|\dfrac{f'(x)}{g'(x)}-l\,\right|<{\varepsilon}\,,\\
|y-a|<{\delta_2} \implies  \left|\dfrac{f'(y)}{g'(y)}-l\,\right|<{\varepsilon}\,,\\
\end{gather}
$$

를 만족하는 $\delta_1,\,\delta_2$ 가 존재한다. 이 때 $\delta = \min \{\delta_1,\,\delta_2\}$ 라 하자. $c$ 가 $x$ 와 $y$ 사이에 있으므로, $|c-a|$ 는 $|x-a|$ 와 $|y-a|$ 중 큰 값보다 항상 작다. 즉 $|c-a|<{\delta}$ 이므로 $\left|\dfrac{f'(c)}{g'(c)}-l\,\right| <{\varepsilon}$ 이다.

따라서,

$$
\left|\dfrac{f(x)}{g(x)}-l\,\right| \le \left|\dfrac{f(y)}{g(x)}\right| + \left|1-\dfrac{g(y)}{g(x)}\right| \cdot \varepsilon + |l|\cdot \left|\dfrac{g(y)}{g(x)}\right|
$$

이다. $f$ 와 $g$ 의 $x \to a$ 극한이 $0$ 인 경우 위 식에서 $y\to a$ 극한을 취해도 위 부등식은 성립한다. 즉,

$$
\left|\dfrac{f(x)}{g(x)}-l\,\right| \le \varepsilon
$$

이다. 즉 $\displaystyle \lim_{x \searrow a} \dfrac{f(x)}{g(x)}=l$ 이다.

$f$ 와 $g$ 의 $x\to a$ 극한이 $\infty$ 인 경우 위 식에서 $x\to a$ 극한을 취하면,

$$
\lim_{x \searrow a} \left|\dfrac{f(x)}{g(x)} -l\,\right| \le \varepsilon
$$

을 얻는다. 따라서 이 경우도  $\displaystyle \lim_{x \searrow a} \dfrac{f(x)}{g(x)}=l$  이다.

:::


</br>

## 탐구문제

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_S01} 

정적분

$$
\int_{0}^1 \arctan x^2 dx
$$
를 값의 오차의 한계가 $10^{-3}$ 이하가 되도록 구하라.

:::

</div>

::: {.solution}

$\dfrac{d}{dx} \arctan x = \dfrac{1}{1+x^2}= \displaystyle \sum_{k=0}^\infty (-1)^{k}x^{2k}$ 임을 이용한다.

$$
\begin{aligned}
\arctan x^2 &= \sum_{k=0}^\infty \dfrac{(-1)^k x^{4k+2}}{2k+1}\\
\int_0^1 \arctan x^2 \, dx&=\sum_{k=0}^\infty \dfrac{(-1)^k}{(2k+1)(4k+3)}
\end{aligned}
$$

Tayler series를 생각하면 $(2k+1)(4k+3)>10^3$ 이 되도록 하는 $k$ 값을 찾으면 된다.  $k>10$ 이므로 위 식을 10 차항 까지 구하면 된다. 이에 대한 python code 는 아래와 같다.

```python
import numpy as np
nn = np.arange(0,11)
pp = ((-1)**nn) /(2*nn+1)/(4*nn+3)
print(pp.sum())

0.2984047079489637
```

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_S02} 

원점 근방에서 정의된 $n+1$ 급 함수 $f(x)$ 의 테일러 전개에서 $n$ 차 나머지 항은

$$
R_n f(x) = \dfrac{1}{n!} \int_0^x (x-t)^n f^{(n+1)}(t)\,dt
$$

로 주어짐을 귀납법을 이용하여 보이라.

:::

</div>

::: {.solution}

($1$) $n=0$ 일 때,

$$
R_0 f(x) = \int_0^x f'(t) dt = f(t)-f(0)
$$

이므로 성립한다.

($2$) $n$ 일 때 성립함을 가정하자.

$$
\begin{aligned}
R_{n+1}f(x) &= \dfrac{1}{(n+1)!} \int_0^x (x-t)^{n+1} f^{(n+2)} (t)\, dt \\
&=\dfrac{1}{(n+1)!}\left[ (x-t)^{n+1} f^{(n+1)}(t)\right]_{t=0}^{t=x} \\[0.3em]
&\qquad\qquad - \dfrac{1}{(n+1)!} \int_0^x\left(-(n+1)(x-t)^{n} \right)f^{(n)}(t)\, dt \\
&=-\dfrac{f^{(n+1)}(t)}{(n+1)!} x^{n+1}  + R_n f(x)
\end{aligned}
$$

이다. 우리는,
$$
\begin{aligned}
f(x) &= f(0)+\cdots + \dfrac{f^{(n)}(0)}{n!}x^{n} +R_{n}f(x) \\[0.3em]
&= f(0) + \cdots +  \dfrac{f^{(n)}(0)}{n!}x^{n} + \dfrac{f^{(n+1)}(0)}{(n+1)!}x^{n+1} + R_{n+1}f(x)
\end{aligned}
$$
임을 알고 있으므로 $n$ 일 때 성립함을 가정하면 $n+1$ 에서도 성립함을 보였다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_S03} 

#### Fourier 급수

Fourier에 의하면 모든 주기함수는 사인함수와 코사인 함수의 (무한)합으로 나타난다. 좀 더 자세히 서술하면 다음과 같다. 함수

$$
\sin x,\, \sin 2x,\, \sin 3x,\ldots,\,\qquad,\,1,\, \cos x,\, \cos 2x,\, \cos 3x,\ldots
$$

는 모두 주기가 $2\pi$ 인 함수이다(최소주기가 아니라 일반적인 주기, 즉 어떤 $T\in \mathbb{R}$ 에 대해 모든 $x\in \mathbb{R}$ 에서 $f(x)=f(x+T)$ 일 때 $T$ 를 $f$ 의 주기라 한다.) 함수 $f(x)$ 가 주기가 $2\pi$ 인 함수이면,

$$
f(x) = a_0 + \sum_{n=1}^\infty (a_n \cos nx + b_n \sin nx)
$$

를 만족시키는 실수 $a_0,\,a_1,\,b_1,\,a_2,\,b_2,\ldots$ 가 (오직 하나) 존재한다. 이때 위 식의 오른쪽 항을 $f$ 의 Fourier 급수 전개라고 부른다. 이제 급수

$$
\sum_{n=1}^\infty \dfrac{\sin nx}{n}
$$

가 수렴하기 위한 $x$ 의 범위를 구하라.

:::

</div>

::: {.solution}

$\sin nx = \dfrac{e^{inx}-e^{-inx}}{2i}$ 이 다. 위 식은

$$
\begin{aligned}
\sum_{n=1}^\infty \dfrac{\sin nx}{n} &=\dfrac{1}{2i}\sum_{n=1}^\infty \dfrac{\left(e^{inx}-e^{-inx}\right)}{n}  \\
&=-\dfrac{1}{2} \sum_{n=1}^\infty\left[  \int_{0}^x e^{int}\,dt +\int_0^x e^{-int}\, dt\right] \\
&=-\dfrac{1}{2} \int_0^x \left[\sum_{n=1}^\infty \left(e^{int}+e^{-int}\right)\right] \,dt
\end{aligned}
$$

이다. $\sum$  안이 수렴하려면

---- to be done ----

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_S04} 

함수

$$
f(x):=\left\{ \begin{array}{ll} e^{-\tan^2 x} \,,\qquad &x \in \left(-\dfrac{\pi}{2},\, \dfrac{\pi}{2}  \right) \\ 0\,, & x \not\in \left(-\dfrac{\pi}{2},\, \dfrac{\pi}{2} \right)\end{array}\right.
$$

가 무한급 함수임을 보여라.

:::

</div>

::: {.solution}

$x\not\in\left(-\dfrac{\pi}{2},\, \dfrac{\pi}{2}\right)$ 일 때는 무한급이므로 $x\in \left(-\dfrac{\pi}{2},\, \dfrac{\pi}{2} \right)$ 와 두 영역의 경계에서만 생각하자. $e^{-\tan^2 x}$ 함수의 $n$ 차 미분의 각 term은 모두 $e^{-\tan^2 x}$ 를 포함하고 있음을 알 수 있다. 이 때,

$$
\lim_{x \to -\pi/2} e^{-\tan^2 x}= \lim_{x \to \pi/2} e^{-\tan^2 x}=0
$$

이다.

$$
f'(x) = -2\dfrac{\sin x}{\cos^3 x} e^{-\tan^2 x}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_S05} 

#### 큰 $O$

원점을 포함하는 구간 $I$ 에서 정의된 함수 $f$ 와 자연수 $n$ 에 대하여 어떤 상수 $B,\, \delta$ 가 존재하여, $|x|<\delta$ 이면 $|f(x)|\le B|x|^n$ 이라고 하자. 이 대 $f$ 를 원점 근방에서 $O(x^n)$ 이라 부르고 $f(x) \in O(x^n)$ 이라고 쓴다.

($1$) $\sin x \in O(x)$ 임을 보이라.

($2$) $\sin x \not\in O(x^2)$ 임을 보이라.

($3$) $f(x),\,g(x) \in O(x^n)$ 이면 $f(x)+g(x) \in O(x^n)$ 임을 보이라.

($4$) 임의의 실수 $c$ 와 $f(x) \in O(x^n)$ 에 대하여 $cf(x) \in O(x^n)$ 임을 보이라.

:::

</div>

::: {.solution}

($1$) $\delta<1$ 이라 하자.  $\sin x = x-\dfrac{\sin (x_{\ast}) x^3}{6}$  을 만족하는  $x_{\ast} \in (-\delta,\,\delta)$  가 존재한다. $|\sin (x_{\ast})|\le 1$, $|x| <\delta <1$ 을 이용하면,

$$
\begin{aligned}
|\sin x| &= \left|x - \dfrac{\sin(x_{\ast})}{6} x^3\right| \le |x|+\left|\dfrac{\sin (x_{\ast})}{6}\right||x|^3 \\
& \le |x|+\dfrac{1}{6} |x|^3 < |x| + \dfrac{1}{6} |x|=\dfrac{7}{6}|x|
\end{aligned}
$$

($2$) $\sin x\in O(x^2)$ 라 가정하자. 즉 $|x|<\delta \implies |\sin x| \le B|x|^2$ 를 만족하는 $B,\, \delta$ 가 존재함을 가정한다. 그렇다면 $-Bx^2 \le \sin x \le Bx^2$ 이므로, 양변을 $x^2$ 으로 나눈 후 $x \to 0$ 극한을 취하면, $\displaystyle \lim_{x \to 0 }\dfrac{\sin x}{x^2}$ 은 $(-B,\,B)$ 사이에 위치해야 하나 우리는 이 극한값이 발산함을 알고 있다.

($3$) $|x|<\delta_1 \implies |f(x)|\le B_1 |x|^n$ 이고 $|x|<\delta_2 \implies |g(x)|\le B_2 |x|^n$ 이라 하자. $\delta = \min \{\delta_1,\,\delta_2\}$ 라 하면 $|x|<\delta \implies |f(x)|\le B_1 |x|^,\, g(x)\le B_2|x|^n$ 이다.

$$
|x|<\delta \implies |f(x)+g(x)|\le |f(x)|+|g(x)|\le (B_1+B_2)|x|^n
$$

($4$) $|x|<\delta \implies |f(x)|\le B|x|^n \implies |cf(x)|\le (|c|B) |x|^n$.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_S07}

두 함수 $f,\,g : [2,\infty) \to \mathbb{R}$ 에 대하여

$$
\lim_{x \to \infty} \dfrac{f(x)}{g(x)} =1
$$

이며 $f\sim g$ 라고 나타내기로 하자. 이제 로피탈의 정리를 이용하여,

$$
\dfrac{x}{\ln x} \sim \int_2^x \dfrac{dt}{\ln t}
$$

임을 보이라.

:::

</div>

::: {.solution}

$\displaystyle \lim_{x \to \infty} \dfrac{x}{\ln x}=\infty$ 와 $\displaystyle \lim_{x \to \infty}\int_2^x \dfrac{dt}{\ln t}=\infty$ 임은 쉽게 보일 수 있다. 이제 로피탈의 정리를 사용한다.

$$
\lim_{x\to \infty} \dfrac{\dfrac{x}{\ln x}}{\displaystyle \int_2^x \dfrac{dt}{\ln t}} = \lim_{x \to \infty} \dfrac{\dfrac{1}{\ln x} - \dfrac{1}{(\ln x)^2}}{1/\ln x}=\lim_{x \to \infty}\dfrac{1-\dfrac{1}{\ln x}}{1}=1
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_S08} 

정수론을 연구하는 학자들은

> 주어진 자연수 $n$ 에 대하여, $n$ 이하의 소수의 개수가 과연 얼마나 될까?

하는 문제에 관심이 많다. 여기에서 $n$ 이하의 소수의 개수를 $\pi (n)$ 이라고 두면,

$$
\pi (1)=0,\, \quad \pi(2)=1,\quad \pi(3)=2,\quad \pi (4) =2,\quad \pi (5) =3,\ldots
$$

을 알 수 있다.

1896년 경에 Hadamard와 de la Vallée-Poussin 에 의하여 독자적으로 발견된 소수정리에 의하면,

$$
\pi (n) \sim \dfrac{n}{\ln n} 
$${#eq-exr-CAL_3_S08_1}

임이, 즉,

$$
\lim_{n \to \infty} \dfrac{\pi (n) \ln n}{n}=1 
$${#eq-exr-CAL_3_S08_2}

이 알려졌다. 이를 이용하여 멱급수

$$
\sum_{n=0}^\infty \dfrac{1}{\pi (n)} x^n
$$

의 수렴반경을 구하라.

:::

</div>

::: {.solution}

$\displaystyle \sum_n a_n x^n$ 에 대한 수렴반경은 $\rho:=\displaystyle \lim_{n \to \infty} \left| \dfrac{a_{n+1}}{a_n} \right|$ 일 때 $\dfrac{1}{\rho}$ 임을 안다.  

@eq-exr-CAL_3_S08_2 에 의하면 어떤 고정된 $\varepsilon>0$ 에 대해 $N\in \mathbb{N}$ 이 존재하여 $n\ge N \implies \left|\dfrac{\pi (n) \ln n}{n }-1\right|< \dfrac{\varepsilon}{2}$ 이다. 따라서,

$$
\left(1-\dfrac{\varepsilon}{2}\right) \dfrac{n}{\ln n} < \pi (n) <\left(1+\dfrac{\varepsilon}{2}\right) \dfrac{n}{\ln n}
$$

이다. $0<\varepsilon \ll 1$ 이라도 잡아도 상관 없으므로,

$$
\dfrac{\left(1-\dfrac{\varepsilon}{2}\right) \dfrac{n}{\ln n}}{\left(1+\dfrac{\varepsilon}{2}\right) \dfrac{n+1}{\ln (n+1)}}<\dfrac{\pi (n)}{\pi(n+1)} <\dfrac{\left(1+\dfrac{\varepsilon}{2}\right) \dfrac{n}{\ln n}}{\left(1-\dfrac{\varepsilon}{2}\right) \dfrac{n+1}{\ln (n+1)}}
$$

$(1-x)/(1+x)$ 는 $0$ 근방에서 단조감소, $(1+x)/(1-x)$ 는 $0$ 근방에서 단조증가 함수이므로, 충분히 작은 $\varepsilon$ 에 대해,

$$
\begin{aligned}
(1-\varepsilon)\dfrac{ \dfrac{n}{\ln n}}{\dfrac{n+1}{\ln (n+1)}} &< \dfrac{\left(1-\dfrac{\varepsilon}{2}\right) \dfrac{n}{\ln n}}{\left(1+\dfrac{\varepsilon}{2}\right) \dfrac{n+1}{\ln (n+1)}} < \dfrac{\pi (n)}{\pi(n+1)} \\[0.3em]
&<\dfrac{\left(1+\dfrac{\varepsilon}{2}\right) \dfrac{n}{\ln n}}{\left(1-\dfrac{\varepsilon}{2}\right) \dfrac{n+1}{\ln (n+1)}}<(1+\varepsilon)\dfrac{ \dfrac{n}{\ln n}}{\dfrac{n+1}{\ln (n+1)}}
\end{aligned}
$$

이므로 $\displaystyle \lim_{n \to \infty} \dfrac{\pi (n)}{\pi (n+1)}= \lim_{n \to \infty} \dfrac{n\ln {n}}{(n+1)\ln (n+1)}$ 이며, 로피탈의 정리를 사용하면,

$$
\lim_{n \to \infty} \dfrac{n\ln {n}}{(n+1)\ln (n+1)}=\lim_{n \to \infty} \dfrac{\ln n+1}{\ln (n+1)+1}=\lim_{n \to \infty} \dfrac{n+1}{n}=1
$$

이다. 따라서 수렴반경은 $1$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_S09} 

구간 $I$ 에서 정의된 미분가능함수 $f(x)$ 와 주어진 점 $c\in I$ 에 대하여

$$
f(x) =f(c)+(x-c)g(x)
$$

를 만족시키는 연속함수 $g(x)$ 가 존재함을 보여라. 이때 $g(c) =f'(c)$ 임을 보이라. 만약 $f(x)$ 의 $n$ 계 도함수 $f^{(n)}(x)$  가 존재하면, $g(x)$ 의 $(n-1)$ 계 도함수가 존재함을 보이라.

:::

</div>

::: {.solution}

$h(x)=\dfrac{p(x)}{q(x)}$ 이며 $p(x),\,q(x)$ 가 어떤 구간 $I$ 에서 연속이고 이 구간에서 $p(x)\ne 0$ 이면 $h(x)$ 도 $I$ 에서 연속임을 보이자. $p(x),\, q(x)$ 가 $c\in I$ 에서 연속이므로, 임의의 $\varepsilon>0$ 에 대해 어떤 $\delta_1>0,\, \delta_2>0$ 이 존재하여 $0<|x-c|<\delta_1 \implies |p(x)-q(c)|<\varepsilon$ 이고 $0<|x-c|<\delta_2\implies |q(x)-q(c)|<\varepsilon$   이다. $\delta = \min \{\delta_1,\, \delta_2\}$ 라 하면 $0<|x-c|<\delta \implies |p(x)-p(c)|<\varepsilon,\, |q(x)-q(c)|<\varepsilon$ 이다.  우선 $\varepsilon < \min \{1,\,|q(c)|\}$ 라 선택한다고 하자.

$$
\begin{aligned}
|h(x)-h(c)| &= \left|\dfrac{p(x)q(c)-q(x)p(c)}{q(x)q(c)}\right|=\left|\dfrac{q(c)(p(x)-p(c))-p(c)(q(x)-q(c))}{q(x)q(c)}\right| \\
&\le \dfrac{1}{|q(x)|}\left| p(x)-p(c)\right|+\dfrac{|p(c)|}{|q(c)|} \left|q(x)-q(c) \right| \\
&\le\left(\dfrac{1}{|q(x)|} + \left|\dfrac{p(c)}{q(c)}\right| \right) \varepsilon
\end{aligned}
$$

를 얻었다. $\varepsilon> |q(x)-q(c)|\ge \large \left| \normalsize |q(x)|-|q(c)|\large\right|$ 이므로 $|q(c)|-\varepsilon < |q(x)|<|q(c)|+\varepsilon$ 이며 $\varepsilon<q(c)$ 이므로, $|q(x)|>\dfrac{|q(c)|}{2}$ 이다. 따라서,

$$
|h(x)-h(c)|\le \left(\dfrac{2+|p(c)|}{|q(c)|} \right)\varepsilon
$$

이므로 $h(x)$ 는 연속이다. 주어진 식에 대해서는 $g(x) = \dfrac{f(x)-f(c)}{x-c}$ 이며 $f(x)-f(c)$ 와 $x-c$ 가 구간 $I$ 중 $c$ 를 제외한 구간에서 앞의 증명을 만족하므로 $c$ 를 제외한 영역에서 연속이다. 그리고 $g(c)=f'(c)$ 로 정의 한다면, $\displaystyle \lim_{x \to c} g(x) = f'(c)$ 이므로 $g(x)$ 는 구간 $I$ 에서 연속인 함수가 된다.

즉,

$$
g(x) = \left\{ \begin{array}{ll} \dfrac{f(x)-f(c)}{x-c}\,,\qquad & x \ne c \\ f'(c) \,, & x=c \end{array} \right.
$$

이며 $g(x)$ 는 연속함수이다.  

이제 $g' (x) = \dfrac{f'(x)(x-c)-f(x)-f(c)}{(x-c)^2}$ when $x\ne c$ 이며 로피탈의 정리를 이용하면 $\displaystyle \lim_{x \to c}g'(x) = \dfrac{f''(c)}{2}$ 임을 안다.

이제 $F_n[x]$ 를 $f^{(k)}(x)(x-c)^l$ where $k,\, l = 0,\ldots,\,{n-1}$ and $k+l<n$ 꼴의 함수의 선형결합이으로 이루어진 함수의 집합이라고 하자. $f$ 가 $n$ 계 도함수일 때 $F_{n}[x]$ 에 속한 모든 함수는 구간 $I$ 에서 미분가능하다. $h(x)\in F_n[x]$ 라면 $h'(x)\in F_{n+1}[x]$ 임은 쉽게 알 수 있다.  즉 $h(x) =f(x)-f(c) \in F_0[x]$  에 대해

$$
g'(x)=\dfrac{f'(x)(x-c)-h(x)}{(x-c)^2}
$$

이다. $h(x) \in F_{n-1}[x]$ 에 대해  $g^{(n)}(x) = \dfrac{f^{(n)}(x)(x-c)^{n}+h(x)}{(x-c)^{n+1}}$  일 때,

$$
\begin{aligned}
g^{(n+1)}(x) &= \dfrac{(f^{(n+1)}(x)(x-c) +f^{(n)}(x) + h'(x))(x-c) - (n+1)(f^{(n)}(x)(x-c)+h(x))}{(x-c)^{n+2}}\\
&= \dfrac{f^{(n+1)}(x)(x-c) + q(x)}{(x-c)^{n+2}} =\dfrac{f^{(n+1)}(x)}{(x-c)^{n+1}} + \dfrac{q(x)}{(x-c)^{n+2}}\qquad ;q(x)\in F_{n}[x]
\end{aligned}
$$

이다. 즉 $f^{(n)}(x)$ 가 존재한다면 $x\ne c$ 에 대해 $g^{(n)}(x)$ 가 존재한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_S10} 

원점에서 함수가 $f(x)=\dfrac{1}{1+x+x^2}$ 의 테일러 급수가 수렴하는 $x$ 의 범위를 구하라.

:::

</div>

::: {.solution}

우리는 $\dfrac{1}{1+y}$ 의 테일러 전개에서 수렴반경이 $1$ 임을 알고 있다. 따라서 $f(x)$ 의 수렴 조건은 $|x+x^2|<1$ 이다. 이 조건을 풀면

$$
\dfrac{-1-\sqrt{5}}{2} <x<\dfrac{-1+\sqrt{5}}{2}
$$

이므로 수렴반경은 $\dfrac{-1+\sqrt{5}}{2}$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_S11}

무한급 함수 $f: \mathbb{R}\to \mathbb{R}$ 에 대하여 점 $a\in \mathbb{R}$ 에서의 $n$ 차 테일러 다항식을 $T_{n}^a (f)$ 로 나타내기로 하자. 이제 임의의 $g,\, h \in  \mathcal{C}^\infty (\mathbb{R})$ 에 대하여,

$$
\begin{aligned}
T_n^a (gh) & \equiv (T_n^a g)(T_n^a h) & \mod\;(x-a)^{n+1}\\
T_n^a (g \circ h) &\equiv \left(T_n^{h(a)} \right) \circ T_{n}^a h & \mod \; (x-a)^{n+1}
\end{aligned}
$$

을 보이라.

:::

</div>

::: {.solution}

($1$) $T_n^a (gh)\equiv (T_n^a g)(T_n^a h) \; \mod \; (x-a)^{n+1}$ 임을 보이자. $gh$ 의 $n$ 차 도함수는 다음을 만족함을 보이자.

$$
\dfrac{d^n}{dx^n}(gh)=\sum_{k=0}^n \dfrac{n!}{k!(n-k)!} \dfrac{d^{k}g}{dx^k} \cdot \dfrac{d^{n-k}h}{dx^{n-k}}=\sum_{k=0}^k {}_nC_{k} g^{(k)}h^{(n-k)}
$$

Induction 을 사용하여 보이자. $n=1$ 일 때 $\dfrac{d}{dx}(gh)= g'h + h'g$ 이므로 성립한다. $n$ 일 때 성립함을 가정한다.

$$
\begin{aligned}
\dfrac{d^{n+1}}{dx^{n+1}}(gh)&= \dfrac{d}{dx}\left(\dfrac{d^{n}}{dx^n}(gh)\right) \\
&=\sum_{k=0}^n \dfrac{n!}{k!(n-k)!} \left(g^{(k)}h^{(n-k+1)}+g^{(k+1)} h^{(n-k)}  \right)\\
&= \left( g^{(0)}h^{(n+1)} + g^{(1)}h^{(n)}\right) + {}_nC_1 \left(g^{(1)}h^{(n)}+ g^{(2)}h^{(n-1)} \right) + \cdots +{}_nC_k \left(g^{(k)}h^{(n-k+1)} + g^{(k+1)}h^{(n-k)}\right) \\
& \qquad \qquad \qquad \qquad + {}_nC_{n-1} \left(g^{(n-1)} h^{(2)} + g^{(n)} h^{(1)}\right) + {}_nC_n \left(g^{(n)}h^{(1)}+g^{(n+1)}h^{(0)} \right) \\
&= g^{(0)}h^{(n+1)} + \left( g^{(1)}h^{(n)} +{}_nC_1 g^{(1)}h^{(n)}\right) + \cdots + \left( {}_nC_{k-1} g^{(k)}h^{(n-k-1)} +{}_nC_{k} g^{(k)}h^{(n-k+1)} \right)\\
&\qquad \qquad \qquad \qquad + \cdots + \left( {}_nC_{n-1} g^{(n)}h^{(1)} +  {}_nC_n g^{(n)} h^{(1)}\right) + {}_nC_n g^{(n+1)}h^{(0)} \\
&= g^{(0)}h^{(n+1)} + (n+1) g^{(1)}h^{(n)} + \cdots + \left({}_nC_{k-1}+{}_n C_k  \right) g^{(k)}h^{(n+k-1)} + \cdots (n+1) g^{(n)}h^{(1)} + g^{(n+1)}h^{(0)} \\
&={}_{n+1}C_{0} g^{(0)}h^{(n+1)} + {}_{n+1}C_{1} g^{(1)}h^{(n)} + \cdots + {}_{n+1}C_{k} g^{(k)} h^{(n+k-1) }+ \cdots +{}_{n+1}C_{n} g^{(n)} h^{1} + {}_{n+1}C_{n+1}g^{(n+1)}h^{(0)}\\
&= \sum_{k=0}^{n+1} \dfrac{(n+1)!}{k! (n-k+1)!} g^{(k)}h^{{(n-k+1)}}
\end{aligned}
$$

이제 $T_n^a (gh)$ 의 $k$ 차 항은 $\dfrac{(gh)^{(k)}(a)}{k!}(x-a)^k = \dfrac{1}{k!}\displaystyle \sum_{m=0}^k \dfrac{k!}{m!(k-m)!} g^{(m)}(a)h^{(k-m)}(a) (x-a)^k=\sum_{m=0}^k \dfrac{g^{(m)}(a) h^{(k-m)}(a)}{m! (k-m)!}(x-a)^k$ 임을 안다. $(T_n^a g)(T_n^ah)$ 의 $k$ 차 항은 $m=0,\,1\,\ldots,\, k$ 에 대해 $(T_n^a g)$ 의 $m$ 차항과 $(T_n^a h)$ 의 $k-m$ 차항의 곱이다. 따라서,

$$
\sum_{m=0}^{k} \dfrac{g^{(m)}(a)}{m!}(x-a)^{m} \dfrac{h^{(k-m)}(a)}{(k-m)!}(x-a)^{k-m}=\sum_{m=0}^k \dfrac{g^{(m)}(a) h^{(k-m)}(a)}{m!(k-m)!}(x-a)^k
$$

이다. 또한 $(T_n^a g)(T_n^a h)$ 중 $n$ 차 이상의 상은 $\mod\, (x-a)^{n+1}$ 에 의해 사라진다. 증명 끝.

(2) $T_n^a (g \circ h) \equiv \left(T_n^{h(a)g} \right) \circ T_{n}^a h \; \mod \; (x-a)^{n+1}$ 임을 보이자.

Induction을 사용한다. $n=1$ 이면,

$$
\begin{aligned}
T_1^a (g \circ h) &= g(h(a)) + h'(a)g'(h(a)) (x-a) \\
\left(T_1^{h(a)}g \right) \circ T_{1}^a h \; \mod \; (x-a)^{2} &= (g(h(a))+g'(h(a))(x-h(a))\circ(h(a)+h'(a)(x-a)) \mod (x-a)^2 \\
&= g(h(a)) +g'(h(a))(h(a)+h'(a)(x-a)-h(a)) \mod (x-a)^2\\
&= g(h(a)) +h'(a) g'(h(a))(x-a)
\end{aligned}
$$

이므로 두 식이 같다.

이제 $T_n^a (g \circ h) \equiv \left(T_n^{h(a)}g \right) \circ T_{n}^a h \; \mod \; (x-a)^{n+1}$ 임을 가정하자.

$$
\begin{aligned}
\left(T_{n+1}^{h(a)}g \right) \circ T_{n+1}^a h  \mod  (x-a)^{n+2} &= \left(\sum_{k=0}^{n+1} \right)\\
T_{n+1}^a (g \circ h) &= T_{n}^a (g \circ h) + \dfrac{d}{dx}
\end{aligned}
$$

--- to be done ---

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_3_S12} 

원점 근방에서 정의된 무한급 함수 $f$ 에 대하여 수열

$$
f_0 := f(0),\quad f_1 := f'(0),\quad f_2 := f''(0), \ldots
$$

를 대응시키는 사상을 생각하자. 이 사상은 전사임을 보여라.

:::

</div>

::: {.solution}

... to be done ...

:::
