---
title: "행렬과 선형사상"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

## 연습문제 : 제 6장 1절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_1_1}

생략
:::
</div>

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_1_2}

$m\times n$ 행렬 $A_0,\,A_1,\ldots,\,A_k$ 가 임의의 실수 $x$ 에 대하여

$$
A_0 +A_1x + \cdots + A_k x^k=O
$$

이면 $A_0 = A_1=\cdots =A_k =O$ 임을 보이라.

:::
</div>

::: {.solution}
$(A_i)_{1,\,1}=a_i$ 라 하면 $a_0+a_1x+\cdots +a_kx^k=0$ 이어야 한다. 임의의 실수 $x$ 에 대해 성립하려면 $a_0=a_1=\cdots =a_k=0$ 이어야 하며 이는 $A_0,\ldots,\,A_k$ 의 각 성분에 대해서도 그러하다. 따라서 $A_0=\cdots =A_k=O$ 이어야 한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_1_3}

생략

:::

</div>

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_1_4}

$m \times n$ 행렬 전체의 집합은 $\mathbb{R}^{mn}$ 과 일대일 대응 관계가 있음을 보이라.

:::

</div>

::: {.solution}

정확히 말하면 실수에서 정의된 $m\times n$ 행렬 전체의 집합 $\mathbb{R}^{m \times n}$ 과 $\mathbb{R}^{mn}$ 이 일대일 대응 관계가 있음을 보여야 한다. $f:\mathbb{R}^{m \times n}\to \mathbb{R}^{mn}$ 을 다음과 같이 정의하자. $A\in \mathbb{R}^{m \times n}$ 에 대해

$$
f(A)=(A_{11},\ldots, A_{1n},\,A_{21},\ldots,\, A_{2n},\cdots , A_{m1},\ldots,\,A_{mn})
$$

라 하자. 이는 잘 정의된 함수이다. 임의의 $B\in \mathbb{R}^{mn}$ 에 대해 $f(A)=B$ 인 $A$ 가 존재하므로 $f$ 는 전사이며 $f(A)=f(A')\implies A=A'$ 이므로 $f$ 는 단사이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_1_5}

#### 야코비 항등식 

$n$ 차 정사각행렬 $A,\,B$ 에 대하여

$$
[A,\,B]:=AB-BA
$$

로 정의하자. 이때 $n$ 차 정사각행렬 $C$ 에 대하여,

$$
[[A,\,B],\,C]+[[B,\,C],\,A]+[[C,\,A],\,B]=O
$$

임을 보이라.

:::

</div>

::: {.solution}
$$
\begin{aligned}
{}[[A,\,B],\,C] + &[[B,\,C],\,A]+[[C,\,A],\,B] \\[0.3em]
&=[AB-BA,\,C]+[BC-CB,\,A]+[CA-AC,\,B]\\
&=(AB-BA)C-C(AB-BA)+(BC-CB)A-A(BC-CB)\\
&\qquad\qquad +(CA-AC)B-B(CA-AC)\\
&=ABC-BAC-CAB+CBA+BCA-CBA-ABC+ACB\\
&\qquad \qquad +CAB-ACB-BCA+BAC\\
&=0
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_1_6}
행렬
$$
\sigma_0 =\begin{pmatrix} 1 & 0 \\ 0 &-1\end{pmatrix},\quad \sigma_+=\begin{pmatrix} 0 & 1\\0 & 0\end{pmatrix},\quad \sigma_{-} = \begin{pmatrix}0 & 0 \\ 1 & 0\end{pmatrix}
$$
에 대하여
$$
{}[\sigma_+,\,\sigma_-]=\sigma_0,\quad [\sigma_0,\,\sigma_+]=2\sigma_+,\quad [\sigma_0,\,\sigma_-]=-2\sigma_-
$$
임을 보이라.

:::

</div>

::: {.solution}


$$
\begin{aligned}
{}[\sigma_+,\,\sigma_-] & = \sigma_+ \sigma_- - \sigma_ - \sigma_+ = \begin{pmatrix} 1 & 0\\ 0 & 0\end{pmatrix} - \begin{pmatrix} 0 & 0 \\ 0 & -1\end{pmatrix} = \begin{pmatrix} 1 & 0\\ 0 & 1\end{pmatrix} =\sigma_0 \\
[\sigma_0,\, \sigma_+] &=\sigma_0 \sigma_+ - \sigma_+ \sigma_0 = \begin{pmatrix} 0 & 1\\ 0 & 0 \end{pmatrix} - \begin{pmatrix} 0 & -1\\ 0 & 0 \end{pmatrix} = \begin{pmatrix} 0 & 2\\ 0 & 0\end{pmatrix} =2 \sigma_{+}\\
[\sigma_0,\,\sigma_-] &=\sigma_0 \sigma_- - \sigma_- \sigma_0 = \begin{pmatrix} 0 & 0 \\ -1 & 0\end{pmatrix} - \begin{pmatrix} 0 & 0 \\ 1 & 0 \end{pmatrix} = \begin{pmatrix} 0 & 0\\ -2 & 0\end{pmatrix}=-2\sigma_-
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_1_7}

$n$ 차 정사각행렬중 $(i,\,j)$ 항만 $1$ 이고 나머지 항은 $0$ 이 되는 행렬을 $E_{ij}$ 라고 두자. 그러면,

$$
E_{ij}E_{kl}=\delta_{kj}E_{il} \quad (i,\,j,\,k,\,l) \in \{1,\ldots,\,n\}
$$

임을 보이라. 여기서,

$$
\delta_{jk}=\left\{\begin{array}{ll}1 \qquad & (j=k) \\ 0 &(j \ne k)\end{array}\right.
$$

이다.

:::

</div>

::: {.solution}

$E_{ij}$ 의 $(p,\,q)$ 항을 $[E_{ij}]_{pq}$ 라 하면 $[E_{ij}]_{pq}=\delta_{ip}\delta_{jq}$ 이다.

$$
{}[E_{ij}E_{kj}]_{pr}=\sum_{q=1}^n [E_{ij}]_{pq} [E_{kl}]_{qr}=\sum_{q=1}^n \delta_{ip}\delta_{jq}\delta_{kq}\delta_{lr}= \delta_{ip}\delta_{jk}\delta_{lr}=\delta_{jk}[E_{il}]_{pr}
$$

이므로 $E_{ij}E_{kj}=\delta_{jk}E_{il}$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_1_8}

정사각행렬중에 대각선 이외의 항이 모두 $0$ 인 행렬을 대각행렬이라고 부른다. 이 때 임의의 $n$ 차 대각행렬 $A,\,B$ 에 대하여 $AB=BA$ 임을 보이라.

:::

</div>

::: {.solution}

$A$ 가 대각행렬이면 $A_{ij}=a_j\delta_{ij}$ 이다. $B_{ij}=b_j \delta_{ij}$ 라 하면,

$$
\begin{aligned}
(AB)_{jk}&=\sum_{i=1}^n A_{ji}B_{ik}=\sum_{i=1}^n a_j\delta_{ij}b_i\delta_{ik}=a_jb_j\delta_{jk}\\
(BA)_{jk}&= \sum_{i=1}^n B_{ji}A_{ik}=\sum_{i=1}^m b_{j}\delta_{ij}a_k\delta_{ik}=a_jb_j \delta_{jk}
\end{aligned}
$$

따라서 $AB=BA$ 이다.

:::

<</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_1_9}
#### 복소수 와 행렬  

행렬 $I=\begin{pmatrix} 1 & 0 \\ 0 & 1\end{pmatrix},\, J=\begin{pmatrix}0 & -1 \\ 1 & 0\end{pmatrix}$ 에 대하여,

$$
J^2=-I
$$

임을 보이라. 또 임의의 실수 $a,\,b,\,c$ d에 대하여

$$
(aI+bJ)(cI+dJ)=(ac-bd)I+(bc+ad)J
$$

임을 보이라.

:::

</div>

::: {.solution}

$$
J^2=\begin{pmatrix}0 & -1 \\ 1 & 0\end{pmatrix}\begin{pmatrix}0 & -1 \\ 1 & 0\end{pmatrix}=\begin{pmatrix}-1 & 0 \\ 0 & -1\end{pmatrix}=-I
$$

이다. 이와 함께, $I^2=I,\, IJ=JI=J$ 를 이용하면,

$$
\begin{aligned}
(aI+bJ)(cI+dJ)&= acI+adJ+bcJ+bdJ^2=(ac-bd)I+(bc+ad)J
\end{aligned}
$$

이다.
:::

</br>

## 연습문제 : 제 6장 2절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_2_1}

삼차원 공간에서 $xy$ 평면으로의 정사영에 대응되는 행렬을 구하라. 또 $yz$-평면, $zx$-평면으로의 정사영에 대응되는 행렬을 각각 구하라.

:::

</div>

::: {.solution}

삼차원 공간에서 $xy$ 평면으로의 정사영을 함수로 하면 $p_{xy}(x,\,y,\,z)=(x,\,y,\,0)$ 이다. 이를 행렬로 표현한 것을 $P_{xy}$ 라 하면.. 그리고 $yz,\,zx$ 평면에 대해서도 같이 생각하면,

$$
P_{xy}=\begin{pmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0\end{pmatrix},\quad P_{yz}=\begin{pmatrix}0 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{pmatrix},\quad P_{zx}=\begin{pmatrix}1 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 1\end{pmatrix}
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_2_2}

$m \times n$ 행렬 $A,\,B$ 와 실수 $c$ 에 대하여,

$$
L_{A+B}=L_A+L_B,\quad L_{cA}=cL_A
$$
임을 보이라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
L_{A+B}(\bf{x})&=(A+B)\bf{x}=A\bf{x}+B\bf{x}=L_A(\bf{x})+L_B(\bf{x})\\
L_{cA}(\bf{x})&=(cA)\bf{x}=c(A\bf{x})=cL_A(\bf{x})
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_2_3}

$m\times n$ 행렬 $A$ 와 $n \times l$ 행렬 $B$ 에 대하여 두 선형사상 $L_B : \mathbb{R}^l \to \mathbb{R}^n$ 과 $L_A: \mathbb{R}^n \to \mathbb{R}^m$ 의 합성

$$
L_A \circ L_B : \mathbb{R}^l \to \mathbb{R}^m
$$

은 $L_{AB}: \mathbb{R}^l \to \mathbb{R}^m$ 과 일치함을 보이라. 즉 행렬의 곱은 선형사상의 합성에 해당된다.

:::

</div>

::: {.solution}

$$
L_A\circ L_B (\bf{x})=L_A (B\bf{x})=A(B\bf{x})=(AB)\bf{x}=L_{AB}(\bf{x})
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_2_4} 

선형사상 $L:\mathbb{R}^n \to \mathbb{R}^m$ 이 일대일 함수일 필요충분조건은 방정식 $L(X)=O$ 의 해가 자명한 것일 뿐임을 보이라.

:::

</div>

::: {.solution}

일대일 함수는 단사함수를 의미한다.

($1$) $L(X)=O$ 의 해가 자명한 것, 즉 $X=O$ 뿐임을 가정한다. 그렇다면 $A,\,B\in \mathbb{R}^n$ 에 대해
$$
L(A)=L(B)\implies L(A)-L(B)=O \implies L(A-B)=O \implies A=B
$$

이다. 이므로 $L$ 은 일대일 함수이다.

($2$) $L$ 이 일대일 함수임을 가정하자. 우리는 $L'$ 이 선형사상이면 $L'(O)=O$ 임을 알고 있다. $L$ 이 일대일 함수이면 $L(X)=O$ 를 만족하는 $X$ 가 하나 뿐 이므로 자명한 $O$ 뿐이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_2_5}

공간의 점들의 질량중심은 선형사상에 의하여 보존됨을 보여라. 즉, 점 $P_1,\ldots,\,P_k$ 의 질량이 각각 $m_1,\ldots,\,m_k$ 로 주어지고, 이들의 질량중심이 $\overline{P}$ 일 때 선형사상에 의한 이들의 상 $L(P_1),\ldots,\,L(P_k)$ 의 질량중심은 $L(\overline{P})$ 임을 보이라. (단, $L(P_i)$ 의 질량은 $m_i$ 이다.)

:::

</div>

::: {.solution}

$M=m_1+\cdots +m_k$ 라면 $\displaystyle \overline{P}=\sum_{i=1}^k \dfrac{m_i}{M}P_i$ 이다.

$$
L\left(\overline{P}\right)=L\left(\sum_{i=1}^k \dfrac{m_i}{M}P_i\right)=\sum_{i=1}^k \dfrac{m_i}{M}L(P_i)
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_2_6}

공간 속의 점들의 질량중심은 평행이동에 대하여 보존됨을 보이라.

:::

</div>

::: {.solution}

평행이동을 $f:X \mapsto X+\bf{v}$ 라 하자. 문제 5와 같은 notation을 사용한다.

$$
\begin{aligned}
f\left(\sum_{i=1}^k \dfrac{m_i}{M}P_i\right) &= \sum_{i=1}^k \dfrac{m_i}{M}P_i +\bf{v}=\sum_{i=1}^k \dfrac{m_i}{M}P_i +\sum_{i=1}^m \dfrac{m_i}{M}\bf{v} \\[0.3em]
&= \sum_{i=1}^k \dfrac{m_i}{M}(P_i+\bf{v})=\sum_{i=1}^k \dfrac{m_i}{M}f(P_i)
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_2_2}

차수가 $n$ 이하인 다항식 전체의 집합을 $P_n$ 이라 두고,

$$
p(x)=a_0+a_1x+\cdots + a_nx^n
$$

을 벡터 $(a_0,\ldots,\,a_n)$ 과 같이 보았을 때, 미분사상

$$
D:P_n \to P_n , \quad p(x)\mapsto p'(x)
$$

에 대응하는 행렬을 구하라. 또 사상

$$
S:P_n \to P_{n+1},\qquad p(x)\mapsto xp(x)
$$

에 대응되는 행렬을 구하라.

::: 

</div>

::: {.solution}

$$
\begin{aligned}
D(a_0,\ldots,\,a_n)&=(a_1,\, 2a_2,\cdots,\,na_n,\,0)\\
S(a_0,\ldots,\,a_n)&= (0,\,a_0,\,a_1,\ldots,\,a_n)
\end{aligned}
$$

이므로

$$
D=\begin{pmatrix} 0 & 1 & 0 & 0 & \cdots & 0 & 0\\0 & 0 & 2 & 0 & \cdots & 0 & 0 \\
0 & 0 & 0 & 3 & \cdots & 0 & 0 \\ & & & \vdots  &\\0& 0 & 0 & 0 & \cdots & 0 & n \\ 0 & 0 & 0& 0 & \cdots & 0 & 0\end{pmatrix} \,\qquad S=\begin{pmatrix} 0 & 0 & 0 & \cdots & 0& 0\\ 1 & 0 & 0 &\cdots & 0 & 0 \\
0 & 1 & 0 & \cdots & 0 & 0 \\ 0 & 0 & 1 & \cdots & 0 & 0 \\
&&&\vdots \\
0&0&0&\cdots&1 & 0\\
0 & 0 & 0 & \cdots & 0 & 1\end{pmatrix}
$$
이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_2_8}

$m \times n$ 행렬 $A,\,B$ 가 임의의 $n \times l$ 행렬 $X$ 에 대하여 $AX=BX$ 이면 $A=B$ 임을 보이라.

::: 

</div>

::: {.solution}

@exr-CAL_6_1_7 에 정의된 $E_{ij}\in \mathbb{R}^{n\times l}$ 을 생각하자. $E_{ij}$ 는 $(i,\,j)$ 항만 $1$ 이고 나머지는 $0$ 인 행렬이다. $X=E_{ij}$ 이면

$$
(AX)_{pq}=(AE_{ij})_{pq}=\sum_{r=1}^n A_{pr}(E_{ij})_{rq}=\sum_{r=1}^nA_{pr}\delta_{ir}\delta_{jq}=A_{pi}\delta_{jq}
$$

이므로 $AE_{ij}$ 의 $j$-th column 은 $A$ 의 $i$-th column 이며 나머지는 $0$ 이다. $AE_{ij}=BE_{ij}$ 이므로 $A$ 의 $i$-th column 과 $B$ 의 $i$-th column이 같다는 것을 확인 할 수 있으며 $i$ 를 $1$ 부터 $n$ 까지 변화시키면 $A$ 와 $B$ 의 모든 column 이 같음을 확인 할 수 있다. 따라서 $A=B$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_2_9}

삼차원의 공간에서 벡터 $(1,\,2,\,3)$ 에 대한 정사영을 나타내는 행력을 구하라.

:::

</div>

::: {.solution}

$X=(x,\,y,\,z)$ 의 $\bf{a}=(1,\,2,\,3)$ 에 대한 정사영 $P$ 는 정리 3.1.1 에 의해,

$$
P(X)=\dfrac{X \cdot \bf{a}}{\bf{a}\cdot \bf{a}}\bf{a}=\dfrac{x+2y+3z}{14}(1,\,2,\,3)
$$

이므로 이를 행렬 $P$ 로 나타내면,

$$
P =\dfrac{1}{14}\begin{pmatrix} 1 & 2 & 3 \\ 2 & 4 & 6 \\ 3 & 6 & 9\end{pmatrix}
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_2_10}

행렬 $\begin{pmatrix} 1 & 1 & 1\\ 1 & 1 & 1 \\ 1 & 1 & 1\end{pmatrix}$ 로 표현되는 선형변환의 기하학적 의미를 설명하라.

:::

</div>

::: {.solution}

$$
(x,\,y,\,z) \mapsto (x+y+z,\, x+y+z,\, x+y+z)
$$

이다.

:::

</br>

## 부록 : 등장변환과 행렬의 극한

### 등장변환

변환 $T:\mathbb{R}^n \to \mathbb{R}^n$ 이

$$
|T(X)-T(Y)|=|X-Y| \qquad (X,\,Y \in \mathbb{R}^n)
$$

를 만족시키면 $T$ 를 등장변환이라고 한다.

</br>

### 정리 3.1.2

변환 $T:\mathbb{R}^n \to \mathbb{R}^n$ 이 원점을 보존하는 등장변환이면, 임의의 $X,\,Y\in \mathbb{R}^n$ 에 대하여 (여기서 $T(X)$ 를 $TX$ 로 쓰기로 하자.)

&emsp;($1$) $|TX|=|X|$

&emsp;($2$) $TX\cdot TY=X \cdot Y$

&emsp;($3$) $T(aX+bY)=aTX+bTY \qquad (a,\,b\in \mathbb{R})$

가 성립한다. 특히 원점을 보존하는 등장변환은 선형변환이다.

::: {.proor}

($1$) 등장변환이면 $|TX-TY|=|X-Y|$  이며 $T$ 가 원점을 보존하는 선형변환이므로 $Y=0$ 에 대해 $T(Y)=0$ 이다. 따라서 $|TX|=|X|$

($2$) $|TX-TY|=|X-Y|\implies |TX-TY|^2=|X-Y|^2 \implies TX\cdot TY=X\cdot Y$

($3$) 임의의 $Z\in \mathbb{R}^n$ 에 대해

$$
\begin{aligned}
|TZ-aTX&-bTY|^2 = |TZ|^2+a^2|TX|^2+b^2|TY|^2-2a(TZ\cdot TX) \\[0.3em]
&\qquad\qquad -2b(TZ \cdot TY)+2ab(TX\cdot TY)\\
&= |Z|^2+a^2|X|^2+|Y|^2-2a(Z\cdot X)-2b(Z\cdot Y)+2ab(X \cdot Y)\\
&=|Z-aX-bY|^2
\end{aligned}
$$

을 얻는다. $Z=aX+bY$ 라 하면 $|T(aX+bY)-aTX-bTY|^2=0$ 이므로 $T(aX+bY)=aTY+bTY$ 이다. $\square$

:::


</br>

### 정리 3.1.3

$n$ 차 정사각행렬 $A$ 로 부터 얻은 $n$-공간의 선형변환 $L_A$ 가 등장변환일 필요충분조건은

$$
A^tA=I
$$

이다.

::: {.proof} 

($1$) $L_A$ 가 등장변환이라 가정하자. 임의의 $X,\,Y\in \mathbb{R}^n$ 에 대해 정리 3.1.2 (2) 를 사용한다면,

$$
X \cdot Y = AX \cdot AY =(AX)^t AY=X^tA^tAY
$$

이다.

($2$) $A^tA=I$ 임을 가정한다. 임의의 $X\in \mathbb{R}^n$ 에 대해,

$$
|X|^2=X\cdot X = X^tX= X^tA^tAX=(AX)^tAX=(AX)\cdot (AX)=|AX|^2
$$

이다. 따라서 $|X|=|AX|$ 이므로, 임의의 $X,\,Y\in \mathbb{R}^n$ 에 대해,

$$
ㅣL_A(X)-L_A(Y)|=|AX-AY|=|A(X-Y)|=|X-Y|
$$

이므로 $L_A$ 는 등장변환이다.

:::

</br>

### 직교행렬 (Orthogonal matrix)과 직교변환

정사각행렬 $A$ 가 $A^tA=I$ 를 만족할 때 $A$ 를 직교행렬이라고 부른다. 직교행렬에 의한 변환을 직교변환이라고 한다.

</br>

### 직교행렬과 정규직교기저

$n \times n$ 행렬 $A$ 가 직교행렬이면 $A$ 의 각 열벡터는 $n$ 공간의 정규직교기저를 이룬다.

::: {.proof} 

$A$ 행렬의 $i$-th column 을 $A_i$ 라 하고 $A=(A_1,\ldots,\,A_n)$ 이라 쓸 수 있다. 이 때, $(A^tA)_{ij}=A_i \cdot A_j = \delta_{ij}$ 이므로 $A$ 의 각 열벡터는 정규직교공간의 기저이다.
:::

</br>

### 따름정리 3.1.4

$n$ 공간의 등장변환은 직교변환과 평행이동의 합성으로 이루어진다.

::: {.proof} 

$T:\mathbb{R}^n \to \mathbb{R}^n$ 이 등장변환이면

$$
L(X):=T(X)-T(O)
$$

은 원점을 보존한다. 임의의 $X,\,Y\in \mathbb{R}^n$ 에 대해,

$$
|L(X)-L(Y)|=|T(X)-T(O)-T(Y)+T(O)|=|T(X)-T(Y)|=|X-Y|
$$

이므로 등장변환이다. $L$ 은 원점을 보존하는 등장변환이며 따라서 정리 3.1.2에 의해 선형변환므로 정리 3.1.3에 의해 직교변환이다.

$$
T(X)=L(X)+T(O)
$$

이므로 등장변환은 직교변환과 평행이동의 함성이다.

:::

</br>

### 행렬의 극한

$m\times n$ 행렬 $A=(a_{ij})$ 의 크기, 혹은 절대값을 $|A|$ 라 쓰고 다음과 같이 정의하자.

$$
|A|:=\sqrt{\sum_{i=1}^m \sum_{j=1}^n {a_{ij}}^2}
$$

</br>

#### 정리 3.3.2

$m \times n$ 행렬 $A$ 와 $n \times l$ 행렬 $B$ 에 대하여,

$$
|AB|\le |A|\cdot |B|
$$

가 성립한다. 특히 $A$ 가 정사각행렬이면,

$$
\left|A^k \right|\le |A|^k \qquad (k=1,\,2,\,3,\ldots)
$$

가 성립한다.

::: {.proof}

$$
\begin{aligned}
|AB|^2 &= \sum_{i=1}^m \sum_{j=1}^l \left(\sum_{k=1}^n a_{ik}b_{kj}\right)^2 \\
&\le \sum_{i=1}^m \sum_{j=1}^l \left(\sum_{k=1}^n a_{ik}^2\right)\left(\sum_{k=1}^n b_{kj}^2\right) \\
&=\left(\sum_{i=1}^m\sum_{k=1}^{n}a_{ik}^2
\right)\left(\sum_{j=1}^l\sum_{k=1}^{n}b_{kj}^2 \right)\\
&=|A|^2|B|^2
\end{aligned}
$$

:::

</br>

#### 정리 3.3.3

$m\times n$ 행렬의 수열 $A(k),\,k=1,\,2,\,3,\ldots$ 이 행렬 $B$ 에 수렴할 필요충분조건은

$$
\lim_{k \to \infty} |A(k)-B|=0
$$

이다.

::: {.proof}

$M=m\times n$ 라 하자. 만약 $A(k)$ 가 $B$ 에 수렴한다고 가정한다면 $A(k)$ 의 각 항이 해당하는 $B$ 각 항에 수렴하는 것이므로, 주어진 $\epsilon>0$에 대해 $n\ge N_{ij}\implies \left| (A(k))_{ij}-B_{ij} \right|\le \dfrac{\epsilon}{M}$ 를 만족하는 $N_{ij}$ 가 존재한다.  $N:=\max\{N_{ij}: 1\le i,\,j \le n\}$ 이라 하면

$$
n\ge N \implies  \left| (A(k))_{ij}-B_{ij} \right|\le \dfrac{\epsilon}{M} \quad \forall i,\,j=1,\ldots,\,n
$$

이다. 그렇다면, $n\ge N$ 일 때

$$
|A(k)-B|= \sqrt{\sum_{i,\,j} \left(A(k)_{ij}-B_{ij}\right)^2}\le \sqrt{\sum_{i,\,j} \dfrac{\epsilon^2}{M^2}}=\dfrac{\epsilon}{\sqrt{M}}\le \epsilon
$$

이므로 $\displaystyle \lim_{k \to \infty} |A(k)-B|=0$ 이다.

이제 $\displaystyle \lim_{k \to \infty} |A(k)-B|=0$ 임을 가정하자. 임의의 행렬 $C$ 에 대해 $|C|\le \max\{C_{ij}\}$ 이므로 $|A(k)_{ij}-B_{ij}|\le |A(k)-B|$ 이며 따라서,

$$
\lim_{k \to \infty}|A(k)_{ij}-B_{ij}|=0
$$

이다. 따라서 행렬 $A(k)$ 는 $B$ 로 수렴한다.

:::

</br>

### 행렬 급수의 수렴

$m\times n$ 행렬의 급수 $\displaystyle \sum_{k=0}^\infty A(k)$ 가 행렬 $B$ 에 수렴한다는 것은 유한합으로 이루어진 행렬의 수열 $\displaystyle \sum_{k=0}^n A(k),\quad n=0,\,1,\,2,\ldots$ 가 $B$ 에 수렴한다는 뜻이다. 이 때 $\displaystyle \sum_{k=0}^\infty A(k)=B$ 로 쓰기로 한다.

</br>

#### 정리 3.4.2

임의의 정사각행렬 $A$ 에 대하여 급수

$$
I+A+\dfrac{1}{2!}A^2+ \dfrac{1}{3!}A^3 + \cdots + \dfrac{1}{k!}A^k + \cdots
$$

는 항상 수렴한다. 이 때 극한값을 $\exp A$ 또는 $e^A$ 로 쓴다.

::: {.proof}

($1$) $a=\max\{|A_{ij}|: 1\le i,\,j \le n\}$ 라 하면 $|A| \le na$ 이다. 또한 정리 3.3.2 에 의해 $|A^k_{ij}|\le |A^k|\le |A|^k \le n^k a^k$ 이다.

($2$) 따라서 $B=I+A+\dfrac{1}{2!}A^2+\cdots $ 라 했을 때 $|B_{ij}|\le 1+na+\dfrac{n^2a^2}{2!}+\dfrac{n^3a^3}{3!}+\cdots = e^{na} $ 이다.

:::

</br>

## 연습문제 : 제 6장 3절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_1}

차수가 같은 두 직교행렬의 곱은 직교행렬임을 보여라.

::: 

</div>

::: {.solution}

$A,\,B\in \mathbb{R}^{n \times n}$ 이 직교행렬이라 하자. $(AB)^t(AB)=B^tA^tA^B=B^tB=I$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_2}

영이 아닌 벡터 $X\in \mathbb{R}^n$ 에 대하여 $n \times n$ 행렬

$$
A:=I_n-\dfrac{2}{|X|^2}XX^t
$$

는 직교행렬임을 보이라.

:::

</div>

::: {.solution}

우리는 임의의 $n\times n$ 행렬 $P,\,Q$ 와 $c\in \mathbb{R}$ 에 대해 다음이 성립함을 안다.

$$
\begin{aligned}
(P+cQ)^t&=P^t+cQ^t
\end{aligned}
$$

따라서,

$$
A^t = (I_n)^t-\dfrac{2}{|X|^2}(XX^t)^t = I_n -\dfrac{2}{|X|^2}XX^t=A
$$

이며, $X^tX=|X|^2$ 임을 이용한다.

$$
\begin{aligned}
A^tA &= A^2=\left(I_n - \dfrac{2}{|X|^2}XX^t\right)^2\\
&= I_n - \dfrac{4}{|X|^2}XX^t+ \dfrac{4}{|X|^2}XX^tXX^t \\
&=I_n - \dfrac{4}{|X|^2}XX^t+\dfrac{4}{|X|^2}|X|^2XX^t\\
&=I_n
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_3}

좌표평면의 점들을 원점 주위로 크기 $\alpha$ 만큼 회전시키는 변환을 한 다음, 다시 각의 크기 $\beta$ 만큼 회전시키는 변환은, 각의 크기 $\alpha+\beta$ 만큼 회전시키는 변환과 같음을 이용하여,

$$
\begin{aligned}
\cos (\alpha+\beta)& =\cos \alpha \, \cos \beta -\sin \alpha\sin \beta\\
\cos (\alpha+\beta)& =\sin \alpha \cos \beta + \cos \alpha \sin \beta
\end{aligned}
$$
를 유도하라.

:::

</div>

::: {.solution}

$\mathbb{R}^2$ 에서 $\theta$ 만큼 회전 시키는 변화를 나타내는 행렬 $R_\theta = \begin{pmatrix} \cos \theta & -\sin \theta \\ \sin \theta & \cos \theta \end{pmatrix}$ 이다. 따라서,

$$
\begin{aligned}
&\begin{pmatrix} \cos (\alpha+\beta) & - \sin (\alpha+\beta) \\ \sin (\alpha+\beta) & \cos (\alpha + \beta)  \end{pmatrix} = \begin{pmatrix} \cos \beta & -\sin \beta \\ \sin \beta & \cos \beta \end{pmatrix} \begin{pmatrix} \cos \alpha & -\sin \alpha \\ \sin \alpha & \cos \alpha \end{pmatrix} \\[0.3em]
&\qquad\qquad = \begin{pmatrix} \cos \alpha\cos \beta - \sin \alpha \sin \beta & -\sin \alpha \cos \beta - \cos \alpha \sin \alpha \\ \sin \alpha \cos \beta + \cos \alpha \sin \alpha  & \cos \alpha\cos \beta - \sin \alpha \sin \beta \end{pmatrix}
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_4}
 삼차원 공간에서 회전변환 $R_1,\,R_2,\,R_3$ 가 다음 관계를 가짐을 보여라.

$$
R_1 \left(-\dfrac{\pi}{2}\right)\circ R_3 (\theta) \circ R_1\left(\dfrac{\pi}{2}\right)=R_2(\theta)
$$

:::

</div>

::: {.solution}

$$
\begin{aligned}
R_1 \left(-\dfrac{\pi}{2}\right)\circ R_3 (\theta) \circ R_1\left(\dfrac{\pi}{2}\right)& = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 0 & 1 \\ 0 & -1 & 0\end{pmatrix} \begin{pmatrix} \cos \theta & - \sin \theta & 0 \\\sin \theta & \cos \theta& 0 \\ 0 & 0 & 1\end{pmatrix} \begin{pmatrix} 1 & 0 & 0 \\ 0 & 0 & -1 \\ 0 & 1 & 0\end{pmatrix} \\
&= \begin{pmatrix} \cos \theta & -\sin \theta & 0 \\ 0 & 0 & 1 \\ - \sin \theta & - \cos \theta & 0\end{pmatrix}\begin{pmatrix} 1 & 0 & 0 \\ 0 & 0 & -1 \\ 0 & 1 & 0\end{pmatrix} \\
&=\begin{pmatrix} \cos \theta & 0 & \sin \theta \\ 0 & 1 & 0 \\ - \sin \theta & 0 & \cos \theta\end{pmatrix}\\
&=R_2(\theta)
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_5}

좌표평면에서 곡선

$$
ax^2+2bxy+cy^2+d=0
$$

을 회전이동하여 얻은 곡선이

$$
a'x^2+2b'xy+c'y^2+d'=0
$$

이라고 하자. 이 때

$$
ac-b^2=a'c'-b'^2
$$

임을 보이라.

::: 

</div>

::: {.solution}

$x\to \cos \theta x-\sin \theta y,\, y \to \sin \theta x + \cos \theta y$ 라 하면,

$$
\begin{aligned}
a'x^2 &+ 2b'xy+c'y^2+d' \\[0.3em]
&= a (\cos \theta x-\sin \theta y)^2 +2b (\cos \theta x-\sin \theta y)(\sin \theta x + \cos \theta y) \\
&\qquad + c(\sin \theta x+\cos \theta y)^2+d\\
& = (a \cos^2 \theta + 2b \cos \theta \sin \theta +c \sin^2 \theta ) x^2 + (-2a\cos \theta \sin \theta + 2b \cos^2 \theta \\[0.3em]
&\qquad - 2b \sin^2 \theta + 2c \sin \theta \cos \theta) xy + (a\sin^2 \theta -2b \sin \theta \cos \theta +c \cos^2 \theta ) y^2 + d'
\end{aligned}
$$

이다. 따라서,

$$
\begin{aligned}
a'c'-b'^2 &= (a \cos ^2 \theta +2b \cos \theta \sin \theta + c\sin ^2 \theta)(a\sin^2 \theta -2b \sin \theta \cos \theta+c\cos ^2 \theta)\\
&\qquad -(-a\cos \theta \sin \theta+b \cos^2\theta-b \sin^2 \theta+c\sin \theta \cos \theta)^2\\
& = ( \cos^2\theta\sin^2\theta-\cos^2\theta\sin^2\theta)a^2 \\[0.3em]
&\qquad + (-4\cos^2\theta \sin^2 \theta-(\cos^2\theta-\sin^2\theta)^2)b^2\\
&\qquad +(\cos^2\theta\sin^2\theta-\cos^2\theta\sin^2\theta)c^2 \\
&\qquad +(-2\cos^3\theta \sin \theta+2\cos\theta\sin^2\theta+2\cos\theta\sin\theta(\cos^2\theta-\sin^2\theta)) ab\\
&\qquad +(2\cos^3\theta \sin\theta-2\cos\theta \sin^3\theta-2\sin\theta\cos\theta(\cos^2\theta-\sin^2\theta))bc\\
&\qquad +(\cos^4\theta+\sin^4\theta+2\sin^2\theta\cos^2\theta)ac\\
&=0\cdot a^2+(-2\sin^22\theta-2\cos^2 2\theta)b^2 + 0\cdot c^2-0\cdot ab+0\cdot bc  \\
&\qquad + (\cos^2\theta+\sin^2\theta)^2ac\\
&=ac-b^2
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_6}

좌표평면에서 두 직선 $ax+by+c_1=0,\, ax+by+c_2=0$ 에 대한 반사변환을 각각 $T_1,\,T_2$ 라고 두자. (단 $a^2+b^2=1$ 이라고 가정한다) 이 때 합성변환 $T_1 \circ T_2$ 는 어떤 변환인가.

::: 

</div>

::: {.solution}

$ax+by+c_2=0$ 의 한 점 $X$에서 $ax+by+c_1=0$ 으로 수선을 내렸을때의 교점을 $Y$ 라 한다면 $\overrightarrow{XY}$ 방향으로 두 직선의 거리의 두배만큼 평행이동 하는 변환이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_7}

포물선 $y=x^2$ 과 $y=2x^2$ 은 닮음 변환임을 보이라.

:::

</div>

::: {.solution}

$x \to 2x$, $y \to 2y$ 변환을 생각하라.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_8}

좌표평면에서 곡선

$$
x^2+4xy+3y^2=1
$$

은 타원, 쌍곡선, 포물선 중 어느 것인지를 판정하라.

:::

</div>

::: {.solution}

$$
x^2+4xy+3y^2=1 \implies (x+2y)^2-y^2=1
$$

이므로 쌍곡선이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_9}

좌표평면의 점 $(x,\,y)$ 를 $x$ 축에 대하여 대칭이동 시키고, 원점을 중심으로 하여 반시계방향으로 $60^\circ$ 회전시킨 다음, 다시 $x$ 축에 대하여 대칭이동시키는 선형사상을 $T$ 라고 두자. 이 사상을 2001회 시행하였을 때, 점 $(1,\,1)$ 의 상을 구하라.

:::

</div>

::: {.solution}

$$
T=\begin{pmatrix} 1 & 0 \\ 0 & -1\end{pmatrix} \begin{pmatrix} 1/2 & -\sqrt{3}/2 \\ \sqrt{3}/2 &1/2 \end{pmatrix}\begin{pmatrix} 1 & 0 \\ 0 & -1\end{pmatrix}=\begin{pmatrix} 1/2 & \sqrt{3}/2 \\ -\sqrt{3}/2 &1/2 \end{pmatrix}
$$

이므로 $T$ 는 시계방향 $60^\circ$ 회전이다. 2001회 시행은 시계방향으로 $180^\circ$ 회전이므로 역시 반시계방향 $180^\circ$ 회전이다. 따라서 (1,1) 의 상은 (-1,-1) 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_1}

#### 오일러 항등식 

임의의 실수 $t$ 에 대하여,

$$
\exp \begin{pmatrix} 0 &-t\\ t & 0\end{pmatrix} = \begin{pmatrix} \cos t & - \sin t \\ \sin t & \cos t\end{pmatrix}
$$

임을 보이라.

:::

</div>

::: {.solution}

$A=\begin{pmatrix} 0 &-t\\ t & 0\end{pmatrix},\, J=\begin{pmatrix} 0 & -1 \\ 1 & 0\end{pmatrix}$ 라 하면, $J^2=-I_2$, $J^3=-J$, $J_4=I$ 이므로

$$
\begin{aligned}
A^k = t^k J^k
\end{aligned}
$$

이다. $\exp A =I+tJ+\dfrac{1}{2}t^2J^2+\cdots + \dfrac{t^k}{k!}J^k+\cdots$ 이므로,

$$
\begin{aligned}
\left(\exp A \right)_{11} &=  (\exp A)_{22}=\sum_{k=0}^\infty \dfrac{(-1)^{k}t^{2k}}{(2k)!}=\cos t,\,\\
\left(\exp A\right)_{21}&=-\left(\exp A\right)_{12}=\sum_{k=0}^\infty \dfrac{(-1)^{k}t^{2k+1}}{(2k+1)!}=\sin t\,.
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_11}

다음을 보이라.

$$
\exp \begin{pmatrix} 0 & t & 0 & 0 \\ 0 & 0 & t & 0 \\ 0 & 0 & 0 & t \\ 0 & 0 & 0 & 0\end{pmatrix} = \begin{pmatrix} 1 & t & \dfrac{t^2}{2} & \dfrac{t^3}{3!} \\ 0 & 1 & t & \dfrac{t^2}{2} \\ 0 & 0 & 1 & t \\ 0 & 0 & 0 & 1\end{pmatrix}
$$

:::

</div>

::: {.solution}

$$
A=\begin{pmatrix} 0 & t & 0 & 0 \\ 0 & 0 & t & 0 \\ 0 & 0 & 0 & t \\ 0 & 0 & 0 & 0\end{pmatrix}
$$ 

라 하면, 

$$
A^2= \begin{pmatrix} 0 & 0& t^2 & 0 \\ 0 & 0 & 0 & t^2 \\ 0 & 0 & 0 & t \\ 0 & 0 & 0 & 0\end{pmatrix} ,\, A^3 = \begin{pmatrix} 0 & 0 & 0 & t^3 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0\end{pmatrix} ,\, A^4=0
$$ 

이므로 $k\ge 4$ 이면 $A^k=0$ 이다. 따라서,

$$
\exp A= I+A+\dfrac{1}{2}A^2+\dfrac{1}{3}A^3
$$

이므로 주어진 식을 만족함을 쉽게 보일 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_3_12}

행렬 $\sigma_0 :=\begin{pmatrix}  1 & 0 \\ 0 & -1\end{pmatrix}$ 에 대하여,

$$
e^{t\sigma_0} \begin{pmatrix} a& b \\ c & d\end{pmatrix}e^{-t\sigma_0}=\begin{pmatrix}  a & e^{2t}b \\ e^{-2t}c &d\end{pmatrix}
$$

임을 보이고, 이 식을 미분하여

$$
\left[\sigma_0,\, \begin{pmatrix} a & b \\ c & d \end{pmatrix}\right]=2\begin{pmatrix}   0 & b \\ -c & 0\end{pmatrix}
$$

임을 보이라.

:::

</div>

::: {.solution}

($1$) $\sigma_0^2=I$ 이므로,

$$
\begin{aligned}
\left(e^{t\sigma_0}\right)_{11}&=1+t+\dfrac{t^2}{2!}+\dfrac{t^3}{3!}+\cdots =e^{t}\\
\left(e^{t\sigma_0}\right)_{22}&=1-t+\dfrac{t^2}{2!}-\dfrac{t^3}{3!}+\cdots =e^{-t}\\
\left(e^{t\sigma_0}\right)_{21}&=\left(e^{t\sigma_0}\right)_{12}=0\\
\left(e^{-t\sigma_0}\right)_{11}&=1-t+\dfrac{t^2}{2!}-\dfrac{t^3}{3!}+\cdots =e^{-t}\\
\left(e^{-t\sigma_0}\right)_{22}&=1+t+\dfrac{t^2}{2!}+\dfrac{t^3}{3!}+\cdots =e^{t}\\
\left(e^{-t\sigma_0}\right)_{21}&=\left(e^{-t\sigma_0}\right)_{12}=0
\end{aligned}
$$

이다. 따라서

$$
e^{t\sigma_0} \begin{pmatrix} a& b \\ c & d\end{pmatrix}e^{-t\sigma_0}=\begin{pmatrix} e^t & 0 \\ 0 & e^{-t}\end{pmatrix} \begin{pmatrix}a & b \\ c & d\end{pmatrix}\begin{pmatrix} e^{-t} & 0 \\ 0 & e^{t}\end{pmatrix}  = \begin{pmatrix} a & e^{2t}b \\ e^{-2t}c & d\end{pmatrix}
$$

이다.

($2$) 행렬함수 $A(t)=(a_{ij}(t))$ 의 미분은 $A'(t)=(a_{ij}'(t))$ 로 정의된다. 그렇다면 $e^{At}$ 의 미분은?

$$
\begin{aligned}
& \left(e^{At}\right)_{ij}=\sum_{k=0}^\infty \dfrac{(A^k)_{ij}t^k}{k!} \\
\implies & \dfrac{d}{dt}\left(e^{At}\right)_{ij} =\sum_{k=0}^\infty\dfrac{(A^k)_{ij}t^{k-1}}{(k-1)!}=\sum_{l=0}^n A_{il} \left(\sum_{k=0}^\infty \dfrac{A^{k-1}_{lj} t^{k-1}}{(k-1)!} \right) = \sum_{l=0}^n A_{il} \left(e^{^{At}}\right)_{lj}=\left(Ae^{At}\right)_{ij}
\end{aligned}
$$

이다.  또한 행렬함수 $A(t),\,B(t)$ 가 행렬곱이 가능할 때 $A(t)B(t)$ 의 미분은,

$$
\begin{aligned}
\dfrac{d}{dt}\left(A(t)B(t)\right)_{ij} &= \dfrac{d}{dt}\sum_{l}A_{il}(t)B_{lj}(t) \\
& = \sum_l A'_{il}(t)B_{lj}(t)+A_{il}(t)B'_{lj}(t) \\
&= \left(A'(t)B(t)+A(t)B'(t)\right)_{ij}
\end{aligned}
$$
이다. 또한
$$
\sigma_0 e^{t\sigma_0}=\sigma_0 \sum_{k} \dfrac{\sigma_0^k t^k}{k!}=\sum_{k}\dfrac{\sigma_0^k t^k}{k!}\sigma_0 = e^{t\sigma_0}\sigma_0
$$
이므로, 이를 이용하여 문제의 식의 좌 우변을 미분한 후 $t=0$ 을 취하면,
$$
\begin{aligned}
\dfrac{d}{dt} \left[e^{t\sigma_0} \begin{pmatrix} a& b \\ c & d\end{pmatrix}e^{-t\sigma_0}\right] &=\sigma_0 e^{t\sigma_0} \begin{pmatrix} a& b \\ c & d\end{pmatrix}e^{-t\sigma_0}-e^{t\sigma_0} \begin{pmatrix} a& b \\ c & d\end{pmatrix}\sigma_0e^{-t\sigma_0}\,,\\
\dfrac{d}{dt} \left[e^{t\sigma_0} \begin{pmatrix} a& b \\ c & d\end{pmatrix}e^{-t\sigma_0}\right]_{t=0} &=\sigma_0 \begin{pmatrix} a& b \\ c & d\end{pmatrix}-\begin{pmatrix} a& b \\ c & d\end{pmatrix}\sigma_0 =\left[\sigma_0,\,\begin{pmatrix} a& b \\ c & d\end{pmatrix}\right] \\
\dfrac{d}{dt}\begin{pmatrix} a & e^{2t}b \\ e^{-2t}c & d\end{pmatrix} &=\begin{pmatrix} 0 & 2e^{2t}b \\ -2e^{-2t}c & 0\end{pmatrix} \\
\dfrac{d}{dt}\begin{pmatrix} a & e^{2t}b \\ e^{-2t}c & d\end{pmatrix}_{t=0} &= 2\begin{pmatrix} 0 & b\\ -c & 0\end{pmatrix}
\end{aligned}
$$

:::

</br>

## 제 6장 탐구문제

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S01}

다항식 $p(x),\,q(x),\,r(x)$ 에 대하여 $p(x)=q(x)r(x)$ 이면, 임의의 정사각행렬 $A$ 에 대하여 $p(A)=q(A)r(A)$ 가 성립함을 보이라.

:::

</div>

::: {.solution}

우리는 임의의 정사각 행렬 $A$ 와 실수 $a,\,b$ , 자연수 $n,\,m$ 에 대해 $\left(aA^n \right)\left(bA^m\right)=abA^{n+m}$ 임을 안다.

$\displaystyle p(x)=\sum_{k=0}^{n_p}p_kx^k,\, q(x) =\sum_{k=0}^{n_q}q_k x^k,\, r(x)=\sum_{k=0}^{n_r} r_k x^k$ 라 하자. $p(x)=q(x)r(x)$ 이므로,

$$
p_k = \sum_{i=0}^k q_ir_{k-i}
$$

이제,

$$
\begin{aligned}
q(A)r(A) & =\left(\sum_{i=0}^{n_q}q_i A^i\right) \left(\sum_{j=0}^{n_r} r_j A^{j}\right) \\
&= \sum_{i=0}^{n_p}\sum_{j=0}^{n_r} q_ir_j A^{i+j} \\
&= \sum_{k=0}^{n_p}\sum_{l=0}^k q_{l}r_{k-l}A^k \\
&=\sum_{k=0}^{n_p} p_kA^k =p(A)
\end{aligned}
$$
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S02}

$m \times n$ 행렬 $A$ 와 $n \times l$ 행렬 $B$ 에 대하여, $B$ 의 각 열벡터를 차례로 $B_1,\ldots,\,B_l$ 이라고 두자. 이 때 $AB$ 의 각 열벡터는 $AB_1,\ldots,\,AB_l$ 임을 보이라. 또 $A$ 의 각 행벡터를 $A_{(1)},\ldots,\,A_{(m)}$ 으로 두면, $AB$ 의 각 행벡터는 $A_{(1)}B ,\ldots,\,A_{(m)}B$ 임을 보이라.

:::

</div>

::: {.solution}

$\widehat{e}_i$ 는 $n \times 1$ 열백터로 $i$ 번째 성분만 $1$ 이고 나머지는 $0$ 인 벡터라고 하자. $\widehat{f}_j$ 는 $1\times n$ 행백터로 $j$ 번째 성분만 $1$ 이고 나머지는 $0$ 인 벡터라고 하자. 그렇다면,
$$
B_i = B\widehat{e}_i ,\qquad A_{(j)}=\widehat{f}_j A
$$
이다.
$$
(AB)_{i}=(AB)\widehat{e}_i=A(B\widehat{e}_i)=AB_i,\qquad (AB)_{(j)}=\widehat{f}_j (AB)=(\widehat{f}_j A)B=A_{(j)}B
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S03}

$m\times n$ 행렬 $A$ 와 $n \times l$ 행렬 $B$ 에 대하여, $AB$ 의 각 행벡터는 $B$ 의 행벡터들의 일차결합임을 보이라. 또 $AB$ 의 각 열벡터는 $A$ 의 열벡터들의 일차결합임을 보이라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
(AB)_{(i)}&=A_{(i)}B= (a_{i1}\,a_{i2}\cdots \, a_{in})\begin{pmatrix} B_{(1)}\\
B_{(2)}\\
\vdots \\B_{(n)}\end{pmatrix}=a_{i1}B_{(1)}+ \cdots + a_{in}B_{(n)} \\
(AB)_{j} &= AB_i = \begin{pmatrix}A_1\, A_2 \, \cdots A_n\end{pmatrix} \begin{pmatrix}b_{j1}\\ b_{j2} \\ \vdots  \\b_{jn}\end{pmatrix} =b_{j1}A_1 + \cdots+b_{jn}A_n
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S04}

$m \times n$ 행렬 $A$ 의 열벡터 $A_1,\ldots,\,A_n$ 이 일차종속이면 $A\bf{v}=0$ 이 되는 영이 아닌 $n$ 벡터 $\bf{v}$ 가 존재함을 보이라. 또 이 명제의 역이 성립함을 보이라.

:::

</div>

::: {.solution}

$A_1,\ldots,\,A_n$ 이 일차종속이면 $v_1A_1+\cdots +v_nA_n=0$ 을 만족시키는 nontrivial $v_1,\ldots,\,v_n$ 이 존재한다. 즉 $v_1,\ldots,\,v_n$ 중 최소한 하나는 $0$ 이 아니다. $\bf{v}=(v_1,\ldots,\,v_n)$ 이라 하면  $\displaystyle A\bf{v}=\sum_{i=1}^n A_i v_i=0$ 이 된다.

역으로  $A\bf{v}=0$ 이 되는 영이 아닌 $n$ 벡터 $\bf{v}$ 가 존재한다면 $\bf{v}=(v_1,\ldots,\,v_n)$ 일 때 $\displaystyle A\bf{v}=\sum_{i=1}^n v_iA_i=0$ 이므로 $A_1,\ldots,\,A_n$ 은 일차종속이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S05}

자연수 $m_1,\,m_2,\,n_1,\,n_2,\,l_1,\,l_2$ 에 대하여 $m=m_1+m_2,\, n=n_1+n_2,\,l=l_1+l_2$ 라고 두자. 이제 $m \times n$ 행력 $A$ 와 $n \times l$ 행렬 $B$ 를 $m_i\times n_j$ 행렬 $A_{ij}$ 와 $n_j\times l_k$ 행렬 $B_{jk}$ 로 분해하여,

$$
A=\begin{pmatrix}A_{11} & A_{12}\\ A_{21} & A_{22}\end{pmatrix},\qquad B=\begin{pmatrix} B_{11} & B_{12} \\ B_{21} & B_{22}\end{pmatrix}
$$

로 두면

$$
AB=\begin{pmatrix} A_{11}B_{11} + A_{12}B_{21} &  A_{11}B_{12} + A_{12} B_{22} \\ A_{21}B_{11}+A_{22}B_{21} & A_{21}B_{12} + A_{22}B_{22}\end{pmatrix}
$$

임을 보이라.

:::

</div>

::: {.solution}

$1\le i\le n_1,\, 1\le j\le l_1$ 에서의 $(AB)_{ij}$ 를 보자.

$$
\begin{aligned}
(AB)_{ij} &= \sum_{k=1}^{n_1+n_2}A_{ik}B_{kj}=\sum_{k=1}^{n_1}A_{ik}B_{kj} +\sum_{k=n_1+1}^{n_1+n_2} A_{ik}B_{kj}\\[0.3em]
&=\sum_{k=1}^{n_1}(A_{11})_{ik}(B_{11})_{kj}+\sum_{k=1}^{n_2}(A_{12})_{ik}(B_{21})_{kj}
\end{aligned}
$$

이므로 $1\le i\le n_1,\, 1\le j\le l_1$ 에서의 $AB=A_{11}B_{11}+A_{12}B_{21}$ 이다.

이렇게 계속 확인해가면 답을 보일 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S06}

$n$ 차 정사각행렬 $A$ 가 임의의 정사각행렬 $B$ 에 대하여 $AB=BA$ 이면 $A$ 는 항등행렬의 상수배임을 보이라.

:::

</div>

::: {.solution}

$n$차 정사각행렬 $E_{ij}$ 를 $(i,\,j)$ 항만 $1$ 이고 나머지 항은 $0$ 인 행렬로 정의하자.  $AE_{ij}=C$ 라 하면 $C$ 는 $j$ 번째 열이 $A$ 의 $i$ 번째 열과 같으며 나머지 열은 $0$ 인 행렬이다. $E_{ij}A=D$ 라 하면 $D$ 의 $i$ 번째 행이 $A$ 의 $j$ 번째 행과 같고 나머지 행은 $0$ 인 행렬이다.

$AE_{11}=E_{11}A$ 이므로 $A_{11}$ 을 제외한 나머지 $A_{j1}$ 과  $A_{1i}$ 도 $0$ 이다. 이것을 $AE_{ii}=E_{ii}A$ $i=1,\,2,\ldots,\,n$ 까지 계속 해 나가면 행렬 $A$ 는 대각성분을 제외한 성분이 $0$ 임을 알 수 있다.

$AE_{12}=E_{12}A$ 이므로 $A_{11}=A_{22}$ 이다. 이것을 $AE_{1j}=E_{1j}A$ 에서 반복하면 $A_{11}=A_{22}=\cdots =A_{nn}$ 임을 알 수 있다. 따라서 $A$ 는 항등행렬의 상수배이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S07}

대각선이 $(a_1,\ldots,\,a_n)$ 인 정사각행렬과 반대각선이 $(b_1,\ldots,\,b_n)$ 인 정사각행렬을 각각 $D_{a_1,\ldots,\,a_n}$ 과 $E_{b_1,\ldots,\,b_n}$ 으로 나타내기로 하자. 이 대 다음을 보이라.

$$
\begin{aligned}
D_{a_1,\ldots,\,a_n} E_{b_1,\ldots,\,b_n} &= E_{a_1b_1,\ldots,\,a_nb_n}\\[0.3em]
E_{b_1,\ldots,\,b_n}E_{c_1,\ldots,\,c_n}&= D_{b_1c_n,\, b_2c_{n-1},\ldots,\,b_nc_1}
\end{aligned}
$$

:::

</div>

::: {.solution}

$\left(D_{a_1,\ldots,\,a_n}\right)_{ij}=a_i\delta_{ij}$ 이며 $(E_{b_1,\ldots,\,b_n})_{ij}=b_i \delta_{i,n-j+1}$ 이다. 역시 $\delta_{ij}$ 는 크로네커델타함수 이다.

$$
\begin{aligned}
\left(D_{a_1,\ldots,\,a_n}E_{b_1,\ldots,\,b_n}\right)_{ij}&=\sum_{k=1}^n \left(D_{a_1,\ldots,\,a_n}\right)_{ik}\left(E_{b_1,\ldots,\,b_n}\right)_{kj} \\
&=\sum_{k=1}^n a_i \delta_{ik}b_k\delta_{k,\, n-j+1}=a_ib_i\delta_{i,\,n-j+1} \\
& = \left(E_{a_1b_1,\ldots,\,a_nb_n}\right)_{ij}\\
\left(E_{b_1,\ldots,\,b_n}E_{c_1,\ldots,\,c_n}\right)_{ij} & = \sum_{i=1} \left(E_{b_1,\ldots,\,b_n}\right)_{ik}\left(E_{c_1,\ldots,\,c_n}\right)_{kj} \\
&=\sum_{k=1} b_i\delta_{i,\, n-k+1}c_k\delta_{k,\,n-j+1}\\
&=b_i c_{n-j+1}\delta_{ij}=(E_{b_1c_{n},\, b_2c_{n-1}\ldots,\,b_nc_1})
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S08}

$m\times n$ 행렬 $A$ 와 $B$ 에 대하여

$$
|\operatorname{tr} (A^tB)| \le |A|\cdot |B|
$$
임을 보이라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
|A|\cdot |B| &= \sqrt{\sum_{j=1}^n\sum_{i=1}^m (A_{ij})^2}  \sqrt{\sum_{j=1}^n\sum_{i=1}^m (B_{ij})^2}  \\[0.3em]
&\le\left|\sum_{j=1}^n \sum_{i=1}^m A_{ij}B_{ij}\right|= \left|\sum_{j=1}^n \sum_{i=1}^m (A^t)_{ji}B_{ij}\right|=\left|\operatorname{tr}(A^tB)\right|
\end{aligned}
$$

중간의 부등호는 코시-슈바르츠 부등식.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S9}

단사인 선형사상에 대하여 일차독립인 벡터들의 상은 여전히 일차독립임을 보이라.

:::

</div>

::: {.solution}

벡터공간 $V,\,U$ 에 대해  $T:U \to V$ 가 단사인 선형사상이며, $\bf{u}_1,\ldots,\bf{u}_n$ 이 $U$의 일차독립인 벡터라 하자.

$$
\begin{aligned}
c_1T(\bf{u_1})+ c_2T(\bf{u}_2)+\cdots + c_n T(\bf{u}_n)=0 \implies T(c_1\bf{u}_1 + \cdots +c_n \bf{u}_n)=0
\end{aligned}
$$

이며  $T$ 가 단사인 선형사상이므로  $c_1\bf{u}_1 + \cdots +c_n \bf{u}_n=0$ 이다. $\bf{u}_1,\ldots,\,\bf{u}_n$ 이 일차독립인 벡터이므로  $c_1=\cdots =c_n=0$. 따라서 $T(\bf{u}_1),\ldots,\,T(\bf{u}_n)$ 은 $V$ 에서의 일차독립이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S10}

단사인 선형사상에 의한 직선의 상은 직선임을 보이라.

:::

</div>

::: {.solution}

$n$-공간에서 직선은 $x_i = a_it+b_i$ for $i=1,\ldots,n$ 로 표현된다. 선형사상에 의해  $x'_i = \sum_{j=1}^n T_{ij}x_j$ 일 때,

$$
x_i'=\sum_{j=1}^n T_{ij} x_j = \sum_{j=1}^n (a_jt+b_j)=\left(\sum_{j=1}^n T_{ij}a_j\right) t+\left(\sum_{j=1}^n T_{ij}b_j\right)
$$

이므로 직선이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S11}

선형변환  $L:\mathbb{R}^n \to \mathbb{R}^n$ 이 단사일 필요충분조건은  $L$ 이 전사임을 보이라.

:::

</div>

::: {.solution}

우리는 연습문제 제 6장 2절 4번에서 선형사상이 단사일 필요충분조건은 $L(X)=O$ 의 해가 $O$ 뿐이라는 것을 보였다. 또한 9번에서 단사인 선형사상에 대하여 일차독립인 벡터들의 상은 여전히 일차독립임을 보였다.

$L$ 이 단사임을 가정하자. $\mathbb{R}^n$ 의 임의의 기저 $\bf{u}_1,\ldots,\,\bf{u}_n$ 에 대해 $L(\bf{u}_1),\ldots,\,L(\bf{u}_n)$ 이 일차독립이므로 (문제 9) $\{L(\bf{u}_i):i=1,\ldots,\,n\}$ 은 $\mathbb{R}^n$ 의 기저이다. $\mathbb{R}^n$ 의 임의의 벡터는 $c_1L(\bf{u}_1)+\cdots + c_n L(\bf{u}_n)$ 으로 표현할 수 있으며 이는  $L(c_1 \bf{u}_1+\cdots c_n \bf{u}_n)$ 이므로 $L$ 은 전사이다.

$L$ 이 단사가 아님을 가정하자. 어떤 $\bf{u}\ne 0$ 에 대해  $L(\bf{u})=O$ 이다.  우리는 앞서 $n$ 공간에서의 표준단위벡터 $\bf{e}_1,\ldots,\,\bf{e}_n$ 을 배웠다. $\bf{u}\ne O$ 이므로 $\bf{u}$ 의 $0$ 이 아닌 첫번째 성분이 있을 것이다. 그 성분이 $k$ 번째 성분이라면 표준단위벡터의 집합에서 에서 $\bf{e}_k$ 를 빼고 $\bf{u}$ 를 넣어도 이것이  $\mathbb{R}^n$ 의 기저임을 알 수 있다. 그렇다면  $L(\bf{e}_1),\ldots,\, L(\bf{e}_{k-1}),\,L(\bf{u}),\, L(\bf{e}_{k+1}),\ldots,\, L(\bf{e}_n)$ 중에서 최소한 하나 이상은 $0$ 벡터 이며 이것들의 선형결합으로 표현되는 벡터공간의 차원은 $n$ 보다 작다. 따라서 $L$ 은 전사가 아니다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S12}

선형사상 $L:\mathbb{R}^n \to \mathbb{R}^n$ 이 역사상을 가지면, 그 역사상 역시 선형임을 보이라.

:::

</div>

::: {.solution}

선형사상 $L$ 역사상을 가지면 $L$ 은 전단사이다. $L(\bf{u}_1)=\bf{v}_1,\, L(\bf{u}_2)=\bf{v}_2,\, c\in \mathbb{R}$ 라 하자. $L^{-1}(\bf{v}_1)=\bf{u}_1$ 이며 $L^{-1}(\bf{v}_2)=\bf{u}_2$ 이다. $L$ 이 선형사상이므로 $L(\bf{u}_1+\bf{u_2})=\bf{v}_1+\bf{v}_2,\, L(c\bf{u}_1)=cL(\bf{u_1})=c\bf{v}_1$ 이며 $L$ 이 전단사이므로

$$
\begin{aligned}
L^{-1}(\bf{v}_1+\bf{v}_2)&=\bf{u}_1+\bf{u}_2=L^{-1}(\bf{v}_1)+L^{-1}(\bf{v}_2)\\
L^{-1}(c\bf{v}_1) & =c\bf{u_1}=cL^{-1}(\bf{v}_1)
\end{aligned}
$$

이다. 따라서 $L^{-1}$ 도 선형사상이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S13}

선형사상 $L:\mathbb{R}^n \to \mathbb{R}^m$ 에 대응되는 $m \times n$ 행렬을  $A$ 라고 하자. 또 $A$ 의 전치 행렬 $A^t$ 에 대응되는 선형사상을  $L^t:\mathbb{R}^m \to \mathbb{R}^n$ 으로 두자. 이때

$$
\bf{w} \cdot L\bf{v}=L^t\bf{w}\cdot \bf{v} \qquad (\bf{v}\in \mathbb{R}^n,\, \bf{w}\in \mathbb{R}^m)
$$

을 보이라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
\bf{w}\cdot L\bf{v} &= \sum_{i=1}^m w_i (A\bf{v})_{i}=\sum_{i=1}^m w_i \left(\sum_{j=1}^n A_{ij}v_j\right) =\sum_{j=1}^n \left(\sum_{i=1}^m A_{ij}w_i\right)v_j \\[0.3em]
&=\sum_{j=1}^n \left(\sum_{i=1}^m (A^t)_{ji}w_i\right)v_j = \sum_{j=1}^n (A^t \bf{w})_j v_j = L^t\bf{w}\cdot \bf{v}
\end{aligned}
$$

</br>

**Note :** $n$ 벡터 $\bf{u},\,\bf{v}$ 를 $n\times 1$ 열벡터로 표현한것을 $U,\,V$ 라 하면 벡터의 내적 $\bf{u}\cdot \bf{v}$ 는 $U^tV$ 와 같다. 선형사상을 $L$  의 행렬표현을  $A$ 라 하고 $\bf{w},\,\bf{v}$ 의 행렬표현을  $w,\,v$ 라 하면

$$
\bf{w}\cdot L\bf{v}=w^t Av =(A^tw)^t v = (L^t\bf{w})\cdot \bf{v}
$$

로 더 쉽게 표현 할 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S14}

$m$-행 벡터  $\langle \bf{w}|$ 와 $m\times n$  행렬  $A$ 에 대하여, 사상

$$
\langle \bf{w}|\mapsto \langle\bf{w}|A
$$

는 선형사상임을 보이라. 또 주어진 $n$-열벡터 $|\bf{v}\rangle$ 에 대하여 사상

$$
\langle \bf{w}|\mapsto \langle \bf{w}|A|\bf{v}\rangle
$$

도 선형사상임을 보이라.

:::

</div>

::: {.solution}

$m$ 행 벡터  $\langle \bf{w}|$ 는 이에 상응하는 열벡터 $|\bf{w}\rangle$ 의 행렬표현을 $\bf{w}$ 라 하면  $\bf{w}^t$ 이다. 따라서 $(\bf{w}_1^t+\bf{w}_2^t)A=\bf{w}^t_1A+\bf{w}^t_2A$ 이며 임의의 $c\in \mathbb{R}$ 에 대해 $(c\bf{w}_1^t)A=c(\bf{w}_1^tA)$ 이므로 선형사상이다. 또한,

$$
\begin{aligned}
(\bf{w}_1^t+\bf{w}_2^t)A\bf{v} &= \bf{w}_1^tA\bf{v}+\bf{w}_2^tA\bf{v}\\[0.3em]
(c\bf{w}_1^t)A\bf{v}&=c(\bf{w_1}^tA\bf{v})
\end{aligned}
$$

이므로 선형사상이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S15}

열벡터들이 일차독립인 $m\times n$  행렬 $A$ 와 $Y\in \mathbb{R}^m$ 에 대하여 $m>n$ 이면 방정식  

$$
AX=Y \qquad (X\in \mathbb{R}^n)
$$

는 일반적으로 해를 가지지 않음을 설명하라. 이때

$$
A^tAX=A^tY \qquad (X\in \mathbb{R}^n)
$$

은 항상 해를 가짐을 설명하라.

:::

</div>

::: {.solution}

행렬 $A$ 의 $i$-번째 열벡터를 $A_i$ 라 하고 $X=(x_1,\ldots,\,x_2)$ 라 하자. 그렇다며 $AX=x_1A_1+\cdots +x_nA_n=Y$ 이어야 한다. $n<m$ 이며 $A_i \in \mathbb{R}^m$   이므로  $AX=Y$ 인 $X$  가 존재한다는 것은 $Y$ 를 $A_1,\ldots,\,A_n$ 의 일차결합으로 표현할수 있다는 뜻이다. 그런데 $Y\in \mathbb{R}^m$ 이며  $A_i$ 의 갯수는 $n$ 개이므로 $Y$ 가 속한 $\mathbb{R}^m$ 을 모두 표현 할 수 없다. 따라서 일반적으로 해를 가지지 않는다.

$A^tAX=A^tY \implies A^t(AX-Y)=0$ 이다. $Y\in \mathbb{R}^m$ 이며 $A_1,\ldots,\, A_n$ 의 선형결합으로 표현되지 않을 경우 $AX=Y$ 인 $X$ 가 존재하지 않는다. 이제 $A_1,\ldots,\,A_n$ 을 포함하는 $\mathbb{R}_n$ 의 basis를 항상 잡을 수 있다. 나머지 basis 를 $B_1,\ldots,\,B_{m-n}$ 이라 하자. 우리는 $B_1,\ldots,\,B_{m-n}$ 을 모든 $A_1,\ldots,\,A_n$ 과 수직한 벡터로 구성 할 수 있다. (제 5장 탐구문제  6번) 이제 $Y$ 가 $A_1,\ldots,\,A_n,\,B_1,\ldots,\,B_{m-n}$ 의 일차결합으로 다음과 같이 표현된다면

$$
Y=a_1A_1+\cdots +a_nA_n+b_1B_1+\cdots +b_{m-n}B_{m-n}
$$

$X=(a_1,\ldots,\,a_n)^t$ 라 놓자. 그렇다면 $AX-Y=b_1B_1+\cdots +b_m-nB_{m-n}$ 이 된다. 그렇다면,

$$
A^t(AX-Y)=\begin{pmatrix} A_1^t \\A_2^t \\ \vdots \\ A_n^t\end{pmatrix}(b_1B_1+\cdots +b_{m-n}B_{m-n})=\begin{pmatrix} \displaystyle \sum_{j=1}^{m-n} b_j \left(A_1^t \cdot B_j\right) \\ \displaystyle \sum_{j=1}^{m-n} b_j \left(A_2^t \cdot B_j\right) \\ \vdots \\ \displaystyle \sum_{j=1}^{m-n} b_j \left(A_n^t \cdot B_j\right)
\end{pmatrix} = O
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S16}

두 벡터 공간 사이에 정의된 선형사상 $L:X \to Y$ 와 주어진 $ y\in Y$ 에 대하여 방정식 $L(x)=y$ 를 만족시키는  해 $x_0\in X$ 가 존재한다고 하자. 이 때 주어잔 방정식의 해집합은

$$
x_0+\ker L:=\{x_0 +x : x\in X,\,L(x)=0\}
$$

임을 보이라.

:::

</div>

::: {.solution}

$L(x)=y$ 의 해집합을 $A$ 라 하자. 임의의 $x\in \ker L$ 에 대해 $L(x_0+x)=L(x_0)+L(x)=L(x_0)=y$ 이므로 로  $x_0+\ker L\subset A$ 이다.

어떤 $z\not\in \ker L$ 이면  $x_0 + z \not \in x_0 +\ker L$ 임을 보이자 . 역으로 $x_0 +z \in x_0 + \ker L$ 이면 어떤  $x\in \ker L$ 에 대해 $x_0 +z = x_0 +x \implies z=x$ 이어야 하므로 모순. 따라서 $x_0 +z \not\in x_0 +\ker L$ 이다.  그렇다면  $L(x_0 +z)=L(x_0)+L(z)=L(z)\ne O$ 이므로 $(x_0+\ker C)^C \subset A^C$ 이다. 따라서 $A=x_0 + \ker L$ 임을 보였다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S17}

$\mathbb{R}^n$ 의 선형부분공간 $\mathcal{V}$  와 $n$ 차 정사각행렬 $A$  에 대하여

$$
A\mathcal{V}:=\{ A\bf{v}: \bf{v}\in \mathcal{V}\}
$$

가 $\mathcal{V}$ 가 포함되면 $A$ 가  $\mathcal{V}$ 를 보존한다고 말한다. 이제 $A$ 가 $\mathcal{V}$ 를 보존하면, $A^t$ 는

$$
\mathcal{V}^\perp :\{\bf{w} \in \mathbb{R}^n: \bf{w}\cdot \bf{v}= 0,\, \forall\bf{v}\in \mathcal{V}\}
$$

를 보존함을 보이라.

:::

</div>

::: {.solution}

$\bf{w}=(w_1,\ldots,\,\,w_n) \in \mathcal{V}^\perp$ 라 하자. $\bf{v}=(v_1,\ldots,\,v_n)\in \mathcal{V}$ 이면  $A\mathcal{v}=\bf{v}'\in \mathcal{V}$ 이다.  

$$
(A^t\bf{w})\cdot \bf{v}= (A^t\bf{w})^t\bf{v} = (\bf{w}^tA)\bf{v} = \bf{w}^t(A\bf{v}) = \bf{w}^t \bf{v'}=0
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S18}

정사각행렬 $A$ 가 $A^tA=I$ 이면 $ AA^t=I$ 임을 보이라.

::: 

</div>

::: {.solution}

$A$ 가  $n \times n$ 행렬이라 하자.

$$
(A^tA)_{ij}=\sum_{k=1}^n (A^t)_{ik}A_{kj}=\delta_{ij}
$$

임을 안다.

$$
(AA^t)_{ij}=\sum_{l=1}^n A_{il}(A^t)_{lj}=\sum_{l=1}^n (A^t)_{li}A_{jl}=\sum_{i=1}^n A_{jl}(A^t)_{li}=\delta_{ji}
$$

이므로 $(AA^t)=I$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S19}

삼차원 좌표공간 $\mathbb{R}^3$ 에서 점 $P$ 를 지나고, 단위벡터 $\bf{v}$ 에 수직인 평면으로의 정사영을 $E$ 라고 두면

$$
E(X)=X+((P-X)\cdot \bf{v})\bf{v},\qquad X\in \mathbb{R}^3
$$

임을 보이라. 또 $E^2=E$ 임을 보이라.

:::

</div>

::: {.solution}

점 $P$ 를 지나고 단위벡터 $\bf{v}$ 에 수직인 평면은 $\bf{v}\cdot (X-P)=0$ 이다. $X_0\in \mathbb{R}^3$  를 지나고 기울기 $\bf{v}$ 인 직선의 방정식은  $t\in \mathbb{R}$ 에 대해

$$
X=\bf{v}t+X_0
$$

이다. 이 때 직선과 평면의 교점은, ($|\bf{v}|=1$ 이므로,

$$
\bf{v} \cdot (\bf{v}t+X_0-P)=0 \implies |\bf{v}|^2t=\bf{v}\cdot (P-X_0) \implies t=(P-X_0)\cdot \bf{v}
$$

에 의해 결정된다. 즉 이 교점을 $X_1$ 라 하고  $t_0=(P-X_0)\cdot \bf{v}$ 라 하면,

$$
X_1=\bf{v}t_0 +X_0
$$

이다. 이 때 $X_0-X_1=-\bf{v}t_0$ 이며, 평면상의 임의의 점 $X_2$ 에 대해 $\bf{v}\cdot (X_2-X_1)=\bf{v}(X_2-P)-\bf{v}(X_1-P)=0$ 이므로  $X_1-X_0$ 와 $X_2-X_1$ 은 항상 수직하다. 따라서 피타고라스의 정리에 의해 평면과 $X_0$ 사이의 최단거리는 $|X_1X_0|$ 이므로  $X_0$ 가 $X_1$ 의 정사영이다.

$X_1\to X,\, X_0\to E(X)$ 라 하면,

$$
E(X)=X+\left((P-X)\cdot \bf{v}\right)\bf{v}
$$

이다.

또한 $E^2=E$ 임을 보이자. $|\bf{v}|^2=\bf{v}\cdot \bf{v}=1$ 을 이용하면,

$$
\begin{aligned}
E(E(X))&=X+((P-X)\cdot \bf{v})\bf{v} +((P-[X+\left((P-X)\cdot \bf{v}\right)\bf{v}])\cdot \bf{v})\bf{v} \\
&=X+((P-X)\cdot \bf{v})\bf{v} +((P-V)\cdot \bf{v}) \bf{v}-((P-X)\cdot \bf{v})(\bf{v}\cdot \bf{v})\bf{v} \\
&= X+((P-X)\cdot \bf{v})\bf{v}\\
&=E(X)
\end{aligned}
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S20}

좌표공간 $\mathbb{R}^3$ 에서 서로 다른 두 평면 $\pi_1,\,\pi_2$ 로의 정사영을 각각 $E_1,\,E_2$ 라고 할 때, $E_1E_2=E_2E_1$ 이 될 필요충분조건은 $\pi_1$ 과  $\pi_2$ 가 서로 수직으로 만나는 것임을 보이라.

:::

</div>

::: {.solution}

$\pi_1,\,\pi_2$ 의 방향벡터의 단위벡터를 각각 $\bf{v}_1,\,\bf{v}_2$ 라고 하고 각각의 평면이 지나는 한 점을 $P_1,\,P_2$ 라 하자. 두 평면이 서로 다른 평면상에 있으므로 $P_1$  을 $\pi_2$  위에 있지 않고, $P_2$  는 $\pi_1$  위에 있지 않도록 잡을 수 있다.  

$$
\begin{aligned}
E_1(E_2(X)) &=E_1(X+((P_2-X)\cdot \bf{v}_2)\bf{v}_2)\\
&= X+((P_2-X)\cdot \bf{v}_2)\bf{v}_2 +((P_1-X-((P_2-X)\cdot \bf{v}_2)\bf{v}_2)\cdot \bf{v}_1)\bf{v}_1\\
&=X+((P_2-X)\cdot \bf{v}_2)\bf{v}_2 +((P_1-X)\cdot \bf{v}_1)\bf{v}_1 -((P_2-X)\cdot \bf{v}_2)(\bf{v}_2\cdot \bf{v}_1)\bf{v}_1\\
E_2(E_1(X))&=X+((P_1-X)\cdot \bf{v_1})\bf{v}_1 + ((P_2-X)\cdot \bf{v}_2)\bf{v}_2 -((P_1-X)\cdot \bf{v}_1)(\bf{v}_1 \cdot \bf{v}_2)\bf{v}_2
\end{aligned}
$$

이다.

$$
E_1E_2=E_2E_2\implies (\bf{v}_1\cdot \bf{v}_2)\left[(P_2-X)\cdot \bf{v}_2)\bf{v}_1-((P_1-X)\cdot \bf{v}_1)\bf{v}_2 \right]=0
$$

이다. 따라서 $\bf{v}_1\cdot \bf{v}_2=0$ 이거나 $((P_2-X)\cdot \bf{v}_2)\bf{v}_1=((P_1-X)\cdot \bf{v}_1) \bf{v}_2$ 일 때이다.

두번째 경우부터 보자. 임의의  $X$ 에 대해 성립해야 하므로, $\bf{v}_1=c\bf{v}_2$ for some $c\in \mathbb{R}$ 이어야 한다. $\bf{v}_1$ 과 $\bf{v}_2$  는 단위벡터이므로 $c=\pm 1$ 이며, 따라서,

$$
\begin{aligned}
(P_2-X)\cdot \bf{v}_2 = \pm (P_1-X)\cdot \bf{v}_1 &\implies (P_2-X)\cdot \bf{v}_1=(P_1-X)\cdot \bf{v_1} \\[0.3em]
&\implies (P_1-P_2)\cdot \bf{v}_1 =0
\end{aligned}
$$

이다. 이것을 만족하는 $P_2$ 는 평면 $\pi_1$ 상에 있는데 우리는 이미 $P_2$ 가 $\pi_1$ 위에 있지 않다고 가정했으므로 위 식은 성립할 수 없다. 따라서,

$$
E_1E_2=E_2E_1 \iff \bf{v}_1\cdot \bf{v}_2=0
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S21}

좌표공간에서 원점을 지나는 한 평면으로의 정사영을 $E$ 라고 두자. 이때 임의의 벡터 $\bf{v}$ 에 대하여,

$$
\langle \bf{v}|E\bf{v}\rangle = |E\bf{v}|^2
$$

임을 보이라.

:::

</div>

::: {.solution}

우리는 @exr-CAL_6_S19 를 풀 때 문제에는 3차원 좌표공간임을 가정했지만 3차원임을 이용하지 않았다. 즉 @exr-CAL_6_S19 의 결론은 임의의 $n$ 차원 좌표공간에 적용 할 수 있다. 원점을 지나는 한 평면의 방정식은 단위방향벡터 $\bf{n}$ 에 대하여 $\bf{n}\cdot X=0$ 으로 나타 낼 수 있다. 이에 대한 정사영은 (@exr-CAL_6_S19 를 이용하면),

$$
E(X)=X-(X\cdot\bf{n})\bf{n}
$$

이다. 임의의 $\bf{v}\in \mathbb{R}^n$ 에 대해 $\langle {\bf{v}-E\bf{v}}|E\bf{v}\rangle$ 을 계산해보자. $E(\bf{v})=\bf{v}-(\bf{v}\cdot \bf{n})\bf{n}$ 이므로,

$$
\langle {\bf{v}-E\bf{v}}|E\bf{v}\rangle =\langle (\bf{v}\cdot \bf{n})\bf{n}|\bf{v}-(\bf{v}\cdot \bf{n})\bf{n}\rangle = (\bf{v}\cdot \bf{n})^2-(\bf{v}\cdot \bf{n})^2(\bf{n}\cdot\bf{n})=0
$$

이다. 그런데,

$$
0=\langle {\bf{v}-E\bf{v}}|E\bf{v}\rangle =\langle\bf{v}|E\bf{v}\rangle -\langle E\bf{v}|E\bf{v}\rangle = \langle \bf{v}|E\bf{v}\rangle -|E\bf{v}|^2
$$

이다. 따라서 $\langle \bf{v}|E\bf{v}\rangle =|E\bf{v}|^2$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S22}

삼차원 좌표공간에서 단위벡터 $\bf{v}=(v_1,\,v_2,\,v_3)$ 가 만드는 축의 주위로 $\theta$ 만큼 회전이동하는 변환의 행렬 $R_{\bf{v}}(\theta)$ 는

$$
\begin{pmatrix}
v_1^2 (1-\cos \theta) +\cos \theta & v_1v_2(1-\cos \theta)-v_3\sin \theta  & v_1v_3 (1-\cos \theta)+ v_2\sin \theta \\
v_1v_2(1-\cos\theta)+v_3 \sin \theta & v_2^2 (1-\cos \theta) + \cos \theta & v_2v_3 (1-\cos \theta) - v_1 \sin \theta \\
v_1v_3 (1-\cos \theta) - v_2 \sin \theta & v_2v_3 (1-\cos \theta)+v_1\sin \theta & v_3^2(1-\cos \theta) + \cos \theta
\end{pmatrix}
$$

임을 보이라. 또,

$$
\cos \theta = \dfrac{1}{2} \left(\operatorname{tr} R_{\bf{v}}(\theta)-1\right)
$$

임을 보이라.

:::

</div>

::: {.solution}

지겨운데..

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S23}

정사각행렬 $A$ 에 대하여 $|A|<1$ 이면 급수

$$
I+A+A^2+A^3+\cdots
$$

가 수렴하고 이 때

$$
(I-A)(I+A+A^2+A^3+\cdots )=I
$$

임을 보이라.

::: 

</div>

::: {.solution}

$A$ 를 $n \times n$ 행렬이라 하자. 우리는 $|A_{ij}|<1 \;\forall 1\le i,\,j \le n$ 이며 $|A^k|\le |A|^k$ 임을 안다. (정리 3.3.2) 즉 $|A_{ij}|=r<1$ 이면 $|A^k|\le r^k$ 이므로 모든 $A^k$ 의 성분은 $r^k$ 보다 작다. 따라서, $\displaystyle \lim_{k=\infty}A^k=0$ 이며, $B_k=I+A+A^2+\cdots +A^k $ 라 하면,

$$
|(B_k)_{ij}|<1+r+r^2+\cdots +r^{k}<\dfrac{1}{1-r}
$$

이므로 $(B_k)_{ij}$ 는 절대수렴한다. $I+A+A^2+\cdots = B$ 이므로 양변에 $A$ 를 곱하면 $B-I=AB$ 임을 안다. 따라서,

$$
(I-A)(I+A+A^2+\cdots)=B-AB=I
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_6_S24}

수렴반경이 $r>0$ 인 멱급수 $\displaystyle f(x)=\sum_{k=0}^\infty b_k x^k$ 를 생각하자. 이 때 $A$ 가 $|A|<r$ 인 정사각행렬이면 급수

$$
f(A):=\sum_{k=0}^\infty b_k A^k
$$

가 수렴함을 보이라.

:::

</div>

::: {.solution}

우리는 $|A^k|<|A|^k<r^k$ 임을 알며 $|(A^k)_{ij}|<|A^k|<r^k$ 임을 안다. 따라서,

$$
|f(A)_{ij}| = \left|\sum_{k=0}^\infty b_k (A^k)_{ij}\right|\le \sum_{k=0}^\infty \left|b_k (A^k)_{ij}\right| \le \sum_{k=0}^{\infty} b_k r^k
$$

이므로 절대수렴한다.

:::
