---
title: "정사각 행렬과 행렬식"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

## 연습문제 : 제 7장 1절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_1_1}

$n$ 차 정사각행렬 $A,\,B$ 에 대하여 $AB=O$ 이면 $BA=O$ 인가?

:::

</div>

::: {.solution}

No. For example, $A=\begin{pmatrix} 0 & 0 & 1 \\ 0 & 0 & 1 \\ 0 & 0 & 0\end{pmatrix}, B=\begin{pmatrix} 0 & 0 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 0\end{pmatrix}$ 이면 $AB=\begin{pmatrix} 0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0\end{pmatrix},  BA=\begin{pmatrix} 0 & 0 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0\end{pmatrix}$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_1_2}

행렬 $A=\begin{pmatrix} 1 & 2 & 0 \\ 2 & 3 & 0 \end{pmatrix} ,\, B=\left(\begin{array}{rr} -3 & 2 \\ 2 & -1 \\ 0 & 0\end{array}\right)$ 에 대하여 $AB=I$ 를 보이라. 이 때 $BA=I$ 인가?

:::

</div>

::: {.solution}

$BA=\begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0\end{pmatrix}$.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_1_3} 

$n$ 차 가역행렬 $A$ 에 대하여

$$
\left(A^{-1}\right)^{-1}=A,\qquad \left( A^{-1} \right)^k = \left( A^k \right)^{-1}, \qquad (k=1,\,2,\,3,\ldots)
$$

임을 보이라. 또 전치행렬 $A^t$ 도 가역임을 보이고, 이때,

$$
\left( A^{t}\right)^{-1}=\left(A^{-1}\right)^t
$$

임을 밝히라. 또 $B$ 가 $n$ 차 가역행렬이면

$$
\left(AB\right)^{-1}=B^{-1}A^{-1}
$$

임을 보이라.

::: 

</div>

::: {.solution}

($1$) $A^{-1}A=I$ 이므로 $\left( A^{-1} \right)^{-1}=A$ 이다.

($2$) $\underbrace{A^{-1}\cdots A^{-1}}_{k-\text{times}} \underbrace{A \cdots A}_{k-\text{times}} =\underbrace{A^{-1}\cdots A^{-1}}_{(k-1)-\text{times}} \underbrace{A \cdots A}_{(k-1)-\text{times}}=\cdots= A^{-1}A=I$  

($3$) $B$ 를 $A^{-1}$ 이라 하면, $AB=BA=I$ 이므로, $ I^t=I=(AB)^t=B^tA^t$, $I^t=I=(BA)^t=A^tB^t$ 이다. 따라서 $\left(A^{t}\right)^{-1}=\left(A^{-1}\right)^t$ 이다.

($4$) $AB(B^{-1}A^{-1})=(B^{-1}A^{-1})AB=I$ 이므로 $(AB)^{-1}=B^{-1}A^{-1} $ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_1_4}

행렬 $\begin{pmatrix} 0 & 0 & 1\\ 0 & 2 & 0 \\ 3 & 0 & 0 \end{pmatrix}$ 의 역행렬을 보여라.

:::

</div>

::: {.solution}

주어진 행렬을 $A$ 라 하고 역행렬을 $B=\begin{pmatrix} a & b & c\\ d&e&f \\g & h & i\end{pmatrix}$ 라 하면, 

$$
AB=\begin{pmatrix} g & h & i \\2d & 2e & 2f \\ 3a & 3b & 3c\end{pmatrix} = I
$$ 

이므로, $a=0,\,b=0,\,c=1/3,\, d=0, \, e=1/2,\, f=0,\, g=1,\, h=0,\, i=0$ 이다. 즉

$$
\begin{pmatrix}0 & 0 & \frac{1}{3} \\ 0 & \frac{1}{2} & 0 \\ 0 & 0 & 1\end{pmatrix}
$$

이다.

:::

</br>

## 연습문제 : 제 7장 2절

없음

</br>

## 연습문제 : 제 7장 3절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_3_2} 

좌표평면 위의 두 벡터 $\bf{x},\, \bf{y}$ 가 이루는 평행사변형

$$
\{s\bf{x}+t\bf{y}:0 \le s,\,t \le 1\}
$$

의 넓이는 $|\det(\bf{x},\,\bf{y})|$ 임을 보이라.

::: 

</div>

::: {.solution}

연습문제 5장 3절 5번에 의해 면적 $S=\sqrt{|\bf{x}|^2|\bf{y}|^2-(\bf{x}\cdot \bf{y})^2}$ 이다. $\bf{x}=(x_1,\,\bf{x}_2),\, \bf{y}=(y_1,\,y_2)$ 라 하면,

$$
\begin{aligned}
S &= \sqrt{(x_1^2+x_2^2)(y_1^2+y_2^2)-(x_1y_1+x_2y_2)^2} =\sqrt{(x_1y_2-x_2y_1)^2} \\[0.3em]
&=|x_1y_2-x_2y_1| =|\det(\bf{x},\, \bf{y})|
\end{aligned}
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_3_3} 

좌표평면에서 네 점 $(0,\,0),\, (1,\,0),\, (3,\,1),\, (2,\,3)$ 을 꼭지점으로 가지는 볼록사각형의 넓이는


$$
\left|\det \begin{pmatrix} 1 & 0 \\ 3 & 1 \end{pmatrix} + \det \begin{pmatrix}  3&1\\ 2 & 3 \end{pmatrix} \right| = \dfrac{1}{2}(1+7)=4
$$

임을 보이라. 일반적으로 평면의 점 $A_1,\,A_2,\,\ldots,\,A_n,\,A_1$ 을 차례로 연결한 평면다각형의 넓이는

$$
\dfrac{1}{2}\left|\det(A_1,\,A_2) + \cdots + \det (A_{n-1},\,A_n)+\det(A_n,\,A_1)\right|
$$

임을 보이라.

:::

</div>

::: {.solution}

*이거 지금까지 배운걸로 풀 수 있는거 맞아? 각 삼각형의 determinant의 부호가 같다는걸 보여야 하는데..*

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_3_4}

좌표평면의 벡터 $\bf{x},\,\bf{y}$ 가 이루는 평행사변형의 넓이를 $\operatorname{area}(\bf{x},\,\bf{y})$ 라고 두었을 때, 2차 정사각행렬 $A$ 에 대하여

$$
\operatorname{area}(L_A(\bf{x}),\,L_A(\bf{y}))=|\det A|\operatorname{area}(\bf{x},\,\bf{y})
$$

임을 보이라.

:::

</div>

::: {.solution}

$L_A(x_1,\,x_2)=(ax_1+bx_2,\, cx_1+dx_2),\, \bf{x}=(x_1,\, x_2),\, \bf{y}=(y_1,\, y_2)$ 라 하자. $B,\,C$ 가 $n\times n$ 행렬일 때 $\det(BC)=\det(B)\det(C)$ 임을 알고 있으며, $\operatorname{area}(\bf{x},\,\bf{y})=|\det (\bf{x},\,\bf{y})|$ 임을 알고 있다.

$$
\begin{aligned}
\operatorname{area}(L_A(\bf{x}),\,L_A(\bf{y})) &= \left|\det \begin{pmatrix} ax_1+bx_2  & cx_1+dx_2 \\ ay_1+by_2 & cy_1+dy_2\end{pmatrix} \right| \\
&=\left| \det \left[\begin{pmatrix}x_1 & x_2 \\ y_1 & y_2 \end{pmatrix}\begin{pmatrix}a & b \\ c & d \end{pmatrix} \right]\right|=|\det A| \operatorname{area}(\bf{x},\,\bf{y})
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_3_5}

좌표평면에서 원판 $x^2+y^2\le 1$ 이 선형변환 $\begin{pmatrix} 2 & 0 \\ 0 & 3\end{pmatrix}$ 에 의하여 변화된 상의 넓이를 구하라. 또 넓이가 $A$ 인 영역은 이 선형변환에 의하여 넓이가 얼마인 영역이 되는가?

:::

</div>

::: {.solution}

이 선형변환을 $L$ 이라 하면 $L(x,\,y)=(2x, 3y)$ 이다. $x'=2x,\,y'=3y$ 이므로 $\dfrac{x^2}{2^2}+\dfrac{y^2}{3^2}\le 1$ 인 영역이 된다. 이는 타원의 면적으로 $2\times 3 \times \pi = 6\pi$ 이다.

*아직 일반화된 면적의 변화까지는 안배운것 같은데...*

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_3_6}

$n$ 차 정사각행렬 $A$ 와 실수 $c$ 에 대하여 $\det (cA)$ 는 $\det (A)$ 의 몇배인가?

:::

</div>

::: {.solution}

$A$ 의 $i$ 번째 열을 $A_i$ 라 하면 $\det (cA) = \det (cA_1,\,cA_2,\ldots,\,cA_n)$ 이다. 정리 3.0.3을 이용하면,

$$
\begin{aligned}
\det (cA_1,cA_2,\ldots,\,cA_n) &= c\det(A_1,\,cA_2,\ldots,\,cA_n) \\[0.3em]
&=c^2\det (A_1,\,A_2,\ldots,\,cA_n)=\cdots \\[0.3em]
&= c^n\det(A_1,\ldots,A_n)=c^n\det A
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_3_7} 

다음을 보이라..

:::

</div>

::: {.solution}
생략.

:::

</br>

## 제 4절 부록

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_4_B03} 

호환들 중에서 인접한 항을 바꾸는 것, 즉 $(i\;\; i+1)$ 을 인접호환 이라고 부르자. 이때 임의의 호환은 홀수개의 인접호환으로 나타남을 보이라. 모든 치환은 인접호환의 곱으로 나타남을 증명하라

::: 

</div>

::: {.solution}

$(i \;\;j)$ 을 생각하자. $(i\;\;j)=(j\;\;i)$ 이므로 $i<j$ 라 두어도 상관 없다. $j-i=n$ 으로 놓고 $n$ 에 대한 induction을 사용한다. $n=1$ 일 때는 인접호환이므로 성립한다. $n$ 일 때 성립함을 가정하자. $(i\;\; i+n+1)=(i\;\;i+1)(i+1\;\;i+n)(i\;\;i+1) $ 이다. $(i\;\;i+1)$ 은 인접호환이고 $(i+1\;\;i+n)$ 은 가정에 의해 홀수개의 인접호환으로 나타낼 수 있으므로 $(i \;\;i+n+1)$ 은 홀수개의 인접호환으로 나타 낼 수 있다.

정리 4.1.2 에 의해 모든 치환은 호환의 곱으로 나타나며 3. 에 의해 모든 호환은 홀수개의 인접호환의 곱으로 나타나므로 모든 치환은 인접호환의 곱으로 나타난다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_4_B05} 

호환 $(i\;\;j)$ 의 전도의 수는 $2|i-j|-1$ 임을 보여라.

:::

</div>

::: {.solution}

$(i,\,j)=(j,\, i)$ 이므로  $i<j$ 라 가정하자. $\sigma(i)$ 가 $\sigma(i+1),\cdots,\ \sigma(j)$ 보다 크므로 일단 $j-i$ 개. $\sigma(i+1)$ 부터 $\sigma(j-1)$ 까지 $\sigma(j)$ 보다 크므로 $j-i-1$ 개. 따라서 $2(j-i)-1$ 개이다. $j<i$ 이면 $2(i-j)-1$ 이므로  $2|i-j|-1$ 개이다.

:::

</br>

**정리 4.1.6**  임읭 치환 $\sigma$ 와 호환 $\tau$ 에 대하여
$$
N(\sigma \tau)\equiv N(\sigma)+1 \;\operatorname{mod}\;2
$$
이다.

::: {.proof}

우선 $\tau$ 가 인접호환 $(k,\, k+1)$ 인 경우를 보자. $N(\sigma\tau)$ 와 $N(\sigma)$ 의 차이는 $\tau$ 에 의해서 $\sigma(\tau (k))=\sigma(k+1),\, \sigma(\tau (k+1))=\sigma (k)$ 로 변하는 것이다. 즉
$$
\sigma \tau =\begin{pmatrix} 1 & 2 & 3 & \cdots & k & k+1 & \cdots & n\\ \sigma(1) & \sigma(2) & \sigma(3) &\cdots &\sigma(k+1) & \sigma(k) & \cdots & \sigma(n)\end{pmatrix}
$$

- $i<k$ 일 때는 $\sigma(i)$ 이후애 $\sigma(i)$ 보다 작은 항들의 갯수는 변화가 없다.

- $i>k+1$ 일 때에도 $\sigma(i)$ 이후에 $\sigma(i)$ 보다 작은 항들의 갯수는 변화가 없다.

- $\sigma(k)$ 이후에 $\sigma(k)$ 보다 작은 것의 갯수를 $M_k$ $\sigma(k+1)$ 이후에 $\sigma(k+1)$ 보다 작은 것의 갯수를 $M_{k+1}$ 이라 하자. $\sigma(k)<\sigma(k+1)$ 이라면 $\sigma\tau(k)$ 이후에 $\sigma\tau(k)$ 보다 작은 것의 갯수는 변함없이 $M_k$ 이며 $\sigma\tau(k+1)$ 이후에 $\sigma\tau(k)$ 보다 적은것이 하나 늘었으므로  $M_k+1$ 이다. $\sigma(k+1)<\sigma(k)$ 라면 $\sigma\tau(k)$ 이후에 $\sigma\tau (k)$ 보다 적은것이 하나 줄고, $\sigma\tau(k+1)$ 이후에 $\sigma(\tau)(k+1)$ 이후에 는 변화가 없으므로,

$$
N(\sigma \tau)=N(\sigma) \pm 1
$$

이다.

즉 임의의 인접호환마다 전도의 수는 하나씩 줄거나 늘어난다.

임의의 호환은 홀수개의 인접호환의 곱이므로 전도의 수는 홀수만큼 늘거나 준다. 따라서

$$
N(\sigma \tau)\equiv N(\sigma) +1\qquad \operatorname{mod}\;2
$$

이다. $\square$

:::


</br>

**정리 4.1.8** 자연수 $k,\,k'$ 과 호환 $\tau_1,\ldots,\,\tau_k,\,\tau'_1,\ldots,\,\tau'_{k'}$ 에 대하여

$$
\tau_1 \cdots \tau_k = \tau'_1\cdots \tau'_{k'}
$$

이면

$$
k \equiv k \quad \operatorname{mod}\; 2
$$

이다.

::: {.proof}

우리는

$$
\tau'_{k'}\cdots \tau'_{1}\tau_1 \cdots \tau_k = \operatorname{id}
$$

임을 안다. $N(\operatorname{id})=0$ 이므로

$$
\begin{aligned}
0 &=N(\operatorname{id})=N(\tau_{k'}\cdots \tau'_1\tau_1\cdots \tau_k) \\[0.3em]
&\equiv N(\tau'_{k'}\cdots \tau'_1 \tau_1 \cdots \tau_{k-1})+1\quad \operatorname{mod}\;2 \equiv\cdots \\[0.3em]
&\equiv k+k' \quad \operatorname{mod}\; 2
\end{aligned}
$$

이다. 즉

$$
k \equiv k' \quad \operatorname{mod}\;2
$$

이다. $\square$
:::
</br>

**정리 3.0.3** 의 증명

$n\times n$ 정사각행렬 $A$ 의 행렬식 $\det A$ 는 $A$ 의 각 열 $A_1,\ldots,\,A_n$ 의 함수로 $\det(A_1,\ldots,\,A_n)$ 으로 표현 할 수 있다. 이 때 행렬식

$$
\det : \mathbb{R}^n \times \cdots \times \mathbb{R}^n \to \mathbb{R}
$$

은

($1$) 각 열에 대한 선형사상이다. 즉 임의의 실수 $t,\,t'$ 에 대해

$$
\begin{aligned}
\det(A_1,\dots,\,A_{i-1},&tA_i + t'A'_i ,\, A_{i+1},\ldots,\, A_n) \\[0.3em]
&= t\det(A_1,\ldots,\,A_{i-1},\,A_i, A_{i+1},\ldots, \,A_n) \\[0.3em]
&\qquad \qquad + t'\det(A_1,\ldots,\,A_{i-1},\,A'_i, A_{i+1},\ldots, \,A_n)
\end{aligned}
$$

이다.

($2$) 두 열을 바꾸면 부호가 바뀐다. 즉 $i<j$ 에 대하여,
$$
\det(A_1,\ldots,\,A_i,\,\ldots,\,A_j,\ldots,\,A_n)=-\det(A_1,\ldots,\,A_j,\ldots,\,A_i,\ldots,\,A_n)
$$
이다.

역으로 함수 $f:\mathbb{R}^n \times \mathbb{R}^n \to \mathbb{R}$ 이 위의 성질 (1) 과 (2) 를 만족시키면, 임의의 정사각행렬 $A$ 에 대하여

$$
f(A)=f(I)\det A
$$

이다.

::: {.proof}

행렬식의 정의는

$$
\det A=\sum_{\sigma \in S_n} \operatorname{sgn}(\sigma) A_{1\sigma(1)}\cdots A_{n\sigma(n)}
$$

이다.

함수  $f$ 가 성질 ($1$), ($2$)를 가진다면 따름정리 3.0.4 를 만족함을 보이자.

$i<j$ 에 대해 $A_i=A_j$ 라 하자.

$$
\begin{aligned}
\det (\ldots,\,A_i,\ldots,\,A_j &= A_i ,\ldots)=\det(\ldots, A_i -A_j,\ldots, A_j,\ldots) \\[0.3em]
&=\det(\dots,\,0,\ldots, A_j,\ldots)=0
\end{aligned}
$$

이므로 서로 다른 열이 같은 벡터의 정사각행렬은 $0$ 이다.  $i\ne j$ 에 대해,

$$
\begin{aligned}
\det &(\ldots ,A_i+tA_j,\ldots, A_j,\ldots) \\[0.3em]
&=\det(\ldots,A_i,\ldots,\,A_j,\ldots )+ t\det(\ldots,\,A_j,\ldots,\,A_j,\ldots)\\[0.3em]
&=\det(\ldots,\,A_i,\ldots,\,A_j,\ldots)=\det A
\end{aligned}
$$

이므로 정사각행렬에 어떤 열의 벡터를 상후배하여 다른 열에 더하더라도 행열식의 값은 변화가 없다.

이제 열벡터  $A_j = \displaystyle \sum_{i=1}^n a_{ij}\bf{e}_i$ 라 쓰자. 그렇다면,

$$
\begin{aligned}
f(A)&= f\left(\sum_{i_1=1}^n a_{i_11}\bf{e}_{i_1}, \, \sum_{i_2=1}^n a_{i_22}\bf{e}_{i_2},\ldots,\, \sum_{i_n=1}^n a_{i_nn}\bf{e}_{i_n}\right) \\
&= \sum_{i_1=1}^n a_{i_11}f\left(\bf{e}_{i_1}, \, \sum_{i_2=1}^n a_{i_22}\bf{e}_{i_2},\ldots,\, \sum_{i_n=1}^n a_{i_nn}\bf{e}_{i_n}\right) \\
&= \sum_{i_1=1}^n \cdots \sum_{i_n=1}^n a_{i_11} \cdots a_{i_n n} f\left(\bf{e}_{i_1},\ldots, \bf{e}_{i_n}\right)\\
&=\sum_{\sigma \in S_n} a_{\sigma(1)1}\cdots a_{\sigma(n)n } f(\bf{e}_{\sigma(1)},\ldots,\, \bf{e}_{\sigma(n)})\\
&=\sum_{\sigma\in S_n}\operatorname{sgn}(\sigma)a_{\sigma(1)1}\cdots a_{\sigma(n)n} f(\bf{e}_1,\ldots,\,\bf{e}_{\sigma(n)})\\
&= f(I)\det A^t\\
&=f(I)\det A
\end{aligned}
$$

:::


</br>

**정리 4.2.2** $n$ 벡터 $\bf{a}_1,\ldots,\,\bf{a}_n$ 이 일차독립일 필요충분조건은

$$
\det (\bf{a}_1,\ldots,\,\bf{a}_n) \ne 0
$$

이다.

::: {.proof}

$n$ 벡터 $\bf{a}_1,\ldots, \bf{a}_n$ 이 일차독립이면 표준단위벡터  $\bf{e}_1,\ldots,\,\bf{e}_n$ 이 모두  $\bf{a}_1,\ldots,\,\bf{a}_n$ 의 일차결합으로 표시된다. 따라서,

$$
\bf{e}_j=\sum_{i=1}^n \bf{a}_ib_{ij}
$$

로 쓸 수 있다. 이제 $A=(\bf{a}_1,\ldots,\,\bf{a}_n),\, B=(b_{ij})$ 로 두면 $I=AB$ 이며, 따라서,

$$
1=\det (I)=\det(AB)=(\det A)(\det B)
$$
가 되므로 $\det A\ne 0$ 이다.

만약  $\bf{a}_1,\ldots,\,\bf{a}_n$ 이 일차종속이면 이중 어느 하나는 나머지 하나의 일차결합이므로 $\det A=0$ 이다.

:::


</br>

## 연습문제  : 제 7 장 4절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_4_1}

$n$  치환 중에서 짝치환인 것의 갯수와 홀치환인 것의 갯수를 구하라.

:::

</div>

::: {.solution}

모든 원소가  $1$ 인 $n \times n$ 행렬  $A$ 를 생각하면  $\det A=0$ 임은 자명하다. 그런데 $A$ 의 행렬식은 정의에 의해

$$
\det A=\sum_{\sigma\in S_n}\operatorname{sgn}(\sigma) =[\text{짝치환의 갯수}]-[\text{홀치환의 갯수}]=0
$$

이므로 홀치환의 갯수 와 짝치환의 갯수는 같으며 둘의 합이 $n!$ 이므로 각각 $\dfrac{n!}{2}$  이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_4_2} 

치환  
$$
\sigma(k)=16-k\qquad (k\in \{1,\,2,\ldots,\,15\})
$$

는 홀치환임을 보이라.

:::

</div>

::: {.solution}

$$
\sigma(k)=\begin{pmatrix} 1 & 2 & \cdots & 14 & 15 \\ 15 & 14 &\cdots & 2 & 1\end{pmatrix} =(1\;\;15)(2\;\; 14)\cdots (7\;\;8)
$$

이므로 7개의 호환이 모인 홀치환이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_4_3} 

$m \times n$ 직사각형 퍼즐은 1부터  $mn-1$ 까지의 숫자와 빈칸으로 이루어져 있다. 처음 공장에서 배열한 순서를 뒤집어 배열할 수 있는 가역퍼즐은 어떠한 것인가?

:::

</div>

::: {.solution}

모르겠다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_4_4} 

다음 "넉줄 사다리 타기" 에서 5개의 계단을 놓아 같은 숫자끼리 연결되게 할 수 있는가?

:::

</div>

::: {.solution}
계단 하나는 하나의 인접호환이며 5개의 계단은 5개의 인접호환이므로 이것의 합성은 홀치환이다. 같은 숫자까지 연결되는 것은 항등호환 $\operatorname{id}$ 이므로 짝치환이다. 따라서 불가능.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_4_5} 

흰실, 노란실, 검은실 세 가닥을 딿아 길고 굵은 끈을 만들었다고 하자. 끈의 처음 색의 배열이 끈의 끝에서의 배열과 같을 때, 땋은 횟수가 짝수임을 설명하라.

:::

</div>

::: {.solution}

한번 땋는 것은 인접호환. 4번과 같은 이유로 짝치환.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_4_6} 

치환 $\sigma,\,\sigma'$ 에 대하여

$$
\operatorname{sgn}(\sigma\sigma')=\operatorname{sgn}(\sigma)\operatorname{sgn}(\sigma')
$$

임을 보이라. 또 이로부터,

$$
\operatorname{sgn}(\sigma^{-1})=\operatorname{sgn}(\sigma)
$$

를 유도하라.

:::

</div>

::: {.solution}

홀치환 짝치환을 생각하면 $\operatorname{sgn}(\sigma\sigma')=\operatorname{sgn}(\sigma)\operatorname{sgn}(\sigma')$ 는 trivial 하다 .$\operatorname{sgn}(\operatorname{id})=1$ 이므로 $1=\operatorname{sgn}(\sigma \sigma') = \operatorname{sgn}(\sigma)\operatorname{sgn}(\sigma')$ . $\operatorname{sgn}(\sigma)= \pm 1$ 이므로 $\operatorname{sgn}(\sigma^{-1})=\operatorname{sgn}(\sigma)$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_4_7} 

$n$-치환 $\sigma$  에 대하여

$$
\operatorname{sgn}(\sigma)=\prod_{i>j} \operatorname{sgn}(\sigma (i)-\sigma(j))=(-1)^{N(\sigma)}
$$

임을 보이라.

:::

</div>

::: {.solution}

정리 4.1.6  에서 임의의 치환$\sigma$ 와 호환 $\tau$ 에 대해  $N(\sigma \tau)\equiv N(\sigma)+1 \quad \operatorname{mod}2$ 임을 보았다. 즉 호환 한번마다 $N(\sigma)$ 의 짝/홀 이 바뀐다. $N(I)=0$ 이므로  $\operatorname{sgn}(\sigma)=(-1)^{N(\sigma)}$ 임을 알 수 있다. $i>j$ 에 대해 $\operatorname{sgn}(\sigma(i))-\sigma(j))$ 은 전도되었으면 $-1$, 전도되지 않았으면  $+1$ 이다. 따라서,
$$
\prod_{i>j} \operatorname{sgn}(\sigma(i)-\sigma(j))=(-1)^{N(\sigma)}
$$
이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_4_8} 

다음 치환의 전도의 수가 짝수인 지 또는 홀수인지를 밝히라.

$$
\begin{pmatrix} 1& 2& 3& 4& 5& 6& 7 & 8 & 9 \\9 & 8 & 7 & 6 & 5 & 4& 3& 2& 1 \end{pmatrix}
$$

:::

</div>

::: {.solution}

주어진 치환을 $A$ 라 하면,

$$
A=(1\;\;9)(2 \;\; 8)( 3\;\;7)(4\;\; 6)
$$

과 같으므로 짝치환이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_4_9} 

$n$ 차 정사각행렬  $A$ 와 $m$ 차 정사각행렬 $B$  에 대하여

$$
\det \begin{pmatrix} A & O \\ O & B \end{pmatrix}=(\det A) (\det B)
$$

임을 보이라.

:::

</div>

::: {.solution}

$n\times n$ 단위행렬 $I_n$ 과 $m\times m$ 단위행렬  $I_m$ 에 대해 $A'=\begin{pmatrix} A & O \\ O & I_m\end{pmatrix}$ , $B'=\begin{pmatrix} I_n & O \\ O & B\end{pmatrix}$ 라 하고 $C=\begin{pmatrix} A & O \\ O & B \end{pmatrix}$ 라 하면 $C=A'B'$ 이다.

$$
\det A' = \sum_{\sigma \in S_{n+m}} \operatorname{sgn}(\sigma) A'_{1\sigma(1)}\cdots A'_{n+m, \sigma(n+m)}
$$

인데  $j>n$ 일 경우  $A'_{j\sigma(j)}=\delta_{j,\sigma(j)}$ 이므로  $\sigma \not\in S_n \implies  A'_{1\sigma(1)}\cdots A'_{n\sigma(n)}=0$ 이다. 따라서,

$$
\det A'=\sum_{\sigma \in S_n}\operatorname{sgn}(\sigma) A'_{1\sigma(1)}\cdots A'_{n\sigma(n)}=\det (A)
$$

이다. 같은 방식으로 $\det B'=\det B$ 임을 보일 수 있다. 그렇다면, 

$$
\det C=(\det A')(\det B')=(\det A)(\det B)
$$ 

이다.

:::

</br>

## 제 7 장 탐구문제

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S01} 

임의의 $n$ 차 정사각행렬 $A,\,B$ 에 대하여 $B$ 가 가역이면

$$
e^{B^{-1}AB}=B^{-1}e^AB
$$
를 보이라.

:::

</div>

::: {.solution}

우리는 제 3절 정리 3.4.2 에서 임의의 정사각 행렬 $A$ 에 대해 $e^{A}$ 를 정의할 수 있음을 알았다. 또한,

$$
(B^{-1}AB)^n = B^{-1}A^nB
$$

임은 쉽게 보일 수 있다. 따라서,

$$
e^{B^{-1}AB}=\sum_{k=0}^\infty \dfrac{(B^{-1}AB)^k}{k!}=B^{-1}\left(\sum_{k=0}^\infty \dfrac{A^k}{k!}\right)B=B^{-1}e^AB
$$
이다.

:::

</br>

### 이후 문제를 풀기 위한 Summary

우리는 제 6장 탐구문제 11번에서 선형변환이 단사일 필요충분조건이 전사임을 보였다. (이것은 유한차원벡터공간에서 항상 성립한다) 즉 선형사상이 단사이면 전단사이다. 또한 제 6장 탐구문제 12번에서 선형변환에 대한 역사상이 존재하면 역사상도 선형사상임을 보였다. 즉, 선형사상 $L:\mathbb{R}^n \to \mathbb{R}^m$ 이 단사이면 전단사이고 역사상도 선형사상이다.

또한 선형사상 $L : \mathbb{R}^n \to \mathbb{R}^m$ 이 단사일 필요충분 조건은 $L(X)=0$ 의 해가 $O$ 일 때 뿐임을 보았다.( 연습문제 6장 2절 4번).

이를 정리하자.

</br>

**S1.**  선형사상 $L: \mathbb{R}^n \to \mathbb{R}^m$ 에 대해 세 명제는 동치이다.

&emsp;($1$) $L$ 은 단사이다.
&emsp;($2$) $L$ 은 전사이다.
&emsp;($3$) $L(X)=O$ 의 해는 자명해 뿐이다.

</br>

**S2.** 선형사상 $L:\mathbb{R}^n \to \mathbb{R}^m$ 이 단사이면 역사상이 존재하며 이 역사상도 선형사상이다.

(탐구문제, 연습문제에서 풀었으므로 증명은 필요 없을 것이다.)

</br>

**S3.** 또한 제 5장 6절의 따름정리 6.4.2 를 다시 쓰면,

&emsp;($1$) $n$ 공간에서 $n+1$ 개 이상의 벡터들은 일차종속이다.

&emsp;($2$) $n$-공간에서 $k$ 개의 벡터가 일차독립이면 $k\le n$ 이다.

&emsp;($3$) $k$ 개의 벡터가 $n$ 공간을 생성하면 $k\ge n$ 이다.

&emsp;($4$) $k$ 개의 벡터가 $n$ 공간의 기저이면 $k=n$ 이다.

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S02} 

만약 $n \ne m$ 이면, $n$ 차원 공간 $\mathbb{R}^n$ 과 $m$ 차원 공간 $\mathbb{R}^m$ 에는 전단사인 선형사상이 존재하지 않음을 보이라.

:::

</div>

::: {.solution}

$n<m$ 이면 이 선형사상은 전사일 수 없다. $\mathbb{R}^n$ 의 basis 를 $\bf{a}_1,\ldots,\, \bf{a}_n$ 이라 하고 임의의 선형사상 $L:\mathbb{R}^n \to \mathbb{R}^m$ 에 대해 $\bf{b}_i = L(\bf{a}_i)$ 라 하자. 그렇다면 $L$ 에 의한 치역은 $L(\bf{a}_1),\ldots,\ldots,\,L(\bf{a}_n)$ 의 선형결합으로 생성되며 **S3.**($3$) 에 따라 $R^m$ 을 생성 할 수 없다.

$n>m$ 이면 이 선형사상은 단사 일 수 없다. $L(\bf{a}_1),\ldots,\,L(\bf{a}_n)$ 가 일차독립이려면 **S3.**($1$) 의해 $n\le m$ 이어야 하는데 조건에 위배된다. 따라서 $L(\bf{a}_1),\ldots,\,L(\bf{a}_n)$ 은 일차종속이며, 따라서 $c_1L(\bf{a}_1)+\cdots c_n L(\bf{a}_n)=0$ 을 만족하는 nontrivial $(c_1,\ldots,\,c_n)$ 이 존재한다. 그런데,

$$
0=c_1L(\bf{a}_1)+\cdots c_n L(\bf{a}_n)=L(c_1\bf{a}_1+\cdots c_n\bf{a}_n)
$$

이므로 $L(X)=0$ 을 만족하는 $X\ne O$ 이 존재하므로 **S1.** 에 따라 $L$ 은 단사가 아니다.

따라서 $n\ne m$ 이면 $\mathbb{R}^n$ 과 $\mathbb{R}^m$ 사이에는 전단사인 선형사상이 존재하지 않는다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S03} 

$n$ 차 정사각행렬 $A$ 가 역행렬을 가지지 않으면, $AB=O$ 이 되는, 영 아닌 $n$ 차 정사각행렬 $B$ 가 존재함을 보이라.

:::

</div>

::: {.solution}

$A$ 가 역행렬을 가지지 않으면 $AY=O$ 를 만족하는 nontrivial $Y \in \mathbb{R}^n$ 가 존재함을 보이자.  $A$ 에 의해 표현되는 선형사상 $L_A:\mathbb{R}^n\to \mathbb{R}^n$ 을 생각하자. $X = (x_1,\ldots,\,x_n)^t\in \mathbb{R}^n$ 이고 $A=(a_{ij})$ 라 하면, $L_A(X)=AX$ 로 정의된다. 이제 $L_A$ 가 단사이면 (따라서 전단사이면) $L_A$ 의 역사상이 존재하며 이는 선형사상이다.

이제 $A$ 가 역행렬을 가진다는 것과 $L_A$ 가 역사상을 가진다는 것이 동치임을 보이자.

$A$ 가 역행렬 $A^{-1}$을 가진다고 하자. $L_A(X)=A(X)$ 이며 $(L_{A^{-1}}\circ L_{A})(X)=L_{A^{-1}}(AX)=A^{-1}AX=X$ 이며, 같은 방법으로 $(L_A \circ L_{A^{-1}})(X)=X$ 임을 보일 수 있다. 즉 $A^{-1}$ 에 의해 정해지는 $L_{A^{-1}}$ 은 $L_A$ 의 역사상이므로 행렬 $A$ 의 역행렬이 존재하면 $L_A$ 는 역사상을 가진다.

이제 $L_A$ 가 역사상을 가짐을 가정하자. 즉 $L_B \circ L_A = L_A \circ L_B = I_n$ 이므로 $BA=AB=I$ 인 $B$ 가 존재하는데 이는 정의상 $A$ 의 역행렬이다.

그리고,  **S1.** 에 따라 $A$ 가 역행렬을 가진다는 것과 $AX=O$ 을 만족하는 $X$ 는 자명해 뿐이라는 것이 동치이다. 즉 $A$ 가 역행렬을 갖지 않으면 $AX=O$ 를 만족하는 비자명해가 존재한다. 이제 $B$ 의 각 열벽터를 $AX=O$ 을 만족하는 $\mathbb{R}^n$ 벡터들로 구성하면 $AB=0$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S04} 

직교행렬의 행렬식의 값은 $1$ 또는 $-1$ 임을 보이라.

:::

</div>

::: {.solution}

직교행렬은 $A^tA=I$ 를 만족하는 정사각행렬 $A$ 를 말한다. 우리가 $\det A^t=\det A$ 임을 보이면 $\det(I)=1=(\det A^t)(\det A)$ 이므로 $\det A= \pm 1$ 이다. 이제 $\det A^t = \det A$ 임을 보이자.

$$
\det A=\sum_{\sigma \in S_n} \operatorname{sgn}(\sigma) A_{1\sigma(1)}\cdots A_{n\sigma(n)}
$$

이다. $\sigma$ 는 전단사함수이므로 항상 $\sigma^{-1}$ 이 존재하며 $\sigma^{-1}\in S_n$ 이다. 또한 모든 치환은 호환의 곱임을 알고 있다. (정리 4.1.2)  $\sigma = \tau_1\cdots \tau_n$ 이라 하면, $\tau_n \cdots \tau_1=\sigma^{-1}$ 이다. 따라서 $\operatorname{sgn}(\sigma)=\operatorname{sgn}(\sigma^{-1})$ 이다. 그리고, 임의의 $\sigma$ 에 대해 ($\sigma$ 가 전단함수임을 생각하면)

$$
A_{1\sigma(1)}\cdots A_{n\sigma(n)}=A_{\sigma^{-1}(1)1}\cdots A_{\sigma^{-1}(n)n}
$$

이다.

$$
\begin{aligned}
\det A^{t}&=\sum_{\sigma \in S_n}\operatorname{sgn}(\sigma) A_{\sigma(1)1}\cdots A_{\sigma(n)n} \\
&=\sum_{\sigma^{-1}\in S_n} \operatorname{sgn}(\sigma^{-1}) A_{1\sigma^{-1}(1)} \cdots A_{n\sigma^{-1}(n)}\\
&=\sum_{\phi\in S_n} \operatorname{sgn}(\phi) A_{1\phi(1)}\cdots A_{n \phi(n)}=\det A
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S05} 

어떤 집합 $X$ 에서 정의된 함수 $y_1(x),\ldots,\,y_n(x)$ 에 대하여 항등식

$$
c_1y_1 + \cdots + c_n y_n(x)=0
$$

이 성립하는 경우가 자명한 상수인 경우 ($c_1=\cdots =c_n=0$)뿐이면, 힘수 $y_1,\ldots,\,y_n$ 을 일차독립이라고 부른다. 또 $y_1,\ldots,\,y_n$ 이 일차독립이 아니면, 일차종속이라고 부른다. 이제 실수체에서 정의된 함수

$$
1,\,x,\,x^2,\ldots,\,x^n
$$

는 일차독립임을 보이라. 또,

$$
1,\,\cos x,\, \cos 2x,\ldots,\, \cos nx,\,\sin x,\,\sin 2x,\ldots,\, \sin nx
$$

도 일차독립임을 보이라.

:::

</div>

::: {.solution}
$$
c_0+c_1x+\cdots +c_nx^n=0
$$

이라 하자. 여기서 $0$ 은 실수 $0$ 이 아니라 $0$ 함수, 즉 모든 $x\in \mathbb{R}$ 에 대해 $f(x)=0$ 인 함수 $f$ 를 의미한다. 이것은 상수함수이므로 무한번 미분 가능하며 그 도함수는 모든 실수구간에서 $0$ 이다, $k$ 번 미분하고 $x=0$ 을 넣으면 $c_k=0$ 을 얻는다. 따라서 일차독립이다.

또한,

$$
g(x)=a_0+a_1\cos x + \cdots + a_n \cos nx + b_1\sin x + \cdots +b_n \sin nx=0
$$

이라 하자. 임의의 자연수 $m\ne n$ 에 대해,

$$
\begin{aligned}
\int_0^{2\pi} \cos mx  \cos nx
\,dx &=\dfrac{1}{2} \int_0^{2\pi}  \left[\cos (m+n)x + \cos(m-n)x\right]\,dx=0\\
\int_0^{2\pi} \sin mn \sin nx \, dx &= \dfrac{1}{2} \int_0^{2\pi} \left[ \cos (m-n)x - \cos (m+n)x\right]\, dx.=0
\\
\int_0^{2\pi} \sin mx \cos nx\,dx & = \dfrac{1}{2}\int_0^{2\pi} \left( \sin (m+n)x + \sin (m-n)x   \right)\,dx = 0\;,\\
\end{aligned}
$$

이며 $m \ne 0$ 에 대해

$$
\begin{aligned}
\int_0^{2\pi} \cos^2 mx \, dx & = \dfrac{1}{2} \int_0^{2\pi} (\cos 2mx +1)\,dx = \pi \\
\int_0^{2\pi} \sin^2 mx\, dx &=\dfrac{1}{2} \int_0^{2\pi} (1-\cos 2mx)\, dx = \pi
\end{aligned}
$$

임을 이용한다. 이제 $g(x)=0$ 이므로 임의의  $m\in \mathbb{N}$ 에 대해  

$$
\displaystyle \int_0^{2\pi}g(x)\sin mx \, dx = \int_0^{2\pi} g(x) \cos mx\, dx=0
$$ 

이다. 이를 이용하면

$$
\begin{aligned}
0=\int_0^{2\pi}g(x) \sin mx\, dx = \pi b_m \implies b_m =0  \quad{\forall}m=1,\ldots,\,n\\
0 = \int_0^{2\pi} g(x) \cos mx\, dx = \pi a_m \implies a_m =0 \quad{\forall}m=1,\ldots,\,n6.
\end{aligned}
$$

따라서  $g(x)=a_0=0$ 이므로 $a_0=0$ 이다. 즉 일차독립이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S06}

두 함수  $y_1,\,y_2 :\mathbb{R} \to \mathbb{R}$ 이 일차종속이면,

$$
W(y_1,\,y_2) :=\det \begin{pmatrix} y_1 & y_2 \\ y'_1 & y'_2 \end{pmatrix}
$$

가 항등적으로 $0$ 임을 보이라. 또 함수 $y_1,\, y_2,\,y_3$ 가 일차종속이면, 이들의 **Wronskian**

$$
W(y_1,\,y_2,\,y_3):=\det \begin{pmatrix} y_1 & y_2 & y_3 \\  y_1' & y_2' & y_3' \\  y_1'' & y_2'' & y_3'' \end{pmatrix}
$$

가 항등적으로 $0$ 임을 보이라.

:::

</div>

::: {.solution}

$y_1,\ldots,\,y_n$ 이 일차종속이면 $c_1y_1+\cdots + c_n y_n=0$ 을 만족하는 nontrivial $c_1,\ldots,\, c_n$ 이 존재한다. 이를 $k$ 번 미분해도 이 $(c_1,\ldots,\,c_n)$ 에 대해

$$
c_1 y_1^{(k)}+ \cdots+ c_n y_n^{(k)}=0
$$

이다. 정사각 행렬 $A_{ij}=y_j^{(i-1)}$  과 $C=\begin{pmatrix}c_1 & \cdots & c_n \end{pmatrix}^t$ 를 생각하면, $AX=0$ 의 nontrivial solution $C$ 가 존재하는 것이며 따라서  $\det A=0$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S07} 

행렬함수

$$
A(X)=(a_{ij}(x))
$$

의 미분은 각 항의 미분으로 이루어진 행렬

$$
A'(x) =\left(a'_{ij}(x)\right)
$$

를 뜻한다. 이제

$$
\begin{aligned}
\dfrac{d}{dx} &\det \begin{pmatrix} a_{11}(x) & a_{12}(x) & a_{13}(x) \\ a_{21}(x) & a_{22}(x) & a_{23}(x) \\ a_{31}(x) & a_{32}(x) & a_{33}(x) \end{pmatrix} \\
&=  \det \begin{pmatrix} a_{11}'(x) & a'_{12}(x) & a'_{13}(x) \\ a_{21}(x) & a_{22}(x) & a_{23}(x) \\ a_{31}(x) & a_{32}(x) & a_{33}(x) \end{pmatrix} +  \det \begin{pmatrix} a_{11}(x) & a_{12}(x) & a_{13}(x) \\ a'_{21}(x) & a'_{22}(x) & a'_{23}(x) \\ a_{31}(x) & a_{32}(x) & a_{33}(x) \end{pmatrix}\\
&+ \det \begin{pmatrix} a_{11}(x) & a_{12}(x) & a_{13}(x) \\ a_{21}(x) & a_{22}(x) & a_{23}(x) \\ a'_{31}(x) & a'_{32}(x) & a'_{33}(x) \end{pmatrix}
\end{aligned}
$$
임을 보이라.

:::

</div>

::: {.solution}

$$
A = \begin{pmatrix} a_{11}(x) & a_{12}(x) & a_{13}(x) \\ a_{21}(x) & a_{22}(x) & a_{23}(x) \\ a_{31}(x) & a_{32}(x) & a_{33}(x) \end{pmatrix}
$$ 

라 하면,

$$
\det (A) = \sum_{\sigma \in S_3} \text{sgn}(\sigma) a_{1\sigma(1)}a_{2\sigma(2)}a_{3\sigma(3)}
$$

이므로,

$$
\begin{aligned}
\dfrac{d}{dx} \det A(x) & = \sum_{\sigma \in S_3} \text{sgn}(\sigma) a'_{1\sigma(1)}a_{2\sigma(2)}a_{3\sigma(3)} + \sum_{\sigma \in S_3} \text{sgn}(\sigma) a_{1\sigma(1)}a'_{2\sigma(2)}a_{3\sigma(3)} \\
& + \sum_{\sigma \in S_3} \text{sgn}(\sigma) a_{1\sigma(1)}a_{2\sigma(2)}a_{\sigma(3)} \\
&= \det \begin{pmatrix} a_{11}'(x) & a'_{12}(x) & a'_{13}(x) \\ a_{21}(x) & a_{22}(x) & a_{23}(x) \\ a_{31}(x) & a_{32}(x) & a_{33}(x) \end{pmatrix} +  \det \begin{pmatrix} a_{11}(x) & a_{12}(x) & a_{13}(x) \\ a'_{21}(x) & a'_{22}(x) & a'_{23}(x) \\ a_{31}(x) & a_{32}(x) & a_{33}(x) \end{pmatrix}\\
& +  \det \begin{pmatrix} a_{11}(x) & a_{12}(x) & a_{13}(x) \\ a_{21}(x) & a_{22}(x) & a_{23}(x) \\ a'_{31}(x) & a'_{32}(x) & a'_{33}(x) \end{pmatrix}
\end{aligned}
$$
:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S08}

$n$ 차 정사각행렬 전체의 집합을  $\mathcal{M}_n$ 이라고 두자. 만약 함수 $f:\mathcal{M}_n\to \mathbb{R}$  이

($i$) 임의의 $A,\,B\in \mathcal{M}_n$ 에 대하여 $f(AB)=f(A)f(B)$ 이고,

($ii$) 대각원이 차례로 $\lambda_1,\,1,\ldots,\, 1$ 로 주어진 임의의 대각행렬 $D_{\lambda}$ 에 대하여 $f(D_\lambda)=\lambda$ 이면,

$f=\det$ 임을 보이라.

:::

</div>

::: {.solution}

*임의의 정사각행렬은 대각화 가능한 두 행렬의 곱으로 나타냄을 보이면 된다고?????*

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S09}

좌표평면에서 행렬식 값이 $0$ 이 되지 않는 자기선형사상에 대하여, 타원의 상은 여전히 타원인가? 또 포물선이나 쌍곡선의 상은 여전히 타원인가?

:::

</div>

::: {.solution}

*to be done*

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S10} 

#### 수반행렬 (adjoint matrix) 
 
 $n$ 차 정사각행렬 $A$ 의 $i$ 번째 행과 $j$ 번 째 쳘을 제거한 $n-1$ 차 정사각행렬을 $A_{ij}$ 라고 하였을 때, 임의의 $i$ 에 대하여

$$
\det A=\sum_{j=1}^n (-1)^{i+j} a_{ij}\det A_{ij}
$$

임을 보이라. 또 임의의 $j$ 에 대하여

$$
\det A = \sum_{i=1}^n (-1)^{i+j} a_{ij}\det A_{ij}
$$

임을 보이라. 또 $i \ne j$ 이면

$$
\sum_{k=1}^n (-1)^{j+k} a_{ik}\det A_{jk}=0=\sum_{k=1}^n (-1)^{j+k} a_{ki}\det A_{kj}
$$

임을 보이라. 이제 $(i,\,j)$ 항이 $(-1)^{i+j}\det A_{ji}$ 로 주어진 $n$ 차 정사각행렬 $\operatorname{adj} A$ 를 $A$ 의 수반행렬이라 하면,

$$
A(\operatorname{adj}A)=(\det A)I=(\operatorname{adj}A)A
$$

임을 보이라. 특히 $A$ 가 가역행렬이면,

$$
A^{-1}=\dfrac{1}{\det A} \operatorname{adj}A
$$

임을 보이라.

::: 

</div>

::: {.solution}

($1$) 우리는 문제 4 에서 $\det A^t = \det A$ 임을 보였다. 이것은 행렬의 열에관한 정리 3.0.3 과 따름정리 3.0.4 가 행에 대해서도 그대로 성립함을 말한다. 여기서는 주로 행에 대한 연산을 말할 것이다.

($2$) $n$ 공간에서 $i$ 번 째 행은 $\displaystyle \sum_{j=1}^n a_{ij}\bf{e}_j$ 로 쓸 수 있다. 그리고 $i$ 번째 행이 $\bf{e}_j$ 일 때의 행렬식을 $\overline{A}_j$ 라 하자. 그렇다면

$$
\overline{A}_j = \begin{pmatrix} a_{11} &\cdots & a_{1(j-1)} & a_{1j} & a_{1(j+1)} & \cdots &a_{1n} \\ \vdots & & & & & &\vdots\\
a_{(i-1)1} & \cdots & a_{(i-1)(j-1)} &a_{(i-1)j} & a_{(i-1)(j+1)} & \cdots & a_{(i-1)n} \\
0 & \cdots & 0 &1 & 0 &\cdots & 0 \\
a_{(i+1)1} & \cdots & a_{(i+1)(j-1)} &a_{(i+1)j} & a_{(i+1)(j+1)} & \cdots & a_{(i+1)n} \\
\vdots & & & & & &\vdots\\
a_{n1} &\cdots & a_{n(j-1)} & a_{nj} & a_{n(j+1)} & \cdots &a_{nn}
\end{pmatrix}
$$

이다.  따름정리 3.0.4 (1) 의 행에 대한 응용에 의해,

$$
\det A = \sum_{j=1}^n a_{ij}\det(\overline{A_j}) \tag{10.1}
$$

이다. $i$ 번째 행을 첫째 행으로 그리고 1번부터 $i-1$ 번째 행까지는 행번호가 하나씩 늘어나는 행렬(즉 $i$ 번째 행이 맨 첫번째 행으로 바뀌고 1행부터 $i-1$ 행까지는 아래로 하나씩 밀리는 행렬)을 $A'_j$ 이라 하면,

$$
A'_j =  \begin{pmatrix} 0 & \cdots & 0 &1 & 0 & \cdots & 0 \\
a_{11} &\cdots & a_{1(j-1)} & a_{1j} & a_{1(j+1)} & \cdots &a_{1n} \\
\vdots & & & & & &\vdots\\
a_{(i-1)1} & \cdots & a_{(i-1)(j-1)} &a_{(i-1)j} & a_{(i-1)(j+1)} & \cdots & a_{(i-1)n} \\
a_{(i+1)1} & \cdots & a_{(i+1)(j-1)} &a_{(i+1)j} & a_{(i+1)(j+1)} & \cdots & a_{(i+1)n} \\
\vdots & & & & & &\vdots\\
a_{n1} &\cdots & a_{n(j-1)} & a_{nj} & a_{n(j+1)} & \cdots &a_{nn}
\end{pmatrix}
$$

이고, 행끼리 $(i-1)$ 번의 치환을 한 것이므로, 따름정리 3.0.4 (2) 의 행에 대한 응용에 의해

$$
\det A'_j=(-1)^{i-1} \det \overline{A}_j
$$

이다. 이제 행렬의 첫행은 $\bf{e}_j$ 이다. 이제 $j$ 번째 열을 첫번째로 옮기고 $1$ 번 열부터 $j-1$ 번 열까지 뒤로 한칸씩 민 행렬을 $A''_j$ 라 하면

$$
A''_j =  \begin{pmatrix}1 &  0& \cdots &0 & 0 &\cdots & 0 \\
a_{1j} & a_{11} &\cdots & a_{1(j-1)} &  a_{1(j+1)} & \cdots &a_{1n} \\ \vdots & & & & & &\vdots\\
a_{(i-1)j} & a_{(i-1)1} & \cdots & a_{(i-1)(j-1)} &a_{(i-1)(j+1)} & \cdots & a_{(i-1)n} \\
a_{(i+1)j} & a_{(i+1)1} & \cdots & a_{(i+1)(j-1)} & a_{(i+1)(j+1)} & \cdots & a_{(i+1)n} \\
\vdots & & & & & &\vdots\\
a_{nj} & a_{n1} &\cdots & a_{n(j-1)} & a_{n(j+1)} & \cdots &a_{nn}
\end{pmatrix}
$$

이고, 행끼리 $j-1$ 번의 치환을 한 것이므로,

$$
\det A''_j = (-1)^{j-1} \det A'_j =(-1)^{i+j-2}\det \overline{A}_j=(-1)^{i+j}\det \overline{A}_j \tag{10.2}
$$

이다. 이제 $B$ 가 $n \times n$ 행렬이고 $B$ 의 첫 행이 $\bf{e}_1$ 인 행렬 일 때 $\det B$ 는 1행과 1열을 제거한 나머지 $(n-1)\times (n-1)$ 행렬 $B_0$ 의 행렬식과 같음을 보이자.
$$
\operatorname{sgn}(\sigma) B_{1\sigma(1)}=\operatorname{sgn}(\sigma)\delta_{1,\sigma(1)}
$$

이며 $S_n$ 중 $\sigma(1)=1$ 인 것의 집합은 $\{2,\ldots,\,n\}$ 의 치환의 집합(을 $S'$ 이라 할 때) 과 전단사 대응이 존재하며 이 둘 의 $\operatorname{sgn}$ 함수값은 변하지 않음도 쉽게 알 수 있다. 즉

$$
\det B = \sum_{\sigma\in S_n} \operatorname{sgn}(\sigma)B_{1\sigma(1)}\cdots B_{n\sigma(n)} =\sum_{\sigma'\in S'}\operatorname{sgn}(\sigma')B_{2\sigma'(2)} \cdots B_{n \sigma'(n)}=\det (B_0)
$$

이다. 그렇다면 $A''_j$ 의 1행과 1열을 제거한것은 문제에서 정의된 $A_{ij}$ 와 같으므로

$$
\det (A''_j)=\det A_{ij}
$$

이며, 식 (10.1), (10.2) 로 부터,

$$
\det A=\sum_{j=1}^n a_{ij}\det \overline{A}_j = \sum_{j=1}^n  (-1)^{i+j} a_{ij} \det A_{ij}
$$

임을 보였다.

($3$) ($2$) 번 과정을 열에 대해 수행하면

$$
\det A = \sum_{i=1}^n (-1)^{i+j} a_{ij}\det A_{ij}
$$

를 얻을 수 있다.

($4$) $i \ne j$ 라 하자.  $\displaystyle \sum_{k=1}^{n}(-1)^{j+k}a_{ik}\det A_{jk}$ 는 행렬 $A$ 의 $j$ 번째 행을 $i$ 번째 행으로 바꾼 행렬의 행렬식인데 이 행렬에 동일한 행이 존재하므로 이 행렬의 행렬식은 $0$ 이다. 또한 $\displaystyle \sum_{k=1}^n (-1)^{j+k} a_{ki}\det A_{kj}$ 는 행렬의 $j$ 번째 열을 $i$ 번째 열로 바꾼 행렬의 행렬식으로 그 값은 $0$ 이다. 따라서,

$$
\sum_{k=1}^n (-1)^{j+k} a_{ik}\det A_{jk}=0=\sum_{k=1}^n (-1)^{j+k} a_{ki}\det A_{kj}
$$

이다.

($5$) ($4$) 의 결과를 이용하면,

$$
\begin{aligned}
\left[A (\operatorname{adj}A)\right]_{ij} &= \sum_{k=1}^na_{ik}(\operatorname{adj}(A))_{kj}=\sum_{k=1}^n a_{ik}(-1)^{k+j}\det A_{jk}=\delta_{ij}\det A \\
\left[\operatorname{adj}(A) A\right]_{ij} &= \sum_{k=1}^n (\operatorname{adj}(A))_{ik}a_{kj}= \sum_{k=1}^n (-1)^{i+k}\det A_{ki} a_{ij}=\delta_{ij}\det A
\end{aligned}
$$

이므로 $A(\operatorname{adj}A)=(\det A) I=(\operatorname{adj}A)A$ 이다.

($6$) $I=A \left(\dfrac{1}{\det A} \operatorname{adj} A\right) =  \left(\dfrac{1}{\det A} \operatorname{adj} A\right)A$ 이므로 $A$ 가 가역이면 $A^{-1}=\dfrac{1}{\det A} \operatorname{adj} A$ 이다.

:::

</br>

**11. , 12.** 번은 생략.

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S13} 

#### 크래머 의 공식 

$n$ 차 가역행렬 $A$ 와 $\bf{x}=\begin{pmatrix} x_1 \\ \vdots \\ x_n \end{pmatrix}$ , $\bf{c}=\begin{pmatrix}c \\ \vdots \\ c_n \end{pmatrix}$ 에 대하여 방정식

$$
A\bf{x}=\bf{c}
$$

의 해는

$$
x_j =\dfrac{\det (\bf{a}_1,\ldots, \bf{a}_{j-1},\, \bf{c},\,\bf{a}_{j+1},\ldots, \bf{a}_n)}{\det A} \qquad (j=1,\,2,\ldots,\,n)
$$

임을 보이라. 여기서 $\bf{a}_j$ 는 $A$ 의 $j$ 번째 열을 나타낸다.

:::

</div>

::: {.solution}

$A$ 가 가역행렬이라는것과 @exr-CAL_7_S10 의 결과를 이용하면,

$$
\bf{x}=A^{-1}\bf{c}=\dfrac{1}{\det A} (\operatorname{adj} A)\bf{c}
$$

이다. 행렬 $A$ 에서 $j$ 번째 열을 $\bf{c}$ 로 바꾼 것을 $A(j)$ 라 하면,

$$
\det A(j) =\sum_{k=1}^n (-1)^{j+k}A(j)_{kj} \det A(j)_{kj}=\sum_{k=1}^n (-1)^{j+k}c_k \det A_{kj}
$$

이다. 그렇다면,

$$
\begin{aligned}
x_{j} = \dfrac{1}{\det A} \sum_{k=1}^n (-1)^{j+k}\det A_{kj}c_{k}=\dfrac{\det A(j)}{\det A}
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S14}

정사각행렬 $A$ 의 각 항이 모두 정수이고 $\det A=1$ 이면 $A^{-1}$ 의 각 항도 모두 정수임을 보이라.

:::

</div>

::: {.solution}

$\displaystyle \det A= \sum_{\sigma \in S_n} \operatorname{sgn}(\sigma)a_{1\sigma(1)}\cdots a_{n \sigma(n)}$ 로 부터 우리는 각 항이 모두 정수인 정사각행렬 $A$ 에 대해 $\det A$ 도 정수임을 알 수 있다. $\det A=1$ 이면 가역행렬이고 $A^{-1}$ 의 $j$ 번째 열을 $X$ 라 하면 $AX=\bf{e}_j$ 임을 알 수 있다. 크라머의 공식으로 부터

$$
X_j = \sum_{k=1}^n (-1)^{j+k}\det A_{kj}\delta_{jk}=\det A_{jj}
$$

인데 $A_{jj}$ 역시 정수로 이루어진 행렬이므로 $\det A_{jj}$ 가 정수이고 따라서 $X$ 는 정수행렬이며,  $A^{-1}$ 역시 정수행렬이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S15}

$n$ 차 정사각행렬 $A$ 의 처음 $n-1$ 개의 행과 열로 이루어진 $n-1$ 차 행렬을 $B$ 라 두고

$$
A=\begin{pmatrix} B & C \\ C^t & d\end{pmatrix}
$$

로 두자. 이때 $B$ 가 가역이면

$$
\det A= (d-C^tB^{-1}C)\det B
$$

을 보이라. 또 $B$ 가 가역이 아니더라도

$$
\det A = d \cdot \det B - C^t(\operatorname{adj}B)C
$$

임을 보이라.

:::

</div>

::: {.solution}

일단

$$
\det A = d \cdot \det B - C^t(\operatorname{adj}B)C = \det B \left( d-C^t \dfrac{\operatorname{adj} B}{\det B} C \right)
$$

이며 $B$ 가 가역행렬이면 $B^{-1}=\dfrac{\operatorname{adj} B}{\det B}$ 이므로 $\det A = d \cdot \det B - C^t(\operatorname{adj}B)C$ 만 보이면 된다.

$$
\det A= \sum_{j=1}^n (-1)^{i+j}a_{ij}\det A_{ij}
$$

이며 $i=n$ 으로 놓으면 $a_{nn}=d$ 이고 $j\ne n$ 일 때 $a_{nj}=(C^t)_{j}$ 이므로

$$
\begin{aligned}
\det A &= \sum_{j=1}^n (-1)^{n+i}a_{nj}\det A_{nj} \\[0.3em]
&= (-1)^{2n}d \cdot\det B+\sum_{j=1}^{n-1} (-1)^{n+j}(C^t)_{j} \det(A_{nj})\\[0.3em]
&= d \cdot \det B +\sum_{j=1}^{n-1} (-1)^{n+j}(C^t)_{j} \det(A_{nj}) 
\end{aligned}\tag{1}
$$

이다. $j<n$ 일 때, $\det(A_{nj})$ 는 행렬 $B$ 에서 $j$ 번째 열을 빼고 남은 $(n-1)\times (n-2)$ 행렬에 마지막 열로 $C$ 를 넣은 행렬의 행렬식이다.  


*to be done*

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S16} 

$$
\det \begin{pmatrix} 1 & 2 & 1 \\ 2 & 5 & 3 \\ 8 & 2& 5\end{pmatrix} \equiv 0 \quad \operatorname{mod}\; 11
$$

임을 보이라.

:::

</div>

::: {.solution}

첫번째 행에 100을 곱한것과 두번째 행에 10을 곱한것과 세번째 행을 더하여 세번째 행에 두더라도 행렬식 값은 바뀌지 않는다. 따라서,

$$
\det \begin{pmatrix} 1 & 2 & 1 \\ 2 & 5 & 3 \\ 8 & 2& 5\end{pmatrix} =\det \begin{pmatrix} 1 & 2 & 121 \\ 2 & 5 & 253 \\ 8 & 2& 825\end{pmatrix}
$$

이다. 행렬식의 각 term 에는 121, 253, 825 중 하나가 들어가는데 이는 모두 11로 나누어 떨어지는 수이다. 따라서 증명 끝.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S17} 

격자 $L$ 의 한 기저를 $\bf{v}_1,\ldots,\,\bf{v}_k$ 라 하고 또 다른 기저를 $\bf{w}_1,\ldots,\,\bf{w}_k$ 라고 하자. 이 때,

$$
\bf{w}_j = \sum_{i=1}^n a_{ij}\bf{v}_i
$$

로 두었을 때,

$$
|\det (a_{ij})|=1
$$

임을 보이라.

:::

</div>

::: {.solution}

$\{\bf{v}_1,\ldots,\,\bf{v}_k\}\in L$ 이며 $\{\bf{w}_1,\ldots,\,\bf{w}_k\}\in L$ 이므로 $a_{ij}\in \mathbb{Z}$ 이어야 한다. $A=(a_{ij})$ 라 하면 $A$ 는 가역행렬 이어야 하며 같은 이유로 $A^{-1}$ 도 정수행렬이어야 한다. 따라서 $\det A$ 와 $\det A^{-1}$ 이 정수이다. 그런데 $(\det A ) (\det A^{-1})=1$ 이어야 하므로 가능한 값은 $\det A=\pm 1$ 뿐이다.

:::

</br>

**18.**  

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S19} 

모든 정사각행렬은 가역행렬로 이루어진 수열의 극한값임을 설명하여라.

:::

</div>

::: {.solution}

가역행렬이 아닌 행렬에 대해서만 생각하면 된다. 예를 들어 생각해보자. $O$ 행렬의 경우는 $\displaystyle \lim_{k \to \infty}\dfrac{1}{k} I_n$ 이며 대각행렬의 경우는 비가역 행렬이면 대각성분에 $0$ 이 존재하므로 $0$ 을 $\dfrac{1}{k}$ 로 바꾸고 $\displaystyle \lim_{k \to \infty}$ 를 취하면 된다.

$n \times n$ 행렬 $A$ 의 각 열을 $A_i$ 라 하자. $A$ 가 비가역 행렬이면 $\{A_1,\ldots,\, A_n\}$ 중에 일차종속인 것이 존재한다. 이제 여기서 일차독립인 수열은 남겨놓고, 이것으로부터 이것들과 일차독립인 벡터들을 모아 $n$ 공간의 basis 를 구성 할 수 있다. 이를 $B_1,\ldots,\,B_m$ 이라 하자. 즉 $\{A_1,\ldots,\,A_n\}$ 에는 일차독립인 벡터 $n-m$ 개가 있고, 이들과 일차종속인 열벡터 $m$ 개가 있다. 이 일차종속인 열벡터에 순서대로 $\dfrac{1}{k}B_1,\ldots,\dfrac{1}{k}B_k$ 를 더한 행렬 $D_k$ 를 생각한다. 즉 $A_p$ 가 일차종속인 $j$ 번째 열벡터이면 $D_k$ 의 $p$ 번째 열벡터는 $A_p+\dfrac{1}{k}B_j$ 이다.

당연히 $D_k$ 의 열벡터들은 서로 일차독립이 되며 따라서 $D_k$ 는 가역행렬이고 $\displaystyle \lim_{k \to \infty}D_k = A$ 이다.

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S20} 

$n$-벡터 $\bf{v}_1,\ldots,\,\bf{v}_n$ 에 대하여

$$
\det (\bf{v}_1,\ldots,\,\bf{v}_n)>0
$$

이면, 기저 $(\bf{v}_1,\ldots,\,\bf{v}_n)$ 은 **양으로 향하여** 있다고 부르고,

$$
\det (\bf{v}_1,\ldots,\,\bf{v}_n)<0
$$

이면 $(\bf{v}_1,\ldots,\,\bf{v}_n)$ 은 **음으로 향하여** 있다고 부른다. 이제 벡터 $\bf{v}_1,\ldots,\,\bf{v}_n$ 이 시각에 따라 연속적으로 변한다고 하자. 시각 $t=0$ 일 때 이들이 양으로 향하여 있고 시각 $t=1$ 일 때 음으로 향하여 있으면, 어느 시각에서 $\bf{v}_1,\ldots,\bf{v}_n$ 이 일차종속임을 보이라.

:::

</div>

::: {.solution}

말인 즉슨 어느 시각에서 $\det (\bf{v}_1,\ldots,\,\bf{v}_n)=0$ 이 된다는 뜻이다. $\bf{v}_1(t)=(v_{11}(t),\ldots,\,v_{1n}(t))$  라 하자. 뒤에 배우겠지만 $\bf{v}_1(t)$ 가 $t$ 에 대해 연속적으로 변한다는 것은 각 $v_{11}(t),\ldots,\,v_{1n}(t)$ 가 모두 시간에 대해 연속적이란 말과 동치이다. (9.1 매개화된 곡선 을 보라.)  

이렇게 $\bf{v}_k(t) = (v_{k1}(t),\ldots,\, v_{kn}(t))$ 로 정의하고 행렬 $V(t)=(v_{ij}(t))$ 라 정의하자. 문제의 조건에 의해 $v_{ij}(t)$ 가 연속함수이며 $\det V(t)$ 는 이런 $v_{ij}(t)$ 의 유한개의 곱들의 합이므로 $\det V(t)$ 는 $t$ 에 대한 연속함수이다. (당연하겠지?)

이제 $\det V(t=0)>0$ 이며 $\det V(t=1)<0$ 이고 $\det V(t)$ 는 연속함수 이므로 평균값 정리에 의해 어떤 $t_0\in (0,\,1)$ 에서 $\det V(t_0)=0$ 이다. 즉 $(\bf{v}_1(t_0),\ldots,\,\bf{v}_n(t_0))$ 은 일차종속이다.

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S21} 

표준단위벡터 $\bf{e}_1,\ldots,\,\bf{e}_n$ 에 대하여 $n$ 공간의 기저 $(\bf{e}_1,\ldots,\,\bf{e}_n)$ 양으로 향해 있음을 보이라.

:::

</div>

::: {.solution}

trivial.

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S22} 

임의의 $n$ 차 정사각행렬 $A,\,B$ 에 대하여, $B$ 가 가역이면,

$$
(B^{-1}AB)^k = B^{-1}A^kB \qquad (k=1,\,2,\,3,\ldots)
$$

임을 보이라. 임의의 다항식 $p(x)$ 에 대하여,

$$
p(B^{-1}AB)=B^{-1}p(A)B
$$

임을 보이라.

:::

</div>

::: {.solution}

($1$) 우선 induction으로 증명한다. $k=1$ 일 때 자명하다. $n$ 일 때 성립함을 가정한다.

$$
(B^{-1}AB)^{n+1}=(B^{-1}AB)^n B^{-1}AB=B^{-1}A^nBB^{-1}AB=B^{-1}A^{n+1}B
$$

이다.

($2$) $p(x)=a_0 + a_1x+\cdots +a_nx^n$ 이면,

$$
\begin{aligned}
p(B^{-1}AB)&=a_0 + a_1(B^{-1}AB)+ a_2(B^{-1}AB)^2 + \cdots + a_n (B^{-1}AB)^n \\
&=a_0 +a_1(B^{-1}AB)+a_2B^{-1}A^2B+\cdots + a_n B^{-1}A^nB\\
&=B^{-1}(a_0 +a_1A+a_2 A^2+\cdots + a_nA^n)B^{-1}\\
&=B^{-1}p(A)B^{-1}
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_7_S23} 

$n$ 차 정사각행렬 $A,\,B$ 에 대하여 $B$ 가 가역이면

$$
\operatorname{tr} (B^{-1}AB)=\operatorname{tr}A
$$

임을 보이라.

:::

</div>

::: {.solution}

우선 $n$ 차 정사각행렬 $A,\,B$ 에 대해 $\operatorname{tr}(AB)=\operatorname{tr}(BA)$ 임을 안다. $B^{-1}A$ 도 $n$ 차 정사각행렬이므로,

$$
\operatorname{tr}(B^{-1}AB)=\operatorname{tr}(ABB^{-1})=\operatorname{tr}(A)\;.
$$ 

:::

