---
title: "벡터"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

</br>

## 연습문제 : 제 5장 1 절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_1_1} 

다음을 보이라.

($1$) 평행이동은 전단사 함수이다.

($2$) 평행이동에서는 한 점이 어디로 가는가를 알면, 임의의 점이 어디로 가는가를 알 수 있다.

($3$) 임의의 두 점 $A,\,B$ 에 대하여 $A$ 를 $B$ 로 옮기는 평행이동이 존재하고, 오직 하나 뿐이다.

($4$) 만약 $T:\mathbb{R}^n \to\mathbb{R}^n$ 이 평행이동이면,

$$
X \mapsto \operatorname{dist}(X,\,T(X)) \qquad (X\in \mathbb{R}^n)
$$

는 상수함수이다.

:::

</div>

::: {.solution}

($1$) 평행이동 함수 $T_{\bf{v}}:\mathbb{R}^n \to \mathbb{R}^n$ 가 어떤 $\bf{v}\in \mathbb{R}^n$ 에 대해 $T_{\bf{v}}(X):X + \bf{v}$ 로 정의된다고 하자. $X_1+\bf{v}=X_2+\bf{v}\implies X_1=X_2$ 이므로 $T_{\bf{v}}$ 는 단사이다. 임의의 $Y\in \mathbb{R}^n$ 에 대해 $X=Y-\bf{v}$ 이면 $T_\bf{v}(X)=Y$ 이므로 $T_{\bf{v}}$ 는 전사이다. 따라서 전단사이다.

($2$) 우리는 어떤 평행이동 $T_{\bf{v}}$ 에 대해 $T_{\bf{v}}(A)=B$ 임을 안다고 하자. $A+\bf{v}=B$ 이므로 $\bf{v}=B-A$ 로 정해진다. 따라서 임의의 $X\in \mathbb{R}^n$ 에 대해

$$
T_{\bf{v}}(X)=X+(B-A)
$$

이다.

($3$) ($2$) 에 의해 $A$ 를 $B$ 로 옮기는 평행이동이 존재함을 안다. 다른 평행이돈 $T_{\bf{v'}}=X+\bf{v'}$ 이 존재하여 $A$ 를 $B$ 로 보낸다면 $A+\bf{v}'=B$ 이므로 $\bf{v}=\bf{v}'$ 이 된다. 따라서 $T_{\bf{v}}=T_{\bf{v}'}$ 이므로 오직 하나 뿐이다.

($4$) 임의의 $\bf{v}\in\mathbb{R}^n$ 에 대해 $T(X)=X+\bf{v}$ 이면 $\operatorname{dist}(X,\, T(X))=\operatorname{dist}(X,\, X+\bf{v})=\operatorname{dist}(0,\, \bf{v})$ 이므로 $X$ 와 무관한 상수함수이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_1_2}

$n$-공간에서 점 $P$ 에 대한 점대칭 변환 (central symmetry)

$$
s_P : X \to s_P(X)
$$

는 식 $\dfrac{1}{2} (X+s_P(X))=P$ 가 만족되도록 주어진다. 즉,

$$
s_P(X)=2P-X
$$

이다. 이 때 두 점 $P_1,\,P_2$ 에 대한 점대칭변환의 합성 $s_{P_1}\circ s_{P_2}$ 는 어떠한 변환인가?

:::

</div>

::: {.solution}

$$
(s_{P_1}\circ s_{P_2})(X) = s_{P_1}(2P_2-X)=2P_1-(2P_2-X)=2P_1-2P_2+X
$$

이므로 $X$ 에 대해 $2P_1-2P_2$ 만큼의 평행이동이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_1_3}

$n$-공간에서 점 $P$ 를 중심으로 하고, 닮음비가 $c\in \mathbb{R}$ 인 닮음변환 $S_{P,\,c}:\mathbb{R}^n \to \mathbb{R}^n$ 은

$$
S_{P,\,c}(X)=P+c(X-P)
$$

로 정의된다. 이제 점 $Q$ 를 중심으로 하고 닮음비가 $c$ 인 닮음변환 $S_{Q,\,c}$ 는 닮은 변환 $S_{P,\,c}$ 를 실행한 다음 $(1-c)(Q-P)$ 만큼 평행이동하는 사상과 같음을 보이라.

:::

</div>

::: {.solution}

평행이동 $T(X)=X+(1-c)(Q-P)$ 를 생각하면,

$$
\begin{aligned}
(T\circ S_{P,\,c})(X)&=T(P+c(X-P))\\
&=(1-c)(Q-P)+P+cX-cP\\
&=(1-c)Q-(1-c)P+P+cX-cP\\
&=Q+c(X-Q)\\
&=S_{Q,\,c}
\end{aligned}
$$

:::

</br>

## 연습문제 : 제 5장 2절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_2_1} 

다음 벡터와 나란한 방향의 단위벡터를 모두 구하라.

:::

</div>

::: {.solution}

($1$) $\bf{a}=(-1,\,-2,\,-3)$  : $\dfrac{1}{14}(1,\,2,\,3)$ , $-\dfrac{1}{14}(1,\,2,\,3)$

($2$) $\bf{b}=(4,\,-5,\,6)$ : $\dfrac{1}{77}(4,\,-5,\,6)$, $-\dfrac{1}{77}(4,\,-5,\,6)$

($3$) $\bf{c}=(1999,\, 1999,\, 1999)$ : $\dfrac{1}{\sqrt{3}}(1,\,1,\,1)$, $-\dfrac{1}{\sqrt{3}}(1,\,1,\,1)$

($4$) $\bf{d}=(3,\,4,\,0)$ : $\dfrac{1}{5}(3,\,4,\,0)$, $-\dfrac{1}{5}(3,\,4,\,0)$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_2_2} 

모든 벡터는 단위벡터의 상수배로 나타낼 수 있음을 보이라.

:::

</div>

::: {.solution}

임의의  non-zero 벡터 $\bf{v}$ 에 대해 $\bf{v}=|\bf{v}| \cdot \left(\dfrac{\bf{v}}{|\bf{v}|}\right)$ . 영벡터 $\bf{0}$ 은 임의의 단위벡터 $\bf{e}$ 에 대해 $\bf{0}=0\cdot\bf{e}$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_2_3} 

#### 동등관계 

어떤 집합 $X$ 에 대하여 (**제**)**곱집합**

$$
X\times X=\{(x,\,y): x\in X,\, y\in X\}
$$

의 부분집합 $R$ 이 주어졌다고 하고 $(x,\,y)\in R$ 일 때 $x\equiv y$ 로 쓰기로 하자. 이 때 $R$ 이 다음 세 조건을 만족시키면 $R$ 을 동등관계라고 부른다.

​(**반사율**) $x \equiv x$

​(**대칭률**) $x\equiv y \implies y \equiv x$

​(**추이율**) $x\equiv y,\, y \equiv z \implies x \equiv z$

이제 주어진 실수 $c$ 에 대하여 두 실수 $a,\,b$ 의 차가 $c$ 의 정수배가 될 때

$$
a \equiv b \,\operatorname{mod}\,c
$$

로 쓰기로 한다. 이 관계가 동등관계임을 보이라.

:::

</div>

::: {.solution}

(반사율) $x-x=0 = 0 \cdot c$

(대칭률) $\exists c\in \mathbb{Z} \text{ s.t. } x-y=k \cdot c \implies y-x = (-k)\cdot c$ and $(-k)\in \mathbb{Z}$

(추이율) $x-y=nc,\, y-z=mc \implies x-z=(x-y)+(y-z)=(n+m)c$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_2_4} 
 생략
:::
</div>

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_2_5} 

실수 $d$ 에 대하여

$$
d^o :=\{x\in \mathbb{R} : x \equiv d \;\operatorname{mod} \, 360\}
$$

으로 정의하자. 이 때 임의의 실수 $a,\,b$ 에 대하여

$$
a^o=b^o \qquad \text{또는} \qquad a^o \cap b^o = \varnothing
$$

임을 보이라.

:::

</div>

::: {.solution}

$x,\,y \in d^o$ 이면 어떤 정수 $m,\,n$ 이 존재하여 $x-d=m\cdot 360,\, y-d=n\cdot 360$ 이며 $y \equiv x \;\operatorname{mod}\;360$ 이다. 따라서 $d^o=x^o=y^o$ 이다.  따라서 $x\in a^o \cap b^o$ 이면 즉 $a^o \cap b^o \ne \varnothing$ 이면 $x^o = a^o = b^o$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_2_6}

$n$-공간의 임의의 한 점 $P$ 에 대하여, $n$-벡터 전체의 집합은 $P$ 를 시점으로 하는 유향선분 전체의 집합과 일대일 대응관계가 있음을 설명하라.

:::

</div>

::: {.solution}

평행이동!

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_2_7} 

$n$-공간의 임의의 벡터 $\bf{a}$ 와 실수 $t$ 에 대하여,

$$
0 \bf{a}=\bf{0},\qquad t\bf{0}=\bf{0}
$$

임을 보이라. 또 $t\bf{a}=\bf{0}$ 이면 $t=0$ 또는 $\bf{a}=\bf{0}$ 임을 보이라.

:::

</div>

::: {.solution}

trivial

:::


</br>

### 기본연습문제

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_1_B01}

임의의 실수 $a_1,\,a_2,\ldots,\,a_n$ 에 대하여 부등식


$$
(a_1+a_2+\cdots + a_n)^2 \le n({a_1}^2+{a_2}^2+\cdots +{a_n}^2 )
$$
이 성립함을 보이라. 또 등호가 성립하는 경우는 언제인가? 그리고 평균의 제곱 제곱의 평균보다 이하임을 보이라.

:::

</div>

::: {.solution}

$\mathbb{R}^n$ 에서 $\bf{a}=(a_1,\,a_2,\ldots,\,a_n)$ 과 $\bf{b}=(1,\,1,\ldots,\,1)$ 을 생각한다. CBS 부등식 $|\bf{a}|^2|\bf{b}|^2\ge |\bf{a}\cdot \bf{b}|^2$ 을 생각하면,

$$
\begin{aligned}
|\bf{a}|^2&= ({a_1}^2+{a_2}^2 + \cdots +{a_n}^2)\,,\\
|\bf{b}|^2&=n\,,\\
|\bf{a}\cdot \bf{b}|&=|a_1+a_2+\cdots +a_n|
\end{aligned}
$$

이므로 성립한다. 등호가 성립하는 경우는 둘이 나란할 할 때 이므로 $a_1=a_2=\cdots =a_n$ 일 때 이며,

$$
\begin{aligned}
[\text{평균의 제곱}] &=\dfrac{1}{n^2} (a_1+a_2+\cdots +a_n)^2\,,\\
[\text{제곱의 평균}] &=\dfrac{1}{n} ({a_1}^2+{a_2}^2+\cdots +{a_n}^2)\;.
\end{aligned}
$$

이므로 주어진 식에 의해 [평균의 제곱]$\le$ [제곱의 평균] 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_1_B02}

실수 $a_1,\ldots,\,a_n$ 이 $a_1+\cdots +a_n=1$ 을 만족시킬 때 ${a_1}^2+\cdots +{a_n}^2$ 의 최소값을 구하라.

:::

</div>

::: {.solution}
@exr-CAL_5_3_1_B01 의 결과를 이용하면, $({a_1}^2+\cdots +{a_n}^2)\ge \dfrac{1}{n}$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_1_B03}

#### 라그랑즈 항등식 

다음 항등식을 증명하라.

$$
\left(\sum_{k=1}^n {a_k}^2\right)\left(\sum_{k=1}^n {b_k}^2\right) = \left(\sum_{k=1}^n a_kb_k\right)^2 + \dfrac{1}{2}\sum_{i,\,j=1}^n (a_ib_j-a_jb_i)^2.
$$

:::

</div>

::: {.solution}

$\bf{a}=(a_1,\ldots,\,a_n),\,  \bf{b}=(b_1,\ldots,\,b_n)\in \mathbb{R}^n$ 이라 하자.

$$
\begin{aligned}
\sum_{i,\,j=1}^n (a_ib_j-a_jb_i)^2 &=\sum_{i=1}^n \sum_{j=1}^n \left({a_i}^2{b_j}^2 + {a_j}^2{b_i}^2-2a_ia_jb_ib_j\right) \\
&=\left(\sum_{i=1}^n {a_i}^2 \right)\left(\sum_{j=1}^n {b_j}^2 \right)+\left(\sum_{i=1}^n {b_i}^2 \right)\left(\sum_{j=1}^n {a_j}^2 \right) \\[0.3em]
&\qquad -2\left(\sum_{i=1}^n a_ib_i\right) \left(\sum_{j=1} a_j b_j\right)\\[0.3em]
&=2|\bf{a}|^2|\bf{b}|^2-2(\bf{a}\cdot\bf{b})^2
\end{aligned}
$$

이므로,

$$
\begin{aligned}
\left(\sum_{k=1}^n a_kb_k\right)^2 + \dfrac{1}{2}\sum_{i,\,j=1}^n (a_ib_j-a_jb_i)^2 &= (\bf{a}\cdot \bf{b})^2+|\bf{a}|^2|\bf{b}|^2-(\bf{a}\cdot \bf{b})^2 \\[0.3em]
&=|\bf{a}|^2|\bf{b}|^2=\left(\sum_{k=1}^n {a_k}^2\right)\left(\sum_{k=1}^n {b_k}^2\right)
\end{aligned}
$$
이다.

:::

</br>

## 연습문제 : 제 5장 3절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_4}

$\bf{v}_1,\,\bf{v}_2,\ldots,\,\bf{v}_k$ 가 서로 수직인 단위벡터들이면, 임의의 실수 $a_1,\,a_2,\ldots,\,a_k$ 에 대하여

$$
\left|a_1\bf{v}_1 + a_2\bf{v}_2 + \cdots + a_k\bf{v}_k\right|^2 ={a_1}^2+{a_2}^2+\cdots + {a_k}^2
$$

임을 보이라.

::: 

</div>

::: {.solution}

$\delta_{ij}$ 를 다음과 같이 정의한다.

$$
\delta_{ij}=\left\{\begin{array}{ll}1 \qquad &\text{if }i=j \\ 0 &\text{if } i \ne j\end{array}\right.
$$

이 때 임의의 $\bf{v}_i,\,\bf{v}_j$ 에 대해 $\bf{v}_i \cdot \bf{v}_j = \delta_{ij}$ 임을 알 수 있다.

$$
\left|a_1\bf{v}_1 + a_2\bf{v}_2 + \cdots + a_k\bf{v}_k\right|^2  = \sum_{i=1}^k \sum_{j=1}^k a_i a_j (\bf{v}_i\cdot \bf{v}_j)=\sum_{i=1}^k\sum_{j=1}^k a_ia_j \delta_{ij}=\sum_{i=1}^k {a_i}^2
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_5}

$n$-공간에서 벡터 $\bf{a}_1,\ldots,\,\bf{a}_k$ 가 이루는 나란히꼴은

$$
\{t_1\bf{a}_1+\cdots + t_k \bf{a}_k : 0\le t_1,\ldots,\,t_k\le 1\}
$$

로 정의한다. 이 때 두 벡터 $\bf{a},\,\bf{b}$ 가 이루는 나란히꼴의 넓이는

$$
\sqrt{|\bf{a}|^2|\bf{b}|^2-(\bf{a}\cdot \bf{b})^2}=|\bf{a}||\bf{b}| \sin \theta
$$

임을 보이라. (여기에서 $\bf{a}$ 와 $\bf{b}$ 사이의 각을 $\theta$ 라 두었다.)

:::

</div>

::: {.solution}

두 변의 길이가 각각 $a,\,b$ 이며 사잇각이 $\theta$ 인 사다리꼴의 넓이가 $ab\sin \theta$ 임을 안다. 따라서,

$$
[\text{Area}]=|\bf{a}||\bf{b}|\sin\theta =|\bf{a}||\bf{b}|\sqrt{1-\cos^2\theta}=\sqrt{|\bf{a}||\bf{b}|-(\bf{a}\cdot \bf{b})^2}
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_6}

#### 정사영과 피타고라스정리 

삼차원 좌표공간에서 두 벡터 $A,\,B$ 가 이루는 나란히꼴 $P$ 를 $yz$-평면에 정사영한 것의 넒이를 $a_1$, $zx$-평면에 정사영한 것의 넒이를 $a_2$, $xy$-평면에 정사영한 것의 넓이를 $a_3$ 라고 두자. 이 때 $P$ 의 넓이 $a$ 는

$$
a^2={a_1}^2+{a_2}^2+{a_3}^2
$$

을 만족시킴을 보이라. 또 $P$ 와 $yz$-평면의 사이의 각을 $\theta_1$, $zx$-평면 사이의 각을 $\theta_2$, $xy$-평면 사이의 각을 $\theta_3$ 이라 두면

$$
a_i = a \cos \theta_i,\qquad (i=1,\,2,\,3)
$$

임을 보여라.

:::

</div>

::: {.solution}

($1$) $A=(A_1,\,A_2,\,A_3), \, B=(B_1,\,B_2,\,B_3)$  라 하면

$$
\begin{aligned}
a_1 &= \sqrt{({A_2}^2+{A_3}^2)({B_2}^2+{B_3}^2)-(A_2B_2+A_3B_3)^2}=|A_2B_3-A_3B_2|\,,\\
a_2 &= \sqrt{({A_1}^2+{A_3}^2)({B_1}^2+{B_3}^2)-(A_1B_1+A_3B_3)^2}=|A_1B_3-A_3B_1|\,,\\
a_3 &= \sqrt{({A_1}^2+{A_2}^2)({B_1}^2+{B_2}^2)-(A_1B_1+A_2B_2)^2}=|A_1B_2-A_2B_1|\,,\\
a&= \sqrt{({A_1}^2+{A_2}^2+{A_3}^2)({B_1}^2+{B_2}^2+{B_3}^2)-(A_1B_1+A_2B_2+A_3B_3)^2}\,,\\
&=\sqrt{(A_1B_2-A_2B_1)^2+(A_1B_3-A_3B_1)^2+(A_2B_3+A_3B_2)^2} \\
&= \sqrt{{a_1}^2+{a_2}^2+{a_3}^2 }&
\end{aligned}
$$

($2$) 뒤에 나오는 벡터의 외적을 이용한다. $A,\,B$  두 벡터에 의해 정해지는 평면과 수직인 벡터 $N=A\times B$ 이며, $yz,\, zx,\,xy$-평면에 수직인 벡터는 차례대로 $\bf{e}_1,\,\bf{e}_2,\,\bf{e}_3$ 이다. 두 평면이 이루는 $\theta_i$ 는 $0\le \theta_i <\dfrac{\pi}{2}$ 사이로 정해지므로 $\cos \theta_i>0$ 이며,

$$
\cos \theta_i =\dfrac{|N\cdot \bf{e}_i|}{|N||\bf{e}_i|}=\dfrac{a_i}{a}
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_7}

삼차원 좌표공간에서 한 나란히꼴 $P$ 를 $yz$-평면, $zx$-평면, $xy$-평면에 정사영한 것의 넓이가 각각 $1,\,2,\,3$ 이었다고 하자. 이때 $P$ 의 넓이는 얼마인가?

:::

</div>

::: {.solution}

@exr-CAL_5_3_6 으로부터, $P$ 의 넓이는 $\sqrt{1+4+9}=\sqrt{14}$ 임을 안다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_8}

모든 벡터와 수직인 벡터는 영벡터임을 안다.

:::

</div>

::: {.solution}

$n$ 차원 공간에서 표준 단위벡터 $\bf{e}_1,\ldots,\, \bf{e}_n$ 과 모든 벡터에 수직인 벡터 $X=(x_1,\ldots,\,x_n)$ 을 생각하자. $i=1,\,2,\,\ldots,\,n$ 에 대해 $\bf{e}_i \cdot X=x_i=0$  이어야 한다. 따라서 모든 벡터와 수직인 벡터는 영벡터이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_9}

내적이 주어진 공간, 즉 내적공간에서는 벡터 $\bf{v}$ 는 함수의 역할을 한다.

$$
\bf{v}^\ast : \bf{w}\to \bf{v}\cdot \bf{w}
$$

이제 두 함수 $\bf{v}^\ast_1$ 와 $\bf{v}^\ast_2$ 가 같은 함수이면 $\bf{v}_1^\ast = \bf{v}_2^\ast$ 임을 보이라.

:::

</div>

::: {.solution}

임의의 $\bf{w}$ 에 대해 $\bf{v}^\ast_1 (\bf{w})= \bf{v}_2^\ast (\bf{w})$ 이어야 한다. 따라서,

$$
\bf{v}_1\cdot \bf{w}=\bf{v}_2\cdot \bf{w} \implies (\bf{v}_1-\bf{v}_2)\cdot \bf{w}=0
$$

이므로 문제 8에 의해 $\bf{v}_1-\bf{v}_2=0$ 이어야 한다. 즉 $\bf{v}_1=\bf{v}_2$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_10}

두 벡터 $\bf{a},\,\bf{b}$ 가 수직일 필요충분조건은,

$$
|\bf{a}+\bf{b}|=|\bf{a}-\bf{b}|
$$

임을 보이라.

:::

</div>

::: {.solution}

($1$) 두 벡터 $\bf{a}$ 와 $\bf{b}$ 가 수직이면 $\bf{a} \cdot \bf{b}=0$ 이다. 주어진 식으로부터,

$$
|\bf{a}+\bf{b}|^2-|\bf{a}-\bf{b}|^2 = 4\bf{a}\cdot \bf{b}=0
$$

이므로 $|\bf{a}+\bf{b}|=|\bf{a}-\bf{b}|$ 이다.

($2$) $|\bf{a}+\bf{b}|=|\bf{a}-\bf{b}|$ 임을 가정하자.

$$
|\bf{a}+\bf{b}|=|\bf{a}-\bf{b}| \implies |\bf{a}+\bf{b}|^2=|\bf{a}-\bf{b}|^2\implies \bf{a}\cdot \bf{b}=0
$$

이므로 $\bf{a}$ 와 $\bf{b}$ 는 수직이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_11}

임의의 두 벡터 $\bf{a},\,\bf{b}$ 에 대하여

$$
\large| \normalsize|\bf{a}|-|\bf{b}|\large|\normalsize\ge |\bf{a}-\bf{b}|
$$

임을 보여라.

:::

</div>

::: {.solution}


두 벡터의 사잇각을 $\theta$ 라 하면,
$$
(\large|\normalsize |\bf{a}|-|\bf{b}|\large|\normalsize)^2-|\bf{a}-\bf{b}|^2=2|\bf{a}||\bf{b}|+2\bf{a}\cdot \bf{b}=2|\bf{a}||\bf{b}|(1-\cos \theta) \ge 0
$$
이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_12}

벡터 $\bf{a}=(a_1,\ldots,\,a_n)\ne 0$ 이 표준단위벡터 $\bf{e}_1,\ldots,\,\bf{e}_n$ 과 이루는 각을 각각 $\theta_i$ 이라고 할 때 다음을 보이라.

($1$) $\cos \theta_1=a_1/|\bf{a}|,\ldots,\, \cos \theta_n|=a_i/|\bf{a}|$

($2$) $\cos^2\theta_1 + \cdots + \cos^2\theta_n=1$

($3$) $(\cos \theta_1,\ldots,\,\cos \theta_n)$ 은 $\bf{a}$ 와 같은 방향의 단위벡터이다.

:::

</div>

::: {.solution}

($1$) $\cos \theta_i = \dfrac{\bf{a} \cdot \bf{e}_i}{|\bf{a}| |\bf{e}_i|}=\dfrac{a_i}{|\bf{a}|}$

($2$) $|\bf{a}|^2 =a_1^2+\cdots +a_n^2 = |\bf{a}|^2(\cos^2 \theta_1 + \cdots + \cos^2 \theta_n)$ 이므로 $\cos^2\theta_1 + \cdots +\cos^2 \theta_n =1$.

($3$) $\bf{a}=(a_1,\ldots,\,a_n)=|\bf{a}| (\cos \theta_1,\ldots,\,\cos \theta_n)$ 이므로 두 벡터는 같은 방향. ($2$) 로부터 단위벡터.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_13}

좌표공간 $\mathbb{R}^3$ 에서 단위벡터 $\bf{v}$ 가 $x$-축과 이루는 각을 $\theta_x$, $y$-축과 이루는 각을 $\theta_y$ 라 하였을 때, $\bf{v}$ 가 $xy$-평면과이루는 각 $\alpha$ 는 얼마인가? 또 $\theta_x=\theta_y =60^{\circ}$ 이면 $\alpha$ 는 얼마인가?

::: 

</div>

::: {.solution}

@exr-CAL_5_3_12 로 부터 $\bf{v}=(\cos \theta_x,\, \cos \theta_y,\, \cos \theta_z)$ 이며 $\cos \theta_z =\sqrt{1-\cos^2 \theta_x -\cos^2 \theta_y}$ 임을 안다. $xy$-평면과 이루는 각은 $\bf{v}$ 와 $(\cos \theta_x,\,\cos \theta_y,\,0)$ 과 이루는 각이므로,

$$
\cos \alpha= \dfrac{\cos^2 \theta_x + \cos^2 \theta_y}{\sqrt{\cos^2 \theta_x+\cos^2 \theta_y}}=\sqrt{\cos^2 \theta_x + \cos^2 \theta_y}
$$

이 성립한다. 따라서,

$$
\alpha = \arccos \sqrt{\cos^2 \theta_x +\cos^2 \theta_y}
$$

이다.

$\theta_x =\theta_y=60^\circ$ 라면 $\alpha = \arccos \sqrt{1/2}=45^\circ$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_14}

양수 $a,\,b$ 에 대하여

$$
A=(b,\, ab^2),\qquad A'=(-b,\,ab^2)
$$

으로 두고, 또 $t \ne b$ 인 양수 $t$ 에 대하여

$$
P=P(t) = (t,\,at^2)
$$

으로 두면, 이들은 포물선 $y=ax^2$ 위의 점들이 됨을 알 수 있다. 이때 벡터 $\overrightarrow{PA}$ 와 $\overrightarrow{PA'}$ 이 이루는 각의 크기를 $\theta(t)$ 라고 두면,

$$
\lim_{t \searrow b} \cos \theta(t)=\dfrac{1}{\sqrt{1+4a^2b^2}}\,,\qquad \lim_{t \nearrow b}\cos \theta(t)=-\dfrac{1}{\sqrt{1+4a^2b^2}}
$$

임을 보여라.

::: 

</div>

::: {.solution}

$$
\overrightarrow{PA}=(b-t,\, ab^2-at^2),\qquad \overrightarrow{PA'}=(-t-b,\, ab^2-at^2)
$$

이며,

$$
\begin{aligned}
\cos \theta(t) &= \dfrac{-b^2+t^2+a^2t^4+a^2b^4-2a^2t^2b^2}{\sqrt{(b-t)^2+a^2(b^2-t ^2)^2}\sqrt{(b+t)^2+a^2(b^2-t^2)^2}}\\
&=\dfrac{a^2t^4-(2a^2b^2-1)t^2+b^2(a^2b^2-1)}{|b^2-t^2|\sqrt{1+a^2(b+t)^2}\sqrt{1+a^2(b-t)^2}} \\
&= \dfrac{(t^2-b^2)}{|t^2-b^2|}\dfrac{(a^2t^2-a^2b^2+1)}{\sqrt{1+a^2(b+t^2)}\sqrt{1+a^2(b-t^2)}} \\
\end{aligned}
$$

이다. 따라서,

$$
\lim_{t \searrow b}\cos \theta(t)=\dfrac{1}{\sqrt{1+4a^2b^2}},\qquad \lim_{t \nearrow b}\cos \theta(t)=-\dfrac{1}{\sqrt{1+4a^2b^2}}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_15}

#### 코사인법칙 

변의 길이가 각각 $a,\,b,\,c$ 인 삼각형에서 "$a$-변" 과 "$b$-변" 사이의 각을 $\theta$ 라 하면

$$
c^2=a^2+b^2-2ab\cos \theta
$$

임을 보이라.

:::

</div>

::: {.solution}

삼각형의 세 꼭지점을 $A,\,B,\,C$ 라 하고 $\bf{a}=\overrightarrow{BC},\, \bf{b}=\overrightarrow{CA},\, \bf{c}=\overrightarrow{AB}$ 라 하자. 또한 $a=|\bf{a}|,\, b=|\bf{b}|,\, c=|\bf{c}|$ 라 하자. 그렇다면 $\cos \theta$ 는 $\bf{a}$ 와 $\bf{b}$ 의 사잇각이다. $\bf{a}+\bf{b}=\bf{c}$ 이므로,

$$
c^2=|\bf{c}|^2=|\bf{a}+\bf{b}|^2=a^2+b^2+2\bf{a}\cdot \bf{b}=a^2+b^2+2ab\cos \theta
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_16}

$x^2+2y^2+3z^2=1$ 일 때 $x+y+z$ 의 최대값과 최소값을 구하라.

:::

</div>

::: {.solution}

$\mathbb{R}^3$ 에서의 세 백터 $\bf{x}=(x,\, \sqrt{2}y,\,\sqrt{3}z)$ 와 $\bf{a}=(1,\,1/\sqrt{2},\,1\sqrt{3})$ 을 생각한다. $|\bf{x} \cdot \bf{a}|^2\le |\bf{x}|^2|\bf{a}|^2$ 를 이용하면,

$$
|\bf{x}\cdot \bf{a}|^2=|x+y+z|가 ^2\le |x^2+2y^2+3z^3|\cdot\dfrac{11}{6}=\dfrac{11}{6}
$$

따라서 최대값은 $\sqrt{11/6}$ 최소값은 $-\sqrt{11/6}$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_3_17}

다음은 중심의 위치가 $P_0,\,P_1,\,P_2$ 이고 질량이 같은 세개의 당구공이 당구대위에 놓여 있는것을 위에서 본 그림이다.

(그림 생략)

이 때 당구공 $P_0$ 를 때려, 이것이 당구공 $P_1$ 을 맞춘 다음 당구공 $P_2$ 와 속력 $v_2$ 로 정면 충돌하기 위해서는 처음에 당구공 $P_0$ 를 어느 방향으로 얼마만큼의 속력으로 때려야 하는가.

:::

</div>

::: {.solution}

당구공의 질량이 모두 같으므로 $1$ 로 놓아도 된다.  운동량 보존에 의해 $\bf{v}_0=\bf{v}_1+\bf{v}_2$ 이다. 탄성충돌을 가정한다면 $|\bf{v}_0|^2=|\bf{v}_1|^2+|\bf{v}_2|^2$ 이다.  $P_1P_2$ 와 $P_2P_3$ 의 사잇각을 $\theta$ 라 하면 $v_0=v_2/\cos \theta$ 이어야 한다.

:::


</br>

### 4.1.2 기본연습문제

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_B01}

$n$ 공간의 한 점 $Q$ 와 초평면 $\bf{a}\cdot (X-P)=0$ 사이의 거리는

$$
\dfrac{|\bf{a}\cdot (Q-P)|}{|\bf{a}|}
$$

임을 보이라.

:::

</div>

::: {.solution}

$Q$ 와 초평면 $\bf{a}\cdot(X-P)$ 사이의 거리는 $(Q-P)$ 의 $\bf{a}$ 방향으로의 정사영의 크기이다.  이 정사영을 $k\bf{a}$ 라 하면 $(k\bf{a} -(Q-P) ) \cdot \bf{a}=0$ 이므로,

$$
k|\bf{a}|^2=\bf{a}\cdot (Q-{P})\implies |k\bf{a}|= \dfrac{|\bf{a}\cdot (Q-P)|}{|\bf{a}|}
$$

이다.

:::

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_B02}

원점과 평면 $ax+by+cz=d$ 사이의 거리를 구하라.

:::

</div>

::: {.solution}

$a(x-x_0)+b(y-y0)+c(z-z_0)=0$ and $ax_0+by_0+cz_0=d$ 라 하면 이 식이 평면의 방정식이다. 이를 1.에 대입하면,
$$
[\text{distance}]=\dfrac{|ax_0+by_0+cz_0|}{\sqrt{a^2+b^2+c^z}}= \dfrac{|d|}{\sqrt{a^2+b^2+c^z}}
$$

:::

</br>

## 연습문제 : 제 5장 4절

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_1}

좌표평면의 두 직선 $y=mx+b$ 와 $y=m'x+b'$ 이 서로 수직일 필요충분조건은 $mm'=-1$ 임을 보여라.

:::

</div>

::: {.solution}

$x+\dfrac{b}{m}=\dfrac{y}{m}$ , $x+\dfrac{b'}{m'}=\dfrac{y}{m'}$ 으로 부터 두 직선의 방향은 $(1,\, 1/m),\, (1,\, 1/m')$ 이다.

두 직선이 수직 $\iff$ 두 방향벡터의 내적이 $0$ $\iff$ $1+\dfrac{1}{mm'}=0 \iff mm'=-1$.

:::

</br>

**2** 생략

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_3}

삼차원 공간에서 원점에 광원이 위치하고 스크린이 평면

$$
ax+by+cz=d \qquad (a^2+b^2+c^2 \ne 0,\, d\ne 0)
$$

으로 주어졌을 때 점 $P=(p,\, q,\,r)$ 의 상의 위치를 구하여라.

:::

</div>

::: {.solution}

원점과  $(p,\,q,\,r)$ 을 지나는 직선은 $(pt,\,qt,\,rt)$ 로 쓸 수 있으며 이것의 상의 위치는 $t=\dfrac{d}{ap+bq+cr}$ 로 정해진다. 즉
$$
\left(\dfrac{pd}{ap+bq+cr},\, \dfrac{qd}{ap+bq+cr},\, \dfrac{rd}{ap+bq+cr}\right)
$$
이며 $ap+bq+cr=0$ 이면 해가 존지하지 않는다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_4}

평면상에서 두 직선 $l,\,l'$ 과 이 직선 밖의 한 점 $O$ 를 생각하자. 이제 $l$ 상의 한 점 $P$ 와 $O$ 를 잇는 직선이 $l'$ 과 만나는 점을 $P'$ 이라고 두자.

이 때 $P'$ 이 존재하는 $P\in l$ 의 집합을 $l_\ast$ 라고 하였을 때, $l_\ast$ 의 임의의 네 점 $P_1,\,P_2,\,P_3,\,P_4$ 에 대하여,

$$
\dfrac{\overline{P_1P_2}\cdot \overline{P_3P_4}}{\overline{P_1P_4}\cdot \overline{P_2P_3}}=\dfrac{\overline{P'_1P'_2}\cdot \overline{P'_3P'_4}}{\overline{P'_1P'_4}\cdot \overline{P'_2P'_3}}
$$

:::

</div>

::: {.solution}

$O$ 를 원점으로 이동하고 회전시켜 $l'$ 이 $x$ 축과 평행하도록 하자. 도형을 축소시켜 $l'$ 이 $y=1$ 선상에 있도록 하고 이 때 $l$ 의 직선의 방정식을 $y=ax+b$ 라 하자. $P'_1,\,P'_2,\,P'_3,\,P'_4$ 의 좌표를 각각 $(x'_1,\,1),\, (x'_2,\,1),\, (x'_3,\,1),\, (x'_4,\,1)$이라 하자.

원점과 $(x'_1,\,1)$ 을 지나는 직선의 방정식은 $y=\dfrac{1}{x'_1}x$ 이다. 이것과 $l$ 과의 교점 $P_1$ 의 좌표는 $\dfrac{b}{1-ax_1'}\left(x_1',\,1\right)$ 이다. 즉,

$$
P_i = \left(\dfrac{b}{1-ax'_i}x'_i,\,\dfrac{b}{1-ax'_i}\right)
$$

이다.

$$
\dfrac{\overline{P'_1P'_2}\cdot \overline{P'_3P'_4}}{\overline{P'_1P'_4}\cdot \overline{P'_2P'_3}}=\dfrac{|x_1'-x_2'|\cdot|x_3'-x_4'|}{|x_1'-x_4'|\cdot |x_2'-x_3'|}
$$

이며,

$$
\dfrac{\overline{P_1P_2}\cdot \overline{P_3P_4}}{\overline{P_1P_4}\cdot \overline{P_2P_3}} = \dfrac{|x_1'-x_2'|\cdot|x_3'-x_4'|}{|x_1'-x_4'|\cdot |x_2'-x_3'|}=\dfrac{\overline{P'_1P'_2}\cdot \overline{P'_3P'_4}}{\overline{P'_1P'_4}\cdot \overline{P'_2P'_3}}
$$

임을 알 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_5}
</br>

($a$) 공간속의 한 점 $A$ 에서 평면 $\bf{n}\cdot (X-P)=0$ 에 내린 수선의 발을 구하라.

($b$) (**반사변환**(reflection)) 평면 $\bf{n}\cdot X =0$ 에 대한 점 $A$ 의 대칭점 $A'$ 을 구하라. 또 평면 $\bf{n}\cdot (X-P)$ 에 대한 점 $A$ 의 대칭점 $A''$ 을 구하라.

:::

</div>

::: {.solution}

($a$) $A=(a_1,\ldots,\,a_k)$ 를 지나며 방향벡터가 $\bf{n}=(n_1,\ldots,\,n_k)$ 인 직선은 $x_i = n_i t+a_i$ for $i=1,\ldots,\,k$ 로 나타 낼 수 있다. 직선과 평면의 교점이 수선의 발이므로 교점을 구하자. 수선의 발의 위치를 $Q$ 라 하면,

$$
\bf{n}\cdot (\bf{n}t+A-P)=0 \implies t=\dfrac{\bf{n}\cdot (P-A)}{|\bf{n}|^2} \implies Q=\left(\dfrac{\bf{n}\cdot (P-A)}{|\bf{n}|^2}\right)\bf{n} +A
$$

이다.

($b$) $A''+A=2Q$ 이므로 $A'' =2Q-A$ 이다. 즉,

$$
A''=2\left(\dfrac{\bf{n}\cdot (P-A)}{|\bf{n}|^2}\right)\bf{n} +A
$$

$A'$ 은 $A''$ 에서 $P=0$ 일 때 이다.

$$
A'=-2\left(\dfrac{\bf{n}\cdot A}{|\bf{n}|^2}\right)\bf{n} +A
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_6}

좌표공간에서 평면 $x+y+2z=1$ 에 대하여 점 $P=(1,\,1,\,1)$ 의 대칭점을 구하라.

:::

</div>

::: {.solution}

$$
x+y+2z=1 \implies (x-1)+y+2z=0 \implies (1,\,1,\,2)\left[(x,\,y,\,z)-(1,\,0,\,0)\right]=0
$$

이므로 문제 5를 이용하여 $P$ 의 대칭점 $P'$ 을 구하면,

$$
P'=2 \left( \dfrac{-3}{6}\right)(1,\,1,\,2)+(1,\,1,\,1)=(-1+1,\,-1+1,\, -2+1)=(0,\,0,\,-1)
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_7}

삼차원 좌표공간에서 두 평면

$$
2x+4y+z=5,\qquad x-3y+2z=0
$$

이 이루는 교각의 코사인 값을 구하라.

:::

</div>

::: {.solution}

두 평면의 방햑벡터를 $\bf{n}_1=(2,\,4,\,1),\, \bf{n}_2=(1,\,-3,\,2)$ 라 하면,

$$
\cos(\bf{n}_1,\,\bf{n}_2)= \dfrac{\bf{n}_1 \cdot \bf{n}_2}{|\bf{n}_1||\bf{n}_2|}=-\dfrac{8}{7\sqrt{6}}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_8}

#### 입체사영 

구면 $x^2+y^2+z^2=1$ 의 점 $(0,\,0,\,1)$ 과 $xy$-평면의 점 $(x,\,y,\,0)$ 을 지나는 직선이 구면과 만나는 새로운 점의 좌표를 구하라. 또 이를 이용하여 정수방정식 $a^2+b^2+c^2=d^2$ 의 풀이를 구하라. $p,\,q$ 가 정수이면 정수점 $(2pq,\,2p^2,\,q^2)$ 과 원점까지의 거리가 정수 $2p^2+q^2$ 임을 살펴보라. 또 원점까지의 거리가 정수인 정수점 $(a,\,b,\,c)$ 를 모두 구하라.

:::

</div>

::: {.solution}

($1$) $(0,\,0,\,1)$ 과 $(x,\,y,\,0)$ 을 지나는 직선은 $(xt,\, yt,\, -t+1)$ 로 표현 할 수 있다. 이 직선과 구면이 만나는 새로운 점의 좌표는,

$$
x^2t^2+y^2t^2+t^2-2t+1=1 \implies t=\dfrac{2}{x^2+y^2+1}\text{ or }t=0
$$

이다. $t=0$ 일 때는 $(0,\,0,\,1)$ 인 사소한 해 이다.

($2$) 정수방정식 $a^2+b^2+c^2=d^2$ 을 생각하자. $d=0 \iff a= b=c=0 $ 의 사소한 해를 제외하고 생각하기로 하자. $d\ne 0$ 이므로,

$$
\left(\dfrac{a}{d}\right)^2+\left(\dfrac{b}{d}\right)^2+\left(\dfrac{c}{d}\right)^2=1
$$

를 얻는다. ($1$) 로 부터 $x,\,y\in \mathbb{Q}$ 일 때 $(x,\,y,\,0)$ 과 $(0,\,0,\,1)$ 을 지나는 직선이  $x^2+y^2+z^2=1$ 과 만나는 점의 좌표는 유리수임을 알 수 있다. 역으로 $x,\,y,\,z\in \mathbb{Q}$ 이고 $x^2+y^2+z^2=1$ 이면 $(0,\,0,\,1)$ 과 $(x,\,y,\,z)$ 를 동시에 지나는 직선 $(xt,\,yt,\,zt+1)$ 이 $xy$-평면과 만나는 점의 좌표는 $(-x/z,\, -y/z,\,0)$ 이므로 좌표값이 유리수이다. 즉 $x^2+y^2+z^2=1$ 을 만족하는 $x,\,y,\,z$ 가 유리수 인 것은 $(0,\,0,\,1) $ 과 $(x,\,y,\,z)$ 를 잇는 직선이 $xy$--평면과 만나는 점의 $x,\,y$ 좌표가 모두 유리수인것의 필요충분조건이다.

따라서 임의의 유리수 $q_1\,q_2$ 에 대하여

$$
\left(\dfrac{2q_1}{q_1^2+q_2^2+1},\, \dfrac{2q_2}{q_1^2+q_2^2+1},\, \dfrac{q_1^2+q_2^2-1}{q_1^2+q_2^2+1}\right)
$$

가 $x^2+y^2+z^2=1$ 상의 유리수이므로 $a^2+b^2+c^z=d^2$ 을 만족하는 정수방정식은 임의의 유리수 $q_1,\,q_2$ 에 대하여 $q_1^2+q_2^2+1,\,2q_1,\,2q_2$ 의 최소공배수의 임의의 배수를 $M$ 이라 할 때 $a=2Mq_1,\, b=2Mq_2,\,c=M(q_1^2+q_2^2-1),\, d=M(q_1^2+q_2^2+1)$ 이 정수방정식의 해이다. 또한 사소한 해 즉 임의의 정수 $d$ 에 대해 $a=d,\,b=c=0$, $b=d,\,a=c$, $c=d,\, a=b=0$ 또 해이다.

($3$) $p,\,q$ 가 정수일 때 $(2pq,\,2p^2,\,q^2)$ 과 원점 까지의 거리는 $\sqrt{4p^2q^2+4p^4+q^4}=(2p^2+q^2)$

($4$) 원점까지의 거리가 정수인 정수점은 (2) 에서 구하였다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_10}

삼차원 공간의 원점에서 $(1,\,2,\,3)$ 방향으로 발사된 빛이 평면 $x+y+z=1$ 에 위치한 거울에 반사되었을 때, 반사된 빛이 $xy$-평면과 만나는 점을 구하라.

:::

</div>

::: {.solution}

삼차원공간의 원점에서 $(1,\,2,\,3)$ 방향으로 발사된 빛은 직선의 방정식 $(t,\,2t,\,3t)$ 로 기술되며 평면 $x+y+z=1$ 에 위치한 거울 만나는 점은

$$
t+2t+3t=1\implies t=\dfrac{1}{6}
$$

로부터 $(1/6,\,1/3,\,1/2)$ 이다.

원점에서 출발하여 거울에 반사된 빛이 원점에서 반사점까지의 거리만큼 반사되어 갔을 때의 위치를 $P=(x,\,y,\,z)$ 라 하면  원점과 $P$ 의 중점이 $(1/6,\,1/3,/,1/2)$ 를 지나며 평면의 방향벡터와 같은 $(1,\,1,\,1)$ 을 방향벡터로 갖는 직선 위에 있어야 한다. 즉,

$$
\dfrac{O+P}{2}=\left(\dfrac{x}{2},\, \dfrac{y}{2},\, \dfrac{z}{2}\right) = \left(t+\dfrac{1}{6},\, t+\dfrac{1}{3},\, t+\dfrac{1}{2}\right)
$$

를 만족하는 $t\in \mathbb{R}$ 이 존재해야 한다. 또한 $\overrightarrow{OP}\cdot (1,\,1,\,1)=0$ 이어야 하므로, $(x+y+z)=0$  이어야 한다. 즉 $t=-\dfrac{1}{3}$ 이므로,

$$
P=\left(-\dfrac{1}{3},\, 0,\, \dfrac{1}{3}\right)
$$

이다. 즉 반사된 빛의 경로는, $\left(3s-\dfrac{1}{3},\, 2s,\, s+\dfrac{1}{3}\right)$ 을 따른다. $xy$-평면과 만나는 점은 $s=-\dfrac{1}{3}$ 일 때 이므로

$$
\left(-\dfrac{4}{3},\, -\dfrac{3}{2},\,0 \right)
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_11}

공간의 세 점 $P_0,\,P_1,\,P_2$ 가 동일 직선상에 있으면, 방정식

$$
\begin{aligned}
&t_0+t_1+t_2=0\,,\\
&(t_0,\,t_1,\,t_2)\ne (0,\,0,\,0)\,,\\
&t_0P_0+t_1P_1+t_2P_2=0\;.
\end{aligned}
$$

을 만족시키는 실수 $t_0,\,t_1,\,t_2$ 가 존재함을 보이라. 또 이 명제의 역이 성립함을 보이라.

:::

</div>

::: {.solution}

세 점이 동일직선상에 있으면 $\overrightarrow{P_1P_0}$ 와 $\overrightarrow{P_2P_0}$ 가 평행해야 한다. 즉 $a(P_0-P_1)+b(P-0-P_2)=0 \implies (a+b)P_0-aP_1-bP_2=0$ 을 만족하는 실수 $0$ 이 아닌 실수 $a,\,b$ 가 존재히야 한다. $a+b=t_0,\, -a=t_1,\,-b=t_2$ 라 놓으면 $t_0+t_1+t_2=0$ 이므로 방정식 3개중 첫번째와 세번째를 만족하는 실수 $t_0,\,t_1,\,t_2$ 가 존재해야함과 동치이다. 또한 $a,\,b \ne 0 \iff (t_0,\,t_1,\,t_2)\ne (0,\,0,\,0)$ 이므로 두번째 방정식도 만족해야 한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_12}

공간의 부분집합 $A$ 에 속하는 임의의 두 점 $P,\,Q$ 에 대하여 선분

$$
PQ:=\{(1-t)P+tQ \mid 0\le t\le 1 \}
$$

가 여전히 $A$ 에 속하면 $A$ 를 **볼록집합** (convex set) 이라고 부른다. 이제 공간 속의 임의의 점 $P_0,\,P_1,\ldots,\,P_k$ 에 대하여 집합

$$
K:=\{t_0P_0 + t_1P_1 + \cdots + t_k P_k : t_0,\ldots,\,t_k \ge 0,\, t_0+t_1+\cdot +t_k =1\}
$$

가 볼록집합임을 보이라. 또 $K$ 는 $P_0,\ldots,\,P_k$ 를 포함하는 최소의 볼록집합임을 보이라.

:::

</div>

::: {.solution}

($1$) $X,\,Y\in K$ 라 하면 $X=x_0P_0 + \cdots x_k P_k,\, Y=y_0P_0 + \cdots + y_k P_k$ 이며 $x_0,\ldots,\,x_k,\,y_0,\ldots,\,y_k \ge 0$ 이고 $x_0+\cdots + x_k = y_0 + \cdots + y_k=1$ 을 만족시키는 $x_0,\ldots,\,x_k,\,y_0,\ldots,\,y_k$ 가 존재한다.  $0\le t \le 1$ 에 대해

$$
(1-t)X+tY = \sum_{m=1}^k (1-t)x_mP_m+ty_mP_m = \sum_{m=1}^k (x_m-tx_m+ty_m) P_m
$$

이다. $t<1,\, x_m,\, y_m\ge 0$ 이므로 $(1-t)x_m-ty_m\ge 0$  이며, $\displaystyle \sum_{m=1}^k (x_m-tx_m +ty_m)=1-t+t=1$ 이므로,

$$
(1-t)X+tY\in K
$$

이다. 따라서 $K$ 는 볼록집합이다.

($2$) $K_i:=\{t_0P_1 + \cdots + t_i P_i : t_0,\ldots,\,t_i \ge 0,\, t_0+\cdots + t_i=1 \}$ 에 대해 이것이 $P_0,\ldots,\,P_i$ 를 포함하는 최소한의 볼록집합임을 induction을 사용하여 증명하자.  $K_0 =\{P_0\}$  이며 $K_1=\{(1-t)P_0+tP_1: 0 \le t\le 1\}$ 임을 보이자. 볼록집합의 정의에 의해 $K_1$ 이 $P_0,\,P_1$ 을 포함하는 최소한의 볼록집합임은 자명하다.

이제 $K_N$ 이 $P_0,\ldots,\,P_N$ 을 포함하는 최소한의 볼록집합임을 가정하면 $K_{N+1}$ 이 $P_0,\ldots,\,P_N,\, P_{N+1}$ 을 포함하는 최소한의 볼록집합임을 보이자. $Q_N\in K_N$ 이라 할 때 $0\le s \le 1$ 을 만족하는 $s$ 에 대해 $(1-s)Q_N + sP_{N+1} \in P_{N+1}$ 이어야 한다. $Q_N = x_0P_1 + \cdot + x_NP_N$ for some $x_0,\ldots,\,x_N \ge 0,\, x_0+\cdots + x_N=1$ 이므로

$$
(1-s)Q_N+sP_{N+1}=(1-s)x_0 P_1 + \cdots +(1-s)x_NP_1 + sP_{N+1}
$$

이다. $\displaystyle \sum_{j=1}^N (1-s)x_j + s=(1-s)\sum_{j=1}^N x_j + s=1$ 이므로 $(1-s)Q_N + sP_{N+1}\in P_{N+1}$ 이다. 따라서 $P_1,\ldots,\,P_{N+1}$ 을 포함하는 볼록집합은 $K_{N+1}$ 부분집합이다. 또한 $K_{N+1}$ 의 정의에 의해 $K_{N+1}$ 은 $P_1,\ldots,\,P_{N+1}$ 을 포함하는 볼록집합에 포함된다. 따라서 $K_N$ 이 $P_1,\ldots,\,P_N$ 을 포함하는 최소한의 볼록집합이면 $K_{N+1}$ 은 $P_1,\ldots,\,P_{N+1}$ 을 포함하는 최소한의 볼록집합이다. 따라서 증명 끝.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_13}

볼록집합과 볼록집합의 교집합은 볼록집합임을 보이라.

:::

</div>

::: {.solution}

$A,\,B$ 가 볼록집합이며 $P,\,Q\in A \cap B$ 라 하자. 임의의 $0\le t \le 1$ 에 대해 $tP+(1-t)Q \in A \cap B$ 임은 trivial 하므로 $A \cap B$ 는 볼록집합이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_14}

$n$ 공간 속의 공

$$
\begin{aligned}
B^{n}(C,\,r) &:= \{X\in \mathbb{R}^n : |X-C|<r\}\\  
\overline{B}^n (C,\,r)&:= \{X \in \mathbb{R}^n : |X-C|\le r\}
\end{aligned}
$$

은 모두 볼록집합임을 보이라.

:::

</div>

::: {.solution}

$X,\,Y \in B^n(C,\,r)$ 이라면 $|X-C|<r,\, |Y-C|<r$ 이다. 임의의 $0\le t \le 1$ 에 대해

$$
\begin{aligned}
|tX+(1-t)Y-C| & =|t(X-C)+(1-t)(Y-C)| \\[0.3em]
& \le t|X-C|+(1-t)|Y-C|< tr+(1-t)r=r
\end{aligned}
$$

이므로 $tX+(1-t)Y\in B^n(C,\,R)$ 이다. 따라서 $B^n(C,\,r)$ 은 볼록집합이다.

$X,\,Y \in \overline{B}^n(C,\,r)$ 이라면 $|X-C|\le r,\, |Y-C|\le r$ 이다. 임의의 $0\le t \le 1$ 에 대해

$$
\begin{aligned}
|tX+(1-t)Y-C| &= |t(X-C)+(1-t)(Y-C)| \\[0.3em]
&\le t|X-C|+(1-t)|Y-C| \le tr+(1-t)r=r
\end{aligned}
$$

이므로 $tX+(1-t)Y\in \overline{B}^n(C,\,R)$ 이다. 따라서 $\overline{B}^n(C,\,r)$ 은 볼록집합이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_15}

$n$-공간의 단위벡터 $\bf{n}$ 에 대하여 초평면 $\bf{n}\cdot X+c=0$ 과 점 $P_1,\ldots,P_k$ 사이의 거리의 제곱합은 $\displaystyle \sum_{i=1}^k (\bf{n}\cdot P_i +c)^2$ 으로 주어진다. 이 값이 최소로 되는 초평면을, 주어진 점 $P_1,\ldots,\,P_k$ 에서 가장 가까운 초평면이라고 부를 때, 주어진 점에서 가장 가까운 초평면은 그 점들의 중심을 지남을 보이라.

:::

</div>

::: {.solution}

$c=-\bf{n}\cdot X$ 이므로, $

$$
\sum_{i=1}^k (\bf{n}\cdot P_i + c)^2=\sum_{i=1}^k (\bf{n} \cdot (P_i-X))^2
$$

$$
\begin{aligned}
\sum_{i=1}^k \left(\bf{n} \cdot P_i + c\right)^2 &=\sum_{i=1}^k (\bf{n}\cdot P_i)^2 + 2c\left(\sum_{i=1}^k \bf{n}\cdot P_i\right) + kc^2 \\
&=k\left[c^2 + \dfrac{2}{k}\left(\sum_{i=1}^k \bf{n}\cdot P_i\right)c+\dfrac{1}{k^2}\left(\sum_{i=1}^k \bf{n}\cdot P_i\right) ^2\right] \\[0.3em]
&\qquad \qquad \qquad +\sum_{i=1}^k (\bf{n}\cdot P_i)^2-\dfrac{1}{k}\left(\sum_{i=1}^k \bf{n}\cdot P_i\right) ^2 \\
&=k\left[c+\dfrac{1}{k} \left(\sum_{i=1}^k \bf{n}\cdot P_i\right)\right]^2+\sum_{i=1}^k (\bf{n}\cdot P_i)^2-\dfrac{1}{k}\left(\sum_{i=1}^k \bf{n}\cdot P_i\right) ^2
\end{aligned}
$$

여기서 뒤의 두 term 은 상수 term 이므로 $\displaystyle c=-\dfrac{1}{k} \left(\sum_{i=1}^k \bf{n}\cdot P_i\right)$ 일 때 최소값을 가진다. 이 때,

$$
0=\bf{n}\cdot X +c = \bf{n}\cdot \left(X-\dfrac{1}{k}
\sum_{i=1}^k P_i\right)
$$

이므로 이 초평면은 $\displaystyle \dfrac{1}{k}\sum_{i=1}^k P_i$ 를 지나는데 이 점이 중심이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_16}

어떤 보물섬의 지도에는 $n$ 개의 마을이 그려져 있고, 보물을 찾아 갈 수 있는 지시가 다음과 같이 쓰여 있다.

> 마을 $A_1$ 에서 출발하여 마을 $A_2$ 쪽으로 $\frac{1}{2}$ 만큼 간 다음, 마을 $A_3$ 쪽으로 $\frac{1}{3}$ 만큼 가고, 계속해서 마을 $A_4$ 쪽으로 $\frac{1}{4}$ 만큼 가고, ... , 마을 $A_n$ 쪽으로 $\frac{1}{n}$ 만큼 간 곳에 보물이 묻여 힜다.

그러나 지도에는 마을의 이름이 모두 지워져 있었다. 이 때 부물이 묻힌 곳을 알 수 있겠는가.

:::

</div>

::: {.solution}

처음 시작점의 위치를 $P_1$, $k$ 번째 마을을 향하여 주어진 만큼 향하였을때의 위치를 $P_k$ 라 하자. 그렇다면, $P_1=A_1$ 이며 $k\ge 2$ 에 대해

$$
P_k = P_{k-1}+\dfrac{1}k(A_k-P_{k-1})= \dfrac{k-1}{k}P_{k-1} + \dfrac{1}{k}A_k
$$

이므로,

$$
kP_k = (k-1)P_{k-1}+A_k
$$

이다. 양 변에 $\displaystyle \sum_{k=1}^n$ 을 씌워 계산하면,

$$
P_1 + 2P_2 + \cdots + nP_n = P_1 + \cdots (n-1)P_{n-1} + A_1 + \cdot + A_n
$$

이므로, $nP_n =A_1+\cdots +A_n$ 이다. 즉,

$$
P_n = \dfrac{1}{n} \sum_{k=1}^n A_n
$$

이므로 $P_n$ 은 $n$ 개의 마을들의 중심이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_17}

사각형의 각 변의 중점을 차례로 이어 얻은 사각형은 평행사변형임을 보이라.

:::

</div>

::: {.solution}

사각형의 각 꼭지점을 $A,\,B,\,C,\,D$ 라 하면 각 변의 중점은 $X_1=(A+B)/2,\,X_2=(B+C)/2,\,X_3=(C+D)/2,\,X_4=(D+A)/2$ 이다. 이 때 $X_1-X_2=\dfrac{A-C}{2}=X_4-X_3$ 이므로 $X_1-X_2$ 가 이루는 변과 $X_4-X_3$ 가 이루는 변이 평행하며, $X_4-X_1=\dfrac{D-B}{2}=X_3-X_2$ 이므로 $X_4-X_1$ 과 $X_3-X_2$ 가 이루는 변이 평행하다. 따라서 이 사각형은 평행사변형이다.

:::

</br>

**18.**

trivial

</br>

**19.**

trivial

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_20}

공간속의 점 $P_1,\ldots,\,P_k$ 에 대하여

$$
|P_1-Q|^2 + \cdots +|P_k-Q|^2
$$

의 값을 최소로 하는 점 $Q$ 는 $P_1,\ldots,\,P_k$ 의 중심임을 보여라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
\sum_{i=1}^k|P_i-Q|^2&= \sum_{i=1}^k |P_i|^2-2\sum_{i=1}^k P_i \cdot Q + k|Q|^2 \\
&=k\left(|Q|^2-2\left(\dfrac{1}{k}\sum_{i=1}^k P_i\right) \cdot Q + \left( \dfrac{1}{k}\sum_{i} P_i  \right)^2 \right) \\[0.3em]
&\qquad \qquad \qquad +\sum_{k=1}^k |P_i|^2-\dfrac{1}{k}\left(\sum_{i=1}^k P_i\right)^2 \\
&= k \left(Q- \dfrac{1}{k} \sum_{i=1}^k P_i\right)^2+\sum_{k=1}^k |P_i|^2-\dfrac{1}{k}\left(\sum_{i=1}^k P_i\right)^2
\end{aligned}
$$

이다. 마지막 두 terms 는 $\{P_i\}$ 에만 의존하는 상수 term 이므로 이 값을 최소하 하는 점 $Q$ 는

$$
Q=\dfrac{1}{k}\sum_{i=1}^k P_i
$$

이다. 즉 $P_1,\ldots,\,P_k$ 의 중심이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_21}

두 평면 $x+y+z=1$ 과 $x-y-z=5$ 의 교선의 식을 구하라.

:::

</div>

::: {.solution}

두 식을 더하면 $2x=6\implies x=3$ 이다. 따라서 $y+z=-2$ 이다. 따라서 교선의 식은,

$$
x=3,\quad y=t,\quad z=-t-2
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_4_22}

공간에서 점과 실수의 쌍 $(P,\,m)$ 을 질점이라고 부르기로 하자. 질점들의 집합

$$
A:=\{(P_1,\,m_1),\,(P_2,\,m_2),\ldots,\, (P_n,\,m_n)\}
$$

에 대하여 $m:=m_1+\cdots +m_n$ 을 $A$ 의 질량이라고 한다. 그리고 질량이 $0$ 이 아닌 질점들의 집합 $A$ 에 대하여 $A$ 의 질량중심을

$$
\operatorname{CM}(A):= \left(\dfrac{m_1}{m}P_1 + \dfrac{m_2}{m}P_2 + \cdots + \dfrac{m_n}m P_n\right)
$$

으로 정의한다. 서로 공통부분이 없는 두 질점들의 유한집합 $A,\,B$ 에 대하여,

$$
\operatorname{CM}(A \cup B)=\operatorname{CM}(\{\operatorname{CM}(A),\, \operatorname{CM}(B)\})
$$

임을 보이라. 편의상 $A,\,B$ 의 각 질량이 모두 양수라 가정한다.

:::

</div>

::: {.solution}

$A,\,B,\,m_A$ 를 각각 아래와 같이 정하자.

$$
\begin{aligned}
A &:= \{(P_1^A,\,m_1^A) \ldots,\,(P_N^A,\,m_N^A)\}, \\[0.3em]
B &:= \{(P_1^B,\,m_1^B) \ldots,\,(P_M^B,\,m_M^B)\}, \\[0.3em]
m_A&: =m_1^A+ \cdots +m_N^A$, $m_B=m_1^B+\cdots + m_M^B.
\end{aligned}
$$

$$
\begin{aligned}
\operatorname{CM}(\{\operatorname{CM}(A),\, \operatorname{CM}(B)\}) &= \dfrac{m_A}{m_A+m_B} \operatorname{CM}(A) + \dfrac{m_B}{m_A+m_B} \operatorname{CM}(B) \\
&=\dfrac{m_A}{m_A+m_B}\left(\dfrac{1}{m_A}\sum_{i=1}^N m_i^AP_i^A\right) + \dfrac{m_B}{m_A+m_B}\left(\dfrac{1}{m_B}\sum_{j=1}^M m_j^BP_j^B\right) \\
&=\dfrac{1}{m_A+m_B} \left(\sum_{i=1}^N m_i^AP_i^A+ \sum_{j=1}^M m_j^B P_j^B\right) = \operatorname{CM}(A \cup B)
\end{aligned}
$$

:::

</br>

## 연습문제 : 제 5장 5 절

**1.** trivial

</br>

**2.** trivial

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_5_3}

세 벡터 $\bf{u},\,\bf{v},\,\bf{w}$ 가 일차독립일 때, 벡터

$$
\begin{aligned}
\bf{a}&= a_1 \bf{u}+a_2 \bf{v}+a_3\bf{w}\\
\bf{b} &= b_1 \bf{u}+b_2 \bf{v}+b_3\bf{w}\\
\bf{c} &= c_1 \bf{u}+c_2 \bf{v}+c_3\bf{w}\\
\end{aligned}
$$

가 일차독립일 필요충분조건은 벡터 $(a_1,\,a_2,\,a_3),\, (b_1,\,b_2,\,b_3),\, (c_1,\,c_2,\,c_3)$ 가 일차독립임을 보여라.

::: 

</div>

::: {.solution}

($1$) $\bf{a},\,\bf{b},\,\bf{c}$ 가 일차독립이면 $d_1\bf{a}+d_2\bf{b}+d_3\bf{c}=0$ 을 만족시키는 $d_1,\,d_2,\,d_3$ 는 모두 $0$ 이다. 즉,

$$
(d_1a_1+d_2b_1+d_3c_1)\bf{u}+(d_1a_2+d_2b_2+d_3 c_2)\bf{v}+(d_1a_3+d_2b_3+d_3c_3)\bf{w}=0
$$

이면 $d_1=d_2=d_3=0$ 이다.  $\bf{u},\,\bf{v},\, \bf{w}$ 가 일차독립이므로,

$$
d_1a_1+d_2b_1+d_3c_1=0\\
d_1a_2+d_2b_2+d_3 c_2=0\\
d_1a_3+d_2b_3+d_3c_3=0
$$

이어야 한다. 따라서 $d_1(a_1,\,a_2,\,a_3)+d_2(b_1,\,b_2,\,b_3)+d_3(c_1,\,c_2,\,c_3)=0$ 를 만족하는 $d_1,\,d_2,\,d_3$ 는 모두 $0$ 일 때이다. 따라서 벡터 $(a_1,\,a_2,\,a_3),\, (b_1,\,b_2,\,b_3),\, (c_1,\,c_2,\,c_3)$ 는 일차독립이다.

($2$) 벡터 $(a_1,\,a_2,\,a_3),\, (b_1,\,b_2,\,b_3),\, (c_1,\,c_2,\,c_3)$ 가 일차독립임을 가정하자. 그렇다면 $d_1(a_1,\,a_2,\,a_3)+d_2(b_1,\,b_2,\,b_3)+d_3(c_1,\,c_2,\,c_3)=0$ 를 만족하는 $d_1,\,d_2,\,d_3$ 는 모두 $0$ 일 때이다. 이는 $d_1 \bf{a}+d_2\bf{b}+d_3\bf{c}=0$ 을 만족하는 $d_1,\,d_2,\,d_3$ 는 모두 $0$ 이란 뜻이며, 따라서 $\bf{a},\,\bf{b},\,\bf{c}$ 는 모두 일차독립이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_5_4}

벡터 $\bf{a}_1,\ldots,\,\bf{a}_k$ 가 일차독립이면, 모든 $i\in \{1,\ldots,\,k\}$ 에 대하여 $\bf{a}_i \ne 0$ 임을 보여라.

:::

</div>

::: {.solution}

$\bf{a}_1=0$ 이면 $\sum c_i \bf{a}_i=0$ 에 대해 $c_1\ne 0,\, c_2=\cdots c_k=0$ 이어도 성립하므로 $\bf{a}_1,\ldots,\,\bf{a}_k$ 는 일차독립이 아니다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_5_5}

자연수 $k$ 가 자연수 $l$ 보다 작을 때, $n$-벡터 $\bf{a}_1,\ldots,\bf{a}_l$ 이 일차독립이면 $\bf{a}_1,\ldots,\bf{a}_k$ 도 일차독립임을 보여라.

:::

</div>

::: {.solution}

$\bf{a_1},\ldots,\,\bf{a}_k$ 가 일차독립이 아니면 $c_1 \bf{a}_1 + \cdots + c_k \bf{a}_k=0$ 을 만족하는 nontrivial $c_1,\ldots,\,c_k$ 가 존재한다. 그렇다면 $c_j=0$ for $j=k+1,\ldots,\,l$ 이라 놓으면 $c_1 \bf{a}_1 + \cdots +c_k\bf{a}_k + \cdots +c_l \bf{a}_l=0$ 을 만족하는 nontrivial $c_1,\ldots,\,c_l$ 이 존재하므로 $\bf{a}_1,\ldots,\,\bf{a}_l$ 은 일차독립이 아니다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_5_6}

벡터 $\bf{a}$ 가 벡터 $\bf{b}_1,\ldots,\,\bf{b}_k$ 의 일차결합이고, 벡터 $\bf{b}_i\,(i=1,\ldots,\,k)$ 가 각각 벡터 $\bf{c}_1,\ldots,\,\bf{c}_l$ 의 일차결합이면, 벡터 $\bf{a}$ 는 $\bf{c}_1,\ldots,\,\bf{c}_l$ 의 일차결합이 됨을 설명하라.

:::

</div>

::: {.solution}

Let $\displaystyle \bf{a}=\sum_{i=1}^k \beta_i \bf{b}_i$ and $\displaystyle \bf{b}_i=\sum_{j=1}^l \gamma_{ji}\bf{c}_j$ 라 하자. 그렇다면 $\displaystyle \bf{a}=\sum_{i=1}^k \beta_i \left(\sum_{j=1}^l \gamma_{ji}\bf{c}_j\right)=\sum_{j=1}^l \left(\sum_{i=1}^k \beta_i \gamma_{ji}\right) \bf{c}_j$ 이므로 증명 끝.

:::

</br>

## 연습문제 : 제 5장 6절

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_6_1}

$n$ 공간의 단위벡터 $\bf{v}_1,\ldots,\,\bf{v}_n$ 이 서로 수직이면, 이들을 정규직교기져라고 부른다. 이제 임의의 $n$-벡터 $\bf{a}$ 와 정규직교기저 $\bf{v}_1,\ldots,\,\bf{v}_n$ 에 대하여,

$$
\bf{a}=(\bf{a}\cdot \bf{v}_1)\bf{v}_1 + \cdots +(\bf{a}\cdot \bf{v}_n)\bf{v}_n
$$

임을 보이라.

:::

</div>

::: {.solution}

$\displaystyle \bf{a}=\sum_{k=1}^n a_k \bf{v}_k$ 이며 이 때 $a_k$ 는 유일하게 결정된다. $\displaystyle \bf{a}\cdot \bf{v}_i =\sum_{k=1}^n a_k (\bf{v}_k \cdot \bf{v}_i)=a_i$ 이다. 따라서 $\displaystyle \bf{a}=\sum_{k=1}(\bf{a}\cdot \bf{v}_k)\bf{v}_k$  이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_6_6}

정육면체 격자의 각 정육면체의 중점들로 이루어진 집합을

$$
\operatorname{FC}:=\left\{\left(\dfrac{1}{2},\, \dfrac{1}{2},\, 0\right), \, \left(\dfrac{1}{2},\,0,\, \dfrac{1}{2}\right),\,\left(0,\,\dfrac{1}{2},\, \dfrac{1}{2}\right)\right\}+\mathbb{Z}^3
$$

라고 하자. 이제 **FCC 격자**

$$
\mathbb{Z}^3 \cup \text{FC}
$$
에서,

$$
\bf{i}=(1,\,0,\,0) ,\quad \left(\dfrac{1}{2},\, \dfrac{1}{2},\,0\right),\quad \left(0,\,\dfrac{1}{2},\, \dfrac{1}{2}\right)
$$

가 기저임을 보여라.

:::

</div>

::: {.solution}

$\bf{v}_1=\bf{i}=(1,\,0,\,0) ,\, \bf{v}_2= \left(\dfrac{1}{2},\, \dfrac{1}{2},\,0\right),\,\bf{v}_3=\left(0,\,\dfrac{1}{2},\, \dfrac{1}{2}\right)$ 라 하자.
$$
c_1 \bf{v}_1+c_2\bf{v}_2+c_3\bf{v}_3=0 \implies \left(c_1+\dfrac{c_2}{2},\, \dfrac{c_2+c_3}{2},\, \dfrac{c_3}{2}\right) =0 \implies c_1=c_2=c_3=0
$$
이므로 $\bf{v}_1,\,\bf{v}_2,\,\bf{v}_3$ 는 일차독립이다.

$$
\begin{aligned}
\text{FC} =&\left\{\left(\dfrac{1}{2}+n_1,\, \dfrac{1}{2}+n_2,\, n_3 \right):n_1,\,n_2,\,n_3\in \mathbb{Z} \right\} \\
&\qquad \bigcup \left\{\left(\dfrac{1}{2}+n_1,\,n_2,\, \dfrac{1}{2}+n_3\right) : n_1,\,n_2,\,n_3\in \mathbb{Z} \right\} \\
& \qquad \bigcup \left\{\left(n_1,\,\dfrac{1}{2}+n_2,\, \dfrac{1}{2}+n_3\right):n_1,\,n_2,\,n_3\in \mathbb{Z} \right\}
\end{aligned}
$$

이다.

$$
\begin{aligned}
\left(\dfrac{1}{2}+n_1,\, \dfrac{1}{2}+n_2,\, n_3 \right) & = (n_1-n_2+n_3)\bf{v}_1+(1+2n_2-2n_3)\bf{v}_2+2n_3 \bf{v}_3\\
\left(\dfrac{1}{2}+n_1,\,n_2,\, \dfrac{1}{2}+n_3\right) &= (1+n_1-n_2+n_3)\bf{v}_1+(-1+2n_2-2n_3)\bf{v}_2+(1+2n_3)\bf{v}_3 \\
\left(n_1,\,\dfrac{1}{2}+n_2,\, \dfrac{1}{2}+n_3\right) &=(n_1-n_2+n_3)\bf{v}_1+(2n_2-2n_3)\bf{v}_2+(1+2n_3)\bf{v}_3
\end{aligned}
$$

이므로 모든 $\text{FC}$ 의 벡터들을 표현 할 수 있다. 따라서 기저이다.

:::

</br>

## 제 5 장 탐구문제

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S01}

공간의 점 $P_0,\,P_1,\ldots,\,P_k$ 에 대하여 벡터

$$
\overrightarrow{P_0P_1},\ldots,\,\overrightarrow{P_0P_k}
$$

가 일차독립이면, 점 $P_0,\,P_1,\ldots,\,P_k$ 는 일반위치 (general position) 에 있다고 한다. 공간속의 점 $P_0,\ldots,\,P_k$ 가 일반위치에 있기 위한 필요충분조건은 벡터,

$$
\overrightarrow{P_0P_1},\,\overrightarrow{P_1P_2},\ldots,\,\overrightarrow{P_{k-1}P_k}
$$

가 일차독립인 것을 보여라.

:::

</div>

::: {.solution}

($1$) $\bf{a}_i = \overrightarrow{P_0P_k}$ 라 하고, $\bf{b}_i = \overrightarrow{P_{i-1}P_i}$ 이라 하자. $\bf{b}_1=\bf{a}_1,\,\bf{b_i}= \bf{a}_i-\bf{a}_{i-1}$ for $i=2,\ldots,\,k$ 임을 알 수 있다.

($2$) $\bf{a}_1,\ldots,\,\bf{a}_k$ 가 일차독립임을 가정하자.

$$
\begin{aligned}
c_1 \bf{b}_1 + &\cdots + c_k \bf{c}_k=0 \\[0.3em]
&\implies c_1(\bf{a}_1)+c_2(\bf{a}_2-\bf{a}_1)+ \cdots + c_k (\bf{a}_k -\bf{a_{k-1}})=0 \\
&\implies (c_1-c_2)\bf{a}_1+(c_2-c_3)\bf{a}_2 + \cdots +(c_{k-1}-c_k)\bf{a}_{k-1}+c_k \bf{a}_k=0 \\
&\implies c_k =0,\, c_k=c_{k-1}=\cdots =c_2=c_1\\
&\implies c_1=c_2=\cdots =c_k=0
\end{aligned}
$$

따라서 $\bf{b}_1,\ldots,\,\bf{b}_k$ 는 일차독립이다.

($3$) $\bf{b}_1,\ldots,\,\bf{b}_k$ 가 일차독립임을 가정하자. $\bf{a}_1=\bf{b}_1$ 이며, $\bf{a}_j = \bf{b}_1+\cdots +\bf{b}_j$ 이므로,

$$
\begin{aligned}
d_1\bf{a}_1 + &\cdots +d_k \bf{a}_k = 0 \\[0.3em]
&\implies d_1\bf{b}_1+ d_2(\bf{b}_1+\bf{b}_2)+ \cdots + d_k(\bf{b}_1+\cdots +\bf{b_k})=0\\
&\implies  (d_1+\cdots +d_k)\bf{b_1}+ (d_2 + \cdots +d_k)\bf{b}_2 +\cdots + d_k\bf{b}_k =0 \\
&\implies d_k=0,\, d_k+d_{k-1}=0 ,\ldots, \, d_1+ \cdots + d_k = 0\\
&\implies d_1=d_2=\cdots =d_k=0
\end{aligned}
$$

따라서 $\bf{a}_1,\ldots,\,\bf{a}_k$ 도 일차독립이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S02}

평면에서 일반위치에 있는 석점 $P_1,\,P_2,\,P_3$ 와 $m_1+m_2+m_3=1$ 인 실수 $m_1,\,m_2,\,m_3$ 에 대하여,

$$
Q:=m_1P_1+m_2P_2+m_3P_3
$$

로 두자. 이 때 점 $Q$ 를 지나고 직선 $P_2P_3$ 와 나란한 직선이 직선 $P_1P_2$ 와 만나는 점은

$$
m_1P_1 +(m_2+m_3)P_2
$$

임을 보이라.

:::

</div>

::: {.solution}

$Q$ 를 지나고 직선 $P_2P_3$ 나란한 직선이 직선 $P_1P_2$ 와 만나는 점 $S$ 의 위치는 어떤 실수 $0\le r \le 1$ 에 대하여 $rP_1+(1-r)P_2$ 라 할 수 있다. $QS$ 와 $P_2P_3$ 는 평행하므로, 어떤 실수 $t$ 에 대해 $tQS=P_2P_3$ 이다. 즉,

$$
t\left(rP_1+(1-r)P_2 - m_1P_1-m_2P_2-m_3P_3\right)= P_3-P_2
$$

이다. 여기서 $P_1,\,P_2,\,P_3$ 가 일반위치에 존재하므로,

$$
(tr-tm_1)P_1 +(t-tr-tm_2+1)P_2 -(tm_3+1)P_3=0
$$

그렇다면 $tr-tm_1=0,\, t-tr-tm_2+1=0,\, tm3+1=0$ 이다. $t(r-m_1)=0$ 에서 $t=0$ 이면 두번째 조건에서 $1=0$ 이 되므로 모순. 따라서 $t\ne 0$ and $r=m_1$ 이다. 즉,

$$
S=m_1P_1+(1-m_1)P_2=m_1P_1+(m_2+m_3)P_2
$$

이다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S03}

공간의 점 $P_0,\,P_1,\ldots,\,P_k$ 가 일반위치에 있지 않으면,

$$
\begin{aligned}
t_0+\cdots + t_k = 1 &= t'_0+\cdots+t_k'\\
(t_0,\ldots,\,t_k) &\ne (t'_0,\ldots,\, t'_k)\\
t_0P_0 + \cdots + t_k P_k &= t'_0P_0 + \cdots + t_k'P_k
\end{aligned}
$$

을 만족시키는 실수 $t_0,\ldots,\,t_k,\,t'_0,\ldots,\,t'_k$ 가 존재함을 보이라.

:::

</div>

::: {.solution}

Let $\bf{a}_i = \overrightarrow{P_iP_0}$ for $i=1,\ldots,\,n$. 문제 @exr-CAL_5_S01 에 의해 $\bf{a}_1,\ldots,\,\bf{a}_k$ 는 일차종속이므로, 어떤 nonzero $c_1,\ldots,\,c_k$ 에 대해

$$
c_1\bf{a}_1+\cdots +c_k\bf{a}_k=0
$$

이며,

$$
c_1(P_1-P_0)+c_2(P_2-P_0)+ \cdots c_k (P_k-P_0)=0 \implies -(c_1+\cdots +c_k)P_0 +c_1P_1 + \cdots +c_k P_k=0
$$

을 만족시키는 nonzero $c_1,\ldots,\,c_k$ 가 존재함을 의미한다. 이제 $c_0=-(c_1+\cdots+c_k )$ 라 하면,

$$
c_0P_0+\cdots +c_kP_k=0
$$

을 만족하는 $c_0,\ldots,\,c_k$ 중 최소한 하나는 $0$ 이 아님을 의미한다. $c_0 \ne 0$ 이면 어떤 $c_1,\ldots,\,c_k$ 중 nonzero 인 것이 존재한다. 따라서,

$$
P_0 = \dfrac{1}{(c_1+\cdots + c_k)}\left(c_1P_1+\cdots c_k P_k\right)
$$

이므로 $t_0=1,\,t_2=\cdots = t_k=0$ 과 $t'_0=0,\,t'_k = c_k/(c_1+\cdots +c_k)$ 이면 주어진 조건을 만족한다.

$c_0=0$ 이면 $c_1+\cdots + c_k=0$ 이며 최소한 하나의 $c_1,\ldots,\,c_k$ 는 nonzero 이다. $c_1P_1+\cdots + c_kP_k=0$ 이므로,

$$
P_1 + c_1P_1+\cdots +c_kP_k = P_1
$$

이며 주어진 조건을 만족한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S04}

벡터 $\bf{v}_1,\ldots,\,\bf{v}_k$ 에 의하여 생긴 **(선형)부분공간** 이란

$$
\langle\langle \bf{v}_1,\ldots,\,\bf{v}_k\rangle\rangle :=\{t_1\bf{v}_1+\cdots + t_k\bf{v}_k\mid t_1,\ldots,\,t_k\in \mathbb{R}\}
$$

을 뜻한다. 이 때 $\langle\langle \bf{v}_1,\ldots,\,\bf{v}_k\rangle\rangle$ 의 차원은 $k$ 를 넘지 않음을 보여라.

:::
</div>

:::{.solution}

trivial

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S05}

삼차원 좌표공간에서 식

$$
x+y+z=0,\quad x-y-z=0
$$

을 만족시키는 점들의 집합은 벡터공간임을 보이고, 그 벡터공간의 기저를 구하라.

:::

</div>

::: {.solution}

$X=\{(x,\,y,\,z) \in \mathbb{R}^3: x+y+z=0,\, x-y-z=0\}$ 는 문제에 주어진 집합이다. $(x,\,y,\,z),\,(x',\,y',\,z')\in X$ 라 하고 임의의 $a,\,b\in \mathbb{R}$ 에 대해,

$$
a(x,\,y,\,z)+b(x',\,y',\,z') =(ax+bx',\, ay+by',\,az+bz')\in X
$$

임을 보이면 된다.

$$
\begin{gather}
(ax+bx')+(ay+by')+(az+bz')=a(x+y+z)+b(x'+y'+z')=0\\
(ax+bx')-(ay+by')-(az+bz')=a(x-y-z)+b(x'-y'-z')=0
\end{gather}
$$

이므로 $a(x,\,y,\,z)+b(x',\,y',\,z')\in X$ 이다. 따라서 $X$ 는 벡터공간이다.

$x+y+z=0$ 과 $x-y-z=0$ 을 만족하는 $(x,\,y,\,z)$ 는 임의의 $t\in \mathbb{R}$ 에 대해 $(0,\,t,\,-t)$ 이어야 한다. 따라서 기저는 $(0,\,1,\,-1)$ 일 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S06}

#### Gram-Schmidt 방법 

일차독립인 벡터 $\bf{v}_1,\ldots,\,\bf{v}_k$ 에 대하여,

$$
\bf{w}_i :=\bf{v}_i - \dfrac{\bf{v}_i\cdot \bf{w}_1}{\bf{w}_1 \cdot \bf{w}_1} \bf{w}_1 - \cdots - \dfrac{\bf{v}_i \cdot \bf{w}_{i-1}}{\bf{w}_{i-1}\cdot \bf{w}_{i-1}} \bf{w}_{i-1}\quad (i=1,\ldots,\,k)
$$

로 정의하자. 이 때 $\bf{w}_i\ne 0$ 임을 보이라. 또,

$$
\bf{u}_i = \dfrac{\bf{w}_i}{|\bf{w}_i|} \quad (i=1,\ldots,\,k)
$$

로 두면, 임의의 $i\in \{1,\ldots,\,k\}$ 에 대하여

$$
\langle\langle \bf{u}_1,\ldots,\,\bf{u}_i\rangle\rangle = \langle\langle \bf{v}_1,\ldots,\,\bf{v}_i\rangle \rangle \\
\bf{u}_i \perp \langle\langle \bf{u}_1,\ldots,\,\bf{u}_{i-1}\rangle \rangle ,\,\quad \bf{u}_i \cdot \bf{v}_{i} >0,\quad |\bf{u}_i|=1
$$

임을 보이라. 따라서 $\bf{u}_1,\ldots,\,\bf{u}_k$ 는 서로 수직인 단위벡터가 된다.

::: 

</div>

::: {.solution}

($1$) $\bf{w}_1=\bf{v}_1$ 이므로 $\bf{w}_1\ne 0$ 이다. $\bf{w}_i$ 는 linear combination of $\bf{v}_i ,\,\bf{w}_1,\ldots,\,\bf{w}_{i-1}$ 이며,

$$
\bf{w}_i = \bf{v}_i - \left(\text{linear combination of }\bf{v}_1,\cdots,\,\bf{v}_{i-1}\right)
$$

이다. $\bf{v}_1,\ldots,\,\bf{v}_k$ 는 일차독립이므로 $\bf{w}_i\ne 0$ 이다.

($2$) $\bf{u}_j$ 는 linear combination of $\bf{v}_1,\ldots,\,\bf{v}_j$ 이므로 $\langle\langle \bf{u}_1,\ldots,\,\bf{u}_i\rangle\rangle \subset \langle\langle \bf{v}_1,\ldots,\,\bf{v}_i\rangle\rangle$ 이다.

$\bf{u}_1,\ldots,\,\bf{u}_k$ 가 일차독립임을 보이기 위해 다음을 보이자.

> $n$ 공간의 영벡터가 아닌 벡터들  $\bf{a}_1,\ldots,\,\bf{a}_n$ 에서 $i\ne j \implies \bf{a}_i \cdot \bf{a}_j= 0$ 이면 $\bf{a}_1,\ldots,\,\bf{a}_n$ 은 일차독립이다.

이를 보이기 위해 $c_1\bf{a}_1+\cdots c_n\bf{a}_n=0$ 이라 하자. 이 벡터에 임의의 벡터 $\bf{a}_j$ 와의 내적을 구하면, $c_j |\bf{a}_j|^2=0$ 이므로 $c_j=0$ 이다. 따라서 $\bf{a}_1,\ldots,\,\bf{a}_n$ 은 일차독립이다.

이제 $\bf{w}_1,\ldots,\,\bf{w}_k$ 에 대하여 $1\le i,\,j\le k,\, i \ne j \implies. \bf{w}_i\cdot\bf{w}_j=0$ 임을 보이자.

$$
\bf{w}_2 = \bf{v}_2 -\dfrac{\bf{v}_2\cdot \bf{w}_1}{\bf{w}_1 \cdot \bf{w}_1}\bf{w}_1 \implies \bf{w}_1 \cdot \bf{w}_2 = \bf{w}_1\cdot \bf{v}_1 -\bf{w}_1 \cdot \bf{w}_1=0
$$

이다. 임의의 $n$ 에 대해 $0\le i\ne j\le n$ 에서 $\bf{w}_i \cdot \bf{w}_j =0$ 임을 가정하자.

$$
\bf{w}_{n+1}=\bf{v}_{n+1} -\sum_{j=1}^{n} \dfrac{\bf{v}_{n+1}\cdot \bf{w}_j}{\bf{w}_j \cdot \bf{w}_j}\bf{w}_j
$$

이면

$$\bf{w}_{n+1}\cdot \bf{w}_i = \bf{v}_{n+1} \cdot \bf{w}_i-\sum_{j=1}^{n} \dfrac{\bf{v}_{n+1}\cdot \bf{w}_j}{\bf{w}_j \cdot \bf{w}_j}(\bf{w}_j \cdot \bf{w}_i) = \bf{v}_{n+1}\cdot \bf{w}_i-\bf{v}_{n+1}\cdot \bf{w}_i=0
$$

이다. 즉 induction에 의해 $\bf{w}_1,\ldots,\,\bf{w}_k$ 는 일차독립임을 보였다. 따라서 $\bf{u}_1,\ldots,\,\bf{u}_k$ 는 일차독립이다. 따라서 $\bf{u}_1,\ldots,\,\bf{u}_i$ 는 일차독립이다. (일차독립인 집합의 부분집합은 일차독립이다.)

이제 $\langle\langle \bf{u}_1,\ldots,\,\bf{u}_i\rangle\rangle \supset \langle\langle \bf{v}_1,\ldots,\,\bf{v}_i\rangle\rangle$ 임을 보이자. 우리는 $\bf{u}_1,\ldots,\,\bf{u}_i$ 가 일차독립이며, $\langle\langle \bf{u}_1,\ldots,\,\bf{u}_i\rangle\rangle \subset \langle\langle \bf{v}_1,\ldots,\,\bf{v}_i\rangle\rangle$  임을 안다. 만약 $\langle\langle \bf{u}_1,\ldots,\,\bf{u}_i\rangle\rangle \ne \langle\langle \bf{v}_1,\ldots,\,\bf{v}_i\rangle\rangle$ 이면 어떤 $\bf{v}\in \langle\langle \bf{v}_1,\ldots,\,\bf{v}_i\rangle\rangle$ 에 대해 $v \not\in \langle\langle \bf{u}_1,\ldots,\,\bf{u}_i\rangle\rangle$  이어야 한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S07}

두 연속함수 $f,\,g:[0,\,1]\to \mathbb{R}$ 에 대하여

$$
\langle f,\,g \rangle:=\int_0^1 f(t)g(t)\,dt,\qquad \|f\|:=\sqrt{\langle f,\,f\rangle}
$$

로 정의하자. 이 때,

$$
\langle f,\,g\rangle \le \|f\|\cdot\|g\|
$$

임을 보이라. 여기서 등호가 성립할 때는 언제인가? 또,

$$
\left(\int_0^1 f(t)\,dt\right)^2 \le \int_0^1 f(t)^2 \,dt
$$
임을 보이라.

:::

</div>

::: {.solution}

우선,

$$
\|f\|^2=\langle f,\,f\rangle =\int_0^1 f(t)^2 \, dt \ge 0
$$

이며 $\|f\|=0 \iff f(t)=0,\, \forall t\in [0,\,1] $ 임을 알 수 있다. 임의의 $\lambda \in \mathbb{R}$ 에 대해 $\|f+\lambda g\|\ge 0$ 이므로,

$$
\int_0^1 (f(t)+\lambda g(t))^2\,dt =\|f\|^2+2\lambda \langle f,\,g\rangle+\lambda^2\|g\|^2 \ge 0
$$

이다 따라서,

$$
\langle f,\,g\rangle^2 -\|f\|^2\cdot \|g\|^2 \le 0 \implies \langle f,\,g\rangle\le |\langle f,\,g\rangle |\le \|f\|\cdot \|g\|
$$

이다. 만약 $g(t)=c f(t)$ for some $c >0 $ 이면 $\langle f,\,g\rangle = c\|f\|^2 =\|f\|\cdot \|cf\|$ 이다.

$g(t)=1$ 이라 하면 연속함수이므로,

$$
\begin{aligned}
\langle f,\,1\rangle &= \int_0^1 f(t)\, dt\,\\
\|f\| &= \sqrt{\int_0^1 f(t)^2\, dt}\\
\|1\| &=\sqrt{\int_0^1 1\, dt}=1
\end{aligned}
$$

이며,

$$
\left|\int_0^1 f(t)\, dt \right|= \left|\langle f,\,1\rangle\right| \le \|f\|\cdot \|1\|=\sqrt{\int_0^1 f(t)^2\, dt}
$$

이므로, 양 변을 제곱하면,

$$
\left(\int_0^1 f(t)\,dt\right)^2 \le \int_0^1 f(t)^2 \,dt
$$

를 얻는다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S08}

다음 네 행렬은 일차독립인가?

$$
\begin{pmatrix} 0 & 1 \\ 1 & 1\end{pmatrix}, \quad \begin{pmatrix} 1 & 0 \\ 1 & 1\end{pmatrix},\quad \begin{pmatrix} 1 & 1 \\ 0 & 1\end{pmatrix},\quad \begin{pmatrix} 1 & 1 \\ 1 & 0\end{pmatrix}
$$

:::

</div>

::: {.solution}

$$
\begin{aligned}
\begin{pmatrix} 0 & 0 \\ 0 & 0 \end{pmatrix} &= a\begin{pmatrix} 0 & 1 \\ 1 & 1\end{pmatrix}+ b\begin{pmatrix} 1 & 0 \\ 1 & 1\end{pmatrix}+c\begin{pmatrix} 1 & 1 \\ 0 & 1\end{pmatrix}+d\begin{pmatrix} 1 & 1 \\ 1 & 0\end{pmatrix} \\[0.3em]
&= \begin{pmatrix} b+c+d & a+c+d \\ a+b+d & a+b+c\end{pmatrix}
\end{aligned}
$$

이다, 즉,

$$
a+b+c=0\\
a+b+d=0\\
a+c+d=0\\
b+c+d=0
$$

을 만족하는 $a,\,b,\,c,\,d$ 를 찾자. 네 식을 더하면 $3(a+b+c+d)=0$ 이므로 $a+b+c+d=0$ 이다. 따라서 $a=b=c=d=0$ 이다. 따라서 일차독립이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S09}

미분방정식

$$
f''(x)-f(x)=0
$$

을 만족히키는 함수 $f:\mathbb{R} \to \mathbb{R}$ 전체의 집합을 $V$ 라고 두자. 이 때

($1$) $V$ 는 벡터공간임을 설명하라.

($2$) $V$ 의 한 원소 $f$ 가 서로 다른 실수 $a,\,b$ 에 대하여 $f(a)=f(b)=0$ 이면

$$
\int_a^b f(x)^2 \, dx = -\int_a^b f'(x)^2\, dx
$$
임을 보이라.

($3$) 함수 $e^x$ 와 $e^{-x}$ 는 $V$ 의 기저임을 보이라.

($4$) $V$ 의 차원을 구하라.

:::

</div>

::: {.solution}

($1$) $f,\,g\in V,\, c\in \mathbb{R}$ 에 대해 

$$
(f(x)+cg(x))''-(f(x)+cg(x))=(f''-f(x))+c(g''(x)-g(x))=0
$$ 

이므로 $f+cg\in V$ 이다. 따라서 벡터공간이다.

($2$) $f(x)=f''(x)$ 이므로,

$$
\begin{aligned}
\int_a^b f(x)^2\,dx &= \int_a^b f(x)f''(x)\,dx = \left[f(x)f'(x)\right]_{x=a}^{x=b}-\int_a^b f'(x)f'(x)\,dx \\[0.3em]
&=-\int_a^b f'(x)^2\,dx
\end{aligned}
$$

($3$) $e^x,\, e^{-x}\in V$ 임은 쉽게 알 수 있다. 또한 $c_1e^x+c_2e^{-x}=0\implies c_1=c_2=0$ 이므로 $e^x,\,e^{-x}$ 는 일차독립이다. 주어진 미분방정식을 만족시키는 함수는 $e^x$ 와 $e^{-x}$ 의 선형 결합 함수 뿐이므로 (이게 미적분학 범위인가....) $\{e^x,\,e^{-x}\}$ 는 $V$ 의 기저이다.

($4$) ($3$) 에 따라 2 차원이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S10}

등장사상 $T:\mathbb{R}^n \to \mathbb{R}^n$ 에 대하여,

$$
X\mapsto \operatorname{dist}(X,\,T(X)),\qquad(X\in \mathbb{R}^n)
$$

가 상수함수이면 $T$ 는 평행이동임을 보여라.

:::

</div>

::: {.solution}

$f:\mathbb{R}^n\to \mathbb{R}$ 을 $f(X)=\operatorname{dist}(X,\,T(X))=\|X-T(X)\|$ 로 정의한다. $T$ 가 평행이동이면 $f$ 가 상수함수임은 자명하다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S11}

실수 $c_1,\,c_2,\,c_3,\,c_4$ 에 대하여 미지수 $x,\,y,\,z$ 에 관한 방정식

$$
\begin{aligned}
x + y + z &= c_1, \\
x + 2y + 3z &= c_2, \\
x + 4y + 9z &= c_3, \\
x + 8y + 27 z &= c_4 
\end{aligned}
$$

는 일반적으로 해를 가지지 않음을 설명하라.

:::

</div>

::: {.solution}

$\mathbb{R}^3$ 에서 생각하자. $X=(x,\,y,\,z)$, $A=(1,\,1,\,1)$, $B=(1,\,2,\,3)$, $C=(1,\,4,\,9)$, $D=(1,\,8,\,27)$ 이라 하면 위 식은,

$$
X\cdot A=c_1,\quad X\cdot B=c_2,\quad X\cdot C=c_3,\quad X\cdot D=c_4
$$

가 된다. $\mathbb{R}^3$ 의 기저벡터는 3개이며,

$$
\begin{aligned}
aA+bB+cC=0 &\implies (a+b+c,\, a+2b+4c,\, a+3b+9c)=(0,\,0,\,0)\\
&\implies a+b+c=0,\, b+3c=0,\, b+5c=0\\
&\implies a=b=c=0
\end{aligned}
$$

이므로 $A,\,B,\,C$ 는 $\mathbb{R}^3$ 의 기저이다. $D=6A-11B+6C$ 이므로,

$$
c_4=X\cdot D=X\cdot (6A-11B+6C)=6c_1-11c_2+6c_3
$$

이어야 한다. 만약 $6c_1-11c_2+6c_3-c_4\ne 0$ 이면  방정식들은 해를 갖지 않는다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_5_S12}

차수가 $n$ 이하인 다항식 전체로 이루 어진 공간의 차원은 $n+1$ 임을 설명하라.

:::

</div>

::: {.solution}

일단 차수가 $n$ 이하인 다항식 전체로 이루어진 공간은 $1,\,x,\,x^2,\ldots,\,x^n$ 의 선형결합으로 이루어진다.

$$
c_0+c_1x+c_2x^2+ \cdots + c_nx^n=0
$$

이라 하면 $c_0= c_1=\cdots =c_n=0$ 이므로 기저는 $1,\,x,\,x^2,\ldots,\,x^n$ 이다. 따라서 $n+1$ 차원 공간이다.

:::
