<!-- ---
title: "다변수 함수의 미분"
number-sections: true
number-depth : 3
crossref:
  chapters: true
--- -->

{{< include ../../latexmacros.qmd >}}

</br>

## 기본 개념


### 다변수 함수의 미분 {#sec-CM_differentiation_of_multivariable_function}

선형변환 $T:\R^n \to \R^m$ 은 $m \times n$ 행렬로 표현할 수 있다는 것을 안다. 물론 미리 $\R^n$ 과 $\R^m$ 의 기저가 정해져야 한다. $\R^n$ 의 기저 $\mathcal{B}_n=(\bf{v}_1,\ldots,\,\bf{v}_n)$ 과 $\R^m$ 의 기저 $\mathcal{B}_m=(\bf{u}_1,\ldots,\,\bf{u}_m)$ 에 대한 $T$ 에 대한 행렬 표현을 $[T]_{\mathcal{B}_n,\, \mathcal{B}_m}$ 라고 하자. $\R^m$ 과 $\R^n$ 각각의 표준기저에 대한 행렬표현은 $[T]$ 라고 쓰기로 하자. 즉 $T(\bf{x}) = [T]\cdot \bf{x}$ 이다. 

혼동의 여지가 있지만 $[T]$ 의 $i$ 행 $j$ 열 성분을 $[T]_{ij}$ 라고 표현하기로 하자. 첨자가 인덱스이면 행렬의 성분이며 첨자가 기저이면 특정 기저의 행렬표현이다. 하지만 여기서는 대부분 전자의 의미로 사용되며, 혼동의 여지가 있다면 특정하기로 하자. 즉 $\bf{x} = \begin{bmatrix} x_1 & \ldots & x_n\end{bmatrix}^T \in \R^m$ 과 $\bf{y} = T(\bf{x})$ 에 대해  

$$
y_i = (T(\bf{x}))_i = \sum_{i=1}^m [T]_{ij}x_j
$$

이다. 

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-CM_differentiation_of_multivariable_function}

#### 다변수 함수의 미분

함수 $F:\R^n\to \R^m$ 와 $\bf{a}\in \R^n$ 에 대해 어떤 선형변환 $T:\R^n \to \R^m$ 이 존재하여

$$
\lim_{\bf{h} \to \bf{0}} \dfrac{\|F(\bf{a}+\bf{h}) - F(\bf{a}) - T(\bf{h})\|}{\|\bf{h}\|} = 0
$$ {#eq-CM_derivative_of_vector_function}

일 때 $F$ 는 $\bf{a}$ 에서 미분가능하다 라고 하며 $T$ 를 $DF(\bf{a})$ 혹은 $F'(\bf{a})$ 라고 쓴다. 

::: 
:::

</br>

즉 $DF(\bf{a}) \in \mathcal{M}_{m \times n}(\mathbb{R})$ 이다. 

</br>


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_uniqueness_of_derivative}

$F:\R^n \to \R^m$ 이 $\bf{a}\in \R^n$ 에서 미분가능하다면 @eq-CM_derivative_of_vector_function 를 만족하는 선형변환은 유일하다. 

:::

</div></br>

::: {.proof}

$T,\, L\in \mathcal{L}(\R^n,\, \R^m)$ 이 @eq-CM_derivative_of_vector_function 를 만족한다고 하자. 그리고 $D(\bf{h}) = F(\bf{x}-\bf{a})-F(\bf{a})$ 라고 하자. 

$$
\begin{aligned}
\|T(\bf{h})-L(\bf{h})\| &= \|T(\bf{h})-D(\bf{h}) + D(\bf{h})- L(\bf{h})\| \\[0.3em]
&\le \|T(\bf{h})-D(\bf{h}) \| + \|L(\bf{h})- D(\bf{h})\|
\end{aligned}
$$

이다. 위 식의 양변을 $\|\bf{h}\|$ 로 나누고 $\lim_{\bf{h}\to \bf{0}}$ 을 취하면 @eq-CM_derivative_of_vector_function 로 부터 

$$
\lim_{\bf{h}\to \bf{0}} \dfrac{\|T(\bf{h})-L(\bf{h})\|}{\|\bf{h}\|} =0
$$ {#eq-CM_uniqueness_of_derivative_1}

임을 안다. 이제 두 선형변환 $T,\,L$ 이 @eq-CM_uniqueness_of_derivative_1 를 만족하면 $T=L$ 임을 보이자. 임의의 $\bf{x}\in \R^n$ 에 대해 

$$
0 = \lim_{t\to 0} \dfrac{\|T(t\bf{x})-L(t\bf{x})\|}{\| t\bf{x}\|} = \dfrac{\|T(\bf{x})- L(\bf{x})\|}{\|\bf{x}\|}
$$

이므로 $T=L$ 이다. $\square$

:::

</br>

### 야코비 행렬 {#sec-CM_jacobian}

$F:\R^n\to\R^m$ 이 모든 $\bf{x}\in \R^n$ 에서 미분가능하면 마치 일변수 함수의 $f'(x)$ 처럼 $F'(\bf{x})$ 와 같이 쓸 수 있다. 이 때 $F'(\bf{a})$ 는 선형변환이므로 행렬로 표현할 때 기저에 따라 그 성분값이 달라진다. 여기에 기준이 되는 야코비 행렬을 아래와 같이 정의한다.

</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-CM_jacobian}

#### 야코비 행렬

$F:A \subset \R^n \to \R^m$ 에 대해 $DF(\bf{a})$ 를 $\R^n$ 과 $\R^m$ 의 표준기저에 대해 표현한 행렬을 **야코비 행렬 (Jacobian matrix)** 이라고 하며 $J[F](\bf{a})$ 혹은 $J_F(\bf{a})$ 와 같이 표기한다. 모든 $A\subset \R^n$ 에서 미분가능할 때는 $A$ 에서 정의된 함수로서 $J_F(\bf{x})$ 라고 표기한다.

::: 
:::

</br>

### 연습문제 {.unnumbered}



<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_differentiability_of_identity_function}

@def-CM_projection_function 에서 정의된 $\bf{\pi}:\R^n \to \R^n$ 은 모든 $\bf{x}\in \R^n$ 에서 미분가능함을 보여라. 사영함수 $\pi_i:\R^n \to \R$ 도 모든 $\bf{x}\in \R^n$ 에서 미분가능함을 보여라.

:::
</div></br>

::: {.solution}

$I_n :\R^n \to \R^n$ 을 항등사상이라고 하자. $\bf{\pi} = I_n$ 이며 $\pi_i = \bf{e}_i^T$ 임을 안다.
$$
\|\bf{\pi}(\bf{x}+\bf{h})-\bf{\pi}(\bf{x})-I(\bf{h})\| = 0 
$$

이므로 $D\bf{\pi}'(\bf{x})=I_n$ 이다. 또한

$$
\|\pi_i (\bf{x}+\bf{h})-\pi_i (\bf{x})-\pi_i(\bf{h})\| = 0
$$

이므로 $D\pi_i(\bf{x})= \pi_i = \bf{e}_i^T$ 이다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_1}
#### Spivak 2_1

$F:\R^n \to \R^m$ 이 $\bf{a}$ 에서 미분가능하면 $\bf{a}$ 에서 연속임을 보여라.

:::

</div></br>

::: {.solution}

@eq-CM_derivative_of_vector_function 로부터 $\displaystyle \lim_{\bf{h}\to \bf{0}} \|F(\bf{a}+\bf{h}) - F(\bf{a}) - T(\bf{h})\| = 0$ 이며 @exr-CM_spivak_1_10 로부터 $\displaystyle \lim_{\bf{h} \to \bf{0}} T(\bf{h})=\bf{0}$ 이므로 $\displaystyle \lim_{\bf{h}\to \bf{0}} F(\bf{a}+\bf{h})-F(\bf{a}) = \bf{0}$ 이다. 즉 $F$ 는 $\bf{a}$ 에서 연속이다.
:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_2}
#### Spivak 2_2

$f:\R^2 \to \R$ 이 모든 $y_1,\,y_2\in \R$ 에 대해 $f(x,\,y_1) = f(x,\,y_2)$ 일 때 $f$ 가 두번째 변수에 대해 독립이라고 한다. $f$ 가 두번째 변수에 대해 독립일 필요충분조건이 어떤 $g:\R \to \R$ 이 존재하여 $f(x,\,y)=g(x)$ 임을 보여라. $f'(a,\,b)$ 를 $g'$ 으로 표현하면 무엇인가?

:::

</div></br>

::: {.solution}

$f(x,\,y)=g(x)$ 이면 $f$ 가 두번째 변수에 대해 독립임은 자명하다. 임의의 고정된 $y_1,\,y_2\in \R$ 에 대해 $g_1(x) = f(x,\,y_1)$, $g_2(x) = f(x,\,y_2)$ 이면 $g_1=g_2$ 이다. 따라서 $f$ 가 두번째 변수에 대해 독립이면 $g(x) = f(x,\,y)$ 인 함수 $g$ 가 존재한다.

$f'(a,\,b) = g'(a)$ 임은 쉽게 알 수 있다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_4}
#### Spivak 2_4

$g$ 는 단위원 $\{\bf{x}\in \R^2 : \|\bf{x}\|=1\}$ 에서 정의된 연속인 실함수이며 $g(0,\,1)= g(1,\,0)=0$, $g(-\bf{x})=-g(\bf{x})$ 이다. $f:\R^2 \to \R$ 은 다음과 같이 정의된다.

$$
f(\bf{x}) = \left\{\begin{array}{ll} \|\bf{x}\| \cdot g\left(\dfrac{\bf{x}}{\|\bf{x}\|}\right), \qquad &\bf{x}\ne \bf{0}, \\ 0. & \bf{x}=\bf{0} \end{array}\right.
$$

($a$) $\bf{x}\in \R^2$ 이고 $h:\R\to\R$ 이 $h(t) := f(t\bf{x})$ 로 정의되었다면 $h$ 가 미분가능함을 보여라.

($b$) $g = 0$ 일 때를 제외하면 $f$ 가 $(0,\,0)$ 에서 미분가능하지 않음을 보여라.

:::

</div></br>

::: {.solution}

($a$) $h(t) = tf(\bf{x})$ 이므로 $h'(t) = f(\bf{x})$ 이다.

($b$) $g=0$ 이면 $f$ 는 자연스럽게 미분가능. 이제 $g\ne 0$ 임을 가정한다. $Df(\bf{0})$ 이 존재한다면 어떤 $1 \times 2$ 행렬 $T=\begin{bmatrix} a & b \end{bmatrix}$ 에 대해

$$
\lim_{\bf{h} \to \bf{0}}\dfrac{f(\bf{h})-f(\bf{0}) - T(\bf{h})|}{\|\bf{h}\|} = \lim_{(h,\,k) \to \bf{0}} \dfrac{|f(h,\,k) - (ah+bk)|}{\sqrt{h^2+k^2}} = 0
$$

이어야 한다. 우선 $h=0,\, k\to 0$ 을 보면 

$$
0=\lim_{k \to 0}\dfrac{|f(0,\,k) - bk|}{|k|} = \lim_{k \to 0}\dfrac{|(|k|g(0,\,1)) - bk|}{|k|} = |b|
$$

이어야 한다. 즉 $b=0$ 이다. 같은 방법으로 $a=0$ 임을 보일 수 있다. $f$ 가 $(0,\,0)$ 에서 미분가능하다면 임의의 $\bf{x}\in \R^2$ 에 대해

$$
\lim_{\bf{x}\to \bf{0}}  g\left(\dfrac{\bf{x}}{\|\bf{x}\|}\right) =0 
$$

이며 $g$ 는 연속이므로 $g=0$ 이다. 즉 $g\ne 0$ 이면 $f$ 는 $(0,\,0)$ 에서 미분가능하지 않다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_5}
#### Spivak 2_5

$f:\R^2 \to \R$ 이 아래와 같이 정의되었다.

$$
f(x,\,y) = \left\{ \begin{array}{ll} \dfrac{x|y|}{\sqrt{x^2+y^2}}, \qquad & (x,\,y) \ne \bf{0}, \\ 0,&(x,\,y) = \bf{0}.\end{array}\right.
$$

$f$ 는 @exr-CM_spivak_2_4 와 같은 종류의 문제로 $(0,\,0)$ 에서 미분가능하지 않음을 보여라.

:::

</div></br>

::: {solution}

$f$ 가 $0,\,0$ 에서 미분가능하다면 $\bf{h}= (h,\,k)$ 에 대해 어떤 $T=\begin{bmatrix}a & b\end{bmatrix}$ 가 존재하여
$$
0 = \lim_{\bf{h}\to\bf{0}} \dfrac{|f(h,\,k)-f(0,\,0) - (ah+bk)|}{\|\bf{h}\|} =  \lim_{\bf{h}\to\bf{0}} \dfrac{|f(h,\,k) - (ah+bk)|}{\|\bf{h}\|} 
$$

이어야 한다. 

$(0,\,k)$ 에서 $k\to 0$ 극한을 생각하면 $b=0$ 이며 $(h,\,0)$ 에서 $h\to 0$ 극한을 생각하면 $a=0$ 이다. 에제 $(h,\,h)$ 에서 $h\to 0$ 인 극한을 생각하자.

$$
\lim_{h \to 0} \dfrac{h|h|}{2h^2} = \pm \dfrac{1}{2} \ne 0
$$

이므로 $f$ 는 $(0,\,0)$ 에서 미분가능하지 않다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_6}
#### Spivak 2_6

$f:\R^2 \to \R$ 이 $f(x,\,y) = \sqrt{|xy|}$ 로 정의되었다. $f$ 가 $(0,\,0)$ 에서 미분가능하지 않음을 보여라.

:::

</div></br>

::: {.solution}

$f(0,\,0)=0$ 이다. $f$ 가 $(0,\,0)$ 에서 미분가능하다면 어떤 $T=\begin{bmatrix} a & b\end{bmatrix}$ 가 존재하여
$$
0 = \lim_{(h,\,k)\to \bf{0}}\dfrac{|f(h,\,k)- (ah+bk)|}{\sqrt{h^2+k^2}} =  \lim_{(h,\,k)\to \bf{0}}\dfrac{|\sqrt{|hk|}- (ah+bk)|}{\sqrt{h^2+k^2}}
$$

이어야 한다. $(h,\,0)$ 에서 $h \to 0$ 인 극한을 취하면 위 식은

$$
0=\lim_{h \to 0}\dfrac{|ah|}{|h|} = |a|
$$

이며, 같은 방법으로 $b=0$ 임을 구할 수 있다. 이제 $(h,\,h)$ 에서 $h\to 0$ 인 극한을 취하면

$$
\lim_{h \to 0}\dfrac{|h|}{\sqrt{2}|h|} = \dfrac{1}{\sqrt{2}}
$$

이므로 $f$ 는 $(0,\,0)$ 에서 미분가능하지 않다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_7}
#### Spivak 2_7

$f: \R^2 \to \R$ 이 $|f(\bf{x})|\le \|\bf{x}\|^2$ 을 만족한다고 하자. $f$ 가 $(0,\,0)$ 에서 미분가능함을 보여라.

:::

</div></br>

::: {.solution}

$f(0,\,0)=0$ 이다. 어떤 $T=\begin{bmatrix}a & b \end{bmatrix}$ 에 대해

$$
0 = \lim_{(h,\,k)\to \bf{0}}\dfrac{|f(h,\,k)- (ah+bk)|}{\sqrt{h^2+k^2}} 
$$ {#eq-CM_spivak_2_7}

이어야 한다. 

$$
\dfrac{f(\bf{h})}{\|\bf{h}\|^2}\le \|\bf{h}\|
$$

이므로 $a=b=0$ 에 대해 @eq-CM_spivak_2_7 를 만족한다. 따라서 $Df(\bf{0})= \begin{bmatrix}0 & 0\end{bmatrix}^T$ 이다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_8}
#### Spivak 2_8

$F:\R \to \R^2$ 이며 $F = \begin{bmatrix} f_1 & f_2\end{bmatrix}^T$ 라 하자. $F$ 가 $a\in R$ 에서 미분가능할 필요충분조건은 $f_1,\,f_2$ 가 각각 $a$ 에서 미분가능하며 $F'(a) = \begin{bmatrix} f_1'(a) & f_2'(a)\end{bmatrix}^T$ 임을 보여라.

:::

</div></br>

::: {.solution}

$F$ 가 $a$ 에서 미분가능하다면 $T=\begin{bmatrix} c_1 & c_2\end{bmatrix}^T$ 가 존재하여
$$
0 = \lim_{h \to 0}\dfrac{\|F(a+h) - F(a) - Th\|}{|h|}
$$

이어야 한다. $i=1,\,2$ 에 대해

$$
\dfrac{|f_i(a+h) - f_i(a) - c_ih|}{|h|} \le \dfrac{\|F(a+h) - F(a) - \begin{bmatrix} c_1h & c_2h\end{bmatrix}^T\|}{|h|}
$$

이므로 양변에 $h \to 0$ 극한을 취하면 좌변의 극한은 $0$ 이며 미분의 정의에 의해 $c_i = f_i'(a)$ 이다. 즉 $F'(a) = \begin{bmatrix} f_1'(a) & f_2'(a)\end{bmatrix}^T$ 이다. 

역으로 $f_1,\,, f_2$ 가 각각 $a$ 에서 미분가능하다고 하면 

$$
\begin{aligned}
&\dfrac{\|F(a+h) - F(a) - \begin{bmatrix} f_1'(a)h & f_2'(a)h\end{bmatrix}^T\|}{|h|} \\
&\qquad \qquad \qquad \le \dfrac{|f_1(a+h) - f_1(a) - f_1'(a)h|}{|h|} +\dfrac{|f_2(a+h) - f_2(a) - f_2'(a) h|}{|h|} 
\end{aligned}
$$

이므로 양변에 극한을 취하면 $0$ 좌변이 $0$ 이 됨을 안다. 즉 $F$ 는 $a$ 에서 미분가능하며 $F'(a) = \begin{bmatrix} f_1'(a) & f_2'(a)\end{bmatrix}^T$ 이다.
:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_9}
#### Spivak 2_9

$f,\,g :\R \to \R$ 이 $n\in \mathbb{Z}_+$ 에 대해

$$
\lim_{h \to 0}\dfrac{f(a+h)-g(a+h)}{h^n} = 0
$$

이면 $f$ 와 $g$ 는 $a$ 에서 $n$ 차 까지 같다 라고 한다.

($a$) $f$ 가 $a$ 에서 미분가능할 필요충분조건은 $g(x) = a_0+a_1(x-a)$ 인 함수 $g$ 가 존재하여 $f$ 와 $g$ 는 $a$ 에서 $1$ 차 까지 같은것임을 보여라.

($b$) $f'(a),\ldots,\, f^{(n)}(a)$ 가 존재하며 $g$ 는 아래와 같다고 하자.

$$
g(x) = \sum_{i=0}^n \dfrac{f^{(i)}(a)}{i!} (x-a)^i
$$

이 때 $f$ 와 $g$ 는 $n$ 차 까지 같음을 보여라.
:::

</div></br>

::: {.solution}

($a$) $f$ 가 $a$ 에서 미분가능하고 $g(x) = f(a) + f'(a)(x-a)$ 라고 하자. 

$$
\lim_{h \to 0} \dfrac{f(a+h)-g(a+h)}{h} = \lim_{h \to 0} \dfrac{f(a+h) - f(a) + f'(a) h}{h} = 0
$$

이므로 $f$ 와 $g$ 는 1차 까지 같다. 이제 $g(x)  = a_0 + a_1(x-a)$ 와 $f$ 가 $1$ 차 까지 같다고 하자.

$$
0 = \lim_{h \to 0} \dfrac{f(a+h) - a_0 + a_1(h)}{h}
$$

이다. $a_0 = f(a)$ 라고 하면 $f$ 의 미분가능성의 정의에 의해 $f$ 는 $a$ 에서 미분가능하며 $a_1=f'(a)$ 이다.

($b$) $k\in \mathbb{Z}_+$ 에 대해 

$$
\lim_{h \to 0}\dfrac{\displaystyle f(a+h) - \sum_{i=0}^n \dfrac{f^{(i)}(a)}{i!} (h)^i}{h^k}
$$

임을 보이자. 로피탈의 정리를 사용할 수 있으며 $h$ 에 대해 미분하면 쉽게 보일 수 있다.

:::

</br>

## 연쇄규칙과 미분의 기본 성질

### 다변수 함수의 연쇄규칙 {#sec-CM_chain_rule_for_mutivariable_function}

일변수 함수에 대한 연쇄규칙은 @thm-MA_chain_rule 을 참고하라.

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_chain_rule}

#### 다변수 함수의 연쇄규칙

$F:\R^n \to \R^m$ 이 $\bf{a}$ 에서 미분가능하며 $G:\R^m \to \R^p$ 가 $F(\bf{a})$ 에서 미분가능하다면 $G\circ F$ 도 $\bf{a}$ 에서 미분가능하며 다음이 성립한다.

$$
D(G\circ F)(\bf{a})= DG(F(\bf{a})) \circ DF(\bf{a})
$$ {#eq-CM_chain_rule}

위 식은 아래와 같이 쓸 수 있다.

$$
(G\circ F)'(\bf{a}) = G'(F(\bf{a})) \cdot F'(\bf{a}).
$$ {#eq-CM_chain_rule_2}
:::

</div></br>

::: {.proof}

$\bf{b}=F(\bf{a})$, $L=DF(\bf{a}),\, T = DG(F(\bf{a}))$ 라고 하자. 그리고 다음과 같이 정의한다.

$$
\begin{aligned}
\bf{\varphi} (\bf{x}) &:= F(\bf{x}) - F(\bf{a}) - L(\bf{x}-\bf{a}),\\[0.3em]
\bf{\psi} (\bf{y}) &:= G(\bf{y})- G(\bf{b})-T(\bf{y}-\bf{b}), \\[0.3em]
\bf{\rho}(\bf{x}) &: = G\circ F(\bf{x})- G \circ F(\bf{a}) - (T\circ L) (\bf{x}-\bf{a}).
\end{aligned}
$$ {#eq-thm_part3_chainrule_1}

미분가능성의 정의로부터

$$
\lim_{\bf{x}\to\bf{a}}\dfrac{\|\bf{\varphi}(\bf{x})\|}{\|\bf{x}-\bf{a}\|} = 0, \qquad \lim_{\bf{y}\to\bf{b}}\dfrac{\|\bf{\psi}(\bf{y})\|}{\|\bf{y}-\bf{b}\|} = 0
$$ {#eq-thm_part3_chainrule_2}


이다. 우리는 이제 다음을 보이면 된다.

$$
\lim_{\bf{x}\to\bf{a}}\dfrac{\|\bf{\rho}(\bf{x})\|}{\|\bf{x}-\bf{a}\|} = 0.
$$ {#eq-thm_part3_chainrule_3}

그렇다면

$$
\begin{aligned}
\bf{\rho}(\bf{x}) &= G(F(\bf{x})) -  G(\bf{b}) - (T \circ L)(\bf{x}-\bf{a})\\[0.3em]
& = G(F(\bf{x})) - G(\bf{b}) - T(F(\bf{x}) - F(\bf{a})- \bf{\varphi}(\bf{x})) \\[0.3em]
&= \left[G(F(\bf{x})) - G(\bf{b}) -T(F(\bf{x})-F(\bf{a}))\right] + T(\bf{\varphi}(\bf{x})) \\[0.3em]
&=\bf{\psi}(F(\bf{x})) + T(\bf{\varphi}(\bf{x}))
\end{aligned}
$$ {#eq-thm_part3_chainrule_4}

이다. 우선 $\displaystyle \lim_{\bf{x}\to \bf{a}} \dfrac{\|T(\bf{\varphi}(\bf{x}))\|}{\|\bf{x}-\bf{a}\|}=0$ 임을 보이자. @exr-CM_spivak_1_10 으로부터 어떤 $M_T>0$ 에 대해

$$
\dfrac{\|T(\bf{\varphi}(\bf{x}))\|}{\|\bf{x}-\bf{a}\|}\le \dfrac{M_T\|\bf{\varphi}(\bf{x})\|}{\|\bf{x}-\bf{a}\|}
$$ {#eq-thm_part3_chainrule_5}

이며 @eq-thm_part3_chainrule_2 의 첫번째 극한으로부터 다음을 알 수 있다.

$$
\displaystyle \lim_{\bf{x}\to \bf{a}} \dfrac{\|T(\bf{\varphi}(\bf{x}))\|}{\|\bf{x}-\bf{a}\|}=0
$$ {#eq-thm_part3_chainrule_6}

또한 @eq-thm_part3_chainrule_2 의 두번째 극한으로부터 임의의 $\varepsilon>0$ 에 대해 다음을 만족하는 $\delta>0$ 이 존재한다는 것을 안다.

$$
\|F(\bf{x})-\bf{b}\|<\delta \implies \|\bf{\psi}(F(\bf{x}))\| < \varepsilon \|F(\bf{x})-\bf{b}\|
$$

그렇다면 @eq-thm_part3_chainrule_1 로부터

$$
\begin{aligned}
\varepsilon \|F(\bf{x})-\bf{b}\| &= \varepsilon \| \bf{\varphi}(\bf{x}) + L(\bf{x}-\bf{a})\| \\[0.3em]
& \le \varepsilon \|\bf{\varphi}(\bf{x})\| + \varepsilon\|L(\bf{x}-\bf{a})\|
\end{aligned}
$$

이며 역시  @exr-CM_spivak_1_10 로부터 어떤 $M_L>0$ 가 존재하여 $\|L(\bf{x}-\bf{a})\| \le M_L \|\bf{x}-\bf{a}\|$ 임을 안다. 이 결과와 @eq-thm_part3_chainrule_2 의 첫번째 식을 이용하면 어떤 $\eta>0$ 에 대해

$$
\|\bf{x}-\bf{a}\|<\eta \implies \|\bf{\varphi}(\bf{x})\| <\|\bf{x}-\bf{a}\|
$$

이므로 임의의 $\varepsilon>0$ 에 대해 어떤 $\eta>0$ 이 존재하여 

$$
\|\bf{x}-\bf{a}\|<\eta \implies \|\bf{\psi}(F(\bf{x}))\| \le \varepsilon(M_L+1) \|\bf{x}-\bf{a}\|
$$

이다. 임의의 $\varepsilon>0$ 에 대해 성립하므로 

$$
\lim_{\bf{x}\to \bf{a}}\dfrac{\|\bf{\psi}(F(\bf{x}))\|}{\|\bf{x}-\bf{a}\|} = 0
$${#eq-thm_part3_chainrule_7}


이다. 따라서 @eq-thm_part3_chainrule_4 로 부터

$$
\lim_{\bf{x}\to \bf{a}} \dfrac{\|\bf{\rho}(\bf{x})\|}{\|\bf{x}-\bf{a}\|} =0
$$

이므로 $(G\circ F)'(\bf{a}) = T\circ L= DG(F(\bf{a})) \circ DF(\bf{a})$ 이다. $\square$
:::

</br>

### 다변수 함수 미분의 기본 성질 {#sec-CM_basic_properties_of_derivative_of_multivariable_functions}

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_basic_properties_of_derivative_of_multivariable_functions}

$F:\R^n \to \R^m$, $F(\bf{x}) = \begin{bmatrix}f_1(\bf{x}) &\cdots & f_m(\bf{x})\end{bmatrix}^T$ 이라고 하자.

($1$) $F$ 가 상수함수이면 모든 $\bf{x}\in \R^n$ 에 대해 $DF(\bf{x}) = \bf{0}$ 이다.

($2$) $F$ 가 선형사상이면 $F'(\bf{a})= F$ 이다. 

($3$) $F$ 가 $\bf{a}$ 에서 미분 가능한 필요충분조건은 각각의 $f_i$ 가 $\bf{a}$ 에서 미분가능한 것이며 

$$
F'(\bf{a}) = \begin{bmatrix} f_1'(\bf{a}) & \cdots &f_m'(\bf{a})\end{bmatrix}^T
$$

이다. 따라서 $F'(\bf{a})\in \mathcal{M}_{m \times n}(\R)$ 이며 $i$ 번째 열은 $(f_i)'(\bf{a})$ 이다.

($4$) $s:\R^2 \to \R$ 이 $s(x,\,y) = x+y$ 이면 $Ds(a,\,b)= s$ 이다.

($5$) $p:\R^2 \to \R$ 이 $p(x,\,y) = x \cdot y$ 이면 $Dp(a,\,b) (x,\,y) = bx+ay$ 이다. 따라서 $p'(a,\,b)= (b,\,a)$ 이다. 


:::

</div></br>

::: {.proof}

($1$) $F$ 가 상수함수이면 $\|F(\bf{x}+\bf{h})- F(\bf{x})\|=0$ 이다. 

($2$) $F$ 가 선형사상이면 $\|F(\bf{x}+\bf{h})- F(\bf{x})- F(\bf{h})\| = 0$ 이다. 

($3$) 우선 $f_i'(\bf{a})$ 는 $1 \times n$ 행렬, 즉 열행렬임을 안다. $1 \times n$ 열행렬 $\bf{a}_1,\ldots,\, \bf{a}_m$ 에 대해 

$$
\begin{bmatrix} \bf{a}_1 \\ \vdots \\ \bf{a}_m \end{bmatrix} = \begin{bmatrix} (\bf{a}_1)_1 & \cdots & (\bf{a}_1)_n \\ \vdots & & \vdots \\ (\bf{a}_m)_1 & \cdots & (\bf{a}_m)_n\end{bmatrix}
$$ 

이라고 하자. 


이제 각각의 $f_i$ 가 $\bf{a}$ 에서 미분가능하며 $T=\begin{bmatrix} f_1'(\bf{a}) \\ \vdots \\ f_m'(\bf{a})\end{bmatrix}$ 라고 하자. 

$$
\begin{aligned}
\dfrac{\|F(\bf{a}+\bf{h})-F(\bf{a})-T(\bf{h})\|}{\|\bf{h}\|}  \le \sum_{i=1}^m \dfrac{|f_i(\bf{a}+\bf{h}) - f_i(\bf{a})- f_i'(\bf{a})(\bf{h})|}{\|\bf{h}\|}
\end{aligned}
$$

이며 $\bf{h}\to \bf{0}$ 극한에서 우변이 $0$ 이므로 좌변도 $0$ 이다. 즉 $DF(\bf{a}) = T$ 이다. 

이제 $F$ 가 $\bf{a}$ 에서 미분가능하다고 하자. 사영함수(@def-CM_projection_function) $\pi_i$ 에 대해 @exr-CM_differentiability_of_identity_function 에서 미분가능함을 보였다. @thm-CM_chain_rule 에 의해 $\pi_i \circ F$ 도 $\bf{a}$ 에서 미분가능하다. 

($4$) $s$ 가 선형사상이므로 ($2$) 에 의해 성립한다.

($5$) $T(x,\,y) = bx+ay$ 라고 하자. $|p(a+h,\,b+k) - p(a,\,b) - T(h,\,k)| = hk$ 이므로 

$$
\lim_{(h,\,k) \to \bf{0}}\dfrac{|p(a+h,\,b+k) - p(a,\,b) - T(h,\,k)|}{\sqrt{|h|^2+|k|^2}} = \lim_{(h,\,k) \to \bf{0}}\dfrac{|hk|}{\sqrt{h^2+k^2}} 
$$

이다. 우리는 $|h|^2+|k|^2 \le 2|hk|$ 임을 안다. 따라서 위의 극한은 $0$ 이므로 $Dp(a,\,b)(x,\,y) = bx+ay$ 이다. 

:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-CM_basic_properties_of_derivative_of_multivariable_functions}

$f,\,g :\R^n \to \R$ 이 $\bf{a}$ 에서 미분가능하다면 다음이 성립한다. 

$$
\begin{aligned}
D(f+g)(\bf{a})  &= Df(\bf{a}) + Dg(\bf{a}), \\[0.3em]
D(f\cdot g)(\bf{a}) &= g(\bf{a}) Df(\bf{a}) + f(\bf{a}) Dg(\bf{a}).
\end{aligned}
$$ {#eq-cor_part3_basic_properties_of_derivative_of_multivariable_functions_1}

또한 $g(\bf{a})\ne 0$ 이면 다음이 성립한다.

$$
D(f/g)(\bf{a}) = \dfrac{g(\bf{a})Df(\bf{a}) - f(\bf{a})Dg(\bf{a})}{[g(\bf{a})]^2}
$$ {#eq-cor_part3_basic_properties_of_derivative_of_multivariable_functions_2}

:::

</div></br>

::: {.proof}

@thm-CM_basic_properties_of_derivative_of_multivariable_functions ($4$) 의 $s(x,\,y)=x+y$ 를 이용한다. $f+g = s\circ (f,\,g)$ 이므로

$$
\begin{aligned}
D(f+g)(\bf{a}) &= Ds(f(\bf{a}),\, g(\bf{a})) \circ D(f,\,g)(\bf{a}) \\[0.3em]
&= s \circ (D(f,\,g)(\bf{a}) ) = D(f)(\bf{a}) + D(g)(\bf{a})
\end{aligned}
$$

이다. 

@thm-CM_basic_properties_of_derivative_of_multivariable_functions ($5$) 의 $p(x,\,y) = x\cdot y$ 를 이용한다. $f\cdot g = p\circ(f,\,g)$ 이므로

$$
\begin{aligned}
D(f \cdot g)(\bf{a}) &= Dp(f(\bf{a}),\, g(\bf{a}))\circ D(f,\, g)(\bf{a})\\[0.3em]
&= g(\bf{a})Df(\bf{a}) + f(\bf{a})Dg(\bf{a})
\end{aligned}
$$

이다. 

이제 @eq-cor_part3_basic_properties_of_derivative_of_multivariable_functions_2 를 보이기 위해 $g(\bf{a})\ne 0$ 이며 $\bf{a}$ 에서 미분가능할 때 $D(1/g)(\bf{a})$ 를 구해보자. $h(x) = 1/g(x)$ 라고 하면 $g\cdot h = 1$ 이며 $D1(\bf{x})=0$ 이므로

$$
0 = g(\bf{a})Dh(\bf{a}) + h(\bf{a})Dg(\bf{a})
$$

이며 따라서 

$$
D(1/g)(\bf{a})= - \dfrac{Dg(\bf{a})}{[g(\bf{a})]^2}
$$

이다. $f/g= f\cdot h$ 이므로

$$
\begin{aligned}
D(f/g)(\bf{a}) &= D(f\cdot h)(\bf{a}) = \dfrac{Df(\bf{a})}{g(\bf{a})} - \dfrac{f(\bf{a}) Dg(\bf{a})}{[g(\bf{a})]^2} \\[0.3em]
&= \dfrac{g(\bf{a})Df(\bf{a})-f(\bf{a})Dg(\bf{a}) }{[g(\bf{a})]^2}
\end{aligned}
$$

이다. 

:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_10}
#### Spivak 2_10

다음 함수에 대해 $f'$ 을 구하라.

&emsp;($a$) $f(x,\,y,\,z) = x^y$.

&emsp;($b$) $f(x,\,y,\,z) = (x^y,\,z)$.

&emsp;($c$) $f(x,\,y) = \sin (x \sin y)$.

&emsp;($d$) $f(x,\,y,\,z) = \sin (x \sin (y \sin z))$.

&emsp;($e$) $f(x,\,y,\,z) = x^{y^z}$.

&emsp;($f$) $f(x,\,y,\,z) =  x^{y+z}$.

&emsp;($g$) $f(x,\,y,\,z) = (x+y)^z$.

&emsp;($h$) $f(x,\,y) = \sin (xy)$.

&emsp;($i$) $f(x,\,y) = [\sin (xy)]^8$.

&emsp;($j$) $f(x,\,y) = (\sin (xy),\, \sin(x \sin y),\, x^t)$.

:::

</div></br>

::: {.solution}

($a$) $x^y = e^{y\ln (x)}$ 임을 안다. $\bf{x} = (x,\,y,\,z) \in R^3$ 에 대해 $f(\bf{x}) = e^{\pi_2 (\bf{x}) \ln(\pi_1(\bf{x}))}$ 이다. $g:\R \to \R$ 을 $g(t) := e^t$, $h:\R^3 \to \R$ 을 $h(\bf{x}) := \pi_2 \cdot \ln (\pi_1)$ 이라고 하면 $f = g \circ h$ 이다. $g'(t) = g(t)$ 임을 안다. 또한 $\pi_i'=\pi_i$ 이며 $(\ln x)'=1/x$ 이므로

$$
\begin{aligned}
Dh(\bf{x}) &= \begin{bmatrix}0 & 1 & 0\end{bmatrix} \ln (\pi_1(\bf{x})) + \begin{bmatrix} 1 & 0 & 0 \end{bmatrix}\dfrac{\pi_2(\bf{x})}{\pi_1(\bf{x})} \\
&= \begin{bmatrix} \dfrac{y}{x} & \ln x & 0\end{bmatrix}
\end{aligned}
$$

이다. 이로부터 $f'(x,\,y,\,z)$ 가 아래와 같음을 안다.

$$
\begin{aligned}
f'(x,\,y,\,z) &= g'(h(\bf{x})) \cdot h'(\bf{x}) = x^y \begin{bmatrix} \dfrac{y}{x} & \ln x & 0\end{bmatrix} \\[0.3em]
&= \begin{bmatrix} y x^{y-1} & x^y \ln x & 0\end{bmatrix}.
\end{aligned}
$$

($b$) $F(\bf{x}) = (h(\bf{x}),\, \pi_3(\bf{x})) = \begin{bmatrix} h(\bf{x}) \\ \pi_3(\bf{x})\end{bmatrix}$, 이며 $h$ 는 ($a$) 의 $f$ 이다. 이로부터

$$
DF = \begin{bmatrix}  y x^{y-1} & x^y \ln x & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

이다. 

($c$) $f(\bf{x}) = \sin (\pi_1(\bf{x}) \cdot \sin (\pi_2(\bf{x})))$ 이다. $g(x) = \sin (x)$, $h(\bf{x}) = \pi_1(\bf{x})\cdot \sin (\pi_2(\bf{x}))$ 라고 하면, $f= g\circ h$ 이다. $g'(x) = \cos (x)$ 이며, 

$$
\begin{aligned}
h'(\bf{x}) &= \bf{e}_1^T \sin (\pi_2(\bf{x})) + \pi_1(\bf{x})\bf{e}_2^T \cos (\pi_2(\bf{x})) \\[0.3em]
&= \begin{bmatrix} \sin y & x \cos y & 0 \end{bmatrix} 
\end{aligned}
$$

이다. 따라서

$$
f'(x,\,y,\,z) = \cos(x\sin y) \begin{bmatrix} \sin y & x \cos y & 0\end{bmatrix}
$$

이다. 

($d$) ($c$) 와 유사한 방법으로 구할 수 있다.

$$
f'(x,\,y,\,z) = \cos (x \sin (y \sin z))\begin{bmatrix} \sin(y \sin z) & x\sin z \cos (y \sin z) & xy \cos z \cos (y \sin z) \end{bmatrix}
$$

</br>
$\vdots$
</br>


:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_11}
#### Spivak 2_11

$g:\R \to \R$ 이 연속일 대 다음 함수 $f$ 에 대해 $f'$ 을 구하라.

&emsp;($1$) $\displaystyle f(x,\,y) = \int_a^{x+y} g$.

&emsp;($2$) $\displaystyle f(x,\,y) = \int_{a}^{x\cdot y} g$.

&emsp;($3$) $\displaystyle f(x,\,y,\,z) = \int_{x^y}^{\sin (x \sin (y \sin z))} g$.
:::

</div></br>

::: {.solution}
$G(t) = \int_0^t g$ 인 $G:\R \to R$ 이 존재한다. 이 때 $G' = g$ 이다.

($a$) $f(x,\,y) = G(x+y)- G(a)$ 이므로 

$$
f'(x,\,y) = G'(x+y)\begin{bmatrix} 1 & 1 \end{bmatrix} = \begin{bmatrix} g(x+y) & g(x+y)\end{bmatrix}.
$$ 

($b$) $f(x,\,y) = G(x \cdot y) - G(a)$ 이므로

$$
f'(x,\,y)= G'(x \cdot y) \begin{bmatrix} y & x\end{bmatrix} = \begin{bmatrix} y\cdot g(xy) & x \cdot g(xy)\end{bmatrix}
$$

($c$) @exr-CM_spivak_2_10 ($d$) 를 이용한다. $f(x,\,y,\,z) = G(\sin (x \sin (y \sin z))) - G(xy)$ 이므로 

$$
f'(x,\,y,\,z) = ...
$$

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_12}
#### Spivak 2_12

$F:\R^n \times \R^m \to \R^p$ 가 $\bf{x},\, \bf{x}_1,\,\bf{x}_2\in \R^n$, $\bf{y},\,\bf{y}_1,\,\bf{y}_2\in \R^m$, $a\in \R$ 에 대해 다음을 만족하면 $f$ 를 **쌍선형(bilinear)** 이라고 한다.

$$
\begin{aligned}
F(a\bf{x},\, \bf{y}) &= aF(\bf{x},\, \bf{y}) = F(\bf{x},\, a\bf{y}),\\[0.3em]
F(\bf{x}_1 + \bf{x}_2,\, \bf{y}) &= F(\bf{x}_1,\, \bf{y}) + F(\bf{x}_2,\, \bf{y}),\\[0.3em]
F(\bf{x},\, \bf{y}_1+\bf{y}_2) &= F(\bf{x},\, \bf{y}_1) + F(\bf{x},\, \bf{y}_2).
\end{aligned}
$$ {#eq-CM_spivak_2_12_1}

($a$) $F$ 가 쌍선형이면 다음이 성립함을 보여라.

$$
\lim_{(\bf{h},\,\bf{k}) \to \bf{0}} \dfrac{\|F(\bf{h},\,\bf{k})\|}{\|(\bf{h},\,\bf{k})\|} = 0.
$$

($b$) $DF(\bf{a},\,\bf{b})(\bf{x},\,\bf{y}) = F(\bf{a},\,\bf{y}) + F(\bf{x},\, \bf{b})$ 임을 보여라.

($c$) @thm-CM_basic_properties_of_derivative_of_multivariable_functions ($5$) 의 $Dp(a,\,b)$ 는 ($b$) 의 특별한 형태임을 보여라.

:::

</div></br>

::: {.solution}

여기서는 쌍선형 형식에 대해 다음을 증명하자.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_bilinear_1}

$F:\R^n \times \R^m \to \R^p$ 가 쌍선형 형식일 대 다음이 성립한다.

&emsp;($1$) $F(\bf{0},\,\bf{0}) = \bf{0}$ 이다.

&emsp;($2$) 어떤 $M>0$ 이 존재하여 $\|F(\bf{x},\,\bf{y})\| \le M\|(\bf{x},\,\bf{y})\|^2$ 이다.
:::

</div></br>

::: {.proof}

($1$) @eq-CM_spivak_2_12_1 의 첫번째 식으로부터  $F(-\bf{x},\,\bf{y}) = - F(\bf{x},\, \bf{y})= F(\bf{x},\, -\bf{y})$ 임을 안다. 이를 이용하면 $F(\bf{0},\, \bf{y})= F(\bf{x},\, \bf{0})= \bf{0}$ 임을 안다. 

($2$) $\R^n,\, \R^m$ 에서의 표준기저를 각각 $(\bf{e}_i),\, (\bf{t}_j)$ 라고 하자. $\bf{x} = \sum_i x_i \bf{e}_i$, $\bf{y}= \sum_j y_j \bf{t}_j$ 라고 하면 

$$
\begin{aligned}
F(\bf{x},\,\bf{y}) = \sum_{i, j} x_i y_j F(\bf{e}_i,\, \bf{t}_j)
\end{aligned}
$$

임을 안다. $M_{ij} = \|F(\bf{e}_i,\, \bf{t}_j)\|$, 이며 $M_0=\max \{M_{ij}\}$ 라고 하자. 또한 

$$
|x_iy_j| \le \|\bf{x}\||y_j| \le \|\bf{x}\|\cdot \|\bf{y}\| \le  \|\bf{x}\|^2+\|\bf{y}\|^2 = \|(\bf{x},\, \bf{y})\|^2
$$ 

이므로 
$$
\|F(\bf{x},\,\bf{y})\| = \sum_{i, j} |x_i y_j| M_{ij} \le \sum_{i, j}|x_iy_j|M \le mn\|(\bf{x},\, \bf{y})\|^2M_0
$$

이 성립한다. $M=mnM_0$ 라고 놓으면 ($2$) 가 성립함을 안다. $\square$

:::

</br>

이제 ($2$) 로부터

$$
\lim_{(\bf{h},\, \bf{k}) \to \bf{0}} \dfrac{\|F(\bf{h},\, \bf{k})\|}{\|(\bf{h},\, \bf{k})\|} \le \lim_{(\bf{h},\, \bf{k})\to \bf{0}}M\|(\bf{h},\, \bf{k})\| = 0
$$

이므로 ($a$) 가 증명되었다.

($b$) 쌍선형 형식의 정의로부터 

$$
\begin{aligned}
F(\bf{x}+\bf{h},\bf{y}+\bf{k}) &- F(\bf{x},\, \bf{y}) - F(\bf{x},\, \bf{k}) - F(\bf{h},\, \bf{y}) = F(\bf{h},\, \bf{k})
\end{aligned}
$$

이므로

$$
\lim_{(\bf{h},\bf{k})\to \bf{0}}\dfrac{\|F(\bf{x}+\bf{h},\bf{y}+\bf{k}) - F(\bf{x},\, \bf{y}) - F(\bf{x},\, \bf{k}) - F(\bf{h},\, \bf{y})\|}{\|(\bf{h},\, \bf{k})\|} = 0
$$

이다. 미분의 정의에 의해 $DF(\bf{x},\,\bf{y}) (\bf{h,\, \bf{k}})= F(\bf{x},\, \bf{k}) + F(\bf{h},\, \bf{y})$ 이다.

($c$) $f(x,\,y) =xy$ 는 쌍선형 형식이다. ($b$) 를 적용하라.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_13}
#### Spivak 2_13

$IP:\R^n \times \R^n \to \R$ 을 $IP(\bf{x},\, \bf{y}) := \langle \bf{x},\,\bf{y}\rangle = \bf{x}^T \bf{y}$ 로 정의한다.

($a$) $D(IP)(\bf{a},\,\bf{b})$ 와 $(IP)'(\bf{a},\,\bf{b})$ 를 구하라

($b$) $F,\,G : \R \to \R^n$ 이 미분가능하고 $h:\R \to \R$ 이 $h(t) = \langle F(t),\, G(t)\rangle$ 로 정의되었을 때 다음이 성립함을 보여라.

$$
h'(\bf{a}) = \langle F'(a)^T,\, G(a)\rangle + \langle F(a),\, G'(\bf{a})^T\rangle.
$$

($c$) $F:\R \to \R^n$ 이 미분가능하고 모든 $t\in \R$ 에 대해 $\|F\|=1$ 이면 $\langle F'(t),\, F(t)\rangle = 0$ 임을 보여라.

:::

</div></br>

::: {.solution}

($a$) $IP$ 는 쌍선형 형식이다. 따라서 $D(IP)(\bf{a},\,\bf{b})(\bf{x},\,\bf{y}) = \langle \bf{a},\, \bf{y}\rangle + \langle \bf{x},\, \bf{b}\rangle$ 이다. $(IP)'(\bf{a},\, \bf{b}) = \begin{bmatrix} \bf{b}^T & \bf{a}^T\end{bmatrix}$ 이다.

($b$) $h(t) = \langle F(t),\, G(t) \rangle = \displaystyle \sum_{i=1}^n f_i (t) g_i (t)$ 이므로

$$
h'(t) = \sum_{i=1}^n f'_i(t)g_i(t) + f_i(t) g'_i(t) = \langle F'(t),\, \bf{g}(t)\rangle + \langle F(t),\, \bf{g}'(t)\rangle.
$$


($c$) $g:\R \to \R$ 을 $g(t) = \langle F(t),\, F(t)\rangle$ 로 정의하면 $g=1$ 이므로

$$
0 = g'(t) = 2 \langle F'(t),\, F(t) \rangle
$$

이다.

:::


</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_14}
#### Spivak 2_14

$i=1,\ldots,\,k$ 에 대해 $E_i$ 는 각각의 차원을 가진 유클리드 공간이다. $F:E_1 \times \cdots \times E_k \to \R^p$ 이다. 각각의 $x_j \in E_j,\, j \ne i$ 에 대해 아래와 같은 $G:\R \to \R^p$ 가 선형함수라면 $F$ 를 다중선형함수라고 한다.
$$
G(x) = F(x_1,\ldots,\,x_{i-1},\,x,\, x_{i+1},\ldots,\,x_k)
$$

($a$) $F$ 가 다중선형함수이고 $i\ne j$ 일 때 $\bf{h} = (h_1,\ldots,\,h_k),\, h_l \in E_l$ 에 대해

$$
\lim_{\bf{h} \to 0} \dfrac{\|F(a_1,\ldots,\,h_i,\ldots,\, h_j,\ldots,\,a_k)\|}{\|\bf{h}\|} = 0
$$

임을 보여라.

($b$) 다음이 성립함을 보여라.

$$
\begin{aligned}
DF(a_1,\ldots,\,a_k)&(x_1,\ldots,\,x_k) = \sum_{i=1}^k F(a_1,\ldots,\,a_{i-1},\, x_i,\,a_{i+1},\ldots,\,a_k)
\end{aligned}
$$

:::

</div></br>

::: {.solution}

($a$) 정해진 $i,\,j,\, i\ne j$ 에 대해 

$$
G_{ij}(x,\,y) = F(x_1,\ldots,\,x_{i-1},\,x,\,x_{i+1},\ldots,\,x_{j-1},\,y,\, x_{j+1},\ldots,\,x_k)
$$ 

는 쌍선형 함수이다. 따라서 @exr-CM_spivak_2_12 ($a$) 에 의해 ($a$) 가 성립한다.

($b$) $n$ 선형 형식에 대해 다음 명제를 증명한다.


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_multilinear_1}

유클리드 공간 $E_1,\ldots,\,E_n$ 에 대해 $F:E_1 \times \cdots \times E_n \to \R^p$ 가 $n$-선형 형식일 때 다음이 성립한다.

&emsp;($1$) $F(0,\ldots,0) = \bf{0}$ 이다.

&emsp;($2$) 어떤 $M>0$ 이 존재하여 $\|F(x_1,\ldots,\,x_n)\| \le M\|(x_1,\ldots,\,x_n)\|^n$ 이다.
:::

</div></br>

::: {.proof}

($1$) 은 @prp-CM_bilinear_1 과 같은 방법으로 쉽게 증명 할 수 있다.  

($2$) $E_i$ 의 차원이 $d_i$ 라고 하고 $\left(\bf{e}^{(i)}_j\right)$ 가 $E_i$ 의 표준기저라고 하자. $x_i = \sum_{j_i} c_{j_i}^{(i)}\bf{e}_{j_i}^{(i)}$ 라고 하면 

$$
\begin{aligned}
\|F(x_1,\ldots,\,x_n)\| &= \left\|F\left(\sum_{j_1} c^{(1)}_{j_1} \bf{e}^{(1)}_{j_1}, \ldots,\, \sum_{j_n} c^{(n)}_{j_n} \bf{e}^{(n)}_{j_n}\right) \right\| \\[0.3em]
&= \sum_{j_1,\ldots,\,j_n} \left|c^{(1)}_{j_1} \cdots c^{(n)}_{j_n}\right| F\left(\bf{e}^{(1)}_{j_1},\ldots,\, \bf{e}^{(n)}_{j_n}\right)\\[0.3em]
& \le \sum_{j_1,\ldots,\,j_n} \|\bf{x}_1\|\cdots \|\bf{x}_n\| F\left(\bf{e}^{(1)}_{j_1},\ldots,\, \bf{e}^{(n)}_{j_n}\right)\\[0.3em]
\end{aligned}
$$

$M_0 = \max \left\{\left\| F\left(\bf{e}^{(1)}_{j_1},\ldots,\, \bf{e}^{(n)}_{j_n}\right)\right\|\right\}$ 라고 하자. 또한

$$
\|\bf{x}_1\|\cdots \|\bf{x}_n\| \le \|\bf{x}_1\|^n + \cdots + \|\bf{x}_1\|^n \le (\|\bf{x}_1\|^2 + \cdots + \|\bf{x}_n\|^2)^{n/2} = \|(\bf{x}_1,\ldots,\,\bf{x}_n)\|^{n}
$$

이므로 

$$
\|F(x_1,\ldots,\,x_n)\| \le d_1 \cdots d_n M_0 \|(\bf{x}_1,\ldots,\,\bf{x}_n)\|^n
$$

이다. 즉 $M=d_1 \cdots d_n M_0 \|(\bf{x}_1,\ldots,\,\bf{x}_n)$ 로 잡으면 ($2$) 이다. $\square$

:::


문제로 돌아와서 Multilinear 의 정의에 의해

$$
\begin{aligned}
&F(a_1+h_1,\ldots, a_k +h_k) - F(a_1,\ldots,\,a_k) \\[0.3em]
&\quad = F(a_1,\,a_2+h_2,\ldots,\,a_k+h_k) + F(h_1,\,a_2+h_2,\ldots,\,a_k+h_k ) - F(a_1,\ldots,\,a_k)\\[0.3em]
&\quad = F(a_1,\,a_2,\,a_3+h_3,\ldots,a_k+h_k) + F(a_1,\,h_2,\,a_3+h_3,\ldots,,a_k+h_k) \\[0.3em]
&\qquad\qquad \qquad + F(h_1,a_2,\,a_3+h_3,\ldots,\,a_k+h_k) + F(h_1,\,h_2,\,a_3+h_3,\ldots,\,a_k+h_k) \\[0.3em]
&\qquad\qquad\qquad - F(a_1,\ldots,\,a_k)
\end{aligned}
$$

이며 이것을 계속 반복하다보면 $F$ 의 인자로 주어지는 $k$ 개의 coordinate index 가운데 $\bf{h}$ 의 성분이 1개 있는 것부터 $k$ 개 있는 것까지의 합이 된다. 

이제 주어진 $\displaystyle DF(a_1,\ldots,\,a_k)(h_1,\,\ldots,\,h_k) = \sum_{i=1}^k F(a_1,\ldots,\,a_{i-1},\, h_i,\,a_{i+1},\ldots,\,a_k)$ 의 우변은 $F(a_1,\ldots,\,a_k)$ 의 $k$ 개의 인자 $a_1,\ldots,\,a_k$ 가운데 하나만 $\bf{h}$ 의 해당 성분으로 바꾼 것이다. 그렇다면

$$
\lim_{\bf{h}\to \bf{0}}\dfrac{\displaystyle \left\|F(a_1+h_1,\ldots,\,a_k+h+k) - F(a_1,\ldots,\, a_k) - \sum_{i=1}^n F(a_1,\ldots,\,a_{i-1},h_i,a_{i+1},\ldots,a_k)\right\|}{\|\bf{h}\|}
$$

를 생각해보자. 분자의 $\| \cdots \|$ 안에는 $F$ 의 인자 $a_1,\ldots,\,a_k$ 가운데 두개 이상을 $\bf{h}$ 의 해당 성분으로 바꾼 것만 남는다. 이제 우리가 증명한 @prp-CM_multilinear_1 에 의해 위의 극한이 $0$ 이 됨을 알 수 있다. 

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_15}
#### Spivak 2_15

$n\times n$ 행렬은 $n$ 개의 $\R^n$ 의 데카르트곱 $\R^n \times \cdots \times R^n$ 의 한 점으로 간주 할 수 있다. 이 때 행렬의 각 행은 $\R^n$ 의 원소이다.

($a$) $\det:\R^n \times \cdots \times \R^n \to \R$ 이 미분가능이며

$$
D(\det) (a_1,\ldots,\,a_n) (x_1,\ldots,\,x_n) = \sum_{i=1}^n \det \begin{bmatrix} a_1 \\ \vdots  \\ x_i  \\ \vdots  \\ a_n\end{bmatrix}
$$

임을 보여라.

($b$) $a_{ij}: \R \to \R$ 이 미분가능하며 $f(t) = \det (a_{ij}(t))$ 라면 다음이 성립함을 보여라.

$$
f'(t) = \sum_{j=1}^n \det \begin{bmatrix} a_{11}(t) & \cdots & a_{1n}(t) \\ \vdots & & \vdots \\ a_{j1}'(t) & \cdots & a_{jn}'(t) \\ \vdots & & \vdots \\ a_{n1}(t) & \cdots & a_{nn}(t) \end{bmatrix}
$$

($c$) 모든 $t$ 에 대해 $\det (a_{ij}(t)) \ne 0$ 이며 $b_1,\ldots,\,b_n : \R\to \R$ 이 미분가능할 때 $s_1,\ldots,s_n :\R\to \R$ 을 다음 방정식의 해라고 하자.

$$
\sum_{j=1}^n a_{ji}(t) s_j(t) = b_i(t), \qquad i=1,\ldots,\,n.
$$

이 때 $s_i$ 는 미분가능함을 보이고 $s_i'(t)$ 를 구하라.

:::

</div></br>

::: {.solution}

($a$) 우리는 $n \times n$ 행렬의 행렬식이 $n$-선형 형식임을 안다. 따라서 @exr-CM_spivak_2_14 ($b$) 에 의해 주어진 식이 성립함을 안다.

($b$) $f'(t) = D(\det)(a_{ij}(t))(a'_{ij}(t))$ 이므로 식시 성립한다.

($c$) $[a_{ij}(t)]=\bf{A}(t)$, $[s_j(t)]=\bf{s}(t)$, $[b_i(t)]=\bf{b}(t)$ 라고 하면 주어진 방정식은 $\bf{sA}=\bf{b}$ 이다. $\det(\bf{A})\ne 0$ 이므로 역행렬이 존재하므로 방정식의 해 $\bf{s}$ 가 존재한다. $\bf{sA}=\bf{b}$ 의 양변을 미분하면

$$
\bf{s}'\bf{A}+ \bf{s}\bf{A}' = \bf{b}'
$$

이므로 

$$
\bf{s}' = (\bf{b}'-\bf{sA}')\bf{A}^{-1}
$$

이다. 

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_16}
#### Spivak 2_16

$F:\R^n \to \R^n$ 이 미분가능하며 미분가능한 역함수 $F^{-1}:\R^n \to \R^n$ 이 존재한다고 하자. 다음이 성립함을 보여라.

$$
(F^{-1})'(\bf{a}) = \left[F'\left(F^{-1}(\bf{a})\right)\right]^{-1}
$$

:::

</div></br>

::: {.solution}

$F\circ F^{-1} = \bf{\pi}$ 이며 양변을 미분하면 $F'(F^{-1}(\bf{a})) (F^{-1})'(\bf{a}) = \bf{I}_n$ 이므로 주어진 식이 성립한다. 
:::

</br>

## 편미분

### 편미분의 정의

::: {.callout-note appearance="simple" icon="false"}

::: {#def-CM_partial_derivative}

#### 편미분

$f:\R^n \to \R$ 과 $\bf{a}\in \R^n$ 에 대해 아래와 같이 정의된 $D_if(\bf{a})$ 가 존재할 때 이를 $f$ 의 $\bf{a}$ 에서의 $i$ 번째 편미분이라고 한다.

$$
D_i f(\bf{a}) :=\lim_{h \to 0} \dfrac{f(a_1,\ldots,\,a_{i-1}, a_{i}+h,\, a_{i+1},\ldots,\,a_n) - f(a_1,\ldots,\,a_n)}{h}.
$$ {#eq-CM_ith_partial_derivative}


$D_if(\bf{a})$ 를 $\partial_i f(\bf{a})$ 혹은 $\dfrac{\partial f(\bf{a})}{\partial x_i}$ 와 같이 쓰기도 한다. 
::: 
:::

</br>

### 편미분의 기본 성질

만약 $D_i f(\bf{x})$ 가 모든 $\bf{x}\in \R^n$ 에서 존재한다면 $D_i f$ 는 $\R^n \mapsto \R$ 함수이다. 즉 $D_i f$ 에 대한 $j$ 번째 편미분이 존재 할 수 있다. 이를 $D_j (D_i f)(\bf{x})$ 혹은 $D_jD_i f(\bf{x})$ 혹은 $D_{i,j}f$ 라고 쓴다. 물론 $\partial_j \partial_i f(\bf{x})$ 나 $\partial_{i, j}f(\bf{x})$ 라고 쓸 수도 있다. 일반적으로는 아니지만 특수한 경우 $D_iD_j f = D_j D_i f$ 인데 이것이 성립하는 조건은 다음과 같다. 다만 여기에 대한 증명은 잠시 미뤄두기로 하자. 

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_exchange_of_the_order_of_partial_derivative}

$D_jD_i f$ 와 $D_j D_if$ 가 $\bf{a} \in \R^n$ 을 포함하는 어떤 열린 집합에서 연속일 때 $D_jD_if(\bf{a}) = D_jD_if(\bf{a})$ 이다.

:::

</div></br>

$D_iD_jf$ 와 같이 두번 편미분 한 것을 **2 계 편미분(2nd-order partial derivative)** 이라고 한다. 비슷한 방법으로 $n$ 계 편미분을 정의할 수 있다. 우리는 미분가능한 1변수 함수 $f$ 가 $a\in \R$ 에서 극값을 가지면 $f'(a)=0$ 임을 알고 있다. 이와 비슷한 것이 편미분에 대해서도 성립한다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_extrema_and_partial_derivative}

$f : A \subset \R^n \to \R$ 이 $\bf{a}\in \text{int}(A)$ 에서 극값을 갖고 $D_i f$ 가 $A$ 에서 존재한다면 $D_i f(\bf{a})=0$ 이다. 

:::

</div></br>

::: {.proof}

$g_i(x) = f(a_1,\ldots,\,a_{i-1},\,x.,\,a_{i+1},\ldots,\,a_n)$ 이라고 하자. $g_i(x)$ 는 $a_i$ 에서 극값을 가지며 따라서 $g_i'(a_i) = 0$ 이다. 이는 $D_i f(\bf{a})=0$ 과 같다. $\square$

:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_17}
#### Spivak 2_17

다음 함수의 편미분을 구하라.

&emsp;($a$) $f(x,\,y,\,z) = x^y$.

&emsp;($b$) $f(x,\,y,\,z) = z$.

&emsp;($c$) $f(x,\,y) = \sin (x \sin y)$.

&emsp;($d$) $f(x,\,y,\,z) = \sin (x \sin (y \sin z))$.

&emsp;($e$) $f(x,\,y,\,z) = x^{y^z}$.

&emsp;($f$) $f(x,\,y,\,z) = x^{y+z}$.

&emsp;($g$) $f(x,\,y,\,z) = (x+y)^z$.

&emsp;($h$) $f(x,\,y) = \sin (xy)$.

&emsp;($i$) $f(x,\,y) = (\sin (xy))^{\cos 8}$.

:::

</div></br>

::: {.solution}

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_18}
#### Spivak 2_18

$g:\R \to \R$ 이 연속일 때 다음 함수의 편미분을 구하라

&emsp;($a$) $\displaystyle f(x,\,y) = \int_{a}^{x+y} g$.

&emsp;($b$) $\displaystyle f(x,\,y) = \int_y^x g$.

&emsp;($c$) $\displaystyle f(x,\,y) = \int_a^{xy}g$.

&emsp;($d$) $\displaystyle f(x,\,y) = \int_a^{\displaystyle \int_b^y g} g$.

:::

</div></br>

::: {.proof}

$G(t) = \int_0^t g$ 라고 하자. $g$ 가 연속이므로 $G(t)$ 는 항상 존재하며 $G'(t) = g(t)$ 이다.

($a$) $f(x,\,y) = G(x+y)-G(a)$ 이므로, $D_1 f(x,\,y)= D_2 f(x,\,y) =  g(x+y)$ 이다. 

($b$) $f(x,\,y) = G(x)-G(y)$ 이므로 $D_1 f(x,\,y) = g(x)$, $D_2 f(x,\,y)= -g(y)$ 이다.

($c$) $f(x,\,y) = G(xy)- G(a)$ 이므로 $D_1 f(x,\,y)= y g(xy)$, $D_2 f(x,\,y) = xg(xy)$ 이다.

($d$) $f(x,\,y) = G\left(\int_b^y g\right) - G(a)$ 이므로 $D_1f(x,\,y)=0$, $D_2f(x,\,y) = g(y) g\left(\int_b^y g\right)$ 이다. 

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_19}
#### Spivak 2_19

$f(x,\,y) = x^{x^{x^y}} + (\log x) (\arctan (\arctan (\arctan (\sin (\cos xy)- \log (x+y)))))$ 일 때 $D_2 f(1,\,y)$ 를 구하라

:::

</div></br>

::: {.solution}

$g(x,\,y) =  (\arctan (\arctan (\arctan (\sin (\cos xy)- \log (x+y)))))$ 라고 하자.

$$
D_2f(x,\,y)= \log \left(x^{x^x}\right) x^{x^{x^y}} + \log (x) D_2g(x,\,y)
$$

이므로 $D_2 f(1,\,y) = 0$ 이다.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_20}
#### Spivak 2_20

$f$ 의 편미분을 $g$ 와 $h$ 의 미분을 이용하여 구하라.

&emsp;($a$) $f(x,\,y) = g(x)h(y)$.

&emsp;($b$) $f(x,\,y) = g(x)^{h(y)}$.

&emsp;($c$) $f(x,\,y) = g(x)$.

&emsp;($d$) $f(x,\,y) = g(y)$.

&emsp;($e$) $f(x,\,y) = g(x+y)$.
:::

</div></br>

::: {.solution}
($a$) $D_1 f(x,\,y) =  g'(x)h(y)$, $D_2f(x,\,y) = g(x)h'(y)$.

($b$) $D_1 f(x,\,y) = g'(x) g(x)^{h(y)-1}$, $D_2 f(x,\,y) =  h'(y)\log (g(x)) g(x)^{h(y)}$.

($c$) $D_1 f(x,\,y) = g'(x)$, $D_2f(x,\,y)=0$.

($d$) $D_1 f(x,\,y) = 0$, $D_2f(x,\,y)=g'(y)$.

($e$) $D_1 f(x,\,y) = g'(x+y) = D_2 f(x,\,y)$

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_21}
#### Spivak 2_21

$g_1,\,g_2 :\R^2 \to \R$ 이 연속이다. $f:\R^2 \to \R$ 을 다음과 같이 정의한다.

$$
f(x,\,y) = \int_0^x g_1(t,\,0)\, dt + \int_0^y g_2(x,\,t)\, dt.
$$

($a$) $D_2 f(x,\,y) = g_2(x,\,y)$ 임을 보여라.

($b$) $D_1 f(x,\,y)= g_1(x,\,y)$ 가 되려면 $f$ 는 어떻게 정의되어야 하는가?

($c$) $f:\R^2 \to \R$ 이 $D_1f(x,\,y)=x$, $D_2f(x,\,y) = y$ 인 $f:\R^2 \to \R$ 을 찾아라. $D_1f(x,\,y) = y$, $D_2 f(x,\,y)= x$ 인 $f:\R^2 \to \R$ 을 찾아라. 

:::

</div></br>

::: {.solution}

($a$) $G_1(x) := \int_0^x g_1(t,0)\, dt$, $G_2(x,\,y) := \int_0^y g_2(x,\,y)\, dt$  라고 하자. $f(x,\,y)= G_1(x) +G_2(x,\,y)$ 이며 $G_1'(x) = g_1(x,\,0)$, $D_2 G_2(x,\,y) = g_2(x,\,y)$ 이다. 따라서 $D_2 f(x,\,y)= g_2(x,\,y)$ 이다.

($b$) $f(x,\,y) = \int_0^x g_1(t,\,y)\, dt$ 이면 $D_1 f(x,\,y) = g_1(x,\,y)$ 이다.

($c$) $f(x) = \dfrac{1}{2}x^2+ \dfrac{1}{2}y^2 +c$ d이면 $D_1f(x,\,y)=x,\, D_2f(x,\,y)=y$. $f(x,\,y) = xy$ 이면 $D_1f(x,\,y) = y$, $D_2 f(x,\,y)=x$.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_22}
#### Spivak 2_22

$f:\R^2 \to \R$ 이 $D_2f=0$ 일 때 $f$ 는 두번째 변수에 독립임을 보여라. $D_1f = D_2f=0$ 이면 $f$ 는 상수임을 보여라.

:::

</div></br>

::: {.solution}

$D_2 f$ 가 일단 존재하므로 $f$ 는 미분 가능이며 따라서 연속이다. 고정된 $x=x_0$ 에 대해 $g(y) = f(x_0,\,y)$ 라고 하면 $D_2f(x_0,\,y) = g'(y)$ 이며 따라서 $g$ 는 미분가능하다. 중간값 정리에 의해 $g(y_2)-g(y_1) = g'(c)(y_2-y_1)$ 인 $c$ 가 $y_1$ 과 $y_2$ 사이에 있으야 하는데 $g'(c) = 0$ 이므로 $g(y_1) = g(y_2)$ 이다. 즉 $g$ 는 상수함수이며 $f(x,\,y)$ 는 $y$ 값에 무관하게 $x$ 에 의해서만 정해진다. 따라서 $f$ 는 두번째 변수에 대해 독립이다.

$D_1 f = D_2f = 0$ 이라면 $f$ 가 $x,\,y$ 값 모두에 대해 독립이므로 $f$ 는 상수이다.
:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_23}
#### Spivak 2_23

$A=\{(x,\,y) \subset \R^2 : x<0,\text{ or } x\ge 0 \text{ and } y\ne 0\}$ 에 대해 다음을 보여라.

($a$) $f:A \to \R$ 이며 $D_1f = D_2 f = 0$ 이면 $f$ 는 상수이다.

($b$) $f:A\to \R$ 이며 $D_2 f = 0$ 이지만 $f$ 가 두번째 변수에 독립적이지 않은 함수를 찾아라.

:::

</div></br>

::: {.solution}

($a$) $A$ 의 임의의 두 점 $(x_1,\,y_1)$ 과 $(x_2,\,y_2)$ 는 $x$ 축 혹은 $y$ 축과 평행한 선분으로 연결된다. 이 선분을 따라 두 편미분 값이 모두 같으므로 $D_1 f=D_2f=0$ 이면 $f$ 는 상수이다.

($b$) 아래의 함수는 $Df_2 = 0$ 이지만 $y$ 에 의존한다. 

$$
f(x) = \left\{\begin{array}{ll} 0,\qquad & x < 0,\\ x & x\ge 0,\text{ and } y>0 \\ -x & x\ge 0 \text{ and } y < 0 \end{array} \right.
$$
:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_24}
#### Spivak 2_24

$f:\R^2 \to \R$ 이 아래와 같이 정의되었다.

$$
f(x,\,y) = \left\{\begin{array}{ll} xy\dfrac{x^2-y^2}{x^2+y^2},\qquad & (x,\,y) = 0, \\ 0 & (x,\,y) = (0,\,0).\end{array}\right.
$$

($a$) 모든 $x$ 에 대해 $D_2 f(x,\,0) = x$ 이며 모든 $y$ 에 대해 $D_1 f(0,\,y)=-y$ 임을 보여라.

($b$) $D_{1,2}f(0,\,0) \ne  D_{2,\,1}f(0,\,0)$ 임을 보여라.

:::

</div></br>

::: {.solution}

($a$) 

$$
\begin{aligned}
D_2f(x,\,0) &= \lim_{h \to 0}\dfrac{1}{h}\dfrac{xh(x^2-h^2)}{x^2+h^2} = x, \\
D_1f(0,\,y) &= \lim_{k \to 0} \dfrac{1}{k} \dfrac{ky(k^2-y^2)}{k^2+y^2} = -y.
\end{aligned}
$$

($b$) ($a$) 로부터 $D_{1,\,2}f(0,\,0) =  -1$, $D_{2,\,1}f(0,\,0) = 1$ 

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_25}
#### Spivak 2_25

$f:\R \to \R$ 을 아래와 같이 정의한다.

$$
f(x) = \left\{\begin{array}{ll} e^{-x^{-2}},\qquad & x\ne 0, \\ 0 & x = 0\end{array}\right.
$$

$f$ 가 $C^\infty$ 급 함수임을 보이고 모든 $i$ 에 대해 $f^{(i)}(0)= 0$ 임을 보여라.

:::

</div></br>

::: {.solution}

$f'(x) = \dfrac{2}{x^3}e^{-1/x^2}$ 이다. 다항식 $p(x)$ 에 대해

$$
\dfrac{d}{dx}\left[p\left(\dfrac{1}{x}\right) e^{-1/x^2}\right] = - \dfrac{1}{x^2}p'\left(\dfrac{1}{x}\right) e^{-1/x^2} + \dfrac{2}{x^3}\,p\left(\dfrac{1}{x}\right) e^{-1/x^2}
$$

이므로 어떤 다항식 $q(x)$ 에 대해 $q(1/x)e^{-1/x^2}$ 꼴이다. $f'(x)$ 가 이 형태이므로 우리는 $f^{(i)}$ 가 $p(1/x)e^{-1/x^2}$ 꼴임을 알 수 있다. 이제 임의의 자연수 $n$ 과 $m>n/2$ 인 자연수 $m$ 을 생각하자. 테일러 정리 에 의해 $e^{1/x^2} > 1 + \cdots + 1/(m!x^{2m})$ 이므로 

$$
\lim_{x \to 0} x^n e^{1/x^2}  \ge \lim_{x \to 0} x^n + \cdots + \dfrac{1}{m!}x^{-2m+n} = \infty
$$

임을 알 수 있다. 즉 임의의 자연수 $n$ 에 대해 

$$
\lim_{x \to 0}\dfrac{e^{-1/x^2}}{x^n} = \lim_{x \to 0}\dfrac{1}{x^n e^{1/x^2}} = 0
$$

이이다. 따라서 $f^{(i)}(0)=0$ 이다. $f\in C^\infty$ 인 것은 자연스럽게 알 수 있다.

:::


</br>

## 다변수 벡터 함수의 미분

### 다변수 벡터함수의 미분과 편미분 {#sec-CM_derivative_and_partial_derivatives_of_multivariable_vector_valued_function}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_derivative_and_partial_derivative_1}

#### 다변수 벡터함수의 미분과 편미분 1

$F:\R^n \to \R^m$ 이 $\bf{a}\in \R^n$ 에서 미분가능하다면 각각의 $1 \le i \le m,\, 1 \le j \le n$ 에 대해 $D_jf_i(\bf{a})$ 가 존재하며, $F'(\bf{a})$ 는 $m\times n$ 행렬로 $D_jf_i(\bf{a})$ 를 $i$ 행 $j$ 열 성분으로 가진다. 즉

$$
F'(\bf{a}) = \begin{bmatrix} D_1f_1(\bf{a}) & \cdots & D_nf_1(\bf{a})\\ \vdots & & \vdots \\ D_1 f_m(\bf{a}) & \cdots & D_n f_m(\bf{a}) \end{bmatrix}
$$ 

이다.
::: 

</div></br>

::: {.proof}

@thm-CM_basic_properties_of_derivative_of_multivariable_functions 의 ($3$) 에 의해 $f_i'(\bf{a}) = \begin{bmatrix} D_1 f_i(\bf{a}) & \cdots D_n f_i(\bf{a})\end{bmatrix}$ 임을 보이면 된다. $H:\R \to \R^n$ 를 $\bf{a}$ 에서 $j$ 번째 성분만 $x$ 인 함수라고 하자. 즉

$$
H(\bf{a}) = (a_1,\ldots,\,a_{j-1},\,x,\,a_{j+1},\ldots,\,a_n)
$$

이다. 그렇다면 $D_j f_i(\bf{a}) = (f_i \circ H)'(a_j) = f_i'(\bf{a}) \cdot H'(a_j) =f'_i(\bf{a})\cdot \bf{e}_j= (f'_i(\bf{a}))_j$ 이다. 따라서 

$$
f_i'(\bf{a}) = \begin{bmatrix} D_1 f_i(\bf{a}) & \cdots D_n f_i(\bf{a})\end{bmatrix}
$$

이다. $\square$

:::

</br>

즉 우리는 $F:\R^n \to \R^m$ 이 $\bf{a}$ 에서 미분가능할경우 $F'(\bf{a})$ 를 $D_jf_i(\bf{a})$ 로 표현 가능하다는 것을 알았다. 그러나 그 역은 성립하지 않는데 $\bf{a}$ 에 대해 $F$ 의 모든 편미분이 존재하더라도 $F$ 가 미분가능하지 않을 수 있다. 여기에는 하나의 조건이 더 필요하다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_derivative_and_partial_derivative_2}

#### 다변수 벡터함수의 미분과 편미분 2

$F:\R^n \to \R^m$ 에 대해 $\bf{a}$ 를 포함하는 어떤 열린 공간에서 $D_jf_i(\bf{a})$ 가 존재하며 연속이면 $F$ 는 $\bf{a}$ 에서 미분가능하다.
::: 

</div></br>

::: {.proof}

$f_i = \pi_i\circ F$ 라고 하자. 또한 $\bf{a}$ 를 포함하는 위의 조건을 만족하는 열린 공간에서만 생각한다. 

$$
\begin{aligned}
f_i(\bf{a}+\bf{h})-f_i(\bf{a}) &= f_i(a_1+h_1, a_2,\ldots,\, a_n) - f_i(a_1,\ldots,\,a_n) \\[0.3em]
&\quad + f_i(a_1+h_1, a_2+h_2,a_3,\ldots,\,a_n) - f_i(a_1+h_1,a_2,\ldots,\,a_n) \\[0.3em]
&\quad + \qquad \qquad \vdots \\[0.3em]
&\quad + f_i(a_1+h+1, \ldots,a_n+h_n) - f_i(a_1+h_1,\ldots,a_{n-1}+h_{n-1},a_n)
\end{aligned}
$$

이다. 평균값정리를 이용하면 $j=1,\ldots,\,n$ 에 대해 

$$
\begin{aligned}
f_i(a_1+h_1,\ldots,\,a_{j}+h_j,\,a_{j+1},\ldots,\,a_n) &- f_i(a_1+h_1,\ldots,\,a_{j-1}+h_{j-1},\,a_j,\ldots,\,a_n) \\[0.3em]
&= h_j D_j f_i (a_1+h_1,\ldots,\,a_{j-1}+h_{j-1},\,b_j,\,a_{j+1},\ldots,a_n)
\end{aligned}
$$

을 만족하는 $b_j$ 가 $a_j$ 와 $a_j+h_j$ 사이에 존재한다. 즉 이 $b_1,\ldots,\,b_n$ 에 대해 

$$
f_i(\bf{a}+\bf{h})-f_i(\bf{a}) = \sum_{j=1}^n h_jD_jf_i (a_1+h_1,\ldots,\,a_{j-1}+h_{j-1},\,b_j,\,a_{j+1},\ldots,a_n)
$$

이다. 이제 $\bf{c}_j =(a_1+h_1,\ldots,\,a_{j-1}+h_{j-1},\,b_j,\,a_{j+1},\ldots,a_n)$ 라고 하자. 

$$
\begin{aligned}
&\left\|F(\bf{a}+\bf{h})-F(\bf{a}) - \sum_{i=1}^m \sum_{j=1}^n D_j f_i(\bf{a}) \cdot h_j\right\| \\[0.3em] 
&\qquad \qquad \qquad\le\sum_{i=1}^m \left| f_i(\bf{a}+\bf{h})-f_i(\bf{a}) - \sum_{j=1}^n D_j f_i(\bf{a}) h_j\right| \\[0.3em]
&\qquad \qquad \qquad=\sum_{i=1}^m \left| \sum_{j=1}^n D_j f_i(\bf{c}_j) h_j- D_j f_i (\bf{a})h_j \right| \\[0.3em]
&\qquad \qquad \qquad\le \sum_{i=1}^m \sum_{j=1}^n \left|D_j f_i(\bf{c}_j) - D_j f_i (\bf{a})\right||h_j|
\end{aligned}
$$

이다. $|h_j|\le \|\bf{h}\|$ 임을 이용하면

$$
\lim_{\bf{h}\to \bf{0}} \dfrac{\displaystyle \left\|F(\bf{a}+\bf{h})-F(\bf{a}) - \sum_{i=1}^m \sum_{j=1}^n D_j f_i(\bf{a}) \cdot h_j\right\| }{\|\bf{h}\|} \le \lim_{\bf{h}\to \bf{0}}\sum_{i=1}^m \sum_{j=1}^n\left|D_j f_i(\bf{c}_j) - D_j f_i (\bf{a})\right| = 0
$$

이며 $\bf{h}\to \bf{0}$ 이면 $\bf{c}_j \to \bf{a}$ 이며 $\bf{a}$ 에서 연속이므로 위의 극한이 $0$ 임을 알 수 있다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_chain_rule_for_multivariable_vector_valued_function}

#### 다변수 벡터함수의 연쇄 규칙

$G:\R^n \to \R^m$ 이 $C^1$ 급 함수이고 $F:\R^m \to \R^p$ 이 $G(\bf{a})$ 에서 미분가능 할 때 다음이 성립한다.

$$
D(F \circ G)(\bf{a}) = DF(G(\bf{a}))\cdot DG(\bf{a})
$$

::: 

</div></br>

::: {.proof}

*trivial*
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_mean_value_theorem_for_vector_function}

#### 다변수 함수의 중간값 정리

열린 $U\subset\R^n$ 에서 정의된 $f:U \to \R$ 가 $U$ 에서 미분가능하다고 하자. $U$ 가 $\bf{a}$ 와 $\bf{a}+\bf{h}$ 를 잇는 선분을 포함한다면 이 선분상의 한 점 $\bf{c}$ 에서 다음을 만족한다.

$$
f(\bf{a}+\bf{h}) - f(\bf{a}) = Df(\bf{x})\cdot \bf{h}.
$$ {#eq-thm_part3_mean_value_theorem_for_vector_function}

:::

</div></br>

::: {.proof}

$\phi:[0,\,1]\to \R$ 을 $\phi(t) := f(\bf{a}+t\bf{h})$ 라고 정하자. $\phi$ 는 미분가능함수이며 $\phi'(t) = \bf{h} \cdot Df(\bf{a}+t\bf{h})$ 이다. 일변수 함수의 평균값 정리에 의해

$$
\phi(1)-\phi(0)= \phi'(t_0)(1-0)= \phi'(t_0)
$$

인 $t_0\in (0,\,1)$ 이 존재하며 이는 @eq-thm_part3_mean_value_theorem_for_vector_function 를 의미한다. $\square$


:::

### 연습문제 {.unnumbered}

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_28}
#### Spivak 2_28

다음 함수의 편미분을 구하라.

&emsp;($a$) $F(x,\,y) = f(g(x)k(y),\, g(x)+h(y))$.

&emsp;($b$) $F(x,\,y,\,z) = f(g(x+y),\, h(y+z))$.

&emsp;($c$) $F(x,\,y,\,z) = f(x^y,\, y^z,\,z^x)$.

&emsp;($d$) $F(x,\,y,\,z) = f(x,\,g(x),\, h(x,\,y))$.

:::

</div></br>

::: {.solution}

($a$) $p(x,\,y) = g(x)k(y),\,q(x,\,y) = g(x)+h(y)$ 라고 놓으면

$$
\begin{aligned}
D_1F (x,\,y) &= g'(x) k(y) D_1 f(p(x,\,y),\,q(x,\,y)) + g'(x)D_2 f(p(x,\,y),\,q(x,\,y)), \\[0.3em]
D_2F(x,\,y) &= g(x)k'(y) D_1 f(p(x,\,y),\,q(x,\,y)) + h'(y) D_2 f(p(x,\,y),\,q(x,\,y)).
\end{aligned}
$$

($b$) $D_1F(x,\,y)= g'(x+y) D_1 f(g(x+y),\, h(y+z))$, $D_2F(x,\,y) = g'(x+y)D_1f(g(x,\,y),\,h(y,\,z)) + h'(y+z)D_2f(g(x,\,y),\,h(y+z))$, $D_3F(x,\,y,\,z) = h'(y+z)D_2f(g(x+y),\, h(y+z))$.

($c$) $D_1F(x,\,y,\,z) = x^{y-1}D_1 f(x^y,\, y^z,\,z^x) + (\ln z) z^x D_3 f(x^y,\, y^z,\,z^x)$ 이며 나머지도 같은 방법으로 ...

($d$) $D_1F(x,\,y,\,z) = D_1f(x,\,g(x),\,h(x,\,y)) + g'(x)D_2f(x,\,g(x),\,h(x,\,y)) + D_1h(x,\,y) D_3f(x,\,g(x),\,h(x,\,y))$, $D_2F(x,\,y,\,z) = D_2h(x,\,y)D_3f(x,\,g(x),\,h(x,\,y))$

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_29}
#### Spivak 2_29

$f:\R^n \to \R$ 과 $\bf{x}\in \R^n$ 에 대해 

$$
\lim_{t \to 0} \dfrac{f(\bf{a}+t\bf{x}) - f(\bf{a})}{t}
$$

가 존재할 때 $D_\bf{x}f(\bf{a})$ 라 쓰고 $f$ 의 $\bf{a}$ 에서의 $\bf{x}$ 방향의 방향미분이라고 한다. 

&emsp;($a$) $D_{\bf{e}_i} f(\bf{a}) = D_i f(\bf{a})$ 임을 보여라.

&emsp;($b$) $D_{t\bf{x}} f(\bf{a}) = tD_\bf{x}f(\bf{a})$ 임을 보여라.

&emsp;($c$) $f$ 가 $\bf{a}$ 에서 미분가능하면 $D_\bf{x}f(\bf{a}) = Df(\bf{a})(\bf{x})$ 이며, 따라서 $D_{\bf{x}+\bf{y}}f(\bf{a}) = D_\bf{x}f(\bf{a})+ D_{\bf{y}}f(\bf{a})$ 임을 보여라.

:::

</div></br>

::: {.solution}

($a$) 

$$
\lim_{t\to 0}\dfrac{f(\bf{a}+t\bf{e}_i)-f(\bf{a})}{t} =\lim_{t\to 0} \dfrac{f(a_1,\ldots,a_{i-1},a_{i}-t,a_{i+1}\ldots,\,a_n)-f(a_1,\ldots,\,a_n)}{t} = D_if(\bf{a})
$$

($b$)

$$
D_{t\bf{x}}f(\bf{a})= \lim_{s \to 0}\dfrac{f(\bf{a}+st\bf{x})-f(\bf{a})}{s} = \lim_{s \to 0}t\dfrac{f(\bf{a}+st\bf{x})-f(\bf{a})}{ts}=tD_\bf{x}f(\bf{a})
$$

($c$) $Df(\bf{a})(\bf{x})= \sum_i x_iD_i f(\bf{a})=D_{\bf{x}}f(\bf{a})$ 이다. 이로부터

$$
D_{\bf{x}+\bf{y}}f(\bf(a)) = Df(\bf{a})(\bf{x}+\bf{y}) = Df(\bf{a})(\bf{x})+ Df(\bf{a})(\bf{y}) = D_\bf{x}f(\bf{a}) + D_\bf{y}f(\bf{a})$ 
$$

이다.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_30}
#### Spivak 2_30

$f$ 가 @exr-CM_spivak_2_4 의 그것과 같다. $D_\bf{x}f(0,\,0)$ 이 모든 $\bf{x}$ 에서 정의됨을 보여라. 그러나 $g\ne 0$ 이면 $D_{\bf{x}+\bf{y}}f(0,\,0) = D_\bf{x}f(0,\,0) + D_\bf{y}f(0,\,0)$ 은 모든 $\bf{x},\, \bf{y}$ 에서 성립하는 것은 아님을 보여라.

:::

</div></br>

::: {.solution}

$$
D_{\bf{x}}f(0,0) = \lim_{t \to 0}\dfrac{f(t\bf{x})}{t} = \lim_{t \to 0} \dfrac{1}{t}\|t\bf{x}\|g\left(\dfrac{t\bf{x}}{\|t\bf{x}\|}\right) 
$$

이며 $g(-\bf{x})=-g(\bf{x})$ 이므로 $t\to 0^+$ 이든 $t \to 0^-$ 이든 $D_{\bf{x}}f(0,\,0) = f(\bf{x})$ 이다. 

$g \ne 0$ 이면 $g(a,\,b)\ne 0$ 인 $(a,\,b)$ 가 존재한다. 그런데 $D_{(a,0)}f(0,\,0) = aD_{\bf{e}_1}f(0,\,0)=0$, $D_{(0,\,b)}f(0,\,0)=bD_{\bf{e}_2}f(0,\,0)=0$ 이지만 $D_{(a,\,b)}f(0,\,0) = f(a,\,b) \ne 0$ 이다.


:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_31}
#### Spivak 2_31

$f:\R^2 \to \R$ 이 @exr-CM_spivak_1_26 과 같이 정의되었다. $f$ 가 $(0,\,0)$ 에서 연속이 아니지만 모든 $\bf{x}\in \R^2$ 에서 $D_{\bf{x}} f(0,\,0)$ 이 존재함을 보여라.

:::

</div></br>

::: {.solution}

$f$ 가 $(0,\,0)$ 에서 연속이 아님은  @exr-CM_spivak_1_26 에서 보였다. $D_{\bf{x}}(0,\,0) = \lim_{t \to 0}\dfrac{f(t\bf{x})}{t}=0$ 이다.
:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_32}
#### Spivak 2_32

($a$) $f:\R\to\R$ 이 다음과 같이 정의되었다.

$$
f(x) = \left\{\begin{array}{ll} x^2 \sin \dfrac{1}{x},\qquad & x\ne 0 \\ 0,& x=0.\end{array}\right.
$$

$f$ 가 $0$ 에서 미분가능하지만 $f'$ 은 $0$ 에서 연속이 아님을 보여라.

($b$) $f:\R^2 \to \R$ 이 다음과 같이 정의되었다.

$$
f(x,\,y) = \left\{\begin{array}{ll} (x^2+y^2) \sin \dfrac{1}{\sqrt{x^2+y^2}},\qquad & (x,\,y) \ne \bf{0} \\ 0,& (x,\,0) = \bf{0}.\end{array}\right.
$$

$f$ 는 $(0,\,0)$ 에서 미분가능이지만 $D_if$ 는 $(0,\,0)$ 에서 연속이 아님을 보여라.

:::

</div></br>

::: {.solution}

($a$) $\left|t \sin \left(\dfrac{1}{t}\right)\right| \le |t|$ 이므로 

$$
f'(0) = \lim_{t \to 0}\dfrac{t^2 \sin (1/t)}{t} = \lim_{t \to 0}t \sin \left(\dfrac{1}{t}\right) = 0
$$

이다. $x\ne 0$ 에 대해

$$
f'(x) = x\sin \dfrac{1}{x} - \cos \dfrac{1}{x}
$$

이며 $x \to 0$ 에 대해 수렴하지 않으므로 $f'$ 은 $0$ 에서 연속이 아니다.

($b$) ($a$) 와 같은 이유로 $f$ 는 $(0,\,0)$ 에서 미분가능이다.

$$
D_1f(0,\,0) = \lim_{h \to 0} h^2\sin \dfrac{1}{|h|} = 0 = D_2f(0,\,0)
$$

이다. 그러나

$$
\begin{aligned}
D_1 f(x,\,y) &= 2x \sin \dfrac{1}{\sqrt{x^2+y^2}} - \dfrac{x}{\sqrt{x^2+y^2}} \cos \dfrac{1}{\sqrt{x^2+y^2}}, \\[0.3em]
D_2 f(x,\,y) &= 2y \sin \dfrac{1}{\sqrt{x^2+y^2}} - \dfrac{y}{\sqrt{x^2+y^2}} \cos \dfrac{1}{\sqrt{x^2+y^2}}.
\end{aligned}
$$

이며 둘 다 $(0,\,0)$ 으로의 극한이 존재하지 않는다.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_33}
#### Spivak 2_33

@thm-CM_derivative_and_partial_derivative_2 에서 $D_1f_i(\bf{a})$ 가 연속인 조건을 제거해도 된다는 것을 보여라. ($D_2f_j$ 부터는 연속이어야 한다.)

:::

</div></br>

::: {.solution}
@thm-CM_derivative_and_partial_derivative_2 의 증명에서 $D_1f_i$ 

$$
\begin{aligned}
f_i(\bf{a}+\bf{h})-f_i(\bf{a}) &= f_i(a_1+h_1, a_2,\ldots,\, a_n) - f_i(a_1,\ldots,\,a_n) \\[0.3em]
&\quad + f_i(a_1+h_1, a_2+h_2,a_3,\ldots,\,a_n) - f_i(a_1+h_1,a_2,\ldots,\,a_n) \\[0.3em]
&\quad + \qquad \qquad \vdots \\[0.3em]
&\quad + f_i(a_1+h+1, \ldots,a_n+h_n) - f_i(a_1+h_1,\ldots,a_{n-1}+h_{n-1},a_n) \\[0.3em]
&=f_i(a_1+h_1, a_2,\ldots,\, a_n) - f_i(a_1,\ldots,\,a_n)  \\[0.3em]
&+ \sum_{j=2}^n h_j D_jf_i (a_1+h_1,\ldots,\,a_{j-1}+h_{j-1},\,b_j,\,a_{j+1},\ldots,a_n)
\end{aligned}
$$

이므로

$$
\begin{aligned}
&\left\|F(\bf{a}+\bf{h})-F(\bf{a}) - \sum_{i=1}^m \sum_{j=1}^n D_j f_i(\bf{a}) \cdot h_j\right\| \\[0.3em] 
& \qquad\le\sum_{i=1}^m \left| f_i(\bf{a}+\bf{h})-f_i(\bf{a}) - \sum_{j=1}^n D_j f_i(\bf{a}) h_j\right| \\[0.3em]
& \qquad=\sum_{i=1}^m \left| f_i(a_1+h_1, a_2,\ldots,\, a_n) - f_i(a_1,\ldots,\,a_n) + \sum_{j=2}^n D_j f_i(\bf{c}_j) h_j- \sum_{j=1}^nD_j f_i (\bf{a})h_j \right| \\[0.3em]
&\qquad \le \sum_{i=1}^m \left| f_i(a_1+h_1, a_2,\ldots,\, a_n) - f_i(a_1,\ldots,\,a_n) - D_1 f_i (\bf{a})h_1 \right| \\[0.3em] 
&\qquad \qquad \qquad + \sum_{i=1}^m \sum_{j=2}^n \left| D_jf_i(\bf{c}_j)h_j - D_jf_i(\bf{a})h_j\right|
\end{aligned}
$$

이다. 마지막 의 첫번째 항은 편미분의 정의에 의해 $0$ 으로 수렴하며 두번째 항부터는 $D_jf_i$ 의 연속성에 의해 $0$ 으로 수렴한다. 즉 $D_1f_i$ 는 연속이 아니더라도 미분가능성에는 문제가 없다.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_34}
#### Spivak 2_34

$f:\R^n \to \R$ 이 자연수 $m$ 에 대해 $f(t\bf{x})=t^mf(\bf{x})$ 라면 **homogeneous of degree $m$** 라고 한다. $f$ 가 미분가능하다면 다음이 성립함을 보여라.

$$
\sum_{i=1}^n x_i D_i f(\bf{x}) = mf(\bf{x}).
$$

:::

</div></br>

::: {.solution}

정해진 $\bf{x}$ 에 대해 $g(t) = f(t\bf{x})$ 라고 하면 $\dfrac{dg(t)}{dt} = mt^{m-1}f(\bf{x})$ 이다. 

$$
\dfrac{df(t\bf{x})}{dt} = \bf{x}\cdot Df(t\bf{x}) = \sum_{i=1}^n x_i D_i f(t\bf{x})
$$

이므로 $t=1$ 을 넣으면 $\sum_{i=1}^n x_i D_i f(\bf{x})= mf(\bf{x})$ 이다.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_35}
#### Spivak 2_35

$f:\R^n \to \R$ 이 미분가능하며 $f(\bf{0})=0$ 일 때 다음을 만족하는 $g:\R^n \to \R$ 이 존재함을 보여라.

$$
f(x) = \sum_{i=1}^n x_i g_i(x).
$$

:::

</div></br>

::: {.solution}

$h_\bf{x}(t) = f(t\bf{x})$ 라고 하자.  $\displaystyle \dfrac{dh_\bf{x}(t)}{dt} = \sum_{i=1}^n x_i D_i f (t\bf{x})$ 이며

$$
f(\bf{x}) = f(\bf{x})- f(\bf{0}) = \int_0^1 \dfrac{d h_{\bf{x}}(t)}{dt}\, dt = \sum_{i=1}^n \int_0^1 x_i D_if(t\bf{x})\, dt
$$

이므로 $g_i(x) = \int_0^1 D_i f(t\bf{x})\, dt$ 이다.

:::

</br>