---
title: "역함수 정리와 음함수 정리"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

## 다변수 벡터 함수의 미분

### 다변수 벡터함수의 미분과 편미분 {#sec-CM_derivative_and_partial_derivatives_of_multivariable_vector_valued_function}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_derivative_and_partial_derivative_1}

#### 다변수 벡터함수의 미분과 편미분 1

$F:\R^n \to \R^m$ 이 $\bf{a}\in \R^n$ 에서 미분가능하다면 각각의 $1 \le i \le m,\, 1 \le j \le n$ 에 대해 $D_jf_i(\bf{a})$ 가 존재하며, $F'(\bf{a})$ 는 $m\times n$ 행렬로 $D_jf_i(\bf{a})$ 를 $i$ 행 $j$ 열 성분으로 가진다. 즉

$$
F'(\bf{a}) = \begin{bmatrix} D_1f_1(\bf{a}) & \cdots & D_nf_1(\bf{a})\\ \vdots & & \vdots \\ D_1 f_m(\bf{a}) & \cdots & D_n f_m(\bf{a}) \end{bmatrix}
$$ 

이다.
::: 

</div>

::: {.proof}

@thm-CM_basic_properties_of_derivative_of_multivariable_functions 의 ($3$) 에 의해 $f_i'(\bf{a}) = \begin{bmatrix} D_1 f_i(\bf{a}) & \cdots D_n f_i(\bf{a})\end{bmatrix}$ 임을 보이면 된다. $H:\R^n \to \R^n$ 를 $\bf{a}$ 에서 $j$ 번째 성분만 $x$ 인 함수라고 하자. 즉

$$
H(\bf{a}) = (a_1,\ldots,\,a_{j-1},\,x,\,a_{j+1},\ldots,\,a_n)
$$

이다. 그렇다면 $D_j f_i(\bf{a}) = (f_i \circ H)'(a_j) = f_i'(\bf{a}) \cdot H'(a_j) =f'_i(\bf{a})\cdot \bf{e}_j= (f'_i(\bf{a}))_j$ 이다. 따라서 

$$
f_i'(\bf{a}) = \begin{bmatrix} D_1 f_i(\bf{a}) & \cdots D_n f_i(\bf{a})\end{bmatrix}
$$

이다. $\square$

:::

</br>

즉 우리는 $F:\R^n \to \R^m$ 이 $\bf{a}$ 에서 미분가능할경우 $F'(\bf{a})$ 를 $D_jf_i(\bf{a})$ 로 표현 가능하다는 것을 알았다. 그러나 그 역은 성립하지 않는데 $\bf{a}$ 에 대해 $F$ 의 모든 편미분이 존재하더라도 $F$ 가 미분가능하지 않을 수 있다. 여기에는 하나의 조건이 더 필요하다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_derivative_and_partial_derivative_2}

#### 다변수 벡터함수의 미분과 편미분 2

$F:\R^n \to \R^m$ 에 대해 $\bf{a}$ 를 포함하는 어떤 열린 근방에서 $D_jf_i(\bf{a})$ 가 존재하며 연속이면 $F$ 는 $\bf{a}$ 에서 미분가능하다.
::: 

</div>

::: {.proof}

$f_i := \pi_i\circ F$ 라고 하자. 또한 $\bf{a}$ 를 포함하는 위의 조건을 만족하는 열린 근방에서만 생각한다. 

$$
\begin{aligned}
f_i(\bf{a}+\bf{h})-f_i(\bf{a}) &= f_i(a_1+h_1, a_2,\ldots,\, a_n) - f_i(a_1,\ldots,\,a_n) \\[0.3em]
&\quad + f_i(a_1+h_1, a_2+h_2,a_3,\ldots,\,a_n) - f_i(a_1+h_1,a_2,\ldots,\,a_n) \\[0.3em]
&\quad + \qquad \qquad \vdots \\[0.3em]
&\quad + f_i(a_1+h+1, \ldots,a_n+h_n) - f_i(a_1+h_1,\ldots,a_{n-1}+h_{n-1},a_n)
\end{aligned}
$$

이다. 평균값정리를 이용하면 $j=1,\ldots,\,n$ 에 대해 

$$
\begin{aligned}
f_i(a_1+h_1,\ldots,\,a_{j}+&h_j,\,a_{j+1},\ldots,\,a_n) - f_i(a_1+h_1,\ldots,\,a_{j-1}+h_{j-1},\,a_j,\ldots,\,a_n) \\[0.3em]
&= h_j D_j f_i (a_1+h_1,\ldots,\,a_{j-1}+h_{j-1},\,b_j,\,a_{j+1},\ldots,a_n)
\end{aligned}
$$

을 만족하는 $b_j$ 가 $a_j$ 와 $a_j+h_j$ 사이에 존재한다. 즉 이 $b_1,\ldots,\,b_n$ 에 대해 

$$
f_i(\bf{a}+\bf{h})-f_i(\bf{a}) = \sum_{j=1}^n h_jD_jf_i (a_1+h_1,\ldots,\,a_{j-1}+h_{j-1},\,b_j,\,a_{j+1},\ldots,a_n)
$$

이다. 이제 $\bf{c}_j =(a_1+h_1,\ldots,\,a_{j-1}+h_{j-1},\,b_j,\,a_{j+1},\ldots,a_n)$ 라고 하자. 

$$
\begin{aligned}
&\left\|F(\bf{a}+\bf{h})-F(\bf{a}) - \sum_{i=1}^m \sum_{j=1}^n D_j f_i(\bf{a}) \cdot h_j\right\| \\[0.3em] 
&\qquad \qquad \qquad\le\sum_{i=1}^m \left| f_i(\bf{a}+\bf{h})-f_i(\bf{a}) - \sum_{j=1}^n D_j f_i(\bf{a}) h_j\right| \\[0.3em]
&\qquad \qquad \qquad=\sum_{i=1}^m \left| \sum_{j=1}^n D_j f_i(\bf{c}_j) h_j- D_j f_i (\bf{a})h_j \right| \\[0.3em]
&\qquad \qquad \qquad\le \sum_{i=1}^m \sum_{j=1}^n \left|D_j f_i(\bf{c}_j) - D_j f_i (\bf{a})\right||h_j|
\end{aligned}
$$

이다. $|h_j|\le \|\bf{h}\|$ 임을 이용하면

$$
\lim_{\bf{h}\to \bf{0}} \dfrac{\displaystyle \left\|F(\bf{a}+\bf{h})-F(\bf{a}) - \sum_{i=1}^m \sum_{j=1}^n D_j f_i(\bf{a}) \cdot h_j\right\| }{\|\bf{h}\|} \le \lim_{\bf{h}\to \bf{0}}\sum_{i=1}^m \sum_{j=1}^n\left|D_j f_i(\bf{c}_j) - D_j f_i (\bf{a})\right| = 0
$$

이며 $\bf{h}\to \bf{0}$ 이면 $\bf{c}_j \to \bf{a}$ 이며 $\bf{a}$ 에서 연속이므로 위의 극한이 $0$ 임을 알 수 있다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_chain_rule_for_multivariable_vector_valued_function}

#### 다변수 벡터함수의 연쇄 규칙

$G:\R^n \to \R^m$ 이 $C^1$ 급 함수이고 $F:\R^m \to \R^p$ 이 $G(\bf{a})$ 에서 미분가능 할 때 다음이 성립한다.

$$
(F \circ G)'(\bf{a}) = F'(G(\bf{a}))\cdot G'(\bf{a})
$$

::: 

</div>

::: {.proof}

*trivial*
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_mean_value_theorem_for_vector_function}

#### 다변수 함수의 중간값 정리

열린 $U\subset\R^n$ 에서 정의된 $F:U \to \R$ 가 $U$ 에서 미분가능하다고 하자. $U$ 가 $\bf{a}$ 와 $\bf{a}+\bf{h}$ 를 잇는 선분을 포함한다면 이 선분상의 한 점 $\bf{c}$ 에서 다음을 만족한다.

$$
F(\bf{a}+\bf{h}) - F(\bf{a}) = F'(\bf{x})\cdot \bf{h}.
$$ {#eq-thm_part3_mean_value_theorem_for_vector_function}

:::

</div>

::: {.proof}

$\phi:[0,\,1]\to \R$ 을 $\phi(t) := F(\bf{a}+t\bf{h})$ 라고 정하자. $\phi$ 는 미분가능함수이며 $\phi'(t) = \bf{h} \cdot F'(\bf{a}+t\bf{h})$ 이다. 일변수 함수의 평균값 정리에 의해

$$
\phi(1)-\phi(0)= \phi'(t_0)(1-0)= \phi'(t_0)
$$

인 $t_0\in (0,\,1)$ 이 존재하며 이는 @eq-thm_part3_mean_value_theorem_for_vector_function 를 의미한다. $\square$

:::

</br>

### 연습문제 {.unnumbered}

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_28}
#### Spivak 2_28

다음 함수의 편미분을 구하라.

&emsp;($a$) $F(x,\,y) = f(g(x)k(y),\, g(x)+h(y))$.

&emsp;($b$) $F(x,\,y,\,z) = f(g(x+y),\, h(y+z))$.

&emsp;($c$) $F(x,\,y,\,z) = f(x^y,\, y^z,\,z^x)$.

&emsp;($d$) $F(x,\,y,\,z) = f(x,\,g(x),\, h(x,\,y))$.

:::

</div>

::: {.solution}

($a$) $p(x,\,y) = g(x)k(y),\,q(x,\,y) = g(x)+h(y)$ 라고 놓으면

$$
\begin{aligned}
D_1F (x,\,y) &= g'(x) k(y) D_1 f(p(x,\,y),\,q(x,\,y)) + g'(x)D_2 f(p(x,\,y),\,q(x,\,y)), \\[0.3em]
D_2F(x,\,y) &= g(x)k'(y) D_1 f(p(x,\,y),\,q(x,\,y)) + h'(y) D_2 f(p(x,\,y),\,q(x,\,y)).
\end{aligned}
$$

($b$) $D_1F(x,\,y)= g'(x+y) D_1 f(g(x+y),\, h(y+z))$, $D_2F(x,\,y) = g'(x+y)D_1f(g(x,\,y),\,h(y,\,z)) + h'(y+z)D_2f(g(x,\,y),\,h(y+z))$, $D_3F(x,\,y,\,z) = h'(y+z)D_2f(g(x+y),\, h(y+z))$.

($c$) $D_1F(x,\,y,\,z) = x^{y-1}D_1 f(x^y,\, y^z,\,z^x) + (\ln z) z^x D_3 f(x^y,\, y^z,\,z^x)$ 이며 나머지도 같은 방법으로 ...

($d$) $D_1F(x,\,y,\,z) = D_1f(x,\,g(x),\,h(x,\,y)) + g'(x)D_2f(x,\,g(x),\,h(x,\,y)) + D_1h(x,\,y) D_3f(x,\,g(x),\,h(x,\,y))$, $D_2F(x,\,y,\,z) = D_2h(x,\,y)D_3f(x,\,g(x),\,h(x,\,y))$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_29}
#### Spivak 2_29

$f:\R^n \to \R$ 과 $\bf{x}\in \R^n$ 에 대해 

$$
\lim_{t \to 0} \dfrac{f(\bf{a}+t\bf{x}) - f(\bf{a})}{t}
$$

가 존재할 때 $D_\bf{x}f(\bf{a})$ 라 쓰고 $f$ 의 $\bf{a}$ 에서의 $\bf{x}$ 방향의 방향미분이라고 한다. 

&emsp;($a$) $D_{\bf{e}_i} f(\bf{a}) = D_i f(\bf{a})$ 임을 보여라.

&emsp;($b$) $D_{t\bf{x}} f(\bf{a}) = tD_\bf{x}f(\bf{a})$ 임을 보여라.

&emsp;($c$) $f$ 가 $\bf{a}$ 에서 미분가능하면 $D_\bf{x}f(\bf{a}) = Df(\bf{a})(\bf{x})$ 이며, 따라서 $D_{\bf{x}+\bf{y}}f(\bf{a}) = D_\bf{x}f(\bf{a})+ D_{\bf{y}}f(\bf{a})$ 임을 보여라.

:::

</div>

::: {.solution}

($a$) 

$$
\begin{aligned}
\lim_{t\to 0}\dfrac{f(\bf{a}+t\bf{e}_i)-f(\bf{a})}{t} &=\lim_{t\to 0} \dfrac{f(a_1,\ldots,a_{i-1},a_{i}-t,a_{i+1}\ldots,\,a_n)-f(a_1,\ldots,\,a_n)}{t} \\[0.3em]
&= D_if(\bf{a})
\end{aligned}
$$

($b$)

$$
D_{t\bf{x}}f(\bf{a})= \lim_{s \to 0}\dfrac{f(\bf{a}+st\bf{x})-f(\bf{a})}{s} = \lim_{s \to 0}t\dfrac{f(\bf{a}+st\bf{x})-f(\bf{a})}{ts}=tD_\bf{x}f(\bf{a})
$$

($c$) $Df(\bf{a})(\bf{x})= \sum_i x_iD_i f(\bf{a})=D_{\bf{x}}f(\bf{a})$ 이다. 이로부터

$$
D_{\bf{x}+\bf{y}}f(\bf(a)) = Df(\bf{a})(\bf{x}+\bf{y}) = Df(\bf{a})(\bf{x})+ Df(\bf{a})(\bf{y}) = D_\bf{x}f(\bf{a}) + D_\bf{y}f(\bf{a}) 
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_30}
#### Spivak 2_30

$f$ 가 @exr-CM_spivak_2_4 의 그것과 같다. $D_\bf{x}f(0,\,0)$ 이 모든 $\bf{x}$ 에서 정의됨을 보여라. 그러나 $g\ne 0$ 이면 $D_{\bf{x}+\bf{y}}f(0,\,0) = D_\bf{x}f(0,\,0) + D_\bf{y}f(0,\,0)$ 은 모든 $\bf{x},\, \bf{y}$ 에서 성립하는 것은 아님을 보여라.

:::

</div>

::: {.solution}

$$
D_{\bf{x}}f(0,0) = \lim_{t \to 0}\dfrac{f(t\bf{x})}{t} = \lim_{t \to 0} \dfrac{1}{t}\|t\bf{x}\|g\left(\dfrac{t\bf{x}}{\|t\bf{x}\|}\right) 
$$

이며 $g(-\bf{x})=-g(\bf{x})$ 이므로 $t\to 0^+$ 이든 $t \to 0^-$ 이든 $D_{\bf{x}}f(0,\,0) = f(\bf{x})$ 이다. 

$g \ne 0$ 이면 $g(a,\,b)\ne 0$ 인 $(a,\,b)$ 가 존재한다. 그런데 $D_{(a,0)}f(0,\,0) = aD_{\bf{e}_1}f(0,\,0)=0$, $D_{(0,\,b)}f(0,\,0)=bD_{\bf{e}_2}f(0,\,0)=0$ 이지만 $D_{(a,\,b)}f(0,\,0) = f(a,\,b) \ne 0$ 이다.


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_31}
#### Spivak 2_31

$f:\R^2 \to \R$ 이 @exr-CM_spivak_1_26 과 같이 정의되었다. $f$ 가 $(0,\,0)$ 에서 연속이 아니지만 모든 $\bf{x}\in \R^2$ 에서 $D_{\bf{x}} f(0,\,0)$ 이 존재함을 보여라.

:::

</div>

::: {.solution}

$f$ 가 $(0,\,0)$ 에서 연속이 아님은  @exr-CM_spivak_1_26 에서 보였다. $D_{\bf{x}}(0,\,0) = \lim_{t \to 0}\dfrac{f(t\bf{x})}{t}=0$ 이다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_32}
#### Spivak 2_32

($a$) $f:\R\to\R$ 이 다음과 같이 정의되었다.

$$
f(x) = \left\{\begin{array}{ll} x^2 \sin \dfrac{1}{x},\qquad & x\ne 0 \\ 0,& x=0.\end{array}\right.
$$

$f$ 가 $0$ 에서 미분가능하지만 $f'$ 은 $0$ 에서 연속이 아님을 보여라.

($b$) $f:\R^2 \to \R$ 이 다음과 같이 정의되었다.

$$
f(x,\,y) = \left\{\begin{array}{ll} (x^2+y^2) \sin \dfrac{1}{\sqrt{x^2+y^2}},\qquad & (x,\,y) \ne \bf{0} \\ 0,& (x,\,0) = \bf{0}.\end{array}\right.
$$

$f$ 는 $(0,\,0)$ 에서 미분가능이지만 $D_if$ 는 $(0,\,0)$ 에서 연속이 아님을 보여라.

:::

</div>

::: {.solution}

($a$) $\left|t \sin \left(\dfrac{1}{t}\right)\right| \le |t|$ 이므로 

$$
f'(0) = \lim_{t \to 0}\dfrac{t^2 \sin (1/t)}{t} = \lim_{t \to 0}t \sin \left(\dfrac{1}{t}\right) = 0
$$

이다. $x\ne 0$ 에 대해

$$
f'(x) = x\sin \dfrac{1}{x} - \cos \dfrac{1}{x}
$$

이며 $x \to 0$ 에 대해 수렴하지 않으므로 $f'$ 은 $0$ 에서 연속이 아니다.

($b$) ($a$) 와 같은 이유로 $f$ 는 $(0,\,0)$ 에서 미분가능이다.

$$
D_1f(0,\,0) = \lim_{h \to 0} h^2\sin \dfrac{1}{|h|} = 0 = D_2f(0,\,0)
$$

이다. 그러나

$$
\begin{aligned}
D_1 f(x,\,y) &= 2x \sin \dfrac{1}{\sqrt{x^2+y^2}} - \dfrac{x}{\sqrt{x^2+y^2}} \cos \dfrac{1}{\sqrt{x^2+y^2}}, \\[0.3em]
D_2 f(x,\,y) &= 2y \sin \dfrac{1}{\sqrt{x^2+y^2}} - \dfrac{y}{\sqrt{x^2+y^2}} \cos \dfrac{1}{\sqrt{x^2+y^2}}.
\end{aligned}
$$

이며 둘 다 $(0,\,0)$ 으로의 극한이 존재하지 않는다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_33}
#### Spivak 2_33

@thm-CM_derivative_and_partial_derivative_2 에서 $D_1f_i(\bf{a})$ 가 연속인 조건을 제거해도 된다는 것을 보여라. ($D_2f_j$ 부터는 연속이어야 한다.)

:::

</div>

::: {.solution}
@thm-CM_derivative_and_partial_derivative_2 의 증명에서 $D_1f_i$ 

$$
\begin{aligned}
f_i(\bf{a}+\bf{h})-f_i(\bf{a}) &= f_i(a_1+h_1, a_2,\ldots,\, a_n) - f_i(a_1,\ldots,\,a_n) \\[0.3em]
&\quad + f_i(a_1+h_1, a_2+h_2,a_3,\ldots,\,a_n) - f_i(a_1+h_1,a_2,\ldots,\,a_n) \\[0.3em]
&\quad + \qquad \qquad \vdots \\[0.3em]
&\quad + f_i(a_1+h+1, \ldots,a_n+h_n) - f_i(a_1+h_1,\ldots,a_{n-1}+h_{n-1},a_n) \\[0.3em]
&=f_i(a_1+h_1, a_2,\ldots,\, a_n) - f_i(a_1,\ldots,\,a_n)  \\[0.3em]
&+ \sum_{j=2}^n h_j D_jf_i (a_1+h_1,\ldots,\,a_{j-1}+h_{j-1},\,b_j,\,a_{j+1},\ldots,a_n)
\end{aligned}
$$

이므로

$$
\begin{aligned}
&\left\|F(\bf{a}+\bf{h})-F(\bf{a}) - \sum_{i=1}^m \sum_{j=1}^n D_j f_i(\bf{a}) \cdot h_j\right\| \\[0.3em] 
& \qquad\le\sum_{i=1}^m \left| f_i(\bf{a}+\bf{h})-f_i(\bf{a}) - \sum_{j=1}^n D_j f_i(\bf{a}) h_j\right| \\[0.3em]
& \qquad=\sum_{i=1}^m \left| f_i(a_1+h_1, a_2,\ldots,\, a_n) - f_i(a_1,\ldots,\,a_n) + \sum_{j=2}^n D_j f_i(\bf{c}_j) h_j- \sum_{j=1}^nD_j f_i (\bf{a})h_j \right| \\[0.3em]
&\qquad \le \sum_{i=1}^m \left| f_i(a_1+h_1, a_2,\ldots,\, a_n) - f_i(a_1,\ldots,\,a_n) - D_1 f_i (\bf{a})h_1 \right| \\[0.3em] 
&\qquad \qquad \qquad + \sum_{i=1}^m \sum_{j=2}^n \left| D_jf_i(\bf{c}_j)h_j - D_jf_i(\bf{a})h_j\right|
\end{aligned}
$$

이다. 마지막 의 첫번째 항은 편미분의 정의에 의해 $0$ 으로 수렴하며 두번째 항부터는 $D_jf_i$ 의 연속성에 의해 $0$ 으로 수렴한다. 즉 $D_1f_i$ 는 연속이 아니더라도 미분가능성에는 문제가 없다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_34}
#### Spivak 2_34

$f:\R^n \to \R$ 이 자연수 $m$ 에 대해 $f(t\bf{x})=t^mf(\bf{x})$ 라면 **homogeneous of degree $m$** 라고 한다. $f$ 가 미분가능하다면 다음이 성립함을 보여라.

$$
\sum_{i=1}^n x_i D_i f(\bf{x}) = mf(\bf{x}).
$$

:::

</div>

::: {.solution}

정해진 $\bf{x}$ 에 대해 $g(t) = f(t\bf{x})$ 라고 하면 $\dfrac{dg(t)}{dt} = mt^{m-1}f(\bf{x})$ 이다. 

$$
\dfrac{df(t\bf{x})}{dt} = \bf{x}\cdot Df(t\bf{x}) = \sum_{i=1}^n x_i D_i f(t\bf{x})
$$

이므로 $t=1$ 을 넣으면 $\sum_{i=1}^n x_i D_i f(\bf{x})= mf(\bf{x})$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_35}
#### Spivak 2_35

$f:\R^n \to \R$ 이 미분가능하며 $f(\bf{0})=0$ 일 때 다음을 만족하는 $g:\R^n \to \R$ 이 존재함을 보여라.

$$
f(x) = \sum_{i=1}^n x_i g_i(x).
$$

:::

</div>

::: {.solution}

$h_\bf{x}(t) = f(t\bf{x})$ 라고 하자.  $\displaystyle \dfrac{dh_\bf{x}(t)}{dt} = \sum_{i=1}^n x_i D_i f (t\bf{x})$ 이며

$$
f(\bf{x}) = f(\bf{x})- f(\bf{0}) = \int_0^1 \dfrac{d h_{\bf{x}}(t)}{dt}\, dt = \sum_{i=1}^n \int_0^1 x_i D_if(t\bf{x})\, dt
$$

이므로 $g_i(x) = \int_0^1 D_i f(t\bf{x})\, dt$ 이다.

:::

</br>

## 역함수 정리 {#sec-CM_inverse_function_theorem}

$C^1$ 급 함수 $f:\R\to \R$ 이 $f'(a)\ne 0$ 일 때 $(f^{-1})'(a) = 1/f'(a)$ 임을 안다. $f'(a)>0$ 일 경우 $a$ 의 어떤 근방에서 $f$ 는 전단사 함수이며 국소적으로 역함수가 존재하고 그 도함수도 구할 수 있다는 의미이다. 다변수 함수에서도 똑같은 일을 할 수 있다. 그 전에 미리 알아야 할 것이 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-CM_inverse_function_theorem_1}

큐브 $A\subset \R^n$ 에서 정의된 $F:A \to \R^n$ 이 $C^1$ 급이라고 하자. 어떤 양수 $M>0$ 이 존재하여 모든 $\bf{x}\in \text{int}(A)$ 에 대해 $|D_jf_i(\bf{x})|\le M$ 이면 다음이 성립한다.

$$
\bf{x},\,\bf{y}\in A \implies \|F(\bf{y})-F(\bf{x})\|\le n^2M \|\bf{y}-\bf{x}\|.
$$

:::

</div>

::: {.proof}

$F(\bf{x}) = \begin{bmatrix} f_1 (\bf{x}) & \cdots & f_n (\bf{x})\end{bmatrix}^T$ 일 때 다음이 성립한다.

$$
\begin{aligned}
f_i(\bf{y})-f_i(\bf{x}) &= f_i(y_1,\,x_2,\ldots,\,x_n) - f_i(x_1,\ldots,\,x_n) \\[0.3em]
&\qquad + f_i(y_1,y_2,x_3,\ldots,x_n) - f_i(y_1,x_2,\ldots,x_n)\\[0.3em] 
&\qquad + \qquad \vdots \\[0.3em]
&\qquad + f_i(y_1,\ldots,\,y_n) - f_i(y_1,\ldots,\,y_{n-1},x_n).
\end{aligned}
$$

각 줄마다 편미분에 대한 중간값 정리를 사용하면

$$
f_i(\bf{y})-f_i(\bf{x}) = \sum_{j=1}^n (y_j-x_j)D_j f_i(y_1,\ldots,\,y_{j-1},\, z_{ij},\, x_{j+1},\ldots,\,x_n)
$$

을 만족하는 $z_{ij}$ 가 $x_j$ 와 $y_j$ 사이에 존재한다. 이로부터 다음을 보일 수 있다.

$$
\begin{aligned}
\|F(\bf{y}) - F(\bf{x})\| &\le \sum_{i=1}^n |f_i(\bf{y}) - f_i(\bf{x})| \\[0.3em]
& =\sum_{i=1}^n \sum_{j=1}^n |y_j-x_j| \cdot |D_j f_i (y_1,\ldots,\,y_{j-1},z_{ij},x_{j+1},\ldots,x_n)| \\[0.3em]
&\le \sum_{i=1}^n \sum_{j=1}^n \|\bf{y}-\bf{x}\| M = n^2M\|\bf{y}-\bf{x}\|. \qquad \square
\end{aligned}
$$

:::

</br>

즉 모든 어떤 열린 큐브 $A\subset \R^n$ 에서 정의된 $F:A \to \R^n$ 의 모든 편미분이 유계이면 $F$ 는 $A$ 에서(고른) 연속이다. 

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_for_inverse_function_theorem_1}

$L\in \mathcal{L}(\R^n)$ 이 가역이며 $U\in \R^n$ 이 열린 집합이고 $F:U \to \R^n$ 일 때 $F\in C^1$ 일 필요충분조건은 $L\circ F\in C^1$ 이다.

:::

</div>

::: {.solution}

선형사상 $L\in \mathcal{L}(\R^n)$ 은 $\R^n$ 전체 에서 연속이며 미분가능하다. 또한 $L'(\bf{x}) = L$ 이므로 $L\in C^1$ 이다. $(L\circ F)'(\bf{x}) = L\cdot F'(\bf{x})$ 이므로 $L \circ F$ 는 미분가능하며, @prp-MA_continuity_of_composited_function 에 의해 $F\in C^1$ 이면 $L \circ F\in C^1$ 이다. $F = L^{-1}\circ (L \circ F)$ 이므로 $L\circ F \in C^1$ 이면 $F\in C^1$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_for_inverse_function_theorem_2}

$L\in \mathcal{L}(\R^n)$ 이 가역이며 열린 집합 $U\in \R^n$ 에서 정의된 미분가능한 함수 $F:U \to \R^n$ 에 대해 $W=F(U),\, G=L\circ F$ 라고 하자. 이 때 다음은 동치이다.

&emsp;($a$) $F:U\to \R^n$ 에 대해 미분가능한 역함수 $F^{-1}: F(U) \to U$ 가 존재한다.

&emsp;($b$) $G:U\to \R^n$ 에 대해 미분가능한 역함수 $G^{-1}: G(U) \to U$ 가 존재한다.
:::

</div>

::: {.solution}

($a \implies b$) $H=F^{-1}\circ L^{-1}$ 라고 하면 $F^{-1}$ 는 미분가능하므로 $H$ 도 미분가능하다. $H\circ G = I$ 이므로 $G^{-1}=H=F^{-1}\circ L^{-1}$ 이다.

($b\implies c$) $F=L^{-1}\circ G$ 이므로 위의 논리를 똑같이 적용 할 수 있다. 

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-CM_inverse_function_theorem_2}

열린 집합 $A\subset \R^n$ 에 대해 $F: A\to \R^n$ 가 $C^1$-함수 라고 하자. $\bf{a}\in A$ 이며 $\det(F'(\bf{a}))\ne 0$ 일 때 $\bf{a}$ 를 중심으로 하는 열린 큐브 $U\subset A$ 에 대해 아래의 부등식이 성립하는 $\alpha>0$ 가 존재한다.

$$
\bf{x}_1,\, \bf{x}_2\in U \implies \|F(\bf{x}_1) - F(\bf{x}_2)\| \ge \alpha \|\bf{x}_1-\bf{x}_2\|.
$$

:::

</div>

::: {.proof}

$L:=F'(\bf{a})$ 이라고 하자. $\det (L)>0$ 이므로 $L$ 은 가역이다. $M_2=\|L^{-1}\|$ 이라고 하면 

$$
\|\bf{x}_1-\bf{x}_2\| = \left\|L^{-1}\cdot L(\bf{x}_1-\bf{x}_2)\right\| \le M_2 \|L(\bf{x}_1-\bf{x}_2)\|
$$

이므로 

$$
\|L(\bf{x}_1-\bf{x}_2)\| \ge \dfrac{1}{M_2}\|\bf{x}_1-\bf{x}_2\|
$$

이다. 이제 $H(\bf{x}) := F(\bf{x})-L(\bf{x})$ 라고 하자. $H\in C^1$ 이며 $H'(\bf{x}) = F'(\bf{x})-L$, $H'(\bf{a})=\bf{0}$ 이다. $H'(\bf{x})$ 가 연속이므로 $\bf{a}$ 를 중심으로 하는 어떤 열린 cube $U = C(\bf{a},\, \varepsilon)$ 가 존재하여 

$$
\bf{x}\in U \implies \|H'(\bf{x})\|\le \dfrac{1}{2nM_2}
$$ 

이다. $H(\bf{x}) = \begin{bmatrix} h_1(\bf{x})  & \cdots & h_n(\bf{x}) \end{bmatrix}^T$ 라고 할 때 중간값 정리(@thm-CM_mean_value_theorem_for_vector_function) 를 이용하면 $\bf{x}_1,\, \bf{x}_2\in U$ 일 때 어떤 $\bf{c}_i\in U$ 에 대해 

$$
|h_i(\bf{x}_1)-h_i(\bf{x}_2)| = |Dh_i(\bf{c}_i)\cdot (\bf{x}_1-\bf{x}_2)|  \le \dfrac{1}{2nM_2}\|\bf{x}_1-\bf{x}_2\|
$$

이며, 따라서

$$
\begin{aligned}
\|H(\bf{x}_1)-H(\bf{x}_2)\| &\le \sum_{i=1}^n |h_i(\bf{x}_1)-h_i(\bf{x}_2)| \\[0.3em]
&\le n\cdot \dfrac{1}{2nM_2} \|\bf{x}_1-\bf{x}_2\| = \dfrac{1}{2M_2}\|\bf{x}_1-\bf{x}_2\|
\end{aligned}
$$

이다. 이로부터

$$
\begin{aligned}
\|\bf{x}_1-\bf{x}_2\| &\ge 2M_2 \|H(\bf{x}_1)-H(\bf{x}_2)\| \\[0.3em]
&= 2M_2 \|F(\bf{x}_1)-F(\bf{x}_2) - L(\bf{x}_1-\bf{x}_2)\| \\[0.3em]
&\ge 2M_2 \|L(\bf{x}_1-\bf{x}_2)\| - 2M_2\|F(\bf{x}_1)-F(\bf{x}_2)\| \\[0.3em]
& \ge 2\|\bf{x}_1-\bf{x}_2\| - 2M_2 \|F(\bf{x}_1)-F(\bf{x}_2)\|
\end{aligned}
$$

이며

$$
\|F(\bf{x}_1)-F(\bf{x}_2)\| \ge \dfrac{1}{2M_2}\|\bf{x}_1-\bf{x}_2\|
$$

이다. $\square$

:::

</br>

@lem-CM_inverse_function_theorem_2 은 $\det(F'(\bf{a}))\ne 0$ 이면 $\bf{a}$ 를 중심으로 하는 어떤 열린 cube 에서 $F$ 가 단사가 됨을 의미한다. $\bf{x}_1\ne \bf{x}_2$ 이면 $\|F(\bf{x}_1)-F(\bf{x}_2)\|>0$ 이 기 때문이다. 이제 위의 보조정리에서 계속 진행해보자.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-CM_inverse_function_theorem_3}

열린 집합 $A\subset \R^n$ 에 대해 $F:A \to \R^n$ 이 $C^1$-급 함수 이며 $\det(F'(\bf{a}))\ne 0$ 라고 하자. $\bf{a}$ 를 포함하는 열린 집합 $V$ 와 $F(\bf{a})$ 를 포함하는 열린 집합 $W$ 가 존재하여 $F:V\to W$ 에 대한 역함수 $F^{-1}: W \to V$ 가 존재한다.

:::

</div>

::: {.proof}
$F$ 가 열린 집합 $U_0$ 에서 $C^1$ 이라고 하자. $F$ 는 아래의 명제 ($C-1$), ($C-2$), ($C-3$) 를 모두 만족한다.

($C-1$) @lem-CM_inverse_function_theorem_2 로 부터 $\bf{a}$ 를 중심으로 하는 열린 cube $U_1\subset A$ 이 존재하여 어떤 $\alpha>0$ 에 대해 

$$
\bf{x}_1,\,\bf{x}_2\in U_1 \implies \|F(\bf{x}_1)-F(\bf{x}_2)\| \ge \alpha\|\bf{x}_1-\bf{x}_2\|
$$

임을 안다. 즉 $U_1$ 에서 $F$ 는 단사이다.

($C-2$) $\det$ 함수와 $F'$ 이 모두 연속이므로 $\bf{a}$ 를 중심으로 하는 어떤 열린 cube $U_2\subset A$ 에서 $\bf{x}\in U_2 \implies \det(F'(\bf{x})) \ne 0$ 이다. 

($C-3$) $D_jf_i$ 가 연속이므로 $\bf{a}$ 를 포함하는 어떤 열린 cube $U_3\subset A$ 에서 

$$
\bf{x}\in U_3 \implies \|D_jf_i(\bf{x})-D_jf_i(\bf{a})\|< \dfrac{1}{2n^2}
$$

이며, 따라서 $U_3$ 에서 $D_jf_i(\bf{x})$ 는 유계이다. (@lem-CM_inverse_function_theorem_1 의 조건)

이제 $\bf{a}$ 를 중심으로 하는 작은 cube $U$ 가 존재하여 $U \subset (U_1 \cap U_2 \cap U_3)$ 이다. $U$ 를 작게 잡아 $\partial U \cap \partial U_1 = \varnothing$ 이 되도록 잡을 수 있다. 이 때 $\partial U$ 는 $U$ 의 경계점(@exr-MA_KKK_2_7_6) 이다. $\partial U$ 는 유계인 닫힌 집합이므로 옹골집합이며 $\bf{a}$ 를 포함하지 않고 $\partial U \subset U_1$ 이므로, 그리고 $U_1$ 에서 $F$ 는 단사이므로 $F(\bf{a}) \notin F(\partial U)$ 이다. $F$ 가 연속이므로 $F(\partial U)$ 도 옹골집합이며 따라서 모든 $\bf{x}\in \partial U$ 에 대해 $\|F(\bf{x})-F(\bf{a})\| \ge d$ 인 $d>0$ 이 존재한다. 이제 집합 $W$ 를 다음과 같이 정의한다.

$$
W:= \{\bf{y} \in \R^n: \|\bf{y}-F(\bf{a})\|<d/2\}.
$$

이 때 $W$ 는 열린집합이다(@exr-MA_rudin_4_3 의 풀이를 보라). 그렇다면 $\bf{y}\in W,\, \bf{x}\in \partial U$ 일 때

$$
\begin{aligned}
\|\bf{y}-F(\bf{x})\| &= \|F(\bf{x})-F(\bf{a})-\bf{y}+F(\bf{a})\| \\[0.3em]
 &\ge \|F(\bf{x})-F(\bf{a})\| - \|\bf{y}-F(\bf{a})\|  > \dfrac{d}{2} > \|\bf{y}-F(\bf{a})\|
\end{aligned} 
$$

이다. 

($C-4$) 즉 $\bf{y}\in W,\, \bf{x}\in \partial U$ 일 때

$$
\|\bf{y}-F(\bf{x})\|> \|\bf{y}-F(\bf{a})\|
$$

이다. 

이제 $\bf{y}\in W$ 에 대해 $\bf{y}=F(\bf{x})$ 를 만족하는 $\bf{x}\in U$ 는 항상 유일하게 존재함을 보이자. 이를 위해 $\overline{U} = U \cup \partial U$ 에서 정의된 $g:\overline{U} \to \R$ 을 다음과 같이 정의한다.

$$
g(\bf{x}) := \|\bf{y}-F(\bf{x})\|^2
$$

이 함수는 연속이며 $\overline{U}$ 는 옹골집합이므로 최소값을 가진다. $\bf{x} \in \partial U$ 라면 ($C-4$) 에 의해 최소값이 될 수 없으므로 $g$ 를 최소로 하는 $\bf{x}$ 는 $\bf{x}\in U$ 이며 따라서 $g'(\bf{x})=0$ 이므로

$$
\bf{0}=g'(\bf{x}) = 2 F'(\bf{x})\bf{\cdot} (\bf{y}-F(\bf{x}))
$$

이다. 그런데 $\det(F'(\bf{x})) \ne 0$ 이므로(($C-2$) 조건) $\bf{y}=F(\bf{x})$ 이어야 한다. 즉 $\bf{y}=F(\bf{x})$ 인 $\bf{x}\in U$ 가 존재한다. $U\subset U_0$ 이므로 ($C-1$) 에 의해 $U$ 에서 유일하다. 

$V=U\cap F^{-1}(W)$ 는 열린 집합이며 $F:V\to W$ 는 전단사이다. 즉 $F^{-1}:W \to V$ 가 존재한다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_inverse_function_theorem}

#### 역함수 정리

@lem-CM_inverse_function_theorem_3 에서의 $F^{-1}$ 은 미분가능하며 모든 $\bf{y}\in W$ 에 대해

$$
(F^{-1})'(\bf{y}) = \left[F'(F^{-1}(\bf{y}))\right]^{-1}.
$$ {#eq-thm-CM_inverse_function_theorem_1}

이다.
:::

</div>

::: {.proof}

우리는 @lem-CM_inverse_function_theorem_3 까지 오면서 $F:V \to W$ 를 전단사가 되게 하는 열린 집합 $V,\,W$ 가 존재함을 보였다. 이제 $F^{-1}$ 이 연속임을 보이자. $V,\,W$ 는 @lem-CM_inverse_function_theorem_3 의 증명에서의 그것과 같다. $\bf{y}_1,\,\bf{y}_2 \in W$ 일 때 @lem-CM_inverse_function_theorem_3 증명의 ($C-1$) 조건으로부터

$$
\|F^{-1}(\bf{y}_1)-F^{-1}(\bf{y}_2)\|  \le  \dfrac{1}{\alpha} \|\bf{y}_1-\bf{y}_2\|
$${#eq-thm-CM_inverse_function_theorem_2}

이다. 따라서 $F^{-1}$ 은 $W$ 에서 연속이다.

$L= F'(\bf{x})$ 라고 하자. @thm-CM_chain_rule 의 증명에서 나온 $\bf{\varphi}$ 를 이용하자. $\bf{x}'\in V$ 에 대해

$$
F(\bf{x}_1) = F(\bf{x}) + L(\bf{x}'-\bf{x}) + \bf{\varphi}(\bf{x}'-\bf{x})
$$

라고 하면

$$
\lim_{\bf{x}'\to \bf{x}} \dfrac{\|\bf{\varphi}(\bf{x}'-\bf{x})\|}{\|\bf{x}'-\bf{x}\|} = 0
$$ {#eq-thm-CM_inverse_function_theorem_3}

이다. 따라서

$$
L^{-1}(F(\bf{x}')-F(\bf{x})) = \bf{x}' - \bf{x} + L^{-1}(\bf{\varphi}(\bf{x}'-\bf{x}))
$$

이다. 각각의 $\bf{y}'\in W$ 에 대해 $\bf{y}' = F(\bf{x}_1)$ 인 $\bf{x}\in V$ 가 유일하게 존재하므로

$$
F^{-1}(\bf{y}') = F^{-1}(\bf{y}) + L^{-1}(\bf{y}'-\bf{y}) - L^{-1}(\bf{\varphi}(F^{-1}(\bf{y}') - F^{-1}(\bf{y})))
$$

이다. 즉 

$$
\lim_{\bf{y}'\to \bf{y}} \dfrac{\left\| L^{-1}(\bf{\varphi}(F^{-1}(\bf{y}') - F^{-1}(\bf{y})))\right\|}{\|\bf{y}'-\bf{y}\|} = 0
$$

임을 보이면 된다. $L^{-1}$ 이 선형변환이므로 @exr-CM_spivak_1_10 에 따라

$$
\lim_{\bf{y}'\to \bf{y}} \dfrac{\left\| \bf{\varphi}(F^{-1}(\bf{y}') - F^{-1}(\bf{y}))\right\|}{\|\bf{y}'-\bf{y}\|} = 0
$$ {#eq-thm-CM_inverse_function_theorem_4}

만 보이면 된다. 

$$
\dfrac{\left\| \bf{\varphi}(F^{-1}(\bf{y}') - F^{-1}(\bf{y}))\right\|}{\|\bf{y}'-\bf{y}\|} = \dfrac{\left\| \bf{\varphi}(F^{-1}(\bf{y}') - F^{-1}(\bf{y}))\right\|}{\|F^{-1}(\bf{y}')-F^{-1}(\bf{y})\|}  \dfrac{{\|F^{-1}(\bf{y}')-F^{-1}(\bf{y})\|}}{\|\bf{y}'-\bf{y}\|}
$$

인데. $F^{-1}$ 이 연속이므로 @eq-thm-CM_inverse_function_theorem_3 에 따라 첫번째 항의 $\bf{y}'\to \bf{y}$ 극한은 $0$ 이다. 또한 @eq-thm-CM_inverse_function_theorem_2 에 따라 두번째 항은 $1/\alpha$ 보다 작으므로 @eq-thm-CM_inverse_function_theorem_4 가 성립한다. 

즉 $\bf{y}=F(\bf{x})$ 일 때 

$$
(F^{-1})'(\bf{y}) = (F'(\bf{x}))^{-1} = [F'(F^{-1}(\bf{y}))]^{-1}
$$

이다. $\square$

:::

</br>

### 연습문제 {.unnumbered}

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_36}
#### Spivak 2.36

$A\subset \R^n$ 이 열린 집합이며 $F:A \to \R^n$ 이 $C^1$ 급 함수이고 모든 $\bf{x}\in A$ 에 대해 $\det (F'(\bf{x}))\ne 0$ 이다. $F(A)$ 는 열린 집합이며 $F^{-1}:F(A)\to A$ 는 미분가능함을 보여라. $B\subset A$ 가 열린 집합이면 $F(B)$ 도 열린 집합임을 보여라.
:::

</div>

::: {.solution}

@thm-MA_continuity_and_inverse_of_map 로부터 $F:\R^n \to \R^m$ 에서 $F$ 가 연속가 연속인 것과 임의의 열린 집합 $W\subset \R^m$ 에 대해 $F^{-1}(W)$ 가 열린 집합인 것은 동치이다. 

역함수 정리에 의해 $\bf{x}\in A$ 에 대해 $\bf{x}$ 를 포함하는 열린 집합 $V_x$ 와 $F(\bf{x})$ 를 포함하는 열린 집합 $W_x$ 가 존재하여 $F^{-1} : W_x \to V_x$ 가 미분 가능하다. $\bf{y}\in F(A)$ 이면 $\bf{y}$ 를 포함하는 열린 집합 $W_y$ 에 대해 $F^{-1}(W_y)$ 가 열린 집합이며 $F^{-1}(W_y)\cap A$ 도 열린 집합이다. $F(F^{-1}(W_y)\cap A) \subset W_y$ 이며 $\bf{y}\in F(F^{-1}(W_y)\cap A)$ 이고 $F(F^{-1}(W_y)\cap A)$ 는 열린 집합이므로 $F(A)$ 도 열린 집합이다. 같은 이유로 열린 집합 $B$ 에 대해 $F(B)$ 도 열린 집합이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_37}
#### Spivak 2.37

($a$) $f:\R^2 \to \R$ 이 $C^1$ 급 함수이다. $f$ 가 단사함수가 될 수 없음을 보여라.

($b$) ($a$) 의 결과를 $m<n$ 일 때의 $F:\R^n \to \R^m$ 으로 일반화하라.

:::

</div>

::: {.solution}

($a$) 어떤 열린 집합 $A\subset \R^2$ 에 대해 $(x,\,y)\in A \implies D_1f(x,\,y)\ne 0$ 이라고 하고 $G:A \to \R^2$ 를 $G(x,\,y) := (f(x,\,y),\, y)$ 라고 하자. 

$$
\det (G'(a_1,\,a_2)) = \det \left(\begin{bmatrix} D_1f(a_1,\,a_2) & D_2f(a_1,\,a_2) \\ 0 & 1 \end{bmatrix}\right) = D_1f(a_1,\,a_2) \ne 0
$$  

이며 @exr-CM_spivak_2_36 에 의해 $G(A)$ 는 열린집합이다. $(a_1,\,a_2) \in A$ 이면 $G(a_1,\,a_2)=$$(f(a_1,\,a_2),\, a_2)$$\in G(A)$ 이므로 어떤 $\widetilde{a}_2 \ne a_2$ 에 대해 $(f(a_1,\,a_2),\,\widetilde{a}_2) \in G(A)$ 이다. 그런데 $f$ 가 단사이므로 $f(a_1,\,\widetilde{a}_2) \ne f(a_1,\,a_2)$ 이다. 따라서 $(f(a_1,\,a_2),\,\widetilde{a}_2) \notin G(A)$ 이어야 하므로 모순. 따라서 $f$ 는 단사 일 수 없다.

어떤 $(x_1,\,y_1)\in A$ 에 대해 $D_1f(x_1,\,y_1)= 0$ 이라고 하자. $D_2f(x_1,\,y_1) \ne 0$ 일 때는 앞의 경우와 마찬가지로 $f$ 가 단사가 될 수 없음을 보일 수 있다. 

이제 $D_1f(x_1,\,y_1)=D_2f(x_1,\,y_1)=0$ 

($b$) $F(x_1,\ldots,\,x_n)$ 이 단사라고 하자. $G=(F(x_1,\ldots,\,x_n),\, )$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_38}
#### Spivak 2.38

($a$) $f:\R \to \R$ 이 모든 $x\in \R$ 에 대해 $f'(x) \ne 0$ 이면 $f$ 는 단사임을 보여라.

($b$) $F:\R^2 \to \R^2$ 가 $F(x,\,y) := \begin{bmatrix} e^x \cos y & e^x \sin y\end{bmatrix}^T$ 이다. $F'(x,\,y) \ne 0$ 이지만 $F$ 는 단사가 아님을 보여라.

:::

</div>

::: {.solution}

($a$) $a<b$ 에 대해 $f(b)-f(a) = (b-a)f'(c)$ 를 만족하는 $c\in (a,\,b)$ 가 존재해야 한다. $f(a)=f(b)$ 이면 $f'(c) = 0$ 이어야 하는데 가정에 모순. 

($b$) $F'(x,\,y) = \begin{bmatrix} e^x \cos y & - e^x \sin y \\ e^x \sin y & e^x \cos y\end{bmatrix}$ 이므로 $\det(F'(x,\,y)) =e^x \ne 0$ 이지만 $F(x,\,y) = F(x,\, 2\pi + y)$ 이므로 단사가 아니다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_39}
#### Spivak 2.39
$f:\R \to \R$ 이 다음과 같이 정의되었다.

$$
f(x) = \left\{\begin{array}{ll} \dfrac{x}{2} + x^2 \sin \dfrac{1}{x}, \qquad & x\ne 0,\\ 0 & x = 0\end{array}\right.
$$

도함수가 연속이 아님을 보여라.

:::

</div>

::: {.solution}

$$
f'(x)  = \dfrac{1}{2} + 2x \sin \dfrac{1}{x} - \cos \dfrac{1}{x}
$$

이며 $\lim_{x\ to 0}$ 은 존재하지 않는다. 그러나

$$
f'(0) = \lim_{t \to 0}\left(\dfrac{1}{2} + t \sin \dfrac{1}{t}\right) = \dfrac{1}{2}
$$

이므로 도함수는 연속이지 않다. 

:::

</br>

## 음함수 정리 {#sec-CM_implicit_function_theorem}

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-CM_pts_of_inverse_function}

$F:\R^n \times \R^m \to \R^n \times \R^m$ 이 $F(\bf{x},\,\bf{y}) = (\bf{x},\, H(\bf{x,\,y}))$ 꼴이며 역함수가 존재한다면 어떤 $K:\R^n \to \R^m$ 에 대해 $F^{-1}(\bf{x},\,\bf{y}) = (\bf{x},\, K(\bf{x}))$ 꼴임을 보이자. $F^{-1}=G=\begin{bmatrix} g_1 & \cdots & g_{n+m}\end{bmatrix}^T$ 라고 하자. $i \le n$ 에 대해서만 보면 된다. $x_i = (G\circ F)_i = g_i (\bf{x},\, F_1(\bf{x},\, \bf{y}))$ 이므로 $g_i = x_i$ 이다. 

:::

</div>

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_implicit_function_theorem_1}

$F: \R^n \times \R^m \to \R^m$ 이 $(\bf{a}, \bf{b})$ 를 포함하는 열린 집합에서 $C^1$ 급 함수이며 $F(\bf{a}, \bf{b})=0$ 이라고 하자. $m \times m$ 행렬 $M$ 에 대해 $M_{ij} = D_{n+j}f_i(\bf{a},\,\bf{b})$ 이고 $\det (M) \ne 0$ 이면 $\bf{a}$ 를 포함하는 어떤 열린 집합 $A\subset \R^n$ 와 $\bf{b}$ 를 포함하는 어떤 열린집합 $B\subset \R^m$ 에서 정의된 미분가능한 단사 함수 $G:A \to B$ 가 존재하여 $F(\bf{x},\, G(\bf{x})) = 0$ 이 되도록 한다.

:::

</div>

::: {.proof}

$\widetilde{F}: \R^n \times \R^m \to \R^n \times \R^m$ 을 $\widetilde{F}(\bf{x},\,\bf{y}) := (\bf{x},\, F(\bf{x},\,\bf{y}))$ 로 정의하자. $\det (\widetilde{F}'(\bf{a},\, \bf{b}))$$= \det (M) \ne 0$ 이므로 역함수 정리 (@thm-CM_inverse_function_theorem) 에 따라 $(\bf{a},\,\bf{b})$ 를 포함하는 열린 집합 $V$ 와 $F(\bf{a},\, \bf{b})=(\bf{a},\, \bf{0})$ 을 포함하는 열린 집합 $W$ 에서 정의된 $\widetilde{F}$ 의 미분가능한 역함수 $\widetilde{F}^{-1}:W \to V$ 가 존재한다.

$V$ 를 $A\subset \R^n,\, B\subset \R^m$ 에 대해 $V=A \times B$ 가 되도록 할 수 있으며 그렇다면 $\widetilde{F}^{-1}: W \to A \times B$ 는 어떤 함수 미분가능한 함수 $K:W \to B$ 에 대해 $\widetilde{F}^{-1}(\bf{x},\,\bf{y}) = (\bf{x},\, K(\bf{x},\, \bf{y}))$ 이다(@exm-CM_pts_of_inverse_function). 이제 $\Phi:\R^n \times \R^m \to \R^m$ 을 $\Phi (\bf{x},\, \bf{y}) := \bf{y}$ 로 정의하면 $\Phi \circ \widetilde{F} = F$ 이다. 따라서

$$
F(\bf{x},\, K(\bf{x},\, \bf{y})) = (F \circ \widetilde{F}^{-1})(\bf{x},\, \bf{y}) = (\Phi \circ \widetilde{F} \circ \widetilde{F}^{-1})(\bf{x},\, \bf{y}) = \bf{y}
$$

이다. 따라서 $F(\bf{x},\, K(\bf{x},\,\bf{0})) = \bf{0}$ 이므로 $G(\bf{x}) = K(\bf{x},\,\bf{0})$ 으로 놓으면 된다. $\square$

:::

</br>

$F(\bf{x},\,G(\bf{x}))=\bf{0}$ 이므로 $f_i(\bf{x},\, G(\bf{x}))=0$ 에 대해 양변에 $D_j$ 를 취하면 

$$
0 = D_j f_i(\bf{x},\, G(\bf{x})) + \sum_{k=1}^m D_{n+k}f_i (\bf{x},\, G(\bf{x})) \cdot D_j g_k(\bf{x})
$$

이다. ($F=\begin{bmatrix} f_1 & \cdots f_m\end{bmatrix}^T$ 이며 $G=\begin{bmatrix} g_1 & \cdots g_m\end{bmatrix}^T$ 이다.) 위 식은 행렬 $M_{ij} = D_{n+j}f_i(\bf{x},\, G(\bf{x}))$ 에 대한 선형방정식이며, $\det (M) \ne 0$ 이므로 $D_jg_k(\bf{x})$ 는 $D_jf_i(\bf{x},\, G(\bf{x}))$ 를 사용하여 구할 수 있다. $D_jg_k(\bf{x})$ 를 구할 수 있으므로 $G(\bf{x})$ 역시 구할 수 있다. 그러나 모든 편미분을 이용하여 구하는 것이므로 $G(\bf{x})$ 는 유일하지 않다. 그리고 일반적으로 매우 어렵다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_implicit_function_theorem_2}

$F:\R^n \times \R^m  \to \R^m$ 가 $(\bf{a},\,\bf{b})\in \R^n \times \R^m$ 을 포함하는 열린 집합에서 $C^1$ 급 함수라고 하자. $F(\bf{a},\,\bf{b})=\bf{0}$ 이며 $m\times (n+m)$ 행렬 $M_{ij} = D_{j}f_i(\bf{a},\,\bf{b})$ 에 대해 $\text{rank}(M)=m$ 라면 $(\bf{a},\,\bf{b})$ 를 포함하는 어떤 열린 집합 $A\subset \R^{n+m}$ 에서 정의된, 아래의 ($1$), ($2$) 를 만족하는 $H: A\to \R^n \times \R^m$ 이 존재한다. 

&emsp;($1$) $H^{-1}$ 이 존재하고 미분가능하며,

&emsp;($2$) $(F\circ H)(\bf{x},\,\bf{y}) = \bf{y}$ 이다.

:::

</div>

::: {.proof}

우선 @thm-CM_implicit_function_theorem_1 와의 차이를 보자. $F'(\bf{a},\,\bf{b})$ 는 $m \times (n +m )$ 행렬이며 @thm-CM_implicit_function_theorem_1 은 정체 행과 마지막 $m$ 개의 열로 이루어진 행렬의 행렬식이 $0$ 이 아난 경우이며, 즉 마지막 $m$ 개의 열이 선형독립인 경우이며, 여기는 전체 $m+n$ 개의 열 가운데 위치에 무관하게 $m$ 개의 열이 선형독립인 경우이다. 

이제 $m$ 개의 선형독립인 열의 인덱스를 $j_1,\ldots,\,j_m$ 이라고 하고 열에 대한 permutation $G: \R^n \times \R^m \to \R^n \times \R^m$ 을 $G(x_1,\ldots,\,x_{m+n}) = (\cdots, x_{j_1}, \ldots, x_{j_m})$ 이라고 하면 $F\circ G$ 는 @thm-CM_implicit_function_theorem_1 의 $F$ 와 똑같은 경우이다. 물론 $G$ 는 선형변환이며 따라서 전체 $\R^n \times \R^m$ 에서 $C^\infty$ 급 함수이다.

@thm-CM_implicit_function_theorem_1 에 따라 $F \circ G$ 에 대해

$$
(F \circ G)(\bf{x},\,K(\bf{x},\, \bf{y})) = \bf{y}
$$

인 미분가능한 함수 $K:\R^n \times \R^m \to \R^m$ 이 존재하며 $H=G \circ (\bf{x},\, K(\bf{x},\, \bf{y}))$ 라고 놓으면 된다. $\square$

:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_40}
#### Spivak 2.40

음함수 정리를 이용하여 @exr-CM_spivak_2_15 ($c$) 를 다시 풀어라.

:::

</div>

::: {.solution}

@exr-CM_spivak_2_15 ($c$) 에서 $F = \R\times \R^n \to \R^n$ 을 $F=\begin{bmatrix}f_1 & \cdots f_n\end{bmatrix}^T$ 이며

$$
f_i (t,\,\bf{x}) = \sum_{j=1}^n a_{ij}(t)x_j - b_i(t)
$$

로 정의한다. $\det ([a_{ij}]) \ne 0$ 이므로 @thm-CM_implicit_function_theorem_1 에 의해 $F(t,\, X(t)) = 0$ 이 되도록 하는 미분가능한 $X(t) = \begin{bmatrix} x_1(t) & \cdots & x_n(t)\end{bmatrix}^T$ 가 존재한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_41}
#### Spivak 2.41

$f:\R \times \R \to \R$ 이 미분가능하다. 각각의 $x\in\R$ 에 대해 $g_x:\R \to \R$ 을 $g_x(y)= f(x,\,y)$ 로 정의하자. 각각의 $x$ 에 대해 $g_x'(y) = 0$ 이 되도록 하는 $y$ 가 유일하게 존재한다고 가정하고 이 $y$ 를 $c(x)$ 라고 하자.

($a$) 모든 $(x,\,y)$ 에 대해 $D_{2,2} f(x,\,y) \ne 0$ 이면 $c$ 는 미분가능하며

$$
c'(x) = - \dfrac{D_{2,1}f(x,\,c(x))}{D_{2,\,2}f(x,\,c(x))}
$$

임을 보여라.

($b$) $c'(x) =0$ 이면 어떤 $y$ 에서

$$
D_{2,1}f(x,\,y) = 0,\qquad D_2f(x,\,y) = 0
$$

임을 보여라.

($c$) $f(x,\,y) = x(y \ln y - y) - y \ln x$ 라고 하자. 다음을 구하라.

$$
\max_{\frac{1}{2} \le x \le 2} \left(\min_{\frac{1}{2} \le y \le 1} f(x,\,y)\right)
$$

:::

</div>

::: {.solution}

($a$) $g_x'(y) = 0$ 은 $D_{2}f(x,\,y)=0$ 과 같다는 것을 안다. $h(x,\,y)= D_2f(x,\,y)$ 라고 하자. $D_2 h = D_{2,2}f  \ne 0$ 이므로 $h(x,\, k(x)) = 0$ 을 만족하는 $y=k(x)$ 가 존재하며 이는 $c(x)$ 와 같다. 모든 $x\in \R$ 에 대해 $h(x,\,c(x))=0$ 이므로,

$$
0 = D_1 h(x,\,c(x)) = D_1h(x,\,c(x)) + c'(x) D_2h(x,\, c(x))
$$

이다. 따라서

$$
c'(x) = -\dfrac{D_1h(x,\,c(x))}{D_2 h(x,\,c(x))} = - \dfrac{D_{2, 1}h(x,\,c(x))}{D_{2,\,2} h(x,\,c(x))}
$$

이다.

($b$) ($a$) 로부터 $D_{2,1}f(x,\,c{x}) = 0$ 이므로 $y=c(x)$ 에서 $D_{2,1}f(x,\,y)=0$ 이다. $c(x)$ 의 정의에 의해 $D_2f(x,\,y) = g'(x,\,c(x))=0$ 이다.

($c$) 

:::

</br>

## 역함수 정리와 음함수 정리에 대한 다른 증명

지금까지는 거의 @Spivak1965 의 방식을 따른 증명이었다. 이제 @Rudin1976 의 방식을 따라 증명해보자.


::: {.callout-note appearance="simple" icon="false"}

::: {#def-CM_contraction}

#### Contraction

거리공간 $X$ 에서 정의된 함수 $\varphi :X \to X$ 가 어떤 실수 $c<1$ 에 대해

$$
x,\,y\in X \implies \|\phi(x)-\phi(y)\| \le c \|x-y\|
$$ {#eq-CM_def_of_contraction}

일 때 $\phi$ 를 $X$ 에서의 **contraction** 이라고 한다.

::: 
:::

</br>

Contraction 의 정의에 의해 다음은 자명하다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_uniform_continuity_of_contraction}

거리공간 $X$ 에서의 contraction 은 고른 연속 함수이다.
::: 

</div>

Contraction 과 고정점의 관계를 알아보자.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_contraction_and_fixed_point}

$\varphi$ 가 완비거리공간 $X$ 에서의 contraction 일 때 $\phi(x)=x$ 인 $x\in X$ 는 유일하게 존재한다.
::: 

</div>

::: {.proof}

즉 contraction 은 완비거리공간에서 유일한 고정점을 가진다는 의미이다. 임의의 $x_0\in X$ 를 선택하고 수열 $\langle x_n\rangle$ 을 $x_{n+1}=\varphi(x_n)$ 으로 정의하자. $n\ge 1$ 에 대해

$$
\|x_{n+1}-x_n\| = \|\varphi(x_n)-\varphi(x_{n-1})\| \le c\|x_n - x_{n-1}\| \le \cdots \le c^{n}\|x_1-x_0\|
$$

이다. 임의의 $n>m>1$ 에 대해 

$$
\begin{aligned}
\|x_n - x_m \| &\le \|x_n-x_{n-1}\| + \cdots + \|x_{m+1} - x_m\|  \\[0.3em]
&\le \left(c^{n-1} + c^{n-2} + \cdots + c^{m}\right)\|x_1-x_0\| \\[0.3em]
&= \dfrac{c^m(1-c^{n-m})}{1-c}\|x_1-x_0\| \le \dfrac{c^m}{1-c}\|x_1-x_0\|
\end{aligned}
$$

이므로 $\langle x_n \rangle$ 은 코시수열이며, $X$ 가 완비거리공간이므로 수렴한다.


:::

</br>

이제 contraction 을 이용하여 역함수 정리를 증명한다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_inverse_function_theorem_rudin}

$\R^n$ 에서의 열린 집합 $E$ 에서 정의된 $C^1$ 함수 $F:E \to \R^n$ 과 $\bf{a}\in U$ 에 대해 $F'(\bf{u})$ 가 가역이라고 하자.

($1$) $\bf{a}$ 를 포함하는 어떤 열린 집합 $U$ 와 $F(\bf{a})$ 를 포함하는 어떤 열린 집합 $V$ 에 대해 $F:U\to V$ 는 전단사이며,

($2$) $G$ 가 ($1$) 에서의 $F^{-1}$ 이라면 $G$ 는 $C^1$ 함수이다. 

::: 

</div>

::: {.proof}

$\bf{b}=F(\bf{a}),\, A=F'(\bf{a})$ 라고 하자. $2\lambda \left\|A^{-1}\right\|=1$ 이 되도록 $\lambda$ 를 정하자. $F'$ 이 연속이므로 어떤 $\bf{a}$ 열린 근방 $U$ 를 아래를 만족하도록 잡을 수 있다.

$$
\bf{x}\in U \implies \|F'(\bf{x})-A\|\le \lambda
$$ {#eq-thm-CM_inverse_function_theorem_rudin_1}

이제 $\bf{y}\in \R^n$ 에 대해 $\phi_\bf{y}:U \to \R^n$ 을 다음과 같이 정의하자.

$$
\phi_\bf{y}(\bf{x}) := \bf{x} + A^{-1}(\bf{y}-F(\bf{x})).
$$

그렇다면 

$$
\phi'_{\bf{y}}(\bf{x}) = I - A^{-1}F'(\bf{x}) = A^{-1}(A-F'(\bf{x}))
$$ 

이므로 @eq-thm-CM_inverse_function_theorem_rudin_1 과 $2\lambda \|A^{-1}\|=1$ 조건을 사용하면

$$
\forall \bf{x}\in U,\,\left\|\varphi'_\bf{y}(\bf{x})\right\| \le \dfrac{1}{2}
$$

이다. @thm-CM_mean_value_theorem_for_vector_function 


:::