---
title: "미분 형식"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---
{{< include ../../latexmacros.qmd >}}

## 다중 선형 대수

### 텐서와 텐서곱 {#sec-CM_tensor_and_tensor_product}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_k_tensor}

#### $k$-텐서

벡터공간 $V$ 에 대해 $V^k \mapsto \R$ 인 다중선형 함수의 집합을 **$k$-텐서 ($k$-tensor)** 라고 하며 $k$-텐서 의 집합을 $\mathfrak{J}^k(V)$ 라고 쓴다. 즉 $a\in \R$ 와 각각의 $i=1,\ldots,\,n$ 에 대해

$$
\begin{aligned}
\phi(v_1,\ldots,v_i+av'_i,\ldots,v_k) = \phi(v_1,\ldots,v_i,\ldots,v_k) + a\phi(v_1,\ldots,cv'_i,\,v_k)
\end{aligned}
$$ {#eq-CM_multilinear_property}

이면 $\phi\in\mathfrak{J}^K(V)$ 이다. 

여기서 $\mathfrak{J}^k(V)$ 의 합과 스칼라곱을 아래와 같이 정의한다.

$$
\begin{aligned}
(\phi+\psi)(v_1,\ldots,\,v_k) &= \phi(v_1,\ldots,\,v_k) + \psi(v_1,\ldots,\,v_k) , \\[0.3em]
(c\phi)(v_1,\ldots,\,v_k) &= c \cdot {\big (}\phi(v_1,\ldots,\,v_k){\big )} .
\end{aligned}
$$ {#eq-CM_def_addition_and_scala_product_in_k_tensor}

::: 
:::


우리는 $\mathfrak{J}^1(V)$ 가 $V$ 의 쌍대공간 $V^\ast$ 이라는 것을 쉽게 알 수 있다. 그리고 아래는 쉽게 보일 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_k_tensor_is_vector_space}

$\mathfrak{J}^k(V)$ 는 벡터공간이다.
:::

</div></br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_tensor_product}

#### 텐서곱

$\phi\in\mathfrak{J}^k(V),\, \psi\in \mathfrak{J}^l(V)$ 일 때 텐서곱 $\phi\otimes \psi \in \mathfrak{J}^{k+l}(V)$ 를 다음과 같이 정의한다.

$$
(\phi\otimes \psi)(v_1,\ldots,v_k,v_{k+1},\ldots,v_{k+l})=\phi(v_1,\ldots,v_k) \cdot \psi(v_{k+1},\ldots,v_{k+l})
$$ {#eq-CM_tensor_product}
::: 
:::

</br>

@eq-CM_tensor_product 로 정의된 $\phi\otimes \psi$ 는 실제 $(k+l)$-텐서임은 쉽게 보일 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_tensor_product}
텐서곱에 대해 다음이 성립한다. 

$$
\begin{aligned}
(\phi_1+\phi_2)\otimes \psi &= \phi_1 \otimes \psi + \phi_2 \otimes \psi, \\[0.3em]
\phi \otimes (\psi_1+\psi_2) &= \phi\otimes \psi_1 + \phi \otimes \psi_2, \\[0.3em]
(c\phi)\otimes \psi &= c(\phi \otimes \psi) = \phi \otimes (c\psi), \\[0.3em]
(\phi \otimes \psi) \otimes \chi &= \phi \otimes (\psi \otimes \chi).
\end{aligned}
$$ {#eq-CM_basic_properites_of_tensor_product}
:::

</div>

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_basis_of_tensor_product}

$n$ 차원 벡터공간 $V$ 의 기저 $e_1,\ldots,\,e_n$ 에 대한 쌍대기저 $\varphi_1,\ldots,\,\varphi_n$ 에 대해 

$$
\{\varphi_{i_1} \otimes \cdots \otimes \varphi_{i_k} : 1 \le i_1,\ldots,\,i_k \le n\}
$$

는 $\mathfrak{J}^k(V)$ 의 기저이다.

:::

</div>

::: {.proof}

쌍대기저의 성질에 의해 $\varphi_j(v_i)= \delta_{ij}$ 이다. 그리고

$$
\left(\varphi_{i_1} \otimes \cdots \otimes \varphi_{i_k}\right)(e_{j_1},\ldots,\,e_{j_k}) = \delta_{i_1j_1}\cdots \delta_{i_kj_k}
$$

임을 안다. $v_1,\ldots,v_k\in V$ 이며 $v_i = \sum_{j=1}^n a_{ij}e_j$ 이고 $T\in \mathfrak{J}^k(V)$ 일 때

$$
\begin{aligned}
T(v_1,\ldots,v_k) &= \sum_{j_1,\ldots,\,j_k=1}^n a_{1,j_1}\cdots a_{k,j_k} T(e_{j_1},\ldots,e_{j_k}) \\[0.3em]
&= \sum_{i_1,\ldots,i_k=1}^n T(e_{i_1},\ldots,e_{i_k}) \cdot {\big(} \varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k} {\big )}(v_1,\ldots,\,v_k)
\end{aligned}
$$

이다. 즉 $\{\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k} : 1\le i_1,\ldots,i_k\le n\}$ 가 $\mathfrak{J}^k(V)$ 를 span 한다. 이제 선형독립임을 보이자.

$$
\sum_{i_1,\ldots,i_k=1}^n a_{i_1,\ldots,i_k} \left(\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k}\right) = 0
$$

일 때 모든 $a_{i_1,\ldots,i_k}=0$ 이라는 것을 보이면 된다. 이 함수를 $(e_{j_1},\ldots,e_{j_k})$ 에 적용시켜보면 이를 확인 할 수 있다. $\square$

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_pullback}

#### Pull-back

미분가능한 함수 $F:V \to W$ 와 $\phi\in \mathfrak{J}^k(W)$ 에 대해 아래와 같이 정의되는 $F^\ast : \mathfrak{J}^k(W) \to \mathfrak{J}^k(V)$ 를 $F$ 에 의한 $\phi$ 의 **pull-back** 이라고 한다.

$$
\left(F^\ast (\phi)\right)(v_1,\ldots,v_k) := \phi(F(v_1),\ldots,\,F(v_k))
$$ {#eq-CM_def_pull_back_for_k_tensor}

::: 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_dual_transform}

미분가능한 $F\in \mathcal{L}(V,W)$ 에 대한 pull-back $F^\ast : \mathfrak{J}^k(W) \to \mathfrak{J}^k(V)$ 에 대해 다음이 성립한다.

&emsp;($1$) $F$ 가 선형변환이면 $F^\ast$ 는 선형변환이다.

&emsp;($2$) $F^\ast( \phi \otimes  \psi) = F^\ast (\phi) \otimes F^\ast (\psi)$ 이다.

&emsp;($3$) $G \in \mathcal{L}(W,\,X)$ 이면 $(G \circ F)^\ast (\phi) = F^\ast (G^\ast (\phi))$ 이다.

:::

</div>

::: {.proof} 

($1$) 은 정의에 의해 자명하다.

($2$) $\phi\in \mathfrak{J}^k(V),\, \psi\in \mathfrak{J}^l(V)$ 일 때,

$$
\begin{aligned}
F^\ast( \phi\otimes \psi) & (v_1,\ldots,v_k,\,v_{k+1},\ldots,v_{k+l}) \\[0.3em]
&=(\phi\otimes \psi)(F(v_1),\ldots,\,F(v_{k+l})) \\[0.3em]
&=\phi (F(v_1),\ldots,F(v_k))\cdot \psi(F(v_{k+1}),\ldots,F(v_{k+l})) \\[0.3em]
&= (F^\ast (\phi)) \otimes (F^\ast (\psi)) (v_1,\ldots,v_k,\,v_{k+1},\ldots,v_{k+l})
\end{aligned}
$$

($3$) 

$$
\begin{aligned}
\left((G\circ F)^\ast (\phi)\right)(v_1,\ldots,\,v_k) &= \phi( (G\circ F)(v_1),\ldots,(G\circ F)(v_k)) \\[0.3em]
&= \left(G^\ast (\phi)\right)(F(v_1),\ldots,\,F(v_k)) \\[0.3em]
&= F^\ast (G^\ast (\phi)) (v_1,\ldots,\,v_k). \square
\end{aligned}
$$

:::

</br>

### 교대 텐서 {#sec-CM_alternating_tensor}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_alternating_k_tensor}

#### 교대 텐서

$\omega \in \mathfrak{J}^k(V)$ 가 아래와 같은 성질을 가질 때 $\omega$ 를 **교대 $k$-텐서 (alternaging $k$-tensor)** 라고 한다.

$$
\omega (v_1,\ldots,v_i,\ldots,v_j,\ldots,v_n) = -\omega (v_1,\ldots,v_j,\ldots,v_i,\ldots,v_n) .
$$ {#eq-CM_alternating_property_of_k_tensor}

그리고 교대 $k$-텐서의 집합을 $\Omega^k(V)$ 로 표기한다.

::: 
:::

</br>

이제부터 $\omega$ 기호는 어떤 교대 텐서를 나타내는 기호로 고정한다. 아래는 쉽게 보일 수 있다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_k_alternating_tensor_is_vector_space}

$\Omega^k(V)$ 는 벡터공간이며 $\mathfrak{J}^k(V)$ 의 부분공간이다.
:::

</div></br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_alternatization}

#### 교대화

아래에 정의된 $\text{Alt}: \mathfrak{J}^k(V) \to \Sigma^k(V)$ 는 $k$-텐서의 선형결합으로 교대 $k$-텐서를 반환한다. 이를 **교대화(Alternatization)** 라고 한다. 여기서 $\sigma$ 는 대칭군 $S_k$ 에 속하는 순열이며 $\text{sgn}(\sigma)$ 는 순열에 대한 부호함수이다.

$$
\text{Alt}(\phi)(v_1,\ldots,v_k) := \dfrac{1}{k!}\sum_{\sigma \in S_k} \text{sgn}(\sigma) \cdot \phi\left(v_{\sigma(1)},\ldots,v_{\sigma(k)}\right).
$$ {#eq-CM_definition_of_alt_function}

:::
:::



</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_alt_function}

#### 교대화의 기본 성질
</br>

&emsp;($1$) $\phi\in \mathfrak{J}^k(V)$ 이면 $\text{Alt}(\phi)\in \Omega^k(V)$ 이다.

&emsp;($2$) $\omega\in \Omega^k(V)$ 이면 $\text{Alt}(\omega) = \omega$ 이다.

&emsp;($3$) $\phi\in \mathfrak{J}^k(V)$ 이면 $\text{Alt}(\text{Alt}(\phi)) = \text{Alt}(\phi)$ 이다.
:::

</div>

::: {.proof}

($1$) $\sigma,\,\tau \in S_k$ 일 때 $\text{sgn}(\sigma \circ \tau)= \text{sgn}(\sigma)\cdot \text{sgn}(\tau)$ 임을 안다. 호환 (transportation) $\tau = (i,j)$ 를 생각하면 $\text{sgn}(\tau)=-1$ 이며

$$
\begin{aligned}
\text{Alt}(\phi)(\cdots ,v_j,\ldots,\,v_i,\ldots) &= \text{Alt}(\phi) (v_{\tau(1)},\ldots,v_{\tau(k)})  \\[0.3em]
&=\dfrac{1}{k!} \sum_{\sigma\in S_k} \text{sgn}(\sigma) \cdot \phi(v_{\sigma \circ \tau (1)},\ldots,v_{\sigma\circ \tau (k)}) \\[0.3em]
&= -\dfrac{1}{k!} \sum_{\theta \in S_k} \text{sgn}(\theta) \cdot \phi(v_{\theta (1)},\ldots,v_{\theta (k)}) \\[0.3em]
&= - \text{Alt}(\phi)(\ldots,v_i,\ldots,v_j,\ldots)
\end{aligned}
$$

이다. 따라서 $\text{Alt}(\phi)\in \Omega^k(V)$ 이다.

($2$) @eq-CM_alternating_property_of_k_tensor 로 부터 $\omega (v_{\sigma (1)},\ldots,v_{\sigma (k)}) = \text{sgn}(\sigma) \cdot \omega (v_1,\ldots,v_k)$ 임을 보일 수 있다. 따라서 

$$
\begin{aligned}
\text{Alt}(\omega)(v_1,\ldots,v_k)  &= \dfrac{1}{k!}\sum_{\sigma\in S_k} \text{sgn}(\sigma) \cdot \omega(v_{\sigma (1)},\ldots,v_{\sigma(k)}) \\[0.3em]
&= \dfrac{1}{k!} \sum_{\sigma \in S_k} \text{sgn}(\sigma)\cdot \text{sgn}(\sigma) \cdot \omega (v_1,\ldots,v_k) \\[0.3em]
&= \omega(v_1,\ldots,v_k).
\end{aligned}
$$

($3$) ($1$), ($2$) 에 의해 자명하다. $\square$

:::

</br>

우리는 이전에 $\phi\in \mathfrak{J}^k(V),\,\psi\in \mathfrak{J}^l(V)$ 일 때 $\phi \otimes \psi \in \mathfrak{J}^{k+l}(V)$ 임을 보였다. 그러나 $\omega \in \Omega^k(V),\, \eta \in \Omega^l(V)$ 일 때 $\omega \otimes \eta$ 는 일반적으로 $\Omega^{k+l}(V)$ 에 포함되지 않는다. 

</br>

### 쐐기곱

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_wedge_product}

#### 쐐기곱

$\omega \in \Omega^k(V),\, \eta \in \Omega^l(V)$ 에 대해 $\omega$ 와 $\eta$ 의 **쐐기곱 (wedge product)** 혹은 **외적 (exterior product)** $\omega \wedge \eta : V^{k+l} \to \R$ 은 아래와 같이 정의된다.

$$
\begin{aligned}
\omega \wedge \eta &:= \dfrac{(k+l)!}{k!\,l!} \text{Alt}(\omega \otimes \eta)
\end{aligned}
$$ {#eq-CM_definition_of_wedge_product}
::: 
:::

@eq-CM_definition_of_wedge_product 와 @eq-CM_definition_of_alt_function 로부터 다음을 얻는다.

$$
\begin{aligned}
(\omega \wedge \eta) (v_1,\ldots,\,v_{k+l}) &= \dfrac{1}{k!\,l!}\sum_{\sigma\in S_{k+l}} \text{sgn}(\sigma)\cdot (\omega \otimes \eta)(v_{\sigma (1)},\ldots v_{\sigma (k+l)}) \\[0.3em]
&= \dfrac{1}{k!\,l!}\sum_{\sigma\in S_{k+l}} \text{sgn}(\sigma)\cdot \omega(v_{\sigma(1)},\ldots,v_{\sigma (k)}) \cdot \eta(v_{\sigma (k+1)},\ldots v_{\sigma (k+l)}).
\end{aligned}
$$ {#eq-CM_equation_of_wedge_product}



아래는 정의와 @prp-CM_basic_properties_of_alt_function 의 ($1$) 로 부터 자명하다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_wedge_product_is_an_alternating_tensor}

$\omega \wedge \eta \in \Omega^{k+l}(V)$ 이다.
:::

</div></br>

이제 쐐기곱의 중요한 성질을 알아보자.


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_wedge_product_1}

$\omega,\,\omega_1,\,\omega_2\in \Omega^k(V),\, \eta,\,\eta_1,\,\eta_2\in \Omega^l(V),\, a\in \R$ 일 때 다음이 성립한다.
$$
\begin{aligned}
(\omega_1 + \omega_2) \wedge \eta &= \omega_1 \wedge \eta + \omega_2 \wedge \eta, \\[0.3em]
\omega \wedge (\eta_1+\eta_2) &= \omega \wedge \eta_1 + \omega \wedge \eta_2, \\[0.3em]
a (\omega \wedge \eta) &= (a\omega) \wedge \eta = \omega \wedge (a\eta), \\[0.3em]
\omega \wedge \eta & = (-1)^{kl} \eta \wedge \omega.
\end{aligned}
$$ {#eq-CM_basic_properties_of_wedge_product}
:::

</div>

::: {.proof}

우선 첫번째 식을 보자.
$$
\begin{aligned}
{\big (}(\omega_1 + \omega_2)\wedge \eta {\big )} &(v_1,\ldots,\,v_{k+l}) =\dfrac{(k+l)!}{k!\,l!} \text{Alt}((\omega_1+\omega_2) \otimes \eta)(v_1,\ldots,v_{k+l}) \\[0.3em]
&= \dfrac{1}{k! \, l!} \sum_{\sigma\in S_{k+l}} \text{sgn}(\sigma) \cdot (\omega_1+\omega_2) \left(v_{\sigma (1)},\ldots,v_{\sigma (k)}\right) \cdot \eta \left(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)}\right) \\[0.3em]
&= (\omega_1 \wedge \eta_1 + \omega_2 \wedge \eta_2) (v_1,\ldots,\,v_{k+l})
\end{aligned}
$$

임을 알 수 있다. 같은 방법으로 두번째 식도 보일 수 있다. 세번째 식은 자명하다.이제 마지막 식을 보자.

$$
\begin{aligned}
(\omega \wedge \eta)(v_1,\ldots,\,v_{k+l}) &= \dfrac{1}{k!\,l!} \sum_{\sigma\in S_{k+l}}\text{sgn}(\sigma) \cdot \omega\left(v_{\sigma (1)},\ldots,v_{\sigma (k)}\right) \cdot \eta \left(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)}\right) \\[0.3em]
\end{aligned}
$$

여기서 $\tau\in S_{k+l}$ 을 $A=(1,\,2,\ldots,\,k+l)$ 을 $B=(k+1,\ldots,\,k+l,\,1,\ldots,\,k)$ 로 바꿔주는 순열이라고 하자. $A$ 의 $k+1$ 을 첫번째로 보내는 데 $k$ 번의 호환이 필요하며 이것을 $l$ 번 해줘야 하므로 $\text{sgn}(\tau) = (-1)^{kl}$ 이다. $\theta = \sigma \circ \tau$ 라고 하면 

$$
\theta(1) = \sigma(k+1),\, \theta(2) = \sigma(k+2), \ldots,  \theta(k+l) = \sigma(k)
$$

이므로
$$
\begin{aligned}
(\omega \wedge \eta)(v_1,\ldots,\,v_{k+l}) &=\dfrac{1}{k!\,l!} \sum_{\sigma\in S_{k+l}}\text{sgn}(\sigma) \cdot \eta \left(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)}\right) \cdot \omega\left(v_{\sigma (1)},\ldots,v_{\sigma (k)}\right)  \\[0.3em]
&= \dfrac{ (-1)^{kl} }{k! l!} \sum_{\theta \in S_{k+l}} \text{sgn}(\theta) \cdot \eta \left(v_{\theta (1)}, \ldots, v_{\theta (l)}\right) \cdot \omega \left(v_{\theta (l+1)} ,\ldots, v_{\theta (k+l)}\right) \\[0.3em]
&= (-1)^{kl} \eta \cdot \omega (v_1,\ldots,\,v_{k+l})
\end{aligned}
$$
이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_wedge_product_2}

$\omega\in \Omega^k(V),\, \eta\in \Omega^l(V),\, F\in \mathcal{L}(V, W)$ 일 때 다음이 성립한다.
$$
F^\ast (\omega \wedge \eta) = F^\ast (\omega) \wedge F^\ast (\eta)
$$ {#eq-CM_basic_properties_of_wedge_product_2}
:::

</div>

::: {.proof}

$$
\begin{aligned}
{\big(}F^\ast (\omega \wedge \eta){\big )}&(v_1,\ldots,v_{k+l}) = (\omega \wedge \eta)(F(v_1),\ldots,F(v_{k+l})) \\[0.3em]
&= \dfrac{1}{k!\,l!} \sum_{\sigma\in S_{k+l}} \text{sgn}(\sigma) \cdot \omega (F(v_{\sigma (1)}), \ldots, F(v_{\sigma (k)}))\cdot \eta (F(v_{\sigma (k+1)}), \ldots, F(v_{\sigma (k+l)})) \\[0.3em]
&= \dfrac{1}{k!\,l!}\sum_{\sigma \in S_{k+l}} \text{sgn}(\sigma) {\big (}F^\ast (\omega) \otimes F^\ast (\eta) {\big )} (v_{\sigma (1)},\ldots, v_{\sigma (k+l)}) \\[0.3em]
&= {\big (}F^\ast (\omega)\wedge F^\ast (\eta){\big )}(v_{1},\ldots, v_{k+l}). \qquad \square
\end{aligned}
$$


:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_wedge_product_3}

</br>

($1$) $\phi\in \mathfrak{J}^k(V),\, \psi\in \mathfrak{J}^l(V)$ 이고 $\text{Alt}(\phi) = 0$ 이면 $\text{Alt}(\phi \otimes \psi) = \text{Alt}(\psi \otimes \phi)=0$ 이다.

($2$) $\text{Alt}\left(\text{Alt}(\omega \otimes \eta) \otimes \zeta\right) = \text{Alt}(\omega \otimes \eta \otimes \theta) = \text{Alt}(\omega \otimes \text{Alt}(\eta \otimes \zeta))$

($3$) $\omega\in \Omega^k(V),\, \eta\in \Omega^l(V),\, \zeta \in \Omega^m(V)$ 일 때 다음이 성립한다.

$$
(\omega \wedge \eta ) \wedge \zeta = \omega \wedge (\eta \wedge \zeta) = \dfrac{(k+l+m)!}{k!\,l!\, m!} \text{Alt}(\omega \otimes \eta \otimes \zeta)
$${#eq-CM_basic_properties_of_wedge_product_3}
:::

</div>

::: {.proof}
($1$)

$$
\begin{aligned}
(k+l)! &\text{Alt}(\phi\otimes \psi)(v_1,\ldots,\,v_{k+l}) \\[0.3em] 
&= \sum_{\sigma \in S_{k+l}} \text{sgn}(\sigma)\cdot \phi(v_{\sigma(1)},\ldots,v_{\sigma(k)})\cdot \psi(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)})
\end{aligned}
$$ {#eq-prp_CM_basic_properties_of_wedge_product_3_1}

여기서 $G = \{\sigma \in S_{k+l} : \sigma(k+i)= k+i,\, i=1,\ldots, l\}$ 이라고 하자. 즉 $\sigma \in G$ 이면 $\sigma(k+i) = k+i$ 이다.

$$
\begin{aligned}
\sum_{\sigma\in G} \text{sgn}(\sigma) &\cdot \phi(v_{\sigma(1)},\ldots,v_{\sigma(k)})\cdot \psi(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)}) \\[0.3em]
&=\left[\sum_{\tau\in S_k} \text{sgn}(\tau) \cdot \phi(v_{\tau (1)},\ldots,v_{\tau(k)})\right] \cdot \psi(v_{k+1},\ldots,v_{k+l}) \\[0.3em]
&= k! \text{Alt}(\phi) \cdot \psi(v_{k+1},\ldots,v_{k+l}) = 0
\end{aligned}
$$

이다. $\sigma_0 \in S_{k+l}-G$ 에 대해 $G\sigma_0 =\{\sigma' \cdot \sigma_0 : \sigma' \in G\}$ 라고 하자. 그리고 $i=1,\ldots,k+l$ 에 대해 $u_{i}=v_{\sigma_0(i)}$ 라고 하자. 이로부터

$$
\begin{aligned}
\sum_{\sigma \in G\sigma_0} \text{sgn}(\sigma) & \cdot \phi(v_{\sigma(1)},\ldots,v_{\sigma(k)})\cdot \psi(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)}) \\[0.3em]
&= \left[\text{sgn}(\sigma_0) \cdot \sum_{\sigma' \in S(k)} \text{sgn}(\sigma') \cdot \phi\left(u_{\sigma'(1)},\ldots,\,u_{\sigma'(k)}\right)\right]\cdot \psi(u_{k+1},\ldots,u
_{k+l}) \\[0.3em]
&=\text{sgn}(\sigma_0) \cdot \text{Alt}(\phi)\cdot \psi(u_{k+1},\ldots,u_{k+l}) = 0
\end{aligned}
$$

이다. $S_{k+l}$ 은 군이며 $G$ 는 $S_{k+l}$ 의 부분군이다. 따라서 $S_{k+l}$ 은 서로소인 $G$ 에 대한 오른쪽 잉여류(left cosets) 로 분할되며 각 잉여류는 같거나 서로소이다. $\sigma_0$ 는 $S_{k+l}$ 에 속하지만 $G$ 에 속하지 않는 임의의 원소이므로 @eq-prp_CM_basic_properties_of_wedge_product_3_1 은 $0$ 임을 알 수 있다.

($2$) @prp-CM_basic_properties_of_alt_function ($3$) 으로부터 

$$
\text{Alt}\left(\text{Alt}(\eta \otimes \zeta) - \eta \otimes \zeta\right) =0
$$

임을 안다. ($1$) 로부터

$$
\begin{aligned}
0 &= \text{Alt}\left(\omega \otimes \left[ \text{Alt}(\eta \otimes \zeta) - \eta \otimes \zeta\right]\right) \\[0.3em]
&= \text{Alt} (\omega \otimes \text{Alt}(\eta \otimes \zeta)) - \text{Alt}(\omega \otimes \eta \otimes \zeta)
\end{aligned}
$$

이다. 즉 $\text{Alt} (\omega \otimes \text{Alt}(\eta \otimes \zeta)) = \text{Alt}(\omega \otimes \eta \otimes \zeta)$ 이다. 다른 등호도 같은 방법으로 보일 수 있다.

($3$) $(\omega \wedge \eta)\wedge \zeta$ 에 대해서는 아래와 같이 보일 수 있다. 나머지는 비슷한 방법으로 보일 수 있다.

$$
\begin{aligned}
(\omega \wedge \eta)\wedge \zeta &= \dfrac{(k+l+m)!}{(k+l)!\, m!} \text{Alt}((\omega \wedge \eta) \otimes \zeta) \\[0.3em]
&= \dfrac{(k+l+m)!}{(k+l)!\, m!} \dfrac{(k+l)!}{k!\,l!} \text{Alt}((\omega \otimes \eta) \otimes \zeta) \qquad \square
\end{aligned}
$$

:::

</br>

위의 명제 ($3$) 으로부터 $(\omega \wedge \eta) \wedge \zeta$ 와 $\omega \wedge (\eta \wedge \zeta)$ 가 같기 때문에 $\omega \wedge \eta \wedge \zeta$ 와 같이 쓸 수 있다는 것을 알 수 있다. 또한 $\omega_1 \wedge \omega_2 \wedge\cdots \wedge \omega_n$ 도 이와 같이 정의 할 수 있다는 것을 안다. 


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_basis_of_alternating_tensor_space}

벡터공간 $V$ 의 기저 $(e_1,\ldots,e_n)$ 와 이 기저에 대한 쌍대기저 $\varphi_1,\ldots,\,\varphi_n$ 에 대해 아래 집합이 $\Omega^k(V)$ 의 기저이다.

$$
\{ \varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k} : 1 \le i_1 <i_2 < \cdots < i_k \le n\}.
$$

또한 

$$
\dim \left(\Omega^k(V)\right) = \begin{pmatrix} n \\k \end{pmatrix} = \dfrac{n!}{k!\, (n-k)!}
$$ {#eq-CM_dimension_of_alternating_k_tensor_space}

이다. 

:::

</div>

::: {.proof}

$\omega \in \Omega^k(V) \subset \mathfrak{J}^k(V)$ 에 대해

$$
\omega = \sum_{i_1,\ldots,\,i_k} a_{i_1,\ldots,i_k} \left[\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k}\right]
$$

로 쓸 수 있다. $\omega = \text{Alt}(\omega)$ 이므로

$$
\omega = \text{Alt}(\omega) = \sum_{i_1,\ldots,i_k} a_{i_1,\ldots,i_k} \text{Alt}(\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k})
$$

이다. $\text{Alt}(\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k})$ 는 @eq-CM_basic_properties_of_wedge_product_3 에 의해
$\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k}$ 의 상수배이다. 따라서 $\{\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k}\}$ 는 $\Omega^k(V)$ 를 span 한다. 이제 이 집합이 선형 독립임을 보이자.

$$
\sum_{i_1,\ldots,i_k =1}^n a_{i_1,\ldots,i_k}(\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k})=0
$$

라고 하자. $(e_{j_1},\ldots,e_{j_k})$ 에 적용시켜보면 모든 $a_{\ldots}=0$ 이다(@exr-CM_spivak_4_1 ($a$)). 따라서 선형 독립이다. 

$\dim \left(\Omega^k(V)\right)$ 는 가능한 $\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k}$ 의 개수이며 $1 \le i_1 < \cdots < i_k \le n$ 이므로 차원에 대해 @eq-CM_dimension_of_alternating_k_tensor_space 이 성립한다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-CM_alternating_tensor_and_determinant}

$n$ 차원 벡터공간에 대해 $\Omega^n(V)$ 에 속하는 텐서는 행렬식의 상수배이다.

:::
</div>

::: {.proof}
$\dim (V)=n$ 이라면 $\Omega^n(V)$ 는 1차원이며 따라서 ($i$) $\omega$ 는 어떤 $0$ 이 아닌 값의 배수이며 ($ii$) 모든 교대 $n$-텐서는 정해진 기저 $v_1,\ldots,\,v_n$ 에 대한 쌍대 함수 $\varphi_1,\ldots,\varphi_n$ 와 상수 $a$ 에 대해

$$
\omega = a \cdot \left(\varphi_1 \wedge \cdots \wedge \varphi_n\right)
$$

꼴임을 안다. $\omega$ 에 속하는 함수가 행렬식이므로 우리는 $\omega$ 가 행렬식의 배수임을 안다. $\square$

:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_alternating_tensor_and_determinant}

$v_1,\ldots,v_n$ 이 $V$ 의 기저이고 $\omega \in \Omega^n(V)$ 라고 하자. $i=1,\ldots,\,n$ 에 대해 $\displaystyle u_i = \sum_{j=1}^n a_{ij}v_j$ 일 때 다음이 성립한다.

$$
\omega (u_1,\ldots,u_n) = \det (a_{ij})\cdot \omega (v_1,\ldots,v_n)
$$

:::

</div>

::: {.proof}

$\eta \in \mathfrak{J}^n(\R^n)$ 을 아래와 같이 정의하자.

$$
\eta ( (a_{11},\ldots,a_{1n}),\ldots,(a_{n1},\ldots,a_{nn})) := \omega \left(\sum_{j=1}^n a_{1j}v_j,\ldots,\sum_{j=1} ^na_{nj}v_j\right).
$$

$\eta\in \Omega^n(\R^n)$ 이므로 @cor-CM_alternating_tensor_and_determinant 에 따라 $\eta = \lambda \cdot \det$ 이다. $\eta(e_1,\ldots,e_n) = \lambda \cdot \det (I_n)= \lambda$ 이며 $\eta(e_1,\ldots,e_n) = \omega (v_1,\ldots,v_n)$ 이므로 주어진 식이 성립한다. $\square$

:::

</br>

### 부피 요소와 벡터곱 {#sec-CM_volume_element_and_cross_product}

#### **방향과 부피요소**
@thm-CM_alternating_tensor_and_determinant 에 따라 $0$ 이 아닌 $\omega \in \Omega^n(V)$ 는 $V$ 의 기저 $(v_1,\ldots,\,v_n)$ 를 $\omega$ 함수값이 양수인 것과 음수인 두 집합으로 분할한다. $V$ 의 두 기저 $(u_i)$ 와 $(v_j)$ 사이에 $u_i = \sum_j a_{ij}v_j$ 의 관계가 있을 때 $\det(a_{ij})>0$ 일 때에만 두 기저가 같은 집합에 속한다. 이 두 집합 가운데 하나를 벡터공간 $V$ 의 **방향 (orientation)** 으로 정할 수 있다. 기저 $(v_1,\ldots,v_n)$ 이 속한 방향을 $[v_1,\ldots,v_n]$ 으로 표기하며 반대 방향을 $-[v_1,\ldots,v_n]$ 으로 표기한다. 특별히 $\R^n$ 에서는 표준기저에 대한 방향, 즉 $[e_1,\ldots,e_n]$ 을 **정방향(usual orientation)** 이라고 한다. 

벡터공간에 어떤 내적 $T:V\times V \to \R$ 이 정해졌다고 하자. 그리고 이 내적에 대한 두 정규직교기저 $(e_i)$ 와 $(f_j)$ 
사이에는 어떤 직교행렬 (orthogonal matrix) $U$ 에 대해 $e_i = U f_i$ 의 관계가 있다는 것을 안다. 직교행렬은 $UU^T=I$ 이므로 $\det(U)= \pm 1$ 이다. 만약 $V$ 의 방향 $\mu$ 가 정해졌다면 정규직교기저 $(e_1,\ldots,e_n)$ 에 대해 $\omega (e_1,\ldots,e_n)=1$ 이 되도록 $\omega\in \Omega^n(V)$ 를 유일하게 정할 수 있다. 이 유일한 $\omega$ 를 내적 $T$ 와 방향 $\mu$ 에 의해 결정되는 **부피 요소 (volume element)** 라고 한다. $\R^n$ 에서 $\det$ 는 $\R^n$ 의 스칼라곱과 정방향에 의해 결정된 부피 요소와 같으며 $|\det (e_1,\ldots,e_n)|$ 은 원점과 $e_1,\ldots,\,e_n$ 에 의해 결정되는 다차원 평행육면체(parallelipiped) 의 부피이다.

</br>

#### **벡터곱**

이제 $\R^n$ 에서의 **벡터곱(cross product)** 에 대해 알아보자. 정해진 $v_1,\ldots,\,v_{n-1} \in \R^n$ 에 대해 $\phi(u) := \det(v_1,\ldots,\,v_{n-1},u)$ 라고 하면 $\phi \in \Omega^1(\R^n)$ 이다. $\det$ 의 성질에 의해 $\phi (u)$ 는 $V$ 에서 정해진 선형 범함수(linear functinal) 이며, 따라서 소위 리스의 표현정리 (Riesz representation theorem) 에 의해 $\phi (u)=\langle u,\,w \rangle$ 을 만족하는 $w\in V$ 가 유일하게 존재한다. 이 $w$ 를 $v_1 \times \cdots \times v_{n-1}$ 로 표기하고 $v_1,\ldots,v_{n-1}$ 의 **벡터곱** 이라고 한다. 즉 모든 $u \in \R^n$ 에서

$$
\phi(u) = \langle u,\,  w \rangle = \det \left( v_1,\ldots,\,v_{n-1},\, u\right)
$$ {#eq-CM_inner_product_and_cross_product}

를 만족하는 $w$ 를 $v_1 \times \cdots \times v_{n-1}$ 로 표기한다.

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-CM_magnitude_of_cross_product}

#### 벡터곱의 기본 성질
</br>

($1$) 행렬식의 성질로부터 $w = v_1\times \cdots \times v_{n-1}$ 일 때 $\langle v_i,\, w\rangle = 0$ 임을 알 수 있다.
 
($2$) $\R^n$ 에서의 표준기저 $(e_1,\ldots,\,e_n)$ 에 대해 $e_1 \times \cdots \times e_{n-1}=e_n$ 이다.

($3$) @eq-CM_inner_product_and_cross_product 에서 $u=v_1\times \cdots \times v_{n-1}$ 을 넣으면 다음을 얻는다.

$$
\|v_1 \times \cdots \times v_{n-1}\|^2 = \det (v_1,\ldots,\,v_{n-1},\, v_1\times \cdots \times v_{n-1})
$$ {#eq-CM_norm_of_cross_product}


:::

</div>

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_cross_product}

벡터곱에 대해 다음이 성립한다.

$$
\begin{aligned}
v_{\sigma(1)}\times \cdots \times v_{\sigma(n-1)} &= \text{sgn}(\sigma)\cdot (v_1\times \cdots \times v_{n-1}), \\[0.3em]
v_1\times \cdots \times (av_i)\times \cdots \times v_{n-1} &= a\cdot (v_1\times \cdots \times v_{n-1}), \\[0.3em]
v_1 \times \cdots \times (v_i + v'_i) \times \cdots \times v_{n-1} &=v_1 \times \cdots \times v_i \times \cdots \times v_{n-1} \\[0.3em]
&\, + v_1 \times \cdots \times v'_i \times \cdots \times v_{n-1} 
\end{aligned}
$$ {#eq-CM_basic_properties_of_cross_product}
:::

</div>

::: {.proof}

행렬식의 성질에 의해 쉽게 보일 수 있다.
:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_1}

#### Spivak 4.1

$\R^n$ 의 표준기저 $(e_1,\ldots,\,e_n)$ 와 이 기저에 대한 쌍대기저 $(\varphi_1,\ldots,\,\varphi_n)$ 을 생각한다.

($a$) $\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k} (e_{i_1},\cdots,e_{i_k})=1$ 임을 보여라. 

($b$) $\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k} (v_1,\ldots,\,v_k)$ 는 행렬 $\begin{bmatrix} v_1 \\ \vdots \\ v_k\end{bmatrix}$ 에서 $i_1,\ldots,\,i_k$ 행을 취한 $k\times k$ 행렬의 행렬식임을 보여라.

:::

</div>
::: {.solution}

($a$) 

$$
\begin{aligned}
\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k} &(e_{i_1},\cdots,e_{i_k}) = k! \cdot \text{Alt}(\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k})(e_{i_1},\cdots,e_{i_k}) \\[0.3em]
&= \dfrac{k!}{k!} \sum_{\sigma \in S_k} \text{sgn}(\sigma)\cdot (\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k})(e_{\sigma(i_1)},\cdots,e_{\sigma(i_k)}) \\[0.3em]
&= \sum_{\sigma\in S_k} \text{sgn}(\sigma) \delta_{i_1,\sigma(i_1)} \cdots \delta_{i_k,\sigma(i_k)} = 1
\end{aligned}
$$

($b$) $v_j$ 의 $i$ 번째 성분을 $v_{ji}$ 라고 하자. 

$$
\begin{aligned}
\left(\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k}\right) & (v_1,\ldots,\,v_k) = \sum_{\sigma\in S_k} \text{sgn}(\sigma) \cdot (\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k})(v_1,\ldots,\,v_k) \\[0.3em]
&=\sum_{\sigma\in S_k} \text{sgn}(\sigma) v_{1\sigma(i_1)}\cdots v_{k\sigma(i_k)}
\end{aligned} 
$$

이므로 행렬식의 정의에 의해 문제에서 제시한 행렬의 행렬식임을 알 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_2}

#### Spivak 4.2

$F \in \mathcal{L}(V)$ 이고 $\dim(V)=n$ 일 때 $F^\ast :\Omega^n (V) \to \Omega^n (V)$ 는 어떤 상수 $c$ 에 대한 곱임을 보여라. 그리고 $c=\det (F)$ 임을 보여라.

:::

</div>

::: {.solution}

$\Omega^n(V)$ 는 1차원 벡터공간이며, 1차원 벡터공간 사이의 선형사상은 어떤 성분의 상수배이다. 즉 $F^\ast(\omega) = c \omega$ 이다. 그리고 $\det \in \Omega^n(V)$ 이므로 $c=\det F$ 로 놓을 수 있다.


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_3}

#### Spivak 4.3

$\omega \in \Omega^n (V)$ 가 내적 $T$ 와 방향 $\mu$ 에 의해 결정되는 부피 요소이고 $u_1,\ldots,u_n\in V$ 일 때 다음이 성립함을 보여라.

$$
\left|\omega (u_1,\ldots,\,u_n)\right| = \sqrt{\det (g_{ij})},\qquad \text{where }g_{ij}=T(u_i,u_j).
$$

:::

</div>

::: {.solution}

$(e_1,\ldots,\,e_n)$ 이 $T$ 에 대한 정규직교기저이고 $u_i =\sum_j A_{ij}e_j$ 라 하자. 

$$
\begin{aligned}
g_{ij}=T(u_i,u_j)&=\sum_{k, l} A_{ik}A_{jl}T(e_k, e_l)= \sum_k A_{ik}A_{jk}= \left(AA^T\right)_{ij} 
\end{aligned}
$$ 

이며 $\det(A)=\det(A^T)$ 이므로 $\det (g_{ij}) = (\det(A))^2$ 이다. 따라서 다음이 성립한다.

$$
|\omega(u_1,\ldots,u_n)|= |\det(A)| \cdot \underbrace{|\det(e_1,\ldots,e_n)|}_{=1} = \sqrt{\det(g_{ij})}.
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_4}

#### Spivak 4.4

벡터공간 $V$ 에서 $\omega$ 가 내적 $T$ 와 방향 $\mu$ 에 의해 결정되 는 부피 요소이고 $F :\R^n \to V$ 가 동형사상이며 $F^\ast (T) = \langle\,,\,\rangle$ 이고 $[F(e_1),\ldots, F(e_n)]=\mu$ 일 때 $F^\ast \omega = \det$ 임을 보여라.

:::

</div>

::: {.solution}

$(e_1,\ldots,\,e_n)$ 이 $\R^n$ 의 표준기저이며 $v_i = F(e_i)$ 라고 하자. $F^\ast (T) = \langle \,,\,\rangle$ 로부터 $F^\ast T (e_i,\,e_j) = \langle e_i,e_j\rangle = \delta_{ij}$ 이며 $F^\ast T(e_i,e_j)= T(F(e_i),F(e_j))=T(v_i,v_j)$ 이므로 $F$ 는 내적을 보존하는 isometry 임을 안다. 따라서 $\det (F)=\pm 1$ 이며 방향을 보존하므로 $\det (F) = 1$ 이다. 


$\omega$ 가 $V$ 의 정규직교기저 $u_1,\ldots,\,u_n$ 에 대해 $T,\, \mu$ 에 의해 결정되는 부피요소라고 하자. 이 때
$$
\begin{aligned}
\left(F^\ast (\omega)\right)(v_1,\ldots,v_n) &=\omega (F(v_1),\ldots,F(v_n)) \\[0.3em]
&= \underbrace{\det (F)}_{=1} \cdot \det (v_1,\ldots,v_n) = \det (v_1,\ldots,v_n)
\end{aligned}
$$

이므로 $F^\ast \omega = \det$ 이다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_5}

#### Spivak 4.5

$P:[0,\,1] \to (\R^n)^n$ 이 연속이며 각각의 $(\bf{p}_1(t),\ldots,\,\bf{p}_n(t))$ 가 $\R^n$ 의 기저 일 때 $[\bf{p}_1(0),\ldots,\bf{p}_n(0)] = [\bf{p}_1(1),\ldots,\,\bf{p}_n(1) ]$ 임을 보여라.

:::

</div>

::: {.solution}

$\det$ 도 연속이고 $P$ 도 연속함수이므로 $\det (P(t))$ 도 연속함수이다. $(\bf{p}_1,\ldots,\,\bf{p}_n(t))$ 가 $\R^n$ 의 기저이므로 선형 독립이고 따라서 $\det(P(t))\ne 0$ 이다. 즉 $t\in [0,\,1]$ 에 대해 $\det(P(t))>0$ 이거나 $\det(P(t))<1$ 이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_6}

#### Spivak 4.6

($a$) $v\in \R^2$ 일 때 $v\times$ 는 무엇인가?
 
($b$) $v_1,\ldots,v_{n-1}\in \R^n$ 이 선형 독립이라면 $[v_1,\ldots,v_{n-1},v_1 \times \cdots \times v_{n-1}]$ 은 정방향 임을 보여라.

:::

</div>

::: {.solution}

($a$) $v = (v_1,\,v_2)$, $\bf{z}=(z_1,\,z_2)$, $\bf{w}=(w_1,\,w_2)$ 라고 하자. 정의에 의해

$$
z_1w_1+z_2w_2 = v_1w_2 - v_2w_1
$$

이어야 하므로 $z_1=v_1,\, z_2 = -v_2$ 이다. 즉 $\bf{w} = (v_1,\,-v_2)$ 이다.

($b$) $\phi(u) = \det (v_1,\ldots,\,v_{n-1},\,u) = \langle u, w\rangle$ 가 $u\in \R^n$ 에 대해 성립한다. $v_1,\ldots,\,v_{n-1}$ 이 선형 독립이면 $v_1 \times \cdots \times v_{n-1}\ne 0$ 이며 $u=z=v_1 \times \cdots \times v_{n-1}$ 로 놓으면

$$
0 < \langle z,\,z\rangle = \det (v_1,\ldots,\,v_{n-1},\, v_1\times \cdots \times v_{n-1})
$$

이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_7}

#### Spivak 4.7

$0$ 이 아닌 모든 $\omega \in \Omega^n(V)$ 는 어떤 내적 $T$ 와 방향 $\mu$ 에 의해 정해지는 부피 요소 일 수 있음을 보여라.

:::

</div>

::: {.solution}

선형 독립인 $v_1,\ldots,\,v_n$ 과 그 쌍대함수 $\varphi_1,\ldots,\varphi_n$ 에 의해 $\omega = \varphi_1 \wedge \cdots \wedge \varphi_n \in \Omega^n(V)$ 가 정해진다. $u,\, w\in V$ 에 대해 $u=\sum_i a_i v_i,\, w=\sum_j b_jv_j$ 일 때 내적 $T(u,\,v) = \langle u,\,w\rangle = \sum_{i}a_ib_i$ 로 정의 할 수 있으며 $\omega (v_1,\ldots,\,v_n)=1$ 이므로 방향성도 정해진다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_8}

#### Spivak 4.8

$\omega\in \Omega^n(V)$ 가 부피 요소일 때 벡터곱 $v_1\times \cdots \times v_{n-1}$ 을 $\omega$ 를 이용해 표현하라.

:::

</div>

::: {.solution}

$(e_1,\ldots,\,e_n)$ 이 $V$ 의 기저라고 하자. $u = v_1\times \cdots \times v_{n-1}= \sum_i a_i e_i$ 라고 하면 
$$
\begin{aligned}
\omega (v_1,\ldots,\,v_{n-1},\,v_1\times \cdots \times v_{n-1}) &= \sum_{i=1}^n a_i \cdot \omega (v_1,\ldots,\,v_{n-1},\,e_i)
\end{aligned}
$$


이므로 

$$
v_1\times \cdots \times v_{n-1} = \sum_i \omega (v_1,\ldots,\,v_{n-1},\,e_i) e_i
$$

로 정할 수 있다.

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_9}

#### Spivak 4.9
$\R^3$ 에서의 벡터곱이 아래의 성질을 가짐을 보여라.

($a$) Levi-civita 기호 $\varepsilon_{ijk}$ 에 대해 $\bf{e}_i \times \bf{e}_j = \varepsilon_{ijk} \bf{e}_k$,

($b$) $\bf{v}\times \bf{w} = (v_2w_3 - v_3w_2) \bf{e}_1 + (v_3w_1 - v_1w_3)\bf{e}_3 + (v_1w_2 - v_2w_1)\bf{e}_3$, 

($c$) $\theta = \angle (\bf{v},\bf{w})$ 에 대해 $\|\bf{v} \times \bf{w}\| = \|\bf{v}\| \cdot \|\bf{w}\| \cdot |\sin \theta|$ 이며 $\langle \bf{v} \times \bf{w},\bf{v}\rangle = 0$,

($d$) $\begin{gather} \langle \bf{v},\,\bf{w}\times \bf{z}\rangle = \langle \bf{w},\,\bf{z}\times \bf{v}\rangle = \langle \bf{z},\, \bf{v}\times \bf{w}\rangle, \\[0.3em]
\bf{v}\times (\bf{w}\times \bf{z}) = \langle \bf{v},\,\bf{z}\langle \bf{w} - \langle \bf{v},\,\bf{w}\rangle \bf{z}\\[0.3em]
(\bf{v}\times \bf{w}) \times \bf{z} = \langle \bf{v},\,\bf{z}\rangle \bf{w} - \langle \bf{w},\,\bf{z}\rangle \bf{v}.
\end{gather}$

($e$) $\|\bf{v}\times \bf{w}\| = \sqrt{\langle \bf{v}\,\bf{v}\rangle \langle \bf{w},\,\bf{w}\rangle - \langle \bf{v},\,\bf{w}\rangle^2}$.

:::

</div>

::: {.solution}

trivial
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_10}

#### Spivak 4.10

$u_1,\ldots, u_{n-1}\in \R^n$ 이며 $g_{ij}= \langle u_i,u_j\rangle$ 일 때 다음이 성립함을 보여라.

$$
\|u_1 \times \cdots \times u_{n-1}\| = \sqrt{\det (g_{ij})}.
$$

:::

</div>

::: {.solution}


$u_n = u_1 \times \cdots \times u_{n-1}$ 이라고 하면 @eq-CM_norm_of_cross_product 에 따라 

$$
\|u_n\|^2 = \|u_1\times \cdots \times u_{n-1}\|^2 = \det (u_1,\ldots,\,u_{n-1},\,u_n)
$$

이다. $u_1,\ldots,\,u_{n-1}$ 이 선형 종속일 경우는 $u_1 \times \cdots \times u_{n-1}=0$ 이며 $\det (g_{ij})=0$ 이므로 성립하므로 이제 $u_1,\ldots,u_{n-1}$ 이 선형 독립일 경우만 생각한다. 주어진 식의 $g_{ij}$ 는 $1\le i,\,j \le n-1$ 이지만 이를 $u_1,\ldots,\,u_n$ 까지 확장하여 $\tilde{g}_{ij} = \langle u_i,\,u_j\rangle$ 이라고 하자. $\langle u_i,\,u_n\rangle = \delta_{in}\|u_n\|^2$ 이므로

$$
\tilde{g}_{ij} = \begin{bmatrix} [g_{ij}] & \bf{0} \\ \bf{0} & \|u_n\|^2\end{bmatrix}
$$

이다. 따라서 $\det(\tilde{g}_{ij}) = \|u_n\|^2 \det (g_{ij})$ 이다. @exr-CM_spivak_4_3 로부터

$$
\omega (u_1,\ldots,u_n) = \|u_n\|^2 = \sqrt{\det (\tilde{g}_{ij})} = \|u_n\|\sqrt{\det (g_{ij})}
$$

이므로

$$
\|u_n\| = \|u_1 \times \cdots \times u_{n-1}\| = \sqrt{\det (g_{ij})}.
$$


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_11}

#### Spivak 4.11

내적벡터공간 $V$ 에서 $L\in \mathcal{L}(V)$ 에 대해 모든 $x,\,y\in V$ 에서 $\langle x,\,L(y)\rangle = \langle L(x),\,y\rangle$ 일 때 이 $L$ 을 에르미트 연산자라고 한다. $v_1,\ldots,\,v_n$ 이 정규직교기저이고 $A=(a_{ij})$ 가 이 기저에 대한 $L$ 의 행렬 이라면 $a_{ij} = a_{ji}$ 임을 보여라.

:::
</div>

::: {.solution}

모든 $x,\,y\in V$ 에 대해 성립하므로 $v_i,\,v_j$ 에 대해서도 성립해야 한다.
$$
\begin{aligned}
\langle v_i,\, L(v_j)\rangle &= \left\langle v_i, \sum_k a_{jk}v_k\right\rangle = \sum_{k} a_{jk} \langle v_i,\,v_k\rangle = a_{ji}, \\[0.3em]
\langle L(v_i),\,v_j\rangle &= \left\langle \sum_k a_{ik}v_k,\, v_j\right\rangle = \sum_k a_{ik} \langle v_k,\,v_j\rangle = a_{ij}
\end{aligned}
$$ 

이므로 $a_{ji}=a_{ij}$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_12}

#### Spivak 4.12

$F_1,\ldots,\,F_{n-1} : \R^m \to \R^n$ 에 대해 $F_1 \times \cdots \times F_n : \R^m \to \R^n$ 을 아래와 같이 정의한다.

$$
(F_1 \times \cdots \times F_n)(p) = F_1(p)\times \cdots \times F_n(p).
$$

$F_1,\ldots,\,F_{n-1}$ 이 미분가능 할 때 @exr-CM_spivak_2_14 를 이용하여 $D(F_1 \times \cdots \times F_{n-1})$ 을 구하라.

:::
</div>

::: {.solution}

$F :(\R^m)^{n-1} \to \R^n$ 을 아래와 같이 정의하면 다중선형함수이다.

$$
F(x_1,\ldots,x_{n-1}) = x_1\times \cdots \times x_{n-1}.
$$

$$
\begin{aligned}
(F_1 \times \cdots &\times F_{n-1})'(p)(x) \\[0.3em]
&= (F\circ (F_1,\ldots,\,F_{n-1}))'(p)(x) \\[0.3em]
&= F'(F_1(p),\ldots,\,F_{n-1}(p)) \circ (F'_1(p),\ldots,\,F'_{n-1}(p)) (x) \\[0.3em]
&= \sum_{i=1}^{n-1} \left[F_1(p) \times \cdots \times F_{i-1}(p) \times F'_{i}(p) \times F_{i+1}(p)\times \cdots \times F_{n-1}(p)\right] (x)
\end{aligned}
$$

:::

</br>

## 장과 형식 

### 탄젠트 공간과 벡터장 {#sec-CM_tangent_space_and_vector_field}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_tangent_space}

#### 탄젠트 공간

정해진 $\bf{p}\in \R^n$ 에 대해 $\bf{p}$ 에서의 **탄젠트 공간 (tangent space)** $T_\bf{p}(\R^n)$ 는 

$$
T_\bf{p}({\R^n}) = \{(\bf{p},\,\bf{x}) : \bf{x}\in \R^n\}
$$

에 대해 아래의 연산이 정의된 구조이다.

$$
\begin{aligned}
(\bf{p},\,\bf{x}) + (\bf{p},\,\bf{y}) &= (\bf{p}, \bf{x}+\bf{y}),\\[0.3em]
a\cdot (\bf{p},\,\bf{x}) &= (\bf{p},\,a\bf{x}).
\end{aligned}
$$

$T_\bf{p}(\R^n)$ 의 벡터 $(\bf{p},\bf{v})$ 는 흔히 $\bf{v}_\bf{p}$ 혹은 $(\bf{v})_\bf{p}$ 와 같이 표기하기도 한다.
::: 
:::

다음은 쉽게 보일 수 있다.


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_tangent_space_as_a_vector_space}

$T_\bf{p}(\R^n)$ 는 $(\bf{p},\,\bf{0})$ 을 영벡터로 하는 벡터공간이다.
:::
</div>

</br>

일반적인 $\R^n$ 의 벡터는 원점으로부터의 화살표로 표현되는 경우가 많다. 이와 유사하게 $T_\bf{p}(\R^n)$ 의 벡터 $(\bf{p},\bf{v})$ 는 $\bf{p}$ 를 시작으로 $\bf{p}+\bf{v}$ 를 향하는 화살표로 표현된다. 또한 내적과 방향의 경우 $\R^n$ 과 같이 정의 할 수 있으며 이를 통상 내적, 통상 방향이라고 한다.


::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_usual_inner_product_and_orientation}

#### 통상 내적, 통상 방향

$T_\bf{p}(\R^n)$ 에서의 내적 $\langle\,,\,\rangle_\bf{p}$ 을 

$$
\langle (\bf{p},\bf{u}), (\bf{p},\bf{v})\rangle_\bf{p}= \langle \bf{u},\bf{v}\rangle
$$

와 같이 정의할 때 이 내적을 **통상 내적 (usual inner product)** 라고 하며 방향을 

$$
[(\bf{v}_1)_\bf{p},\ldots,(\bf{v}_n)_\bf{p}] = [\bf{v}_1,\ldots,\bf{v}_n]
$$

으로 정의 할 때 이 방향을 **통상 뱡향 (usual orientation)** 이라고 한다.

::: 
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_vector_field}

#### 벡터장

$F:\R^n \to T_\bf{p}(\R^n)$ 를 $\R^n$ 에서의 **벡터장 (vector field)** 라고 한다. $F(\bf{p})$ 의 $i$ 번째 성분을 $f_i(\bf{p})$ 로 표기한다.

$F,\,G$ 가 벡터장이고 $f:\R^n \to \R$ 함수일 때 연산을 아래와 같이 정의한다.

$$
\begin{aligned}
(F+G)(\bf{p}) &:= F(\bf{p}) + F(\bf{p}), \\[0.4em]
\langle F,\, G\rangle (\bf{p}) &: = \langle F(\bf{p}),\, G(\bf{p})\rangle, \\[0.4em]
(f\cdot F)(\bf{p}) &:= f(\bf{p})F(\bf{p}), \\[0.4em]
(F \times \cdots \times G) (\bf{p}) &:= F(\bf{p})\times \cdots \times G(\bf{p}).
\end{aligned}
$$

::: 
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_nabla_operator}

#### Nabla 연산자

$\R^n$ 에서 nabla 연산자 $\nabla$ 를 아래와 같이 정의한다.

$$
\nabla := \sum_{i=1}^n \bf{e}_i \bf{\cdot}D_i.
$$ {#eq-CM_nabla_operator}

::: 
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_divergence_and_curl}

#### Divergence 와 Curl

$\R^n$ 에서의 벡터장 $F$ 에 대해 $\sum_{i=1}^n D_i F_i(\bf{p})$ 를 $F$ 에 대한 **divergence** 라고 하며 $\nabla \cdot F$ 혹은 $\text{div} \,F$ 로 표기한다. $n=3$ 인 경우 아래와 같이 정의된 $\text{curl}\,F(\bf{p})$ 를 $F$ 에 대한 **curl** 이라고 하며 $\nabla \times F$ 로도 표기한다.

$$
\text{curl}\, F(\bf{p}) := (D_2f_3 - D_3f_2)(\bf{e}_1)_\bf{p} + (D_3f_1 - D_1f_3)(\bf{e}_2)_\bf{p} + (D_1f_2-D_2f_1)(\bf{e}_3)_\bf{p}.
$$

::: 
:::

</br>

### 미분 형식 {#sec-CM_differential_form}

$\R^n$ 과 $T_\bf{p}(\R^n)$, 벡터함수와 벡터장과 같이 탄젠트 공간에서 정의된 $k$-form 을 정의 할 수 있다.

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_differential_form}

#### 미분 형식

$\omega (\bf{p})\in \Omega^k(T_\bf{p}(\R^n))$ 를 $\R^n_\bf{p}$ 에서의 $k$-형식, 혹은 **미분 형식(differential form)** 이라고 한다. 표준 기저 $(\bf{e}_i)_\bf{p}$ 에 대한 쌍대 기저를 $\varphi_i (\bf{p})$ 라고 할 때 $k$-형식 $\omega(\bf{p})$ 은 아래의 형태이다.

$$
\omega(\bf{p}) = \sum_{i_1<\cdots <i_k} \omega_{i_1,\ldots,\,i_k}(\bf{p})\cdot \left[\varphi_{i_1}(\bf{p}) \wedge \cdots \wedge \varphi_{i_k}(\bf{p})\right]
$$

::: 
:::

</br>

각각의 $\omega_{i_1,\ldots,\,i_k}(\bf{p})$ 가 연속이거나 미분가능 할 때 $\omega (\bf{p})$ 를 연속이거나 미분가능하다고 한다. 여기서 우리는 벡터장이나 $k$-형식이 미분가능하다고 할 때 $C^\infty$ 를 의미한다. 

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-CM_0_form_and_1_form}

#### $0$-형식 과 $1$-형식

$f:\R^n \to \R$ 은 $0$-형식이다. $1$-형식은 선형 변환이다. 

:::
</div>


</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_arithmatic_of_differential_form}

#### 미분 형식의 연산

$k$-형식 $\omega,\, \zeta$, $m$-형식 $\eta$, 스칼라장 $f$ 에 대해 연산이 아래와 같이 정의된다.

$$
\begin{aligned}
\omega (\bf{p}) + \zeta (\bf{p}) &:= \sum_{i_1<\cdots <i_k} \left(\omega_{i_1,\ldots,\,i_k}(\bf{p}) + \zeta_{i_1,\ldots,\,i_k}(\bf{p})\right) \cdot \left[\varphi_{i_1}(\bf{p}) \wedge \cdots \wedge \varphi_{i_k}(\bf{p})\right], \\[0.3em]
(f \cdot \omega)(\bf{p})  &:=  \sum_{i_1<\cdots <i_k} \left(f(\bf{p}) \cdot \omega_{i_1,\ldots,\,i_k}(\bf{p}) \right)\cdot \left[\varphi_{i_1}(\bf{p}) \wedge \cdots \wedge \varphi_{i_k}(\bf{p})\right], \\[0.3em]
\omega (\bf{p})\wedge \eta (\bf{p}) &:= \sum_{i_1<\cdots <i_{k}} \sum_{j_1<\cdots <j_m} \omega_{i_1,\ldots,\,i_k}(\bf{p})\cdot \eta_{j_1,\ldots,j_m}(\bf{p}) \\[0.3em]
&\qquad\qquad  \qquad \qquad\cdot \left[\varphi_{i_1}(\bf{p}) \wedge \cdots \wedge \varphi_{i_k}(\bf{p}) \wedge \varphi_{j_1}(\bf{p}) \cdots \wedge \varphi_{j_m}(\bf{p})\right] 
\end{aligned}
$$

::: 
:::

</br>

### 형식과 미분 {#sec-CM_form_and_differentiation}


미분 가능한 함수 $f:\R^n \to \R$ 을 생각하자. 이런 함수를 **스칼라장 (scalar field)** 라고 한다. $Df(\bf{p})\in \Omega^1(T_\bf{p}(\R^n))$ 이므로 아래와 같이 미분과 관련된 1-형식을 정의 할 수 있다.

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_1_form}

#### 함수의 미분과 1차 형식

$f:\R^n \to \R$ 에 대해 $1$-형식 $df(\bf{p})$ 를 아래와 같이 정의한다. 

$$
df(\bf{p}) (\bf{v}_\bf{p}) := Df(\bf{p})(\bf{v}) = Df(\bf{p})\cdot \bf{v}.
$$ {#eq-CM_differential_1-form}

::: 
:::


$x_i :\R^n \to \R$ 을 $\bf{x}\in \R^n$ 의 $i$ 번째 성분을 반환하는 함수라고 하자. 이 함수는 선형함수이고 당연히 미분가능하다. 그렇다면 $x_i$ 의 1차 형식 $dx_i(\bf{p})$ 를 생각 할 수 있다. $T_{\bf{p}}(\R^n)$ 의 표준기저벡터 $(\bf{e}_j)_\bf{p}$ 에 대해 $dx_i(\bf{p})\left((\bf{e}_j)_\bf{p}\right) = \delta_{ij}$ 이므로 $dx_i (\bf{p})$ 는 $(\bf{e}_i)_\bf{p}$ 의 쌍대기저이다. 따라서 $k$-형식 $\omega(\bf{p})$ 는 다음과 같이 쓸 수 있다.

$$
\omega (\bf{p}) = \sum_{i_1< \cdots <i_k} \omega_{i_1,\ldots,i_k}(\bf{p})\cdot \left[ dx_{i_1}(\bf{p})\wedge \cdots \wedge dx_{i_k}(\bf{p})\right].
$$

탄젠트 공간을 지정하는 $(\bf{p})$ 는 표기의 편의상 생략되는 경우가 많다. 그렇다면 아래와 같이 표기된다.

$$
\omega = \sum_{i_1< \cdots <k_k} \omega_{i_1,\ldots,i_k}\cdot \left[ dx_{i_1} \wedge \cdots \wedge dx_{i_k} \right].
$$

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_differentiation_of_function_and_form}

$f:\R^n \to \R$ 이 미분가능할 때 다음이 성립한다.

$$
df = D_1 f \cdot dx_1 + \cdots + D_n f \cdot dx_n.
$$

:::
</div>

::: {.proof}

$\displaystyle df(\bf{p})(\bf{v}_p) = Df(\bf{p}) \bf{\cdot}\bf{v} = \sum_{i=1}^n D_i f(\bf{p})\cdot v_i = \sum_{i=1}^n D_i f(\bf{p})\cdot \left(dx_i(\bf{p})(\bf{v}_p)\right). \square$
:::

</br>


::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_push_forward_and_pull_back}

#### Pull-back 과 Push-forward

미분가능한 함수 $F:\R^n \to \R^m$ 과 선형변환인 $F'(\bf{p}) \in \mathcal{L}(\R^n, \R^m)$ 을 생각하자. 아래와 같이 정의되는 선형변환 $F_\ast  \in \mathcal{L}(T_\bf{p}(\R^n),\, T_{F(\bf{p})}(\R^m)$ 을 $F$ 에 대한 **push-forward** 라고 한다.

$$
F_\ast (\bf{v}_p) := \left(F'(\bf{p})(\bf{v})\right)_{F(\bf{p})}
$$ {#eq-def_CM_push_forward}


이로부터 유도되는 선형변환 $F^\ast \in \mathcal{L}\left(\Omega^k\left(T_{F(\bf{p})}(\R^m)\right),\, \Omega^k\left(T_\bf{p}(\R^n)\right)\right)$ 아래와 같이 정의하고 이를 **pull-back** 이라고 한다. $\omega \in \Omega^k \left( T_{F(\bf{p})}(\R^m) \right)$ 에 대해

$$
(F^\ast \omega) (\bf{p}) := (F_\ast)^\ast (\omega (F(\bf{p})))
$$ {#eq-def_CM_pull_back}

이다. 그렇다면 
$$
\begin{aligned}
\left(F^\ast \omega\right)(\bf{p})(\bf{v}_1,\ldots,\bf{v}_k) &= (F_\ast)^\ast(\omega(F(\bf{p})))(\bf{v}_1,\ldots,\bf{v}_k) \\[0.3em]
&= \omega (F(\bf{p})) (F_\ast (\bf{v}_1),\ldots,\, F_\ast(\bf{v}_k)) \\[0.3em]
&= \omega (F(\bf{p})) \left( \left(F'(\bf{p})(\bf{v}_1)\right)_{F(\bf{p})},\ldots,\,\left(F'(\bf{p})(\bf{v}_k)\right)_{F(\bf{p})} \right)
\end{aligned}
$$

이다. 

:::
:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_properties_of_full_back}

$F:\R^n \to \R^m$, $F(\bf{x}) = \begin{bmatrix} f_1(\bf{x}) & \cdots f_m (\bf{x})\end{bmatrix}^T$ 이 미분가능할 때 다음이 성립한다.

&emsp;($1$) $\displaystyle F^\ast(dx_i) = \sum_{j=1}^n D_jf_i \cdot dx_i = \sum_{j=1}^n \dfrac{\partial f_i}{\partial x_j}\,dx_j$,

&emsp;($2$) $F^\ast (\omega_1 + \omega_2) = F^\ast(\omega_1)+ F^\ast (\omega_2)$, 

&emsp;($3$) $F^\ast (g \cdot \omega) = (g\circ F) \cdot F^\ast \omega$, 

&emsp;($4$) $F^\ast (\omega \wedge \eta) = F^\ast \omega \wedge F^\ast \eta$.

:::
</div>

::: {.proof}

($1$) $dx_i$ 는 1-형식 이므로

$$
\begin{aligned}
F^\ast (dx_i) (\bf{p})(\bf{v}_p) &= dx_i(F(\bf{p})) \left(\left(F'(\bf{p})(\bf{v}_\bf{p})\right)_{F(\bf{p})}\right) \\[0.3em]
&= dx_i(F(\bf{p}))\left(\sum_{j=1}^n v_j D_jf_1(\bf{p}),\ldots,\,\sum_{j=1}^n v_jD_j f_m (\bf{p})\right)_{F(\bf{p})} \\[0.3em]
&= \sum_{j=1}^n v_j D_jf_i (\bf{p}) = \sum_{j=1} D_j f_i (\bf{p}) \cdot dx_j(\bf{p})(\bf{v}_\bf{p}).
\end{aligned}
$$

($2$) $\omega_1,\,\omega_2 \in \Omega^k\left(T_{F(\bf{p})} (\R^m)\right)$ 라고 하자.

$$
\begin{aligned}
F^\ast (\omega_1 +\omega_2)&(\bf{p})\left((\bf{v}_1)_\bf{p},\ldots,(\bf{v}_k)_\bf{p}\right) \\[0.3em]
&=(\omega_1+\omega_2)(F(\bf{p}))\left(\left(F'(\bf{p})(\bf{v}_1)\right)_{F(\bf{p})},\ldots,\, \left(F'(\bf{p})(\bf{v}_k)\right)_{F(\bf{p})}\right) \\[0.3em]
&=\left[F^\ast(\omega_1)(\bf{p}) + F^\ast (\omega_2)(\bf{p})\right] \left((\bf{v}_1)_\bf{p},\ldots,(\bf{v}_k)_\bf{p}\right).
\end{aligned}
$$

($3$) 

$$
\begin{aligned}
F^\ast (g \cdot \omega)&(\bf{p})\left((\bf{v}_1)_\bf{p},\ldots,(\bf{v}_k)_\bf{p}\right)  \\[0.3em]
&= (g\cdot \omega)(F(\bf{p}))(F'(\bf{p})(\bf{v}_1)_{F(\bf{p})},\ldots,\,F'(\bf{p})(\bf{v}_k)_{F(\bf{p})}) \\[0.3em]
&= g(F(\bf{p})) \omega (F(\bf{p})) \left(\left(F'(\bf{p})(\bf{v}_1)\right)_{F(\bf{p})},\ldots,\,\left(F'(\bf{p})(\bf{v}_k)\right)_{F(\bf{p})}\right) \\[0.3em]
&= (g\circ F) \cdot (F^\ast \omega)(\bf{p}) \left((\bf{v}_1)_\bf{p},\ldots,(\bf{v}_k)_\bf{p}\right).
\end{aligned}
$$

($4$) @prp-CM_basic_properties_of_wedge_product_2 와 같은 방법으로 증명 할 수 있다. 

$$
\begin{aligned}
F^\ast (\omega \wedge \eta)&(\bf{p})((\bf{v}_1)_\bf{p},\ldots, (\bf{v}_{k+l})_\bf{p}) \\[0.3em]
&= (\omega \wedge \eta)(F(\bf{p})) \left((\bf{v}_1)_{F(\bf{p})},\ldots,\,F'(\bf{p})(\bf{v}_k)_{F(\bf{p})}\right) \\[0.3em]
&= (F^\ast \omega \wedge F^\ast \eta)(\bf{p}) ((\bf{v}_1)_\bf{p},\ldots, (\bf{v}_{k+l})_\bf{p}) . \qquad \square
\end{aligned}
$$

:::

</br>

여기서 ($4$) 는 매끄러운 사상 $F:\R^n \to \R^m$ 에 대해 $T_{F(\bf{p})}(\R^m)$ 의 미분 형식의 구조가 $T_\bf{p}(\R^n)$ 에서도 보존됨을 의미한다. 그리고 이 정리를 이용하면 다음을 알 수 있다.
 
$$
\begin{aligned}
F^\ast &(P \,dx_1 \wedge dx_2 + Q\,dx_2 \wedge dx_3) =  (P \circ F) \cdot F^\ast (dx_1 \wedge dx_2) + (Q\circ F)\cdot F^\ast (dx_2 \wedge dx_3) \\[0.3em]
&\qquad = (P\circ F)\cdot (F^\ast dx_1 \wedge F^\ast dx_2) + (Q\circ F)\cdot (F^\ast dx_2 \wedge F^\ast dx_3)
\end{aligned}
$$

이것은 다소 복잡한 계산이며 이런 류의 계산을 줄이기 위한 정리가 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_full_back_simplification}

$F:\R^n \to \R^n$ 이 미분가능 할 때 다음이 성립한다.

$$
F^\ast (h\, dx_1 \wedge \cdots \wedge dx_n) = (h \circ F)\cdot \det (F')\cdot (dx_1 \wedge \cdots \wedge dx_n).
$$

:::
</div>

::: {.proof}

@thm-CM_properties_of_full_back 에 의해 

$$
F^\ast (h\, dx_1 \wedge \cdots \wedge dx_n) = (h\circ F) \cdot (F^\ast (dx_1 \wedge \cdots \wedge dx_n)).
$$

여기서 $\R^n$ 의 표준 기저 $\bf{e}_1,\ldots,\,\bf{e}_n$ 을 생각하자. 그리고 $F'(\bf{p})=A$ 는 $n \times n$ 행렬이다. 

$$
\begin{aligned}
 (F^\ast (dx_1 \wedge \cdots \wedge dx_n))& (\bf{e}_1,\ldots,\,\bf{e}_n) \\[0.3em]
 &= (dx_1 \wedge \cdots \wedge dx_n) (F_\ast (\bf{e}_1),\ldots,\,F_\ast (\bf{e}_n)) \\[0.3em]
 &=(dx_1 \wedge \cdots \wedge dx_n) (F'(\bf{p})(\bf{e}_1),\ldots,\, F'(\bf{p})(\bf{e}_n)) \\[0.3em]
 &=(dx_1 \wedge \cdots \wedge dx_n) \left(\sum_{i=1}^n A_{i1}\bf{e}_i,\ldots \sum_{i=1}^n A_{in}\bf{e}_i\right) \\[0.3em]
\end{aligned}
$$

@thm-CM_alternating_tensor_and_determinant 에 따라 다음이 성립한다.

$$
(F^\ast (dx_1 \wedge \cdots \wedge dx_n)) (\bf{e}_1,\ldots,\,\bf{e}_n) = \det(A)\cdot (dx_1 \wedge \cdots \wedge dx_n)\cdot (\bf{e}_1,\ldots,\,\bf{e}_n).\square
$$

:::

</br>

### 외미분 {#sec-CM_external_derivative_of_differantial_form}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_differential_of_forms}

#### 외미분

$k$-형식 

$$
\omega = \sum_{i_1<\cdots<i_k} \omega_{i_1,\ldots,i_k}dx_{i_1}\wedge \cdots \wedge dx_{i_k}
$$

에 대한 $\omega$ 의 **외미분 (external derivative)** $d\omega$ 를 아래와 같이 정의한다.

$$
\begin{aligned}
d\omega :=& \sum_{i_1<\cdots <i_k} \left(d\omega_{i_1,\ldots,i_k}\right) \wedge dx_{i_1}\wedge \cdots \wedge dx_{i_k} \\[0.3em]
=& \sum_{i_1<\cdots<i_k} \sum_{\alpha=1}^n D_\alpha (\omega_{i_1,\ldots,i_k}) \,dx_\alpha \wedge dx_{i_1}\wedge \cdots \wedge dx_{i_k}.
\end{aligned}
$$ {#eq-CM_def_of_differential_of_form}

::: 
:::

$k$-형식 $\omega$ 에 대해 $d\omega$ 는 $k+1$ 형식이 된다는 것은 쉽게 알 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_differential_of_form}

$k$-형식 $\omega,\, \eta$ 과 $l$-형식 $\zeta$, 미분가능한 $F:\R^n \to \R^m$ 에 대해 다음이 성립한다.

&emsp;($1$) $d(dx_{i_1}\wedge \cdots \wedge dx_{i_k}) = 0$, 

&emsp;($2$) $d(\omega + \eta) = d\omega + d\eta$, 

&emsp;($3$) $d(\omega \wedge \zeta) = d\omega \wedge \zeta + (-1)^k \omega \wedge d\zeta$, 

&emsp;($4$) $d(d\omega)=0$,

&emsp;($5$) $\omega$ 가 $\R^m$ 에서의 $k$-형식일 때 $F^\ast (d\omega) = d(F^\ast \omega)$.

:::
</div>

::: {.proof}
($1$) @eq-CM_def_of_differential_of_form 에서 $D_\alpha (\omega_{i_1,\ldots,i_k})=0$ 이다.

($2$) $D_\alpha (\omega_\cdots + \eta_\cdots )\,dx_\alpha = D_\alpha \omega_\cdots dx_\alpha + D_\alpha \eta_\cdots dx_\alpha$ 이다.

($3$) $\omega = \omega_0 dx_{i_1}\wedge \cdots \wedge dx_{i_k}$, $\zeta = \zeta_0 dx_{i_{k+1}}\wedge \cdots \wedge dx_{i_{k+l}}$ 이라고 하자. 
$$
\begin{aligned}
d(\omega \wedge \zeta) &= \sum_{\alpha=1}^n D_\alpha (\omega_0 \zeta_0)dx_{\alpha} dx_{i_1} \wedge \cdots \wedge dx_{i_{k+l}}\\[0.3em]
&= \sum_{\alpha} D_\alpha (\omega_0)\,dx_{\alpha} \wedge dx_{i_1} \wedge \cdots \wedge dx_{i_k} \wedge \zeta \\[0.3em]
&\qquad + \sum_{\alpha} \omega \wedge (-1)^k D_\alpha (\zeta_0) dx_{\alpha} dx_{i_{k+1}}\wedge \cdots \wedge dx_{i_{k+l}}\\[0.3em]
&=d\omega \wedge \zeta + (-1)^k \omega \wedge d\zeta.
\end{aligned}
$$

($4$) $\displaystyle d(d \omega) = \sum_{i_1<\cdots <i_k} \sum_{\beta=1}^n \sum_{\alpha=1}^n D_{\alpha,\,\beta} (\omega_{i_1,\cdots,i_k})\, dx_\beta \wedge dx_\alpha \wedge dx_{i_1}\wedge \cdots \wedge dx_{i_k}$ 이다. 여기서 $\displaystyle \sum_{\beta=1}^n \sum_{\alpha=1}^n D_{\alpha,\,\beta} (\omega_{i_1,\cdots,i_k})\, dx_\beta \wedge dx_\alpha = 0$ 이므로 $d(d\omega)=0$ 이다.

($5$) $k$ 에 대한 induction 으로 증명한다. $k=0$ 이면 $d\omega = \sum_{i=1}^n(D_i\omega) dx_i$ 이며

$$
\begin{aligned}
F^\ast (d\omega)(\bf{p})(\bf{v}) &= \sum_{i=1}^n (D_i\omega) (F'(\bf{p})(\bf{v})), \\[0.3em]
d(F^\ast \omega)(\bf{p})(\bf{v}) &= d{\big (}\omega(F(\bf{p})) (F'(\bf{p})(\bf{v})){\big )}=\sum_{i=1}^n (D_i \omega)(F'(\bf{p})(\bf{v}))
\end{aligned}
$$

이다. 이제 $k$ 보다 작은 자연수에 대해 성립함을 가정하고 $k+1$ 형식인 $d(\omega \wedge dx_i)$ 에서 성립함을 보이자.

$$
\begin{aligned}
F^\ast (d(\omega \wedge dx_i)) &=F^\ast ( d\omega \wedge dx_i + (-1)^k \omega \wedge d(dx_i)) \\[0.3em]
&= F^\ast (d\omega \wedge dx_i) = F^\ast (d\omega )\wedge F^\ast (dx_i) \\[0.3em]
\end{aligned}
$$ {#eq-prp-CM_basic_properties_of_differential_of_form}

이다. 여기서

$$
d(F^\ast \omega \wedge F^\ast dx_i) = d(F^\ast \omega) \wedge (F^\ast dx_i) + (-1)^k (F^\ast \omega)\wedge d(F^\ast dx_i)
$$

이며 induction 의 가정에 의해 $d(F^\ast dx_i) = F^\ast (d(dx_i))=0$ 이므로 

$$
d(F^\ast \omega \wedge F^\ast dx_i) = d(F^\ast \omega) \wedge (F^\ast dx_i) = F^\ast d\omega \wedge F^\ast dx_i
$$

이다. @eq-prp-CM_basic_properties_of_differential_of_form 에 대입하면

$$
F^\ast (d(\omega \wedge dx_i)) =d(F^\ast \omega \wedge F^\ast dx_i) = dF^\ast (\omega \wedge dx_i)
$$

임을 안다. $\square$

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_closed_and_exact_form}

#### 닫힌 형식과 완전 형식

형식 $\omega$ 가 $d\omega=0$ 일 때 **닫힌 형식 (closed form)** 이라고 한다. $\omega$ 가 다른 형식 $\eta$ 에 대해 $\omega = d\eta$ 일 때 $\omega$ 를 **완전 형식 (exact form)** 이라고 한다. 

::: 
:::

정의로 부터 아래는 자명하다.
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_closed_form_and_exact_form}

모든 완전 형식은 닫힌 형식이다.

:::
</div>

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-CM_condition_of_closed_form}

#### 

$\omega = Pdx+Qdy$ 가 $\R^2$ 에서 정의된 $1$-형식 이라고 하자. 

$$
d\omega = (D_1Q - D_2P)\, (dx \wedge dy)
$$

이므로 $d\omega = 0$ 이라면 $D_1Q=D_2P$ 이다. @exr-CM_spivak_2_21, @exr-CM_spivak_3_34 는 $\omega = df = D_1f\,dx + D_2fd_y$ 인 $0$-형식 $f$ 가 존재함을 보여준다. 그러나 $\omega$ 가 $\R^n$ 전체가 아닌 부분집합에서만 정의되었다면 이런 함수가 존재하지 않을 수 있다. 고전적인 예는 $\R^2-\{\bf{0}\}$ 에서 정의된 

$$
\omega = \dfrac{-y}{x^2+y^2}dx + \dfrac{x}{x^2+y^2}dy
$$

이다. @exr-CM_spivak_3_41 에서의 $\theta$ 에 대해 $\omega = d\theta$ 이다(@exr-CM_spivak_4_21). 그러나 $\theta$ 는 모든 $\R^2 -\{\bf{0}\}$ 에서 연속으로 정의 될 수 없다. 만약 어떤 함수 $f:\R^2-\{\bf{0}\} \to \R$ 에 대해 $\omega = df$ 라면 $D_1f = D_1\theta,\, D_2f = D_2\theta$ 이며 따라서 $f=\theta + \text{constant}$ 이어야 하지만 이런 함수는 존재할 수 없다.

:::

</div>

</br>

$\omega = \sum_{i=1}^n \omega_i dx_i$ 가 $\R^n$ 에서 정의된 1-형식이며 어떤 $f$ 에 대해 $\omega = df = \sum_{i=1}^n D_if\cdot dx_i$ 라고 하자. $f(\bf{0}) = 0$ 이라고 가정 할 수 있다. 우리는 @exr-CM_spivak_2_35 에서 보였듯이 다음이 성립함을 안다.

$$
f(\bf{x}) = \int_0^1 \dfrac{d}{dt}f(t\bf{x})\,dt = \int_0^1 \sum_{i=1}^n D_i f(t\bf{x})\cdot x_i\, dt = \int_0^1 \sum_{i=1}^n \omega (t\bf{x})\cdot x_i \,dt.
$$

즉 주어진 $\omega$ 에 대해 $\omega = df$ 를 만족하는 $f$ 를 찾기 위해 아래의 함수를 정의할 필요가 있다.

$$
I\omega (\bf{x}) := \int_0^1 \sum_{i=1}^n \omega_i (t\bf{x})\cdot x_i \,dt.
$$ {#eq-CM_Iomega_transform}

$I\omega$ 의 정의가 일단 성립하기 위해 필요한 조건을 살펴 보자. 우선 $\omega$ 가 정의되는 열린 집합 $A\subset \R^n$ 이 $\bf{x}\in A$ 일 때 $0$ 부터 $\bf{x}$ 까지의 선분이 $A$ 에 포함되어야 한다. 이런 성질을 가진 열린 집합을 $\bf{0}$ 주위의 **별모양 집합 (star shaped set)** 이라고 한다. 

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_poincare_lemma}

#### 푸앙카레 정리

$A\subset \R^n$ $\bf{0}$ 주위의 열린 별모양 집합일 때 $A$ 에서 정의된 모든 닫힌 형식은 완전 형식이다.

:::
</div>

::: {.proof}

$l$ 형식 $\omega$ 는 아래와 같은 형태이다.
$$
\omega = \sum_{i_1<\cdots <i_l} \omega_{i_1,\ldots,i_l} dx_{i_1}\wedge \cdots \wedge dx_{i_l}
$$ {#eq-thm_CM_poincare_lemma_1}


우리가 어떤 함수 $I : \Omega^l(\R^n) \to \Omega^{l-1}(\R^n)$ 가 어떤 $\omega\in\Omega^l(\R^n)$ 에 대해서도 ($i$) $I(0)=0$ 이며 ($ii$) $\omega = I(d\omega) + d(I\omega)$ 를 만족하도록 정의 하였다고 하자. $d\omega = 0$ 이면 $\omega = d(I\omega)$ 이므로 우리는 푸앙카레 정리를 증명한 것이 된다.  

$A$ 가 별모양의 열린 집합이므로 우리는 아래와 같이 $I\omega(\bf{x})$ 를 정의 할 수 있다.

$$
\begin{aligned}
I\omega (\bf{x}) &:= \sum_{i_1<\cdots <i_l}\sum_{\alpha=1}^l (-1)^{\alpha-1} \left(\int_0^1 t^{l-1} \omega_{i_1,\ldots,i_l} (t\bf{x})\, dt\right) x_{i\alpha} \\
& \qquad dx_{i_1} \wedge \cdots \wedge\widehat{dx_{i_\alpha}} \wedge \cdots \wedge dx_{i_l}
\end{aligned}
$${#eq-thm_CM_poincare_lemma_2}

여기서 $\widehat{dx_{i_\alpha}}$ 는 $dx_1 \wedge \cdots dx_{i_l}$ 에서 $dx_{i_\alpha}$ 만 빠졌음을 의미한다. 우리는 이제 $\omega = I(d\omega)+ d(I\omega)$ 임을 보일 것이다. 그렇다면 $\omega = d(I\omega)$ 이므로 $d\omega = d^2(I\omega)=0$ 이다. @exr-CM_spivak_3_32 를 사용하여 다음을 보일 수 있다.

$$
\begin{aligned}
d(I\omega) &= l \cdot \sum_{i_1<\cdots <i_l} \left(\int_0^1 t^{l-1} \omega_{i_1,\ldots,i_l} \,dt \right) dx_{i_1} \wedge \cdots \wedge dx_{i_l} \\[0.3em]
&+ \sum_{i_1<\cdots <i_l}  \sum_{\alpha=1}^l \sum_{j=1}^n (-1)^{\alpha-1} \left( \int_0^1 t^l D_j (\omega_{i_1,\ldots,i_l})  (t\bf{x}) \,dt\right) \,x_{i\alpha} \\[0.3em]
&\qquad \qquad \qquad \qquad dx_j \wedge dx_{i_1} \wedge \cdots \wedge \widehat{dx_{i_\alpha}} \wedge \cdots \wedge dx_{i_l}
\end{aligned}
$${#eq-thm_CM_poincare_lemma_3}


이다. 우리는 또한 @eq-thm_CM_poincare_lemma_1 로부터

$$
d\omega = \sum_{i_1< \cdots < i_l} \sum_{j=1}^n D_j \omega_{i_1,\ldots,i_l} \cdot dx_j \wedge dx_{i_1}\wedge \cdots \wedge dx_{i_l}
$${#eq-thm_CM_poincare_lemma_4}


임을 안다. @eq-thm_CM_poincare_lemma_4 를 @eq-thm_CM_poincare_lemma_2 에 대입아여 계산하면 된다. 우선 $\sum_{i_1<\cdots<i_l}$ 과 $\sum_\alpha$ 를 제외하고 정해진 $i_1,\ldots,i_l,\,\alpha$ 에 대해 생각해보면

$$
\begin{aligned}
\sum_{j=1}^n&(-1)^{\alpha-1} \left(\int_0^1 t^{l-1} \underbrace{\left(D_j[\omega_{i_1,\ldots,i_l}(tx)]\right)}_{=tD_j(\omega_{i_1,\ldots,i_l})(tx)}\,dt\right) x_{i\alpha}\, dx_j \wedge dx_{i_1}\wedge \cdots \wedge \widehat{x_{i_\alpha}}\wedge \cdots \wedge dx_l \\[0.3em]
&=\sum_{j=1}^n (-1)^{\alpha-1} \left(\int_0^1 t^l D_j (\omega_{i_1,\ldots,i_l}) (tx)\, dt\right) x_{i\alpha}\, dx_j \wedge dx_{i_1}\wedge \cdots \wedge \widehat{x_{i_\alpha}}\wedge \cdots \wedge dx_l
\end{aligned}
$$

이다. $j=i_\alpha$ 일 경우 에는 

$$
\begin{aligned}
\delta_{j,i_\alpha} & x_{i\alpha}\, dx_j \wedge dx_{i_1}\wedge \cdots \wedge \widehat{x_{i_\alpha}}\wedge \cdots \wedge dx_l =(-1)^{\alpha-1} x_j dx_{i_1}\wedge \cdots \wedge x_{i_l}
\end{aligned}
$$

$$
\begin{aligned}
I(d\omega) &= \sum_{i_1<\cdots<i_l} \sum_{\alpha=1}^l \left(\int_0^1 t^l D_j (\omega_{i_1,\ldots,i_l})(tx)\,dt \right) x_j \,dx_{i_1}\wedge \cdots \wedge dx_{i_l} \\[0.3em]
&-\sum_{i_1<\cdots<i_l} \sum_{j=1}^n\sum_{\alpha=1}^l (-1)^{\alpha-1} \left(\int_0^1 t^l D_j (\omega_{i_1,\ldots,i_l})(tx)\,dt\right)x_{i_\alpha}  \\[0.3em]
&\qquad \qquad \qquad dx_j \wedge dx_{i-1}\wedge \cdots \wedge \widehat {dx_{i_\alpha}} \wedge \cdots \wedge dx_{i_l}.
\end{aligned}
$${#eq-thm_CM_poincare_lemma_5}

@eq-thm_CM_poincare_lemma_3 과 @eq-thm_CM_poincare_lemma_5 를 더하면 $\sum$ 이 세게 붙은 항은 서로 상쇄되므로

$$
\begin{aligned}
d(I\omega) + I(d\omega) &= l \cdot \sum_{i_1<\cdots <i_l} \left(\int_0^1 t^{l-1} \omega_{i_1,\ldots,i_l} \,dt \right) dx_{i_1} \wedge \cdots \wedge dx_{i_l} \\[0.3em] 
&+ \sum_{i_1<\cdots<i_l} \sum_{\alpha=1}^l(-1)^{\alpha-1} \left(\int_0^1 t^l D_j (\omega_{i_1,\ldots,i_l}(tx)\,dt \right) x_j \,dx_{i_1}\wedge \cdots \wedge dx_{i_l} \\[0.3em]
&= \sum_{i_1<\cdots<i_l} \left(\int_0^1 \dfrac{d}{dt} \left[t^l x_j D_j (\omega_{i_1,\ldots,i_l}) (tx)\right]\,dt\right)\,dx_{i_1}\wedge \cdots \wedge dx_{i_l} \\[0.3em]
&=\sum_{i_1<\cdots<i_l} \omega_{i_1,\ldots,i_l} dx_{i_1}\wedge \cdots \wedge dx_{i_l} \\[0.3em]
&= \omega. \square
\end{aligned}
$$

:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_13}

#### Spivak 4.13

$F:\R^n \to \R^m$ 이고 $G:\R^m \to \R^n$ 일 때 $(G\circ F)_\ast = G_\ast \circ F_\ast$ 이고 $(G\circ F)^\ast = F^\ast \circ G^\ast$ 임을 보여라.

:::

</div>

::: {.solution}

@def-CM_push_forward_and_pull_back 을 보자.
$$
\begin{aligned}
(G\circ F)_\ast (v_p) &= ((G\circ F)'(p)(v_p)) = (G'(F(p))\circ F'(p))(v_p) \\[0.3em]
&= G_\ast (F'(p)) (v_p) = G_\ast \circ F_\ast (v_p).\\[0.3em]
(G\circ F)^\ast \omega (v_1,\ldots,v_k) &=((G \circ F)_\ast)^\ast (\omega)(v_1,\ldots,\,v_k) \\[0.3em]
&=\omega((G\circ F)_\ast (v_1),\ldots, (G\circ F)_\ast (v_k))\\[0.3em]
&=\omega ((G_\ast \circ F_\ast)(v_1),\ldots,\, (G_\ast \circ F_\ast)(v_k)) \\[0.3em]
&= (G^\ast \omega) (F_\ast (v_1),\ldots, F_\ast (v_k)) \\[0.3em]
&= (F^\ast \circ G^\ast)(\omega) (v_1,\ldots,\,v_k).
\end{aligned}
$$

:::
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_14}

#### Spivak 4.14

$P:[0,\,1]\to \R^n$ 이 미분가능하다. 즉 $P$ 는 미분가능한 곡선이다. $t\in [0,\,1]$ 에서의 $P$ 의 접백터 $v$ 는 $P_\ast((e_1)_t) = (p_1'(t),\ldots,\,p_n'(t))_{P(t)}$ 로 정의된다. $F:\R^n \to \R^m$ 에서 $F\circ P$ 의 $t$ 에서의 접벡터는 $F_\ast (v)$ 임을 보여라.

:::

</div>

::: {.solution}

@exr-CM_spivak_4_13 의 $(G\circ F)_\ast = G_\ast \circ F_\ast$ 문제이다.

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_15}

#### Spivak 4.15

$f: \R \to \R$ 이며 $P:\R \to \R^2$ 가 $P(t) = (t,\, f(t))$ 라고 하자. $P$ 의 $t$ 에서의 탄젠트벡터의 끝점은 lies on the tangent line to the graph of f at $(t,\,f(t))$.


:::

</div>

::: {.solution}

@exr-CM_spivak_4_14 로부터 $v=P_\ast((e_1)t) = (1,\, f'(t))$ 임을 안다. 따라서 그 끝점은 $(t+1,\, f(t)+f'(t))$ 이다. 


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_16}

#### Spivak 4.16
$P[0,\,1]: \to \R^n$ 이 모든 $t$ 에서 $\|P(t)\|=1$ 이다. $P(t)_{P(t)}$ 와 $t$ 에서의 접선 벡터는 서로 직교함을 보여라.

:::

</div>

::: {.solution}

$1=\|P(t)\|^2=\langle P(t),\, P(t)\rangle$ 이므로 $0=\langle P(t),\, P'(t)\rangle$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_17}

#### Spivak 4.17

$F:\R^n \to \R^n$ 이 벡터장 $\bf{F}(\bf{p}) = F(\bf{p})_\bf{p}\in T_\bf{p}(\R^n)$ 을 정의한다.

($a$) $\R^n$ 에서의 모든 벡터장 $\overline{F}$ 는 어떤 $F$ 에 대해 $\bf{F}$ 형태임을 보여라.

($b$) $\text{div} \bf{F}= \text{tr}(F')$ 임을 보여라.

:::

</div>

::: {.solution}

($a$) $\bf{F}(\bf{p})=F(\bf{p})$ 에 대해 $\overline{F}(\bf{p})=F(\bf{p})$ 로 정의한다.

($b$) $\text{div} \bf{F} = \text{div} F = \sum_{i=1}^n D_i f_i = \text{tr}(F')$.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_18}

#### Spivak 4.18

$f:\R^n \to \R$ 에 대해 벡터장 $f$ 의 $\bf{p}\in \R^n$ 에서의 **gradient** $(\nabla f)$ 혹은 $\text{grad}\,f$ 를 아래와 같이 정의한다.

$$
(\nabla f)(\bf{p}) = D_1 f(\bf{p})\cdot (\bf{e}_1)_\bf{p} + \cdots D_n f(\bf{p})\cdot (\bf{e}_n)_\bf{p} 
$$

$\nabla f(\bf{p}) = \bf{w}_\bf{p}$ 이면 $D_\bf{v}f(\bf{p}) = \langle \bf{v},\,\bf{w}\rangle$ 임을 보이고 $\nabla f(\bf{p})$ 가 $f$ 가 $\bf{p}$ 에서 가장 빠르게 증가하는 방향임을 보여라.


:::

</div>

::: {.solution}

@exr-CM_spivak_2_29 의 방향 미분의 정의에 의해 

$$
D_\bf{v}f(\bf{p}) = \sum_i D_i f(\bf{p}) (\bf{v}) = \sum_i v_i D_i f(\bf{p}) = \langle \bf{v},\,\bf{w}\rangle
$$

이다. $\|\bf{v}\|$ 의 크기를 일정하게 놓으면 $D_\bf{v}f(\bf{p})$ 가 가장 큰 값은 $\bf{v}$ 와 $\bf{w}$ 가 같은 방향일 때 이므로 $\nabla f(\bf{p})$ 늘 $f(\bf{p})$ 가 가장 빠르게 증가하는 방향이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_19}

#### Spivak 4.19

$F$ 가 $\R^3$ 에서의 벡터장일 때 아래와 같이 형식을 정의한다.

$$
\begin{aligned}
\omega_F &= f_1 dx + f_2 dy + f_3 dz,\\[0.3em]
\zeta_F &= f_1 dy \wedge dz + f_2 dz \wedge dx + f_3 dx \wedge dy.
\end{aligned}
$$

($a$) 아래를 증명하라.

$$
\begin{aligned}
df &= \omega_{\text{grad} f}, \\[0.3em]
d(\omega_F) &= \zeta_{\text{curl}\,F}, \\[0.3em]
d(\zeta_F) &= (\text{div} F) \,dx \wedge dy \wedge dz.
\end{aligned}
$$


($b$) ($a$) 를 이용하여 다음을 증명하라.

$$
\begin{aligned}
\text{curl}\, \text{grad} f &= 0, \\[0.3em]
\text{div}\, \text{curl} F &= 0.
\end{aligned}
$$

($c$) $F$ 가 열린 별모양 집합 $A$ 에서 정의된 벡터장 이고 $\text{curl}F=0$ 일 때 $F$ 는 어떤 $f:A \to \R$ 에 대해 $F=\nabla f$ 임을 보여라. 또한 $\text{div} F=0$ 일 때 어떤 $A$ 에서의 벡터장 $G$ 에 대해 $F=\text{curl}\,G$ 임을 보여라.
:::

</div>

::: {.solution}

($a$) $\omega_{\nabla\text{f}} = D_1f dx + D_2f d_y + D_3 f d_z = df$ 이다

$$
\begin{aligned}
\zeta_{\text{curl} F} &= (D_2 f_3-D_3f_2) dy \wedge dz + (D_3f_1 - D_1f_3) dz \wedge dx \\[0.3em]
&\qquad + (D_1f_2-D_2f_1) dx \wedge dy \\[0.3em]
d(\omega_F) &= D_2f_1dy \wedge dx + D_3f_1 dz \wedge dx + D_1f_2 dx \wedge dy \\[0.3em]
&\qquad + D_3f_2 dz \wedge dy + D_1 f_3 dx \wedge dz + D_2 f_3 dy \wedge dz \\[0.3em]
&= \zeta_{\text{curl}\,F}.
\end{aligned}
$$

$$
\begin{aligned}
d(\zeta_F) &= D_1f_1 dx \wedge dy \wedge dz + D_2f_2 dy \wedge dz \wedge dx + D_3f_3 dz \wedge dx \wedge dy \\[0.3em]
&=(D_1f_1 + D_2f_2 + D_3f_3)\,dx \wedge dy \wedge dz = (\text{div}\,F)dx \wedge dy \wedge dz
\end{aligned}
$$

($b$) $\omega F=0 \iff f_1=f_2=f_3=0 \iff F=0 \iff \zeta_F=0$ 이다.

$$
\begin{aligned}
0&=d(df) = d(\omega_{\text{grad}\,f}) = \zeta_{\text{curl}\,\text{grad}\,f},\\[0.3em]
0&=d(d\omega_F) = d(\zeta_{\text{curl}\, F}) = ({\text{div}\, \text{curl}\,F}) \,dx \wedge dy \wedge dz.
\end{aligned}
$$

($c$) $\text{curl}\,F=0$ 이면 $\zeta_{\text{curl}\, F}=0$ 이므로 $d(\omega_F)=0$ 이며 따라서 $\omega_F=df$ 인 $f:A \to \R$ 이 존재한다. ($a$) 에 의해 $df=\omega_{\text{grad}\,f} = \omega_F$ 이므로 $F=\text{grad}\,f= \nabla f$ 이다. 

$\text{div}\,F=0$ 이면 $d(\zeta_F)=0$ 이므로 푸앙카레 보조정리에 의해 $\zeta_F = d \omega_X$ 인 $1$-형식 $\omega_X$ 가 존재한다. $d\omega_X = \zeta_{\text{curl}\, G}$ 이므로 $F=\text{curl}\,G$ 이다.


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_20}

#### Spivak 4.20
미분가능한 $F:U\to \R^n$ 에 대한 미분가능한 역함수 $F^{-1}:F(U) \to \R^n$ 이 존재한다. 모든 $U$ 에서의 닫힌 형식이 완전하다면 $f(U)$ 에서도 그러함을 보여라.

:::

</div>

::: {.solution}

$\omega$ 가 $f(U)$ 위에서의 형식이라고 하자. @prp-CM_basic_properties_of_differential_of_form 의 ($5$) 에 의해 $F^\ast (d\omega)=d(F^\ast \omega)$ 이다. 여기서 $(F^\ast \omega)$ 는 $U$ 에서의 형식이며 $d(F^\ast \omega)=0$ 이면 $F^\ast \omega = d\zeta$ 인 $U$ 에서의 형식 $\zeta$ 가 존재한다. $(F^{-1})^\ast \zeta$ 는 $F(U)$ 위에서의 형식이며 

$$
d((F^{-1})^\ast \zeta)= (F^{-1})^\ast(d\zeta) = (F^{-1})^\ast(F^\ast \omega)
$$

이다. 이 때 $G=F^{-1}$ 이라 하면, $F'\circ G'($ @def-CM_push_forward_and_pull_back 

$$
\begin{aligned}
G^\ast &(F^\ast \omega) (\bf{p})(\bf{v}_1,\ldots,\bf{v}_k)\\[0.3em]
&=(F^\ast \omega)(G(\bf{p}))(G'(\bf{p})(\bf{v}_1),\ldots,\, G'(\bf{p})(\bf{v}_k))\\[0.3em]
&=\omega(F\circ G (\bf{p})) (F'(G(\bf{p})) \cdot G'(\bf{p})(\bf{v}_1),\ldots,\, F'(G(\bf{p})\circ G'(\bf{p})(\bf{v}_k)) \\[0.3em]
&= \omega(\bf{p}) (\bf{v}_1,\ldots,\,\bf{v}_k) = d(G^\ast \zeta)(\bf{v}_1,\ldots,\,\bf{v}_k)
\end{aligned}
$$

이며 따라서 $\omega$ 도 완전하다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_4_21}

#### Spivak 4.21

$\theta$ 가 정의된 집합에서 $d\theta$ 가 다음과 같음을 보여라.

$$
d\theta = \dfrac{-y}{x^2+y^2}dx + \dfrac{x}{x^2+y^2}dy
$$



:::

</div>

