---
title: "미분 형식"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---
{{< include ../../latexmacros.qmd >}}

## 다중 선형 대수

### 텐서와 텐서곱 {#sec-CM_tensor_and_tensor_product}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_k_tensor}

#### $k$-텐서

벡터공간 $V$ 에 대해 $V^k \mapsto \R$ 인 다중선형 함수의 집합을 **$k$-텐서 ($k$-tensor)** 라고 하며 $k$-텐서 의 집합을 $\mathcal{T}^k(V)$ 라고 쓴다. 즉 $c\in \R$ 에 대해

$$
\begin{aligned}
T(v_1,\ldots,v_i+cv'_i,\ldots,v_k) = T(v_1,\ldots,v_i,\ldots,v_k) + cT(v_1,\ldots,cv'_i,\,v_k)
\end{aligned}
$$ {#eq-CM_multilinear_property}

이면 $T\in\mathcal{T}^K(V)$ 이다. 

여기서 $\mathcal{T}^k(V)$ 의 합과 스칼라곱을 아래와 같이 정의한다.

$$
\begin{aligned}
(S+T)(v_1,\ldots,\,v_k) &= S(v_1,\ldots,\,v_k) + T(v_1,\ldots,\,v_k) , \\[0.3em]
(cT)(v_1,\ldots,\,v_k) &= c{\big (}T(v_1,\ldots,\,v_k){\big )} .
\end{aligned}
$$ {#eq-CM_def_addition_and_scala_product_in_k_tensor}


::: 
:::


우리는 $\mathcal{T}^1(V)$ 가 $V$ 의 쌍대공간 $V^\ast$ 이라는 것을 쉽게 알 수 있다. 그리고 아래는 쉽게 보일 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_k_tensor_is_vector_space}

$\mathcal{T}^k(V)$ 는 벡터공간이다.
:::

</div></br>


::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_tensor_product}

#### 텐서곱

$S\in\mathcal{T}^k(V),\, T\in \mathcal{T}^l(V)$ 일 때 텐서곱 $S\otimes T \in \mathcal{T}^{k+l}(V)$ 를 다음과 같이 정의한다.

$$
(S\otimes T)(v_1,\ldots,v_k,v_{k+1},\ldots,v_{k+l})=S(v_1,\ldots,v_k) \cdot T(v_{k+1},\ldots,v_{k+l})
$$ {#eq-CM_tensor_product}
::: 
:::

</br>

@eq-CM_tensor_product 로 정의된 $S\otimes T$ 는 실제 $k+l$-텐서임은 쉽게 보일 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_tensor_product}
텐서곱에 대해 다음이 성립한다. 

$$
\begin{aligned}
(S_1+S_2)\otimes T &= S_1 \otimes T + S_2 \otimes T, \\[0.3em]
S\otimes (T_1+T_2) &= S\otimes T_1 + S \otimes T_2, \\[0.3em]
(cS)\otimes T = c(S \otimes T) &= S \otimes (cT), \\[0.3em]
(S \otimes T) \otimes R &= S \otimes (T \otimes R).
\end{aligned}
$$ {#eq-CM_basic_properites_of_tensor_product}
:::

</div></br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_basis_of_tensor_product}

$V$ 가 $n$ 차원 벡터공간이고 $e_1,\ldots,\,e_n$ 이 $V$ 의 기저일 때 이 기저에 대한 쌍대기저 $\{\varphi_j\}$ 에 대해 

$$
\{\varphi_{i_1} \otimes \cdots \otimes \varphi_{i_k} : 1 \le i_1,\ldots,\,i_k \le n\}
$$

는 $\mathcal{T}^k(V)$ 의 기저이다.

:::

</div>

::: {.proof}

쌍대기저의 성질에 의해 $\varphi_j(v_i)= \delta_{ij}$ 이다. 그리고

$$
\left(\varphi_{i_1} \otimes \cdots \otimes \varphi_{i_k}\right)(e_{j_1},\ldots,\,e_{j_k}) = \delta_{i_1j_1}\cdots \delta_{i_kj_k}
$$

임을 안다. $v_1,\ldots,v_k\in V$ 이며 $v_i = \sum_{j=1}^n a_{ij}e_j$ 이고 $T\in \mathcal{T}^k(V)$ 일 때

$$
\begin{aligned}
T(v_1,\ldots,v_k) &= \sum_{j_1,\ldots,\,j_k=1}^n a_{1,j_1}\cdots a_{k,j_k} T(e_{j_1},\ldots,e_{j_k}) \\[0.3em]
&= \sum_{i_1,\ldots,i_k=1}^n T(e_{i_1},\ldots,e_{i_k}) \cdot {\big(} \varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k} {\big )}(v_1,\ldots,\,v_k)
\end{aligned}
$$

이다. 즉 $\{\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k}\}$ 가 $\mathcal{T}^k(V)$ 를 span 한다. 이제 선형독립임을 보이자.

$$
\sum_{i_1,\ldots,i_k=1}^n a_{i_1,\ldots,i_k}\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k} = 0
$$

일 때 모든 $a_{i_1,\ldots,i_k}=0$ 이라는 것을 보이면 된다. 이 함수를 $(e_{j_1},\ldots,e_{j_k})$ 에 적용시며보면 이를 확인 할 수 있다. $\square$

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_dual_transform}

#### pullback

$f\in \mathcal{L}(V,\,W)$ 에 대해 아래와 같이 정의되는 $f^\ast : \mathcal{T}^k(W) \to \mathcal{T}^k(V)$ 를 $f$ 에 의한 $T$ 의 **pullback** 이라고 한다.

$$
\left(f^\ast (T)\right)(v_1,\ldots,v_k) = T(f(v_1),\ldots,\,f(v_k))
$$ {#eq-CM_definition_of_dual_transform}

::: 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_dual_transform}

선형 변환 $f\in \mathcal{L}(V,W)$ 에 대한 쌍대변환 $f^\ast : \mathcal{T}^k(W) \to \mathcal{T}^k(V)$ 에 대해 다음이 성립한다.

&emsp;($1$) $f^\ast$ 는 선형변환이다.

&emsp;($2$) $f^\ast( S\otimes T) = f^\ast (S) \otimes f^\ast (T)$ 이다.

&emsp;($3$) $g \in \mathcal{L}(W,\,X)$ 이면 $(g \circ f)^\ast (T) = f^\ast (g^\ast (T))$ 이다.

:::

</div>

::: {.proof} 

($1$) 은 정의에 의해 자명하다.

($2$) $S\in \mathcal{T}^k(V),\, T\in \mathcal{T}^l(V)$ 일 때,

$$
\begin{aligned}
f^\ast( S\otimes T) & (v_1,\ldots,v_k,\,v_{k+1},\ldots,v_{k+l}) \\[0.3em]
&=(S\otimes T)(f(v_1),\ldots,\,f(v_{k+l})) \\[0.3em]
&=S(f(v_1),\ldots,f(v_k))\cdot T(f(v_{k+1}),\ldots,f(v_{k+l})) \\[0.3em]
&= (f^\ast (S) \otimes f^\ast (T)) (v_1,\ldots,v_k,\,v_{k+1},\ldots,v_{k+l})
\end{aligned}
$$

($3$) 

$$
\begin{aligned}
\left((g\circ f)^\ast (T)\right)(v_1,\ldots,\,v_k) &= T( (g\circ f)(v_1),\ldots,(g\circ f)(v_k)) \\[0.3em]
&= \left(g^\ast (T)\right)(f(v_1),\ldots,\,f(v_k)) \\[0.3em]
&= f^\ast (g^\ast (T)) (v_1,\ldots,\,v_k). \square
\end{aligned}
$$

:::

</br>

### 교대 텐서 {#sec-CM_alternating_tensor}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_alternating_k_tensor}

#### 교대 텐서

$\omega \in \mathcal{T}^k(V)$ 가 아래와 같은 성질을 가질 때 $\omega$ 를 **교대 $k$-텐서 (alternaging $k$-tensor)** 라고 한다.

$$
\omega (v_1,\ldots,v_i,\ldots,v_j,\ldots,v_n) = -\omega (v_1,\ldots,v_j,\ldots,v_i,\ldots,v_n) .
$$ {#eq-CM_alternating_property_of_k_tensor}

그리고 교대 $k$-텐서의 집합을 $\mathcal{A}^k(V)$ 로 표기한다.

::: 
:::

</br>

아래는 쉽게 보일 수 있다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_k_alternating_tensor_is_vector_space}

$\mathcal{A}^k(V)$ 는 벡터공간이며 $\mathcal{T}^k(V)$ 의 부분공간이다.
:::

</div></br>

교대 텐서를 좀 더 편하게 다루기 위해 $\text{Alt} \in \mathcal{T}^k(V)$ 를 아래와 같이 정의한다. 여기서 $\sigma$ 는 대칭군 $S_k$ 에 속하는 순열이며 $\text{sgn}(\sigma)$ 는 순열에 대한 부호함수이다.

$$
\text{Alt}(T)(v_1,\ldots,v_k) := \dfrac{1}{k!}\sum_{\sigma \in S_k} \text{sgn}(\sigma) \cdot T\left(v_{\sigma(1)},\ldots,v_{\sigma(k)}\right)
$$ {#eq-CM_definition_of_alt_function}

이 $\text{Alt}$ 함수에 대해 다음을 알아보자. 


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_alt_function}
</br>

&emsp;($1$) $T\in \mathcal{T}^k(V)$ 이면 $\text{Alt}(T)\in \mathcal{A}^k(V)$ 이다.

&emsp;($2$) $\omega\in \mathcal{A}^k(V)$ 이면 $\text{Alt}(\omega) = \omega$ 이다.

&emsp;($3$) $T\in \mathcal{T}^k(V)$ 이면 $\text{Alt}(\text{Alt}(T)) = \text{Alt}(T)$ 이다.
:::

</div>

::: {.proof}

($1$) $\sigma,\,\tau \in S_k$ 일 때 $\text{sgn}(\sigma \circ \tau)= \text{sgn}(\sigma)\cdot \text{sgn}(\tau)$ 임을 안다. 호환 (transportation) $\tau = (i,j)$ 라고 하면 $\text{sgn}(\tau)=-1$ 이며

$$
\begin{aligned}
\text{Alt}(T)(\cdots ,v_j,\ldots,\,v_i,\ldots) &= \text{Alt}(T) (v_{\tau(1)},\ldots,v_{\tau(k)})  \\[0.3em]
&=\dfrac{1}{k!} \sum_{\sigma\in S_k} \text{sgn}(\sigma) \cdot T(v_{\sigma \circ \tau (1)},\ldots,v_{\sigma\circ \tau (k)}) \\[0.3em]
&= -\dfrac{1}{k!} \sum_{\theta \in S_k} \text{sgn}(\theta) \cdot T(v_{\theta (1)},\ldots,v_{\theta (k)}) \\[0.3em]
&= - \text{Alt}(T)(\ldots,v_i,\ldots,v_j,\ldots)
\end{aligned}
$$

이다. 따라서 $\text{Alt}(T)\in \mathcal{A}^k(V)$ 이다.

($2$) @eq-CM_alternating_property_of_k_tensor 로 부터 $\omega (v_{\sigma (1)},\ldots,v_{\sigma (k)}) = \text{sgn}(\sigma) \cdot \omega (v_1,\ldots,v_k)$ 임을 보일 수 있다. 따라서 

$$
\begin{aligned}
\text{Alt}(\omega)(v_1,\ldots,v_k)  &= \dfrac{1}{k!}\sum_{\sigma\in S_k} \text{sgn}(\sigma) \cdot \omega(v_{\sigma (1)},\ldots,v_{\sigma(k)}) \\[0.3em]
&= \dfrac{1}{k!} \sum_{\sigma \in S_k} \text{sgn}(\sigma)\cdot \text{sgn}(\sigma) \cdot \omega (v_1,\ldots,v_k) \\[0.3em]
&= \omega(v_1,\ldots,v_k).
\end{aligned}
$$

이다. 

($3$) ($1$), ($2$) 에 의해 자명하다. $\square$

:::

</br>

우리는 이전에 $T\in \mathcal{T}^k(V),\,S\in \mathcal{T}^l(V)$ 일 때 $T \otimes S \in \mathcal{T}^{k+l}(V)$ 임을 보였다. 그러나 $\omega \in \mathcal{A}^k(V),\, \eta \in \mathcal{A}^l(V)$ 일 때 $\omega \otimes \eta$ 는 일반적으로 $\mathcal{A}^{k+l}(V)$ 에 포함되지 않는다. 

</br>

### 쐐기곱

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_wedge_product}

#### 쐐기곱

$\omega \in \mathcal{A}^k(V),\, \eta \in \mathcal{A}^l(V)$ 에 대해 $\omega$ 와 $\eta$ 의 **쐐기곱 (wedge product)** 혹은 **외적 (exterior product)** $\omega \wedge \eta : V^{k+l} \to \R$ 은 아래와 같이 정의된다.

$$
\omega \wedge \eta = \dfrac{(k+l)!}{k!\,l!} \text{Alt}(\omega \otimes \eta)
$$
::: 
:::
아래는 쉽게 보일 수 있다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_wedge_product_is_an_alternating_tensor}

$\omega \wedge \eta \in \mathcal{A}^{k+l}(V)$ 이다.
:::

</div></br>

이제 쐐기곱의 중요한 성질을 알아보자.


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_wedge_product_1}

$\omega,\,\omega_1,\,\omega_2\in \mathcal{A}^k(V),\, \eta,\,\eta_1,\,\eta_2\in \mathcal{A}^l(V),\, a\in \R$ 일 때 다음이 성립한다.
$$
\begin{aligned}
(\omega_1 + \omega_2) \wedge \eta &= \omega_1 \wedge \eta + \omega_2 \wedge \eta, \\[0.3em]
\omega \wedge (\eta_1+\eta_2) &= \omega \wedge \eta_1 + \omega \wedge \eta_2, \\[0.3em]
a (\omega \wedge \eta) &= (a\omega) \wedge \eta = \omega \wedge (a\eta), \\[0.3em]
\omega \wedge \eta & = (-1)^{kl} \eta \wedge \omega.
\end{aligned}
$$ {#eq-CM_basic_properties_of_wedge_product}
:::

</div></br>

::: {.proof}

우선 첫번째 식을 보자.
$$
\begin{aligned}
{\big (}(\omega_1 + \omega_2)\wedge \eta {\big )} &(v_1,\ldots,\,v_{k+l}) =\dfrac{(k+l)!}{k!\,l!} \text{Alt}((\omega_1+\omega_2) \otimes \eta)(v_1,\ldots,v_{k+l}) \\[0.3em]
&= \dfrac{1}{k! \, l!} \sum_{\sigma\in S_{k+l}} \text{sgn}(\sigma) \cdot (\omega_1+\omega_2) \left(v_{\sigma (1)},\ldots,v_{\sigma (k)}\right) \cdot \eta \left(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)}\right) \\[0.3em]
&= (\omega_1 \wedge \eta_1 + \omega_2 \wedge \eta_2) (v_1,\ldots,\,v_{k+l})
\end{aligned}
$$

임을 알 수 있다. 같은 방법으로 두번째 식도 보일 수 있다. 세번째 식은 자명하다.이제 마지막 식을 보자.

$$
\begin{aligned}
(\omega \wedge \eta)(v_1,\ldots,\,v_{k+l}) &= \dfrac{1}{k!\,l!} \sum_{\sigma\in S_{k+l}}\text{sgn}(\sigma) \cdot \omega\left(v_{\sigma (1)},\ldots,v_{\sigma (k)}\right) \cdot \eta \left(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)}\right) \\[0.3em]
\end{aligned}
$$

여기서 $\tau\in S_{k+l}$ 을 $A=(1,\,2,\ldots,\,k+l)$ 을 $B=(k+1,\ldots,\,k+l,\,1,\ldots,\,k)$ 로 바꿔주는 순열이라고 하자. $A$ 의 $k+1$ 을 첫번째로 보내는 데 $k$ 번의 호환이 필요하며 이것을 $l$ 번 해줘야 하므로 $\text{sgn}(\tau) = (-1)^{kl}$ 이다. $\theta = \sigma \circ \tau$ 라고 하면 

$$
\theta(1) = \sigma(k+1),\, \theta(2) = \sigma(k+2), \ldots,  \theta(k+l) = \sigma(k)
$$

이므로
$$
\begin{aligned}
(\omega \wedge \eta)(v_1,\ldots,\,v_{k+l}) &=\dfrac{1}{k!\,l!} \sum_{\sigma\in S_{k+l}}\text{sgn}(\sigma) \cdot \eta \left(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)}\right) \cdot \omega\left(v_{\sigma (1)},\ldots,v_{\sigma (k)}\right)  \\[0.3em]
&= \dfrac{ (-1)^{kl} }{k! l!} \sum_{\theta \in S_{k+l}} \text{sgn}(\theta) \cdot \eta \left(v_{\theta (1)}, \ldots, v_{\theta (l)}\right) \cdot \omega \left(v_{\theta (l+1)} ,\ldots, v_{\theta (k+l)}\right) \\[0.3em]
&= (-1)^{kl} \eta \cdot \omega (v_1,\ldots,\,v_{k+l})
\end{aligned}
$$
이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_wedge_product_2}

$\omega\in \mathcal{A}^k(V),\, \eta\in \mathcal{A}^l(V),\, f\in \mathcal{L}(V, W)$ 일 때 다음이 성립한다.
$$
f^\ast (\omega \wedge \eta) = f^\ast (\omega) \wedge f^\ast (\eta)
$$ {#eq-CM_basic_properties_of_wedge_product_2}
:::

</div></br>

::: {.proof}

$$
\begin{aligned}
{\big(}f^\ast (\omega \wedge \eta){\big )}&(v_1,\ldots,v_{k+l}) = (\omega \wedge \eta)(f(v_1),\ldots,f(v_{k+l})) \\[0.3em]
&= \dfrac{1}{k!\,l!} \sum_{\sigma\in S_{k+l}} \text{sgn}(\sigma) \cdot \omega (f(v_{\sigma (1)}), \ldots, f(v_{\sigma (k)}))\cdot \eta (f(v_{\sigma (k+1)}), \ldots, f(v_{\sigma (k+l)})) \\[0.3em]
&= \dfrac{1}{k!\,l!}\sum_{\sigma \in S_{k+l}} \text{sgn}(\sigma) {\big (}f^\ast (\omega) \otimes f^\ast (\eta) {\big )} (v_{\sigma (1)},\ldots, v_{\sigma (k+l)}) \\[0.3em]
&= {\big (}f^\ast (\omega)\wedge f^\ast (\eta){\big )}(v_{\sigma (1)},\ldots, v_{\sigma (k+l)}). \qquad \square
\end{aligned}
$$


:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_wedge_product_3}

</br>

($1$) $S\in \mathcal{T}^k(V),\, T\in \mathcal{T}^l(V)$ 이고 $\text{Alt}(S) = 0$ 이면 $\text{Alt}(S \otimes T) = \text{Alt}(T \otimes S)=0$ 이다.

($2$) $\text{Alt}\left(\text{Alt}(\omega \otimes \eta) \otimes \zeta\right) = \text{Alt}(\omega \otimes \eta \otimes \theta) = \text{Alt}(\omega \otimes \text{Alt}(\eta \otimes \zeta))$

($3$) $\omega\in \mathcal{A}^k(V),\, \eta\in \mathcal{A}^l(V),\, \zeta \in \mathcal{A}^m(V)$ 일 때 다음이 성립한다.

$$
(\omega \wedge \eta ) \wedge \zeta = \omega \wedge (\eta \wedge \zeta) = \dfrac{(k+l+m)!}{k!\,l!\, m!} \text{Alt}(\omega \otimes \eta \otimes \zeta)
$${#eq-CM_basic_properties_of_wedge_product_3}
:::

</div>

::: {.proof}
($1$)

$$
\begin{aligned}
(k+l)! &\text{Alt}(S\otimes T)(v_1,\ldots,\,v_{k+l}) \\[0.3em] 
&= \sum_{\sigma \in S_{k+l}} \text{sgn}(\sigma)\cdot S(v_{\sigma(1)},\ldots,v_{\sigma(k)})\cdot T(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)})
\end{aligned}
$$ {#eq-prp_CM_basic_properties_of_wedge_product_3_1}

여기서 $A\subset S_{k+l}$ 을 $k+1$ 부터 $k+l$ 까지는 변하지 않는 $S_{k+l}$ 의 성분의 집합이라고 하자.

$$
\begin{aligned}
\sum_{\sigma\in A} \text{sgn}(\sigma) &\cdot S(v_{\sigma(1)},\ldots,v_{\sigma(k)})\cdot T(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)}) \\[0.3em]
&=\left[\sum_{\tau\in S_k} \text{sgn}(\tau) \cdot S(v_{\tau (1)},\ldots,v_{\tau(k)})\right] \cdot T(v_{k+1},\ldots,v_{k+l}) \\[0.3em]
&= k! \text{Alt}(S) \cdot T(v_{k+1},\ldots,v_{k+l}) = 0
\end{aligned}
$$

이다. $\sigma_0 \in S_{k+l}-A$ 에 대해 $A \sigma_0 =\{\sigma' \cdot \sigma_0 : \sigma' \in A\}$ 라고 하자. 그리고 $i=1,\ldots,k+l$ 에 대해 $u_{i}=v_{\sigma_0(i)}$ 라고 하자. 이로부터

$$
\begin{aligned}
\sum_{\sigma \in A\sigma_0} \text{sgn}(\sigma) & \cdot S(v_{\sigma(1)},\ldots,v_{\sigma(k)})\cdot T(v_{\sigma (k+1)},\ldots,v_{\sigma (k+l)}) \\[0.3em]
&= \left[\text{sgn}(\sigma_0) \cdot \sum_{\sigma' \in A} \text{sgn}(\sigma') \cdot S\left(u_{\sigma'(1)}),\ldots,\,u_{\sigma'(k)}\right)\right]\cdot T(u_{k+1},\ldots,u
_{k+l}) \\[0.3em]
&=\text{sgn}(\sigma_0) \cdot \text{Alt}(S)\cdot T(u_{k+1},\ldots,\bf{y}_{k+l}) = 0
\end{aligned}
$$

이다. $S_{k+l}$ 은 군이며 $A$ 는 $S_{k+l}$ 의 부분군이다. 따라서 $S_{k+l}$ 은 서로소인 $A$ 에 대한 오른쪽 잉여류(left cosets) 로 분할되며 각 잉여류는 같거나 서로소이다. $\sigma_0$ 는 $S_{k+l}$ 에 속하지만 $A$ 에 속하지 않는 임의의 원소이므로 @eq-prp_CM_basic_properties_of_wedge_product_3_1 은 $0$ 임을 알 수 있다.

($2$) @prp-CM_basic_properties_of_alt_function ($3$) 으로부터 

$$
\text{Alt}\left(\text{Alt}(\eta \otimes \zeta) - \eta \otimes \zeta\right) =0
$$

임을 안다. ($1$) 로부터

$$
\begin{aligned}
0 &= \text{Alt}\left(\omega \otimes \left[ \text{Alt}(\eta \otimes \zeta) - \eta \otimes \zeta\right]\right) \\[0.3em]
&= \text{Alt} (\omega \otimes \text{Alt}(\eta \otimes \zeta)) - \text{Alt}(\omega \otimes \eta \otimes \zeta)
\end{aligned}
$$

임을 안다. 즉 $\text{Alt} (\omega \otimes \text{Alt}(\eta \otimes \zeta)) = \text{Alt}(\omega \otimes \eta \otimes \zeta)$ 임을 안다. 다른 등호도 같은 방법으로 보일 수 있다.

($3$) $(\omega \wedge \eta)\wedge \zeta$ 에 대해서는 아래와 같이 보일 수 있다. 나머지는 비슷한 방법으로 보일 수 있다.

$$
\begin{aligned}
(\omega \wedge \eta)\wedge \zeta &= \dfrac{(k+l+m)!}{(k+l)!\, m!} \text{Alt}((\omega \wedge \eta) \otimes \zeta) \\[0.3em]
&= \dfrac{(k+l+m)!}{(k+l)!\, m!} \dfrac{(k+l)!}{k!\,l!} \text{Alt}((\omega \otimes \eta) \otimes \zeta) \qquad \square
\end{aligned}
$$

:::

</br>

위의 명제 ($3$) 으로부터 $(\omega \wedge \eta) \wedge zeta$ 와 $\omega \wedge (\eta \wedge \zeta)$ 가 같기 때문에 $\omega \wedge \eta \wedge \zeta$ 와 같이 쓸 수 있다는 것을 알 수 있다. 또한 $\omega_1 \wedge \omega_2 \wedge\cdots \wedge \omega_n$ 도 이와 같이 정의 할 수 있다는 것을 안다. 


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_basis_of_alternating_tensor_space}

$(e_1,\ldots,e_n)$ 이 벡터공간 $V$ 의 기저이고 이 기저에 대한 쌍대기저를 $\varphi_1,\ldots,\,\varphi_n$ 이라고 하자. 이 때 아래 집합이 $\mathcal{A}^k(V)$ 의 기저이다.

$$
\{ \varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k} : 1 \le i_1 <i_2 < \cdots < i_k \le n\}.
$$

또한 

$$
\dim \left(\mathcal{A}^k(V)\right) = \begin{pmatrix} n \\k \end{pmatrix} = \dfrac{n!}{k!\, (n-k)!}
$$

이다. 

:::

</div>

::: {.proof}

$\omega \in \mathcal{A}^k(V) \subset \mathcal{T}^k(V)$ 에 대해

$$
\omega = \sum_{i_1,\ldots,\,i_k} a_{i_1,\ldots,i_k} \varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k}
$$

로 쓸 수 있다. $\omega = \text{Alt}(\omega)$ 이므로

$$
\omega = \text{Alt}(\omega) = \sum_{i_1,\ldots,i_k} a_{i_1,\ldots,i_k} \text{Alt}(\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k})
$$

이다. $\text{Alt}(\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k})$ 는 
$\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k}$ 의 상수배이다. 따라서 $\{\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k}\}$ 는 $\mathcal{A}^k(V)$ 를 span 한다. 이제 이 집합이 선형 독립임을 보이자.

$$
\sum_{i_1,\ldots,i_k =1}^n a_{i_1,\ldots,i_k}(\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k})=0
$$

라고 하자. $(e_{j_1},\ldots,e_{j_k})$ 에 적용시켜보면 모든 $a_{\ldots}=0$ 이다(@exr-spivak_4_1 ($a$)). 따라서 선형 독립이다. $\square$

:::

</br>

우리는 이로부터 중요한 결 론을 얻는다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-CM_alternating_tensor_and_determinant}

$n$ 차원 벡터공간에 대해 $\mathcal{A}^n(V)$ 에 속하는 텐서는 행렬식의 상수배이다.

:::
</div>

::: {.proof}
$\dim (V)=n$ 이라면 $\mathcal{A}^n(V)$ 는 1차원이며 따라서 모든 교대 $n$-텐서는 어떤 상수에 대한 곱이다. 우리는 행렬식이 여기에 포함된 다는 것을 안다. 즉 $n$ 차원 벡터공간에 대한 교대 $n$-텐서는 행렬식의 상수배이다. 
:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_alternating_tensor_and_determinant}

$v_1,\ldots,v_n$ 이 $V$ 의 기저이고 $\omega \in \mathcal{A}^n(V)$ 라고 하자. $i=1,\ldots,\,n$ 에 대해 $\displaystyle u_i = \sum_{j=1}^n a_{ij}v_j$ 일 때 다음이 성립한다.

$$
\omega (u_1,\ldots,u_n) = \det (a_{ij})\cdot \omega (v_1,\ldots,v_n)
$$

:::

</div>

::: {.proof}

$\eta \in \mathcal{T}^n(\R^n)$ 을 아래와 같이 정의하자.

$$
\eta ( (a_{11},\ldots,a_{1n}),\ldots,(a_{n1},\ldots,a_{nn})) := \omega \left(\sum_{j=1}^n a_{1j}v_j,\ldots,\sum_{j=1} ^na_{nj}v_j\right).
$$

$\eta\in \mathcal{A}^n(\R^n)$ 이므로 @cor-CM_alternating_tensor_and_determinant 에 따라 $\eta = \lambda \cdot \det$ 이다. $\eta(e_1,\ldots,e_n) = \lambda \cdot \det (I_n)= \lambda$ 이며 $\eta(e_1,\ldots,e_n) = \omega (v_1,\ldots,v_n)$ 이므로 주어진 식이 성립한다. $\square$

:::

</br>

### 부피 요소와 벡터곱 {#sec-CM_volume_element_and_cross_product}

@thm-CM_alternating_tensor_and_determinant 에 따라 $\omega \in \mathcal{A}^n(V)$ 는 $V$ 의 기저 $(v_1,\ldots,\,v_n)$ 를 $\omega$ 함수값이 양수인 것과 음수인 두 집합으로 분할한다. $V$ 의 두 기저 $(u_i)$ 와 $(v_j)$ 사이에 $u_i = \sum_j a_{ij}v_j$ 의 관계가 있을 때 $\det(a_{ij})>0$ 일 때에만 두 기저가 같은 집합에 속한다. 이 두 집합 가운데 하나를 벡터공간 $V$ 의 **방향 (orientation)** 이라고 한다. 기저 $(v_1,\ldots,v_n)$ 이 속한 방향을 $[v_1,\ldots,v_n]$ 으로 표기하며 반대 방향을 $-[v_1,\ldots,v_n]$ 으로 표기한다. $\R^n$ 에서는 표준기저에 대한 $[e_1,\ldots,e_n]$ 방향을 **정방향(usual orientation)** 이라고 한다. 그러나 일반적인 벡터공간 $V$ 에서는 이렇게 특정 방향을 정할 수 없다. 

벡터공간에 어떤 내적 $T:V\times V \to \R$ 이 정해졌다고 하자. 그리고 이 내적에 대한 두 정규직교기저 $(u_i)$ 와 $(v_j)$ 
사이에는 어떤 직교 행렬 (orthogonal matrix) $O$ 에 대해 $u_i = O v_i$ 의 관계가 있다는 것을 안다. 정규직교 행렬은 $OO^T=I$ 이므로 $\det(O)= \pm 1$ 이다. 만약 $V$ 의 방향 $\mu$ 가 정해졌다면 정규직교기저 $v_1,\ldots,v_n$ 에 대해 $\omega (v_1,\ldots,v_n)=1$ 이 되도록 $\omega\in \mathcal{A}^n(V)$ 를 유일하게 정할 수 있다. 이 유일한 $\omega$ 를 내적 $T$ 와 방향 $\mu$ 에 의해 결정되는 **부피 요소 (volume element)** 라고 한다. $\R^n$ 에서 $\det$ 는 $\R^n$ 의 스칼라곱과 정방향에 의해 결정된 부피 요소와 같으며 $|\det (v_1,\ldots,v_n)|$ 은 원점과 $v_1,\ldots,\,v_n$ 에 의해 결정되는 다차원 평행육면체(parallelipiped) 의 부피이다.

이제 $\R^n$ 에서의 **벡터곱(cross product)** 에 대해 알아보자. 정해진 $v_1,\ldots,v_{n-1} \in \R^n$ 에 대해 $\phi(u) := \det(v_1,\ldots,\,v_{n-1},u)$ 라고 하면 $\phi \in \mathcal{A}^1(\R^n)$ 이다. $\det$ 의 성질에 의해 $\phi (u)$ 는 $V$ 에서 정해진 선형 범함수(linear functinal) 이며, 따라서 소위 리스의 표현정리 (Riesz representation theorem) 에 의해 $\phi (u)=\langle u,\,w \rangle$ 을 만족하는 $w\in V$ 가 유일하게 존재한다. 이 $w$ 를 $v_1 \times \cdots \times v_{n-1}$ 로 표기하고 $v_1,\ldots,v_{n-1}$ 의 **벡터곱** 이라고 한다. 

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_basic_properties_of_cross_product}

벡터곱에 대해 다음이 성립한다.

$$
\begin{aligned}
v_{\sigma(1)}\times \cdots \times v_{\sigma(n-1)} &= \text{sgn}(\sigma)\cdot (v_1\times \cdots \times v_{n-1}), \\[0.3em]
v_1\times \cdots \times (av_i)\times \cdots \times v_{n-1} &= a\cdot (v_1\times \cdots \times v_{n-1}), \\[0.3em]
v_1 \times \cdots \times (v_i + v'_i) \times \cdots \times v_{n-1} &=v_1 \times \cdots \times v_i \times \cdots \times v_{n-1} \\[0.3em]
&\, + v_1 \times \cdots \times v'_i \times \cdots \times v_{n-1} 
\end{aligned}
$$ {#eq-CM_basic_properties_of_cross_product}
:::

</div>

::: {.proof}

행렬식의 성질에 의해 쉽게 보일 수 있다.
:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-spivak_4_1}

#### Spivak 4.1

$\R^n$ 의 표준기저 $(e_1,\ldots,\,e_n)$ 와 이 기저에 대한 쌍대기저 $(\varphi_1,\ldots,\,\varphi_n)$ 을 생각한다.

($a$) $\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k} (e_{i_1},\cdots,e_{i_k})=1$ 임을 보여라. 

($b$) $\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k} (v_1,\ldots,\,v_k)$ 는 행렬 $\begin{bmatrix} v_1 \\ \vdots \\ v_k\end{bmatrix}$ 에서 $i_1,\ldots,\,i_k$ 행을 취한 $k\times k$ 행렬의 행렬식임을 보여라.

:::

</div>
::: {.solution}

($a$) 

$$
\begin{aligned}
\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k} &(e_{i_1},\cdots,e_{i_k}) = k!\text{Alt}(\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k})(e_{i_1},\cdots,e_{i_k}) \\[0.3em]
&= \dfrac{k!}{k!} \sum_{\sigma \in S_k} \text{sgn}(\sigma)\cdot (\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k})(e_{\sigma(i_1)},\cdots,e_{\sigma(i_k)}) \\[0.3em]
&= \sum_{\sigma\in S_k} \text{sgn}(\sigma) \delta_{i_1,\sigma(i_1)} \cdots \delta_{i_k,\sigma(i_k)} = 1
\end{aligned}
$$

($b$) $v_j$ 의 $i$ 번째 성분을 $v_{ji}$ 라고 하자. 

$$
\begin{aligned}
\left(\varphi_{i_1}\wedge \cdots \wedge \varphi_{i_k}\right) & (v_1,\ldots,\,v_k) = \sum_{\sigma\in S_k} \text{sgn}(\sigma) \cdot (\varphi_{i_1}\otimes \cdots \otimes \varphi_{i_k})(v_1,\ldots,\,v_k) \\[0.3em]
&=\sum_{\sigma\in S_k} \text{sgn}(\sigma) v_{1\sigma(i_1)}\cdots v_{k\sigma(i_k)}
\end{aligned} 
$$

이므로 행렬식의 정의에 의해 문제에서 제시한 행렬의 행렬식임을 알 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-spivak_4_2}

#### Spivak 4.2

$f \in \mathcal{L}(V)$ 이고 $\dim(V)=n$ 일 때 $f^\ast :\mathcal{A}^n (V) \to \mathcal{A}^n (V)$ 는 어떤 상수 $c$ 에 대한 곱임을 보여라. 그리고 $c=\det (f)$ 임을 보여라.

:::

</div>

::: {.solution}

$1$ 차원 벡터공간에서의 선형사상은 어떤 상수에 대한 곱이다. $\omega \in \mathcal{A}^n (V)$ 에 대해 

$$
(f^\ast(\omega))= c\omega
$$

라고 하자. 

$$
\begin{aligned}
(f^\ast(\omega))(v_1,\ldots,\,v_n) &= \omega (f(v_1),\ldots, f(v_n)) \\[0.3em]
&= \det (f) \cdot \omega(v_1,\ldots,v_n)
\end{aligned}
$$

이므로 $c=\det(f)$ 이다. 
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-spivak_4_3}

#### Spivak 4.3

$\omega \in \mathcal{A}^n (V)$ 가 내적 $T$ 와 방향 $\mu$ 에 의해 결정되는 부피 요소이고 $u_1,\ldots,u_n\in V$ 일 때 다음이 성립함을 보여라.

$$
\left|\omega (u_1,\ldots,\,u_n)\right| = \sqrt{\det (g_{ij})},\qquad \text{where }g_{ij}=T(u_i,u_j).
$$

:::

</div>

::: {.solution}

$v_1,\ldots,\,v_n$ 이 $T$ 에 대한 정규직교기저이고 $u_i =\sum_j A_{ij}v_j$ 라 하자. $T(u_i,u_j)=(AA^T)_{ij}$ 이며 $\det(A)=\det(A^T)$ 이므로 

$$
|\omega(u_1,\ldots,u_n)|= |\det(g_{ij})| \cdot \underbrace{|\det(v_1,\ldots,v_n)|}_{=1} = \sqrt{\det(g_{ij})}
$$

이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-spivak_4_4}

#### Spivak 4.4

$\omega$ 가 내적 $T$ 와 방향 $\mu$ 에 의해 결정되는 부피 요소이고 $f :\R^n \to V$ 가 동형사상이며 $f^\ast (T) = \langle\,,\,\rangle$ 이고 $[f(e_1),\ldots, f(e_n)]=\mu$ 일 때 $f^\ast \omega = \det$ 임을 보여라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
\left(f^\ast (\omega)\right)(v_1,\ldots,v_n) &=\omega (f(v_1),\ldots,f(v_n)) \\[0.3em]
&= \underbrace{\det (f)}_{=1} \cdot \det (v_1,\ldots,v_n)
\end{aligned}
$$

이므로 $f^\ast \omega = \det$ 이다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-spivak_4_5}

#### Spivak 4.5

$P:[0,\,1] \to (\R^n)^n$ 이 연속이며 각각의 $(\bf{p}_1(t),\ldots,\,\bf{p}_n(t))$ 가 $\R^n$ 의 기저 일 때 $[\bf{p}_1(0),\ldots,\bf{p}_n(0)] = [\bf{p}_1(1),\ldots,\,\bf{p}_n(1) ]$ 임을 보여라.

:::

</div>

::: {.solution}

$\det$ 도 연속이고 $P$ 도 연속함수이므로 $\det (P(t))$ 도 연속함수이다. $(\bf{p}_1,\ldots,\,\bf{p}(t))$ 가 $\R^n$ 의 기저이므로 선형 독립이고 따라서 $\det(P(t))\ne 0$ 이다. 즉 $t\in [0,\,1]$ 에 대해 $\det(P(t))>0$ 이거나 $\det(P(t))<1$ 이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-spivak_4_6}

#### Spivak 4.6

($a$) $v\in \R^2$ 일 때 $v\times$ 는 무엇인가?
 
($b$) $v_1,\ldots,v_{n-1}\in \R^n$ 이 선형 독립이라면 $[v_1,\ldots,v_{n-1},v_1 \times \cdots \times v_{n-1}]$ 은 정방향 임을 보여라.

:::

</div>

::: {.solution}

($a$) $v = (v_1,\,v_2)$, $\bf{z}=(z_1,\,z_2)$, $\bf{w}=(w_1,\,w_2)$ 라고 하자. 정의에 의해

$$
z_1w_1+z_2w_2 = v_1w_2 - v_2w_1
$$

이어야 하므로 $z_1=v_1,\, z_2 = -v_2$ 이다. 즉 $\bf{w} = (v_1,\,-v_2)$ 이다.

($b$) $\phi(u) = \det (v_1,\ldots,\,v_{n-1},\,u) = \langle u, w\rangle$ 가 $u\in \R^n$ 에 대해 성립한다. $v_1,\ldots,\,v_{n-1}$ 이 선형 독립이면 $v_1 \times \cdots \times v_{n-1}\ne 0$ 이며 $u=z=v_1 \times \cdots \times v_{n-1}$ 로 놓으면

$$
0 < \langle z,\,z\rangle = \det (v_1,\ldots,\,v_{n-1},\, v_1\times \cdots \times v_{n-1})
$$

이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-spivak_4_7}

#### Spivak 4.7

$0$ 이 아닌 모든 $\omega \in \mathcal{A}^n(V)$ 는 어떤 내적 $T$ 와 방향 $\mu$ 에 의해 정해지는 부피 요소 일 수 있음을 보여라.

:::

</div>

::: {.solution}

선형 독립인 $v_1,\ldots,\,v_n$ 과 그 쌍대함수 $\varphi_1,\ldots,\varphi_n$ 에 의해 $\omega = \varphi_1 \wedge \cdots \wedge \varphi_n \in \mathcal{A}^n(V)$ 가 정해진다. $u\, w\in V$ 에 대해 $u=\sum_i a_i v_i,\, w=\sum_j b_jv_j$ 일 때 내적 $T(u,\,v) = \langle u,\,w\rangle = \sum_{i}a_ib_i$ 로 정의 할 수 있으며 $\omega (v_1,\ldots,\,v_n)=1$ 이므로 방향성도 정해진다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-spivak_4_8}

#### Spivak 4.8

$\omega\in \mathcal{A}^n(V)$ 가 부피 요소일 때 벡터곱 $v_1\times \cdots \times v_{n-1}$ 을 $\omega$ 를 이용해 표현하라.

:::

</div>

::: {.solution}

$(e_1,\ldots,\,e_n)$ 이 $V$ 의 기저라고 하자. $u = v_1\times \cdots \times v_{n-1}= \sum_i a_i e_i$ 라고 하면 
$$
\begin{aligned}
\omega (v_1,\ldots,\,v_{n-1},\,v_1\times \cdots \times v_{n-1}) &= \sum_{i=1}^n a_i \cdot \omega (v_1,\ldots,\,v_{n-1},\,e_i)
\end{aligned}
$$


이므로 

$$
v_1\times \cdots \times v_{n-1} = \sum_i \omega (v_1,\ldots,\,v_{n-1},\,e_i) e_i
$$

로 정할 수 있다.

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-spivak_4_9}

#### Spivak 4.9
$\R^3$ 에서의 벡터곱이 아래의 성질을 가짐을 보여라.

($a$) Levi-civita 기호 $\varepsilon_{ijk}$ 에 대해 $\bf{e}_i \times \bf{e}_j = \varepsilon_{ijk} \bf{e}_k$,

($b$) $\bf{v}\times \bf{w} = (v_2w_3 - v_3w_2) \bf{e}_1 + (v_3w_1 - v_1w_3)\bf{e}_3 + (v_1w_2 - v_2w_1)\bf{e}_3$, 

($c$) $\theta = \angle (\bf{v},\bf{w})$ 에 대해 $\|\bf{v} \times \bf{w}\| = \|\bf{v}\| \cdot \|\bf{w}\| \cdot |\sin \theta|$ 이며 $\langle \bf{v} \times \bf{w},\bf{v}\rangle = 0$,

($d$) $\begin{gather} \langle \bf{v},\,\bf{w}\times \bf{z}\rangle = \langle \bf{w},\,\bf{z}\times \bf{v}\rangle = \langle \bf{z},\, \bf{v}\times \bf{w}\rangle, \\[0.3em]
\bf{v}\times (\bf{w}\times \bf{z}) = \langle \bf{v},\,\bf{z}\langle \bf{w} - \langle \bf{v},\,\bf{w}\rangle \bf{z}\\[0.3em]
(\bf{v}\times \bf{w}) \times \bf{z} = \langle \bf{v},\,\bf{z}\rangle \bf{w} - \langle \bf{w},\,\bf{z}\rangle \bf{v}.
\end{gather}$

($e$) $\|\bf{v}\times \bf{w}\| = \sqrt{\langle \bf{v}\,\bf{v}\rangle \langle \bf{w},\,\bf{w}\rangle - \langle \bf{v},\,\bf{w}\rangle^2}$.

:::

</div>

::: {.solution}

trivial
:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-spivak_4_10}

#### Spivak 4.10

$\bf{u}_1,\ldots,\bf{u}_{n-1}\in \R^n$ 이며 $g_{ij}= \langle \bf{u}_i,\bf{u}_j\rangle$ 일 때 다음이 성립함을 보여라.

$$
\|\bf{u}_1 \times \cdots \times \bf{u}_{n-1}\| = \sqrt{\det (g_{ij})}.
$$


:::

</div>

::: {.solution}

$X=\text{span}(\bf{u}_1,\ldots,\,\bf{u}_{n-1})$ 은 $n-1$ 차원 벡터공간이며 $\R^n$ 의 부분공간이다. @exr-spivak_4_3 

$$
\begin{aligned}
\|\bf{u}_1 \times \cdots \times \bf{u}_{n-1}\| &= \sqrt{\sum_{i=1}^n \left|\omega (v_1,\ldots,\,v_{n-1},\,e_i)\right|^2} \\[0.3em]
&= 
\end{aligned}
$$

:::


</br>

## 장과 형식 

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_tangent_space}

#### 탄젠트 공간

정해진 $\bf{p}\in \R^n$ 에 대해 $\bf{p}$ 에서의 **탄젠트 공간 (tangent space)** ${\R^n}_\bf{p}$ 는 

$$
{\R^n}_\bf{p} = \{(\bf{p},\,\bf{x}) : \bf{x}\in \R^n\}
$$

에 대해 아래의 연산이 정의된 구조이다.

$$
\begin{aligned}
(\bf{p},\,\bf{x}) + (\bf{p},\,\bf{y}) &= (\bf{p}, \bf{x}+\bf{y}),\\[0.3em]
a\cdot (\bf{p},\,\bf{x}) &= (\bf{p},\,a\bf{x}).
\end{aligned}
$$

${\R^n}_\bf{p}$ 의 벡터 $(\bf{p},\bf{v})$ 를 흔히 $\bf{v}_\bf{p}$ 혹은 $(\bf{v})_\bf{p}$ 와 같이 표기한다.
::: 
:::

다음은 쉽게 보일 수 있다.


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_tangent_space_as_a_vector_space}

${\R^n}_\bf{p}$ 는 $(\bf{p},\,\bf{0})$ 을 영벡터로 하는 벡터공간이다.
:::
</div>

</br>

일반적인 $\R^n$ 의 벡터는 원점으로부터의 화살표로 표현되는 경우가 많다. 이와 유사하게 ${\R^n}_\bf{p}$ 의 벡터 $(\bf{p},\bf{v})$ 는 $\bf{p}$ 를 시작으로 $\bf(p)+\bf{v}$ 를 향하는 화살표로 표현된다. 또한 내적과 방향의 경우 $\R^n$ 과 같이 정의 할 수 있으며 이를 통상 내적, 통상 방향이라고 한다.


::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_usual_inner_product_and_orientation}

#### 통상 내적, 통상 방향

${\R^n}_\bf{p}$ 에서의 내적을 

$$
\langle (\bf{p},\bf{u}), (\bf{p},\bf{v})\rangle_\bf{p}= \langle \bf{u},\bf{v}\rangle
$$

와 같이 정의할 때 이 내적을 **통상 내적 (usual inner product)** 라고 하며 방향을 

$$
[(\bf{v}_1)_\bf{p},\ldots,(\bf{v}_n)_\bf{}] = [\bf{v}_1,\ldots,\bf{v}_n]
$$

으로 정의 할 때 이 방향을 **통상 뱡향 (usual orientation)** 이라고 한다.


::: 
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_vector_field}

#### 벡터장

$F:\R^n \to {\R^n}_\bf{p}$ 를 $\R^n$ 에서의 **벡터장 (vector field)** 라고 한다. $F(\bf{p})$ 의 $i$ 번째 성분을 $f_i(\bf{p})$ 로 표기한다.

$F,\,G$ 가 벡터장이고 $f:\R^n \to \R$ 함수일 때 연산을 아래와 같이 정의한다.

$$
\begin{aligned}
(F+G)(\bf{p}) &:= F(\bf{p}) + F(\bf{p}), \\[0.3em]
\langle F,\, G\rangle (\bf{p}) &: = \langle F(\bf{p}),\, G(\bf{p})\rangle, \\[0.3em]
(f\cdot F)(\bf{p}) &:= f(\bf{p})F(\bf{p}), \\[0.3em]
(F \times \cdots \times G) (\bf{p}) &:= F(\bf{p})\times \cdots \times G(\bf{p}).
\end{aligned}
$$

::: 
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_divergence_and_curl}

#### Divergence 와 Curl

$\R^n$ 에서의 벡터장 $F$ 에 대해 $\sum_{i=1}^n D_i F_i(\bf{p})$ 를 $F$ 에 대한 **divergence** 라고 하며 $\nabla \cdot F$ 혹은 $\text{div} \,F$ 로 표기한다. 

$\R^3$ 에서의 $\text{curl}\,F$ 는 아래와 같이 정의된다.

$$
\text{curl}\, F(\bf{p}) := (D_2f_3 - D_3f_2)(\bf{e}_1)_\bf{p} + (D_3f_1 - D_1f_3)(\bf{e}_2)_\bf{p} + (D_1f_2-D_2f_1)(\bf{e}_3)_\bf{p}
$$

::: 
:::

$\R^n$ 에서 nabla 연산자 $\nabla$ 를 아래와 같이 정의한다.

$$
\nabla := \sum_{i=1}^n \bf{e}_i \bf{\cdot}D_i.
$$

Nabla 연산자를 이용하여 $\text{div}\,F$ 를 $\nabla \bf{\cdot}F$ 로 $\text{curl}\, F$ 를 $\nabla \times F$ 로 표기하기도 한다.

</br>

$\R^n$ 과 $(\R^n)_\bf{p}$, 벡터함수와 벡터장과 같이 탄젠트 공간에서 정의된 $k$-form 을 정의 할 수 있다.


::: {.callout-note appearance="simple" icon="false"}
::: {#def-CM_differential_form}

#### 미분 형식

$\omega (p)\in \mathcal{A}^k({\R^n}_\bf{p})$ 를 $\R^n$ 에서의 $k$-형식, 혹은 **미분 형식(diffential form)** 이라고 한다. 표준 기저 $(\bf{e}_i)_\bf{p}$ 에 대한 쌍대 기저를 $\varphi_i (\bf{p})$ 라고 할 때 $k$-형식 $\omega(\bf{p})은 아래의 형태이다.

$$
\omega(\bf{p}) = \sum_{i_1<\cdots <i_k} a_{i_1,\ldots,\,i_k}(\bf{p})\cdot \left[\varphi_{i_1}(\bf{p}) \wedge \cdots \wedge \varphi_{i_k}(\bf{p})\right]
$$

::: 
:::